package com.vibhu.sapi.enums;

public enum HarnessState {
  RECEIVED,
  AUTHORIZED,
  CONTEXT_BUILT,
  MODEL_CALLED,
  TOOL_CALLING,
  TOOL_RESULTS_VALIDATED,
  RAG_RETRIEVED,
  OUTPUT_VALIDATED,
  APPROVAL_REQUIRED,
  COMPLETED,
  FAILED,
  ESCALATED
}
