server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: msp
    password: msp
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

msp:
  payment:
    fail-threshold: 10000
  outbox:
    relay-interval-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [cid=%X{correlationId}] - %msg%n"
