# Real Postgres + Redis + Kafka
spring:
  autoconfigure:
    exclude: []
  datasource:
    url: ${MT_DB_URL:jdbc:postgresql://127.0.0.1:5434/multitenant}
    username: ${MT_DB_USER:mt}
    password: ${MT_DB_PASSWORD:mt}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6380}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:127.0.0.1:9094}
    consumer:
      group-id: multitenant-order-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
    producer:
      acks: all
      properties:
        enable.idempotence: true

multitenant:
  kafka:
    enabled: true
  redis:
    enabled: true
