import type {TocItem} from './types';

export const ENCRYPTION_TOC: TocItem[] = [
  {id: 'overview', label: 'Big Picture · Payment Data'},
  {id: 'encoding-vs-encryption', label: 'Encoding vs Encryption'},
  {id: 'decision-matrix', label: 'Decision Matrix'},
  {id: 'aes', label: 'AES'},
  {id: 'aes-gcm', label: 'AES-GCM'},
  {id: 'rsa', label: 'RSA'},
  {id: 'signatures', label: 'Signatures · HMAC'},
  {id: 'ecc', label: 'ECC'},
  {id: 'hybrid', label: 'Hybrid Encryption'},
  {id: 'envelope', label: 'Envelope Encryption'},
  {id: 'spring-boot', label: 'Spring Boot Crypto'},
  {id: 'db-encryption', label: 'DB Encryption'},
  {id: 'searchable', label: 'Searchable Encryption'},
  {id: 'tls', label: 'TLS'},
  {id: 'jwt', label: 'JWT'},
  {id: 'kms', label: 'KMS'},
  {id: 'keystore', label: 'Keystore'},
  {id: 'key-rotation', label: 'Key Rotation'},
  {id: 'multi-tenant', label: 'Multi-Tenant Keys'},
  {id: 'algorithm-comparison', label: 'Algorithm Comparison'},
  {id: 'mistakes', label: 'Production Mistakes'},
  {id: 'testing', label: 'Testing'},
  {id: 'performance', label: 'Performance'},
  {id: 'payment-e2e', label: 'Payment E2E'},
  {id: 'threats', label: 'Threats'},
  {id: 'interview', label: 'Interview Qs'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'checklist', label: 'Production Checklist'},
  {id: 'cheat-sheet', label: 'Cheat Sheet'},
];
