import type {TocItem} from './types';

export const ENCRYPTION_TOC: TocItem[] = [
  {id: 'overview', label: 'Big Picture · Payment Data', group: 'Start here'},
  {id: 'famous-algorithms', label: 'Famous Algorithms · 5 Rooms', group: 'Start here'},
  {id: 'code-sequences', label: 'E2E Sequence Diagrams', group: 'Start here'},
  {id: 'encoding-vs-encryption', label: 'Encoding vs Encryption', group: 'Deep dives'},
  {id: 'decision-matrix', label: 'Decision Matrix', group: 'Deep dives'},
  {id: 'aes', label: 'AES', group: 'Deep dives'},
  {id: 'aes-gcm', label: 'AES-GCM', group: 'Deep dives'},
  {id: 'rsa', label: 'RSA', group: 'Deep dives'},
  {id: 'signatures', label: 'Signatures · HMAC', group: 'Deep dives'},
  {id: 'ecc', label: 'ECC', group: 'Deep dives'},
  {id: 'hybrid', label: 'Hybrid Encryption', group: 'Deep dives'},
  {id: 'envelope', label: 'Envelope Encryption', group: 'Deep dives'},
  {id: 'spring-boot', label: 'Spring Boot Crypto', group: 'Deep dives'},
  {id: 'db-encryption', label: 'DB Encryption', group: 'Deep dives'},
  {id: 'searchable', label: 'Searchable Encryption', group: 'Deep dives'},
  {id: 'tls', label: 'TLS', group: 'Deep dives'},
  {id: 'jwt', label: 'JWT', group: 'Deep dives'},
  {id: 'kms', label: 'KMS', group: 'Deep dives'},
  {id: 'keystore', label: 'Keystore', group: 'Deep dives'},
  {id: 'key-rotation', label: 'Key Rotation', group: 'Deep dives'},
  {id: 'multi-tenant', label: 'Multi-Tenant Keys', group: 'Deep dives'},
  {id: 'algorithm-comparison', label: 'Algorithm Comparison', group: 'Deep dives'},
  {id: 'mistakes', label: 'Production Mistakes', group: 'Deep dives'},
  {id: 'testing', label: 'Testing', group: 'Deep dives'},
  {id: 'performance', label: 'Performance', group: 'Deep dives'},
  {id: 'payment-e2e', label: 'Payment E2E', group: 'Deep dives'},
  {id: 'threats', label: 'Threats', group: 'Deep dives'},
  {id: 'interview', label: 'Interview Qs', group: 'Close'},
  {id: 'lab', label: 'Runnable Lab', group: 'Close'},
  {id: 'checklist', label: 'Production Checklist', group: 'Close'},
  {id: 'cheat-sheet', label: 'Cheat Sheet', group: 'Close'},
];
