import type {Incident} from './types';

export const INCIDENTS: Incident[] = [
  {
    id: 'i1',
    title: 'Suddenly millions of 429 responses',
    symptom: '429 rate jumps from <1% to 40% cluster-wide; customers cannot pay.',
    investigation: 'Break down by policy/tenant/route. Check recent config deploys, Redis errors, gateway rules.',
    rootCause: 'Often a bad config tighten, Redis fail-closed storm, or gateway WAF overlapping app limits.',
    fix: 'Rollback policy or widen temporarily; if Redis is sick, restore Redis first — raising limits will not help.',
    prevention: 'Shadow-limit before enforce; config canary; page on reject storms for money routes.',
  },
  {
    id: 'i2',
    title: 'Redis CPU reaches 100%',
    symptom: 'EVAL latency climbs; app p99 follows; some pods timeout.',
    investigation: 'redis-cli --hotkeys / MEMORY / COMMANDSTATS; identify celebrity tenant keys.',
    rootCause: 'Hot key or oversized Lua/scripts; too many keys with sliding-log ZSETs.',
    fix: 'Gateway pre-limit hot tenant; shard key; switch hot paths to O(1) bucket; scale cluster.',
    prevention: 'Hot-key alerts; forbid sliding-log on high-RPS keys; hierarchical limits.',
  },
  {
    id: 'i3',
    title: 'Redis latency 1ms → 100ms',
    symptom: 'API latency tracks Redis; thread pools fill.',
    investigation: 'Slowlog, network, cross-AZ calls, noisy neighbor, AOF fsync.',
    rootCause: 'Cross-AZ Redis, disk-bound persistence, or CPU saturation.',
    fix: 'Co-locate AZ; tighten timeouts; circuit-break; fail policy; fix Redis infra.',
    prevention: 'p99 Redis SLO alerts; never call Redis without timeout.',
  },
  {
    id: 'i4',
    title: 'One tenant consumes all capacity',
    symptom: 'Global/region limits trip; other tenants starved at gateway.',
    investigation: 'Top tenants by RPS; check missing tenant keys (fell through to global only).',
    rootCause: 'Missing per-tenant policy or shared global key only.',
    fix: 'Enforce tenant buckets; temporary block; raise global carefully.',
    prevention: 'Mandatory tenant dimension for multi-tenant SaaS; fairness tiers.',
  },
  {
    id: 'i5',
    title: 'Limiter allows more than configured',
    symptom: 'Traffic exceeds plan; downstream saturates despite “100/s”.',
    investigation: 'Count app instances × local AtomicInteger; check Redis vs memory mode; multi-region double-count.',
    rootCause: 'Per-JVM limiter mistaken for distributed; or GET+SET race; or regional independent Redis.',
    fix: 'Move to Redis Lua; fix race; document regional approx.',
    prevention: 'Concurrency test; integration test against Redis; architecture review checklist.',
  },
  {
    id: 'i6',
    title: 'Legitimate traffic rejected',
    symptom: 'Good customers hit 429 under normal load.',
    investigation: 'Identity key wrong (shared NAT IP); limit too low; clock skew refill; stacked gateway+app.',
    rootCause: 'IP-only keys behind CGNAT; or double enforcement without budget split.',
    fix: 'Key by user/API key; raise quota; coordinate edge vs app budgets.',
    prevention: 'Authenticate then limit; publish remaining headers; load-test plans.',
  },
  {
    id: 'i7',
    title: 'Redis failover',
    symptom: 'Brief error spike; possible tiny over/under admit.',
    investigation: 'Cluster/Sentinel events; replication lag; app error logs.',
    rootCause: 'Primary failover; async replication may lose last writes.',
    fix: 'Accept brief errors under fail policy; WAIT only if product needs it (latency cost).',
    prevention: 'Multi-AZ replicas; rehearsal of failover; fail policy tested.',
  },
  {
    id: 'i8',
    title: 'One API instance behaves differently',
    symptom: 'Only pod-3 returns 429 more often.',
    investigation: 'Compare config version, Redis endpoint, local fallback state, clock.',
    rootCause: 'Stale config map; wrong Redis; local pre-limiter drift; skewed clock.',
    fix: 'Redeploy/refresh config; fix NTP; align Redis client config.',
    prevention: 'Config version metric; clock offset monitors.',
  },
  {
    id: 'i9',
    title: 'Multi-region violates “global” limit',
    symptom: 'us-east + eu-west each allow 100K → 200K global.',
    investigation: 'Confirm regional Redis; no cross-region coordination.',
    rootCause: 'Regional approximate design treated as hard global.',
    fix: 'Clarify product: regional quotas or slower central global ledger for hard caps.',
    prevention: 'Never claim hard global with independent regional Redis.',
  },
  {
    id: 'i10',
    title: 'Retry storm after 429',
    symptom: '429 → immediate retry loops → worse 429 and Redis load.',
    investigation: 'Client SDKs without backoff; missing Retry-After respect.',
    rootCause: 'Clients retry immediately; no jitter; unlimited attempts.',
    fix: 'Enforce Retry-After; exponential backoff + jitter; max retries; gateway connection limits.',
    prevention: 'Publish SDK defaults; chaos-test clients.',
  },
  {
    id: 'i11',
    title: 'Hot Redis key',
    symptom: 'One hash slot CPU-bound; others idle.',
    investigation: 'Hot keys; tenant celebrity event.',
    rootCause: 'Single key for millions of RPS.',
    fix: 'Shard key into N; local fractional buckets; gateway cap.',
    prevention: 'Hierarchical limits; load tests with hot tenant.',
  },
  {
    id: 'i12',
    title: 'Memory leak from client identifiers',
    symptom: 'In-memory ConcurrentHashMap grows without bound.',
    investigation: 'Heap dump; key cardinality of ephemeral IPs.',
    rootCause: 'No TTL/eviction on local map; bot IP churn.',
    fix: 'Caffeine TTL; bound size; prefer Redis with PEXPIRE.',
    prevention: 'Cardinality budgets; eviction tests.',
  },
  {
    id: 'i13',
    title: 'Clock skew wrong refill',
    symptom: 'Some pods refill faster; quota stolen.',
    investigation: 'Compare pod clocks; Lua using ARGV now from app.',
    rootCause: 'Fast wall clock / NTP step; client-supplied time.',
    fix: 'Redis TIME in Lua; clamp negative elapsed; NTP.',
    prevention: 'Never trust client device clocks.',
  },
  {
    id: 'i14',
    title: 'Deploy resets local rate limits',
    symptom: 'After rollout, burst of allowed traffic then settles.',
    investigation: 'Local maps emptied on restart.',
    rootCause: 'Relying on in-memory as source of truth.',
    fix: 'Redis-backed quotas; expect brief local pre-limiter reset.',
    prevention: 'Document local as approximation only.',
  },
  {
    id: 'i15',
    title: 'Redis network partition',
    symptom: 'Some AZs cannot reach Redis; mixed allow/deny.',
    investigation: 'Network ACLs, security groups, AZ failure.',
    rootCause: 'Partition between app and Redis primary.',
    fix: 'Fail policy; promote replica if appropriate; do not dual-write two primaries.',
    prevention: 'Multi-AZ Redis; rehearse partitions; CAP-aware messaging.',
  },
  {
    id: 'i16',
    title: 'Gateway and service conflicting limits',
    symptom: 'Users confused: sometimes edge 429, sometimes app 429 with different numbers.',
    investigation: 'Compare WAF/API-GW quotas vs Redis policies.',
    rootCause: 'Uncoordinated budgets; both claim to be “the” limit.',
    fix: 'Split roles: edge = flood protection; app = product quotas; document headers.',
    prevention: 'Single ownership matrix for each dimension.',
  },
];

export const ANTI_PATTERNS: {title: string; why: string; instead: string}[] = [
  {
    title: 'Local AtomicInteger per instance as global limit',
    why: 'N instances ⇒ N× quota. Classic interview fail.',
    instead: 'Shared Redis/Lua (or gateway) for global identity quotas.',
  },
  {
    title: 'PostgreSQL UPDATE for every request',
    why: 'Row locks, latency, DB becomes the bottleneck you were protecting.',
    instead: 'Redis O(1) state; DB only for durable policy config.',
  },
  {
    title: 'GET then SET from Java',
    why: 'Race: two threads read 1 token, both admit.',
    instead: 'Lua EVAL / Redis 7 function / atomic script.',
  },
  {
    title: 'No TTL on keys',
    why: 'Abandoned identities fill Redis forever.',
    instead: 'PEXPIRE ≥ 2× window; monitor memory.',
  },
  {
    title: 'No client identity strategy',
    why: 'IP-only behind NAT; spoofable headers.',
    instead: 'JWT/API key principal + optional IP for unauth.',
  },
  {
    title: 'No Redis timeout',
    why: 'Slow Redis holds app threads → cascade.',
    instead: 'Few-ms timeouts + circuit breaker.',
  },
  {
    title: 'No failure policy',
    why: 'On-call invents fail-open/closed during the incident.',
    instead: 'Per-route FAIL_OPEN / FAIL_CLOSED / LOCAL_FALLBACK.',
  },
  {
    title: 'Unlimited retry after 429',
    why: 'Retry storm amplifies overload.',
    instead: 'Retry-After, exponential backoff + jitter, max attempts.',
  },
  {
    title: 'Only IP-based limiting',
    why: 'Bots rotate IPs; corporate NAT collapses many users.',
    instead: 'User + API key + tenant (+ IP as secondary).',
  },
  {
    title: 'One global Redis key',
    why: 'Hot key melts one shard; no fairness.',
    instead: 'Hierarchical keys; shard celebrities.',
  },
  {
    title: 'Log every rejected request at INFO',
    why: 'Disk/CPU storm during attacks.',
    instead: 'Sampled logs + metrics; DEBUG sampling.',
  },
  {
    title: 'No observability',
    why: 'Cannot tell plan hits from Redis sickness.',
    instead: 'allowed/rejected/latency/redis_errors/hot_keys dashboards.',
  },
];
