import type {InterviewQ} from './types';

export const SENIOR: InterviewQ[] = [
  {
    id: 's1',
    topic: 'Requirements',
    question: 'What does a distributed rate limiter actually guarantee?',
    answer30s: 'A shared, approximately global quota so N app servers cannot grant N× the limit.',
    answer2m: 'Per identity and route we admit or reject with remaining tokens and Retry-After. Consistency is single-key atomic in Redis, not multi-region linearizability. Availability is a declared fail policy, not “Redis never dies”.',
    followUps: ['What is not guaranteed?'],
    trick: 'Saying every region shares one perfectly consistent counter.',
  },
  {
    id: 's2',
    topic: 'Algorithm',
    question: 'Walk token bucket vs fixed window vs leaky bucket.',
    answer30s: 'Fixed window INCR + boundary 2×. Token bucket burst+refill. Leaky bucket smooths and hates bursts.',
    answer2m: 'I pick token bucket: capacity is burst, refillRate/period is sustained, Retry-After is deficit/rate, memory O(1). Sliding log is more accurate and too expensive per hot key. Sliding counter is the cheap approx alternative at 1M RPS.',
    followUps: ['When leaky?'],
  },
  {
    id: 's3',
    topic: 'Redis',
    question: 'Why Lua?',
    answer30s: 'Refill and consume must be one atomic operation on one key.',
    answer2m: 'GET tokens then SET from Java races: two pods read 1 token and both admit. EVAL runs on the primary, single-threaded per shard. Cluster: one KEY so no CROSSSLOT. TTL via PEXPIRE.',
    followUps: ['WATCH/MULTI instead?'],
    trick: 'INCR alone is a token bucket.',
  },
  {
    id: 's4',
    topic: 'Placement',
    question: 'Gateway vs application rate limiting?',
    answer30s: 'Both. Gateway for unauth floods; app library for JWT identity and per-API quotas.',
    answer2m: 'Gateway does not see stable user ids before auth and cannot easily do tenant+API product quotas. A central limiter service adds a hop that blows a 5ms SLO unless it is local. Platform library + Redis is the usual Staff answer.',
    followUps: ['Sidecar?'],
  },
  {
    id: 's5',
    topic: 'Failure',
    question: 'Redis is down. What do you do?',
    answer30s: 'Per-route: fail-open, fail-closed, or local fallback. Never a surprise.',
    answer2m: 'Payments fail-closed (429/503). Public reads fail-open briefly with a screaming alert. Internal workers use a local bucket so the mesh does not stall. Timeouts must be milliseconds.',
    followUps: ['Slow Redis vs down?'],
    trick: 'Always fail-open “because availability”.',
  },
  {
    id: 's6',
    topic: 'HTTP',
    question: 'What do you return on reject?',
    answer30s: '429, Retry-After, X-RateLimit-Limit/Remaining/Reset.',
    answer2m: 'Do not 401 (auth) or 403 (authz). Body can include policy id. Remaining is 0. Reset is when a token should exist.',
    followUps: ['503 vs 429?'],
  },
  {
    id: 's7',
    topic: 'Multi-level',
    question: 'How do global + tenant + user limits compose?',
    answer30s: 'AND. Fail-fast sequential EVAL per key.',
    answer2m: 'A request needs a token from every matching policy. We do not MULTI across hash slots. Outer reject skips inner spend — a documented trade-off. Headers expose the tightest remaining on allow, the failing policy on reject.',
    followUps: ['Atomic AND?'],
  },
  {
    id: 's8',
    topic: 'Config',
    question: 'Change 100/min to 20/min without restart?',
    answer30s: 'Admin API writes the policy map; next allow() reads it. Redis bucket refills at the new rate.',
    answer2m: 'Prod: DB source of truth + Kafka fan-out to pods. Lab: ConcurrentHashMap upsert + factory evict. Existing tokens are not magically topped up; they refill toward the new capacity.',
    followUps: ['Poison config?'],
  },
  {
    id: 's9',
    topic: 'Security',
    question: 'Can a user bypass limits by switching IPs?',
    answer30s: 'If the key is userId from the API key/JWT, no. IP-only keys yes.',
    answer2m: 'Authenticate first. Rate-limit the authenticated principal and the API key. IP is a secondary signal for unauth endpoints. Tenant isolation is a key prefix, not a header the client chooses alone.',
    followUps: ['API-key sharing?'],
  },
  {
    id: 's10',
    topic: 'Scale',
    question: 'Hot key for a celebrity tenant?',
    answer30s: 'One slot melts. Pre-limit locally, hierarchy, or shard the key.',
    answer2m: 'Gateway caps the tenant. App local bucket of a few percent. Split tenant into N Redis keys and approximate. Separate cluster for payments. Alert hot_keys before CPU sits at 100%.',
    followUps: ['Hash tags making it worse?'],
  },
];

export const ARCHITECT: InterviewQ[] = [
  {
    id: 'a1',
    topic: 'Scale',
    question: 'Design for 1M RPS.',
    answer30s: 'Regional Redis, local admission, hierarchical keys, isolate money paths, edge enforcement.',
    answer2m: 'Do not funnel 1M EVAL to one primary. Partition by region (eventual global). Local token buckets absorb bursts and cut Redis QPS. Sliding counter for the coarsest global key if O(1) still too hot. Payment Redis is a different failure domain.',
    followUps: ['Multi-region quota product?'],
    trick: 'One global Redis Cluster in us-east-1 for the world.',
  },
  {
    id: 'a2',
    topic: 'Consistency',
    question: 'Is the limiter linearizable?',
    answer30s: 'Per key, yes, on one Redis primary. Across regions, no.',
    answer2m: 'Lua on a primary is linearizable for that key. Async replication can lose a few tokens on failover — usually acceptable. Dual-write two regions will over-admit. If finance needs a hard global cap, that is a slower centralized service, not this hot path.',
    followUps: ['WAIT / synchronous replication?'],
  },
  {
    id: 'a3',
    topic: 'Cluster',
    question: 'Explain hash slots, hot partitions, failover.',
    answer30s: '16384 slots, key CRC16, primary per slot, replica failover, MOVED redirects.',
    answer2m: 'Hash-tag {tenant} pins related keys to one slot — good for multi-key Lua, bad if that tenant is hot. Failover: replica promoted, brief unavailability, possible tiny token loss if async. Two primaries for one key is split-brain — fail closed.',
    followUps: ['Why 16384?'],
  },
  {
    id: 'a4',
    topic: 'Product',
    question: 'Quotas are a product contract. What does that change?',
    answer30s: 'Version policies, explain 429s, do not silently tighten in an incident.',
    answer2m: 'Plans (free/pro) map to policy packs. Abuse blocks are explicit. Config changes audit-logged. Customer-visible remaining quota must match enforcement. Shadow-limit before enforcing a new default.',
    followUps: ['Who owns a bad config?'],
  },
  {
    id: 'a5',
    topic: 'Obs',
    question: 'What do you page on?',
    answer30s: 'Reject storms on payments, Redis p99, error rate, fail-open volume, unconfigured requests.',
    answer2m: 'Dashboards by policy/tenant. Distinguish “customers hitting their plan” from “limiter or Redis is sick”. Trace allow() with policy ids. Alert when degraded allows exceed a budget during an incident.',
    followUps: ['Cardinality of tenant labels?'],
  },
  {
    id: 'a6',
    topic: 'Library',
    question: 'Central limiter service vs library?',
    answer30s: 'Library + Redis for latency. Service only if many languages and you can afford the hop.',
    answer2m: 'A gRPC limiter in another DC will miss 5–10ms. A local sidecar on localhost can work (Envoy ratelimit). Staff default: blessed Spring library, Redis contract, gateway for coarse limits.',
    followUps: ['Polyglot org?'],
  },
  {
    id: 'a7',
    topic: 'Clock',
    question: 'Who owns “now” in Lua?',
    answer30s: 'Prefer Redis TIME; if ARGV now, NTP + clamp negative elapsed.',
    answer2m: 'Fast app clocks refill faster and steal quota. Lab passes clock.millis() for testability and clamps elapsed < 0. Production Lua can call redis.call(\'TIME\').',
    followUps: ['Leap seconds?'],
  },
  {
    id: 'a8',
    topic: 'Abuse',
    question: 'Block a bad client vs throttle?',
    answer30s: 'blocked=true policy with huge Retry-After, plus WAF/API-key revoke.',
    answer2m: 'Throttle (low refill) keeps them in the system for forensics. Block is a separate policy. Authn still required — rate limit is not a substitute for kicking the key. Tenant isolation so one client cannot starve siblings except via the shared tenant bucket (intended).',
    followUps: ['Legal hold on logs?'],
  },
  {
    id: 'a9',
    topic: 'Testing',
    question: 'What test proves the design?',
    answer30s: 'N threads, capacity C, refill ≈ 0, allowed == C.',
    answer2m: 'Also refill after advancing a fake clock, multi-tenant isolation, fail-open/closed, config upsert, mocked Lua payload, Testcontainers Redis if Docker exists. Web test for 429 headers.',
    followUps: ['Chaos Redis?'],
  },
  {
    id: 'a10',
    topic: 'R4j',
    question: 'Is Resilience4j RateLimiter this system?',
    answer30s: 'No. R4j is per-JVM. This is the global Redis quota.',
    answer2m: 'R4j is excellent for protecting a dependency from one instance. HPA multiplies local limiters. Staff interview: say both layers — R4j bulkhead/RL locally, Redis token bucket globally, gateway at the edge.',
    followUps: ['Where does the lab live vs /resilience4j?'],
    trick: 'Configuring R4j 100/s and calling it a distributed limiter.',
  },
];

export const RAPID: InterviewQ[] = [
  {id: 'r1', topic: 'Rapid', question: 'HTTP status when over quota?', answer30s: '429', answer2m: 'Retry-After + X-RateLimit-*', followUps: ['Not 401']},
  {id: 'r2', topic: 'Rapid', question: 'Lab port?', answer30s: '8098', answer2m: 'mvn spring-boot:run', followUps: ['Bloom was 8097']},
  {id: 'r3', topic: 'Rapid', question: 'Why Lua?', answer30s: 'Atomic refill+consume', answer2m: 'Single key EVAL', followUps: ['CROSSSLOT?']},
  {id: 'r4', topic: 'Rapid', question: 'Payments Redis down?', answer30s: 'Fail closed', answer2m: 'Public GET fail open', followUps: ['Local fallback?']},
  {id: 'r5', topic: 'Rapid', question: '10 servers local limit 100?', answer30s: '1000 cluster', answer2m: 'Need Redis/GW', followUps: ['R4j?']},
  {id: 'r6', topic: 'Rapid', question: 'Burst vs sustained?', answer30s: 'capacity vs refillRate', answer2m: '100/min + burst 20 → cap 120', followUps: ['Leaky?']},
  {id: 'r7', topic: 'Rapid', question: 'Key shape?', answer30s: 'rate_limit:{tenant}:scope:id', answer2m: 'Hash-tag tenant', followUps: ['Hot tag?']},
  {id: 'r8', topic: 'Rapid', question: 'Fixed window bug?', answer30s: '2× at boundary', answer2m: 'Use bucket or sliding', followUps: ['Log vs counter']},
  {id: 'r9', topic: 'Rapid', question: 'Who is “now”?', answer30s: 'Redis TIME or NTP', answer2m: 'Clamp negative elapsed', followUps: ['Client clock?']},
  {id: 'r10', topic: 'Rapid', question: 'Reject header name?', answer30s: 'Retry-After', answer2m: 'Seconds to wait', followUps: ['Reset header']},
];

export const ALL: InterviewQ[] = [...SENIOR, ...ARCHITECT, ...RAPID];
