import type {TocItem} from './types';

/** Staff/Principal rate-limiter interview board — mirrors the production design doc outline. */
export const RATE_LIMIT_TOC: TocItem[] = [
  {id: 'lab', label: '00. Runnable lab'},
  {id: 'problem', label: '01. Problem statement'},
  {id: 'why', label: '02. Why rate limiting'},
  {id: 'definition', label: '03. Definition & cousins'},
  {id: 'requirements', label: '04. Requirements'},
  {id: 'algorithms', label: '05. Algorithms'},
  {id: 'selection', label: '06. Algorithm selection'},
  {id: 'hld', label: '07. High-level design'},
  {id: 'placement', label: '08. Where it lives'},
  {id: 'lld', label: '09. LLD & patterns'},
  {id: 'java', label: '10. Java token bucket'},
  {id: 'spring', label: '11. Spring Boot filter'},
  {id: 'redis', label: '12. Redis design'},
  {id: 'lua', label: '13. Lua atomicity'},
  {id: 'distributed', label: '14. Distributed limits'},
  {id: 'hotkeys', label: '15. Hot keys'},
  {id: 'multiregion', label: '16. Multi-region'},
  {id: 'failure', label: '17. Failure handling'},
  {id: 'retry', label: '18. Retry + backoff'},
  {id: 'resilience', label: '19. CB · Kafka · DB'},
  {id: 'aws', label: '20. AWS architecture'},
  {id: 'security', label: '21. Security'},
  {id: 'observability', label: '22. Observability'},
  {id: 'capacity', label: '23. Capacity & perf'},
  {id: 'testing', label: '24. Load & unit tests'},
  {id: 'incidents', label: '25. Production incidents'},
  {id: 'antipatterns', label: '26. Anti-patterns'},
  {id: 'diagrams', label: '27. Mermaid diagrams'},
  {id: 'payment', label: '28. Payment system'},
  {id: 'config', label: '29. Dynamic config · fairness'},
  {id: 'answers', label: '30. 5-min · 30-sec · cheat'},
  {id: 'interview', label: '31. Interview bank'},
];
