import type {TocItem} from './types';

/** Unified Kafka DLQ/DLT + Retry + Payments + Hadron + Staff production deep. */
export const KAFKA_DLQ_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview & version'},
  {id: 'gap-score', label: '00b. Gap scorecard'},
  {id: 'fundamentals', label: '01. DLQ fundamentals'},
  {id: 'terms', label: '02. DLQ vs DLT vs retry'},
  {id: 'why', label: '03. Why DLQ · failure categories'},
  {id: 'classify', label: '04. Failure classification'},
  {id: 'architecture', label: '05. Basic DLT architecture'},
  {id: 'retry-strategies', label: '06. Retry strategies'},
  {id: 'retry-topics', label: '07. Retry topics · delayed retry'},
  {id: 'spring', label: '08. Spring Kafka DLT'},
  {id: 'error-handler', label: '09. DefaultErrorHandler'},
  {id: 'recoverer', label: '10. DeadLetterPublishingRecoverer'},
  {id: 'retryable', label: '11. @RetryableTopic'},
  {id: 'rollback', label: '12. AfterRollback · transactions'},
  {id: 'blocking', label: '13. Blocking vs non-blocking'},
  {id: 'ordering', label: '14. Ordering · partitions'},
  {id: 'offsets', label: '15. Offset management · races'},
  {id: 'semantics', label: '16. ALO · DLT publish failure'},
  {id: 'headers', label: '17. Headers · envelope · schema'},
  {id: 'deser', label: '18. Serialization · SR failures'},
  {id: 'exceptions', label: '19. Exception matrix'},
  {id: 'poison', label: '20. Poison · storms · circuit breaker'},
  {id: 'topic-ops', label: '21. Retention · capacity · naming'},
  {id: 'security', label: '22. Security · privacy · governance'},
  {id: 'obs', label: '23. Observability · alerts'},
  {id: 'replay', label: '24. Replay · idempotency'},
  {id: 'ops', label: '25. Ops · incident · SLO'},
  {id: 'payments', label: '26. Payments DLT · runnable demo'},
  {id: 'batch', label: '27. Batch · ack · rebalance'},
  {id: 'corners', label: '28. Corner cases (generic)'},
  {id: 'hadron-story', label: '29. Hadron CashLines case study'},
  {id: 'hadron-sequences', label: '30. Hadron lifecycle sequences'},
  {id: 'hadron-corners', label: '31. Hadron corner cases (35)'},
  {id: 'hadron-domain', label: '32. Neptune · state machine · DLQ DB'},
  {id: 'labs', label: '33. Runnable labs'},
  {id: 'antipatterns', label: '34. Anti-patterns · Hadron mistakes'},
  {id: 'decisions', label: '35. Decision trees · master arch'},
  {id: 'interview', label: '36. Interview & cheat sheets'},
  {id: 'producer-failures', label: '37. Producer failures ≠ consumer DLQ'},
  {id: 'patterns-deep', label: '38. Patterns A–E · comparison'},
  {id: 'dlt-publish-fail', label: '39. DLT publish failure · offsets'},
  {id: 'rebalance-batch-deser', label: '40. Rebalance · batch · deser deep'},
  {id: 'eos-db', label: '41. Kafka EOS vs PostgreSQL'},
  {id: 'replay-loops', label: '42. Replay loops · envelope · schema'},
  {id: 'multi-ops', label: '43. Multi-service · region · capacity'},
  {id: 'payment-reconcile', label: '44. Payment reconcile · safe replay'},
  {id: 'corner-matrix', label: '45. Corner-case matrix (50)'},
  {id: 'chaos-tests', label: '46. Failure-injection tests'},
  {id: 'staff-bank', label: '47. Staff Q bank · wrong answers'},
  {id: 'final-arch', label: '48. Final architecture · cheat sheet'},
];
