import type {TocItem} from './types';

/** Maps the Kafka DLQ/DLT + retry + recovery master curriculum into navigable boards. */
export const KAFKA_DLQ_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview & version'},
  {id: 'fundamentals', label: '01. DLQ fundamentals'},
  {id: 'terms', label: '02. DLQ vs DLT vs retry'},
  {id: 'why', label: '03. Why DLQ · failure categories'},
  {id: 'classify', label: '04. Failure classification'},
  {id: 'architecture', label: '05. Basic DLT architecture'},
  {id: 'retry-strategies', label: '06. Retry strategies'},
  {id: 'retry-topics', label: '07. Retry topics · delayed retry'},
  {id: 'spring', label: '08. Spring Kafka DLT'},
  {id: 'error-handler', label: '09. DefaultErrorHandler'},
  {id: 'recoverer', label: '10. DeadLetterPublishingRecoverer'},
  {id: 'retryable', label: '11. @RetryableTopic'},
  {id: 'rollback', label: '12. AfterRollback · transactions'},
  {id: 'blocking', label: '13. Blocking vs non-blocking'},
  {id: 'ordering', label: '14. Ordering · partitions'},
  {id: 'offsets', label: '15. Offset management · races'},
  {id: 'semantics', label: '16. ALO · DLT publish failure'},
  {id: 'headers', label: '17. Headers · envelope · schema'},
  {id: 'deser', label: '18. Serialization · SR failures'},
  {id: 'exceptions', label: '19. Exception matrix'},
  {id: 'poison', label: '20. Poison · storms · circuit breaker'},
  {id: 'topic-ops', label: '21. Retention · capacity · naming'},
  {id: 'security', label: '22. Security · privacy · governance'},
  {id: 'obs', label: '23. Observability · alerts'},
  {id: 'replay', label: '24. Replay · idempotency'},
  {id: 'ops', label: '25. Ops · incident · SLO'},
  {id: 'payments', label: '26. Payments DLT'},
  {id: 'batch', label: '27. Batch · ack · rebalance'},
  {id: 'corners', label: '28. Corner cases'},
  {id: 'antipatterns', label: '29. Anti-patterns'},
  {id: 'decisions', label: '30. Decision trees · master arch'},
  {id: 'interview', label: '31. Interview & cheat sheets'},
];
