import type {IncidentScenario} from './types';

/** Compact playbook cards — each expands the mandatory incident chain in the UI. */
export const SCENARIOS: IncidentScenario[] = [
  {id:'s01',title:'Angular blank after deploy',layer:'Frontend',symptom:'White screen',impact:'All web users',firstCheck:'Console + Network chunks',mitigate:'Rollback FE + CDN invalidate',rootCause:'Broken bundle / ChunkLoadError',prevent:'Canary FE + smoke'},
  {id:'s02',title:'React infinite API calls',layer:'Frontend',symptom:'RPS spike from browser',impact:'Backend overload',firstCheck:'useEffect deps',mitigate:'Hotfix / flag / rollback FE',rootCause:'useEffect without []',prevent:'Lint exhaustive-deps'},
  {id:'s03',title:'CDN serving old JS',layer:'CDN',symptom:'ChunkLoadError',impact:'Post-deploy users',firstCheck:'Cache headers / invalidation',mitigate:'Invalidate + versioned assets',rootCause:'HTML/JS version skew',prevent:'Immutable hashed assets'},
  {id:'s04',title:'CORS failure',layer:'Frontend',symptom:'Blocked by CORS',impact:'Browser clients',firstCheck:'Preflight OPTIONS + ACAO',mitigate:'Fix gateway/app CORS config',rootCause:'Origin/header mismatch',prevent:'Env-specific CORS tests'},
  {id:'s05',title:'API Gateway 401',layer:'Gateway',symptom:'Unauthorized',impact:'Auth path',firstCheck:'Authorizer logs / token',mitigate:'Fix clock/issuer/keys',rootCause:'Token/authz config',prevent:'Auth canary'},
  {id:'s06',title:'API Gateway 403',layer:'Gateway',symptom:'Forbidden',impact:'Subset or all',firstCheck:'WAF/IAM/authorizer',mitigate:'Adjust deny rule carefully',rootCause:'Policy/WAF',prevent:'Change review'},
  {id:'s07',title:'API Gateway 429',layer:'Gateway',symptom:'Throttled',impact:'Bursty clients',firstCheck:'Usage plan metrics',mitigate:'Raise limit / shed / backoff client',rootCause:'Throttle ceiling',prevent:'Tenant quotas'},
  {id:'s08',title:'ALB 502',layer:'LB',symptom:'Bad Gateway',impact:'Intermittent/all',firstCheck:'Target reset / crash',mitigate:'Drain bad targets',rootCause:'Target connection failure',prevent:'Graceful shutdown'},
  {id:'s09',title:'ALB 503',layer:'LB',symptom:'Service Unavailable',impact:'Wide',firstCheck:'Healthy host count',mitigate:'Rollback / scale / fix health',rootCause:'No healthy targets',prevent:'Readiness tuning'},
  {id:'s10',title:'ALB 504',layer:'LB',symptom:'Gateway Timeout',impact:'Slow APIs',firstCheck:'Target p99 vs idle timeout',mitigate:'Shed load / rollback',rootCause:'Backend exceeds timeout',prevent:'Budget timeouts'},
  {id:'s11',title:'Spring API latency↑',layer:'Spring',symptom:'p95 200ms→5s',impact:'Payments slow',firstCheck:'Traces waterfall',mitigate:'Rollback / isolate dep',rootCause:'Slow span (often DB)',prevent:'Query SLOs'},
  {id:'s12',title:'Spring CPU spike',layer:'JVM',symptom:'CPU 95%',impact:'Latency+timeouts',firstCheck:'top→pid→jstack',mitigate:'Shed traffic',rootCause:'Hot loop/GC/traffic',prevent:'Profile in CI'},
  {id:'s13',title:'JVM memory leak',layer:'JVM',symptom:'Heap climb',impact:'Eventual OOM',firstCheck:'Heap trend + dump once',mitigate:'Restart rolling + fix',rootCause:'Retained objects',prevent:'Load test leak checks'},
  {id:'s14',title:'OOM',layer:'JVM',symptom:'OutOfMemoryError',impact:'Pod crash',firstCheck:'Heap dump / events',mitigate:'Rollback / raise carefully',rootCause:'Leak or undersized heap',prevent:'Limits + alerts'},
  {id:'s15',title:'Long GC',layer:'JVM',symptom:'Pause spikes',impact:'Tail latency',firstCheck:'GC logs/JFR',mitigate:'Reduce alloc / heap tune',rootCause:'Alloc/leak/config',prevent:'Allocation budgets'},
  {id:'s16',title:'Thread stuck',layer:'JVM',symptom:'Requests hang',impact:'Timeouts',firstCheck:'Thread dump stacks',mitigate:'Kill wait source / shed',rootCause:'Blocked on dep/lock',prevent:'Timeouts'},
  {id:'s17',title:'Thread starvation',layer:'JVM',symptom:'Queueing',impact:'504s',firstCheck:'Pool active=max',mitigate:'Load shed',rootCause:'All threads waiting',prevent:'Bulkheads'},
  {id:'s18',title:'Thread pool exhaustion',layer:'Spring',symptom:'Reject/queue',impact:'Errors',firstCheck:'Tomcat/Hikari metrics',mitigate:'Reduce RPS',rootCause:'Slow deps',prevent:'Do not only raise max'},
  {id:'s19',title:'Java deadlock',layer:'Core Java',symptom:'Hard hang subset',impact:'Stuck txs',firstCheck:'jcmd deadlock detect',mitigate:'Restart + fix order',rootCause:'Lock inversion',prevent:'Lock ordering'},
  {id:'s20',title:'Hikari pool exhausted',layer:'DB pool',symptom:'Connection timeout',impact:'API fail',firstCheck:'active/pending',mitigate:'Shed + kill slow queries',rootCause:'Slow SQL/leak',prevent:'Pool≠thread mismatch'},
  {id:'s21',title:'Slow SQL',layer:'Database',symptom:'Query seconds',impact:'p99↑',firstCheck:'EXPLAIN ANALYZE',mitigate:'Kill/limit query',rootCause:'Plan/scan',prevent:'Review new SQL'},
  {id:'s22',title:'Missing index',layer:'Database',symptom:'Seq scan',impact:'CPU+IO',firstCheck:'EXPLAIN',mitigate:'Add index online',rootCause:'New predicate unindexed',prevent:'Migration checklist'},
  {id:'s23',title:'DB lock contention',layer:'Database',symptom:'Blocked sessions',impact:'Latency',firstCheck:'pg_stat_activity',mitigate:'Kill blocker carefully',rootCause:'Long tx',prevent:'Short transactions'},
  {id:'s24',title:'DB deadlock',layer:'Database',symptom:'Deadlock detected',impact:'Retries/errors',firstCheck:'Deadlock logs',mitigate:'Retry idempotent',rootCause:'Lock order',prevent:'Consistent access order'},
  {id:'s25',title:'DB disk full',layer:'Database',symptom:'Writes fail',impact:'Outage',firstCheck:'df / free storage',mitigate:'Expand/free space',rootCause:'Growth/logs',prevent:'Disk alerts 80%'},
  {id:'s26',title:'Replication lag',layer:'Database',symptom:'Stale reads',impact:'Wrong balances',firstCheck:'Lag metrics',mitigate:'Read primary / pause replicas',rootCause:'Replica overload',prevent:'Lag SLOs'},
  {id:'s27',title:'Redis outage',layer:'Redis',symptom:'Timeouts',impact:'API degrade',firstCheck:'Redis health',mitigate:'Fail soft / bypass',rootCause:'Node/failover',prevent:'CB + soft depend'},
  {id:'s28',title:'Cache miss storm',layer:'Redis',symptom:'Hit ratio↓ DB↑',impact:'Cascade',firstCheck:'Hit ratio + DB QPS',mitigate:'Rate limit / stampede lock',rootCause:'Flush/expiry wave',prevent:'Singleflight'},
  {id:'s29',title:'Kafka consumer lag',layer:'Kafka',symptom:'Lag alert',impact:'Delayed money events',firstCheck:'Lag by partition',mitigate:'Scale consumers carefully',rootCause:'Slow consumer',prevent:'Processing SLOs'},
  {id:'s30',title:'Kafka rebalance storm',layer:'Kafka',symptom:'Frequent rebalance',impact:'Throughput drop',firstCheck:'Session/heartbeat',mitigate:'Stabilize membership',rootCause:'GC/network/misconfig',prevent:'Tuning + resources'},
  {id:'s31',title:'External API timeout',layer:'HTTP',symptom:'p99 = timeout',impact:'Feature fail',firstCheck:'Trace external span',mitigate:'CB open / fallback',rootCause:'Vendor slow',prevent:'Timeouts+CB'},
  {id:'s32',title:'Cascading microservices',layer:'Mesh',symptom:'Multi-service 5xx',impact:'Platform',firstCheck:'Deepest slow dep',mitigate:'Shed + CB',rootCause:'Thread propagation',prevent:'Bulkheads'},
  {id:'s33',title:'Retry storm',layer:'Resilience',symptom:'Traffic×N',impact:'Worse overload',firstCheck:'Retry metrics',mitigate:'Disable nested retries',rootCause:'Unbounded retry',prevent:'One retry owner'},
  {id:'s34',title:'Circuit breaker OPEN',layer:'Resilience',symptom:'Fast fails',impact:'Degraded path',firstCheck:'CB state + dependency',mitigate:'Fallback PENDING',rootCause:'Dep repeatedly failing',prevent:'Tuning+alerts'},
  {id:'s35',title:'Deploy regression',layer:'Change',symptom:'Errors at deploy',impact:'Wide',firstCheck:'Version markers',mitigate:'Rollback if safe',rootCause:'Bad release',prevent:'Canary'},
  {id:'s36',title:'Bad config deploy',layer:'Config',symptom:'Timeouts↑',impact:'Exhaustion',firstCheck:'Config diff',mitigate:'Restore prior config',rootCause:'Timeout/pool change',prevent:'Config canary'},
  {id:'s37',title:'DB migration failure',layer:'Schema',symptom:'App/DB errors',impact:'Write path',firstCheck:'Migration logs',mitigate:'Expand/contract recovery',rootCause:'Incompatible schema',prevent:'Backward-compatible DDL'},
  {id:'s38',title:'Unsafe rollback',layer:'Change',symptom:'Worse after rollback',impact:'Extended outage',firstCheck:'App vs DB version',mitigate:'Fix forward',rootCause:'Irreversible migration',prevent:'Compat matrix'},
  {id:'s39',title:'CrashLoopBackOff',layer:'K8s',symptom:'Pod restart loop',impact:'No capacity',firstCheck:'logs --previous',mitigate:'Rollback image',rootCause:'Boot crash',prevent:'Startup probes'},
  {id:'s40',title:'OOMKilled',layer:'K8s',symptom:'Exit 137',impact:'Restarts',firstCheck:'kubectl describe',mitigate:'Raise limit / fix leak',rootCause:'Memory limit/leak',prevent:'Right-size + alerts'},
  {id:'s41',title:'Readiness failure',layer:'K8s',symptom:'No traffic',impact:'503',firstCheck:'Probe endpoint',mitigate:'Fix ready check',rootCause:'False not-ready',prevent:'Probe design'},
  {id:'s42',title:'DNS failure',layer:'Network',symptom:'Unknown host',impact:'Client errors',firstCheck:'dig / Route53',mitigate:'Fix record / failover',rootCause:'Bad/stale DNS',prevent:'Health checks'},
  {id:'s43',title:'TLS cert failure',layer:'Network',symptom:'SSL errors',impact:'HTTPS down',firstCheck:'openssl s_client',mitigate:'Rotate cert',rootCause:'Expiry/SAN/chain',prevent:'Cert monitoring'},
  {id:'s44',title:'Security group block',layer:'AWS',symptom:'Connect timeout',impact:'Dep unreachable',firstCheck:'SG/NACL/flow logs',mitigate:'Open required path',rootCause:'SG rule',prevent:'Change review'},
  {id:'s45',title:'IAM AccessDenied',layer:'AWS',symptom:'AccessDenied',impact:'Feature fail',firstCheck:'CloudTrail',mitigate:'Fix policy least-priv',rootCause:'Missing permission',prevent:'Policy tests'},
  {id:'s46',title:'EC2 CPU spike',layer:'AWS',symptom:'Host CPU high',impact:'Node pressure',firstCheck:'CloudWatch + top',mitigate:'Scale / move load',rootCause:'Process/noisy neighbor',prevent:'Autoscaling'},
  {id:'s47',title:'Disk full',layer:'Infra',symptom:'ENOSPC',impact:'Writes fail',firstCheck:'df -h',mitigate:'Free/expand',rootCause:'Logs/data growth',prevent:'80% alerts'},
  {id:'s48',title:'Region failure',layer:'DR',symptom:'Region unreachable',impact:'Geo outage',firstCheck:'Health + DNS',mitigate:'Failover DR',rootCause:'AZ/region event',prevent:'DR game day'},
  {id:'s49',title:'DB primary failure',layer:'DR',symptom:'Primary down',impact:'Writes down',firstCheck:'RDS events',mitigate:'Failover replica',rootCause:'Instance failure',prevent:'Multi-AZ'},
  {id:'s50',title:'Shard failure',layer:'Sharding',symptom:'Subset users fail',impact:'1/N customers',firstCheck:'Shard health map',mitigate:'Promote shard replica',rootCause:'Single shard outage',prevent:'Per-shard HA'},
];
