import type {TocItem} from './types';

export const PROD_TOC: TocItem[] = [
  {id: 'mindset', label: '00. IC mindset'},
  {id: 'framework', label: '01. Universal framework'},
  {id: 'overview', label: '02. Payment latency story'},
  {id: 'first-minutes', label: '03. First minutes table'},
  {id: 'layers', label: '04. Layer chain'},
  {id: 'immediate', label: '05. Immediate vs permanent'},
  {id: 'golden-rule', label: '06. Golden rule'},
  {id: 'severity', label: '07. Severity P1–P4'},
  {id: 'first5', label: '08. First 5 minutes (topic)'},
  {id: 'signals', label: '09. Golden signals'},
  {id: 'frontend', label: '10. Angular · React · CDN'},
  {id: 'edge', label: '11. Gateway · ALB'},
  {id: 'spring', label: '12. Spring · Threads · JVM'},
  {id: 'cascade', label: '13. Cascade · Retry storm'},
  {id: 'data', label: '14. DB · Redis · Kafka'},
  {id: 'cdc', label: '15. Debezium · CDC'},
  {id: 'mongo', label: '16. MongoDB'},
  {id: 'aws', label: '17. AWS · K8s · Network'},
  {id: 'deploy', label: '18. Deploy · Rollback'},
  {id: 'observe', label: '19. Observability · RCA'},
  {id: 'playbook', label: '20. P1 playbook · Escalate'},
  {id: 'antipatterns', label: '21. Production anti-patterns'},
  {id: 'trees', label: '22. Decision trees'},
  {id: 'multilayer', label: '23. Multi-layer incidents'},
  {id: 'scenarios', label: '24. 90+ scenarios'},
  {id: 'architecture', label: '25. Master decision tree'},
  {id: 'decision', label: '26. Symptom → Check'},
  {id: 'commands', label: '27. Command toolbox'},
  {id: 'seniority', label: '28. Seniority answers'},
  {id: 'postmortem', label: '29. Postmortem'},
  {id: 'checklist', label: '30. 15+ YOE checklist'},
  {id: 'interview', label: '31. Interview mode'},
  {id: 'cheat', label: '32. Cheat sheet'},
  {id: 'related', label: '33. Deep dives (no dupes)'},
];

export const MEMORY_SENTENCE =
  'Confirm impact → check change window → golden signals → trace → name ONE bottleneck → mitigate safely → prove root cause → permanent fix ≠ restart. Deep JVM/perf, stuck-thread curricula, Kafka boards, and Resilience4j live on their hubs — link out, do not re-teach.';
