create table transactions (
    id varchar(36) primary key,
    source varchar(64) not null,
    dest varchar(64) not null,
    amount numeric(19,2) not null,
    state varchar(32) not null,
    status varchar(32) not null,
    fencing_source bigint,
    fencing_dest bigint,
    error text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint chk_transactions_amount_positive check (amount > 0)
);

create table idempotency_keys (
    idempotency_key varchar(128) primary key,
    transaction_id varchar(36) not null unique references transactions(id),
    response_json text not null,
    created_at timestamp with time zone not null
);

create table transaction_locks (
    id bigint generated by default as identity primary key,
    transaction_id varchar(36) not null references transactions(id) on delete cascade,
    lock_key varchar(128) not null,
    mode varchar(16) not null,
    owner_token varchar(128) not null,
    fencing_token bigint not null,
    created_at timestamp with time zone not null,
    unique (transaction_id, lock_key)
);

create table transaction_events (
    id bigint generated by default as identity primary key,
    transaction_id varchar(36) not null references transactions(id) on delete cascade,
    type varchar(64) not null,
    payload text not null,
    created_at timestamp with time zone not null
);

create index idx_transactions_state on transactions(state);
create index idx_transaction_locks_transaction_id on transaction_locks(transaction_id);
create index idx_transaction_events_transaction_id on transaction_events(transaction_id);
