server:
  port: 8092

spring:
  application:
    name: settlement-worker
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:settlement;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: settlement-worker
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        isolation.level: read_committed
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        spring.json.trusted.packages: com.vibhu.kafka.common
        spring.json.value.default.type: com.vibhu.kafka.common.PaymentMessages$PaymentRequestedEvent
        max.poll.records: 50
        max.poll.interval.ms: 300000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        compression.type: zstd
        spring.json.add.type.headers: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
