import type {FailureScenario, Runbook, SectionBlock} from './types';

export const TEMP_PERM_ROWS: string[][] = [
  ['Problem', 'Immediate (temp)', 'Permanent', 'Why temp is dangerous'],
  [
    'Consumer lag SLO breach',
    'Scale consumer pods + raise max.poll.records',
    'Right-size partitions, fix slow handler, add idempotency + DLQ',
    'More pods on hot partition still idle; masks DB bottleneck until cluster melts',
  ],
  [
    'Broker disk >90%',
    'Delete old segments / shorten retention emergency',
    'Tiered storage, retention policy, disk alerts at 70%, rebalance leaders',
    'Data loss window; next spike fills disk again in hours',
  ],
  [
    'Under-replicated partitions',
    'Restart lagging broker / throttle reassignment',
    'Fix disk/NET on follower, rack-aware RF=3, minISR=2, unclean=false',
    'Restart without root cause → ISR flap; unclean elect risks tail loss',
  ],
  [
    'Producer timeout storm',
    'Raise request.timeout.ms + client retries',
    'Fix broker/ISR/network; idempotent producer; circuit breaker on app',
    'Retries multiply load; duplicates without idempotence',
  ],
  [
    'ISR shrink to 1',
    'Accept writes with acks=1 temporarily',
    'Restore follower sync; never run minISR=1 + RF=3 in prod long-term',
    'Single replica = AZ loss equals data loss on broker death',
  ],
  [
    'Hot partition',
    'Add consumer pods',
    'Re-key, salt hot keys, split topic, increase partitions with migration plan',
    'Extra consumers idle — one partition = one consumer owner',
  ],
  [
    'Rebalance storm',
    'Increase session.timeout.ms / max.poll.interval.ms',
    'Fix GC pauses, static group.instance.id, cooperative assignor, right-size heap',
    'Long timeouts hide stuck threads; lag grows during constant rebalance',
  ],
  [
    'Controller flap',
    'Restart controller quorum member',
    'Dedicated controllers, JVM heap tune, network stability, odd voter count across AZs',
    'Leadership churn during flap → p99 spikes and client metadata storms',
  ],
  [
    'Auth / ACL deny',
    'Grant wildcard ACL in crisis',
    'Least-privilege ACL per service account; automate ACL-as-code review',
    'Over-broad ACL persists; audit failure; lateral movement if creds leak',
  ],
  [
    'Message too large',
    'Raise message.max.bytes cluster-wide',
    'Enforce payload limits at API; S3 pointer pattern for blobs',
    'Large records hurt all topics sharing broker; OOM on fetch path',
  ],
  [
    'Offset commit failures',
    'Disable auto-commit; manual commit after process',
    'Idempotent consumer + transactional outbox; fix rebalance/GC causing commit timeout',
    'Manual commit without idempotency → dup or loss on crash window',
  ],
  [
    'MM2 lag to DR',
    'Pause non-critical source topics',
    'Dedicated MM2 cluster, network bandwidth, filter transforms, separate DR cluster sizing',
    'DR RPO silently violated; failover missing hours of events',
  ],
  [
    'Poison message',
    'Skip bad offset manually',
    'DLQ + classifier + replay runbook; schema validation at edge',
    'Skip loses audit trail; manual seek error skips real payments',
  ],
  [
    'Upgrade instability',
    'Rollback broker version',
    'Rolling upgrade with inter.broker.protocol + log.message.format stepping; canary cluster',
    'Rollback may be impossible after message format bump',
  ],
];

export const FAILURE_SCENARIOS: FailureScenario[] = [
  {
    id: 'fs-lag',
    title: 'Consumer lag growing',
    architecture: 'Producers → topic (N partitions) → consumer group (M members)',
    symptoms: ['Lag alert per group/partition', 'Age of oldest unprocessed record ↑', 'Downstream SLA miss'],
    causes: ['Slow handler / DB', 'Too few partitions vs needed parallelism', 'Hot key on one partition', 'Rebalance loop', 'Downstream dependency timeout'],
    metrics: ['kafka.consumer.lag', 'records-lag-max', 'process-time histogram', 'rebalance.rate'],
    logs: ['Consumer poll timeout', 'max.poll.interval exceeded', 'Processing took Xms'],
    tempFix: ['Scale consumer replicas (if partition-bound)', 'Pause non-critical consumers', 'Raise max.poll.interval.ms short-term'],
    permanentFix: ['Profile handler; add idempotency + DLQ', 'Increase partitions with key migration plan', 'Fix hot key salting', 'Static membership + cooperative assignor'],
    tradeoffs: 'Scaling consumers without partition headroom wastes CPU; pausing consumers trades lag for stability.',
    interviewAnswer:
      'First confirm cluster health (URP, offline, disk). Then split lag: one partition vs all. One partition → hot key. All → processing capacity or rebalance. Never tune producer during consumer outage.',
  },
  {
    id: 'fs-disk90',
    title: 'Broker disk >90%',
    symptoms: ['Log dir ENOSPC warnings', 'Produce fail NotEnoughReplicas', 'Fetch latency spike'],
    causes: ['Retention too long', 'Traffic spike', 'Compaction lag', 'No tiered storage', 'RF×ingress underestimated'],
    metrics: ['LogDirSize / capacity', 'BytesInPerSec', 'FailedProduceRequests'],
    logs: ['No space left on device', 'Error while rolling log segment'],
    tempFix: ['Emergency retention shorten', 'Delete obsolete topics', 'Move leaders off full broker'],
    permanentFix: ['Tiered storage', 'Retention by tier', 'Capacity model: ingress×RF×retention', 'Alert at 70%'],
    tradeoffs: 'Emergency retention cut loses replay window; tiered adds ops complexity.',
    interviewAnswer: 'Disk full stops the cluster regardless of consumer lag. Throttle reassignment, expand or tier, then root-cause retention math.',
  },
  {
    id: 'fs-broker-down',
    title: 'Single broker down',
    symptoms: ['Broker not in cluster metadata', 'URP on partitions with replica on dead broker', 'Client NOT_LEADER errors briefly'],
    causes: ['Hardware failure', 'OOM kill', 'Bad deploy', 'Disk full on broker'],
    metrics: ['ActiveControllerCount', 'UnderReplicatedPartitions', 'OfflinePartitionsCount'],
    logs: ['Broker exited unexpectedly', 'Shutdown hook'],
    tempFix: ['Replace/restart broker node', 'Verify ISR recovery'],
    permanentFix: ['RF=3 rack-aware', 'Automated broker replacement', 'Pod anti-affinity / AZ spread'],
    tradeoffs: 'RF=2 survives one broker but not AZ loss; RF=3 costs 3× storage.',
    interviewAnswer: 'With RF=3 minISR=2 unclean=false, AZ-aware: cluster stays writable if replicas elsewhere. Watch leader concentration after recovery.',
  },
  {
    id: 'fs-two-brokers',
    title: 'Two brokers lost (RF=3)',
    symptoms: ['Many URP', 'Some partitions offline if |ISR|<minISR', 'Produce failures on acks=all'],
    causes: ['Correlated failure (AZ, rack)', 'Rolling restart mistake', 'Network partition'],
    metrics: ['OfflinePartitionsCount', 'UnderReplicatedPartitions', 'NotEnoughReplicasPerSec'],
    logs: ['Unable to replicate', 'ISR shrunk to []'],
    tempFix: ['Restore brokers ASAP', 'Do NOT enable unclean election for money topics'],
    permanentFix: ['One replica per AZ', 'Chaos game days', 'Separate controller quorum'],
    tradeoffs: 'Unclean election restores availability with possible tail loss — almost never for payments.',
    interviewAnswer: 'RF=3 survives one broker loss cleanly; two simultaneous losses may offline partitions lacking a third copy. DR is another cluster, not RF alone.',
  },
  {
    id: 'fs-az-down',
    title: 'Availability zone loss',
    symptoms: ['1/3 brokers unreachable', 'Leaders concentrated in lost AZ → offline partitions', 'Spike in latency'],
    causes: ['AZ outage', 'Misconfigured rack awareness (all replicas same AZ)'],
    metrics: ['Brokers per AZ', 'OfflinePartitions', 'Leader count per broker'],
    logs: ['Connection refused to AZ subnet'],
    tempFix: ['Fail traffic to healthy AZ clients', 'Trigger preferred leader election when AZ returns'],
    permanentFix: ['Rack awareness replica.selector.class', 'RF=3 minISR=2', 'Controllers across AZs'],
    tradeoffs: 'minISR=3 would block writes when one AZ dies — minISR=2 keeps availability with 2 copies.',
    interviewAnswer: 'Design goal: one AZ gone, cluster writable, no data loss. RF without rack awareness fails this interview question.',
  },
  {
    id: 'fs-producer-timeout',
    title: 'Producer timeout storm',
    symptoms: ['Client TimeoutException', 'Retry storm from apps', 'Broker request queue depth ↑'],
    causes: ['ISR thin → acks=all wait', 'Broker overload', 'Network latency', 'Too small request.timeout.ms'],
    metrics: ['RequestLatencyMs produce', 'TotalTimeMs', 'RetriesPerSec client'],
    logs: ['Expiring N record batches', 'Not enough replicas'],
    tempFix: ['Circuit breaker on app produce path', 'Raise timeout slightly'],
    permanentFix: ['Fix ISR/broker capacity', 'enable.idempotence=true', 'Right-size acks and linger'],
    tradeoffs: 'Longer timeout hides slow cluster; shorter timeout causes false failures.',
    interviewAnswer: 'Producer talks to leader only. Timeouts often mean durability cannot be met — fix ISR, not just client knobs.',
  },
  {
    id: 'fs-isr-shrink',
    title: 'ISR shrink',
    symptoms: ['Shrinking ISR alerts', 'acks=all failures', 'Follower lag metrics high'],
    causes: ['Slow disk on follower', 'Network between brokers', 'replica.lag.time.max.ms breach', 'Heavy reassignment'],
    metrics: ['IsrShrinksPerSec', 'ReplicaFetcherLag', 'LogFlushRate'],
    logs: ['Removing replica from ISR', 'Replica lagging'],
    tempFix: ['Throttle reassignment', 'Restart lagging follower if stuck'],
    permanentFix: ['Disk/NET tuning', 'num.replica.fetchers', 'Avoid colocated heavy workloads'],
    tradeoffs: 'Aggressive replica.lag.time.max.ms keeps ISR wide but risks acknowledging unreplicated data semantics.',
    interviewAnswer: 'ISR is the durability set for acks=all. Shrinking ISR is the cluster telling you replication is unhealthy.',
  },
  {
    id: 'fs-urp',
    title: 'Under-replicated partitions (URP)',
    symptoms: ['URP metric >0 sustained', 'Risk if another broker fails', 'Possible acks=all errors'],
    causes: ['Follower lag', 'Broker down', 'Reassignment in progress', 'Disk pressure on follower'],
    metrics: ['UnderReplicatedPartitions', 'PartitionCount', 'BytesOutPerSec followers'],
    logs: ['Replica not caught up'],
    tempFix: ['Wait for catch-up if transient', 'Throttle other admin ops'],
    permanentFix: ['Fix follower health', 'Complete reassignment', 'Capacity headroom'],
    tradeoffs: 'Running with URP is technical debt — one more failure can offline partitions.',
    interviewAnswer: 'URP means RF > |ISR|. Not always user-visible yet — P0 before lag because durability already compromised.',
  },
  {
    id: 'fs-offline',
    title: 'Offline partitions',
    symptoms: ['OfflinePartitionsCount >0', 'Produce/consume fail for affected partitions', 'Sev1 page'],
    causes: ['No leader in ISR', 'All replicas down', 'minISR not met and no eligible leader'],
    metrics: ['OfflinePartitionsCount', 'ActiveControllerCount'],
    logs: ['No leader for partition', 'Error in leader election'],
    tempFix: ['Restore brokers', 'Last resort: unclean leader (non-financial only)'],
    permanentFix: ['RF=3 rack-aware', 'Runbooks for broker replacement', 'Never RF=1 in prod'],
    tradeoffs: 'Unclean leader trades data loss for availability.',
    interviewAnswer: 'Offline = no readable/writable leader. Fix replication topology before blaming clients.',
  },
  {
    id: 'fs-controller-flap',
    title: 'Controller flap',
    symptoms: ['Frequent controller migration', 'Leadership churn', 'Client metadata refresh storm'],
    causes: ['Controller JVM GC', 'Network jitter', 'Under-resourced controller', 'ZK/KRaft quorum instability'],
    metrics: ['ActiveControllerCount', 'LeaderElectionRate', 'ControllerEventQueueTimeMs'],
    logs: ['Controller moved to broker X', 'KRaft voter timeout'],
    tempFix: ['Stabilize network', 'Increase controller resources'],
    permanentFix: ['Dedicated KRaft controllers (3/5)', 'Heap and GC tuning', 'Spread voters across AZs'],
    tradeoffs: 'Combined broker+controller saves cost; split when metadata load high.',
    interviewAnswer: 'Controller is metadata brain — flap causes leadership storms unrelated to message size.',
  },
  {
    id: 'fs-rebalance-storm',
    title: 'Rebalance storm',
    symptoms: ['Constant group rebalance logs', 'Throughput collapse', 'Duplicate processing spikes'],
    causes: ['max.poll.interval exceeded', 'Session timeout too tight', 'GC pauses', 'Rolling deploy without static membership'],
    metrics: ['rebalance.rate', 'join.rate', 'time between polls'],
    logs: ['Revoking assignment', 'Member failed heartbeat'],
    tempFix: ['Pause deploys', 'Raise max.poll.interval.ms'],
    permanentFix: ['group.instance.id static membership', 'CooperativeStickyAssignor', 'Fix long processing / async commit'],
    tradeoffs: 'Very long max.poll.interval delays failure detection.',
    interviewAnswer: 'Rebalance stops consumption — storm looks like lag but root is membership instability.',
  },
  {
    id: 'fs-hot-partition',
    title: 'Hot partition',
    symptoms: ['One partition lag extreme', 'One broker BytesIn dominant', 'Skewed leader distribution'],
    causes: ['Key skew (celebrity account)', 'Poor partition count', 'Leader imbalance'],
    metrics: ['BytesInPerSec by partition', 'RecordsPerSec per partition', 'Lag by partition'],
    logs: ['Single partition processing slow'],
    tempFix: ['Manual leader move (does not fix key skew)', 'Rate limit hot producer key'],
    permanentFix: ['Key salting / shuffle topic', 'More partitions + migration', 'Preferred leader election'],
    tradeoffs: 'Salting breaks strict per-key order — document tradeoff.',
    interviewAnswer: 'Consumers scale with partitions, not keys. Hot partition needs key or partition surgery.',
  },
  {
    id: 'fs-slow-consumer',
    title: 'Slow consumer handler',
    symptoms: ['Lag all partitions of group equally', 'Low CPU on consumers but high poll interval', 'DB connection pool wait'],
    causes: ['Sync DB call in listener', 'External API in hot path', 'No batching', 'Missing index'],
    metrics: ['Handler latency histogram', 'Hikari pending', 'poll idle ratio'],
    logs: ['Processing record took 5s'],
    tempFix: ['Scale consumers to partition count', ' Shed load at API gateway'],
    permanentFix: ['Async processing with pause/resume', 'Idempotent batch writes', 'Optimize downstream'],
    tradeoffs: 'Async adds ordering complexity; must keep per-key serialization.',
    interviewAnswer: 'Prove slowness in handler tracing before buying more Kafka brokers.',
  },
  {
    id: 'fs-msg-too-large',
    title: 'Record too large',
    symptoms: ['RecordTooLargeException', 'Produce fail for specific payloads', 'Consumer fetch errors'],
    causes: ['message.max.bytes / replica.fetch.max.bytes mismatch', 'Blob in message body', 'Compression off on huge JSON'],
    metrics: ['FailedProduceRequests', 'Size of max record sample'],
    logs: ['The message is N bytes when max is M'],
    tempFix: ['Raise broker and client max sizes consistently'],
    permanentFix: ['Claim-check pattern (S3 + pointer in Kafka)', 'Schema enforcement at API'],
    tradeoffs: 'Raising max hurts all topics on cluster — prefer reference pattern.',
    interviewAnswer: 'All limits must align: producer, broker, consumer fetch.max.bytes, replica.fetch.max.bytes.',
  },
  {
    id: 'fs-net-latency',
    title: 'Cross-AZ network latency',
    symptoms: ['Produce p99 ↑', 'Replica lag on cross-AZ followers', 'Fetch latency ↑'],
    causes: ['Clients producing from wrong AZ', 'Replication across regions accidentally', 'Oversubscribed network'],
    metrics: ['RequestLatencyMs', 'RemoteBytesIn', 'AZ egress'],
    logs: ['Slow replica fetch'],
    tempFix: ['Pin producers/consumers to broker AZ', 'Throttle cross-AZ traffic'],
    permanentFix: ['Co-locate clients with cluster', 'MM2 for cross-region not client cross-wire'],
    tradeoffs: 'Strict AZ pinning complicates K8s scheduling.',
    interviewAnswer: 'Kafka loves local produce/fetch; cross-AZ replication is necessary for RF but clients should stay close.',
  },
  {
    id: 'fs-slow-db',
    title: 'Slow DB in consumer path',
    symptoms: ['Lag with healthy Kafka metrics', 'DB CPU high', 'Pool exhausted'],
    causes: ['Missing index', 'N+1 queries', 'Long transactions', 'Lock contention'],
    metrics: ['DB query p99', 'pool active connections', 'consumer lag'],
    logs: ['Connection timeout waiting for pool', 'Slow query log'],
    tempFix: ['Kill long queries', 'Increase pool (careful)'],
    permanentFix: ['Index + query rewrite', 'Idempotent upsert batch', 'Outbox pattern decouple'],
    tradeoffs: 'Bigger pool masks DB slowness until DB collapses.',
    interviewAnswer: 'Kafka is rarely the bottleneck when DB spans dominate traces — show EXPLAIN ANALYZE story.',
  },
  {
    id: 'fs-partition-limit',
    title: 'Partition count limit / metadata pressure',
    symptoms: ['Controller slow', 'Broker startup long', 'Metadata refresh timeouts'],
    causes: ['Too many partitions per broker (>4000 rule of thumb)', 'Many tiny topics', 'Over-sharding'],
    metrics: ['PartitionCount per broker', 'Metadata request latency'],
    logs: ['Error loading metadata'],
    tempFix: ['Stop creating topics', 'Merge low-traffic topics'],
    permanentFix: ['Partition budget per cluster', 'Right-size upfront', 'Dedicated metadata controllers'],
    tradeoffs: 'More partitions ≠ infinite scale — each partition has file handles and leader state.',
    interviewAnswer: 'Partitions are parallelism units with overhead — size from throughput math, not default 1000.',
  },
  {
    id: 'fs-stuck-group',
    title: 'Stuck consumer group',
    symptoms: ['Lag frozen', 'One member owns all partitions', 'Join group hangs'],
    causes: ['Zombie member', 'Static member id conflict', 'ACL on __consumer_offsets', 'Coordinator broker issue'],
    metrics: ['members in group vs expected', 'LastCommit offset stale'],
    logs: ['Member id still in group', 'Offset commit failed'],
    tempFix: ['Remove zombie with kafka-consumer-groups --delete', 'Restart consumers rolling'],
    permanentFix: ['Unique group.instance.id', 'ACL for offset topic', 'Monitor coordinator health'],
    tradeoffs: 'Deleting group loses committed offsets — replay risk.',
    interviewAnswer: 'Stuck group often coordinator or offset commit — not always slow processing.',
  },
  {
    id: 'fs-auth',
    title: 'SASL authentication failure',
    symptoms: ['AuthenticationException on clients', 'All producers/consumers fail after rotate', 'Intermittent 401-equivalent'],
    causes: ['Wrong JAAS config', 'Credential rotation drift', 'Clock skew', 'SCRAM mismatch'],
    metrics: ['Failed authentication rate', 'Client connection count drop'],
    logs: ['Authentication failed during login'],
    tempFix: ['Rollback credential change', 'Sync JAAS across pods'],
    permanentFix: ['Automated secret rotation with dual creds', 'Staging canary', 'SASL mechanism standardization'],
    tradeoffs: 'PLAINTEXT is fast to debug and unacceptable in prod.',
    interviewAnswer: 'Auth failures are total — canary one client pod before fleet rollout.',
  },
  {
    id: 'fs-acl',
    title: 'ACL authorization deny',
    symptoms: ['TopicAuthorizationException', 'GroupAuthorizationException', 'Works in dev not prod'],
    causes: ['Missing WRITE on topic', 'CLUSTER ACTION for idempotent producer', 'Prefix ACL typo'],
    metrics: ['Authorization failure logs count'],
    logs: ['Principal X denied Operation Y'],
    tempFix: ['Emergency ACL for service account (tighten after)'],
    permanentFix: ['ACL-as-code in CI', 'Standard templates per service', 'Regular audit'],
    tradeoffs: 'Wildcard ACL fixes outage but violates least privilege.',
    interviewAnswer: 'Idempotent producer needs idempotent_write cluster permission — common interview miss.',
  },
  {
    id: 'fs-zk-fail',
    title: 'ZooKeeper ensemble failure (legacy)',
    symptoms: ['Controller cannot start', 'Broker registration fail', 'Metadata stale'],
    causes: ['ZK quorum loss', 'Disk full on ZK', 'Version skew'],
    metrics: ['ZkRequestLatency', 'Controller not active'],
    logs: ['Unable to connect to ZooKeeper'],
    tempFix: ['Restore ZK quorum members'],
    permanentFix: ['Migrate to KRaft', 'Dedicated ZK with odd count across AZs'],
    tradeoffs: 'Kafka 4.x is KRaft-only — know migration narrative.',
    interviewAnswer: 'ZK loss freezes metadata — greenfield answer is KRaft quorum 3/5, not ZK tuning.',
  },
  {
    id: 'fs-kraft-fail',
    title: 'KRaft controller quorum loss',
    symptoms: ['No active controller', 'Cannot create topics', 'Leadership elections stall'],
    causes: ['Lost majority voters', 'Snapshot corruption', 'Network split on controllers'],
    metrics: ['ActiveControllerCount=0', 'MetadataErrorRate'],
    logs: ['Raft voter unreachable', 'Quorum not satisfied'],
    tempFix: ['Restore voter nodes', 'Never delete metadata log manually'],
    permanentFix: ['5 voters for large clusters', 'AZ spread', 'Backup metadata procedures'],
    tradeoffs: 'Combined mode vs dedicated controllers — cost vs isolation.',
    interviewAnswer: 'Majority quorum required — 3 voters tolerate 1 loss, 5 tolerate 2.',
  },
  {
    id: 'fs-region-fail',
    title: 'Region failure',
    symptoms: ['Entire cluster unreachable', 'DNS to bootstrap fails', 'DR runbook invoked'],
    causes: ['Regional outage', 'Misconfigured single-region DR'],
    metrics: ['MM2 lag to DR', 'RPO/RTO clock'],
    logs: ['Failover initiated'],
    tempFix: ['DNS/traffic shift to DR cluster', 'Accept MM2 lag window'],
    permanentFix: ['Active-passive DR cluster + MM2', 'Idempotent consumers globally', 'Game days'],
    tradeoffs: 'Active-active cross-region doubles complexity and conflict resolution.',
    interviewAnswer: 'RF protects broker/AZ, not region — DR is second cluster with MM2 and offset-independent replay.',
  },
  {
    id: 'fs-mm2-lag',
    title: 'MirrorMaker 2 lag',
    symptoms: ['DR cluster behind primary', 'Failover RPO violated', 'MM2 consumer lag high'],
    causes: ['Under-sized MM2', 'Network bandwidth', 'Transform bottleneck', 'Too many topics mirrored'],
    metrics: ['MM2 consumer lag', 'Replication latency', 'BytesOut primary'],
    logs: ['MM2 connector paused', 'Record too large on mirror'],
    tempFix: ['Scale MM2 tasks', 'Filter non-critical topics'],
    permanentFix: ['Dedicated MM2 cluster', 'Bandwidth provisioning', 'Topic allowlist'],
    tradeoffs: 'Mirroring everything is expensive — tier critical topics only.',
    interviewAnswer: 'MM2 is async replication — RPO = lag at failure time, not zero.',
  },
  {
    id: 'fs-duplicates',
    title: 'Duplicate messages',
    symptoms: ['Double settlement attempts', 'Idempotency table hits', 'Downstream count mismatch'],
    causes: ['At-least-once + retry', 'Rebalance redelivery', 'Producer retry without idempotence'],
    metrics: ['duplicate ignored rate', 'producer retries'],
    logs: ['Duplicate key constraint', 'Redelivered record'],
    tempFix: ['Enable idempotent producer', 'DB unique constraint'],
    permanentFix: ['Business idempotency key', 'Transactional consume-process-produce where needed'],
    tradeoffs: 'EOS broker scope ≠ end-to-end exactly-once with external DB.',
    interviewAnswer: 'Duplicates are normal in Kafka — design consumers to be idempotent, not to forbid retries.',
  },
  {
    id: 'fs-ooo',
    title: 'Out-of-order events per key',
    symptoms: ['State machine violations', 'Later event applied before earlier', 'Compensation storms'],
    causes: ['Multiple producers same key', 'Partition increase without migration', 'Retry topic reorder', 'Concurrent processing'],
    metrics: ['sequence gap alerts', 'version monotonicity checks'],
    logs: ['Rejected event: expected seq N got M'],
    tempFix: ['Pause consumer', 'Park out-of-order in buffer topic'],
    permanentFix: ['Single writer per key', 'Sequence numbers in payload', 'Partition by key strictly'],
    tradeoffs: 'Parallel processing per partition breaks order — use key sub-sharding carefully.',
    interviewAnswer: 'Order is per-partition only — design partition key as your ordering scope.',
  },
  {
    id: 'fs-poison',
    title: 'Poison message',
    symptoms: ['Single partition lag stuck', 'Repeated same stack trace', 'DLT rate flat while lag grows'],
    causes: ['Bad schema', 'Null pointer in mapper', 'Unknown enum', 'Toxic payload size'],
    metrics: ['failure rate by exception class', 'records on same offset'],
    logs: ['Same exception every poll on partition P offset O'],
    tempFix: ['Seek past offset (dangerous)', 'Route to DLQ manually'],
    permanentFix: ['ErrorHandlingDeserializer + DLT', 'Schema validation', 'Replay after fix'],
    tradeoffs: 'Seek skips audit — DLT preserves evidence.',
    interviewAnswer: 'Poison stalls one partition — classifier must send permanent failures to DLT immediately.',
  },
  {
    id: 'fs-disk-fill',
    title: 'Disk fill from retention/compaction',
    symptoms: ['Sudden ENOSPC', 'All partitions on broker affected', 'Produce stopped'],
    causes: ['Compacted topic without delete policy mix', 'Log cleaner stuck', 'Burst traffic'],
    metrics: ['LogDirSize trend', 'Cleaner backlog'],
    logs: ['Failed to flush segment'],
    tempFix: ['Free space', 'Reduce retention'],
    permanentFix: ['Monitor growth rate', 'Tiered storage', 'Separate hot/cold topics'],
    tradeoffs: 'Compaction saves space for keyed topics but costs CPU — plan cleaner capacity.',
    interviewAnswer: 'Disk is the hard stop — lag metrics irrelevant when broker cannot append.',
  },
  {
    id: 'fs-buffer-exhaust',
    title: 'Producer buffer exhausted',
    symptoms: ['BufferExhaustedException', 'Max block timeout', 'App threads blocked on send()'],
    causes: ['Broker slow → backpressure', 'buffer.memory too small', 'No max.block.ms tuning', 'Fire-and-forget overload'],
    metrics: ['buffer-available-bytes', 'batch-size avg', 'record-queue-time-ms'],
    logs: ['Expiring batch due to timeout'],
    tempFix: ['Raise buffer.memory', 'Apply backpressure at API'],
    permanentFix: ['Fix broker latency', 'Async send with callback handling', 'Rate limit ingress'],
    tradeoffs: 'Huge buffers hide broker illness and OOM the client JVM.',
    interviewAnswer: 'Buffer exhaustion is symptom — broker or network cannot absorb produce rate.',
  },
  {
    id: 'fs-gc',
    title: 'Broker JVM GC pauses',
    symptoms: ['Request handler idle drop', 'Replica lag spikes', 'Consumer session timeout'],
    causes: ['Heap too large', 'Wrong GC algorithm', 'Metadata cache pressure'],
    metrics: ['GCTimeMillis', 'RequestHandlerAvgIdlePercent'],
    logs: ['Long GC pause N ms'],
    tempFix: ['Rolling restart brokers', 'Reduce heap temporarily'],
    permanentFix: ['G1/ZGC tuning', 'Keep heap modest — page cache holds logs', 'Dedicated controllers'],
    tradeoffs: 'Big heap steals OS page cache — Kafka broker heap is not “more is better”.',
    interviewAnswer: 'Logs live in page cache; oversized broker heap hurts throughput.',
  },
  {
    id: 'fs-bandwidth',
    title: 'Network bandwidth saturation',
    symptoms: ['Replication lag', 'Fetch latency', 'Inter-broker bytes maxed'],
    causes: ['RF×traffic exceeds NIC', 'Reassignment unthrottled', 'Cross-region replication on same link'],
    metrics: ['NetworkProcessorAvgIdle', 'BytesIn/Out per broker', 'Replication throttle queue'],
    logs: ['Throttled replication'],
    tempFix: ['Throttle reassignment/replication', 'Pause MM2'],
    permanentFix: ['Network capacity model', 'Dedicated replication VLAN', 'Broker count scale-out'],
    tradeoffs: 'Throttling extends reassignment time — prefer scheduled maintenance windows.',
    interviewAnswer: 'Replication multiplies traffic by RF — capacity plan includes inter-broker, not just client ingress.',
  },
  {
    id: 'fs-offset-commit-fail',
    title: 'Offset commit failure',
    symptoms: ['Lag metric wrong vs reality', 'Reprocessing bursts', 'CommitFailedException'],
    causes: ['Rebalance during commit', 'Generation id stale', '__consumer_offsets ACL', 'Coordinator unavailable'],
    metrics: ['commit latency', 'failed commit count'],
    logs: ['Offset commit failed on generation'],
    tempFix: ['Retry commit', 'Reduce rebalance frequency'],
    permanentFix: ['Commit after idempotent side effect', 'Static membership', 'Fix coordinator broker health'],
    tradeoffs: 'Commit-before-process = at-most-once loss risk.',
    interviewAnswer: 'Commit defines consumption progress — failed commit means ambiguous delivery semantics.',
  },
  {
    id: 'fs-replica-fetcher-lag',
    title: 'Replica fetcher lag',
    symptoms: ['Follower LEO << leader LEO', 'ISR shrink imminent', 'URP rising'],
    causes: ['Disk slow on follower', 'num.replica.fetchers too low', 'Network', 'Large messages'],
    metrics: ['ReplicaFetcherLagMetrics', 'FollowerFetchRate'],
    logs: ['Replica fetcher thread slow'],
    tempFix: ['Increase replica fetcher threads', 'Move leader away temporarily'],
    permanentFix: ['Disk type/IOPS', 'Right-size num.replica.fetchers', 'Message size discipline'],
    tradeoffs: 'More fetchers use CPU — balance with broker cores.',
    interviewAnswer: 'Followers pull — lagging fetcher is first domino to ISR shrink.',
  },
  {
    id: 'fs-upgrade-instability',
    title: 'Rolling upgrade instability',
    symptoms: ['URP during upgrade', 'Client protocol errors', 'Intermittent produce fail'],
    causes: ['Skipped protocol version steps', 'Mixed message format', 'Clients too old for broker'],
    metrics: ['Broker version mix', 'FailedProduce during window'],
    logs: ['Unsupported version', 'Incompatible message format'],
    tempFix: ['Pause upgrade', 'Rollback last wave'],
    permanentFix: ['Step inter.broker.protocol and log.message.format.version', 'Canary broker rack', 'Client upgrade first'],
    tradeoffs: 'Big-bang upgrade faster and riskier — stepping is slower and safer.',
    interviewAnswer: 'Upgrade order: clients compatible → brokers rolling → finalize format version — never skip steps on money cluster.',
  },
];

export const RUNBOOKS: Runbook[] = [
  {
    id: 'rb-lag',
    incident: 'Consumer lag SLO breach',
    severity: 'Sev2 (Sev1 if payments)',
    first5: ['Open lag by group/partition dashboard', 'Check URP/offline/disk — cluster first', 'Identify one-partition vs all-partition lag', 'Check recent deploy/rebalance', 'Page owning service if downstream'],
    check: ['records-lag-max per partition', 'Consumer group members', 'Handler p99 / DB pool', 'Rebalance rate'],
    temp: ['Scale consumers to partition ceiling', 'Pause non-critical consumers', 'Raise max.poll.interval if GC'],
    root: 'Slow handler or DB; insufficient partitions; hot key; rebalance storm',
    permanent: ['Optimize handler + idempotency', 'Partition/key plan', 'Static membership', 'DLQ for poison'],
    validation: ['Lag trending down 15m', 'No rebalance loop', 'SLO green 1h'],
    prevention: ['Processing SLO alerts', 'Load test before peak', 'Partition capacity review quarterly'],
  },
  {
    id: 'rb-broker',
    incident: 'Broker failure',
    severity: 'Sev1 if offline partitions',
    first5: ['Identify dead broker id', 'Check offline/URP counts', 'Verify RF and rack placement', 'Avoid unclean leader on financial topics', 'Start replacement node'],
    check: ['UnderReplicatedPartitions', 'OfflinePartitions', 'Log dirs on surviving brokers', 'Controller health'],
    temp: ['Replace broker with same broker.id if possible', 'Reassign leaders if skewed'],
    root: 'Hardware/OOM/disk failure or bad config deploy',
    permanent: ['Automated broker repair', 'RF=3 rack-aware', 'Game day broker loss'],
    validation: ['URP=0 sustained', 'All partitions have leader', 'ISR full'],
    prevention: ['Disk 70% alert', 'AZ spread audits', 'Chaos broker kill in staging'],
  },
  {
    id: 'rb-disk',
    incident: 'Disk full / >90%',
    severity: 'Sev1',
    first5: ['Identify broker log dirs', 'Check retention vs ingress rate', 'Stop unthrottled reassignment', 'Emergency free space or expand volume', 'Watch produce error rate'],
    check: ['LogDirSize', 'BytesInPerSec', 'Retention.ms per topic', 'Compaction backlog'],
    temp: ['Shorten retention emergency', 'Delete test topics', 'Move leaders off full disk'],
    root: 'Undersized disk, retention too long, or missing tiered storage',
    permanent: ['Capacity model + tiered storage', '70/80/90% alerts', 'Topic governance'],
    validation: ['Disk <75%', 'Produce success', 'No ENOSPC in logs'],
    prevention: ['Weekly disk forecast', 'Topic onboarding checklist'],
  },
  {
    id: 'rb-isr',
    incident: 'ISR shrink / acks=all failures',
    severity: 'Sev1 for payment producers',
    first5: ['List partitions with thin ISR', 'Find lagging followers', 'Check disk/network on followers', 'Throttle reassignment', 'Communicate to producer teams'],
    check: ['IsrShrinksPerSec', 'ReplicaFetcherLag', 'min.insync.replicas vs ISR size'],
    temp: ['Restart stuck follower if safe', 'Reduce produce rate at gateway'],
    root: 'Follower disk/network issue, unthrottled reassignment, or under-provisioned brokers',
    permanent: ['IOPS/disk class', 'num.replica.fetchers tune', 'Reassignment throttle policy'],
    validation: ['ISR size = RF for critical topics', 'Produce p99 normal', 'No NotEnoughReplicas'],
    prevention: ['ISR size alert', 'Reassignment change window'],
  },
  {
    id: 'rb-producer',
    incident: 'Producer failure / timeout storm',
    severity: 'Sev2',
    first5: ['Confirm broker health first', 'Check client error class', 'Sample acks/minISR/ISR', 'Enable circuit breaker on apps', 'Review retry multiplier'],
    check: ['RequestLatencyMs produce', 'RetriesPerSec', 'NotEnoughReplicas', 'Client metadata age'],
    temp: ['Slightly raise request.timeout.ms', 'Shed load at API'],
    root: 'ISR/broker issue, wrong acks config, or network partition',
    permanent: ['enable.idempotence=true acks=all', 'Fix cluster capacity', 'Client retry budget'],
    validation: ['Produce success rate restored', 'No retry storm'],
    prevention: ['Synthetic produce canary', 'Client config lint in CI'],
  },
  {
    id: 'rb-consumer',
    incident: 'Consumer failure / stuck group',
    severity: 'Sev2',
    first5: ['Group member list vs expected', 'Coordinator broker health', 'Offset commit errors in logs', 'Poison partition check', 'Recent deploy correlation'],
    check: ['Lag by partition', 'max.poll.interval violations', '__consumer_offsets ACL', 'DLT rate'],
    temp: ['Rolling restart consumers', 'Remove zombie member if confirmed'],
    root: 'Poison message, rebalance misconfig, ACL deny, or slow DB',
    permanent: ['DLQ classifier', 'Static membership', 'Handler optimization'],
    validation: ['Stable group membership', 'Lag decreasing', 'Commits succeeding'],
    prevention: ['Integration tests with rebalance', 'max.poll.interval budget from p99 handler'],
  },
  {
    id: 'rb-controller',
    incident: 'Controller / KRaft quorum failure',
    severity: 'Sev1',
    first5: ['ActiveControllerCount / quorum health', 'Identify unreachable voters', 'Stop destructive admin ops', 'Restore voter connectivity', 'Avoid manual metadata edits'],
    check: ['ControllerEventQueueTime', 'Metadata apply latency', 'Quorum voter logs'],
    temp: ['Restart controller processes', 'Failover to standby voters'],
    root: 'Quorum loss, network split, or controller resource starvation',
    permanent: ['Dedicated controllers 3/5', 'AZ spread', 'Resource limits'],
    validation: ['Active controller elected', 'Topic create/delete works', 'Leader elections stable'],
    prevention: ['Controller JVM GC alerts', 'Quorum member health checks'],
  },
  {
    id: 'rb-az',
    incident: 'Availability zone loss',
    severity: 'Sev1',
    first5: ['Confirm AZ scope', 'Count brokers offline in AZ', 'Check offline partitions', 'Redirect client traffic to healthy AZ', 'Execute DR comms template'],
    check: ['Leaders per AZ', 'RF and rack assignment', 'Client bootstrap AZ affinity'],
    temp: ['Preferred leader election after recovery', 'Accept reduced headroom'],
    root: 'Missing rack awareness, RF=2 only, or all controllers in lost AZ',
    permanent: ['Rack-aware RF=3', 'Controllers across AZs', 'Game day AZ failure'],
    validation: ['Cluster writable from healthy AZs', 'URP trending to zero'],
    prevention: ['Quarterly AZ failure drill', 'Topology audit automation'],
  },
  {
    id: 'rb-replication',
    incident: 'Replication lag / URP',
    severity: 'Sev2 (Sev1 if sustained)',
    first5: ['URP count and duration', 'Identify lagging followers', 'Check reassignment jobs', 'Throttle if needed', 'Assess data loss risk if second failure'],
    check: ['UnderReplicatedPartitions', 'ReplicaFetcherLag', 'Inter-broker bandwidth'],
    temp: ['Throttle replication/reassignment', 'Pause admin changes'],
    root: 'Disk/network on follower, unthrottled move, or under-sized cluster',
    permanent: ['Broker scale-out', 'IOPS upgrade', 'Maintenance windows with throttle'],
    validation: ['URP=0', 'ISR equals RF'],
    prevention: ['URP alert >5m', 'Reassignment automation with throttle defaults'],
  },
  {
    id: 'rb-hot',
    incident: 'Hot partition / skew',
    severity: 'Sev2',
    first5: ['Lag heatmap by partition', 'BytesIn per partition', 'Identify hot key from sample headers', 'Confirm consumer count vs partitions', 'Check leader distribution'],
    check: ['RecordsPerSec per partition', 'Key histogram sample', 'Consumer assignment'],
    temp: ['Rate limit hot producer', 'Manual leader move (limited help)'],
    root: 'Key skew, too few partitions, or celebrity account hotspot',
    permanent: ['Key salting/shuffle pipeline', 'Partition increase + migration', 'Caching hot path'],
    validation: ['Lag balanced across partitions', 'No single partition >2× median lag'],
    prevention: ['Key distribution metrics at produce', 'Partition sizing from peak key QPS'],
  },
];

export const SECTIONS_INCIDENTS: SectionBlock[] = [
  {
    id: 'troubleshoot',
    part: 23,
    title: 'Troubleshooting framework — Detect → Prevent',
    lead: 'Production Kafka incidents reward a fixed order: cluster health before client knobs, partition scope before global scaling, durability before lag cosmetics.',
    ascii: `
DETECT                    TRIAGE                     FIX                    PREVENT
──────                    ──────                     ───                    ───────
Alerts: URP, offline,     Cluster red? → broker     Temp: stabilize,       SLOs, capacity model,
disk, lag SLO             ops first                 throttle, scale to      game days, runbooks,
                          Client red? → handler/    partition ceiling       ACL-as-code, upgrade
                          DB/auth                   Root: topology, code,   stepping, rack-aware RF
Metrics + logs correlate  One partition? hot key    capacity, idempotency
Partition scope split     All partitions? capacity
`,
    body: `**Detect** — Tier-0 signals: OfflinePartitionsCount, UnderReplicatedPartitions, ISR shrink rate, disk >80%, controller not active. Tier-1: consumer lag by group/partition, produce/fetch p99, rebalance rate, authorization failures. Tier-2: business SLO (payment age). Never alert on lag alone without cluster health context.

**Triage** — Ask four questions in order: (1) Can the cluster accept writes? (2) Are all partitions online with healthy ISR? (3) Is lag global or single-partition? (4) Did deploy/config change correlate? Map answers to layer: broker → replication → controller → client → application downstream.

**Fix** — Temporary measures stabilize (throttle reassignment, scale consumers to partition count, circuit-break produce). Permanent fixes remove root cause (disk capacity, handler optimization, rack-aware placement, DLQ for poison). Document temp vs permanent — temp without ticket is how outages repeat.

**Prevent** — Retention and disk forecasting, partition budget, synthetic produce/consume canaries, quarterly AZ and broker-loss game days, rolling upgrade runbooks, and post-incident actions tied to FAILURE_SCENARIOS ids.`,
    remember: [
      'URP/offline/disk before lag tuning',
      'One hot partition ≠ add consumers blindly',
      'Producer timeout often means ISR/minISR — not just client timeout.ms',
      'Every temp fix needs a permanent ticket',
    ],
    oneLiner: 'Detect cluster durability first, triage partition scope, fix root not symptom, prevent with capacity + game days.',
    trap: 'Raising max.poll.interval and buffer.memory on every lag alert without checking URP or poison offset.',
    tables: [
      {
        headers: ['Signal', 'Likely layer', 'First action'],
        rows: [
          ['OfflinePartitions', 'Broker/replication', 'Restore brokers; never unclean on money topics'],
          ['URP sustained', 'Follower lag/disk', 'Find lagging replica; throttle moves'],
          ['Lag one partition', 'Hot key / poison', 'Key skew or DLT; not more pods'],
          ['Lag all partitions', 'Handler/downstream', 'Trace processing; scale to partition count'],
          ['Rebalance storm', 'Consumer membership', 'Static id; fix GC; cooperative assignor'],
        ],
      },
    ],
  },
  {
    id: 'tempperm',
    part: 24,
    title: 'Temporary vs permanent fixes',
    lead: 'Temp fixes buy minutes; permanent fixes buy sleep. Interviewers and incident reviewers both punish “we increased the timeout” without topology or code follow-up.',
    body: `Use TEMP_PERM_ROWS as the canonical matrix. **Immediate** actions stop bleeding: scale to partition ceiling, shorten retention, throttle reassignment, circuit-break clients. **Permanent** actions change architecture or capacity: RF/rack/minISR, idempotent consumers, DLQ, tiered storage, partition/key redesign, ACL templates.

Why temp is dangerous: masking ISR illness with acks=1, skipping poison offsets, wildcard ACLs, and oversized buffers all convert a visible failure into silent data loss or security debt. Runbooks in this hub always pair temp steps with validation gates before closing incidents.`,
    remember: [
      'Temp without owner + deadline = permanent debt',
      'Never unclean leader election for financial topics as temp',
      'Scaling consumers past partition count is theater',
    ],
    oneLiner: 'Stabilize with temp, validate, then permanent fix or the incident repeats louder.',
    trap: 'Closing Sev1 when lag is flat but URP > 0.',
    tables: [{headers: ['Column', 'Purpose'], rows: TEMP_PERM_ROWS.slice(1).map((r) => [r[0], r[3]])}],
  },
  {
    id: 'incidents',
    part: 25,
    title: 'Incident scenario library',
    lead: `${FAILURE_SCENARIOS.length} production failure cards — each with symptoms, metrics, temp/permanent fix, and a staff-ready interviewAnswer.`,
    body: `Scenarios span the full failure surface: lag, disk, broker/AZ/region loss, ISR/URP/offline, controller and rebalance storms, hot partitions, slow consumers, network and DB, auth/ACL, ZK/KRaft legacy and modern, MM2 DR lag, duplicates/OOO/poison, resource exhaustion (disk, buffer, GC, bandwidth), offset commits, replica fetchers, and upgrade instability.

In war rooms, pick the card matching top metric, read symptoms to confirm, apply tempFix only with validation, then permanentFix before retro. Cross-link to runbooks for executable steps.`,
    remember: [
      'Match metric to scenario id — avoid random config churn',
      'interviewAnswer field = 60s verbal summary for staff loop',
      'Poison and hot partition both stall one partition — different fixes',
    ],
    oneLiner: 'Named scenarios turn 3am panic into a checklist.',
    trap: 'Treating MM2 lag as primary cluster lag — different cluster, different fix.',
  },
  {
    id: 'runbooks',
    part: 26,
    title: 'Operational runbooks',
    lead: `${RUNBOOKS.length} executable runbooks: lag, broker, disk, ISR, producer, consumer, controller, AZ, replication, hot partition.`,
    body: `Each runbook follows **first5 → check → temp → root → permanent → validation → prevention**. Severity guides paging: offline/disk/controller/quorum = Sev1; lag/replication = Sev2 unless payment SLO maps to Sev1.

Runbooks assume KRaft metadata, RF=3 rack-aware, minISR=2, unclean=false, idempotent producers, manual offset commit after idempotent side effects. Adjust names to your org but keep ordering: cluster before client, durability before throughput.`,
    remember: [
      'first5 is verbal — assign roles in incident channel',
      'validation gates before “resolved”',
      'prevention becomes next quarter OKR',
    ],
    oneLiner: 'Runbooks are ordered commands, not wiki essays.',
    trap: 'Running preferred leader election before brokers healthy — leadership churn on sick nodes.',
  },
  {
    id: 'semantics',
    part: 27,
    title: 'Delivery semantics — EOS vs ALO vs AMO + outbox/CDC',
    lead: 'Kafka guarantees broker log append semantics; your system guarantees business correctness. Payments need explicit semantics choice plus idempotency — never hand-wave “exactly-once”.',
    ascii: `
ALO (at-least-once)     Process then commit offset → dup on crash/rebalance
AMO (at-most-once)      Commit then process → loss on crash
EOS (broker txn)        Atomic consume+produce in Kafka — not external DB

External DB gap → Outbox (same TX as row) or CDC (Debezium) → Kafka
Effectively-once = ALO + idempotent consumer + business key UNIQUE
`,
    body: `**At-least-once (ALO)** — Default for consumers with manual commit after side effect. Crash before commit → redelivery → duplicates unless idempotent. **At-most-once (AMO)** — Commit before process: fast, loses messages on failure — rare except metrics. **Exactly-once semantics (EOS)** — Kafka transactional producer/consumer ties offset commit to downstream produce in broker; scope is Kafka-to-Kafka, not Kafka-to-PostgreSQL without extra design.

**Outbox pattern** — Business row + outbox row in one DB transaction; relay publishes to Kafka. Avoids dual-write gap. **CDC (Debezium)** — DB WAL → Kafka; ordering per table/key; schema evolution via Registry. Tradeoff: CDC lag and operational complexity vs app-owned outbox relay.

Staff answer: “We use ALO with idempotent ledger keyed by paymentId; EOS on Kafka fan-out where needed; outbox for domain events leaving the monolith boundary.”`,
    remember: [
      'EOS ≠ end-to-end exactly-once with DB',
      'read_committed hides aborted txn records — not dup fix',
      'Outbox and CDC both solve DB→Kafka reliably — pick ops model',
    ],
    oneLiner: 'Pick ALO + idempotency for money; EOS for Kafka-internal atomicity; outbox/CDC for DB boundary.',
    trap: 'Claiming enable.idempotence on producer alone makes settlement exactly-once.',
    tables: [
      {
        headers: ['Semantic', 'Dup risk', 'Loss risk', 'When'],
        rows: [
          ['ALO', 'Yes without idempotency', 'Low', 'Default payments consumer'],
          ['AMO', 'No', 'Yes on crash', 'Metrics, best-effort telemetry'],
          ['EOS (Kafka txn)', 'Reduced in broker scope', 'Low in scope', 'Consume-transform-produce in Kafka'],
          ['Outbox/CDC', 'Relay dup possible', 'Low with TX', 'Domain event publication from DB'],
        ],
      },
    ],
  },
  {
    id: 'security',
    part: 28,
    title: 'Security — TLS, SASL, ACLs + rolling upgrades',
    lead: 'Security and upgrade discipline are GO/NO-GO for production Kafka — PLAINTEXT clusters fail staff interviews instantly.',
    ascii: `
Client ──TLS──▶ Broker :9093
        SASL (SCRAM/OAUTH)
        ACL: principal → topic/group/cluster ops

Upgrade path:
  clients compatible → rolling brokers (one rack/AZ at a time)
  → bump inter.broker.protocol → finalize log.message.format.version
  → monitor URP/ISR each wave
`,
    body: `**TLS** — Encrypt on wire; broker listeners: INTERNAL vs EXTERNAL policies; certificate rotation with dual trust during window. **SASL** — SCRAM-SHA-512 common; OAuth/OIDC for enterprise SSO; never embed passwords in repos — use secret manager. **ACLs** — Least privilege per service account: PRODUCE/READ/DESCRIBE on named topics; READ on consumer group; CLUSTER Idempotent_Write for idempotent producers; regular audit and CI policy tests.

**Rolling upgrade** — Pre-check: client/broker version matrix, inter.broker.protocol.step, backup metadata. Execute: one broker at a time (or rack), wait URP=0 and stable ISR between waves, bump format version only after all brokers on new version. Rollback plan before starting — format bumps may be irreversible. Canary cluster or rack for major jumps.

Pair with auth failure and ACL deny scenarios — total outages, fix with canary pod before fleet.`,
    remember: [
      'Idempotent producer needs CLUSTER action ACL',
      'Upgrade URP during roll is expected briefly — sustained URP is stop signal',
      'Separate admin ACL from app service accounts',
    ],
    oneLiner: 'TLS+SASL on wire, ACL least-privilege, rolling upgrades with ISR gates between waves.',
    trap: 'Rolling all brokers simultaneously to “save time” — cluster-wide ISR risk.',
    tables: [
      {
        headers: ['Control', 'Purpose', 'Interview must mention'],
        rows: [
          ['TLS', 'Encryption in transit', 'Listener maps, cert rotation'],
          ['SASL/SCRAM', 'Authentication', 'Secret rotation, no PLAINTEXT prod'],
          ['ACL', 'Authorization', 'Per-topic/group, not wildcard prod'],
          ['Rolling upgrade', 'Safe version change', 'Protocol stepping, URP watch'],
        ],
      },
    ],
  },
];
