import type {PatternCard} from './types';
import {gofCard} from './card';

/** GoF behavioral patterns (Part 3). */
export const BEHAVIORAL_PATTERNS: PatternCard[] = [
  gofCard({
    id: "chain-of-responsibility",
    part: 3,
    name: "Chain of Responsibility",
    frequency: "Frequently used",
    definition: "Pass a payment through KYC \u2192 AML \u2192 fraud \u2192 limit handlers; any may stop the chain.",
    problem: "200-line if-else validation that cannot grow without merge conflicts.",
    realWorld: "PaymentValidationChainDemo: ordered handlers approve/reject Priya\u2019s \u20b945,000.",
    whyExists: "Independent checks that grow over time; open for new handlers.",
    ascii: "KYC \u2192 AML \u2192 Fraud \u2192 DailyLimit \u2192 (approved)\n  \u2502      \u2502      \u2502         \u2502\n reject reject reject   reject",
    flow: "Build chain \u2192 handle(request) \u2192 stop on reject or reach end.",
    components: [
    {name: "Handler", responsibility: "canHandle / handle / next"},
    {name: "Concrete handlers", responsibility: "KYC, AML, Fraud, Limit"},
    {name: "Chain builder", responsibility: "Wires order"},
  ],
    javaCode: "public abstract class PaymentHandler {\n  private PaymentHandler next;\n  public PaymentHandler link(PaymentHandler n) { this.next = n; return n; }\n  public final void handle(Payment p) {\n    if (!check(p)) throw new ValidationRejected(name());\n    if (next != null) next.handle(p);\n  }\n  protected abstract boolean check(Payment p);\n  protected abstract String name();\n}",
    springCode: "@Bean PaymentHandler paymentValidationChain(List<PaymentHandler> ordered) {\n  // sort by @Order and link\n}",
    unitTest: "@Test void stopsOnAml() {\n  assertThrows(ValidationRejected.class, () -> chain.handle(sanctionedPayee));\n}",
    edgeCases: [
    "Empty chain",
    "Handler order wrong",
    "Handler throws unexpectedly",
  ],
    failureScenarios: [
    "Fraud service timeout in handler",
    "Silent pass-through bug",
  ],
    retry: "Do not retry business rejects; retry transient infra inside handler.",
    idempotency: "Validation should be side-effect free or journaled.",
    timeout: "Per-handler budget; overall chain deadline.",
    observability: "validation_handler_total{handler,result}",
    security: "Fail closed on AML/fraud errors for high risk.",
    performance: "Short-circuit; avoid calling slow handlers when early reject.",
    scalability: "Stateless handlers; shared policy cache.",
    production: "Order via @Order; contract-test the chain.",
    mistakes: [
    "Handlers with side effects that cannot roll back",
  ],
    antiPatterns: [
    "Chain that always runs everything like Decorator",
  ],
    alternatives: [
    "Decorator stack",
    "Rules engine",
    "Pipeline of functions",
  ],
    tradeoffs: "Pros: extensible checks. Cons: order sensitivity; harder tracing.",
    interviewQs: [
    "Chain vs Decorator?",
    "Who decides the next handler?",
  ],
    trickyQs: [
    "Servlet filters \u2014 Chain of Responsibility?",
  ],
    seniorFollowUps: [
    "Sync chain vs async policy service?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/chainofresponsibility/PaymentValidationChainDemo.java",
  }),
  gofCard({
    id: "command",
    part: 3,
    name: "Command",
    frequency: "Frequently used",
    definition: "Turn \u201cdebit Priya \u20b945,000\u201d into an object you can queue, retry, audit, and undo.",
    problem: "Void method calls vanish on timeout \u2014 no idempotent retry or audit trail.",
    realWorld: "PaymentCommandDemo: DebitCommand with execute; queue/retry with idempotency key.",
    whyExists: "Actions need a life: schedule, audit, compensate.",
    ascii: "DebitCommand{key, account, amount}\n     \u2502 execute()\n     \u25bc\n Ledger + Outbox / queue",
    flow: "Build command \u2192 persist/queue \u2192 worker execute \u2192 record result.",
    components: [
    {name: "Command", responsibility: "execute / optionally undo"},
    {name: "Invoker / queue", responsibility: "Runs commands"},
    {name: "Receiver", responsibility: "Ledger / payment service"},
  ],
    javaCode: "public interface PaymentCommand { void execute(); }\npublic final class DebitCommand implements PaymentCommand {\n  private final String idempotencyKey; private final Ledger ledger;\n  private final String account; private final int amount;\n  public void execute() { ledger.debit(idempotencyKey, account, amount); }\n}",
    springCode: "// Outbox row = serialized command; worker deserializes and execute().",
    unitTest: "@Test void debitIsIdempotent() {\n  cmd.execute(); cmd.execute();\n  assertEquals(1, ledger.debitCount(account));\n}",
    edgeCases: [
    "Partial execute",
    "Undo after side effects escaped",
    "Poison message",
  ],
    failureScenarios: [
    "Worker crash after side effect before ack",
    "Duplicate delivery",
  ],
    retry: "At-least-once with idempotent execute.",
    idempotency: "Idempotency key is part of the command.",
    timeout: "Worker visibility timeout > max execute time.",
    observability: "command_execute_total{type,result}; queue lag",
    security: "Authorize before enqueue and at execute.",
    performance: "Batch commands where safe.",
    scalability: "Compete consumers on command queue.",
    production: "Prefer outbox + consumer over in-memory queue for money.",
    mistakes: [
    "Command without idempotency for money",
  ],
    antiPatterns: [
    "Command that is just a void service method rename",
  ],
    alternatives: [
    "Domain events",
    "Saga steps",
    "Job framework",
  ],
    tradeoffs: "Pros: retry/audit. Cons: more moving parts.",
    interviewQs: [
    "Command vs event?",
    "Do you need undo in banking?",
  ],
    trickyQs: [
    "Command in CQRS write side?",
  ],
    seniorFollowUps: [
    "Outbox command vs Kafka event naming?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/command/PaymentCommandDemo.java",
  }),
  gofCard({
    id: "interpreter",
    part: 3,
    name: "Interpreter",
    frequency: "Rare but interview-important",
    definition: "Evaluate a tiny rule language (amount > 50000 AND newPayee) against a payment context.",
    problem: "Compliance wants new rules without waiting for a full release cycle.",
    realWorld: "TransactionRuleInterpreterDemo: expression tree over payment attributes.",
    whyExists: "Small DSLs that business can own \u2014 not a full rules engine.",
    ascii: "AND\n \u251c\u2500 GT(amount, 50000)\n \u2514\u2500 EQ(newPayee, true)\n        \u2502 evaluate(ctx)\n        \u25bc true/false",
    flow: "Parse/build AST \u2192 evaluate against PaymentContext \u2192 allow/step-up.",
    components: [
    {name: "Expression", responsibility: "interpret(context)"},
    {name: "Terminal exprs", responsibility: "amount, flags"},
    {name: "Non-terminal", responsibility: "AND/OR/NOT"},
  ],
    javaCode: "public interface Expr { boolean eval(PaymentContext ctx); }\npublic record GtAmount(int threshold) implements Expr {\n  public boolean eval(PaymentContext ctx) { return ctx.amount() > threshold; }\n}\npublic record And(Expr left, Expr right) implements Expr {\n  public boolean eval(PaymentContext ctx) { return left.eval(ctx) && right.eval(ctx); }\n}",
    springCode: "// Store rule AST as JSON; version rules; canary new versions.",
    unitTest: "@Test void stepUpForNewPayeeLarge() {\n  Expr rule = new And(new GtAmount(50_000), new Flag(\"newPayee\"));\n  assertTrue(rule.eval(ctx(60_000, true)));\n}",
    edgeCases: [
    "Empty expression",
    "Unknown identifier",
    "Short-circuit OR/AND",
  ],
    failureScenarios: [
    "Grammar grows into accidental compiler",
    "Unsafe eval of user code",
  ],
    retry: "N/A \u2014 pure evaluation.",
    idempotency: "eval is pure.",
    timeout: "Bound eval time; reject huge ASTs.",
    observability: "rule_eval_total{ruleId,result}",
    security: "Never eval arbitrary scripts; allowlisted AST nodes only.",
    performance: "Compile/cache AST; avoid re-parse per payment.",
    scalability: "Stateless evaluators.",
    production: "Versioned rules; audit which ruleId fired.",
    mistakes: [
    "Parsing English prose",
    "Building Drools accidentally",
  ],
    antiPatterns: [
    "Interpreter for SQL joins across 12 tables",
  ],
    alternatives: [
    "Drools/Easy Rules",
    "Feature flags",
    "Hard-coded policy",
  ],
    tradeoffs: "Pros: business agility. Cons: DSL maintenance cost.",
    interviewQs: [
    "Interpreter vs Strategy?",
    "When to buy a rules engine?",
  ],
    trickyQs: [
    "Security of expression evaluation?",
  ],
    seniorFollowUps: [
    "Rule versioning and replay for disputes?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/interpreter/TransactionRuleInterpreterDemo.java",
  }),
  gofCard({
    id: "iterator",
    part: 3,
    name: "Iterator",
    frequency: "Occasionally used",
    definition: "Walk salary credits without exposing whether storage is CSV, DB cursor, or S3 stream.",
    problem: "Loading List of 4,000 credits OOMs the batch box; posting loop couples to ArrayList.",
    realWorld: "TransactionIteratorDemo: hasNext/next over transactions; posting loop stays stable.",
    whyExists: "Separate traversal from storage representation.",
    ascii: "PostingJob\n  while (it.hasNext()) post(it.next())\n         \u2502\n   FileIterator | DbCursorIterator | S3Iterator",
    flow: "Obtain iterator \u2192 consume \u2192 close resources in finally/try-with-resources.",
    components: [
    {name: "Iterator", responsibility: "hasNext/next"},
    {name: "Iterable source", responsibility: "File / DB / API pages"},
    {name: "Consumer", responsibility: "Posting loop"},
  ],
    javaCode: "public final class FileCreditIterator implements Iterator<Credit> {\n  private final BufferedReader reader; private String nextLine;\n  public boolean hasNext() { /* peek */ return nextLine != null; }\n  public Credit next() { return Credit.parse(nextLine); }\n}",
    springCode: "// Spring Data Page / Stream; always close ResultSet/Stream.",
    unitTest: "@Test void postsAll() {\n  int n = 0; for (Credit c : credits) { post(c); n++; }\n  assertEquals(3, n);\n}",
    edgeCases: [
    "Empty source",
    "Malformed mid-stream",
    "Fail to close cursor",
  ],
    failureScenarios: [
    "OOM from accidental collect(toList)",
    "Cursor timeout",
  ],
    retry: "Checkpoint offset; resume iterator from last ack.",
    idempotency: "Each credit post keyed.",
    timeout: "Statement/query timeout; job deadline.",
    observability: "iterator_items_total; lag; errors",
    security: "Authorize file/path access.",
    performance: "Streaming beats materializing.",
    scalability: "Partition files across workers.",
    production: "Prefer JDK Iterator/Stream; do not invent for ArrayList.",
    mistakes: [
    "Custom iterator over in-memory List for fashion",
  ],
    antiPatterns: [
    "Exposing internal array to callers",
  ],
    alternatives: [
    "Java Stream",
    "Reactive Flux",
    "Spring Batch reader",
  ],
    tradeoffs: "Pros: storage freedom. Cons: resource lifecycle discipline.",
    interviewQs: [
    "Iterator vs Stream?",
    "Fail-fast iterators?",
  ],
    trickyQs: [
    "Concurrent modification during iteration?",
  ],
    seniorFollowUps: [
    "Exactly-once batch with iterator checkpoints?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/iterator/TransactionIteratorDemo.java",
  }),
  gofCard({
    id: "mediator",
    part: 3,
    name: "Mediator",
    frequency: "Occasionally used",
    definition: "Route colleague services through a settlement hub so fraud/ledger/notify do not import each other.",
    problem: "Spaghetti cycles: fraud\u2192ledger\u2192notify\u2192fraud.",
    realWorld: "OrderProcessingMediatorDemo: mediator coordinates order steps; colleagues know only the hub.",
    whyExists: "Centralize complex interaction; reduce N\u00d7N coupling.",
    ascii: "Fraud \u2500\u2510\nLedger \u2500\u253c\u2192 SettlementMediator\nNotify \u2500\u2518",
    flow: "Event to mediator \u2192 mediator calls colleagues in order \u2192 colleagues never call peers.",
    components: [
    {name: "Mediator", responsibility: "Orchestrates conversation"},
    {name: "Colleagues", responsibility: "Fraud, ledger, notify"},
    {name: "Client", responsibility: "Starts the flow"},
  ],
    javaCode: "public final class SettlementMediator {\n  private final FraudService fraud; private final Ledger ledger; private final Notify notify;\n  public void onAuthorized(Payment p) {\n    fraud.record(p);\n    ledger.post(p);\n    notify.sms(p);\n  }\n}",
    springCode: "// @Service mediator; or Camunda/Temporal for long-running mediation.",
    unitTest: "@Test void postsThenNotifies() {\n  mediator.onAuthorized(p);\n  inOrder.verify(ledger).post(p);\n  inOrder.verify(notify).sms(p);\n}",
    edgeCases: [
    "Mediator god object",
    "Sync vs async colleagues",
    "Partial failure",
  ],
    failureScenarios: [
    "Notify fails after post \u2014 need outbox",
    "Deadlock if colleagues callback incorrectly",
  ],
    retry: "Outbox for side effects; idempotent colleague APIs.",
    idempotency: "Mediator entry keyed by payment id.",
    timeout: "Overall orchestration budget.",
    observability: "mediator_flows_total{flow,result}; step spans",
    security: "AuthZ at mediator entry.",
    performance: "Avoid chatty sync fan-out; parallelize independent steps.",
    scalability: "Stateless mediator + durable workflow engine for long sagas.",
    production: "Split mediators by bounded context when hub grows.",
    mistakes: [
    "Mediator that knows the whole bank",
  ],
    antiPatterns: [
    "Mediator for two services that should call directly",
  ],
    alternatives: [
    "Observer (broadcast)",
    "Saga orchestrator",
    "Facade",
  ],
    tradeoffs: "Pros: decoupled colleagues. Cons: hub complexity.",
    interviewQs: [
    "Mediator vs Observer?",
    "Mediator vs Facade?",
  ],
    trickyQs: [
    "Is Kafka a mediator?",
  ],
    seniorFollowUps: [
    "In-proc mediator vs Temporal workflow?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/mediator/OrderProcessingMediatorDemo.java",
  }),
  gofCard({
    id: "memento",
    part: 3,
    name: "Memento",
    frequency: "Specialized",
    definition: "Snapshot and restore an object\u2019s state (fee table) without breaking encapsulation.",
    problem: "Ops published bad NEFT fees at 10:02; need restore to 09:55 without exposing internals.",
    realWorld: "PaymentConfigurationMementoDemo: caretaker stores opaque mementos; originator restores.",
    whyExists: "In-model undo for carefully sized objects.",
    ascii: "FeeEngine (originator)\n    \u2502 createMemento() / restore()\nCaretaker list[m0,m1,m2]",
    flow: "Before change \u2192 memento \u2192 mutate \u2192 on bad publish restore previous.",
    components: [
    {name: "Originator", responsibility: "FeeEngine \u2014 only one who reads memento guts"},
    {name: "Memento", responsibility: "Opaque snapshot"},
    {name: "Caretaker", responsibility: "Stores history"},
  ],
    javaCode: "public final class FeeEngine {\n  private Map<String, Integer> fees;\n  public Memento snapshot() { return new Memento(Map.copyOf(fees)); }\n  public void restore(Memento m) { this.fees = new HashMap<>(m.state()); }\n  public static final class Memento {\n    private final Map<String, Integer> state;\n    private Memento(Map<String, Integer> s) { this.state = s; }\n    private Map<String, Integer> state() { return state; }\n  }\n}",
    springCode: "// Versioned JSON in DB; only FeeEngine deserializes.",
    unitTest: "@Test void rollback() {\n  var m = engine.snapshot();\n  engine.set(\"NEFT\", 0);\n  engine.restore(m);\n  assertEquals(500, engine.get(\"NEFT\"));\n}",
    edgeCases: [
    "Huge object graphs",
    "Memento leaks internals via public getters",
    "Clock skew on versions",
  ],
    failureScenarios: [
    "Restore wrong version",
    "Partial restore",
  ],
    retry: "N/A",
    idempotency: "restore to same memento is idempotent.",
    timeout: "N/A",
    observability: "memento_restore_total{originator}",
    security: "Mementos may contain sensitive config \u2014 encrypt at rest.",
    performance: "Snapshot cost grows with state size.",
    scalability: "Not for whole-bank state \u2014 use event sourcing.",
    production: "Bound what is snapshottable; prefer audit+event sourcing for money.",
    mistakes: [
    "Public memento fields",
    "Snapshotting mutable shared refs",
  ],
    antiPatterns: [
    "Calling DB backups Memento",
  ],
    alternatives: [
    "Event sourcing",
    "Git-like config repo",
    "Audit log only",
  ],
    tradeoffs: "Pros: clean undo. Cons: memory/version management.",
    interviewQs: [
    "Memento vs serializable DTO?",
    "Memento vs event sourcing?",
  ],
    trickyQs: [
    "How does Java module/encapsulation help?",
  ],
    seniorFollowUps: [
    "Fee config rollback vs ledger compensating tx?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/memento/PaymentConfigurationMementoDemo.java",
  }),
  gofCard({
    id: "observer",
    part: 3,
    name: "Observer",
    frequency: "Frequently used",
    definition: "Publish PaymentPosted once; SMS, email, analytics, MIS listeners react independently.",
    problem: "Ledger importing NotifyService creates brittle coupling and transactional confusion.",
    realWorld: "PaymentObserverDemo + Kafka: listeners fan out; posting must not roll back if SMS fails.",
    whyExists: "One fact, many independent reactions.",
    ascii: "Ledger \u2500publish\u2192 PaymentPosted\n                    \u251c\u2500 NotifyListener\n                    \u251c\u2500 ProjectionListener\n                    \u2514\u2500 MisFileListener",
    flow: "State change \u2192 event \u2192 observers handle asynchronously / in-process.",
    components: [
    {name: "Subject", responsibility: "Payment service / event bus"},
    {name: "Event", responsibility: "PaymentPosted"},
    {name: "Observers", responsibility: "Notify, projection, MIS"},
  ],
    javaCode: "public interface PaymentListener { void onPosted(PaymentPosted e); }\npublic final class PaymentSubject {\n  private final List<PaymentListener> listeners = new CopyOnWriteArrayList<>();\n  public void subscribe(PaymentListener l) { listeners.add(l); }\n  public void post(Payment p) {\n    // persist\u2026\n    var e = new PaymentPosted(p.id());\n    listeners.forEach(l -> l.onPosted(e));\n  }\n}",
    springCode: "@TransactionalEventListener(phase = AFTER_COMMIT)\nvoid onPosted(PaymentPosted e) { notifyService.sms(e); }\n// Production: Kafka topic payment.posted",
    unitTest: "@Test void fansOut() {\n  subject.subscribe(sms); subject.subscribe(mis);\n  subject.post(p);\n  verify(sms).onPosted(any()); verify(mis).onPosted(any());\n}",
    edgeCases: [
    "Listener throws",
    "Ordering of listeners",
    "Re-entrancy",
  ],
    failureScenarios: [
    "SMS fails \u2014 must not undo money",
    "Duplicate events at-least-once",
  ],
    retry: "Per-listener retry + DLQ; never couple to publisher txn after commit.",
    idempotency: "Listeners idempotent on event id.",
    timeout: "Listener processing budgets; Kafka max.poll.interval.",
    observability: "events_published; consumer lag; listener errors",
    security: "Events without secrets; authorize consumers.",
    performance: "Async fan-out; batch where possible.",
    scalability: "Kafka consumer groups per listener type.",
    production: "AFTER_COMMIT + outbox \u2192 Kafka is grown-up Observer.",
    mistakes: [
    "Doing critical sync work in observer that must be atomic with post",
  ],
    antiPatterns: [
    "Observer as a fake mediator conversation",
  ],
    alternatives: [
    "Mediator",
    "Explicit facade calls",
    "CDC",
  ],
    tradeoffs: "Pros: decoupling. Cons: eventual consistency complexity.",
    interviewQs: [
    "Observer vs Mediator?",
    "In-process vs Kafka?",
  ],
    trickyQs: [
    "Transactional EventListener pitfalls?",
  ],
    seniorFollowUps: [
    "Outbox pattern with Observer semantics?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/observer/PaymentObserverDemo.java",
  }),
  gofCard({
    id: "state",
    part: 3,
    name: "State",
    frequency: "Frequently used",
    definition: "Payment behavior follows lifecycle: CREATED \u2192 AUTHORIZED \u2192 POSTED \u2192 SETTLED; illegal ops throw.",
    problem: "Giant switch on status enum scattered across services; illegal refunds slip through.",
    realWorld: "PaymentStateDemo: each state object implements legal verbs; refund illegal in CREATED.",
    whyExists: "Make illegal transitions impossible by construction.",
    ascii: "CREATED \u2500authorize\u2192 AUTHORIZED \u2500post\u2192 POSTED \u2500settle\u2192 SETTLED\n   \u2502 refund? NO              \u2502 refund? YES",
    flow: "Context holds State \u2192 method delegates to state \u2192 state may transition context.",
    components: [
    {name: "PaymentContext", responsibility: "Holds current state"},
    {name: "State interface", responsibility: "authorize/post/refund"},
    {name: "Concrete states", responsibility: "Created/Authorized/Posted/Settled"},
  ],
    javaCode: "public interface PaymentState {\n  void authorize(PaymentContext ctx);\n  void refund(PaymentContext ctx);\n}\npublic final class CreatedState implements PaymentState {\n  public void authorize(PaymentContext ctx) { ctx.setState(new AuthorizedState()); }\n  public void refund(PaymentContext ctx) { throw new IllegalStateException(\"CREATED\"); }\n}",
    springCode: "// Persist status enum; rebuild state object on load via factory.",
    unitTest: "@Test void cannotRefundCreated() {\n  assertThrows(IllegalStateException.class, () -> payment.refund());\n}",
    edgeCases: [
    "Concurrent transitions",
    "Persisting state vs object",
    "Compensating transitions",
  ],
    failureScenarios: [
    "DB status updated without state object",
    "Lost update on concurrent authorize",
  ],
    retry: "Optimistic locking on status version.",
    idempotency: "authorize twice from CREATED should be safe (already AUTHORIZED).",
    timeout: "N/A for in-memory; rail calls have timeouts.",
    observability: "payment_state_transitions_total{from,to}",
    security: "AuthZ per verb (refund vs authorize).",
    performance: "State objects can be flyweight singletons if immutable.",
    scalability: "Status in DB; horizontal services with locking.",
    production: "Pair with optimistic locking / conditional updates.",
    mistakes: [
    "Enum alone without behavior encapsulation",
  ],
    antiPatterns: [
    "State machine library for a boolean",
  ],
    alternatives: [
    "Strategy (you pick algorithm)",
    "XState/external FSM",
  ],
    tradeoffs: "Pros: safe lifecycle. Cons: more classes; persistence mapping.",
    interviewQs: [
    "State vs Strategy?",
    "How do you persist State?",
  ],
    trickyQs: [
    "Null Object state?",
  ],
    seniorFollowUps: [
    "Distributed state machine across microservices?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/state/PaymentStateDemo.java",
  }),
  gofCard({
    id: "strategy",
    part: 3,
    name: "Strategy",
    frequency: "Frequently used",
    definition: "Swap interchangeable algorithms for the same verb \u2014 UPI vs Card vs PayPal payment processing.",
    problem: "Sprawling switch on method codes inside one service method.",
    realWorld: "PaymentStrategyDemo: PaymentMethodRouter EnumMap \u2192 Upi/Card/Paypal/BankTransfer strategies.",
    whyExists: "OCP for algorithms; context stays stable.",
    ascii: "PaymentService.process(method, request)\n        \u2502\n  EnumMap \u2192 PaymentStrategy.pay()",
    flow: "Resolve strategy from method \u2192 validate capabilities \u2192 pay().",
    components: [
    {name: "PaymentStrategy", responsibility: "Algorithm interface"},
    {name: "Concrete strategies", responsibility: "UPI/Card/PayPal/Bank"},
    {name: "Router / context", responsibility: "Selects strategy"},
  ],
    javaCode: "public interface PaymentStrategy {\n  PaymentReceipt pay(PaymentRequest request);\n  boolean supportsRecurring();\n}\npublic final class PaymentMethodRouter {\n  private final Map<PaymentMethod, PaymentStrategy> strategies = new EnumMap<>(PaymentMethod.class);\n  public PaymentStrategy resolve(PaymentMethod method) { return strategies.get(method); }\n}",
    springCode: "@Component\nclass PaymentStrategies {\n  private final Map<PaymentMethod, PaymentStrategy> map;\n  PaymentStrategies(List<PaymentStrategy> all) { /* index */ }\n}",
    unitTest: "@Test void rejectsRecurringUpi() {\n  assertThrows(IllegalArgumentException.class,\n    () -> service.process(UPI, recurringRequest));\n}",
    edgeCases: [
    "Unknown method",
    "Null strategy registration",
    "Strategy with state",
  ],
    failureScenarios: [
    "Missing bean for new rail",
    "Strategy throws after partial side effect",
  ],
    retry: "Per-strategy idempotency keys.",
    idempotency: "Strategies must honor idempotency for money.",
    timeout: "Per-rail timeouts differ (UPI vs NEFT file).",
    observability: "strategy_pay_total{method,result}",
    security: "PCI scope isolation for card strategy.",
    performance: "O(1) map dispatch.",
    scalability: "Stateless strategies.",
    production: "Register via Spring; fail on unknown keys.",
    mistakes: [
    "Stateful strategies shared across requests",
  ],
    antiPatterns: [
    "Interface with one implementation forever",
  ],
    alternatives: [
    "Factory Method",
    "Template Method",
    "State",
  ],
    tradeoffs: "Pros: clean OCP. Cons: indirection for simple cases.",
    interviewQs: [
    "Strategy vs State?",
    "Strategy vs Template Method?",
  ],
    trickyQs: [
    "Strategy vs polymorphism alone?",
  ],
    seniorFollowUps: [
    "Pricing + FX + rail \u2014 nested strategies?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/strategy/PaymentStrategyDemo.java",
  }),
  gofCard({
    id: "template-method",
    part: 3,
    name: "Template Method",
    frequency: "Occasionally used",
    definition: "Fix the skeleton validate \u2192 book \u2192 notify; subclasses fill book() for NEFT vs RTGS.",
    problem: "Every clearing run must enforce the same policy order; free-form inheritance skips validate.",
    realWorld: "PaymentProcessingTemplateDemo: final execute() calls steps; subclasses override hooks.",
    whyExists: "Regulation/policy is the skeleton; product only fills chapters.",
    ascii: "ClearingJob.execute() [final]\n  1 validate()\n  2 book()      \u2190 subclass\n  3 notify()",
    flow: "Base final method calls overridable steps in fixed order.",
    components: [
    {name: "AbstractClearingJob", responsibility: "Template with final execute"},
    {name: "NeftClearingJob", responsibility: "Implements book via file"},
    {name: "RtgsClearingJob", responsibility: "Implements book via wire"},
  ],
    javaCode: "public abstract class ClearingJob {\n  public final void execute() {\n    validate();\n    book();\n    notifyParties();\n  }\n  protected void validate() { /* common */ }\n  protected abstract void book();\n  protected void notifyParties() { /* common */ }\n}",
    springCode: "// Prefer composition pipelines if skeleton itself changes often.",
    unitTest: "@Test void cannotSkipValidate() {\n  // execute() always calls validate before book \u2014 verified via spy\n}",
    edgeCases: [
    "Hook called twice",
    "Subclass breaking LSP",
    "Too many hooks",
  ],
    failureScenarios: [
    "Inheritance fight when skeleton changes",
    "Hidden side effects in base",
  ],
    retry: "Idempotent book step.",
    idempotency: "execute keyed by job run id.",
    timeout: "Job deadline around execute().",
    observability: "clearing_job_steps{step,result}",
    security: "Common validate enforces policy.",
    performance: "Fine for batch.",
    scalability: "One job instance per partition.",
    production: "If skeleton churns, switch to Strategy/pipeline.",
    mistakes: [
    "Forcing inheritance when Strategy fits",
  ],
    antiPatterns: [
    "Template with 20 empty hooks",
  ],
    alternatives: [
    "Strategy for whole algorithm",
    "Pipeline of functions",
  ],
    tradeoffs: "Pros: enforced policy. Cons: brittle inheritance.",
    interviewQs: [
    "Template Method vs Strategy?",
    "Hollywood principle?",
  ],
    trickyQs: [
    "Java HttpServlet \u2014 Template Method?",
  ],
    seniorFollowUps: [
    "Replace inheritance template with composable steps?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/templatemethod/PaymentProcessingTemplateDemo.java",
  }),
  gofCard({
    id: "visitor",
    part: 3,
    name: "Visitor",
    frequency: "Rare but interview-important",
    definition: "Add new operations (GST, TDS, audit PDF) over a stable account type hierarchy via double dispatch.",
    problem: "Reports multiply monthly; editing Savings/Loan/Card for each report is painful.",
    realWorld: "AccountVisitorDemo: account.accept(visitor) for GST/audit/statement visitors.",
    whyExists: "Stable types, exploding operations \u2014 add visitors, not product classes.",
    ascii: "Savings.accept(GstVisitor)\nLoan.accept(GstVisitor)\nCard.accept(GstVisitor)",
    flow: "Client picks visitor \u2192 elements accept \u2192 visitor.visitConcrete(element).",
    components: [
    {name: "Visitor", responsibility: "visitSavings/visitLoan/\u2026"},
    {name: "Element", responsibility: "accept(Visitor)"},
    {name: "Concrete visitors", responsibility: "GST, TDS, Audit"},
  ],
    javaCode: "public interface AccountVisitor {\n  void visit(Savings a);\n  void visit(Loan a);\n}\npublic interface Account {\n  void accept(AccountVisitor v);\n}\npublic final class Savings implements Account {\n  public void accept(AccountVisitor v) { v.visit(this); }\n}",
    springCode: "// Register visitors as @Component; run month-end job per visitor.",
    unitTest: "@Test void gstVisitsSavings() {\n  var v = new GstVisitor();\n  savings.accept(v);\n  assertTrue(v.sawSavings());\n}",
    edgeCases: [
    "New account type breaks all visitors",
    "Visitor with mutable shared state",
    "Null element",
  ],
    failureScenarios: [
    "Adding product types weekly \u2014 Visitor tax",
    "Partial visitor run",
  ],
    retry: "Restart month-end visitor job idempotently.",
    idempotency: "Visitor outputs keyed by period+account.",
    timeout: "Batch window for month-end.",
    observability: "visitor_accounts_total{visitor,type}",
    security: "Authorize report generation.",
    performance: "Single walk per visitor; or combined visitors carefully.",
    scalability: "Partition accounts across workers.",
    production: "Use when types are stable; otherwise ordinary methods.",
    mistakes: [
    "Visitor when types change more than ops",
  ],
    antiPatterns: [
    "Visitor for one operation on one type",
  ],
    alternatives: [
    "Pattern matching switch (Java 21)",
    "Sealed interfaces + methods",
  ],
    tradeoffs: "Pros: easy new ops. Cons: hard new types.",
    interviewQs: [
    "When is Visitor worth it?",
    "Double dispatch explained?",
  ],
    trickyQs: [
    "Visitor vs pattern matching in modern Java?",
  ],
    seniorFollowUps: [
    "Sealed account hierarchy + switch vs classic Visitor?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/behavioral/visitor/AccountVisitorDemo.java",
  }),
];
