import type {PatternCard} from './types';
import {gofCard} from './card';

/** GoF creational patterns (Part 1). */
export const CREATIONAL_PATTERNS: PatternCard[] = [
  gofCard({
    id: "singleton",
    part: 1,
    name: "Singleton",
    frequency: "Occasionally used",
    definition: "Ensure one shared instance of a process-global resource \u2014 holiday calendar, UTR sequence, config cache.",
    problem: "Duplicate ConfigManager / HolidayCalendar instances drift under concurrency: fraud thinks Monday is a holiday, ledger does not.",
    realWorld: "Meridian Bank lab: ConfigManagerDemo uses Bill Pugh holder + enum singleton; Spring @Bean singleton is the production form.",
    whyExists: "Some things are truly singular. Without a controlled single instance, caches and sequences diverge and audits fail.",
    ascii: "Caller \u2192 ConfigManager.getInstance()\n           \u2502\n      Holder.INSTANCE (one JVM)\n           \u2502\n   payment.timeout / fraud.threshold",
    flow: "Boot \u2192 Holder initializes once \u2192 all callers read same map \u2192 never new ConfigManager().",
    components: [
    {name: "ConfigManager", responsibility: "Holds shared config map; private ctor"},
    {name: "Holder", responsibility: "Initialization-on-demand; JVM class-init safety"},
    {name: "EnumConfigManager", responsibility: "Enum singleton alternative for region flags"},
  ],
    javaCode: "public final class ConfigManager {\n  private final Map<String, String> config =\n      Map.of(\"payment.timeout\", \"30s\", \"fraud.threshold\", \"5000\");\n  private ConfigManager() {}\n  private static class Holder {\n    private static final ConfigManager INSTANCE = new ConfigManager();\n  }\n  public static ConfigManager getInstance() { return Holder.INSTANCE; }\n  public String get(String key) { return config.get(key); }\n}",
    springCode: "@Configuration\nclass BankingSingletons {\n  @Bean\n  HolidayCalendar holidayCalendar() {\n    return HolidayCalendar.loadFrom(\"classpath:rbi-holidays.json\");\n  }\n}",
    unitTest: "@Test void sameInstance() {\n  assertSame(ConfigManager.getInstance(), ConfigManager.getInstance());\n}",
    edgeCases: [
    "Classloader duplicates in app servers",
    "Mutable singleton state races",
    "Test pollution from static reset",
  ],
    failureScenarios: [
    "Config reload mid-flight without versioning",
    "Two JVMs each with own singleton \u2014 not cluster-wide",
  ],
    retry: "N/A \u2014 reads are local; retry config remote fetch with backoff at boot.",
    idempotency: "get() is side-effect free.",
    timeout: "Remote config load at boot \u2264 5s; fail fast if missing required keys.",
    observability: "config_reload_total; gauge config_keys; never log secrets.",
    security: "Treat config as sensitive; restrict who can mutate.",
    performance: "O(1) map lookup; avoid locking on hot path (immutable map).",
    scalability: "Per-JVM only \u2014 use Redis/DB for cluster-wide sequence.",
    production: "Prefer Spring singleton beans over hand-rolled static; use enum/holder when you must.",
    mistakes: [
    "God-object singleton",
    "Double-checked locking without volatile",
  ],
    antiPatterns: [
    "Mutable global balance cache named Singleton",
  ],
    alternatives: [
    "Spring @Bean singleton",
    "Enum singleton",
    "External config service",
  ],
    tradeoffs: "Pros: one source of truth per JVM. Cons: hard to fake in tests; not distributed.",
    interviewQs: [
    "Enum vs Bill Pugh vs DCL?",
    "Is a Spring bean a Singleton?",
    "How do you test without static reset?",
  ],
    trickyQs: [
    "Two classloaders \u2014 two singletons?",
    "Cluster-wide uniqueness?",
  ],
    seniorFollowUps: [
    "When is a process singleton wrong for multi-tenant SaaS?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/creational/singleton/ConfigManagerDemo.java",
  }),
  gofCard({
    id: "factory-method",
    part: 1,
    name: "Factory Method",
    frequency: "Frequently used",
    definition: "Let a creator decide which PaymentRail / PaymentGateway implementation to instantiate.",
    problem: "Controllers call new UpiGateway() \u2014 adding IMPS means editing every call site.",
    realWorld: "PaymentGatewayFactoryDemo: method=UPI|CARD|NEFT \u2192 concrete gateway; Pay button stays stable.",
    whyExists: "Open/closed: new rails without rewriting orchestration.",
    ascii: "PayController \u2192 PaymentGatewayFactory.create(method)\n                 \u251c\u2500 UPI \u2192 UpiGateway\n                 \u251c\u2500 CARD \u2192 CardGateway\n                 \u2514\u2500 NEFT \u2192 NeftGateway",
    flow: "Request method \u2192 factory maps to interface \u2192 caller uses PaymentGateway only.",
    components: [
    {name: "PaymentGateway", responsibility: "Product interface (authorize/capture)"},
    {name: "Concrete gateways", responsibility: "UPI / Card / NEFT implementations"},
    {name: "PaymentGatewayFactory", responsibility: "Chooses concrete product from method code"},
  ],
    javaCode: "public interface PaymentGateway { String charge(int amount); }\npublic final class UpiGateway implements PaymentGateway {\n  public String charge(int amount) { return \"upi:\" + amount; }\n}\npublic final class PaymentGatewayFactory {\n  public PaymentGateway create(String method) {\n    return switch (method) {\n      case \"UPI\" -> new UpiGateway();\n      case \"CARD\" -> new CardGateway();\n      case \"NEFT\" -> new NeftGateway();\n      default -> throw new IllegalArgumentException(method);\n    };\n  }\n}",
    springCode: "@Component\nclass SpringPaymentGatewayFactory {\n  private final Map<String, PaymentGateway> byMethod;\n  SpringPaymentGatewayFactory(List<PaymentGateway> all) {\n    this.byMethod = all.stream().collect(toMap(PaymentGateway::method, identity()));\n  }\n  PaymentGateway create(String method) {\n    return Optional.ofNullable(byMethod.get(method))\n        .orElseThrow(() -> new IllegalArgumentException(method));\n  }\n}",
    unitTest: "@Test void createsUpi() {\n  assertInstanceOf(UpiGateway.class, new PaymentGatewayFactory().create(\"UPI\"));\n}",
    edgeCases: [
    "Unknown method code",
    "Null method",
    "Case sensitivity of codes",
  ],
    failureScenarios: [
    "Missing Spring bean for new rail",
    "Factory returns wrong currency rail",
  ],
    retry: "Creation is local; retry downstream charge with idempotency key.",
    idempotency: "Factory create is pure; charge needs idempotency key.",
    timeout: "Factory O(1); gateway charge timeout separate (e.g. 3s).",
    observability: "gateway_factory_selected_total{method}",
    security: "Whitelist method codes \u2014 never Class.forName(clientInput).",
    performance: "Map/registry dispatch O(1).",
    scalability: "Stateless factory scales with service replicas.",
    production: "Register gateways via Spring Map / List injection.",
    mistakes: [
    "Giant switch that also charges",
    "Returning concrete types to controllers",
  ],
    antiPatterns: [
    "Reflection Class.forName(clientInput)",
  ],
    alternatives: [
    "Strategy registry",
    "Abstract Factory when a whole kit must match",
  ],
    tradeoffs: "Pros: OCP for new rails. Cons: switch/map must stay complete.",
    interviewQs: [
    "Factory Method vs Simple Factory?",
    "Factory Method vs Strategy?",
  ],
    trickyQs: [
    "When does Factory Method become Abstract Factory?",
  ],
    seniorFollowUps: [
    "How do you version rails without breaking old clients?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/creational/factory/PaymentGatewayFactoryDemo.java",
  }),
  gofCard({
    id: "abstract-factory",
    part: 1,
    name: "Abstract Factory",
    frequency: "Occasionally used",
    definition: "Create a matching family of related products (currency + rail + regulator pack) without mixing kits.",
    problem: "India UPI wired to a USD ledger \u2014 incompatible family members leak into production.",
    realWorld: "RegionalBankingFactoryDemo: IndiaFactory vs UsFactory produce compatible Account/Rail/Report trio.",
    whyExists: "Some objects only make sense together; the factory encodes that invariant.",
    ascii: "RegionalBankingFactory\n  \u251c\u2500 IndiaFactory \u2192 InrAccount + UpiRail + RbiReport\n  \u2514\u2500 UsFactory    \u2192 UsdAccount + AchRail + FedReport",
    flow: "Pick region \u2192 factory \u2192 createAccount/createRail/createReport \u2192 use as a set.",
    components: [
    {name: "RegionalBankingFactory", responsibility: "Abstract factory interface"},
    {name: "IndiaFactory / UsFactory", responsibility: "Concrete families"},
    {name: "Account / Rail / Report", responsibility: "Abstract products"},
  ],
    javaCode: "public interface RegionalBankingFactory {\n  Account createAccount();\n  PaymentRail createRail();\n  RegulatoryReport createReport();\n}\npublic final class IndiaFactory implements RegionalBankingFactory {\n  public Account createAccount() { return new InrAccount(); }\n  public PaymentRail createRail() { return new UpiRail(); }\n  public RegulatoryReport createReport() { return new RbiMisReport(); }\n}",
    springCode: "@Configuration\n@Profile(\"region-in\")\nclass IndiaBankingConfig {\n  @Bean RegionalBankingFactory regionalBankingFactory() { return new IndiaFactory(); }\n}",
    unitTest: "@Test void indiaFamilyMatches() {\n  var f = new IndiaFactory();\n  assertEquals(\"INR\", f.createAccount().currency());\n  assertEquals(\"UPI\", f.createRail().code());\n}",
    edgeCases: [
    "Cross-region FX corridors",
    "Partial family when a product is shared",
  ],
    failureScenarios: [
    "Wrong @Profile active in prod",
    "Mixing products from two factories",
  ],
    retry: "N/A at creation; rail calls retry separately.",
    idempotency: "Family creation is pure.",
    timeout: "Boot-time factory wiring only.",
    observability: "region_factory_active{region}",
    security: "Region from trusted config, not raw client header alone.",
    performance: "One factory per JVM/region context.",
    scalability: "Per-region services often isolate factories.",
    production: "Profile or tenant \u2192 factory; assert family invariants in IT.",
    mistakes: [
    "Abstract Factory for a single varying product",
  ],
    antiPatterns: [
    "God factory creating unrelated HR + ATM objects",
  ],
    alternatives: [
    "Factory Method",
    "Spring @Configuration per region",
  ],
    tradeoffs: "Pros: family integrity. Cons: more types; overkill for one product.",
    interviewQs: [
    "Abstract Factory vs Factory Method?",
    "How do you prevent kit mixing?",
  ],
    trickyQs: [
    "Can products share across families?",
  ],
    seniorFollowUps: [
    "Multi-region tenant on one JVM \u2014 how do you scope factories?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/creational/abstractfactory/RegionalBankingFactoryDemo.java",
  }),
  gofCard({
    id: "builder",
    part: 1,
    name: "Builder",
    frequency: "Frequently used",
    definition: "Assemble a complex PaymentTransaction with many optional fields without telescoping constructors.",
    problem: "20-arg constructors hide which fields are set; optional remarks/GSTIN/split become bug magnets.",
    realWorld: "PaymentTransactionBuilderDemo: amount, payee, remarks, GSTIN built step-by-step; validate before build().",
    whyExists: "Readable construction + validation at the end of the fluent chain.",
    ascii: "new PaymentTransaction.Builder()\n  .amount(45000).payee(vpa).remarks(\"rent\")\n  .gstin(...).build()",
    flow: "Fluent setters \u2192 validate requireds \u2192 immutable PaymentTransaction.",
    components: [
    {name: "PaymentTransaction", responsibility: "Immutable product"},
    {name: "Builder", responsibility: "Fluent assembly + validation"},
    {name: "Caller", responsibility: "Controller / use-case fills the form"},
  ],
    javaCode: "public final class PaymentTransaction {\n  private final int amount; private final String payee; private final String remarks;\n  private PaymentTransaction(Builder b) {\n    this.amount = b.amount; this.payee = b.payee; this.remarks = b.remarks;\n  }\n  public static final class Builder {\n    private int amount; private String payee; private String remarks = \"\";\n    public Builder amount(int a) { this.amount = a; return this; }\n    public Builder payee(String p) { this.payee = p; return this; }\n    public Builder remarks(String r) { this.remarks = r; return this; }\n    public PaymentTransaction build() {\n      if (amount <= 0 || payee == null || payee.isBlank())\n        throw new IllegalStateException(\"amount/payee required\");\n      return new PaymentTransaction(this);\n    }\n  }\n}",
    springCode: "// Prefer Java records + builder for DTOs; MapStruct for API\u2192domain mapping.",
    unitTest: "@Test void rejectsMissingPayee() {\n  assertThrows(IllegalStateException.class,\n    () -> new PaymentTransaction.Builder().amount(100).build());\n}",
    edgeCases: [
    "Reuse builder after build",
    "Default vs explicit null",
    "Money scale/currency",
  ],
    failureScenarios: [
    "Partial build published to Kafka",
    "Validation rules diverge from API schema",
  ],
    retry: "Rebuild on validation failure with corrected fields.",
    idempotency: "build() should be pure given same inputs.",
    timeout: "N/A",
    observability: "builder_validation_failures_total{field}",
    security: "Sanitize remarks; never put PAN in builder logs.",
    performance: "Negligible vs I/O.",
    scalability: "Builders are per-request \u2014 no shared mutable builder.",
    production: "Lombok @Builder OK if validate in build(); prefer explicit for money.",
    mistakes: [
    "Mutable product after build",
    "No validation in build()",
  ],
    antiPatterns: [
    "Telescoping constructors + builder half-migration",
  ],
    alternatives: [
    "Factory Method",
    "Canonical constructor for 2\u20133 fields",
  ],
    tradeoffs: "Pros: clarity. Cons: boilerplate; overkill for tiny types.",
    interviewQs: [
    "Builder vs Factory?",
    "How do you make Builder thread-safe?",
  ],
    trickyQs: [
    "Should build() return Optional or throw?",
  ],
    seniorFollowUps: [
    "Money/BigDecimal builder \u2014 scale and rounding policy?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/creational/builder/PaymentTransactionBuilderDemo.java",
  }),
  gofCard({
    id: "prototype",
    part: 1,
    name: "Prototype",
    frequency: "Specialized",
    definition: "Clone a template object (standing instruction / report config) instead of rebuilding expensive setup.",
    problem: "Rebuilding a 12-field standing instruction every month duplicates bugs and misses fields.",
    realWorld: "ReportConfigurationPrototypeDemo: clone report/SI template, change date, do not copy last UTR.",
    whyExists: "Cheap copy of a known-good template with controlled deep/shallow rules.",
    ascii: "StandingInstruction template\n        \u2502 copyForNextMonth()\n        \u25bc\nNext-month SI (new date, cleared UTR)",
    flow: "Load template \u2192 clone \u2192 mutate allowed fields \u2192 persist new instance.",
    components: [
    {name: "Prototype", responsibility: "copy / clone method"},
    {name: "Template store", responsibility: "Canonical standing instructions"},
    {name: "Editor", responsibility: "Applies allowed field overrides"},
  ],
    javaCode: "public final class StandingInstruction {\n  private String payeeVpa; private int amount; private String lastUtr;\n  private LocalDate scheduleDate;\n  public StandingInstruction copyForNextMonth(LocalDate next) {\n    StandingInstruction c = new StandingInstruction();\n    c.payeeVpa = this.payeeVpa; c.amount = this.amount;\n    c.lastUtr = null; // never copy identity\n    c.scheduleDate = next;\n    return c;\n  }\n}",
    springCode: "// Prefer explicit copy methods over Object.clone(); document deep vs shallow.",
    unitTest: "@Test void cloneClearsUtr() {\n  var next = original.copyForNextMonth(LocalDate.parse(\"2026-09-01\"));\n  assertNull(next.lastUtr());\n  assertEquals(original.amount(), next.amount());\n}",
    edgeCases: [
    "Deep copy of nested holds",
    "Identity fields accidentally shared",
    "Clone of POSTED state",
  ],
    failureScenarios: [
    "Shallow copy mutates template",
    "Clone carries last month settlement id",
  ],
    retry: "N/A",
    idempotency: "copy should be deterministic.",
    timeout: "N/A",
    observability: "prototype_clone_total{type}",
    security: "Do not clone secrets into lower environments without redaction.",
    performance: "Cheaper than rebuild when templates are large.",
    scalability: "Fine for SI volume; watch deep-copy cost on huge graphs.",
    production: "Explicit copyForX methods beat Cloneable.",
    mistakes: [
    "Using Object.clone() without understanding shallow copy",
  ],
    antiPatterns: [
    "Prototype as substitute for a proper factory of new domain objects",
  ],
    alternatives: [
    "Builder from template DTO",
    "Copy constructor",
  ],
    tradeoffs: "Pros: speed/consistency. Cons: copy rules become a second model.",
    interviewQs: [
    "Deep vs shallow copy?",
    "Prototype vs Builder?",
  ],
    trickyQs: [
    "Cloneable pitfalls in Java?",
  ],
    seniorFollowUps: [
    "Event-sourced rebuild vs prototype clone?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/creational/prototype/ReportConfigurationPrototypeDemo.java",
  }),
];
