import type {PatternCard} from './types';
import {gofCard} from './card';

/** GoF structural patterns (Part 2). */
export const STRUCTURAL_PATTERNS: PatternCard[] = [
  gofCard({
    id: "adapter",
    part: 2,
    name: "Adapter",
    frequency: "Frequently used",
    definition: "Translate a foreign API (legacy CBS / NPCI SDK) into the bank\u2019s PaymentGateway interface.",
    problem: "ISO-8583 CBS and modern PaymentInstruction speak different shapes; leaking either pollutes the domain.",
    realWorld: "LegacyPaymentAdapterDemo wraps legacy charge API so Meridian code only sees PaymentGateway.",
    whyExists: "You do not own the other contract; adapters localize version churn.",
    ascii: "Domain PaymentGateway\n         \u25b2\n   LegacyPaymentAdapter\n         \u2502\n   LegacyCbsClient (ISO-8583)",
    flow: "Instruction \u2192 adapter maps fields \u2192 legacy call \u2192 map response/errors back.",
    components: [
    {name: "PaymentGateway", responsibility: "Target interface the bank owns"},
    {name: "LegacyPaymentAdapter", responsibility: "Maps to/from legacy SDK"},
    {name: "LegacyCbsClient", responsibility: "Foreign / unowned API"},
  ],
    javaCode: "public interface PaymentGateway { String pay(PaymentInstruction i); }\npublic final class LegacyPaymentAdapter implements PaymentGateway {\n  private final LegacyCbsClient cbs;\n  public String pay(PaymentInstruction i) {\n    LegacyRequest req = new LegacyRequest(i.account(), i.amountPaise());\n    LegacyResponse res = cbs.charge(req);\n    if (!res.ok()) throw new PaymentRejected(res.code());\n    return res.rrn();\n  }\n}",
    springCode: "@Bean PaymentGateway legacyGateway(LegacyCbsClient cbs) {\n  return new LegacyPaymentAdapter(cbs);\n}",
    unitTest: "@Test void mapsRejection() {\n  when(cbs.charge(any())).thenReturn(LegacyResponse.fail(\"51\"));\n  assertThrows(PaymentRejected.class, () -> adapter.pay(sample));\n}",
    edgeCases: [
    "Partial field mapping",
    "Charset / amount scale",
    "Timeout vs decline codes",
  ],
    failureScenarios: [
    "SDK version bump breaks mapping",
    "Legacy returns success twice (duplicate RRN)",
  ],
    retry: "Retry only idempotent legacy ops with same RRN/idempotency key.",
    idempotency: "Adapter must forward idempotency key into legacy request.",
    timeout: "Bound legacy calls (e.g. 2\u20133s); map timeout to domain error.",
    observability: "adapter_calls_total{target,result}; latency histogram",
    security: "Do not log full ISO payloads with PAN; mask in adapter.",
    performance: "Thin mapping layer; avoid reflection.",
    scalability: "Stateless adapters scale with service.",
    production: "One adapter per foreign system; contract tests against SDK stubs.",
    mistakes: [
    "Leaking LegacyRequest into controllers",
    "God adapter for five vendors",
  ],
    antiPatterns: [
    "Adapter forever when you own both sides",
  ],
    alternatives: [
    "Rewrite contract",
    "Anti-corruption layer (DDD)",
    "Facade (many internals, not one foreign)",
  ],
    tradeoffs: "Pros: domain stays clean. Cons: mapping debt; dual models.",
    interviewQs: [
    "Adapter vs Facade?",
    "Adapter vs Anti-Corruption Layer?",
  ],
    trickyQs: [
    "Where do you put amount scale conversion?",
  ],
    seniorFollowUps: [
    "How do you version adapters during dual-run cutover?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/adapter/LegacyPaymentAdapterDemo.java",
  }),
  gofCard({
    id: "bridge",
    part: 2,
    name: "Bridge",
    frequency: "Specialized",
    definition: "Separate two independent axes (notification channel \u00d7 vendor) so they can vary without class explosion.",
    problem: "SmsTwilio, SmsSes, EmailTwilio, EmailSes\u2026 N\u00d7M subclasses.",
    realWorld: "NotificationBridgeDemo: Notification holds a Sender; SMS/Email \u00d7 Twilio/SES compose freely.",
    whyExists: "Two dimensions of change should not be fused into one inheritance tree.",
    ascii: "Notification (SMS | Email)\n      \u2502 has-a\n   Sender (Twilio | SES | SNS)",
    flow: "Pick channel abstraction \u2192 inject sender implementor \u2192 send() delegates.",
    components: [
    {name: "Notification", responsibility: "Abstraction (SMS/Email)"},
    {name: "Sender", responsibility: "Implementor (Twilio/SES)"},
    {name: "Concrete pairs", responsibility: "Composed at runtime"},
  ],
    javaCode: "public interface Sender { void deliver(String to, String body); }\npublic abstract class Notification {\n  protected final Sender sender;\n  protected Notification(Sender sender) { this.sender = sender; }\n  public abstract void notify(String to, String body);\n}\npublic final class SmsNotification extends Notification {\n  public SmsNotification(Sender s) { super(s); }\n  public void notify(String to, String body) { sender.deliver(to, \"SMS:\" + body); }\n}",
    springCode: "@Bean Notification paymentSms(Sender twilioSender) {\n  return new SmsNotification(twilioSender);\n}",
    unitTest: "@Test void smsUsesInjectedSender() {\n  Sender spy = mock(Sender.class);\n  new SmsNotification(spy).notify(\"999\", \"posted\");\n  verify(spy).deliver(eq(\"999\"), contains(\"SMS\"));\n}",
    edgeCases: [
    "Null sender",
    "Channel-specific payload limits",
    "Vendor rate limits",
  ],
    failureScenarios: [
    "Wrong sender wired for channel",
    "Vendor outage without fallback sender",
  ],
    retry: "Retry at sender with backoff; circuit-break bad vendors.",
    idempotency: "Notification send needs dedupe key for at-least-once.",
    timeout: "Sender HTTP \u2264 2s.",
    observability: "notify_total{channel,vendor,result}",
    security: "PII in templates; redact in logs.",
    performance: "Bridge adds one hop \u2014 negligible vs network.",
    scalability: "Swap vendors without redeploying channel code.",
    production: "Config maps channel\u2192sender; feature-flag vendor cutover.",
    mistakes: [
    "Calling it Bridge when it is just Strategy",
  ],
    antiPatterns: [
    "Inheritance tree of channel\u00d7vendor",
  ],
    alternatives: [
    "Strategy for one axis",
    "Adapter for foreign shape only",
  ],
    tradeoffs: "Pros: independent evolution. Cons: more types to learn.",
    interviewQs: [
    "Bridge vs Adapter?",
    "Bridge vs Strategy?",
  ],
    trickyQs: [
    "When is Bridge over-engineering?",
  ],
    seniorFollowUps: [
    "Multi-vendor failover \u2014 still Bridge?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/bridge/NotificationBridgeDemo.java",
  }),
  gofCard({
    id: "composite",
    part: 2,
    name: "Composite",
    frequency: "Occasionally used",
    definition: "Treat one payment and a tree of payments (salary bulk) with the same post()/total() interface.",
    problem: "Call sites branch if (bulk) loop else pay \u2014 recursion and uniform ops disappear.",
    realWorld: "OrderCompositeDemo / payroll: bulk NEFT of \u20b92.1cr with 4,000 leaf credits; post() on the tree.",
    whyExists: "Uniform interface over part-whole hierarchies.",
    ascii: "BulkPayment (composite)\n  \u251c\u2500 Credit leaf\n  \u251c\u2500 Credit leaf\n  \u2514\u2500 Nested bulk\u2026",
    flow: "Client calls post() on root \u2192 composites recurse \u2192 leaves post money.",
    components: [
    {name: "PaymentComponent", responsibility: "Common interface: post, total, reverse"},
    {name: "LeafPayment", responsibility: "Single credit/debit"},
    {name: "BulkPayment", responsibility: "Composite holding children"},
  ],
    javaCode: "public interface PaymentComponent {\n  void post();\n  int totalPaise();\n}\npublic final class LeafPayment implements PaymentComponent {\n  private final int paise;\n  public void post() { /* book */ }\n  public int totalPaise() { return paise; }\n}\npublic final class BulkPayment implements PaymentComponent {\n  private final List<PaymentComponent> children = new ArrayList<>();\n  public void add(PaymentComponent c) { children.add(c); }\n  public void post() { children.forEach(PaymentComponent::post); }\n  public int totalPaise() {\n    return children.stream().mapToInt(PaymentComponent::totalPaise).sum();\n  }\n}",
    springCode: "// Persist tree with parent_id; domain composite rebuilds on load.",
    unitTest: "@Test void bulkTotalsChildren() {\n  BulkPayment b = new BulkPayment();\n  b.add(new LeafPayment(100)); b.add(new LeafPayment(50));\n  assertEquals(150, b.totalPaise());\n}",
    edgeCases: [
    "Empty composite",
    "Cycles in tree",
    "Partial post failure mid-tree",
  ],
    failureScenarios: [
    "Leaf fails after siblings posted \u2014 need compensation",
    "Huge tree stack overflow",
  ],
    retry: "Idempotent leaf post; track per-leaf status in bulk job.",
    idempotency: "Each leaf needs its own idempotency key.",
    timeout: "Bulk job wall clock; per-leaf timeout bounded.",
    observability: "composite_posts_total; leaf_failures; tree_depth",
    security: "Authorize on root and sensitive leaves.",
    performance: "Prefer iterative walk for deep/wide trees.",
    scalability: "Stream children; do not load 4,000 into RAM if avoidable.",
    production: "Salary files: composite + iterator + flyweight currency.",
    mistakes: [
    "Composite without uniform interface (just a List)",
  ],
    antiPatterns: [
    "Recursion for flat lists",
  ],
    alternatives: [
    "Explicit batch job loop",
    "Iterator over flat file",
  ],
    tradeoffs: "Pros: uniform ops. Cons: error handling across tree is hard.",
    interviewQs: [
    "Composite vs Decorator?",
    "How do you handle partial failure?",
  ],
    trickyQs: [
    "Should composite expose children publicly?",
  ],
    seniorFollowUps: [
    "Saga over composite children vs single DB txn?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/composite/OrderCompositeDemo.java",
  }),
  gofCard({
    id: "decorator",
    part: 2,
    name: "Decorator",
    frequency: "Frequently used",
    definition: "Wrap a core PaymentProcessor with extra behavior (fraud, audit, metrics) without editing the core.",
    problem: "Fraud/audit if-blocks inside ledger booking make the core untestable and rigid.",
    realWorld: "PaymentDecoratorDemo: FraudDecorator \u2192 AuditDecorator \u2192 MetricsDecorator around PaymentProcessor.",
    whyExists: "Same interface, stackable coats; compose at wiring time.",
    ascii: "Client \u2192 MetricsDecorator \u2192 AuditDecorator \u2192 FraudDecorator \u2192 CoreProcessor",
    flow: "Each decorator does work, then delegates to the next PaymentProcessor.",
    components: [
    {name: "PaymentProcessor", responsibility: "Component interface"},
    {name: "CoreProcessor", responsibility: "Books money only"},
    {name: "*Decorator", responsibility: "Adds fraud/audit/metrics then delegates"},
  ],
    javaCode: "public interface PaymentProcessor { Receipt process(Payment p); }\npublic final class FraudDecoratingProcessor implements PaymentProcessor {\n  private final PaymentProcessor next; private final FraudClient fraud;\n  public Receipt process(Payment p) {\n    if (!fraud.ok(p)) throw new FraudRejected();\n    return next.process(p);\n  }\n}",
    springCode: "@Bean PaymentProcessor paymentProcessor(CoreProcessor core, FraudClient fraud, AuditLog audit) {\n  PaymentProcessor p = core;\n  p = new FraudDecoratingProcessor(p, fraud);\n  p = new AuditDecoratingProcessor(p, audit);\n  return new MetricsDecoratingProcessor(p);\n}",
    unitTest: "@Test void fraudBlocksBeforeCore() {\n  PaymentProcessor core = mock(PaymentProcessor.class);\n  var d = new FraudDecoratingProcessor(core, amt -> false);\n  assertThrows(FraudRejected.class, () -> d.process(sample));\n  verifyNoInteractions(core);\n}",
    edgeCases: [
    "Decorator order matters",
    "Exception swallowing",
    "Double-wrap metrics",
  ],
    failureScenarios: [
    "Audit decorator fails after money posted",
    "Fraud client timeout",
  ],
    retry: "Idempotent core; decorators must not double-charge on retry.",
    idempotency: "Pass idempotency key through the whole chain.",
    timeout: "Each decorator sets budget; fail-open vs fail-closed policy explicit.",
    observability: "decorator_invocations{name}; wrap latency",
    security: "Fraud fail-closed for high-risk; never log full PAN in audit decorator.",
    performance: "Keep decorators allocation-light on hot path.",
    scalability: "Stateless decorators scale with service.",
    production: "Wire order in one @Bean method; document fail-open/closed.",
    mistakes: [
    "Business rules inside decorator that belong in domain",
  ],
    antiPatterns: [
    "Decorator that sometimes does not call next (that is Proxy/Chain)",
  ],
    alternatives: [
    "Proxy for access control",
    "AOP @Around",
    "Middleware pipeline",
  ],
    tradeoffs: "Pros: OCP stacking. Cons: debugging deep stacks; order bugs.",
    interviewQs: [
    "Decorator vs Proxy?",
    "Decorator vs Chain of Responsibility?",
  ],
    trickyQs: [
    "Where do you put transactional boundaries?",
  ],
    seniorFollowUps: [
    "AOP vs explicit decorators in a payment core?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/decorator/PaymentDecoratorDemo.java",
  }),
  gofCard({
    id: "facade",
    part: 2,
    name: "Facade",
    frequency: "Frequently used",
    definition: "One door (PaymentFacade.pay) that orchestrates fraud, account, charge, notify, audit.",
    problem: "Mobile team should not know the choreography of eight internal services.",
    realWorld: "PaymentFacadeDemo.processDetailed: fraud \u2192 account \u2192 charge \u2192 notify \u2192 audit.",
    whyExists: "Hide subsystem complexity behind a stable, intention-revealing API.",
    ascii: "App \u2192 PaymentFacade.pay()\n          \u251c\u2500 FraudService\n          \u251c\u2500 AccountService\n          \u251c\u2500 PaymentService\n          \u251c\u2500 NotificationService\n          \u2514\u2500 AuditService",
    flow: "Single entry \u2192 ordered checks/side effects \u2192 coherent PaymentOutcome.",
    components: [
    {name: "PaymentFacade", responsibility: "Orchestrates collaborators"},
    {name: "Subsystem services", responsibility: "Fraud, account, charge, notify, audit"},
    {name: "Client", responsibility: "Controller / mobile BFF"},
  ],
    javaCode: "public final class PaymentFacade {\n  private final FraudService fraud = new FraudService();\n  private final AccountService account = new AccountService();\n  private final PaymentService payment = new PaymentService();\n  public PaymentOutcome processDetailed(String accountId, int amount) {\n    if (!fraud.ok(amount)) return new PaymentOutcome(\"rejected:fraud\", \"\", List.of(\"fraud\"));\n    if (!account.hasBalance(accountId)) return new PaymentOutcome(\"rejected:account\", \"\", List.of(\"account\"));\n    String ref = payment.charge(accountId, amount);\n    return new PaymentOutcome(\"success\", ref, List.of(\"fraud\", \"account\", \"charge\"));\n  }\n}",
    springCode: "@Service\nclass PaymentFacade {\n  private final FraudService fraud; private final Ledger ledger; /* \u2026 */\n  public PaymentOutcome pay(PayRequest req) { /* orchestrate */ }\n}",
    unitTest: "@Test void rejectsFraud() {\n  assertEquals(\"rejected:fraud\", facade.processDetailed(\"A1\", 9_999).status());\n}",
    edgeCases: [
    "Partial success after charge",
    "Notify failure after money moved",
    "Duplicate pay clicks",
  ],
    failureScenarios: [
    "Subsystem timeout mid-flow",
    "Facade becomes god object",
  ],
    retry: "Idempotency key on pay; compensate notify failures asynchronously.",
    idempotency: "Facade must accept Idempotency-Key and short-circuit duplicates.",
    timeout: "Overall budget (e.g. 5s) with per-collaborator SLAs.",
    observability: "facade_pay_total{result}; step latency breakdown",
    security: "AuthZ at facade edge; do not expose internal services publicly.",
    performance: "Avoid chatty N+1 inside facade \u2014 batch where possible.",
    scalability: "Stateless facade; scale replicas; async side effects.",
    production: "Keep facade thin \u2014 orchestrate, do not own all rules.",
    mistakes: [
    "Putting HR + ATM + loans in one facade",
    "No idempotency",
  ],
    antiPatterns: [
    "FooFacade on every class",
  ],
    alternatives: [
    "API Gateway BFF",
    "Saga/orchestrator for distributed tx",
    "Mediator",
  ],
    tradeoffs: "Pros: simple client. Cons: central choke point if it grows.",
    interviewQs: [
    "Facade vs Adapter?",
    "Facade vs Mediator?",
  ],
    trickyQs: [
    "How do you keep facade from becoming a god class?",
  ],
    seniorFollowUps: [
    "Sync facade vs async saga for checkout?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/facade/PaymentFacadeDemo.java",
  }),
  gofCard({
    id: "flyweight",
    part: 2,
    name: "Flyweight",
    frequency: "Specialized",
    definition: "Share tiny immutable intrinsic state (Currency INR) across millions of extrinsic line items.",
    problem: "10M statement lines each allocating new Currency(\"INR\") wastes RAM and GC.",
    realWorld: "CurrencyFlyweightDemo: factory caches INR/USD/EUR; amount stays extrinsic on the line.",
    whyExists: "Huge N sharing identical immutable metadata.",
    ascii: "CurrencyFactory.get(\"INR\") \u2500\u2500\u25ba shared Currency flyweight\nStatementLine(amount, currencyRef)  // extrinsic + intrinsic ref",
    flow: "Lookup/create flyweight by key \u2192 line holds reference + extrinsic amount.",
    components: [
    {name: "Flyweight (Currency)", responsibility: "Intrinsic: code, decimals, symbol"},
    {name: "Factory cache", responsibility: "Interns flyweights"},
    {name: "Context (line)", responsibility: "Extrinsic amount / account"},
  ],
    javaCode: "public final class Currency {\n  private final String code; private final int scale;\n  Currency(String code, int scale) { this.code = code; this.scale = scale; }\n}\npublic final class CurrencyFactory {\n  private final Map<String, Currency> cache = new ConcurrentHashMap<>();\n  public Currency get(String code) {\n    return cache.computeIfAbsent(code, c -> new Currency(c, scaleFor(c)));\n  }\n}",
    springCode: "@Bean CurrencyFactory currencyFactory() { return new CurrencyFactory(); }",
    unitTest: "@Test void sharesInr() {\n  var f = new CurrencyFactory();\n  assertSame(f.get(\"INR\"), f.get(\"INR\"));\n}",
    edgeCases: [
    "Unknown currency code",
    "Mutable flyweight (bug)",
    "Cache unbounded growth",
  ],
    failureScenarios: [
    "Caching mutable account entities as flyweights",
    "Wrong scale for crypto",
  ],
    retry: "N/A",
    idempotency: "get() idempotent.",
    timeout: "N/A",
    observability: "flyweight_cache_size; hit ratio",
    security: "N/A beyond normal data.",
    performance: "Major RAM win on statement/print jobs.",
    scalability: "Cache per JVM; optional shared cache for huge catalogs.",
    production: "Only immutable catalogs: currency, country, IFSC bank name.",
    mistakes: [
    "Flyweight for balances",
    "No eviction policy for dynamic keys",
  ],
    antiPatterns: [
    "Calling every cache a Flyweight",
  ],
    alternatives: [
    "Enum for closed set",
    "DB reference data",
  ],
    tradeoffs: "Pros: memory. Cons: intrinsic/extrinsic discipline required.",
    interviewQs: [
    "Intrinsic vs extrinsic?",
    "Flyweight vs cache?",
  ],
    trickyQs: [
    "Thread safety of the factory?",
  ],
    seniorFollowUps: [
    "Flyweight in JVM vs Redis interned reference data?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/flyweight/CurrencyFlyweightDemo.java",
  }),
  gofCard({
    id: "proxy",
    part: 2,
    name: "Proxy",
    frequency: "Frequently used",
    definition: "Stand in front of a real PaymentService to enforce auth, rate limit, lazy init, or caching.",
    problem: "Core banking is dangerous/expensive; callers must not reach it unchecked.",
    realWorld: "PaymentServiceProxyDemo + Spring Security / @Transactional proxies: gate before the real object.",
    whyExists: "Control access or lifecycle without changing the subject\u2019s code.",
    ascii: "Client \u2192 PaymentServiceProxy (JWT, RPM)\n              \u2502 allow?\n              \u25bc\n         RealPaymentService",
    flow: "Proxy checks policy \u2192 delegates or rejects \u2192 never leaks real reference casually.",
    components: [
    {name: "PaymentService", responsibility: "Subject interface"},
    {name: "RealPaymentService", responsibility: "Core implementation"},
    {name: "PaymentServiceProxy", responsibility: "Access control / lazy / cache"},
  ],
    javaCode: "public interface PaymentService { Receipt pay(Payment p); }\npublic final class PaymentServiceProxy implements PaymentService {\n  private final PaymentService real; private final Auth auth; private final RateLimiter rl;\n  public Receipt pay(Payment p) {\n    auth.require(\"payments:write\");\n    if (!rl.tryAcquire(p.customerId())) throw new RateLimited();\n    return real.pay(p);\n  }\n}",
    springCode: "// Spring Security MethodSecurityInterceptor and @Transactional are proxies.\n@PreAuthorize(\"hasAuthority('payments:write')\")\npublic Receipt pay(Payment p) { return real.pay(p); }",
    unitTest: "@Test void blocksUnauthorized() {\n  assertThrows(SecurityException.class, () -> proxy.pay(sample));\n  verifyNoInteractions(real);\n}",
    edgeCases: [
    "Proxy bypass via cast to concrete",
    "Lazy proxy init races",
    "Cache stampedes",
  ],
    failureScenarios: [
    "Auth service down \u2014 fail closed",
    "Rate limiter Redis blip",
  ],
    retry: "Do not retry 401/403; retry transient limiter errors carefully.",
    idempotency: "Proxy forwards idempotency headers unchanged.",
    timeout: "AuthZ check \u2264 100\u2013200ms budget.",
    observability: "proxy_rejections_total{reason}; auth latency",
    security: "Least privilege; never log tokens.",
    performance: "Local JWT validate when possible; cache JWKS.",
    scalability: "Stateless proxy scales; rate limit needs shared store.",
    production: "Prefer framework proxies; keep custom proxies thin.",
    mistakes: [
    "Business GST rules inside proxy",
  ],
    antiPatterns: [
    "Proxy that always calls through and only logs (Decorator)",
  ],
    alternatives: [
    "API Gateway filters",
    "Decorator",
    "AOP",
  ],
    tradeoffs: "Pros: centralized control. Cons: hidden indirection; debugging.",
    interviewQs: [
    "Proxy vs Decorator?",
    "Virtual vs protection vs remote proxy?",
  ],
    trickyQs: [
    "Can you cast through a JDK proxy?",
  ],
    seniorFollowUps: [
    "Mesh sidecar vs app-level proxy responsibilities?",
  ],
    deepLabHref: "/java-design-patterns-real-world?file=src/main/java/com/example/designpatterns/structural/proxy/PaymentServiceProxyDemo.java",
  }),
];
