import type {InterviewQ} from './types';

/** Representative interview bank — expand per level in revision sessions. */
export const INTERVIEW_QA: InterviewQ[] = [
  {
    id: 'aws-b1',
    level: 'Beginner',
    tag: '⭐',
    topic: 'VPC',
    question: 'What is the difference between a public and private subnet?',
    answer30s: 'Public subnet has a route to Internet Gateway (0.0.0.0/0 → IGW). Private subnet has no direct internet route — outbound via NAT Gateway in a public subnet.',
    answer2m: 'Draw VPC: IGW attached to VPC, public subnet routes to IGW for inbound/outbound internet. Private subnet routes 0.0.0.0/0 to NAT Gateway ENI in public subnet — only outbound internet. RDS and app servers live in private subnets.',
    production: 'FinTech payment API: ALB in public subnets, ECS tasks in private, RDS in private DB subnets.',
    mistake: 'Putting application servers in public subnet with public IPs.',
    followUps: ['Why NAT Gateway?', 'Can private subnet receive inbound from internet?'],
  },
  {
    id: 'aws-b2',
    level: 'Beginner',
    tag: '⭐',
    topic: 'IAM',
    question: 'IAM User vs IAM Role — when use each?',
    answer30s: 'Users = long-lived human identity (prefer SSO). Roles = temporary credentials via STS for EC2, Lambda, ECS, cross-account — never embed access keys in apps.',
    answer2m: 'EC2 instance profile attaches role → SDK calls STS → temp creds auto-rotated. Lambda execution role same pattern. Interview trap: access keys in application.properties.',
    mistake: 'Creating IAM user for every ECS task with static keys.',
    followUps: ['What is AssumeRole?', 'Instance profile vs task role?'],
  },
  {
    id: 'aws-i1',
    level: 'Intermediate',
    tag: '⭐',
    topic: 'RDS',
    question: 'Multi-AZ vs Read Replica?',
    answer30s: 'Multi-AZ = synchronous standby for HA failover (same region). Read Replica = async copy for read scaling and cross-region DR — different purposes.',
    answer2m: 'Multi-AZ: automatic failover DNS flip ~60-120s, not for read traffic. Read Replica: analytics queries off primary, promote for DR. Use both: Multi-AZ for HA + replicas for read scale.',
    production: 'Payment ledger on Aurora Multi-AZ writer + 2 read replicas for reporting.',
    mistake: 'Using Multi-AZ replicas for read scaling — standby is not readable in classic RDS.',
    followUps: ['Aurora failover time?', 'Cross-region replica lag?'],
  },
  {
    id: 'aws-i2',
    level: 'Intermediate',
    tag: '🔥',
    topic: 'SQS',
    question: 'What is SQS visibility timeout and what happens if processing takes longer?',
    answer30s: 'Message hidden from other consumers during processing. If not deleted before timeout expires, message reappears — duplicate processing unless idempotent.',
    answer2m: 'Set visibility >= p99 processing time. Extend with ChangeMessageVisibility for long jobs. Pair with DLQ after maxReceiveCount. FinTech: payment consumer must be idempotent on redelivery.',
    mistake: 'Default 30s visibility on 5-minute settlement job — infinite duplicate charges.',
    followUps: ['FIFO vs Standard?', 'Long polling benefits?'],
  },
  {
    id: 'aws-s1',
    level: 'Senior',
    tag: '🔥',
    topic: 'DynamoDB',
    question: 'How do you design DynamoDB keys to avoid hot partitions at 10M requests/sec?',
    answer30s: 'Partition key must distribute writes — avoid monotonic keys (timestamp-only). Use composite keys, write sharding suffix {merchantId}#{shard}, or scatter-gather on hot merchants.',
    answer2m: 'Hot key symptom: one partition throttling while table has capacity. Fixes: random suffix on write, GSI with inverted key for queries, on-demand mode absorbs bursts, caching hot reads in ElastiCache. Interview: design payment idempotency table PK=paymentId.',
    production: 'Idempotency table: PK=idempotencyKey (UUID) — naturally distributed.',
    mistake: 'PK=status with all WRITING payments — throttling storm.',
    followUps: ['GSI vs LSI?', 'On-demand vs provisioned cost?'],
  },
  {
    id: 'aws-s2',
    level: 'Senior',
    tag: '🔥',
    topic: 'VPC',
    question: 'Security Group vs NACL — explain stateful vs stateless.',
    answer30s: 'SG = instance/ENI level, stateful (return traffic auto-allowed), allow-only rules. NACL = subnet level, stateless, explicit allow/deny, order matters.',
    answer2m: 'Primary defense: SG on ALB (443 from 0.0.0.0/0), SG on app (8080 from ALB SG only), SG on RDS (5432 from app SG only). NACL for explicit deny (block IP range) or subnet boundary compliance.',
    mistake: 'Relying on NACL alone without SG — SG is always evaluated.',
    followUps: ['Ephemeral ports in NACL?', 'Can SG reference another SG?'],
  },
  {
    id: 'aws-st1',
    level: 'Staff',
    tag: '🏆',
    topic: 'System Design',
    question: 'Design payment processing on AWS (high level).',
    answer30s: 'Route53 → WAF → ALB → ECS Spring Boot → Aurora + DynamoDB idempotency → MSK events → SQS settlement → KMS encryption → CloudTrail audit. Multi-AZ everything.',
    answer2m: 'Walk requirements: idempotent POST, PCI scope reduction (tokenize PAN), 99.99% availability. Capacity: 5k TPS peak. Data: Aurora for ledger, DynamoDB for idempotency keys TTL 24h. Async: MSK PaymentAuthorized → settlement worker. Failure: DLQ, circuit breaker on acquirer, warm standby DR region.',
    production: 'Reference /fintech-architecture topic and oauth-jwt + kafka-production labs.',
    mistake: 'Single-AZ RDS for money movement.',
    followUps: ['RPO/RTO?', 'Exactly-once vs at-least-once?'],
  },
  {
    id: 'aws-st2',
    level: 'Staff',
    tag: '🏆',
    topic: 'DR',
    question: 'Explain RPO and RTO — pick DR strategy for RPO < 5 min, RTO < 15 min.',
    answer30s: 'RPO = max acceptable data loss window. RTO = max downtime. For RPO 5m/RTO 15m: warm standby — Aurora Global Database or cross-region replica + scripted failover + Route53 health checks.',
    answer2m: 'Backup-restore: hours RTO — too slow. Pilot light: minimal DR region, scale up on fail — RTO 1h+. Warm standby: reduced capacity always running — RTO minutes. Active-active: dual write complexity — near zero RTO. FinTech: warm standby + S3 CRR for documents + MSK mirroring.',
    mistake: 'Confusing Read Replica lag with Multi-AZ synchronous replication RPO.',
    followUps: ['Route53 failover routing?', 'Chaos testing DR?'],
  },
];

export const QUESTION_BANK_COUNTS = {
  Beginner: {shown: 2, target: 50},
  Intermediate: {shown: 2, target: 75},
  Senior: {shown: 2, target: 100},
  Staff: {shown: 2, target: 100},
};
