import type {InterviewQ} from './types';

export const SENIOR: InterviewQ[] = [
  {id:'s1',topic:'Senior',question:'What is Resilience4j and why not custom retry?',answer30s:'Lightweight fault-tolerance library with tested CB/Retry/BH/RL/TL, metrics, Spring Boot 3 AOP — less buggy than ad-hoc wrappers.',answer2m:'Hystrix alternative; functional decorators + Micrometer. Custom retry usually misses jitter, windows, half-open, and metrics.',followUps:['Modules list?']},
  {id:'s2',topic:'Senior',question:'Circuit breaker states?',answer30s:'CLOSED normal; OPEN fail-fast after threshold; HALF_OPEN probes then CLOSED or OPEN.',answer2m:'waitDurationInOpenState; permittedNumberOfCallsInHalfOpenState; automaticTransitionFromOpenToHalfOpenEnabled.',followUps:['slowCallRate?']},
  {id:'s3',topic:'Senior',question:'Why minimumNumberOfCalls?',answer30s:'Avoid opening on tiny samples (2 fails of 2 = 100%).',answer2m:'Need N in the window before rate is even computed. Sparse cron jobs false-OPEN without this.',followUps:['COUNT vs TIME window?']},
  {id:'s4',topic:'Senior',question:'Why is retry dangerous for payments?',answer30s:'Timeout may mean the bank already charged — duplicate without idempotency.',answer2m:'Idempotency-Key + UNIQUE(idempotency_key). Same key, at-most-one capture.',followUps:['GET vs POST?'],trick:'Always safe to retry POST.'},
  {id:'s5',topic:'Senior',question:'Timeout vs circuit breaker?',answer30s:'Timeout bounds one call; CB stops calling after repeated bad outcomes.',answer2m:'Both needed. slowCallRateThreshold turns slowness into CB failures. HTTP connect/read timeouts still required.',followUps:['Read vs connect timeout?']},
  {id:'s6',topic:'Senior',question:'What is a bulkhead?',answer30s:'Isolate concurrency/pools so a notification meltdown does not kill payments.',answer2m:'Semaphore = limit on caller thread. ThreadPool = dedicated workers + bounded queue.',followUps:['Sizing?']},
  {id:'s7',topic:'Senior',question:'10 instances each with local rate limiter 100/s?',answer30s:'≈1000/s cluster — not 100. Need GW/Redis/mesh for a global bank quota.',answer2m:'R4j RL is AtomicRateLimiter per JVM. HPA multiplies permits.',followUps:['Tenant RL?']},
  {id:'s8',topic:'Senior',question:'Fake SUCCESS fallback?',answer30s:'Unacceptable for money — return PENDING/fail and reconcile.',answer2m:'Fallback matching ≈ catch. Do not swallow BusinessException into PENDING.',followUps:['OK fallbacks?']},
  {id:'s9',topic:'Senior',question:'Exponential backoff + jitter?',answer30s:'Grow wait; randomize to avoid thundering herd when 1000 pods retry together.',answer2m:'wait = min(max, base*2^n) then × random factor. Cap maxAttempts.',followUps:['Max wait?']},
  {id:'s10',topic:'Senior',question:'Retry amplification?',answer30s:'Nested retries multiply load (3×3×3=27). One retry owner on the payment path.',answer2m:'ADR: mesh retries OFF for money; app retries only with idempotency.',followUps:['Mesh + app?']},
  {id:'s11',topic:'Senior',question:'CallNotPermittedException — what do you do?',answer30s:'CB is OPEN. Do not retry. Fallback PENDING + metric + customer-safe status.',answer2m:'Wait for HALF_OPEN probes. Hammering OPEN wastes threads and hides the outage.',followUps:['Fallback calling the same bank?']},
  {id:'s12',topic:'Senior',question:'RateLimiter vs Bulkhead?',answer30s:'RL = admits over time (tickets/sec). BH = concurrent in-flight (seats).',answer2m:'You can be under QPS limit and still saturate threads — need both on a payment facade.',followUps:['timeoutDuration 0 vs wait?']},
  {id:'s13',topic:'Senior',question:'TimeLimiter vs HTTP client timeout?',answer30s:'TimeLimiter bounds a Future/Mono. Socket connect/read timeouts still fire underneath.',answer2m:'Align budgets: client 3s > TL 2s > read 1.5s > connect 200ms. cancelRunningFuture is not magic for blocking IO.',followUps:['Why both?']},
  {id:'s14',topic:'Senior',question:'Why ignore RequestNotPermitted on the CircuitBreaker?',answer30s:'Otherwise traffic spikes look like a dead bank and OPEN the CB.',answer2m:'Same for BulkheadFullException. CB should record bank failures, not admit-control rejects.',followUps:['recordExceptions?']},
  {id:'s15',topic:'Senior',question:'Self-invocation and @CircuitBreaker?',answer30s:'this.charge() skips the Spring proxy — annotations never run.',answer2m:'Call across beans: OrderService → PaymentGatewayClient. Or decorate programmatically.',followUps:['private methods?']},
];

export const ARCHITECT: InterviewQ[] = [
  {id:'a1',topic:'Architect',question:'Payment service down 10 minutes — what happens?',answer30s:'CB opens after threshold; fallback PENDING; alerts; BH keeps other pools alive; HALF_OPEN probes after waitDuration.',answer2m:'Customer messaging + ops runbook + reconciliation of PENDING. Never convert PENDING to SUCCESS in fallback.',followUps:['Failback?']},
  {id:'a2',topic:'Architect',question:'Prevent cascading failures?',answer30s:'Timeouts + BH + CB + admit RL; isolate thread pools; no nested retries.',answer2m:'Shared Tomcat pool is a hidden bulkhead miss — wrap outbound calls.',followUps:['Shared Tomcat pool?']},
  {id:'a3',topic:'Architect',question:'Retry + CircuitBreaker together?',answer30s:'Default AOP: Retry wraps CB. Attempts count in the window; OPEN stops the call.',answer2m:'Programmatic CB(Retry(api)) waits for retries before recording one result — slower OPEN, longer tail. Know which onion you deployed.',followUps:['Retry outside CB?']},
  {id:'a4',topic:'Architect',question:'Choose failureRateThreshold?',answer30s:'From SLO/error budget and dependency criticality — e.g. 50% with min 20 calls; tune via metrics.',answer2m:'Too low flaps; too high cascades. slowCallRate is a separate knob for "up but useless".',followUps:['slowCallRate?']},
  {id:'a5',topic:'Architect',question:'Tenant-level resilience?',answer30s:'Per-tenant RL/BH for fairness; shared CB for bank health; bound metric cardinality.',answer2m:'GW quotas + in-app tenant BH. Extreme tenants get a dedicated pool.',followUps:['Redis directory?']},
  {id:'a6',topic:'Architect',question:'R4j vs Istio retries?',answer30s:'Mesh = transport defaults; app = business idempotency. One retry owner for payments.',answer2m:'GW RL + mesh timeouts + app CB. Never triple-retry.',followUps:['Hystrix?']},
  {id:'a7',topic:'Architect',question:'Kafka + Resilience4j?',answer30s:'Prefer retry topics/DLQ; careful with blocking retry in poll; CB around sync side effects.',answer2m:'Poison message must not block the partition forever.',followUps:['Replay?']},
  {id:'a8',topic:'Architect',question:'DB write retries?',answer30s:'Dangerous without idempotent upsert; prefer fail + user retry; CB on pool exhaustion.',answer2m:'Socket timeout after commit is the duplicate-payment story in SQL clothing.',followUps:['Read replicas?']},
  {id:'a9',topic:'Architect',question:'How to test CB in CI?',answer30s:'Programmatic registry + stub failing client; assert OPEN after N failures; lab uses PaymentBankStub modes.',answer2m:'Also HALF_OPEN, ignoreExceptions, and HTTP PENDING fallback.',followUps:['HALF_OPEN?']},
  {id:'a10',topic:'Architect',question:'Timeout budget across GW→Order→Payment→Bank?',answer30s:'Outer ≤ sum inners; decreasing inward; cancel work when the client is gone.',answer2m:'Example 3s / 2s / 1.5s / 200ms connect. Retry×timeout is the real budget.',followUps:['cancelRunningFuture?']},
  {id:'a11',topic:'Architect',question:'Design a payment service that calls multiple banks and stays up when one is slow.',answer30s:'Per-bank CB+BH+timeouts; idempotent retry; PENDING fallback; edge RL; never one shared pool for all banks.',answer2m:'Visa vs SWIFT vs local ACH each get named instances. Slow SWIFT must not stall Visa captures.',followUps:['Shared vs per-bank CB?']},
  {id:'a12',topic:'Architect',question:'50M transactions/month — how do you set R4j?',answer30s:'From RPS, p99, thread pools, bank SLA, error budget — not from a blog YAML.',answer2m:'Load test OPEN, RL reject, BH full. Watch retry_calls and CB failure_rate. Recalculate when you HPA.',followUps:['Error budget?']},
  {id:'a13',topic:'Architect',question:'Distributed circuit breaker?',answer30s:'Usually no. Local CB protects that pod\'s threads. Global OPEN needs a shared signal (rarely worth it).',answer2m:'Protect the bank with GW/outlier detection; protect the JVM with R4j. Mixing them without an ADR causes split-brain admits.',followUps:['Multi-region?']},
  {id:'a14',topic:'Architect',question:'Resilience4j vs Spring Cloud CircuitBreaker?',answer30s:'SCB is an abstraction; R4j is a common implementation. You still configure R4j semantics.',answer2m:'If you need BH/RL/TL/events, talk R4j, not the facade.',followUps:['Why abstraction?']},
  {id:'a15',topic:'Architect',question:'Health indicator on CB OPEN — kill the pod?',answer30s:'Usually no — the app can still serve other routes. OPEN is a dependency signal, not process death.',answer2m:'Readiness may degrade a payment-only pod. Liveness kill on bank outage is a self-DDoS with HPA.',followUps:['show-details?']},
];

export const RAPID: InterviewQ[] = [
  {id:'r1',topic:'Rapid',question:'CLOSED vs OPEN vs HALF_OPEN?',answer30s:'CLOSED calls through; OPEN fail-fast; HALF_OPEN limited probes.',answer2m:'Draw the state machine with waitDuration and permitted half-open calls.',followUps:['Who transitions?']},
  {id:'r2',topic:'Rapid',question:'COUNT_BASED vs TIME_BASED?',answer30s:'Count = last N calls; time = last N seconds of calls.',answer2m:'Sparse traffic: COUNT + minimumNumberOfCalls. Bursty: TIME can empty the window.',followUps:['Which for a cron?']},
  {id:'r3',topic:'Rapid',question:'slowCallDurationThreshold?',answer30s:'Calls slower than this count as slow; slowCallRateThreshold can OPEN the CB.',answer2m:'Bank up but 8s p99 — fail-fast instead of drowning threads.',followUps:['Vs read timeout?']},
  {id:'r4',topic:'Rapid',question:'IgnoreExceptions example?',answer30s:'BusinessException, 4xx, RequestNotPermitted, BulkheadFullException.',answer2m:'CB should not treat "insufficient funds" as a dead bank.',followUps:['recordExceptions?']},
  {id:'r5',topic:'Rapid',question:'Semaphore vs ThreadPool bulkhead?',answer30s:'Semaphore limits in-flight on caller threads; ThreadPool isolates workers + queue.',answer2m:'Sync RestClient → semaphore. Async fraud + TimeLimiter → thread-pool.',followUps:['Queue full?']},
  {id:'r6',topic:'Rapid',question:'limitForPeriod meaning?',answer30s:'Permits refreshed every limitRefreshPeriod (token bucket style).',answer2m:'timeoutDuration=0 → fail-fast RequestNotPermitted. Non-zero waits.',followUps:['Atomic vs Semaphore RL?']},
  {id:'r7',topic:'Rapid',question:'Why fallbackMethod signature matters?',answer30s:'Same args + exception parameter; matching like catch — specific first.',answer2m:'Mismatch → NoSuchMethod at runtime. Throwable fallback must not swallow business errors.',followUps:['Multiple fallbacks?']},
  {id:'r8',topic:'Rapid',question:'Actuator endpoint for CB?',answer30s:'/actuator/circuitbreakers and /actuator/circuitbreakerevents — protect in prod.',answer2m:'Also prometheus metrics: state, failure_rate, not_permitted.',followUps:['Who can hit it?']},
  {id:'r9',topic:'Rapid',question:'What is thundering herd?',answer30s:'Many pods retry in lockstep after an outage.',answer2m:'Jitter + CB OPEN + bounded attempts. Without jitter, recovery is a second outage.',followUps:['Full jitter?']},
  {id:'r10',topic:'Rapid',question:'Spring Retry vs Resilience4j?',answer30s:'Spring Retry is retries. R4j is CB+Retry+BH+RL+TL+metrics.',answer2m:'For payments you want the suite, not only Retry.',followUps:['Can you combine?']},
  {id:'r11',topic:'Rapid',question:'When is Cache module useful?',answer30s:'Repeated reads with a staleness budget — FX, calendars. Not captures.',answer2m:'Lab uses Spring Cache+Caffeine. R4j Cache wraps JCache.',followUps:['Stampede?']},
  {id:'r12',topic:'Rapid',question:'Correlation ID on retry logs?',answer30s:'MDC corrId on every attempt/fallback/state change. Never log PAN/JWT.',answer2m:'Otherwise you cannot join three retries to one customer click.',followUps:['PII?']},
  {id:'r13',topic:'Rapid',question:'429 vs CB OPEN response?',answer30s:'429 = admit control (RL). OPEN = dependency judged unhealthy.',answer2m:'Do not map both to the same client error without metrics that distinguish them.',followUps:['Retry-After?']},
  {id:'r14',topic:'Rapid',question:'Self-invocation AOP pitfall?',answer30s:'Same-class this.method() skips the proxy.',answer2m:'Cross a bean, or decorate programmatically.',followUps:['final class?']},
  {id:'r15',topic:'Rapid',question:'Payment PENDING vs SUCCESS?',answer30s:'PENDING = we do not know / bank down. SUCCESS only after bank confirm.',answer2m:'Reconciliation job owns PENDING. Fallback must not lie.',followUps:['Customer UX?']},
  {id:'r16',topic:'Rapid',question:'Default Spring AOP nesting?',answer30s:'Retry wraps CircuitBreaker wraps RateLimiter wraps TimeLimiter wraps Bulkhead.',answer2m:'Annotation order on the method is not runtime order.',followUps:['How to invert?']},
  {id:'r17',topic:'Rapid',question:'HTTP 429 — retry?',answer30s:'Only with Retry-After / explicit policy. Easy to DDoS yourself.',answer2m:'Honor Retry-After; cap attempts; prefer shedding.',followUps:['Vs 503?']},
  {id:'r18',topic:'Rapid',question:'HALF_OPEN traffic spike?',answer30s:'Only permittedNumberOfCallsInHalfOpenState probes. Keep it small.',answer2m:'Too large and you stampede a recovering bank.',followUps:['automaticTransition?']},
];

export const ALL = [...SENIOR, ...ARCHITECT, ...RAPID];
