import type {TocItem} from './types';

export const R4J_TOC: TocItem[] = [
  {id: 'overview', label: 'Big Picture · Payments'},
  {id: 'modules', label: 'Modules Map'},
  {id: 'failures', label: 'What Can Fail'},
  {id: 'circuit', label: 'Circuit Breaker'},
  {id: 'retry', label: 'Retry · Idempotency'},
  {id: 'backoff', label: 'Backoff · Jitter'},
  {id: 'bulkhead', label: 'Bulkhead'},
  {id: 'ratelimit', label: 'Rate Limiter'},
  {id: 'timelimit', label: 'TimeLimiter'},
  {id: 'fallback', label: 'Fallback Rules'},
  {id: 'combine', label: 'Pattern Order'},
  {id: 'spring', label: 'Spring Boot'},
  {id: 'scenarios', label: 'Failure Scenarios'},
  {id: 'kafka', label: 'Kafka · Redis · DB'},
  {id: 'clients', label: 'REST Clients'},
  {id: 'observe', label: 'Metrics · Tracing'},
  {id: 'tenant', label: 'Multi-Tenant'},
  {id: 'drawbacks', label: 'Drawbacks · Mistakes'},
  {id: 'vs', label: 'vs Mesh / Hystrix'},
  {id: 'cache', label: 'Cache'},
  {id: 'threadpool', label: 'ThreadPool Bulkhead'},
  {id: 'aop', label: 'AOP Order'},
  {id: 'selfinvoke', label: 'Self-Invocation'},
  {id: 'webflux', label: 'WebFlux'},
  {id: 'exceptions', label: 'Exception Matrix'},
  {id: 'k8s', label: 'Kubernetes'},
  {id: 'corners', label: 'Corner Cases'},
  {id: 'architecture', label: 'Banking Architecture'},
  {id: 'sysdesign', label: 'System Design Interview'},
  {id: 'decision', label: 'Memory Framework'},
  {id: 'interview', label: 'Interview Mode'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'checklist', label: 'Production Checklist'},
  {id: 'cheat', label: 'Cheat Sheet'},
];
