import type {InterviewQ} from './types';

export const BEGINNER: InterviewQ[] = [
  {id:'b1',level:'Beginner',topic:'Basics',question:'What is Camunda 8?',answer30s:'A BPMN workflow platform built around the Zeebe distributed engine.',answer2m:'Camunda 8 executes BPMN processes, activates external workers, and provides Operate/Tasklist/Optimize for visibility and human work.',followUps:['What is Zeebe?']},
  {id:'b2',level:'Beginner',topic:'Basics',question:'What is Zeebe?',answer30s:'Zeebe is Camunda 8 workflow engine.',answer2m:'It persists workflow events and state in partitioned logs, creates jobs, handles timers/messages, and exposes commands through the gateway.',followUps:['Is Zeebe a database?']},
  {id:'b3',level:'Beginner',topic:'BPMN',question:'What is BPMN?',answer30s:'A standard notation for modeling business processes.',answer2m:'BPMN models tasks, events, gateways, timers, messages, and human work in a diagram that business and engineering can discuss.',followUps:['Why not just code?']},
  {id:'b4',level:'Beginner',topic:'Workers',question:'What is a job worker?',answer30s:'An external service that pulls and completes jobs by type.',answer2m:'For example, FraudCheckWorker subscribes to fraud-check, calls fraud service, and completes the job with fraudStatus variables.',followUps:['Why external workers?']},
  {id:'b5',level:'Beginner',topic:'Workers',question:'Name payment job types.',answer30s:'validate-payment, fraud-check, account-validation, process-payment, notify-payment, manual-review.',answer2m:'The full story may also include payment-gateway, bank-settlement, release-account-hold, and void-gateway-authorization.',followUps:['Which one calls the bank?']},
  {id:'b6',level:'Beginner',topic:'Operate',question:'What is Operate used for?',answer30s:'Runtime visibility and incident resolution.',answer2m:'Operate shows process instances, tokens, variables, jobs, and incidents so operators can diagnose stuck payment workflows.',followUps:['Is Operate source of truth?'],trick:'Using Operate as customer status API.'},
  {id:'b7',level:'Beginner',topic:'Tasklist',question:'What is Tasklist?',answer30s:'The Camunda app for human tasks.',answer2m:'Managers can claim and complete manual-review tasks for payments above 100000, returning approved/rejected variables.',followUps:['How secure approvals?']},
  {id:'b8',level:'Beginner',topic:'Gateway',question:'What port does the Zeebe gateway commonly use here?',answer30s:'26500.',answer2m:'The Spring app on 8094 connects to the Zeebe gateway at 26500 to deploy, start instances, publish messages, and activate jobs.',followUps:['What is Operate port in docs?']},
  {id:'b9',level:'Beginner',topic:'API',question:'What should PaymentController do?',answer30s:'Accept requests, persist domain state, and start/signal workflows.',answer2m:'It should hide Zeebe internals from clients and expose paymentId/domain status rather than raw workflow keys.',followUps:['Why 202 Accepted?']},
  {id:'b10',level:'Beginner',topic:'State',question:'Where is payment status stored?',answer30s:'In the payment business DB.',answer2m:'Zeebe stores workflow progress; the DB stores customer-visible status, idempotency, bank references, approval audit, and ledger links.',followUps:['What variables go to Zeebe?']},
  {id:'b11',level:'Beginner',topic:'BPMN',question:'What is a service task?',answer30s:'A BPMN task backed by a worker job type.',answer2m:'A service task like fraudCheck has zeebe taskDefinition type fraud-check, which a Spring worker activates.',followUps:['What is taskDefinition type?']},
  {id:'b12',level:'Beginner',topic:'BPMN',question:'What is an exclusive gateway?',answer30s:'A decision point where one path is chosen.',answer2m:'For payments, route amount > 100000 to manager approval or fraudStatus REJECTED to rejected notification.',followUps:['Parallel gateway difference?']},
  {id:'b13',level:'Beginner',topic:'Timers',question:'Why use timers?',answer30s:'For durable waiting and SLA timeouts.',answer2m:'Use a boundary timer on manual-review to escalate if a manager does not approve within PT30M.',followUps:['Why not sleep in worker?']},
  {id:'b14',level:'Beginner',topic:'Messages',question:'What is message correlation?',answer30s:'Resuming a workflow with a named message and correlation key.',answer2m:'A bank callback publishes BankSettled with correlationKey paymentId so the right process instance continues.',followUps:['What if callback arrives early?']},
  {id:'b15',level:'Beginner',topic:'Incidents',question:'What is an incident?',answer30s:'A blocked workflow needing operator action.',answer2m:'When a technical job failure exhausts retries, Zeebe creates an incident visible in Operate.',followUps:['How resolve?']},
  {id:'b16',level:'Beginner',topic:'Story',question:'Tell the payment flow in one line.',answer30s:'Validate -> Fraud -> Gateway -> Account -> Process -> Bank -> Notify.',answer2m:'Add fraud rejection, high-value manager approval, bank retry/incident, and notification as explicit BPMN paths.',followUps:['Where does manual review fit?']},
];

export const INTERMEDIATE: InterviewQ[] = [
  {id:'i1',level:'Intermediate',topic:'Retries',question:'Business error vs job failure?',answer30s:'Business error routes expected outcomes; job failure retries technical problems.',answer2m:'Fraud reject is a business path. Bank timeout/5xx is fail command with retry/backoff and incident after retries hit zero.',followUps:['Where use BPMN error?']},
  {id:'i2',level:'Intermediate',topic:'Idempotency',question:'Why must workers be idempotent?',answer30s:'Zeebe retries and workers can crash after side effects.',answer2m:'A bank charge may succeed but job completion fail. On retry, worker must see saved bankReference and not charge again.',followUps:['How implement?']},
  {id:'i3',level:'Intermediate',topic:'Variables',question:'What variables should payment-process carry?',answer30s:'Small routing facts: paymentId, amount, currency, fraudStatus, bankStatus.',answer2m:'Avoid PAN, CVV, full bank payloads, ledgers, and huge JSON; those belong in secure domain storage.',followUps:['Why variables are visible?']},
  {id:'i4',level:'Intermediate',topic:'REST',question:'How start a process from Spring?',answer30s:'Use ZeebeClient create instance command with BPMN process id and variables.',answer2m:'PaymentController writes REQUESTED idempotently, then starts payment-process latestVersion with paymentId/amount/currency.',followUps:['What if start fails after DB insert?']},
  {id:'i5',level:'Intermediate',topic:'Messages',question:'How handle early bank callback?',answer30s:'Use message TTL and persist callback idempotently.',answer2m:'Publish the message with timeToLive so Zeebe can correlate once the catch event subscription exists; keep DB evidence either way.',followUps:['What correlation key?']},
  {id:'i6',level:'Intermediate',topic:'User tasks',question:'How model approval over 100000?',answer30s:'Exclusive gateway routes to manual-review user task with SLA timer.',answer2m:'Candidate group payment-managers completes the task; approved variable continues to process-payment, rejected ends safely.',followUps:['How audit actor?']},
  {id:'i7',level:'Intermediate',topic:'Timers',question:'What does cancelActivity mean?',answer30s:'Whether the boundary timer cancels the attached task.',answer2m:'For approval timeout, cancelActivity=true removes the pending user task and moves to escalation/rejection path.',followUps:['When false?']},
  {id:'i8',level:'Intermediate',topic:'Parallel',question:'When use a parallel gateway?',answer30s:'For independent work that can run concurrently and join before continuing.',answer2m:'Fraud, credit, and account checks can run in parallel if each writes separate results and the join validates all outcomes.',followUps:['What if one branch fails?']},
  {id:'i9',level:'Intermediate',topic:'Multi-instance',question:'What is multi-instance?',answer30s:'Repeating a task for every item in a collection.',answer2m:'Notify multiple channels or validate multiple documents; control concurrency because load multiplies.',followUps:['Sequential vs parallel?']},
  {id:'i10',level:'Intermediate',topic:'Versioning',question:'What happens on BPMN redeploy?',answer30s:'A new process version is created.',answer2m:'New starts can use latest; existing instances continue on their version unless migrated.',followUps:['Keep old workers?']},
  {id:'i11',level:'Intermediate',topic:'C7 vs C8',question:'Main Camunda 7 to 8 change?',answer30s:'From relational embedded/delegate model to Zeebe external workers.',answer2m:'C8 changes storage, scaling, transaction boundaries, APIs, and operations even though BPMN remains.',followUps:['Can JavaDelegate move directly?'],trick:'Copying JavaDelegate code as-is.'},
  {id:'i12',level:'Intermediate',topic:'Operate',question:'Exporter lag impact?',answer30s:'Operate may be stale while Zeebe still runs.',answer2m:'Exporter/index issues affect visibility, not necessarily engine execution, so alert separately and avoid using Operate as transactional API.',followUps:['How detect lag?']},
  {id:'i13',level:'Intermediate',topic:'Security',question:'How protect Operate variables?',answer30s:'Do not put sensitive values in variables and restrict UI access.',answer2m:'Use redaction/minimal variables, OIDC groups, least privilege, and avoid PAN/CVV/full bank payloads in process state.',followUps:['What about support users?']},
  {id:'i14',level:'Intermediate',topic:'Testing',question:'What workflow paths must tests cover?',answer30s:'Happy path, fraud reject, high-value approval, bank retry/incident, callback, compensation.',answer2m:'Also test exact threshold 100000, timeout, duplicate worker execution, and malformed variables.',followUps:['How test incidents?']},
  {id:'i15',level:'Intermediate',topic:'K8s',question:'Which components are stateful?',answer30s:'Zeebe brokers and Elasticsearch/OpenSearch.',answer2m:'Workers and APIs are stateless deployments; brokers need PVCs, stable identity, snapshots, and careful rollouts.',followUps:['Gateway stateful?']},
  {id:'i16',level:'Intermediate',topic:'Observability',question:'What metrics matter for workers?',answer30s:'Activation latency, completion latency, failures, retries, active jobs, backlog by type.',answer2m:'Add incidents by element, downstream latency, idempotency duplicates, exporter lag, and payment status transitions.',followUps:['High-cardinality labels?']},
];

export const SENIOR: InterviewQ[] = [
  {id:'s1',level:'Senior',topic:'Architecture',question:'Design the Camunda 8 payment platform.',answer30s:'Zeebe orchestrates; Spring workers execute idempotently; DB owns payment truth.',answer2m:'PaymentController starts workflow, workers handle validate/fraud/account/process/bank/notify/manual-review, Operate shows incidents, Tasklist handles approvals, DB stores status/idempotency/audit.',followUps:['Draw failure paths.']},
  {id:'s2',level:'Senior',topic:'Consistency',question:'How handle bank timeout after charge may have succeeded?',answer30s:'Use idempotency key and reconciliation before retrying charge.',answer2m:'Persist request/attempt, call bank with paymentId idempotency key, query bank or read saved reference on retry, then complete job once domain state is safe.',followUps:['What if bank has no idempotency?']},
  {id:'s3',level:'Senior',topic:'Saga',question:'How do you compensate a failed payment saga?',answer30s:'Void gateway authorization and release account hold idempotently.',answer2m:'Each local transaction records reference IDs. If bank settlement fails permanently, compensation workers execute in reverse business order with audit and retry handling.',followUps:['Is this rollback?'],trick:'Calling saga rollback ACID.'},
  {id:'s4',level:'Senior',topic:'Transactions',question:'Can Zeebe and business DB share one transaction?',answer30s:'No, design for eventual consistency and idempotency.',answer2m:'Write business state transactionally in your DB, then complete job. If completion fails, retry observes persisted state and completes without duplicating side effect.',followUps:['Outbox pattern?']},
  {id:'s5',level:'Senior',topic:'Incidents',question:'What is the incident runbook?',answer30s:'Identify element, read redacted error, fix dependency/data, retry or migrate, audit resolution.',answer2m:'Operate shows failed element and variables. The runbook checks payment DB, downstream health, retries, worker version, and resolves only after the side effect is safe.',followUps:['Who can resolve?']},
  {id:'s6',level:'Senior',topic:'Backpressure',question:'How prevent workers from overloading bank/fraud?',answer30s:'Bound maxJobsActive, timeouts, rate limits, bulkheads, and separate deployments.',answer2m:'Configure per job type concurrency, client timeouts, retry backoff, circuit breakers, autoscaling, and queues/limits at downstream clients.',followUps:['What metric controls HPA?']},
  {id:'s7',level:'Senior',topic:'Versioning',question:'How deploy a new high-value approval step?',answer30s:'Deploy BPMN vNext and worker/UI support, start new instances on latest, migrate only safe in-flight ones.',answer2m:'Keep old job types running, validate gateway conditions, add tests, coordinate Tasklist/form permissions, and communicate operator changes.',followUps:['Rollback?']},
  {id:'s8',level:'Senior',topic:'Security',question:'What are Camunda security boundaries?',answer30s:'OIDC UIs, scoped Zeebe clients, network policy, API authz, variable minimization.',answer2m:'Operate/Tasklist need groups; workers need least-privileged credentials; approval API needs domain authz; Zeebe should not be publicly reachable.',followUps:['Secrets rotation?']},
  {id:'s9',level:'Senior',topic:'Data',question:'Why not store full payment in variables?',answer30s:'Variables are workflow routing state and may be visible/indexed.',answer2m:'Large/sensitive variables slow exporters and leak data. Store full domain data in DB and pass only IDs/status needed by BPMN.',followUps:['Variable size limits?']},
  {id:'s10',level:'Senior',topic:'Messages',question:'How design bank callback correlation?',answer30s:'Use paymentId or mapped bank reference with TTL and idempotent DB upsert.',answer2m:'Callback endpoint authenticates bank, persists event, publishes BankSettled with correlationKey, handles duplicates and early/late callbacks.',followUps:['Multiple callbacks?']},
  {id:'s11',level:'Senior',topic:'Testing',question:'How test retry to incident?',answer30s:'Make worker fail until retries zero and assert incident at element.',answer2m:'Use test engine/Testcontainers where possible; unit-test fail command logic and integration-test Operate/Zeebe state for critical cases.',followUps:['How avoid slow tests?']},
  {id:'s12',level:'Senior',topic:'Temporal',question:'Camunda vs Temporal?',answer30s:'Camunda is BPMN/business-visible; Temporal is code-first durable execution.',answer2m:'For human approvals and business diagrams choose Camunda; for developer-owned workflow code and SDK-native retries choose Temporal.',followUps:['Can both coexist?']},
  {id:'s13',level:'Senior',topic:'Kafka',question:'Why not just Kafka?',answer30s:'Kafka streams facts; it does not naturally show process tokens, timers, user tasks, and incidents.',answer2m:'Kafka is excellent event backbone. Camunda can orchestrate the payment and publish events to Kafka for independent consumers.',followUps:['Hidden workflow problem?']},
  {id:'s14',level:'Senior',topic:'Step Functions',question:'Camunda vs Step Functions?',answer30s:'Step Functions is AWS-managed orchestration; Camunda is BPMN and portable/business-centric.',answer2m:'Use Step Functions for AWS service glue. Use Camunda when BPMN, human tasks, Operate, and cross-platform process ownership matter.',followUps:['Cost model?']},
  {id:'s15',level:'Senior',topic:'Operations',question:'Zeebe healthy but Operate empty. What now?',answer30s:'Check exporter/index health and lag.',answer2m:'The engine can continue while exporter projection is delayed. Verify broker exporters, Elasticsearch/OpenSearch, Operate config, and index backlog.',followUps:['Customer impact?']},
  {id:'s16',level:'Senior',topic:'Modeling',question:'How granular should BPMN be?',answer30s:'Business milestones, not every method.',answer2m:'Validate, Fraud, Account, Process, Bank, Notify are good. Internal validation functions and DTO mapping should stay in code.',followUps:['Who reads BPMN?']},
];

export const ARCHITECT: InterviewQ[] = [
  {id:'a1',level:'Architect',topic:'Platform',question:'Give the 5-minute architecture answer.',answer30s:'Orchestrate with Zeebe, execute with workers, store truth in DB, operate with metrics and incidents.',answer2m:'Include BPMN path, idempotency, DB boundaries, retries/incidents, manual approval, saga compensation, security, K8s, and observability.',followUps:['Whiteboard it.']},
  {id:'a2',level:'Architect',topic:'Reliability',question:'How do you make payment processing exactly-once?',answer30s:'You do not rely on exactly-once; you design idempotent effects and reconciliation.',answer2m:'Zeebe may retry. External systems may timeout. Use unique paymentId/idempotency keys, state machines, locks/version checks, and reconciliation.',followUps:['What is effectively-once?'],trick:'Promising exactly-once across bank calls.'},
  {id:'a3',level:'Architect',topic:'DR',question:'What is the disaster recovery plan?',answer30s:'Back up Zeebe/Elastic as required, but reconcile from payment DB and external references.',answer2m:'Define RPO/RTO, broker snapshots, exporter projection recovery, DB backups, replay/reconciliation, and manual incident procedures.',followUps:['Can Operate be rebuilt?']},
  {id:'a4',level:'Architect',topic:'Multi-region',question:'How think about multi-region Camunda payments?',answer30s:'Partition ownership and failover carefully; avoid active-active double processing without strong idempotency.',answer2m:'Payment routing, Zeebe cluster topology, database consistency, bank idempotency, and region failover must be designed together.',followUps:['Active-active risks?']},
  {id:'a5',level:'Architect',topic:'Governance',question:'How govern BPMN changes?',answer30s:'Versioned models, tests, code review, owner approval, rollout, migration plan.',answer2m:'Treat BPMN as code: PRs, fixtures, path tests, semantic version notes, operator docs, and worker compatibility matrix.',followUps:['Business signoff?']},
  {id:'a6',level:'Architect',topic:'Compliance',question:'How handle PCI/PII with Camunda?',answer30s:'Keep sensitive data out of variables and UIs.',answer2m:'Tokenize PAN, store secrets in secure DB/vault, pass IDs and masked fields, restrict Operate/Tasklist, audit approvals, redact logs/traces.',followUps:['Support access?']},
  {id:'a7',level:'Architect',topic:'Capacity',question:'How capacity-plan Zeebe and workers?',answer30s:'Estimate process starts, jobs per instance, timers, variables, partitions, and worker latency.',answer2m:'Payment flow has about N jobs per payment; multiply by peak TPS, retries, incidents, exporter volume, and downstream latency to size partitions and workers.',followUps:['Bottleneck examples?']},
  {id:'a8',level:'Architect',topic:'Ownership',question:'Who owns incidents?',answer30s:'Workflow platform owns engine health; payment team owns domain worker failures.',answer2m:'Define on-call split, runbooks by BPMN element/job type, escalation paths, and permissions to resolve incidents.',followUps:['Shared platform?']},
  {id:'a9',level:'Architect',topic:'Migration',question:'How migrate Camunda 7 payment flows to 8?',answer30s:'Inventory BPMN/delegates, redesign workers, replace SQL monitoring, test semantics, roll gradually.',answer2m:'Externalize delegates into idempotent workers, map variables, handle versions, migrate or drain in-flight instances, train operators on Operate.',followUps:['Hardest part?']},
  {id:'a10',level:'Architect',topic:'Data model',question:'How model payment state with workflow state?',answer30s:'Use explicit domain state machine in DB and map workflow milestones to state transitions.',answer2m:'DB states like REQUESTED, VALIDATED, REJECTED, APPROVAL_PENDING, PROCESSING, SETTLED, FAILED_COMPENSATED should be authoritative.',followUps:['Avoid drift?']},
  {id:'a11',level:'Architect',topic:'Human workflow',question:'How design approval at scale?',answer30s:'Tasklist/custom UI with groups, SLA timers, audit, delegation, and metrics.',answer2m:'Add candidate groups, assignment policy, timeout escalation, supervisor override, audit events, and business reports from DB.',followUps:['Segregation of duties?']},
  {id:'a12',level:'Architect',topic:'Resilience',question:'How isolate fraud outage from all payments?',answer30s:'Separate worker pool, rate limits, circuit breaker, timeout, incident path, business fallback.',answer2m:'Backpressure fraud-check without starving notify/process workers; decide whether low-risk payments queue, manual-review, or fail closed.',followUps:['Fail open?']},
  {id:'a13',level:'Architect',topic:'Observability',question:'What is the executive dashboard?',answer30s:'Domain status from DB plus workflow health from Camunda metrics.',answer2m:'Show requested/settled/rejected/approval pending, aging approvals, incidents by element, retry burn, bank latency, and reconciliation gaps.',followUps:['Operate vs BI?']},
  {id:'a14',level:'Architect',topic:'Cost',question:'Where do costs grow?',answer30s:'Brokers, Elastic/OpenSearch, worker pods, Operate data retention, and retries.',answer2m:'Large variables, high exporter volume, excessive retries, and over-modeled BPMN increase cost. Use retention and right-sized workers.',followUps:['Retention policy?']},
  {id:'a15',level:'Architect',topic:'Decision',question:'When would you reject Camunda?',answer30s:'If no business-visible process, human task, timer, or orchestration need exists.',answer2m:'For simple pub/sub use Kafka; AWS glue use Step Functions; code-first durable workflows use Temporal; simple CRUD use no workflow engine.',followUps:['Overengineering signs?']},
  {id:'a16',level:'Architect',topic:'Interview story',question:'Tell a production incident story.',answer30s:'Bank 5xx exhausted retries, incident blocked settlement, operators resolved after downstream fix without double charge.',answer2m:'Explain detection, Operate element, payment DB reference, idempotency check, retry/resolution, customer communication, and preventive metric/runbook.',followUps:['What changed after?']},
];

export const ALL: InterviewQ[] = [...BEGINNER, ...INTERMEDIATE, ...SENIOR, ...ARCHITECT];
