import type {TocItem} from './types';

export const CAMUNDA_TOC: TocItem[] = [
  {id: 'overview', label: 'Overview · Payment Platform'},
  {id: 'code-sequences', label: 'Lifecycle Sequences'},
  {id: 'architecture', label: 'Architecture'},
  {id: 'c7-vs-c8', label: 'Camunda 7 vs 8'},
  {id: 'components', label: 'Components'},
  {id: 'payment-bpmn', label: 'Payment BPMN'},
  {id: 'spring-workers', label: 'Spring Boot + Workers'},
  {id: 'rest-apis', label: 'REST APIs'},
  {id: 'zeebe-storage', label: 'Zeebe Storage'},
  {id: 'bpmn-elements', label: 'BPMN Elements'},
  {id: 'user-tasks', label: 'User Tasks'},
  {id: 'timers', label: 'Timers'},
  {id: 'messages', label: 'Messages'},
  {id: 'errors-retries-incidents', label: 'Errors · Retries · Incidents'},
  {id: 'saga', label: 'Saga Compensation'},
  {id: 'parallel-multi-instance', label: 'Parallel · Multi-Instance'},
  {id: 'versioning', label: 'Versioning'},
  {id: 'security', label: 'Security'},
  {id: 'observability', label: 'Observability'},
  {id: 'business-db-vs-workflow', label: 'Business DB vs Workflow'},
  {id: 'testing', label: 'Testing'},
  {id: 'k8s', label: 'Kubernetes'},
  {id: 'mistakes', label: 'Production Mistakes'},
  {id: 'alternatives', label: 'Camunda vs Alternatives'},
  {id: 'decision-tree', label: 'Decision Tree'},
  {id: 'storytelling', label: 'Storytelling Answers'},
  {id: 'interview', label: '60+ Interview Qs'},
  {id: 'lab', label: 'Lab Explorer'},
  {id: 'checklist', label: 'Production Checklist'},
  {id: 'cheat-sheet', label: 'Cheat Sheet'},
];
