import type {TocItem} from './types';

export const LOCK_TOC: TocItem[] = [
  {id: 'overview', label: 'Why JVM Locks Fail'},
  {id: 'taxonomy', label: 'Lock Taxonomy'},
  {id: 'banking', label: 'Bank Debit Race'},
  {id: 'db-for-update', label: 'DB FOR UPDATE'},
  {id: 'db-lock-table', label: 'DB Lock Table'},
  {id: 'redis-lock', label: 'Redis SET NX PX'},
  {id: 'redis-unlock', label: 'Safe Redis Unlock'},
  {id: 'redisson', label: 'Redisson RLock'},
  {id: 'zookeeper', label: 'ZooKeeper / Curator'},
  {id: 'hazelcast', label: 'Hazelcast ILock'},
  {id: 'infinispan', label: 'Infinispan'},
  {id: 'file-lock', label: 'File Lock (Legacy)'},
  {id: 'behaviors', label: 'Blocking / Timed'},
  {id: 'reentrant', label: 'Reentrant vs Not'},
  {id: 'lease', label: 'Lease / TTL'},
  {id: 'fencing', label: 'Fencing Token'},
  {id: 'failures', label: 'Failure Scenarios'},
  {id: 'deadlock', label: 'Deadlock'},
  {id: 'tx-order', label: 'Lock + Transaction'},
  {id: 'vs-optimistic', label: 'vs Optimistic'},
  {id: 'vs-db', label: 'vs DB Lock'},
  {id: 'vs-saga', label: 'vs Saga'},
  {id: 'when-not', label: 'When NOT to Lock'},
  {id: 'observability', label: 'Observability'},
  {id: 'matrix', label: 'Comparison Matrix'},
  {id: 'decision', label: 'Decision Tree'},
  {id: 'interview', label: 'Interview Mode'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'cheat', label: 'Cheat Sheet'},
];
