package com.vibhu.hadron.domain;

public enum EventType {
  CASHLINE_CREATED,
  CASHLINE_UPDATED,
  CASHLINE_VALIDATED,
  CASHLINE_PROCESSING,
  CASHLINE_SETTLED,
  CASHLINE_COMPLETED,
  CASHLINE_CANCELLED
}
