server:
  port: 8091

spring:
  application:
    name: payment-api
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10
      transaction-id-prefix: payment-api-tx-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        compression.type: zstd
        linger.ms: 25
        batch.size: 65536
        buffer.memory: 33554432
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        spring.json.add.type.headers: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
