import type {TocItem} from './types';

export const LB_TOC: TocItem[] = [
  {id: 'overview', label: 'The Problem'},
  {id: 'taxonomy', label: 'LB Taxonomy'},
  {id: 'l4-l7', label: 'L4 vs L7'},
  {id: 'round-robin', label: 'Round Robin'},
  {id: 'weighted-rr', label: 'Weighted RR'},
  {id: 'least-conn', label: 'Least Connections'},
  {id: 'ip-hash', label: 'IP Hash'},
  {id: 'consistent-hash', label: 'Consistent Hash'},
  {id: 'sticky', label: 'Sticky Sessions'},
  {id: 'health', label: 'Health Checks'},
  {id: 'responsibilities', label: 'LB Responsibilities'},
  {id: 'tls', label: 'TLS Termination'},
  {id: 'retry', label: 'Retry & Timeout'},
  {id: 'failover', label: 'Failover'},
  {id: 'spring', label: 'Spring Load Balancing'},
  {id: 'aws-alb', label: 'AWS ALB'},
  {id: 'aws-nlb', label: 'AWS NLB'},
  {id: 'alb-vs-nlb', label: 'ALB vs NLB'},
  {id: 'api-gw', label: 'API Gateway vs LB'},
  {id: 'deploy', label: 'Zero-Downtime Deploy'},
  {id: 'security', label: 'WAF & Security'},
  {id: 'observability', label: 'Observability'},
  {id: 'kafka', label: 'LB vs Kafka'},
  {id: 'architecture', label: 'Banking Architecture'},
  {id: 'decision', label: 'Decision Tree'},
  {id: 'interview', label: 'Interview Mode'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'cheat', label: 'Cheat Sheet'},
];
