server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: payment-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${INSTANCE_ID:payment-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
