eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

server:
  shutdown: graceful
  tomcat:
    connection-timeout: 5s

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
