import type {TocItem} from './types';

export const JAVA_VERSIONS_TOC: TocItem[] = [
  {id: 'timeline', label: 'Version Timeline'},
  {id: 'comparison', label: 'Comparison Dashboard'},
  {id: 'java-8', label: 'Java 8'},
  {id: 'java-11', label: 'Java 11'},
  {id: 'java-17', label: 'Java 17'},
  {id: 'java-21', label: 'Java 21'},
  {id: 'java-25', label: 'Java 25'},
  {id: 'feature-evolution', label: 'Feature Evolution'},
  {id: 'jvm-evolution', label: 'JVM Evolution'},
  {id: 'concurrency-evolution', label: 'Concurrency Evolution'},
  {id: 'gc-evolution', label: 'Garbage Collection'},
  {id: 'performance-evolution', label: 'Performance Evolution'},
  {id: 'security-evolution', label: 'Security Evolution'},
  {id: 'migrate-8-11', label: 'Java 8 → 11 Migration'},
  {id: 'migrate-11-17', label: 'Java 11 → 17 Migration'},
  {id: 'migrate-17-21', label: 'Java 17 → 21 Migration'},
  {id: 'migrate-21-25', label: 'Java 21 → 25 Migration'},
  {id: 'migrate-8-25', label: 'Complete 8 → 25 Migration'},
  {id: 'checklist', label: 'Production Migration Checklist'},
  {id: 'risk-matrix', label: 'Migration Risk Matrix'},
  {id: 'architecture-decisions', label: 'Architecture Decisions'},
  {id: 'anti-patterns', label: 'Modernization Mistakes'},
  {id: 'interview-questions', label: 'Interview Questions'},
  {id: 'principal-questions', label: 'Principal / Architect'},
  {id: 'scenarios', label: 'Scenario-Based Questions'},
  {id: 'answer-framework', label: 'Interview Answer Framework'},
  {id: 'interview-mode', label: 'Interview Mode'},
  {id: 'principal-mode', label: 'Principal / Architect Mode'},
  {id: 'cheat-sheet', label: 'Cheat Sheet'},
  {id: 'one-liners', label: 'One-Line Answers'},
  {id: 'quick-reference', label: 'Quick Reference'},
  {id: 'playground', label: 'Code Playground'},
];
