server:
  port: 8081

spring:
  application:
    name: api-service
  datasource:
    url: jdbc:h2:mem:api;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

logging:
  level:
    org.springframework.security: INFO
