import type {InterviewQ} from './types';

export const INTERVIEW_QUESTIONS: InterviewQ[] = [
  {
    id: 'q1',
    question: 'synchronized vs ReentrantLock?',
    short: 'synchronized is simplest automatic monitor locking. ReentrantLock adds tryLock, timeouts, interruptibility, fairness, and Conditions.',
    detailed: 'Choose synchronized for straightforward critical sections. Choose ReentrantLock when acquisition policy matters or you need multiple condition queues. Both are JVM-local only.',
    mistake: 'Using ReentrantLock everywhere “because it’s advanced”.',
    followUp: 'When does fair mode hurt you?',
  },
  {
    id: 'q2',
    question: 'How does CAS work?',
    short: 'CPU atomic compare-and-swap updates a memory word only if it still equals an expected value; otherwise the caller retries.',
    detailed: 'Atomics loop on CAS. No mutual-exclusion lock, but contention causes retry spin. Great for single-variable state; not for multi-account transfers.',
    code: `balance.compareAndSet(1000, 900);`,
    mistake: 'Thinking CAS makes multi-field invariants safe.',
    followUp: 'What is the ABA problem?',
  },
  {
    id: 'q3',
    question: 'Why is volatile int counter; counter++ unsafe?',
    short: 'volatile publishes each write, but ++ is read-modify-write — not atomic — so increments can be lost.',
    detailed: 'Two threads can read the same value and both write value+1. Use AtomicInteger or LongAdder.',
    mistake: 'Assuming volatile means “thread-safe for everything”.',
    followUp: 'Where is volatile still the right tool?',
  },
  {
    id: 'q4',
    question: 'How does ConcurrentHashMap achieve concurrency?',
    short: 'Reads are largely non-blocking; updates use CAS and fine-grained synchronization on bins (Java 8+), plus atomic compound methods.',
    detailed: 'Java 7 used segments; Java 8+ uses bins/trees. Never DIY containsKey+put — use computeIfAbsent/merge.',
    mistake: 'Wrapping CHM with a giant synchronized for every call.',
    followUp: 'How can computeIfAbsent deadlock?',
  },
  {
    id: 'q5',
    question: 'What is lock contention?',
    short: 'Many threads compete for the same lock, causing blocking, queueing, and throughput collapse.',
    detailed: 'Fix with finer granularity, less work under lock, atomics, striping, or redesign.',
    mistake: 'Buying a bigger VM instead of reducing critical section size.',
    followUp: 'Which JFR events show contention?',
  },
  {
    id: 'q6',
    question: 'What is lock escalation?',
    short: 'In databases, many fine locks may escalate to coarser page/table locks; in Java, “escalation” is less formal — usually people mean coarsening or biased-locking era myths.',
    detailed: 'Be precise: talk DB lock escalation vs JVM lock coarsening separately in interviews.',
    mistake: 'Claiming HotSpot “escalates synchronized to table locks”.',
    followUp: 'How does Oracle lock escalation differ from PostgreSQL’s model?',
  },
  {
    id: 'q7',
    question: 'What is deadlock?',
    short: 'A cycle of threads each waiting for a lock the next holds — all blocked forever.',
    detailed: 'Four Coffman conditions; prevention via ordering/timeouts; detection via thread dumps.',
    mistake: 'Calling any hang a deadlock without proving a cycle.',
    followUp: 'Walk a real jstack deadlock section.',
  },
  {
    id: 'q8',
    question: 'How do you detect deadlocks?',
    short: 'jstack / jcmd Thread.print, JFR, and JVM deadlock detection sections in dumps.',
    detailed: 'Look for “Found one Java-level deadlock” and map waiting-to-lock edges.',
    mistake: 'Only restarting pods without capturing dumps.',
    followUp: 'How do you automate deadlock capture in K8s?',
  },
  {
    id: 'q9',
    question: 'How do you prevent deadlocks?',
    short: 'Global lock ordering, smaller critical sections, tryLock with backoff, avoid lock-after-lock when possible.',
    detailed: 'For accounts, always lock min(id) then max(id). Prefer single mutex or actor per aggregate.',
    mistake: 'Adding more synchronized hoping it helps.',
    followUp: 'How do DB deadlocks differ from Java monitor deadlocks?',
  },
  {
    id: 'q10',
    question: 'What is livelock?',
    short: 'Threads keep executing and yielding/retrying but make no progress.',
    detailed: 'Fix with randomized backoff or decisive winner policies.',
    mistake: 'Confusing livelock with deadlock.',
    followUp: 'Retry storms as livelock — example?',
  },
  {
    id: 'q11',
    question: 'What is starvation?',
    short: 'A thread repeatedly loses scheduling/lock acquisition and never runs usefully.',
    detailed: 'Fair locks, aging, and separate pools help.',
    mistake: 'Enabling fairness globally without measuring.',
    followUp: 'Writer starvation on RW locks?',
  },
  {
    id: 'q12',
    question: 'What is lock-free?',
    short: 'At least one thread makes progress system-wide even under contention, typically via CAS — not that every operation is contention-free.',
    detailed: 'Lock-free ≠ wait-free. Concurrent structures often are lock-free for some ops.',
    mistake: 'Saying “no locks anywhere in the JVM”.',
    followUp: 'Give a wait-free vs lock-free example.',
  },
  {
    id: 'q13',
    question: 'What is wait-free?',
    short: 'Every thread completes its operation in a bounded number of steps regardless of others.',
    detailed: 'Stronger than lock-free; rarer and specialized.',
    mistake: 'Calling AtomicInteger.wait-free for all usage patterns casually.',
    followUp: 'Why is wait-free hard in practice?',
  },
  {
    id: 'q14',
    question: 'ReentrantLock fairness?',
    short: 'Fair mode roughly honors queue order; unfair allows barging and usually higher throughput.',
    detailed: 'Default unfair is preferred unless starvation is observed.',
    mistake: 'new ReentrantLock(true) as cargo cult.',
    followUp: 'How would you prove fairness fixed a prod issue?',
  },
  {
    id: 'q15',
    question: 'ReadWriteLock vs StampedLock?',
    short: 'RW is reentrant and simpler; StampedLock adds optimistic reads but is not reentrant.',
    detailed: 'Pick StampedLock when optimistic success rate is high and code paths are controlled.',
    mistake: 'Calling unknown code under optimistic read.',
    followUp: 'Can you upgrade read to write on RW lock?',
  },
  {
    id: 'q16',
    question: 'AtomicInteger vs LongAdder?',
    short: 'AtomicInteger: precise single counter with CAS. LongAdder: striped cells for higher throughput under contention; sum is eventually consistent across cells until summed.',
    detailed: 'Metrics often prefer LongAdder; identity counters needing instantaneous precise get may prefer Atomic*.',
    mistake: 'Using LongAdder where a single atomic state machine is required.',
    followUp: 'When is LongAccumulator appropriate?',
  },
  {
    id: 'q17',
    question: 'Semaphore vs CountDownLatch?',
    short: 'Semaphore limits concurrent permits and is reusable via release. Latch waits for N events once and does not reset.',
    detailed: 'Bulkhead vs startup gate.',
    mistake: 'Using latch to limit concurrency.',
    followUp: 'Fair Semaphore use cases?',
  },
  {
    id: 'q18',
    question: 'CountDownLatch vs CyclicBarrier?',
    short: 'Latch: one-shot open. Barrier: fixed parties wait each phase and reuse.',
    detailed: 'Startup vs parallel phased algorithms.',
    mistake: 'Resetting a latch (you can’t).',
    followUp: 'When move from Barrier to Phaser?',
  },
  {
    id: 'q19',
    question: 'synchronized vs database lock?',
    short: 'synchronized protects memory in one JVM. DB locks protect durable shared rows across processes.',
    detailed: 'Payments that share a ledger need transactions/@Version/SELECT FOR UPDATE — not only monitors.',
    mistake: 'Assuming a Spring singleton lock serializes all pods.',
    followUp: 'Optimistic vs pessimistic for wallet debit?',
  },
  {
    id: 'q20',
    question: 'Why can’t synchronized provide distributed locking?',
    short: 'Each JVM has its own monitors; they do not coordinate across processes.',
    detailed: 'Need Redis/ZK/DB locks with lease and fencing — plus idempotency.',
    mistake: 'static synchronized on @Scheduled in K8s.',
    followUp: 'What breaks without fencing tokens?',
  },
  {
    id: 'q21',
    question: 'How would you implement a distributed lock?',
    short: 'Acquire with unique token + TTL in a shared store; do work; release if owner; prefer fencing with monotonic tokens on writes.',
    detailed: 'Discuss failure: GC over TTL, clock issues, process kill, network partitions. Link to site’s distributed-systems guides.',
    mistake: 'SET NX without expiry/ownership checks as “prod ready”.',
    followUp: 'Redlock debate — what is your stance?',
  },
  {
    id: 'q22',
    question: 'What happens when a JVM holding a lock crashes?',
    short: 'JVM monitors die with the process — waiters in that JVM are gone too. Distributed leases expire; design must tolerate reclaim.',
    detailed: 'Crash safety differs completely between intrinsic locks and distributed leases.',
    mistake: 'Assuming Redis lock releases instantly on kill without TTL.',
    followUp: 'How do you size TTL vs GC risk?',
  },
  {
    id: 'q23',
    question: 'What is a fencing token?',
    short: 'A monotonic token issued with lock acquisition that storage checks so a late/expired holder cannot commit.',
    detailed: 'Without fencing, a paused holder can still write after losing the lock.',
    mistake: 'Tokenless locks for money movement.',
    followUp: 'How do you store fencing tokens with DB writes?',
  },
  {
    id: 'q24',
    question: 'How would you reduce lock contention?',
    short: 'Shrink critical sections, partition data/locks, use atomics/CHM, remove I/O under locks, consider lock-free structures.',
    detailed: 'Profile first with JFR before rewriting.',
    mistake: 'Rewriting to StampedLock without evidence.',
    followUp: 'Show a before/after contention flamegraph plan.',
  },
  {
    id: 'q25',
    question: 'How would you diagnose a production deadlock?',
    short: 'Capture thread dumps from all pods, find the cycle, identify locks/objects, ship a fix with ordering/timeout, add regression test.',
    detailed: 'Also check DB deadlocks in AWR/pg logs — symptoms can look similar at the API layer.',
    code: `"Thread-1": waiting to lock monitor X held by Thread-2
"Thread-2": waiting to lock monitor Y held by Thread-1`,
    mistake: 'Restart only, no dump, no root cause.',
    followUp: 'How do you prevent recurrence in CI?',
  },
];
