import type {TocItem} from './types';

export const LOCKING_TOC: TocItem[] = [
  {id: 'overview', label: 'Locking Overview'},
  {id: 'timeline', label: 'Evolution Timeline'},
  {id: 'synchronized', label: 'synchronized'},
  {id: 'volatile', label: 'volatile'},
  {id: 'wait-notify', label: 'wait / notify'},
  {id: 'reentrant-lock', label: 'ReentrantLock'},
  {id: 'read-write-lock', label: 'ReadWriteLock'},
  {id: 'stamped-lock', label: 'StampedLock'},
  {id: 'lock-support', label: 'LockSupport'},
  {id: 'semaphore', label: 'Semaphore'},
  {id: 'count-down-latch', label: 'CountDownLatch'},
  {id: 'cyclic-barrier', label: 'CyclicBarrier'},
  {id: 'phaser', label: 'Phaser'},
  {id: 'atomic', label: 'Atomic / CAS'},
  {id: 'optimistic-pessimistic', label: 'Optimistic vs Pessimistic'},
  {id: 'fair-unfair', label: 'Fair vs Unfair'},
  {id: 'reentrant-concepts', label: 'Reentrant Concepts'},
  {id: 'spin-lock', label: 'Spin Lock'},
  {id: 'custom-lock', label: 'Custom Lock'},
  {id: 'thread-safe-collections', label: 'Thread-safe Collections'},
  {id: 'concurrent-hash-map', label: 'ConcurrentHashMap'},
  {id: 'db-locking', label: 'Database Locking'},
  {id: 'distributed-locking', label: 'Distributed Locking'},
  {id: 'jvm-vs-distributed', label: 'JVM vs Distributed'},
  {id: 'deadlock', label: 'Deadlock'},
  {id: 'livelock', label: 'Livelock'},
  {id: 'starvation', label: 'Starvation'},
  {id: 'race-condition', label: 'Race Condition'},
  {id: 'contention-granularity', label: 'Contention & Granularity'},
  {id: 'lock-free', label: 'Lock-free vs Wait-free'},
  {id: 'payment-system', label: 'Payment System Example'},
  {id: 'production-problems', label: 'Production Problems'},
  {id: 'wrong-choices', label: 'Wrong Lock Choices'},
  {id: 'choose-lock', label: 'Choose the Lock'},
  {id: 'debugging', label: 'Production Debugging'},
  {id: 'benchmark', label: 'Performance Experiment'},
  {id: 'lab', label: 'Concurrency Laboratory'},
  {id: 'decision-tree', label: 'Decision Tree'},
  {id: 'comparison', label: 'Master Comparison'},
  {id: 'best-practices', label: 'Production Best Practices'},
  {id: 'interview-mode', label: 'Interview Mode'},
  {id: 'cheat-sheet', label: 'One Screen Cheat Sheet'},
  {id: 'remember', label: 'Remember Forever'},
];
