import type {GoldenAnswers} from './types';

export const GOLDEN: {name: string; answers: GoldenAnswers}[] = [
  {
    name: '@EnableKafka',
    answers: {
      problem: 'Enable detection of @KafkaListener methods and listener infrastructure.',
      executes: 'Spring ApplicationContext startup.',
      owner: 'Spring Kafka annotation config.',
      kafkaApi: 'None directly — enables containers that later use Consumer API.',
      offset: 'N/A',
      onFailure: 'Context fails if listener beans misconfigured.',
      createsTopic: 'No',
      createsProducer: 'No',
      createsConsumer: 'Indirectly enables containers that create consumers.',
      ordering: 'No',
      transactions: 'No',
      consumerGroups: 'No (listeners define groups)',
      risks: 'Assuming it configures brokers.',
      alternative: 'Boot auto-config / @EnableKafkaRetryTopic',
      whenNot: 'Non-Kafka apps; duplicate enable with conflicting retry config.',
    },
  },
  {
    name: '@KafkaListener',
    answers: {
      problem: 'Declare a consumer endpoint for topic(s).',
      executes: 'Listener container thread(s) after poll/deserialize.',
      owner: 'Spring MessageListenerContainer.',
      kafkaApi: 'KafkaConsumer poll/commit/subscribe.',
      offset: 'Per AckMode / manual ack / transactions.',
      onFailure: 'CommonErrorHandler / ARP / @RetryableTopic path.',
      createsTopic: 'No',
      createsProducer: 'No (unless @SendTo/@RetryableTopic forwarding)',
      createsConsumer: 'Yes (via container)',
      ordering: 'Per partition for that consumer assignment',
      transactions: 'Only if wired with Kafka TM',
      consumerGroups: 'Yes — groupId',
      risks: 'Wrong group, AckMode, concurrency, missing idempotency',
      alternative: 'MessageListenerAdapter / reactive / Kafka Streams',
      whenNot: 'When you need broker admin — use AdminClient.',
    },
  },
  {
    name: '@RetryableTopic',
    answers: {
      problem: 'Non-blocking delayed retries + DLT without blocking main partition long.',
      executes: 'Spring RetryTopicConfigurer + hop consumers.',
      owner: 'Spring Kafka retry-topic feature.',
      kafkaApi: 'Producer forward + Consumer on retry/DLT topics.',
      offset: 'Main offset advances after successful forward to retry/DLT (design carefully).',
      onFailure: 'Next hop or DLT; DLT handler strategy applies.',
      createsTopic: 'Optionally (autoCreateTopics) — prefer IaC.',
      createsProducer: 'Uses KafkaTemplate to forward.',
      createsConsumer: 'Yes for retry/DLT containers.',
      ordering: 'Can break same-key order vs main progress.',
      transactions: 'Advanced / test thoroughly.',
      consumerGroups: 'Additional containers/groups for hops.',
      risks: 'Topic sprawl, ordering, batch unsupported.',
      alternative: 'DefaultErrorHandler or manual retry topics.',
      whenNot: 'Batch listeners; strict in-partition order with long delays.',
    },
  },
  {
    name: '@DltHandler',
    answers: {
      problem: 'Application hook when records land in DLT.',
      executes: 'DLT listener container thread.',
      owner: 'Spring retry-topic DLT infrastructure.',
      kafkaApi: 'KafkaConsumer on DLT topic.',
      offset: 'DLT consumer commits on handler success.',
      onFailure: 'dltStrategy — retry forever vs fail vs no DLT.',
      createsTopic: 'No',
      createsProducer: 'No',
      createsConsumer: 'Uses DLT container consumer',
      ordering: 'DLT partition order only',
      transactions: 'Optional',
      consumerGroups: 'DLT container group',
      risks: 'Silent loops; treating as business workflow',
      alternative: 'External ops consumer / logging default',
      whenNot: 'When another service owns DLT drain.',
    },
  },
  {
    name: '@SendTo',
    answers: {
      problem: 'Publish listener return value to a topic/reply destination.',
      executes: 'After successful listener return.',
      owner: 'Spring Messaging + KafkaTemplate.',
      kafkaApi: 'Producer send.',
      offset: 'Independent of source commit timing — still after success path.',
      onFailure: 'No publish if listener throws.',
      createsTopic: 'No',
      createsProducer: 'Uses template producer',
      createsConsumer: 'No',
      ordering: 'Downstream topic key determines order',
      transactions: 'Can enroll in Kafka TX if configured',
      consumerGroups: 'No',
      risks: 'Hidden coupling; null ignored',
      alternative: 'Explicit KafkaTemplate + outbox',
      whenNot: 'Complex multi-write workflows.',
    },
  },
  {
    name: '@Transactional',
    answers: {
      problem: 'Declare a Spring transaction boundary.',
      executes: 'Around annotated method (proxy).',
      owner: 'Spring PlatformTransactionManager.',
      kafkaApi: 'If Kafka TM: begin/commit/abort + sendOffsetsToTransaction.',
      offset: 'Committed with Kafka TX or not at all on rollback.',
      onFailure: 'Rollback; ARP may run for Kafka listeners.',
      createsTopic: 'No',
      createsProducer: 'Uses transactional producer when Kafka TM',
      createsConsumer: 'No',
      ordering: 'Indirect via commit visibility (read_committed)',
      transactions: 'Yes — that is the point',
      consumerGroups: 'No',
      risks: 'Wrong TM; false DB+Kafka atomicity claims',
      alternative: 'KafkaTemplate.executeInTransaction / outbox',
      whenNot: 'When you only meant DB TX — say so explicitly.',
    },
  },
];
