import type {InterviewQ} from './types';

export const SENIOR_Q: InterviewQ[] = [
  {
    id: 's01',
    level: 'Senior',
    question: 'What does @EnableKafka actually enable?',
    short: 'It turns on Spring Kafka listener annotation processing so @KafkaListener methods are discovered and wired.',
    deep: 'KafkaListenerAnnotationBeanPostProcessor scans beans and registers MessageListenerContainers. It runs in the ApplicationContext, not on the broker.',
    code: '@Configuration\n@EnableKafka\npublic class KafkaConfig {}',
    mistake: 'Thinking @EnableKafka creates brokers, topics, or consumer groups.',
    followUp: 'Is explicit @EnableKafka required in every Spring Boot Kafka app?',
  },
  {
    id: 's02',
    level: 'Senior',
    question: 'What does @KafkaListener create at runtime?',
    short: 'A MessageListenerContainer (usually ConcurrentKafkaListenerContainer) that owns KafkaConsumer poll loops for the declared topics and group.',
    deep: 'Each listener id maps to container infrastructure: subscribe/assign, deserialize, invoke method, then ack/commit per AckMode. Concurrency creates multiple KafkaMessageListenerContainer threads.',
    code: '@KafkaListener(topics = "orders.v1", groupId = "order-service")\npublic void consume(Order order) { process(order); }',
    mistake: 'Saying the annotation runs on the Kafka broker or creates the topic.',
    followUp: 'What changes if concurrency is greater than partition count?',
  },
  {
    id: 's03',
    level: 'Senior',
    question: 'Where does the Kafka consumer live relative to @KafkaListener?',
    short: 'Inside the Spring listener container after context startup; the broker only stores topics and serves Consumer API calls.',
    deep: 'Annotations configure Spring. The container uses KafkaConsumer.poll, commits offsets, and applies CommonErrorHandler or retry-topic paths.',
    code: '// Consumer created by ConcurrentKafkaListenerContainerFactory\n// Broker never sees @KafkaListener',
    mistake: 'Claiming Kafka executes Spring annotations.',
    followUp: 'What is the difference between ConsumerFactory and the listener method?',
  },
  {
    id: 's04',
    level: 'Senior',
    question: 'What does @RetryableTopic do?',
    short: 'It configures non-blocking delayed retries: failed records are forwarded to retry topics, then optionally to a DLT, with separate hop consumers.',
    deep: 'Spring RetryTopicConfigurer wires templates, hop containers, and DLT strategy. Kafka itself does not retry; Spring producers publish to hop topics.',
    code: '@RetryableTopic(attempts = "4", backoff = @Backoff(delay = 1000, multiplier = 2.0))\n@KafkaListener(topics = "orders.v1", groupId = "order-service")\npublic void consume(Order o) { apply(o); }',
    mistake: 'Believing the broker implements @RetryableTopic retries.',
    followUp: 'What does attempts include - original delivery or only retries?',
  },
  {
    id: 's05',
    level: 'Senior',
    question: 'Blocking retry vs non-blocking retry - how do they differ?',
    short: 'Blocking sleeps on the consumer thread (DefaultErrorHandler backoff). Non-blocking forwards to retry topics so the main partition can advance.',
    deep: 'Blocking preserves in-partition order but risks max.poll.interval.ms. Non-blocking adds topic/ops overhead and can reorder same-key work across hops.',
    code: '// DEH: FixedBackOff on listener thread\n// @RetryableTopic: publish to orders.v1-retry-1000 then consume later',
    mistake: 'Calling both "the same Kafka retry feature."',
    followUp: 'When would you still prefer blocking DefaultErrorHandler?',
  },
  {
    id: 's06',
    level: 'Senior',
    question: 'What happens to the offset when a @KafkaListener method throws?',
    short: 'By default the record is not treated as successfully processed; the error handler or after-rollback processor decides seek/retry/DLT before commit advances.',
    deep: 'AckMode and transactions matter: RECORD/BATCH commit timing differs; KafkaTransactionManager rolls back and AfterRollbackProcessor may recover. Manual ack without acknowledge leaves the offset uncommitted.',
    code: 'public void consume(Order o) {\n  throw new TransientException("db down"); // no success commit\n}',
    mistake: 'Assuming every throw always commits the offset and loses the message.',
    followUp: 'How does AckMode.MANUAL change this answer?',
  },
  {
    id: 's07',
    level: 'Senior',
    question: 'What if DLT publish fails after retries are exhausted?',
    short: 'The recoverer/forward path throws; the offset typically stays uncommitted and the partition keeps seeking/retrying until publish succeeds or ops intervenes.',
    deep: 'This is the "stuck partition vs lost failure" trade-off. Prefer alerting on recoverer failure rather than committing past a failed DLT publish.',
    code: '// DeadLetterPublishingRecoverer / retry-topic forward fails -> record remains for redelivery',
    mistake: 'Committing the source offset even when DLT publish failed.',
    followUp: 'How do resetStateOnRecoveryFailure semantics affect backoff?',
  },
  {
    id: 's08',
    level: 'Senior',
    question: 'What does @DltHandler consume?',
    short: 'Records already published to the DLT topic for a @RetryableTopic listener in the same class.',
    deep: 'It is a DLT consumer hook with flexible signatures (payload, ConsumerRecord, exception headers). It is not invoked for successful main-path messages.',
    code: '@DltHandler\npublic void onDlt(Order order, @Header(KafkaHeaders.EXCEPTION_MESSAGE) String msg) {\n  ops.persistDeadLetter(order, msg);\n}',
    mistake: 'Using @DltHandler as the primary business workflow for happy-path events.',
    followUp: 'What headers are typically available on DLT records?',
  },
  {
    id: 's09',
    level: 'Senior',
    question: 'Does @DltHandler create the DLT topic?',
    short: 'No. @RetryableTopic / RetryTopicConfiguration owns DLT topic creation or expectation; @DltHandler only registers a handler for DLT consumption.',
    deep: 'autoCreateTopics on @RetryableTopic may create topics (prefer IaC in prod). Without @RetryableTopic, @DltHandler alone does nothing useful.',
    code: '@RetryableTopic(autoCreateTopics = "false", dltTopicSuffix = "-dlt")\n@KafkaListener(...)\npublic void consume(Order o) {}\n\n@DltHandler\npublic void onDlt(Order o) {}',
    mistake: 'Assuming @DltHandler both creates and drains the DLT.',
    followUp: 'What happens if no @DltHandler is present?',
  },
  {
    id: 's10',
    level: 'Senior',
    question: 'Explain @SendTo internals on a Kafka listener.',
    short: 'After a successful listener return, Spring Messaging publishes the return value via KafkaTemplate to the @SendTo destination (fixed, SpEL, or reply header).',
    deep: 'null return sends nothing. If the method throws, @SendTo does not publish. It is a reply/enrich pattern, not a broker-side route.',
    code: '@KafkaListener(topics = "orders.v1", groupId = "enricher")\n@SendTo("orders.processed.v1")\npublic ProcessedOrder process(Order order) {\n  return enrich(order);\n}',
    mistake: 'Thinking @SendTo runs even when the listener throws.',
    followUp: 'How does KafkaHeaders.REPLY_TOPIC interact with @SendTo?',
  },
  {
    id: 's11',
    level: 'Senior',
    question: 'What does @Transactional mean on a @KafkaListener method?',
    short: 'It opens a Spring transaction around the listener invocation via the configured PlatformTransactionManager.',
    deep: 'With KafkaTransactionManager, produce and sendOffsetsToTransaction commit together. With a DataSource TM, you only get a DB transaction unless you deliberately compose patterns.',
    code: '@Transactional("kafkaTransactionManager")\n@KafkaListener(topics = "orders.v1", groupId = "order-svc")\npublic void consume(Order order) {\n  kafkaTemplate.send("orders.events.v1", order.id(), event(order));\n}',
    mistake: 'Assuming plain @Transactional always means Kafka EOS.',
    followUp: 'What rolls back when the listener throws under Kafka TM?',
  },
  {
    id: 's12',
    level: 'Senior',
    question: 'Which TransactionManager should you name for Kafka listener EOS?',
    short: 'KafkaTransactionManager (or the Boot bean that wraps a transactional ProducerFactory), not the JPA DataSourceTransactionManager by accident.',
    deep: 'Qualifier/bean name on @Transactional matters when multiple TMs exist. Wrong TM = DB commit while Kafka offsets/produces are independent.',
    code: '@Transactional("kafkaTransactionManager")\n@KafkaListener(...)\npublic void consume(Order o) { ... }',
    mistake: 'Relying on the primary TM when primary is DataSourceTransactionManager.',
    followUp: 'How do you verify the transactional producer is actually used?',
  },
  {
    id: 's13',
    level: 'Senior',
    question: 'Does @Transactional make DB writes and Kafka consume/produce atomic?',
    short: 'No. A single annotation does not magically merge PostgreSQL and Kafka into one atomic unit.',
    deep: 'Kafka-only EOS covers consume-process-produce in the broker sense. Cross-store needs outbox, inbox UNIQUE keys, or carefully designed dual-write patterns - never claim bank-grade exactly-once across both.',
    code: '@Transactional // often DB only\n@KafkaListener(...)\npublic void consume(Order o) {\n  repo.save(o); // not atomically tied to Kafka offset\n}',
    mistake: 'Saying "we have exactly-once because the listener is @Transactional."',
    followUp: 'When is transactional outbox the better answer than ChainedTransactionManager?',
  },
  {
    id: 's14',
    level: 'Senior',
    question: 'How does @KafkaHandler method selection work?',
    short: 'On a class-level @KafkaListener, Spring picks the @KafkaHandler whose parameter type is assignable from the deserialized payload.',
    deep: 'Ambiguous equally-applicable handlers fail at runtime. isDefault=true catches unmatched types. Handlers share one container and consumer group.',
    code: '@KafkaListener(topics = "events.v1", groupId = "event-router")\npublic class EventListener {\n  @KafkaHandler public void onOrder(OrderCreated e) {}\n  @KafkaHandler public void onPayment(PaymentCreated e) {}\n  @KafkaHandler(isDefault = true) public void unknown(Object o) {}\n}',
    mistake: 'Thinking each @KafkaHandler is a separate consumer group.',
    followUp: 'When should you prefer separate @KafkaListener methods over @KafkaHandler?',
  },
  {
    id: 's15',
    level: 'Senior',
    question: 'Does deserialization run before the @KafkaListener method?',
    short: 'Yes. The container deserializes during poll conversion; a hard deser failure means the typed listener method never runs.',
    deep: 'ErrorHandlingDeserializer wraps key/value desers, places DeserializationException in headers, and can deliver a null payload so error/DLT paths can run.',
    code: '// Without EHD: deser blow-up before listener\n// With ErrorHandlingDeserializer: headers carry DeserializationException',
    mistake: 'Putting try/catch inside the listener and expecting it to catch Serde failures.',
    followUp: 'How does DeadLetterPublishingRecoverer restore original bytes?',
  },
  {
    id: 's16',
    level: 'Senior',
    question: 'How does @RetryableTopic affect ordering for the same key?',
    short: 'Main-partition progress can continue after forward, so same-key events may reorder relative to later main-topic messages while an earlier one hops retries.',
    deep: 'Match partition counts and keying across hops to preserve partition affinity, but hop delays still break strict in-partition timeline vs blocking backoff.',
    code: '// key=K fails -> retry topic; key=K next message may process on main first',
    mistake: 'Claiming @RetryableTopic always preserves same-key order like in-thread DEH.',
    followUp: 'When is strict order more important than non-blocking retries?',
  },
  {
    id: 's17',
    level: 'Senior',
    question: 'DefaultErrorHandler vs @RetryableTopic - pick one for interview?',
    short: 'DEH = blocking in-thread backoff, simpler ops, batch-friendly. @RetryableTopic = non-blocking hop topics, more ops surface, not for batch listeners.',
    deep: 'Use DEH for short blips and strict partition order. Use retry topics for seconds-to-minutes transient dependency outages without stalling the whole partition.',
    code: '// DEH + DeadLetterPublishingRecoverer\n// vs @RetryableTopic + @DltHandler',
    mistake: 'Defaulting to @RetryableTopic for every service without ops capacity for topic sprawl.',
    followUp: 'How do exception classifiers differ between the two?',
  },
  {
    id: 's18',
    level: 'Senior',
    question: 'Can you use @RetryableTopic with a batch @KafkaListener?',
    short: 'No. Spring Kafka does not support @RetryableTopic on batch listeners.',
    deep: 'Use DefaultErrorHandler with BatchListenerFailedException and DeadLetterPublishingRecoverer for partial batch failure recovery.',
    code: '// BAD: @RetryableTopic + List<Order> / ConsumerRecords batch\n// GOOD: batch factory + DefaultErrorHandler + BatchListenerFailedException',
    mistake: 'Annotating a batch listener with @RetryableTopic hoping hops still work.',
    followUp: 'How does BatchListenerFailedException index recovery work?',
  },
  {
    id: 's19',
    level: 'Senior',
    question: 'What happens when @DltHandler itself throws?',
    short: 'DLT offset does not successfully complete; dltStrategy decides whether to keep redelivering (ALWAYS_RETRY_ON_ERROR) or fail (FAIL_ON_ERROR) / skip DLT (NO_DLT).',
    deep: 'Poison in the DLT handler can loop forever under ALWAYS_RETRY_ON_ERROR. Keep handlers light, idempotent, and instrumented.',
    code: '@RetryableTopic(dltStrategy = DltStrategy.FAIL_ON_ERROR)\n@KafkaListener(...)\npublic void consume(Order o) {}\n\n@DltHandler\npublic void onDlt(Order o) { throw new RuntimeException("sink down"); }',
    mistake: 'Ignoring dltStrategy and assuming DLT is a guarantee of successful processing.',
    followUp: 'When would you set autoStartDltHandler to false?',
  },
  {
    id: 's20',
    level: 'Senior',
    question: 'How do @SendTo and Kafka transactions interact?',
    short: 'When the listener runs under KafkaTransactionManager, the @SendTo publish can enroll in the same Kafka transaction as the consume offsets.',
    deep: 'On listener failure there is no @SendTo publish and the TX rolls back. Without Kafka TM, @SendTo is a separate produce after success with independent failure domains.',
    code: '@Transactional("kafkaTransactionManager")\n@KafkaListener(topics = "in")\n@SendTo("out")\npublic Out map(In in) { return transform(in); }',
    mistake: 'Assuming @SendTo is transactional just because @SendTo is present.',
    followUp: 'What happens if @SendTo produce fails inside the TX?',
  },
  {
    id: 's21',
    level: 'Senior',
    question: 'How do you use manual acknowledgment with @KafkaListener?',
    short: 'Set AckMode to MANUAL or MANUAL_IMMEDIATE and inject Acknowledgment; call acknowledge only after successful side effects (or successful DLT path).',
    deep: 'Acking before DB/outbox/DLT write can lose failure visibility. Never ack in a finally that runs on exceptions unless that is an intentional skip policy.',
    code: '@KafkaListener(..., properties = {}) // factory AckMode.MANUAL\npublic void consume(Order o, Acknowledgment ack) {\n  process(o);\n  ack.acknowledge();\n}',
    mistake: 'Acknowledging at method entry "to keep lag low."',
    followUp: 'MANUAL vs MANUAL_IMMEDIATE - when does the commit happen?',
  },
  {
    id: 's22',
    level: 'Senior',
    question: 'Do Spring Kafka annotations configure the Kafka broker?',
    short: 'No. They configure Spring application behavior that then uses Producer/Consumer/Admin clients against the broker.',
    deep: 'Broker configs (retention, ACLs, quotas) live in broker/topic settings - see kafka-properties - not in @KafkaListener attributes.',
    code: '// @KafkaListener groupId -> ConsumerConfig group.id on the client\n// Broker does not "run" the annotation',
    mistake: 'Equating annotation attributes with broker-side topic configuration.',
    followUp: 'Which annotation attributes become ConsumerConfig overrides?',
  },
  {
    id: 's23',
    level: 'Senior',
    question: 'What is @Backoff used for with Kafka annotations?',
    short: 'It sizes delay hops for @RetryableTopic (delay, multiplier, maxDelay, random jitter) via spring-retry metadata.',
    deep: 'In non-blocking mode the delay is realized by when hop consumers process forwarded records, not by sleeping the main listener for minutes.',
    code: '@Backoff(delay = 1000, multiplier = 2.0, maxDelay = 30_000, random = true)',
    mistake: 'Thinking @Backoff alone creates retry topics without @RetryableTopic.',
    followUp: 'Why enable random jitter in production fan-out systems?',
  },
  {
    id: 's24',
    level: 'Senior',
    question: 'What is @KafkaListeners for?',
    short: 'A repeatable container so one method can declare multiple @KafkaListener bindings (different topics, groups, or factories).',
    deep: 'Each nested @KafkaListener still creates its own container subscription semantics; the method body is shared.',
    code: '@KafkaListeners({\n  @KafkaListener(topics = "orders.v1", groupId = "billing", containerFactory = "jsonFactory"),\n  @KafkaListener(topics = "payments.v1", groupId = "billing", containerFactory = "avroFactory")\n})\npublic void onEither(@Payload Object payload) {}',
    mistake: 'Assuming one @KafkaListeners means one merged consumer subscription across factories.',
    followUp: 'When is duplicating two methods clearer than @KafkaListeners?',
  },
  {
    id: 's25',
    level: 'Senior',
    question: 'Is @EnableKafkaRetryTopic different from @EnableKafka?',
    short: 'Yes. @EnableKafkaRetryTopic enables non-blocking retry-topic infrastructure and is meta-annotated with @EnableKafka.',
    deep: 'Use it when you want the retry-topic import path. Avoid duplicating RetryTopicConfigurationSupport beans that conflict with Boot/auto config.',
    code: '@Configuration\n@EnableKafkaRetryTopic\npublic class RetryKafkaConfig {}',
    mistake: 'Adding both @EnableKafkaRetryTopic and a conflicting custom retry configuration blindly.',
    followUp: 'When is plain @EnableKafka enough?',
  },
];

export const STAFF_Q: InterviewQ[] = [
  {
    id: 't01',
    level: 'Staff',
    question: 'Design the failure path for a payments @KafkaListener - DEH or @RetryableTopic?',
    short: 'Prefer DEH for short blips and strict ledger order; prefer @RetryableTopic when dependency outages last long enough to stall partitions under sleep.',
    deep: 'Staff answer names max.poll.interval risk, same-key reorder risk, topic sprawl, and idempotent settlement. Poison exceptions go straight to DLT with zero long hops.',
    code: '@RetryableTopic(include = TransientException.class, exclude = ValidationException.class)\n@KafkaListener(topics = "payments.settle.v1", groupId = "settlement")\npublic void settle(Payment p) { ledger.apply(p); }',
    mistake: 'Picking retry topics solely because they sound more "enterprise."',
    followUp: 'How do you prove order SLOs for a payment key?',
  },
  {
    id: 't02',
    level: 'Staff',
    question: 'How do you operate @RetryableTopic topics in production?',
    short: 'Disable autoCreateTopics, provision hops/DLT via IaC with matching partitions, ACLs, retention, and alerts on hop/DLT lag.',
    deep: 'Name suffixes deliberately (delay vs index). Cap attempts and use include/exclude so poison does not fan out. Document which group owns each hop container.',
    code: '@RetryableTopic(autoCreateTopics = "false", numPartitions = "12", replicationFactor = "3")',
    mistake: 'Letting Spring auto-create topics with wrong partition counts in prod.',
    followUp: 'How do you capacity-plan DLT retention vs replay tooling?',
  },
  {
    id: 't03',
    level: 'Staff',
    question: 'Main offset advances after forward to retry - what can go wrong?',
    short: 'A later same-key message on main can process while an earlier failure is still hopping, breaking business sequencing.',
    deep: 'Mitigations: blocking retry for that stream, single-flight per key, version vectors, or accept reorder with commutative handlers. Interviewers want you to name the race, not deny it.',
    code: '// offset committed after successful forward to retry hop\n// main consumer continues polling',
    mistake: 'Saying non-blocking retry "never affects ordering."',
    followUp: 'Would you partition-by-account and still use hop retries?',
  },
  {
    id: 't04',
    level: 'Staff',
    question: 'How should exception classification interact with @RetryableTopic?',
    short: 'include transient infrastructure failures; exclude validation, serde, and business permanent errors so they go DLT immediately.',
    deep: 'traversingCauses walks wrapped exceptions. Be explicit - empty include/exclude defaults are easy to misread under stress.',
    code: '@RetryableTopic(\n  include = { QueryTimeoutException.class },\n  exclude = { ValidationException.class, DeserializationException.class },\n  traversingCauses = "true"\n)',
    mistake: 'Retrying JsonParseException ten times "just in case."',
    followUp: 'How do you classify HTTP 409 vs 503 from a downstream API?',
  },
  {
    id: 't05',
    level: 'Staff',
    question: 'Wire Kafka EOS for consume-transform-produce with annotations - what is the minimal correct set?',
    short: 'Transactional ProducerFactory, KafkaTransactionManager, @Transactional on the listener (named TM), and read_committed peers downstream.',
    deep: 'Offsets join via sendOffsetsToTransaction on success. AfterRollbackProcessor handles retries/DLT after rollback. Annotations alone without transactional producer config do nothing.',
    code: '@Transactional("kafkaTransactionManager")\n@KafkaListener(topics = "in", groupId = "eos")\npublic void on(In in) {\n  kafkaTemplate.send("out", in.key(), map(in));\n}',
    mistake: 'Adding only @Transactional without a transactional producer.',
    followUp: 'Where does ProducerFencedException show up in this design?',
  },
  {
    id: 't06',
    level: 'Staff',
    question: 'Staff review: @Transactional on listener that writes JPA and sends KafkaTemplate - approve?',
    short: 'Reject as written if the claim is atomic DB+Kafka. Approve only with an explicit outbox/inbox story and named TMs.',
    deep: 'ChainedTransactionManager is fragile under partial commit. Prefer DB transaction + outbox row, then relay to Kafka after commit.',
    code: '// Prefer:\n// @Transactional DataSource TM -> insert outbox\n// separate publisher reads outbox -> KafkaTemplate',
    mistake: 'Rubber-stamping "@Transactional means EOS across Postgres and Kafka."',
    followUp: 'How do you detect dual-write drift in metrics?',
  },
  {
    id: 't07',
    level: 'Staff',
    question: 'When is @SendTo a Staff-level smell?',
    short: 'When the return publish hides a second failure domain, fan-out, or multi-write workflow that needs outbox and explicit observability.',
    deep: 'Fine for enrich/reply. Poor for "listener returns event and we pretend downstream is covered." Prefer explicit KafkaTemplate + metrics + DLQ policy.',
    code: '// Smell: @SendTo("billing") + @SendTo-like side effects buried in return mapping',
    mistake: 'Using @SendTo to replace an outbox for financial postings.',
    followUp: 'How would you migrate @SendTo to an explicit produce without downtime?',
  },
  {
    id: 't08',
    level: 'Staff',
    question: 'How do you keep @DltHandler from becoming a silent poison loop?',
    short: 'Use FAIL_ON_ERROR or a quarantine path, make the sink idempotent on original topic+partition+offset, and alert on handler failures.',
    deep: 'ALWAYS_RETRY_ON_ERROR is dangerous for broken DLT sinks. autoStartDltHandler=false lets ops control drain during incidents.',
    code: '@RetryableTopic(dltStrategy = DltStrategy.FAIL_ON_ERROR, autoStartDltHandler = "true")',
    mistake: 'Logging-only DLT handlers with no metrics or unique constraints.',
    followUp: 'What UNIQUE key do you use for DLT sink rows?',
  },
  {
    id: 't09',
    level: 'Staff',
    question: 'Manual ack + DLT recoverer - what is the correct acknowledge timing?',
    short: 'Acknowledge only after successful business side effects or after successful DLT/recoverer publish, never before.',
    deep: 'Ack-before-DLT loses the failure record. Ack-after-partial DB write without idempotency creates duplicates on redelivery.',
    code: 'public void consume(Order o, Acknowledgment ack) {\n  try {\n    process(o);\n    ack.acknowledge();\n  } catch (PoisonException e) {\n    dlt.publish(o); // then ack per policy\n    ack.acknowledge();\n  }\n}',
    mistake: 'Ack in finally regardless of outcome.',
    followUp: 'How does this change under Kafka transactions?',
  },
  {
    id: 't10',
    level: 'Staff',
    question: 'Class-level @KafkaListener with @KafkaHandler - how do you design error policies per type?',
    short: 'You mostly cannot: handlers share one container, group, and error handler. Split listeners when types need different retry/DLT rules.',
    deep: 'Polymorphic routing is for dispatch convenience, not per-type AckMode. Use headers/topics for hard isolation.',
    code: '// Separate listeners:\n@KafkaListener(topics="orders", containerFactory="retryFactory")\n@KafkaListener(topics="metrics", containerFactory="cheapFactory")',
    mistake: 'Expecting per-@KafkaHandler @RetryableTopic isolation for free.',
    followUp: 'How do ambiguous type hierarchies fail at runtime?',
  },
  {
    id: 't11',
    level: 'Staff',
    question: 'Deserialization poison on a hot partition - annotation-level playbook?',
    short: 'ErrorHandlingDeserializer + classifier to DLT immediately; never long @RetryableTopic hops for serde failures.',
    deep: 'Without EHD the listener never sees the record and ops debugging is harder. Restore bytes in DLT for forensics; fix schema then replay.',
    code: '// value.deserializer = ErrorHandlingDeserializer\n// spring.deserializer.value.delegate.class = JsonDeserializer',
    mistake: 'Retrying deser failures with exponential hops for minutes.',
    followUp: 'Key vs value deser failure - header differences?',
  },
  {
    id: 't12',
    level: 'Staff',
    question: 'Batch listener partial failure - which annotations and exceptions?',
    short: 'Batch-enabled @KafkaListener, DefaultErrorHandler, throw BatchListenerFailedException for the failed index; not @RetryableTopic.',
    deep: 'Framework can commit prior records and redeliver/recover the failed slice depending on configuration. Conversion errors need explicit checks.',
    code: 'public void batch(List<Order> orders) {\n  for (int i = 0; i < orders.size(); i++) {\n    try { apply(orders.get(i)); }\n    catch (RuntimeException ex) { throw new BatchListenerFailedException("fail", i); }\n  }\n}',
    mistake: 'Putting @RetryableTopic on List<Order> listeners.',
    followUp: 'How do you avoid committing successful siblings twice?',
  },
  {
    id: 't13',
    level: 'Staff',
    question: 'Concurrency on @KafkaListener vs partition count - Staff sizing rules?',
    short: 'Useful concurrency is capped by assigned partitions; extra threads idle. Scale partitions or instances intentionally, not both blindly.',
    deep: 'Retry/DLT containers have their own concurrency knobs under @RetryableTopic. Over-concurrency amplifies DB pool pressure on poison storms.',
    code: '@KafkaListener(topics = "orders.v1", groupId = "order-service", concurrency = "6")',
    mistake: 'Setting concurrency=32 on a 6-partition topic "for throughput."',
    followUp: 'How do you watch rebalance storms after raising concurrency?',
  },
  {
    id: 't14',
    level: 'Staff',
    question: 'How do @KafkaListener properties= interact with global ConsumerFactory config?',
    short: 'Listener properties override/add consumer configs for that container - powerful and dangerous if teams sprinkle max.poll.records ad hoc.',
    deep: 'Staff standardizes factories (json/avro/batch/txn) and keeps per-listener properties rare and reviewed.',
    code: '@KafkaListener(topics = "orders.v1", properties = {\n  "max.poll.records:50",\n  "spring.json.value.default.type:com.acme.Order"\n})',
    mistake: 'Copy-pasting conflicting properties across dozens of listeners.',
    followUp: 'Where should isolation.level=read_committed live?',
  },
  {
    id: 't15',
    level: 'Staff',
    question: 'DLT publish succeeds but process crashes before commit - Staff mitigation?',
    short: 'At-least-once: redelivery may publish a duplicate DLT row. Dedupe DLT sink by original topic, partition, offset headers.',
    deep: 'Transactional commitRecovered paths shrink the window for transactional pipelines. Never claim exactly-once DLT without proof.',
    code: '// UNIQUE(original_topic, original_partition, original_offset) on DLT store',
    mistake: 'Treating DLT as exactly-once durable archive by default.',
    followUp: 'Opposite failure: commit without DLT - how do you detect it?',
  },
  {
    id: 't16',
    level: 'Staff',
    question: 'When should autoStartDltHandler be false?',
    short: 'During incidents when DLT flood would melt the sink, or when a separate ops job owns controlled drain windows.',
    deep: 'Lag grows until started - alert on that lag. Pair with runbooks so "paused DLT" is not forgotten.',
    code: '@RetryableTopic(autoStartDltHandler = "false")',
    mistake: 'Leaving DLT consumers stopped indefinitely with no alert.',
    followUp: 'How do you safely start DLT drain after a schema fix?',
  },
  {
    id: 't17',
    level: 'Staff',
    question: 'Compare DeadLetterPublishingRecoverer DLT vs @RetryableTopic DLT.',
    short: 'DLP is typically wired through DefaultErrorHandler/AfterRollbackProcessor. @RetryableTopic builds hop topology plus optional @DltHandler.',
    deep: 'Both publish to topics; neither is a broker feature. Choose based on blocking vs non-blocking retry needs and batch support.',
    code: '// factory.setCommonErrorHandler(new DefaultErrorHandler(new DeadLetterPublishingRecoverer(template), backoff));',
    mistake: 'Mixing both stacks on one listener without understanding double DLT risk.',
    followUp: 'Can both write to the same -dlt topic safely?',
  },
  {
    id: 't18',
    level: 'Staff',
    question: 'How do you test @RetryableTopic behavior in CI without a full cluster nightmare?',
    short: 'Use EmbeddedKafka or Testcontainers, assert hop topic messages and DLT headers, and keep attempts small for speed.',
    deep: 'Test include/exclude classifiers and dltStrategy failure modes explicitly. Flaky sleep-based tests are a smell - assert topic contents.',
    code: '@SpringBootTest\n@EmbeddedKafka(topics = {"orders.v1", "orders.v1-dlt"})\nclass RetryTopicIT { ... }',
    mistake: 'Only unit-testing the service method and calling annotations "covered."',
    followUp: 'How do you assert non-blocking: main offset moved while hop pending?',
  },
  {
    id: 't19',
    level: 'Staff',
    question: 'Multi-listener app: shared groupId mistakes with annotations?',
    short: 'Two @KafkaListener methods with the same groupId on different topics are fine; same group on the same topic splits partitions - often accidental.',
    deep: 'Anonymous groups and idIsGroup surprises cause duplicate processing or empty lag. Stable explicit groupId is a Staff gate.',
    code: '@KafkaListener(id = "order-main", topics = "orders.v1", groupId = "order-service")',
    mistake: 'Relying on generated group ids across rolling deploys.',
    followUp: 'When is intentional cooperative split across methods justified?',
  },
  {
    id: 't20',
    level: 'Staff',
    question: '@SendTo + failing downstream consumer - is the source listener "successful"?',
    short: 'Yes for the source container once @SendTo produce succeeded; downstream lag is a separate consumer problem.',
    deep: 'Do not conflate produce ack with downstream processing. End-to-end needs consumer metrics and possibly outbox/reply correlation ids.',
    code: '@SendTo("orders.processed.v1")\npublic ProcessedOrder process(Order o) { return enrich(o); }',
    mistake: 'Assuming @SendTo implies downstream processing completed.',
    followUp: 'How do you correlate request/reply across @SendTo?',
  },
  {
    id: 't21',
    level: 'Staff',
    question: 'How does @Backoff random=true change production incident shapes?',
    short: 'Jitter spreads retry-topic load when many partitions fail together on a shared dependency outage.',
    deep: 'Without jitter, hop consumers wake in lockstep and re-stampede the dependency. Still require CB/bulkheads around sync side effects.',
    code: '@Backoff(delay = 1000, multiplier = 2.0, maxDelay = 30_000, random = true)',
    mistake: 'Using huge multiplier without maxDelay and calling it "safe backoff."',
    followUp: 'Where else should jitter live besides @Backoff?',
  },
  {
    id: 't22',
    level: 'Staff',
    question: 'Staff ADR: annotations vs programmatic Kafka APIs for a complex worker?',
    short: 'Prefer annotations for standard consume/retry/DLT; drop to MessageListener/KafkaTemplate APIs when AckMode, batch, or multi-write control exceeds annotation clarity.',
    deep: 'Annotations are Spring configuration sugar over clients. Clarity and testability beat annotation cleverness in money paths.',
    code: '// Explicit: containerFactory + DefaultErrorHandler + KafkaTemplate outbox relay',
    mistake: 'Stacking every Kafka annotation on one method to avoid writing config beans.',
    followUp: 'What is the escape hatch from @KafkaListener to a custom MessageListener?',
  },
  {
    id: 't23',
    level: 'Staff',
    question: 'What breaks if retry/DLT topics have fewer partitions than the source?',
    short: 'Default same-partition publish can fail or concentrate load; partition affinity and ordering assumptions collapse.',
    deep: 'Match partition counts for key order context. Hot keys still hotspot even with matched counts.',
    code: '// source partitions=12 -> retry/DLT partitions=12',
    mistake: 'Auto-creating hop topics with partition count 1 "temporarily."',
    followUp: 'What resolver strategy uses partition -1 and what do you lose?',
  },
  {
    id: 't24',
    level: 'Staff',
    question: 'How do you explain annotations vs broker to a junior on your team?',
    short: 'Annotations configure the Spring app; the broker stores bytes and serves clients. Retry/DLT are application patterns using ordinary topics.',
    deep: 'If it is not a Consumer/Producer/Admin API call, the broker does not "do" it. This prevents magical thinking in incident reviews.',
    code: 'Spring annotation -> Spring container -> Kafka client -> broker',
    mistake: 'Documenting "Kafka retries via @RetryableTopic" as a broker feature.',
    followUp: 'Where do you put broker retention decisions for DLT topics?',
  },
  {
    id: 't25',
    level: 'Staff',
    question: 'exceptionBasedDltRouting - when is it worth the complexity?',
    short: 'When different terminal failures need different DLT topics for ownership (fraud vs validation vs infra), not for vanity taxonomy.',
    deep: 'Added in Spring Kafka 3.2+. Requires clear ops routing and dashboards per DLT. Prefer fewer topics unless ownership demands split.',
    code: '@RetryableTopic(exceptionBasedDltRouting = { ... }) // 3.2+',
    mistake: 'Creating a DLT per exception class without an owning team.',
    followUp: 'How do you prevent DLT topic explosion over a year?',
  },
];

export const PRINCIPAL_Q: InterviewQ[] = [
  {
    id: 'p01',
    level: 'Principal',
    question: 'Set org standards for Spring Kafka annotations across 40 services.',
    short: 'Standard factories (record/batch/txn), DEH vs retry-topic decision tree, no autoCreateTopics in prod, named TMs, and golden interview cards for offsets/DLT.',
    deep: 'Principal bar: platform libraries encode defaults; service teams only choose topic names, classifiers, and idempotency. Ban annotation folklore in READMEs without links to the hub page.',
    code: '// Platform starter: kafkaListenerContainerFactory, kafkaTransactionManager, ErrorHandlingDeserializer',
    mistake: 'Letting every squad invent AckMode and DLT naming.',
    followUp: 'How do you migrate legacy listeners without a big-bang freeze?',
  },
  {
    id: 'p02',
    level: 'Principal',
    question: 'When do you forbid @RetryableTopic platform-wide?',
    short: 'On batch pipelines, strict in-partition financial sequences, or clusters without capacity to operate hop topic sprawl.',
    deep: 'Offer DEH+DLP as the default paved road; allow retry topics by exception with ADR. Measure hop lag and reorder incidents before expanding.',
    code: '// Paved road: DefaultErrorHandler + DeadLetterPublishingRecoverer\n// Exception: @RetryableTopic with platform review',
    mistake: 'Mandating @RetryableTopic as the only "modern" error strategy.',
    followUp: 'What SLOs prove a service may opt into hop retries?',
  },
  {
    id: 'p03',
    level: 'Principal',
    question: 'Architect end-to-end money movement with Kafka listeners - where do annotations stop?',
    short: 'Annotations stop at consume/retry/produce plumbing. Idempotent ledger, outbox, and reconciliation own correctness.',
    deep: 'Principal answers separate transport semantics from business exactly-once. @Transactional Kafka EOS is not a bank settlement guarantee.',
    code: '// inbox UNIQUE(event_id) + ledger apply + outbox + reconcile job',
    mistake: 'Selling "annotation EOS" to risk/compliance as settlement EOS.',
    followUp: 'What audit evidence do you keep for replay from DLT?',
  },
  {
    id: 'p04',
    level: 'Principal',
    question: 'Design multi-region consumers with @KafkaListener - what changes?',
    short: 'Group ids, lag SLOs, and failover are regional topology problems; annotations stay local to each JVM and do not span regions.',
    deep: 'Active-active needs careful offset ownership and idempotency. Retry topics multiply regional topic costs. Prefer regional fail-over runbooks over clever annotation tricks.',
    code: '// region-a group order-service-a / region-b group order-service-b (active-passive)',
    mistake: 'Assuming one @KafkaListener group spans two regions safely by default.',
    followUp: 'How do DLT replay rights work across regions?',
  },
  {
    id: 'p05',
    level: 'Principal',
    question: 'Principal review: @SendTo inside Kafka TX for a fan-out of five topics.',
    short: 'Reject. @SendTo is a single-return reply pattern; multi-topic fan-out needs explicit produces, outbox, and per-destination failure policy.',
    deep: 'One TX with many produces increases fence/timeout risk and obscures which destination failed. Prefer staged outbox or choreography with clear ownership.',
    code: '// outbox rows per destination -> relay workers with independent DLT',
    mistake: 'Stretching @SendTo into an implicit orchestration bus.',
    followUp: 'When is a single transactional produce pair still acceptable?',
  },
  {
    id: 'p06',
    level: 'Principal',
    question: 'How should platform treat DLT publish failure vs source commit?',
    short: 'Never commit past a failed terminal recoverer publish; stuck partition beats silent loss for money and compliance streams.',
    deep: 'Page on recoverer failures. Provide quarantine tooling. Document the rare non-money streams that may skip-with-metric under explicit ADR.',
    code: '// recoverer throws -> seek/retry; alert: dlt_publish_failures_total',
    mistake: 'Global "drop on DLT failure" to protect lag dashboards.',
    followUp: 'What customer communication standard applies during stuck partitions?',
  },
  {
    id: 'p07',
    level: 'Principal',
    question: 'Unify DefaultErrorHandler and @RetryableTopic guidance for the org?',
    short: 'Publish a decision tree: duration of outage, order sensitivity, batch vs record, ops maturity - then encode defaults in starters.',
    deep: 'Train Staff+ on offset semantics for both paths. Eliminate mixed stacks on one listener. Link to kafka-dlq hub for recoverer deep dives.',
    code: '// decision: blip+order -> DEH; long outage+reorder OK -> @RetryableTopic; batch -> DEH only',
    mistake: 'Two "standard" error handlers fighting in the same container factory.',
    followUp: 'How do you detect mixed-stack misconfiguration in CI?',
  },
  {
    id: 'p08',
    level: 'Principal',
    question: 'What is your stance on @DltHandler as business workflow?',
    short: 'Forbid. DLT handlers are ops sinks: persist, alert, quarantine - not secondary happy-path processors.',
    deep: 'Business retries belong on versioned main/retry topics with product ownership. DLT-as-workflow creates untestable shadow products.',
    code: '@DltHandler\npublic void onDlt(Order o, ConsumerRecord<?, ?> r) { ops.persistAndAlert(r); }',
    mistake: 'Shipping features that only run when messages are dead-lettered.',
    followUp: 'How do product teams request controlled replay APIs?',
  },
  {
    id: 'p09',
    level: 'Principal',
    question: 'Principal-level AckMode policy for the company?',
    short: 'Default BATCH/RECORD via factory for most apps; MANUAL only with reviewed acknowledge discipline; transactional listeners use Kafka TM commit path.',
    deep: 'Ban ack-before-side-effects. Document MANUAL_IMMEDIATE trade-offs. Make AckMode visible in actuator/metadata for incident response.',
    code: '// factory.getContainerProperties().setAckMode(ContainerProperties.AckMode.RECORD);',
    mistake: 'Per-listener AckMode chaos without a platform default.',
    followUp: 'How do you migrate MANUAL listeners safely?',
  },
  {
    id: 'p10',
    level: 'Principal',
    question: 'How do annotations interact with mesh retries and gateway timeouts?',
    short: 'Pick one retry owner for money paths. Annotation hop retries plus mesh retries amplify load; document the onion.',
    deep: 'Principal ADR: mesh retries off for settlement APIs; app uses classifier + hop/DEH; timeouts decrease inward. Annotations do not see mesh retries.',
    code: '// ADR: Istio retries=0 for /settle; @RetryableTopic attempts=4 for Kafka side effects only',
    mistake: 'Ignoring mesh/app double retry in capacity plans.',
    followUp: 'Where do you enforce the single-owner rule in CI?',
  },
  {
    id: 'p11',
    level: 'Principal',
    question: 'Scale to thousands of @KafkaListener methods - what breaks first?',
    short: 'Thread/connection pools, rebalance time, metric cardinality, and human cognitive load - not the annotation parser.',
    deep: 'Consolidate factories, bound concurrency, standardize group naming, and split deployables by blast radius. Annotation count is a smell for modularization.',
    code: '// Prefer fewer deployables with clear topic ownership over 500 listeners in one JVM',
    mistake: 'Adding concurrency globally to "fix" listener sprawl.',
    followUp: 'How do you attribute lag to the right listener id in a shared JVM?',
  },
  {
    id: 'p12',
    level: 'Principal',
    question: 'Security review: what can Spring Kafka annotations accidentally expose?',
    short: 'Over-broad topicPattern subscriptions, auto-created topics without ACLs, and DLT payloads with PII lacking retention/redaction policy.',
    deep: 'Annotations do not grant broker ACLs - ops must. Principal requires topic ACLs, encrypted PII strategy, and DLT access controls separate from main consumers.',
    code: '// Avoid: topicPattern = ".*" in shared clusters',
    mistake: 'Treating DLT as "already failed so less sensitive."',
    followUp: 'Who can replay DLT in production under your RBAC?',
  },
  {
    id: 'p13',
    level: 'Principal',
    question: 'Evolve from annotation-centric consumers to Kafka Streams - decision criteria?',
    short: 'Move when you need stateful processing, joins, and windowing as first-class; keep @KafkaListener for simple side-effect workers.',
    deep: 'Do not rewrite for fashion. Streams changes ownership of processing and failure semantics; annotations remain for I/O adapters at edges.',
    code: '// Edge: @KafkaListener -> command\n// Core: Kafka Streams topology for joins/aggregations',
    mistake: 'Rewriting stable listeners into Streams without a state store need.',
    followUp: 'How do DLT strategies differ at the Streams boundary?',
  },
  {
    id: 'p14',
    level: 'Principal',
    question: 'How do you govern @Transactional Kafka usage across polyglot neighbors?',
    short: 'Require read_committed for transactional topics, document producer ids, and never assume non-Java consumers understand Spring annotations.',
    deep: 'Contracts are topic + headers + idempotency keys. Annotations are an implementation detail of the Java service.',
    code: '// ConsumerConfig.ISOLATION_LEVEL_CONFIG = read_committed',
    mistake: 'Publishing "use @Transactional" as a cross-language contract.',
    followUp: 'What happens to lag dashboards with transactional produce delays?',
  },
  {
    id: 'p15',
    level: 'Principal',
    question: 'Incident: DLT handler down, ALWAYS_RETRY_ON_ERROR, lag exploding - Principal call?',
    short: 'Pause DLT container or disable auto-start, stabilize sink, switch strategy toward FAIL_ON_ERROR/quarantine, then controlled drain.',
    deep: 'Protect the cluster from infinite poison loops. Communicate customer impact from main vs DLT separately. Postmortem the missing alerts on DLT handler failures.',
    code: '@RetryableTopic(dltStrategy = DltStrategy.FAIL_ON_ERROR, autoStartDltHandler = "false")',
    mistake: 'Scaling DLT concurrency to hammer a broken sink harder.',
    followUp: 'What permanent platform guardrail prevents recurrence?',
  },
  {
    id: 'p16',
    level: 'Principal',
    question: 'Should platform auto-provision retry/DLT topics from @RetryableTopic metadata?',
    short: 'Prefer GitOps from declared topic catalogs over runtime autoCreateTopics; annotations may generate desired-state hints for the catalog PR.',
    deep: 'Runtime create races ACL and partition mistakes. Principal systems treat topics as products with owners, quotas, and retention - not side effects of a deploy.',
    code: '// autoCreateTopics = "false" + topic CRD/Terraform from service manifest',
    mistake: 'Equating Spring auto-create with production topic management.',
    followUp: 'How do you block merges that add @RetryableTopic without catalog entries?',
  },
  {
    id: 'p17',
    level: 'Principal',
    question: 'Principal interview prompt: prove annotations are not the broker.',
    short: 'Draw Spring container -> client -> broker; show @RetryableTopic as produce+consume on ordinary topics; show broker configs living elsewhere.',
    deep: 'Then ask offset commit on listener throw, DLT publish failure, and DB+Kafka atomicity. Candidates who mythologize the broker fail the bar.',
    code: 'MENTAL: Annotation -> Spring -> KafkaClient -> Broker',
    mistake: 'Accepting "Kafka retries the message because of the annotation" as sufficient.',
    followUp: 'What follow-up question separates Staff from Principal here?',
  },
  {
    id: 'p18',
    level: 'Principal',
    question: 'Cost and complexity of hop retries at org scale?',
    short: 'Topic count, storage, consumer groups, rebalances, and cognitive load dominate before CPU. Price hop retries explicitly.',
    deep: 'sameIntervalTopicReuseStrategy and suffix strategy reduce sprawl. Still budget for DLT growth and replay tooling - annotations make it easy to create expensive topologies.',
    code: '// Prefer SINGLE_TOPIC reuse for fixed backoff intervals (3.2+)',
    mistake: 'Ignoring Kafka storage/ops cost when rolling @RetryableTopic widely.',
    followUp: 'What FinOps signal triggers a retry-topology rethink?',
  },
  {
    id: 'p19',
    level: 'Principal',
    question: 'How do you align @KafkaHandler polymorphic topics with schema evolution?',
    short: 'Require stable type headers or subject strategies; ambiguous assignable handlers are a production footgun under schema drift.',
    deep: 'Principal prefers explicit event types per topic for money, and polymorphic handlers only for soft event buses with a mandatory default handler and metrics on unknown.',
    code: '@KafkaHandler(isDefault = true)\npublic void unknown(Object payload) { metrics.unknown(); }',
    mistake: 'Relying on Java type inventiveness as the long-term contract.',
    followUp: 'When do you split a polymorphic topic into versioned topics?',
  },
  {
    id: 'p20',
    level: 'Principal',
    question: 'Define the golden rules card for Spring Kafka annotations in one breath.',
    short: '@KafkaListener creates containers; @RetryableTopic forwards hops; @DltHandler consumes DLT only; @SendTo publishes returns; @Transactional needs the right TM; broker runs none of these.',
    deep: 'Offsets advance only on success paths you configured; DLT publish failure must not silently commit away; DB+Kafka atomicity is outbox/idempotency, not annotation magic; batch and @RetryableTopic do not mix.',
    code: '// PAGE_MEMORY from overview - teach it in every onboarding',
    mistake: 'Memorizing annotation names without offset/DLT/TM failure semantics.',
    followUp: 'Which two golden rules prevent the most production incidents?',
  },
];

export const ALL_Q: InterviewQ[] = [...SENIOR_Q, ...STAFF_Q, ...PRINCIPAL_Q];
