import type {TocItem} from './types';

export const SKA_TOC: TocItem[] = [
  {id: 'mental-model', label: '00. What is an annotation?'},
  {id: 'classification', label: '01. Classification matrix'},
  {id: 'enable-kafka', label: '02. @EnableKafka'},
  {id: 'kafka-listener', label: '03. @KafkaListener deep'},
  {id: 'listener-lifecycle', label: '04. Listener lifecycle'},
  {id: 'listener-offsets', label: '05. Offsets · AckMode'},
  {id: 'listener-concurrency', label: '06. Concurrency'},
  {id: 'multiple-listeners', label: '07. Multiple @KafkaListener'},
  {id: 'kafka-handler', label: '08. @KafkaHandler'},
  {id: 'kafka-listeners', label: '09. @KafkaListeners'},
  {id: 'retryable', label: '10. @RetryableTopic deep'},
  {id: 'retry-vs-deh', label: '11. vs DefaultErrorHandler'},
  {id: 'backoff', label: '12. @Backoff'},
  {id: 'dlt-handler', label: '13. @DltHandler'},
  {id: 'dlt-failure', label: '14. @DltHandler failure'},
  {id: 'send-to', label: '15. @SendTo'},
  {id: 'transactional', label: '16. @Transactional'},
  {id: 'txn-listener', label: '17. Tx + @KafkaListener'},
  {id: 'txn-db', label: '18. Tx + database'},
  {id: 'interaction', label: '19. Interaction matrix'},
  {id: 'exceptions', label: '20. Exception classification'},
  {id: 'deser', label: '21. Deserialization + annotations'},
  {id: 'batch', label: '22. Batch listeners'},
  {id: 'diagrams', label: '23. Lifecycle diagrams'},
  {id: 'antipatterns', label: '24. Anti-patterns'},
  {id: 'examples', label: '25. Production examples'},
  {id: 'misconceptions', label: '26. Misconceptions'},
  {id: 'decision-tree', label: '27. Decision tree'},
  {id: 'reference', label: '28. Reference table'},
  {id: 'golden', label: '29. Golden rule cards'},
  {id: 'interview', label: '30. Interview bank'},
  {id: 'dont-confuse', label: '31. Don\'t confuse these'},
];
