import type {InterviewQ} from './types';

export const BEGINNER: InterviewQ[] = [
  {
    id: 'b01',
    level: 'beginner',
    topic: 'Latency vs throughput',
    question: 'What is the difference between latency and throughput?',
    answer30s: 'Latency is time per request; throughput is requests completed per unit time. You can have high throughput with bad tails.',
    answer2m: 'Latency (p50/p95/p99) is the user-felt wait. Throughput (RPS/TPS) is capacity. Optimizing average latency while ignoring p99 still fails SLOs. Throughput rises until a bottleneck saturates; then latency climbs (queueing). Always report both with load context.',
  },
  {
    id: 'b02',
    level: 'beginner',
    topic: 'Percentiles',
    question: 'Why prefer p95/p99 over average latency?',
    answer30s: 'Averages hide outliers. Customers feel the tail; SLOs should use percentiles.',
    answer2m: 'One 10s request among many 50ms ones barely moves the mean but destroys UX and timeouts. Histograms/percentiles expose that. Also watch p999 for rare GC/lock events. Never tune only on avg in interviews or prod.',
  },
  {
    id: 'b03',
    level: 'beginner',
    topic: "Little's Law",
    question: "State Little's Law and give a concurrency example.",
    answer30s: 'L = λ × W. 1000 rps × 0.1s ≈ 100 in-flight requests.',
    answer2m: 'Concurrency (in-flight work) ≈ arrival rate × latency. Use it to size threads, DB connections, and bulkheads from P99×peak RPS, not vibes. If latency doubles at same RPS, needed concurrency doubles—pools explode.',
  },
  {
    id: 'b04',
    level: 'beginner',
    topic: 'Bottleneck',
    question: 'What is a performance bottleneck?',
    answer30s: 'The resource that limits end-to-end rate or latency—CPU, disk, lock, pool, or a slow dependency.',
    answer2m: 'USE method: Utilization, Saturation, Errors per resource. Fix the dominant wait first. Scaling other layers wastes money. Prove with metrics/traces/profiles before changing code.',
  },
  {
    id: 'b05',
    level: 'beginner',
    topic: 'Observability',
    question: 'Metrics vs logs vs traces—what is each for?',
    answer30s: 'Metrics: how bad/how often. Logs: what happened. Traces: where time went across services.',
    answer2m: 'Start with golden signals, jump to traces for waterfalls, use logs for errors/audit, profiles/dumps for CPU/heap/threads. Sampling can miss rare p99—correlate with metrics.',
  },
  {
    id: 'b06',
    level: 'beginner',
    topic: 'HTTP caching',
    question: 'Name one HTTP cache header that improves performance.',
    answer30s: 'Cache-Control / ETag / CDN caching for immutable assets and safe GETs.',
    answer2m: 'Immutable hashed static assets at CloudFront cut origin load. APIs need careful TTLs and authorization awareness. Conditional requests (ETag) save bandwidth when data unchanged.',
  },
  {
    id: 'b07',
    level: 'beginner',
    topic: 'DB indexes',
    question: 'How does an index speed up reads?',
    answer30s: 'It avoids full table scans by locating matching rows via a structured structure (e.g. B-tree).',
    answer2m: 'Indexes trade write cost and storage for read speed. Wrong/missing indexes dominate API latency. Always verify with EXPLAIN ANALYZE. Too many indexes hurt writes.',
  },
  {
    id: 'b08',
    level: 'beginner',
    topic: 'N+1',
    question: 'What is the N+1 query problem?',
    answer30s: 'One query loads N parents, then N more queries load children—latency scales with N.',
    answer2m: 'Common with JPA lazy loading. Fix with join fetch, entity graphs, or DTO queries. Detect via Hibernate stats or datasource proxy. Pagination still required for large graphs.',
  },
  {
    id: 'b09',
    level: 'beginner',
    topic: 'Connection pool',
    question: 'Why use a DB connection pool?',
    answer30s: 'Creating DB connections is expensive; pooling reuses them under concurrency.',
    answer2m: 'HikariCP keeps a bounded set of connections. Too small → wait timeouts; too large → DB saturation. Size with Little\'s Law and fleet limits (pods × pool ≤ max_connections).',
  },
  {
    id: 'b10',
    level: 'beginner',
    topic: 'Caching',
    question: 'What is cache-aside?',
    answer30s: 'App reads cache; on miss loads DB, then populates cache with TTL.',
    answer2m: 'Simple and common with Redis. Handle stampede (singleflight/lock), invalidation on writes, and never cache sensitive mutable money without versioning. Measure hit ratio.',
  },
  {
    id: 'b11',
    level: 'beginner',
    topic: 'GC',
    question: 'How can GC affect API latency?',
    answer30s: 'Stop-the-world or long pauses freeze threads → p99 spikes even if business logic is fine.',
    answer2m: 'High allocation increases GC work. Watch GC pause metrics and alloc rate. Fix churn first; tune heap/GC second. Heap dumps for leaks.',
  },
  {
    id: 'b12',
    level: 'beginner',
    topic: 'Timeouts',
    question: 'Why must every remote call have a timeout?',
    answer30s: 'Without timeouts, threads/connections hang forever and exhaust pools.',
    answer2m: 'Set connect+read timeouts shorter than caller budgets. Align gateway → service → client. Pair with circuit breakers. Infinite waits are silent outages.',
  },
  {
    id: 'b13',
    level: 'beginner',
    topic: 'Load testing',
    question: 'Load test vs stress test?',
    answer30s: 'Load validates expected peak; stress pushes past capacity to find break points.',
    answer2m: 'Also use spike (bursts), soak (leaks), capacity (max RPS at SLO). Match production traffic mix. Microbenchmarks are not capacity proof.',
  },
  {
    id: 'b14',
    level: 'beginner',
    topic: 'Vertical vs horizontal',
    question: 'Vertical vs horizontal scaling?',
    answer30s: 'Vertical: bigger machine. Horizontal: more instances behind a load balancer.',
    answer2m: 'Horizontal needs stateless apps and externalized state. Vertical hits hardware ceilings and blast radius. Fix algorithmic bottlenecks before either.',
  },
  {
    id: 'b15',
    level: 'beginner',
    topic: 'Sync vs async',
    question: 'When prefer async (Kafka) over sync HTTP?',
    answer30s: 'When the caller need not wait—fan-out, notifications, eventual workflows.',
    answer2m: 'Async improves user latency and isolates failures, at cost of consistency and ops (lag, DLQ). Sync for immediate invariants (auth, balance check) with tight timeouts.',
  },
  {
    id: 'b16',
    level: 'beginner',
    topic: 'Pagination',
    question: 'Why paginate list APIs?',
    answer30s: 'Bounds memory, CPU, and network per request; prevents OOM on large tables.',
    answer2m: 'Prefer keyset over huge OFFSET. Enforce max page size server-side. Returning findAll() is a production incident waiting to happen.',
  },
  {
    id: 'b17',
    level: 'beginner',
    topic: 'Serialization',
    question: 'How can JSON serialization hurt performance?',
    answer30s: 'CPU and allocations parsing/writing large object graphs dominate hot paths.',
    answer2m: 'Slim DTOs, avoid reflection-heavy paths where possible, compress, consider binary for internal RPC. Profile before rewriting formats.',
  },
  {
    id: 'b18',
    level: 'beginner',
    topic: 'Logging',
    question: 'Can logging cause high CPU?',
    answer30s: 'Yes—stringifying large objects or logging per-item in hot loops.',
    answer2m: 'Use parameterized logging, sampling, and structured fields. Debug logs left on in prod are a classic outage amplifier. Prefer traces for request forensics.',
  },
  {
    id: 'b19',
    level: 'beginner',
    topic: 'CDN',
    question: 'How does a CDN improve performance?',
    answer30s: 'Serves cached content at edge closer to users; cuts origin latency and load.',
    answer2m: 'Great for static assets and cacheable GETs. APIs need careful cache keys and auth. Measure origin offload %, not vanity hit ratios alone.',
  },
  {
    id: 'b20',
    level: 'beginner',
    topic: 'Thread dump',
    question: 'When do you take a thread dump?',
    answer30s: 'When requests hang, pools look full, or CPU is low but latency is high (waiting).',
    answer2m: 'Dumps show blocked/waiting stacks—often DB, locks, or remote calls. Pair with metrics. Prefer jcmd; be careful on huge heaps. Multiple dumps over time help.',
  },
  {
    id: 'b21',
    level: 'beginner',
    topic: 'Heap dump',
    question: 'When do you take a heap dump?',
    answer30s: 'Suspected memory leak or climbing heap toward OOM.',
    answer2m: 'Analyze retained sets (MAT). Dumps are large and pause the JVM—coordinate. Fix root cause; restart is only mitigation. Soak tests catch leaks.',
  },
  {
    id: 'b22',
    level: 'beginner',
    topic: 'Idempotency',
    question: 'Why does idempotency matter for performance under retries?',
    answer30s: 'Safe retries avoid duplicate side effects when timeouts trigger client retries.',
    answer2m: 'Without idempotency, retries cause double charges and extra load. Use Idempotency-Key + server dedup. One retry owner with jitter prevents storms.',
  },
  {
    id: 'b23',
    level: 'beginner',
    topic: 'Warmup',
    question: 'Why can first requests after deploy be slow?',
    answer30s: 'JIT warmup, cold caches, connection pool fill, class loading.',
    answer2m: 'Use readiness probes after warmup, pre-touch pools, cache priming for critical keys. Don\'t judge capacity from cold start alone.',
  },
  {
    id: 'b24',
    level: 'beginner',
    topic: 'Saturation',
    question: 'What does resource saturation look like?',
    answer30s: 'Queueing: pool pending, run queue, disk await, connection waits—latency rises nonlinearly.',
    answer2m: 'Utilization high is a warning; saturation (queues) is the user-visible failure. Alert on pending acquires, queue depth, and p99—not only CPU%.',
  },
  {
    id: 'b25',
    level: 'beginner',
    topic: 'Measure first',
    question: 'Why never optimize without measuring?',
    answer30s: 'Guessing wastes effort on non-bottlenecks and can worsen contention.',
    answer2m: 'Baseline → find bottleneck → change one thing → load test → prove p95/p99. Cargo-culting threads/indexes/cache is a senior anti-pattern.',
  },
];

export const INTERMEDIATE: InterviewQ[] = [
  {
    id: 'i01',
    level: 'intermediate',
    topic: 'Hikari sizing',
    question: 'How do you size HikariCP for a Spring service on K8s?',
    answer30s: 'From P99 latency × RPS (Little\'s Law), then cap pods×pool under DB max_connections.',
    answer2m: 'Measure hold time of connections. Prefer smaller pools with fast queries over huge pools. Watch pending/timeout metrics. Never copy maximumPoolSize=50 across 40 pods blindly.',
  },
  {
    id: 'i02',
    level: 'intermediate',
    topic: 'OSIV',
    question: 'How does Open Session In View hurt performance?',
    answer30s: 'Holds the persistence context/connection through view rendering and invites lazy N+1.',
    answer2m: 'Disable OSIV for APIs; fetch what you need in the service layer; return DTOs. OSIV hides design bugs until prod traffic exposes query storms.',
  },
  {
    id: 'i03',
    level: 'intermediate',
    topic: 'RestClient timeouts',
    question: 'How do you configure timeouts for RestClient/WebClient?',
    answer30s: 'Connect + read/response timeouts; align under parent budget; fail fast.',
    answer2m: 'Use connection pools with max lifetime for K8s pod IP churn. Circuit breaker on slow-call rate. Avoid RestTemplate defaults without timeouts in legacy code.',
  },
  {
    id: 'i04',
    level: 'intermediate',
    topic: 'Cache stampede',
    question: 'How do you prevent a cache stampede?',
    answer30s: 'Singleflight/lock per key, staggered TTLs, soft TTL refresh, rate-limit DB fallback.',
    answer2m: 'When a hot key expires, many pods hit DB. Use request coalescing, probabilistic early refresh, and bulkheads. Monitor hit ratio and DB QPS together.',
  },
  {
    id: 'i05',
    level: 'intermediate',
    topic: 'EXPLAIN',
    question: 'What do you look for in EXPLAIN ANALYZE?',
    answer30s: 'Seq scans on large tables, bad join order, high rows removed by filter, sort/hash spills.',
    answer2m: 'Compare estimated vs actual rows (stats). Check index usage and I/O. Fix query/index; re-run under realistic data. Don\'t index blindly from one EXPLAIN.',
  },
  {
    id: 'i06',
    level: 'intermediate',
    topic: 'Tomcat threads',
    question: 'How do platform threads relate to DB pool size?',
    answer30s: 'Each blocked request may hold a Tomcat thread and often a DB connection—pools must be coherent.',
    answer2m: 'If maxThreads ≫ DB pool, requests wait on Hikari. If both huge, DB dies. Size from blocking profile. Virtual threads change thread count but not DB capacity.',
  },
  {
    id: 'i07',
    level: 'intermediate',
    topic: 'Kafka batching',
    question: 'How do producer batching settings affect throughput?',
    answer30s: 'linger.ms + batch.size amortize network; higher throughput, slightly higher latency.',
    answer2m: 'acks, compression, and idempotence interact. Measure end-to-end. Consumers should also batch side effects. Sync flush-per-message kills throughput.',
  },
  {
    id: 'i08',
    level: 'intermediate',
    topic: 'Consumer lag',
    question: 'Lag is high—what do you check first?',
    answer30s: 'Produce vs consume rate, processing time per record, rebalances, poison messages.',
    answer2m: 'More consumers than partitions won\'t help. Profile listener for sync DB/HTTP. Check GC and session timeouts causing rebalance storms. DLQ poison records.',
  },
  {
    id: 'i09',
    level: 'intermediate',
    topic: 'G1 basics',
    question: 'What GC signals indicate allocation pressure?',
    answer30s: 'High alloc rate, rising GC overhead/pause p99, frequent young collections.',
    answer2m: 'Cut object churn before huge heap increases. Use JFR allocation samples. Humongous objects are special pain. Container-aware heap sizing matters on K8s.',
  },
  {
    id: 'i10',
    level: 'intermediate',
    topic: 'Micrometer',
    question: 'Which Micrometer meters matter for API performance?',
    answer30s: 'http.server.requests timers, Hikari gauges, JVM GC/memory, executor metrics, client timers.',
    answer2m: 'RED/USE golden signals. Histograms for percentiles. Cardinality discipline on tags. Alert on pending acquires and p99, not only error rate.',
  },
  {
    id: 'i11',
    level: 'intermediate',
    topic: 'Bulkhead',
    question: 'What is a bulkhead and why use it?',
    answer30s: 'Isolate thread/semaphore pools per dependency so one slow dep cannot consume all capacity.',
    answer2m: 'Resilience4j bulkhead/semaphore. Size each with Little\'s Law. Pair with timeouts and CB. Shared giant pools create head-of-line blocking.',
  },
  {
    id: 'i12',
    level: 'intermediate',
    topic: 'Retry storms',
    question: 'How do retries worsen performance incidents?',
    answer30s: 'They multiply traffic to a sick dependency, exhausting pools faster.',
    answer2m: 'One retry owner, exponential backoff with jitter, idempotency, fail-fast CB. Nested gateway+client+SDK retries are a classic outage amplifier.',
  },
  {
    id: 'i13',
    level: 'intermediate',
    topic: 'Pagination keyset',
    question: 'Why is keyset pagination faster than large OFFSET?',
    answer30s: 'OFFSET scans/skips many rows; keyset continues from last seen key.',
    answer2m: 'Critical for deep pages. Needs stable sort key/index. Total counts are expensive—avoid on hot paths.',
  },
  {
    id: 'i14',
    level: 'intermediate',
    topic: 'JSON vs binary',
    question: 'When switch from JSON to a binary protocol?',
    answer30s: 'When CPU/alloc of encode/decode dominates and schemas are controlled (internal RPC/events).',
    answer2m: 'Protobuf/Avro with registry. Public APIs often stay JSON. Measure first—network may dominate over CPU for small payloads.',
  },
  {
    id: 'i15',
    level: 'intermediate',
    topic: 'Connection keep-alive',
    question: 'Why does HTTP keep-alive / pooling matter?',
    answer30s: 'Avoids TCP/TLS handshake per request—huge win for chatty services.',
    answer2m: 'Configure pool size, idle eviction, and max lifetime for LB/pod changes. HTTP/2 multiplexing differs from HTTP/1.1 pool math.',
  },
  {
    id: 'i16',
    level: 'intermediate',
    topic: 'Read replicas',
    question: 'How do read replicas help and hurt performance?',
    answer30s: 'Offload read QPS; introduce replication lag and stale reads.',
    answer2m: 'Route read-after-write to primary when needed. Lag under load can confuse users. Don\'t put analytics-heavy queries on primary.',
  },
  {
    id: 'i17',
    level: 'intermediate',
    topic: 'Async logging',
    question: 'Does async logging fix logging performance?',
    answer30s: 'It helps disk waits but still costs CPU for formatting; queues can drop or block.',
    answer2m: 'Reduce log volume first. Bound async appenders. Never log huge payloads. Correlate with traces using ids instead of dumping bodies.',
  },
  {
    id: 'i18',
    level: 'intermediate',
    topic: 'Index write cost',
    question: 'How do indexes slow writes?',
    answer30s: 'Each write updates index structures—CPU, I/O, and storage.',
    answer2m: 'High-churn tables need fewer, well-chosen indexes. Partial/covering indexes help. Measure insert p99 after adding indexes.',
  },
  {
    id: 'i19',
    level: 'intermediate',
    topic: 'Circuit breaker',
    question: 'How does a circuit breaker improve system performance under failure?',
    answer30s: 'Fails fast instead of waiting timeouts—frees threads and pools.',
    answer2m: 'Open on error/slow-call rate; half-open probes. Not a substitute for timeouts. Fallbacks must be cheap. Mis-tuned CB flaps and hurts availability.',
  },
  {
    id: 'i20',
    level: 'intermediate',
    topic: 'Virtual threads intro',
    question: 'Do virtual threads automatically make apps faster?',
    answer30s: 'No—they cheapen blocking concurrency but DB/CPU limits remain.',
    answer2m: 'Great for many waiting I/O tasks. Still need timeouts, pooling for scarce resources, and avoid pinning. Throughput ≠ unlimited.',
  },
  {
    id: 'i21',
    level: 'intermediate',
    topic: 'ALB 504',
    question: 'API returns 504—where do you look?',
    answer30s: 'Compare target processing time vs ALB idle timeout; traces for backend slowness.',
    answer2m: '504 is often backend exceeding timeout, not ALB "being slow". Fix latency or budgets. Check slow deps and pool waits.',
  },
  {
    id: 'i22',
    level: 'intermediate',
    topic: 'Redis latency',
    question: 'Redis is slow—what checks?',
    answer30s: 'Slowlog, CPU, evictions, network, large keys, hot keys.',
    answer2m: 'Avoid KEYS, huge MGET, big values. Connection pool sizing. Treat Redis as soft dependency with fallbacks when appropriate.',
  },
  {
    id: 'i23',
    level: 'intermediate',
    topic: 'JPA flush',
    question: 'How can dirty flushing surprise you in a transaction?',
    answer30s: 'Auto-flush before queries can emit unexpected UPDATEs/INSERTs mid-request.',
    answer2m: 'Long transactions accumulate dirty state and locks. Keep transactions short; understand flush modes; batch writes intentionally.',
  },
  {
    id: 'i24',
    level: 'intermediate',
    topic: 'Payload compression',
    question: 'When enable gzip/br compression?',
    answer30s: 'Large text JSON over WAN when CPU cost < bandwidth/latency savings.',
    answer2m: 'At CDN/edge often best. Double compression wastes CPU. For tiny payloads overhead can lose. Measure.',
  },
  {
    id: 'i25',
    level: 'intermediate',
    topic: 'Pool leak',
    question: 'Symptoms of a DB connection leak?',
    answer30s: 'active connections climb to max; pending grows; traffic still modest.',
    answer2m: 'Thread dump often shows waiters; DB sessions idle in transaction. Fix try-with-resources / transaction boundaries. LeakDetectionThreshold in Hikari helps.',
  },
  {
    id: 'i26',
    level: 'intermediate',
    topic: 'Hot partition',
    question: 'How does a Kafka hot partition hurt performance?',
    answer30s: 'One partition/consumer bottleneck; lag skew; overall SLO fails.',
    answer2m: 'Fix keying strategy, increase partitions carefully, or split workloads. Scaling consumers cannot exceed partition count.',
  },
  {
    id: 'i27',
    level: 'intermediate',
    topic: 'Soak test',
    question: 'What failures only soak tests catch?',
    answer30s: 'Memory leaks, FD growth, disk fill, GC drift, connection churn bugs.',
    answer2m: 'Run hours at realistic load with heap/FD/latency charts. Restart "healing" is a red flag. Gate releases on soak for stateful/cache-heavy services.',
  },
  {
    id: 'i28',
    level: 'intermediate',
    topic: 'DTO mapping',
    question: 'Why can MapStruct/manual mapping beat naive reflection mappers?',
    answer30s: 'Less runtime reflection and alloc on hot paths.',
    answer2m: 'Still measure—DB often dominates. Avoid mapping giant graphs. Prefer query-level DTO projections when possible.',
  },
  {
    id: 'i29',
    level: 'intermediate',
    topic: 'Feature flags',
    question: 'How do flags help performance incidents?',
    answer30s: 'Kill-switch expensive paths without full rollback; canary risky optimizations.',
    answer2m: 'Flag OFF bad query path, new cache, or remote call. Keep flags read-cheap (local cache). Don\'t remote-call flag service on every request without caching.',
  },
  {
    id: 'i30',
    level: 'intermediate',
    topic: 'Cardinality',
    question: 'How does metric cardinality hurt observability performance?',
    answer30s: 'High-cardinality tags explode time series → slow queries, costly TSDB, missing alerts.',
    answer2m: 'Never tag userId on every metric. Use logs/traces for high-card data. Bound label sets. Observability overload is itself an incident.',
  },
];

export const SENIOR: InterviewQ[] = [
  {
    id: 's01',
    level: 'senior',
    topic: 'End-to-end budget',
    question: 'How do you set a latency budget across CloudFront→APIGW→ALB→Spring→DB?',
    answer30s: 'Allocate per-hop budgets that sum under SLO with headroom; enforce timeouts downward.',
    answer2m: 'Example: 300ms SLO → edge 20, GW 30, app 150, DB 80, cushion 20. Each hop times out shorter than parent. Traces validate. Don\'t give every layer the full SLO.',
    deepDive: 'Publish budget table in ADR; alert when a hop eats >X% of budget.',
    mistake: 'Setting all timeouts equal to the client SLO.',
  },
  {
    id: 's02',
    level: 'senior',
    topic: 'P99 forensics',
    question: 'p50 is fine, p99 is 2s—how do you debug?',
    answer30s: 'Inspect slow-trace samples, GC pauses, cache misses, lock/pool waits, and multimodal histograms.',
    answer2m: 'Average health means nothing. Look for cliffs at timeout values, GC correlation, cold-key patterns, and single-instance skew. Fix tails deliberately.',
    deepDive: 'Heatmaps beat single-number dashboards for multimodal latency.',
    mistake: 'Scaling replicas because average looks busy.',
  },
  {
    id: 's03',
    level: 'senior',
    topic: 'Transaction boundaries',
    question: 'Why is a remote HTTP call inside @Transactional a performance bug?',
    answer30s: 'Holds DB connections/locks for network RTT → pool exhaustion under load.',
    answer2m: 'Keep transactions short and local. Outbox pattern for reliable messaging after commit. This single anti-pattern explains many Hikari incidents.',
    mistake: 'Raising pool size to "absorb" the hold time.',
  },
  {
    id: 's04',
    level: 'senior',
    topic: 'Capacity math',
    question: 'Walk through capacity planning for 5k rps at p99=100ms.',
    answer30s: 'In-flight ≈ 5000×0.1=500; size threads/connections/pods with headroom and failure domains.',
    answer2m: 'Per dependency bulkhead separately. Include retry amplification. Validate with load test, not spreadsheet alone. Plan AZ loss (N-1).',
    deepDive: 'Show fleet DB connection budget spreadsheet.',
  },
  {
    id: 's05',
    level: 'senior',
    topic: 'Hibernate batching',
    question: 'How do you speed up bulk JPA writes?',
    answer30s: 'jdbc batching, order_inserts/updates, avoid identity flush traps, clear persistence context.',
    answer2m: 'For huge volumes prefer COPY/bulk SQL or staging tables. Measure. Don\'t keep 100k entities managed.',
    mistake: 'Calling save() in a loop without batch config and expecting miracles.',
  },
  {
    id: 's06',
    level: 'senior',
    topic: 'Cross-AZ cost',
    question: 'How does multi-AZ placement create latency?',
    answer30s: 'Chatty app↔DB/Redis across AZs adds RTT and data transfer cost.',
    answer2m: 'Co-locate chatty tiers; reduce chattiness (batch); accept cross-AZ for HA of coarse calls. Measure with AZ-aware traces.',
    mistake: 'Blaming Spring when topology adds 2–5ms × N queries.',
  },
  {
    id: 's07',
    level: 'senior',
    topic: 'Load shedding',
    question: 'Design load shedding for a payment API under spike.',
    answer30s: 'Admit limited concurrency; return 503 with Retry-After for excess; protect critical paths.',
    answer2m: 'Shed cheap at edge when possible. Prefer fail-fast over timed-out hangs. Combine with CB and queue bounds. Idempotent clients.',
    deepDive: 'Separate interactive vs batch admission classes.',
  },
  {
    id: 's08',
    level: 'senior',
    topic: 'Profile-guided fix',
    question: 'CPU 90%—how do you go from profile to fix confidently?',
    answer30s: 'Flame graph → hot frames → change → same-load A/B prove CPU and p99 drop.',
    answer2m: 'Distinguish app CPU vs GC vs kernel. Avoid premature micro-opts if SQL dominates wall time (use traces too). Ship with regression benchmark.',
    mistake: 'Rewriting streams to for-loops while DB is 95% of latency.',
  },
  {
    id: 's09',
    level: 'senior',
    topic: 'Cache consistency',
    question: 'How do you cache account data without serving stale money?',
    answer30s: 'Short TTL + versioned keys, write-invalidate, or don\'t cache strongly consistent balances.',
    answer2m: 'For money, prefer compute-on-read from primary or carefully versioned entries. Document consistency class per key. Stampede controls still apply.',
    mistake: 'Caching balances forever "for performance".',
  },
  {
    id: 's10',
    level: 'senior',
    topic: 'Kafka exactly-once vs perf',
    question: 'How do transactional/EOS settings trade against throughput?',
    answer30s: 'Stronger delivery guarantees add coordination overhead; use only where required.',
    answer2m: 'Idempotent producer is cheapish; full transactions cost more. Often idempotent consumer + DB unique constraints suffice. Measure lag under peak.',
  },
  {
    id: 's11',
    level: 'senior',
    topic: 'Pool vs VT',
    question: 'With Java 21 virtual threads, how do you rethink pooling?',
    answer30s: 'Don\'t pool virtual threads; still pool scarce resources (DB, HTTP connections) and bound concurrency.',
    answer2m: 'Unlimited VT can stampede DB. Use semaphores/bulkheads. Avoid pinning in synchronized rare cases. MVC+VT ≠ free throughput.',
    deepDive: 'Contrast platform thread Tomcat sizing vs VT+semaphore.',
  },
  {
    id: 's12',
    level: 'senior',
    topic: 'N+1 at scale',
    question: 'N+1 fixed with join fetch—p95 still high. Next?',
    answer30s: 'Check cartesian explosion, over-fetch, missing DB index, and serialization of fat graphs.',
    answer2m: 'DTO query with only needed fields; paginate; cover index; maybe denormalize read model. Verify EXPLAIN and payload sizes.',
    mistake: 'Assuming join fetch always wins.',
  },
  {
    id: 's13',
    level: 'senior',
    topic: 'GC tuning ethics',
    question: 'When is GC tuning appropriate vs a code smell escape hatch?',
    answer30s: 'After reducing allocation; tune to meet pause SLO. Tuning to hide leaks is wrong.',
    answer2m: 'Set container-aware heap, pick collector for latency vs throughput goals, keep GC logs. Prove with JFR under load. Bigger heap can worsen pauses.',
  },
  {
    id: 's14',
    level: 'senior',
    topic: 'Multi-tenant fair use',
    question: 'One noisy tenant kills p99 for all—mitigations?',
    answer30s: 'Per-tenant rate limits, bulkheads, quotas, and fair scheduling at gateway.',
    answer2m: 'Isolate heavy tenants; cache per-tenant hot data carefully; backpressure. Measure tenant-tagged latency without exploding cardinality (approx top-K).',
  },
  {
    id: 's15',
    level: 'senior',
    topic: 'Blue/green perf',
    question: 'How can a deploy create a performance regression undetected by unit tests?',
    answer30s: 'New query plan, missing index on new predicate, config timeout change, ORM fetch change.',
    answer2m: 'Canary on p99 and DB CPU; compare EXPLAIN in CI for critical SQL; load test shadow. Rollback/flag strategy ready.',
    mistake: 'Only watching error rate, not latency/saturation.',
  },
  {
    id: 's16',
    level: 'senior',
    topic: 'Head-of-line',
    question: 'Explain head-of-line blocking in a shared executor.',
    answer30s: 'Slow tasks occupy workers; fast tasks queue behind—p99 suffers.',
    answer2m: 'Separate pools/queues by latency class; bounded queues with shed; prioritize. HTTP/1.1 vs H2 nuances at protocol layer too.',
  },
  {
    id: 's17',
    level: 'senior',
    topic: 'Observability cost',
    question: 'How can tracing itself hurt performance?',
    answer30s: 'High sample rates, huge spans/attributes, sync exporters add CPU and latency.',
    answer2m: 'Tail-based sampling, bound attributes, batch export, cardinality control. Keep critical path instrumentation lean.',
  },
  {
    id: 's18',
    level: 'senior',
    topic: 'Read path CQRS',
    question: 'When does a read model beat optimizing the transactional query?',
    answer30s: 'When complex joins can\'t meet SLO but eventual read projection can.',
    answer2m: 'Kafka/outbox → projected store (Redis/ES/Postgres table). Accept lag. Don\'t CQRS everything—ops cost is real.',
  },
  {
    id: 's19',
    level: 'senior',
    topic: 'SSL overhead',
    question: 'TLS handshake overhead—how do you manage it?',
    answer30s: 'Session resumption, connection pooling, terminate TLS at edge, HTTP/2 where fit.',
    answer2m: 'mTLS between many pods can dominate if short-lived connections. Watch handshake metrics. Prefer keep-alive.',
  },
  {
    id: 's20',
    level: 'senior',
    topic: 'DB lock contention',
    question: 'API slow with low CPU—DB shows lock waits. Approach?',
    answer30s: 'Find blocker sessions; shorten transactions; consistent lock order; reduce hotspot rows.',
    answer2m: 'Classic money row updates—consider queueing per account, optimistic versioning, or partitioning hot keys. Thread dumps show WAITING on socket to DB.',
    mistake: 'Adding indexes when the wait class is locks.',
  },
  {
    id: 's21',
    level: 'senior',
    topic: 'Autoscaling lag',
    question: 'HPA scales on CPU but latency still breaches—why?',
    answer30s: 'Bottleneck is DB/pool/external, not CPU; or scale-up too slow for spikes.',
    answer2m: 'Scale on RPS/concurrency/latency SLIs; pre-warm; shed during spin-up. CPU-only HPA is often wrong for I/O-bound Spring apps.',
  },
  {
    id: 's22',
    level: 'senior',
    topic: 'Serialization boundary',
    question: 'Where should you validate/deserialize large payloads for performance?',
    answer30s: 'Fail oversized bodies at gateway; stream/parse lazily; reject early.',
    answer2m: 'Max request size, content-length checks, streaming JSON parsers for large imports. Don\'t buffer multi-MB into heap unnecessarily.',
  },
  {
    id: 's23',
    level: 'senior',
    topic: 'Connection max lifetime',
    question: 'Why set Hikari maxLifetime / HTTP connection TTL in K8s?',
    answer30s: 'Avoid holding connections to dead pod IPs or stale LB targets.',
    answer2m: 'Rotate before NAT/LB idle timeouts. Prevents mysterious timeouts after deploys. Pair with proper readiness and graceful shutdown.',
  },
  {
    id: 's24',
    level: 'senior',
    topic: 'Percentile aggregation',
    question: 'Why is averaging p99 across instances wrong?',
    answer30s: 'Percentiles don\'t average; need histograms merged correctly.',
    answer2m: 'Use histogram digests (HDR/prometheus histograms) for global p99. Naive avg of p99s misleads capacity decisions.',
  },
  {
    id: 's25',
    level: 'senior',
    topic: 'Warm cache deploy',
    question: 'How do you deploy a cache-dependent service without a miss storm?',
    answer30s: 'Canary, staggered TTL, pre-warm critical keys, singleflight, gradual traffic shift.',
    answer2m: 'Avoid simultaneous fleet restart flushing local caches. Soft dependency on Redis with bounded DB fallback QPS.',
  },
  {
    id: 's26',
    level: 'senior',
    topic: 'Backpressure Kafka',
    question: 'How should a consumer apply backpressure when DB is overloaded?',
    answer30s: 'Pause partition consumption / bound in-flight; don\'t infinitely spawn work.',
    answer2m: 'Spring Kafka pause/resume; reactive pull models; avoid unbounded executor queues. Lag is better than melting the DB.',
  },
  {
    id: 's27',
    level: 'senior',
    topic: 'APM sampling bias',
    question: 'Why might traces miss the incident you care about?',
    answer30s: 'Head sampling drops rare slow traces; you need tail sampling or metric triggers.',
    answer2m: 'Keep RED metrics always-on; sample more on errors/high latency. Don\'t trust empty trace UI as "all fast".',
  },
  {
    id: 's28',
    level: 'senior',
    topic: 'ORM vs SQL',
    question: 'When do you drop to native SQL for performance?',
    answer30s: 'Bulk ops, complex analytics-ish reads, planner hints needs, or proven ORM overhead.',
    answer2m: 'Keep domain writes in ORM if clear; isolate hot native queries with tests and EXPLAIN CI. Don\'t rewrite everything.',
  },
  {
    id: 's29',
    level: 'senior',
    topic: 'Graceful shutdown',
    question: 'How does poor shutdown create performance/availability issues?',
    answer30s: 'In-flight requests killed → retries storm; lingering tasks hold DB rows.',
    answer2m: 'Stop intake, drain threads, commit/close pools, respect LB deregistration delay. Misconfigured preStop causes 5xx spikes each deploy.',
  },
  {
    id: 's30',
    level: 'senior',
    topic: 'Data shape',
    question: 'Why must load tests use production-like data volume and skew?',
    answer30s: 'Plans and cache behavior change with size and hotspot skew.',
    answer2m: 'Synthetic uniform keys hide hot partitions and bad plans. Include outliers and large payloads. Otherwise "perf green" lies.',
  },
  {
    id: 's31',
    level: 'senior',
    topic: 'Native image / AOT',
    question: 'How can native/AOT help or hurt service performance?',
    answer30s: 'Faster startup/lower memory possible; peak throughput/peak latency tradeoffs exist.',
    answer2m: 'Great for scale-to-zero and CLI. For long-running high-throughput JVMs, measure carefully—JIT may win peak. Not a free lunch.',
  },
  {
    id: 's32',
    level: 'senior',
    topic: 'Query pagination consistency',
    question: 'How can unstable sort keys ruin performance and correctness?',
    answer30s: 'Inconsistent ordering causes duplicates/misses and defeats index usage.',
    answer2m: 'Use unique tie-breakers in ORDER BY matching indexes. Keyset pagination depends on deterministic keys.',
  },
  {
    id: 's33',
    level: 'senior',
    topic: 'Client-side timeouts',
    question: 'Mobile client timeout 10s, GW 30s, service 60s—what breaks?',
    answer30s: 'Client retries while server still works → duplicate load and confusing errors.',
    answer2m: 'Align budgets decreasing inward. Idempotency mandatory. Observability must show client-abandoned work.',
    mistake: 'Longer server timeouts "to be safe".',
  },
  {
    id: 's34',
    level: 'senior',
    topic: 'Heap vs RSS',
    question: 'Heap looks fine but RSS high—what else?',
    answer30s: 'Direct buffers, thread stacks, code cache, glibc allocator fragmentation, sidecars.',
    answer2m: 'Profile off-heap; set MaxDirectMemorySize; check native leaks; container metrics vs JVM metrics differ. Important on K8s OOMKills.',
  },
  {
    id: 's35',
    level: 'senior',
    topic: 'Prove the fix',
    question: 'What evidence pack do you bring to say an optimization worked?',
    answer30s: 'Same-load before/after p95/p99, resource charts, EXPLAIN/profile diffs, and no error-rate regression.',
    answer2m: 'Include capacity headroom and cost. Canary in prod with clear success metrics. Senior bar is proof, not anecdotes.',
  },
];

export const STAFF: InterviewQ[] = [
  {
    id: 'st01',
    level: 'staff',
    topic: 'Performance culture',
    question: 'How do you build a performance practice across many Spring services?',
    answer30s: 'SLOs, golden dashboards, load-test gates, shared playbooks, and capacity budgets as platform standards.',
    answer2m: 'Staff+ sets the measurement contract: RED/USE, histogram SLOs, fleet DB connection governance, canary on latency. Provide paved-road libraries (timeouts, Hikari defaults, tracing). Review regressions like security bugs.',
    deepDive: 'Create a performance guild + scorecards per critical journey.',
    mistake: 'One-off hero tuning without institutionalizing gates.',
  },
  {
    id: 'st02',
    level: 'staff',
    topic: 'Error budgets',
    question: 'How do error budgets interact with performance work?',
    answer30s: 'Latency SLO burn triggers freeze/feature slowdown and prioritizes reliability/perf fixes.',
    answer2m: 'Treat p99 burn like availability burn. Tie releases to budget. Distinguish customer-facing journeys vs internal batch.',
    followUps: ['Who owns the budget for a multi-team path?'],
  },
  {
    id: 'st03',
    level: 'staff',
    topic: 'Multi-service bottleneck',
    question: 'Latency is in "the mesh"—how do you find the owning team?',
    answer30s: 'Trace critical path; attribute budget consumption per service; assign fix ownership with data.',
    answer2m: 'Avoid blame ping-pong. Cross-team RCA with span percentages. Platform may fix shared libraries; product teams fix SQL. Staff facilitates with evidence.',
  },
  {
    id: 'st04',
    level: 'staff',
    topic: 'Global pool governance',
    question: 'Design a control to stop teams from melting RDS with pools.',
    answer30s: 'Central max_connections budget, admission for pool size×replicas, and platform defaults.',
    answer2m: 'Automate calc in deploy pipeline; break builds that oversubscribe; provide shared proxies (PgBouncer) when needed. Document exception process.',
    deepDive: 'Per-environment envelopes; prod stricter than stage.',
  },
  {
    id: 'st05',
    level: 'staff',
    topic: 'Cost × performance',
    question: 'How do you decide optimize code vs buy bigger infra?',
    answer30s: 'Compare engineering cost and risk vs recurring infra cost; prioritize high-leverage bottlenecks.',
    answer2m: 'If a missing index saves 50% RDS cost, do that first. If algorithmic O(n²) blocks growth, fix code. Staff frames $ and risk, not macho micro-opts.',
  },
  {
    id: 'st06',
    level: 'staff',
    topic: 'Region strategy',
    question: 'Users far from primary region—perf options?',
    answer30s: 'Edge cache, regional read replicas, multi-region active-active for critical reads, or accept budget.',
    answer2m: 'Consistency and failover complexity explode with multi-region writes. Prefer edge+CDN and regionalize read-heavy paths first. Explicit latency SLOs by geo.',
  },
  {
    id: 'st07',
    level: 'staff',
    topic: 'Platform defaults',
    question: 'What performance defaults belong in the internal Spring Boot starter?',
    answer30s: 'Timeouts, Hikari sane caps, Micrometer histograms, graceful shutdown, JSON size limits, VT/bulkhead patterns.',
    answer2m: 'Opinionated defaults beat wiki pages. Allow overrides with review. Emit metrics for misconfig. Version upgrades as platform products.',
  },
  {
    id: 'st08',
    level: 'staff',
    topic: 'Incident leadership',
    question: 'p99 melted across 20 services—first 15 minutes as staff IC?',
    answer30s: 'Stabilize (shed/rollback/flag), declare severity, assign investigators by layer, demand evidence not theories.',
    answer2m: 'Check deploy markers and shared deps (Redis/RDS/Kafka). Mitigate blast radius before perfect RCA. Comms cadence. Prevent retry storms.',
    mistake: 'Everyone profiles randomly without a coordinator.',
  },
  {
    id: 'st09',
    level: 'staff',
    topic: 'SLO architecture',
    question: 'Should every microservice have the same latency SLO?',
    answer30s: 'No—set journey SLOs; service SLOs derive from contribution to the journey.',
    answer2m: 'User checkout SLO differs from async settlement. Avoid conflicting SLOs that force impossible budgets. Staff aligns product + platform.',
  },
  {
    id: 'st10',
    level: 'staff',
    topic: 'Data architecture',
    question: 'When is sharding the right performance answer?',
    answer30s: 'When a single primary cannot meet QPS/size even after query/index/caching wins.',
    answer2m: 'Sharding adds cross-shard pain. Try vertical split, CQRS, caching, read replicas first. Staff insists on measured ceilings and operational readiness.',
  },
  {
    id: 'st11',
    level: 'staff',
    topic: 'Kafka as backbone',
    question: 'How do you keep event-driven architectures from becoming latency nightmares?',
    answer30s: 'Clear sync vs async boundaries; lag SLOs; avoid sync request-reply over Kafka for UX paths.',
    answer2m: 'Idempotent consumers, DLQ policy, partition strategy, backpressure. Don\'t chain 8 sync awaits on topics. Staff defines allowed patterns.',
  },
  {
    id: 'st12',
    level: 'staff',
    topic: 'Security vs perf',
    question: 'How do you negotiate encryption/PII controls that add latency?',
    answer30s: 'Measure overhead; push crypto to efficient libs/HSM boundaries; cache tokens; don\'t skip controls.',
    answer2m: 'Staff finds designs that meet both: field-level encrypt only sensitive columns, TLS offload, connection reuse. Document accepted budgets.',
  },
  {
    id: 'st13',
    level: 'staff',
    topic: 'Test environments',
    question: 'Prod-like performance testing is expensive—what\'s the staff approach?',
    answer30s: 'Critical journey shadow/canary in prod; scaled-down fidelity stage; microbench for libraries.',
    answer2m: 'Risk-based: money paths get strongest gates. Synthetic probes continuously. Avoid maintaining a perfect full-prod twin for everything.',
  },
  {
    id: 'st14',
    level: 'staff',
    topic: 'Library upgrades',
    question: 'Jackson/Netty upgrade might speed OR regress—process?',
    answer30s: 'Benchmark critical paths, canary, watch alloc/p99, fast rollback.',
    answer2m: 'Platform owns paved-road upgrades with compatibility tests. Don\'t force silent major bumps on Black Friday week.',
  },
  {
    id: 'st15',
    level: 'staff',
    topic: 'Capacity reviews',
    question: 'What does a quarterly capacity review include?',
    answer30s: 'Peak RPS vs headroom, DB CPU/storage, Kafka lag peaks, cache hit, cost, and known bottlenecks.',
    answer2m: 'Forecast launches; AZ-loss scenarios; connection budgets; action owners. Staff turns reviews into funded work, not slideware.',
  },
  {
    id: 'st16',
    level: 'staff',
    topic: 'Cross-team API chattiness',
    question: 'Service A calls B 20 times per user action—staff fix?',
    answer30s: 'Mandate batch/aggregate endpoints or BFF aggregation; budget the chattiness.',
    answer2m: 'Architecture review gate on new sync fan-out. Provide shared BFF patterns. Measure bytes and RTT. Sometimes merge services if boundary wrong.',
  },
  {
    id: 'st17',
    level: 'staff',
    topic: 'Reliability × latency',
    question: 'How can raising availability hurt latency (and vice versa)?',
    answer30s: 'Sync replication/quorums add latency; async improves latency but risks durability/staleness.',
    answer2m: 'Make the trade explicit per data class. Staff prevents one-size policy. Example: durable ledger sync; recommendations async.',
  },
  {
    id: 'st18',
    level: 'staff',
    topic: 'Vendor dependency',
    question: 'Third-party API p99 destroys your SLO—options?',
    answer30s: 'Timeouts/CB/fallback, async where possible, cache, hedge carefully, contractual SLOs, multi-vendor.',
    answer2m: 'Don\'t infinite-wait. Product UX for degraded mode. Track vendor error budgets separately. Staff escalates commercially with data.',
  },
  {
    id: 'st19',
    level: 'staff',
    topic: 'Org incentives',
    question: 'Teams are rewarded for features, not p99—what do you change?',
    answer30s: 'Make SLO burn visible in planning; gate launches; celebrate perf wins with cost savings.',
    answer2m: 'Include latency in definition of done for critical journeys. Platform makes the right thing easy. Staff aligns managers on shared outcomes.',
  },
  {
    id: 'st20',
    level: 'staff',
    topic: 'Disaster + perf',
    question: 'Failover to DR region—what performance risks?',
    answer30s: 'Cold caches, smaller capacity, cross-region residual traffic, DNS TTL lag.',
    answer2m: 'Game-day with traffic; pre-warm; capacity parity goals; shed noncritical load during failover. Measure RTO including performance recovery, not just "up".',
  },
  {
    id: 'st21',
    level: 'staff',
    topic: ' tip vs deep',
    question: 'When do you reject a "just add Redis" proposal?',
    answer30s: 'When root cause is write path, consistency-sensitive money, or missing index—cache won\'t fix.',
    answer2m: 'Staff demands problem framing: read/write ratio, consistency, invalidation owner, failure mode. Cache is a tool, not a personality.',
    mistake: 'Caching as first response to every latency complaint.',
  },
  {
    id: 'st22',
    level: 'staff',
    topic: 'Observability platform',
    question: 'Trace volume costs explode—how do you preserve perf debugging?',
    answer30s: 'Tail sampling, journey-based retention, metrics always-on, strict attribute allowlists.',
    answer2m: 'Keep high-fidelity on checkout/payments. Drop chatty health spans. Staff negotiates cost vs investigative power with finance.',
  },
  {
    id: 'st23',
    level: 'staff',
    topic: 'Contract testing perf',
    question: 'How do API contracts encode performance expectations?',
    answer30s: 'Document payload limits, pagination requirements, and latency class; enforce in gateway.',
    answer2m: 'Break oversized endpoints in review. Provide batch alternatives. Consumer-driven contracts can include SLA notes for critical pairs.',
  },
  {
    id: 'st24',
    level: 'staff',
    topic: 'Heterogeneous runtimes',
    question: 'Some services JVM, some Node/Go—how unify performance standards?',
    answer30s: 'Unify SLIs/SLOs and playbooks; allow runtime-specific profilers behind the same evidence bar.',
    answer2m: 'Platform cares about golden signals and budgets, not identical tools. Staff avoids religious wars; demands proof.',
  },
  {
    id: 'st25',
    level: 'staff',
    topic: 'Peak events',
    question: 'Black Friday prep checklist as staff?',
    answer30s: 'Load test peaks, scale & pre-warm, feature freeze risky paths, dashboards/alerts, shed plans, oncall drills.',
    answer2m: 'Validate DB/Kafka/Redis ceilings; disable nonessential jobs; confirm vendor capacity; clear rollback. Postmortem even if green.',
  },
  {
    id: 'st26',
    level: 'staff',
    topic: 'Technical debt',
    question: 'How do you prioritize a year of performance debt?',
    answer30s: 'Rank by SLO burn × revenue/risk × fix leverage; sequence foundations before polish.',
    answer2m: 'Connection budgets, N+1 on top journeys, timeout alignment beat micro-optimizing JSON. Fund explicitly in roadmap.',
  },
  {
    id: 'st27',
    level: 'staff',
    topic: 'AI/LLM features',
    question: 'New LLM call in a user request path—staff performance guidance?',
    answer30s: 'Never block core UX without budget; async, stream, cache, hard timeouts, degrade gracefully.',
    answer2m: 'Separate SLOs; bound concurrency to vendor; watch cost/latency. Don\'t let AI features melt thread pools for checkout.',
  },
  {
    id: 'st28',
    level: 'staff',
    topic: 'Evidence culture',
    question: 'Engineers keep shipping "optimizations" without numbers—what do you do?',
    answer30s: 'Require before/after metrics in PRs for perf claims; provide easy harnesses.',
    answer2m: 'Make measurement low-friction: standard k6 scripts, dashboard links in template. Reject cargo-cult PRs kindly but firmly.',
  },
  {
    id: 'st29',
    level: 'staff',
    topic: 'Shared DB',
    question: 'Multiple services share one RDS—performance governance?',
    answer30s: 'Treat as a platform: connection quotas, query budgets, noisy-neighbor detection, roadmap to split.',
    answer2m: 'Short-term PgBouncer + limits; long-term ownership boundaries. Staff drives decomposition with data, not dogma.',
  },
  {
    id: 'st30',
    level: 'staff',
    topic: 'Hiring bar',
    question: 'What does a strong senior performance interview answer include?',
    answer30s: 'Measure→bottleneck→fix→prove; Little\'s Law; tradeoffs; failure modes—not tool name-drops.',
    answer2m: 'They cite percentiles, pools, timeouts, and evidence. Staff candidates add org/platform levers and cost. Reject buzzword-only answers.',
  },
];

export const RAPID: InterviewQ[] = [
  {id: 'r01', level: 'beginner', topic: 'Rapid', question: 'Little\'s Law formula?', answer30s: 'L=λW; concurrency≈RPS×latency.', answer2m: 'Use P99×peak RPS to size pools with headroom.'},
  {id: 'r02', level: 'beginner', topic: 'Rapid', question: 'Why p99 > average?', answer30s: 'Tails hurt users; averages hide them.', answer2m: 'SLO on percentiles; watch multimodal histograms.'},
  {id: 'r03', level: 'beginner', topic: 'Rapid', question: 'First tool for slow API?', answer30s: 'Distributed trace waterfall.', answer2m: 'Then EXPLAIN/profile/dump based on top span.'},
  {id: 'r04', level: 'beginner', topic: 'Rapid', question: 'N+1 one-liner?', answer30s: '1+N queries from lazy loads.', answer2m: 'Fix with join/DTO; detect via SQL count.'},
  {id: 'r05', level: 'beginner', topic: 'Rapid', question: 'Hikari timeout meaning?', answer30s: 'Waited too long for a free connection.', answer2m: 'Slow holders or undersized pool; check pending.'},
  {id: 'r06', level: 'beginner', topic: 'Rapid', question: 'Cache stampede?', answer30s: 'Many miss the same key at once → DB spike.', answer2m: 'Singleflight + staggered TTL.'},
  {id: 'r07', level: 'beginner', topic: 'Rapid', question: 'When thread dump?', answer30s: 'Hang/saturation with low CPU.', answer2m: 'See wait stacks on DB/locks/HTTP.'},
  {id: 'r08', level: 'beginner', topic: 'Rapid', question: 'When heap dump?', answer30s: 'Climbing heap / OOM suspicion.', answer2m: 'Analyze retained set; soak to verify.'},
  {id: 'r09', level: 'beginner', topic: 'Rapid', question: 'GC pause symptom?', answer30s: 'Jagged p99 aligned with GC metrics.', answer2m: 'Cut alloc; then tune.'},
  {id: 'r10', level: 'beginner', topic: 'Rapid', question: 'SELECT * cost?', answer30s: 'Extra I/O and serialization.', answer2m: 'Project needed columns.'},
  {id: 'r11', level: 'beginner', topic: 'Rapid', question: 'Idempotency-Key for?', answer30s: 'Safe retries on mutating APIs.', answer2m: 'Prevents double side effects + extra load.'},
  {id: 'r12', level: 'beginner', topic: 'Rapid', question: 'Bulkhead purpose?', answer30s: 'Isolate dependency capacity.', answer2m: 'Stop one slow dep from taking all threads.'},
  {id: 'r13', level: 'beginner', topic: 'Rapid', question: 'CB vs timeout?', answer30s: 'Timeout bounds one call; CB stops calling a sick dep.', answer2m: 'Use both.'},
  {id: 'r14', level: 'beginner', topic: 'Rapid', question: 'Kafka lag cause #1?', answer30s: 'Consume rate < produce rate.', answer2m: 'Often slow per-record I/O in listener.'},
  {id: 'r15', level: 'beginner', topic: 'Rapid', question: 'Partitions vs consumers?', answer30s: 'Parallelism ≤ partitions.', answer2m: 'Extra consumers idle.'},
  {id: 'r16', level: 'beginner', topic: 'Rapid', question: 'ALB 504 usually?', answer30s: 'Backend exceeded idle timeout.', answer2m: 'Fix latency/budgets, not only ALB.'},
  {id: 'r17', level: 'beginner', topic: 'Rapid', question: 'OSIV problem?', answer30s: 'Lazy I/O during view; N+1 risk.', answer2m: 'Disable for APIs; fetch explicitly.'},
  {id: 'r18', level: 'beginner', topic: 'Rapid', question: 'Virtual threads myth?', answer30s: 'Not unlimited DB capacity.', answer2m: 'Still bound scarce resources.'},
  {id: 'r19', level: 'beginner', topic: 'Rapid', question: 'Keyset vs OFFSET?', answer30s: 'Keyset scales deep pages.', answer2m: 'OFFSET gets slower as page depth grows.'},
  {id: 'r20', level: 'beginner', topic: 'Rapid', question: 'Retry storm?', answer30s: 'Layered retries multiply traffic.', answer2m: 'One owner + jitter + idempotency.'},
  {id: 'r21', level: 'beginner', topic: 'Rapid', question: 'Hot key Redis?', answer30s: 'One key dominates CPU/network.', answer2m: 'Split keys / local cache / coalesce.'},
  {id: 'r22', level: 'beginner', topic: 'Rapid', question: 'Soak test finds?', answer30s: 'Leaks and drift over time.', answer2m: 'Hours of steady load with charts.'},
  {id: 'r23', level: 'beginner', topic: 'Rapid', question: 'Cross-AZ chatty cost?', answer30s: 'Extra RTT per call + data transfer.', answer2m: 'Co-locate or reduce chattiness.'},
  {id: 'r24', level: 'beginner', topic: 'Rapid', question: 'Metric cardinality?', answer30s: 'Too many unique label sets.', answer2m: 'Explodes TSDB cost/query time.'},
  {id: 'r25', level: 'beginner', topic: 'Rapid', question: 'Load vs stress?', answer30s: 'Load=expected peak; stress=break point.', answer2m: 'Don\'t treat break point as capacity target.'},
  {id: 'r26', level: 'beginner', topic: 'Rapid', question: 'Connection leak clue?', answer30s: 'Active→max while RPS modest.', answer2m: 'Idle in transaction on DB side.'},
  {id: 'r27', level: 'beginner', topic: 'Rapid', question: 'HTTP keep-alive why?', answer30s: 'Amortize TCP/TLS setup.', answer2m: 'Pool with max lifetime in K8s.'},
  {id: 'r28', level: 'beginner', topic: 'Rapid', question: 'EXPLAIN seq scan bad?', answer30s: 'Often on large tables with selective filters.', answer2m: 'Confirm with ANALYZE + row counts.'},
  {id: 'r29', level: 'beginner', topic: 'Rapid', question: 'p99 across instances?', answer30s: 'Merge histograms; don\'t average p99s.', answer2m: 'Wrong math → wrong capacity.'},
  {id: 'r30', level: 'beginner', topic: 'Rapid', question: 'Sync in transaction?', answer30s: 'Holds DB conn during network.', answer2m: 'Outbox/after-commit instead.'},
  {id: 'r31', level: 'beginner', topic: 'Rapid', question: 'CDN helps APIs?', answer30s: 'Cacheable GETs/assets; careful with auth.', answer2m: 'Not a fix for slow writes.'},
  {id: 'r32', level: 'beginner', topic: 'Rapid', question: 'HPA on CPU fail?', answer30s: 'I/O-bound apps need other signals.', answer2m: 'Scale on RPS/latency/concurrency.'},
  {id: 'r33', level: 'beginner', topic: 'Rapid', question: 'Batch Kafka produce?', answer30s: 'linger.ms + batch.size.', answer2m: 'Higher throughput, slight latency trade.'},
  {id: 'r34', level: 'beginner', topic: 'Rapid', question: 'Logging CPU?', answer30s: 'toString/JSON of fat objects in hot path.', answer2m: 'Sample + structured fields.'},
  {id: 'r35', level: 'beginner', topic: 'Rapid', question: 'Read replica lag risk?', answer30s: 'Stale reads after write.', answer2m: 'Read-your-writes on primary when needed.'},
  {id: 'r36', level: 'beginner', topic: 'Rapid', question: 'Graceful shutdown need?', answer30s: 'Drain in-flight; avoid retry storms.', answer2m: 'Align with LB deregistration delay.'},
  {id: 'r37', level: 'beginner', topic: 'Rapid', question: 'Humongous objects?', answer30s: 'Large allocs stress G1 specially.', answer2m: 'Avoid giant byte[]/strings where possible.'},
  {id: 'r38', level: 'beginner', topic: 'Rapid', question: 'Edge shed vs app shed?', answer30s: 'Edge cheaper; protects whole fleet.', answer2m: 'App shed still needed for dependency protection.'},
  {id: 'r39', level: 'beginner', topic: 'Rapid', question: 'Prove optimization?', answer30s: 'Before/after same-load p99 + resources.', answer2m: 'No error-rate or cost regression.'},
  {id: 'r40', level: 'beginner', topic: 'Rapid', question: 'Cargo cult scale-out?', answer30s: 'More pods multiply bad queries/cost.', answer2m: 'Fix bottleneck first; then scale.'},
];

export const ALL: InterviewQ[] = [...BEGINNER, ...INTERMEDIATE, ...SENIOR, ...STAFF, ...RAPID];
