import type {BeforeAfter, CaseStudy, PlaybookScenario} from './types';

/** Metrics / logs / traces — what each answers. */
export const OBSERVE_ROWS: string[][] = [
  ['Signal', 'Answers', 'Good for', 'Blind spot'],
  ['Metrics', 'How bad / how often?', 'SLOs, alerts, capacity', 'Why a single request was slow'],
  ['Logs', 'What happened on this request?', 'Errors, audit, rare events', 'High-cardinality floods; no latency math'],
  ['Traces', 'Where did time go?', 'Waterfalls across hops', 'Sampling may miss rare P99'],
  ['Profiles', 'Which code burns CPU/alloc?', 'Hot methods, GC pressure', 'Waiting on I/O looks "idle"'],
  ['Dumps', 'What are threads/heap holding?', 'Stuck pools, leaks', 'Point-in-time; can be invasive'],
];

export const PROFILE_ASCII = `
Symptom → evidence tool
───────────────────────
High CPU        → CPU profile (async-profiler / JFR)
Memory climbing → Heap dump (+ allocation profile)
GC pauses       → GC logs / JFR GC events
Stuck / hung    → Thread dump (jstack / jcmd Thread.print)
Slow DB         → EXPLAIN ANALYZE + DB wait events
`.trim();

export const TEST_TYPES_ROWS: string[][] = [
  ['Type', 'Goal', 'What you learn', 'Trap'],
  ['Benchmark', 'Micro latency/throughput of one path', 'Hot code cost', 'Ignores pool/network contention'],
  ['Load', 'Expected peak traffic', 'Meets SLO under plan', 'Flat load hides spikes'],
  ['Stress', 'Push past capacity until break', 'Breaking point / failure mode', 'Do not treat as prod target'],
  ['Spike', 'Sudden 5–10× burst', 'Autoscaling + queues + CB', 'Cold caches look worse'],
  ['Soak', 'Hours/days at moderate load', 'Leaks, GC drift, FD growth', 'Needs stable baseline'],
  ['Capacity', 'Max RPS at SLO with headroom', 'Sizing & cost', 'Wrong mix ≠ production mix'],
];

export const LITTLES_LAW = `
Little's Law
────────────
  L = λ × W
  concurrency ≈ arrival_rate × latency

Example
  1000 rps × 0.1 s = 100 in-flight requests
  → you need ~100 threads/connections/slots for that path
    (plus queueing headroom and P99, not just average)

Sizing tip
  size pools from P99 latency × peak RPS, not from "feels fine"
`.trim();

export const PLAYBOOKS: PlaybookScenario[] = [
  {
    id: 'api-slow',
    title: 'API slow',
    symptom: 'p95/p99 latency up; clients timeout or 504 at edge',
    causes: [
      'Slow SQL / N+1 / missing index',
      'Sync external call without timeout budget',
      'Thread or DB pool saturation',
      'GC pause or lock contention',
      'Retry amplification under load',
    ],
    metrics: ['http.server.requests p95/p99', 'dependency span latency', 'hikaricp.pending', 'tomcat.threads.busy', 'jvm.gc.pause'],
    tools: ['Distributed traces', 'APM waterfall', 'EXPLAIN ANALYZE', 'Thread dump', 'GC logs'],
    rootCause: 'Time is spent in one dominant span (usually DB or remote), or requests queue waiting for a saturated pool',
    fix: 'Fix the hot span (query/index/batch), enforce timeouts+CB, size pools with Little\'s Law, stop nested retries',
    validate: 'p95/p99 back under SLO; pending acquires ~0; dependency error rate stable; load test reproduces gain',
  },
  {
    id: 'cpu-95',
    title: 'CPU 95%',
    symptom: 'Host/pod CPU pegged; latency rises; autoscaling thrash',
    causes: [
      'Hot loop / regex / JSON parse on large payloads',
      'Excessive logging / serialization',
      'GC thrashing from allocation',
      'Busy spin / polling',
      'Traffic spike or retry storm',
    ],
    metrics: ['process.cpu.usage', 'container_cpu_utilization', 'jvm.gc.overhead', 'http rps', 'alloc rate'],
    tools: ['async-profiler / JFR CPU', 'top / kubectl top', 'Flame graph', 'GC logs'],
    rootCause: 'A small set of methods dominate CPU samples, or GC/alloc burns cycles under load',
    fix: 'Optimize hot method, cut allocations, compress/paginate payloads, shed load, fix retry storms',
    validate: 'CPU drops at same RPS; flame graph hot % shrinks; p99 improves without raising replicas only',
  },
  {
    id: 'memory-up',
    title: 'Memory climbing',
    symptom: 'RSS/heap trend up over hours; eventual OOMKilled or OutOfMemoryError',
    causes: [
      'Heap leak (caches without bounds, listeners, ThreadLocal)',
      'Off-heap / direct buffer leak',
      'Metaspace growth (classloader leak)',
      'Large retained responses / unbounded queues',
      'Undersized heap for working set',
    ],
    metrics: ['jvm.memory.used', 'jvm.memory.max', 'container_memory_working_set', 'cache size', 'queue depth'],
    tools: ['Heap dump (MAT/VisualVM)', 'Allocation profile', 'jcmd GC.heap_info', 'kubectl describe OOM'],
    rootCause: 'Objects retained across requests or unbounded growth; sometimes just heap too small for peak',
    fix: 'Bound caches/queues, fix leak root, right-size heap vs limit, rolling restart only as bridge',
    validate: 'Heap stable on soak test; no OOM at peak; retained set in dump shrinks after fix',
  },
  {
    id: 'gc-pauses',
    title: 'GC pauses',
    symptom: 'Tail latency spikes correlate with GC; threads pause; P99 jagged',
    causes: [
      'High allocation rate / object churn',
      'Heap too small → frequent collections',
      'Humongous objects / large arrays',
      'Wrong GC for workload (or default untuned)',
      'Memory leak forcing full GCs',
    ],
    metrics: ['jvm.gc.pause p99', 'jvm.gc.overhead', 'alloc/sec', 'humongous allocations', 'promotion rate'],
    tools: ['GC logs (-Xlog:gc*)', 'JFR GC', 'Allocation profile', 'Heap occupancy charts'],
    rootCause: 'Collector cannot keep up with allocation or heap occupancy without long pauses',
    fix: 'Cut allocation (reuse buffers, avoid boxed churn), tune heap/GC, remove humongous paths, fix leaks',
    validate: 'GC pause p99 within budget; allocation rate down; application p99 smooth under same load',
  },
  {
    id: 'db-cpu',
    title: 'DB CPU high',
    symptom: 'RDS/Aurora CPU high; API latency follows DB; connection wait grows',
    causes: [
      'Full table scans / missing indexes',
      'Bad plans after stats change',
      'N+1 or SELECT * wide rows',
      'Lock waits / long transactions',
      'Analytical query on OLTP primary',
    ],
    metrics: ['DB CPUUtilization', 'ReadIOPS/WriteIOPS', 'DatabaseConnections', 'slow query count', 'lock wait time'],
    tools: ['Performance Insights', 'pg_stat_statements', 'EXPLAIN ANALYZE', 'pg_stat_activity'],
    rootCause: 'Few expensive statements dominate CPU or I/O; app multiplies them under concurrency',
    fix: 'Index/rewrite hot SQL, kill/limit bad queries, move analytics off primary, shorten transactions',
    validate: 'DB CPU down; EXPLAIN uses index; API p95 improves; connection count stable',
  },
  {
    id: 'pool-exhausted',
    title: 'Connection pool exhausted',
    symptom: 'Hikari timeout getting connection; pending acquires; API errors under load',
    causes: [
      'Slow queries holding connections',
      'Connection leak (not closed / long @Transactional)',
      'Pool size ≪ thread concurrency (Little\'s Law miss)',
      'Sync remote call inside transaction',
      'Too many pods × pool > DB max_connections',
    ],
    metrics: ['hikaricp.connections.active', 'hikaricp.connections.pending', 'hikaricp.connections.timeout', 'DB sessions'],
    tools: ['Hikari metrics', 'Thread dump (waiting on pool)', 'pg_stat_activity', 'Datasource proxy'],
    rootCause: 'Connections held longer than budget or pool undersized vs in-flight work; sometimes global oversubscription',
    fix: 'Fix slow/leak holders, shrink transaction scope, size pool = f(P99×RPS), cap pods×pool under DB max',
    validate: 'pending≈0; no acquire timeouts at peak; DB sessions < max; soak stays flat',
  },
  {
    id: 'kafka-lag',
    title: 'Kafka consumer lag',
    symptom: 'Consumer group lag rising; downstream freshness SLO breached',
    causes: [
      'Slow processing per record (DB/HTTP inside listener)',
      'Too few partitions / consumers',
      'Stop-the-world GC or rebalance storms',
      'Poison message / retry loop',
      'Producer burst > sustained consume rate',
    ],
    metrics: ['kafka_consumergroup_lag', 'records-consumed-rate', 'commit latency', 'rebalance rate', 'listener error rate'],
    tools: ['Lag dashboard', 'Consumer JMX', 'Thread dump on consumer', 'Broker metrics', 'DLQ depth'],
    rootCause: 'Consume rate < produce rate for sustained window; often per-message sync I/O',
    fix: 'Batch/async side effects, scale partitions+consumers, tune fetch, isolate poison to DLQ, fix GC/rebalance',
    validate: 'Lag drains to near-zero at peak produce; rebalances rare; end-to-end lag SLO met',
  },
  {
    id: 'p99-only',
    title: 'P99 only (avg fine)',
    symptom: 'Mean/p50 healthy but p99/p999 blow SLO; intermittent client timeouts',
    causes: [
      'Cold cache / cache miss tails',
      'GC pauses or safepoints',
      'Lock / pool queueing under contention',
      'Noisy neighbor / one slow dependency',
      'Retry/timeout cliffs',
    ],
    metrics: ['latency histogram p50/p95/p99', 'GC pause', 'pool wait time', 'cache hit ratio', 'dependency p99'],
    tools: ['Latency heatmap', 'Trace sampling of slow traces', 'JFR', 'Percentile dashboards'],
    rootCause: 'Tail events (pause, miss, queue, slow dep) dominate high percentiles while average stays calm',
    fix: 'Attack tail causes: warm caches, cut GC, reduce contention, timeout+hedge carefully, isolate slow deps',
    validate: 'p99/p999 within SLO at peak; histogram tightens; slow-trace rate drops',
  },
  {
    id: 'one-instance-slow',
    title: 'One instance slow',
    symptom: 'Single pod/node has high latency or errors; others healthy',
    causes: [
      'Bad deploy / config skew on that instance',
      'Noisy neighbor CPU/IO',
      'Local disk full / FD exhaustion',
      'Stuck threads / half-open connection',
      'AZ network path issue',
    ],
    metrics: ['per-instance latency', 'CPU/mem/disk per pod', 'error rate by instance', 'GC per instance'],
    tools: ['Per-pod dashboards', 'kubectl top/describe/logs', 'Thread dump on bad pod', 'Compare configs'],
    rootCause: 'Instance-local resource or state problem, not fleet-wide code bug (until proven otherwise)',
    fix: 'Drain/replace bad instance, fix skew, free disk/FDs, then RCA why it degraded alone',
    validate: 'After replace, fleet latency uniform; root cause ticket closed with prevention',
  },
  {
    id: 'fast-local-slow-aws',
    title: 'Fast local, slow on AWS',
    symptom: 'Laptop/dev fast; prod/stage latency high or unstable',
    causes: [
      'Cross-AZ / cross-region chatter',
      'Small instances + noisy neighbors',
      'RDS far from app / wrong subnet',
      'No connection pooling / TLS overhead ignored locally',
      'Real data volume + cold caches vs tiny local DB',
    ],
    metrics: ['AZ latency', 'cross-AZ bytes', 'RDS latency', 'ALB target response', 'NAT/gateway errors'],
    tools: ['Trace with AZ attributes', 'VPC flow / Reachability', 'CloudWatch', 'Compare prod data shape'],
    rootCause: 'Production topology and data size introduce hops and contention absent on localhost',
    fix: 'Co-locate chatty tiers, cut chattiness, right-size, pool+timeouts, test with prod-like data and multi-AZ',
    validate: 'Prod p95 matches budget; cross-AZ chatter reduced; load test in AWS reproduces local-ish numbers',
  },
];

export const ANTIPATTERNS: string[][] = [
  ['Never blindly', 'Why it can hurt', 'Do this instead'],
  ['Add more threads', 'Amplifies lock/DB contention; Little\'s Law queueing', 'Find waiters; size to P99×RPS'],
  ['Raise Hikari max', 'Exhausts DB max_connections across pods', 'Fix hold time; cap pods×pool'],
  ['Cache everything', 'Stale money, stampede, huge RSS', 'Cache hot reads with TTL+singleflight'],
  ['SELECT *', 'Wide rows, I/O, serialization cost', 'Project needed columns'],
  ['Index every column', 'Write amplification, planner confusion', 'Index proven predicates'],
  ['Sync call in @Transactional', 'Holds DB connection during network', 'Commit then call / outbox'],
  ['Log full payloads', 'CPU, disk, PII, GC pressure', 'Structured fields + sampling'],
  ['Unlimited retries', 'Retry storm worsens outage', 'One owner, jitter, idempotency'],
  ['Bigger JVM heap only', 'Longer GC; hides leaks', 'Cut alloc; then size heap'],
  ['Microbench as capacity', 'Misses pools/network/GC', 'Load test the real path'],
  ['Scale replicas first', 'Multiplies bad queries/cost', 'Fix bottleneck, then scale'],
  ['Disable GC logging', 'Blind during pause incidents', 'Keep GC/JFR in prod (cheap)'],
  ['Ignore p99', 'Customers feel tails', 'SLO on p95/p99, not average'],
  ['Share one giant thread pool', 'Head-of-line blocking', 'Bulkheads per dependency'],
  ['Kafka sync request-reply for UX', 'Couples latency to lag', 'Async + status API'],
];

export const DECISION_MATRIX: string[][] = [
  ['Problem', 'First check', 'Likely fix'],
  ['API p99↑', 'Trace waterfall top span', 'Fix that span (SQL/remote/pool)'],
  ['CPU 90%+', 'CPU flame graph', 'Optimize hot method / cut alloc'],
  ['Heap climbing', 'Heap dump retained set', 'Bound cache / fix leak'],
  ['GC pause spikes', 'GC logs + alloc rate', 'Reduce churn; tune heap'],
  ['Hikari timeouts', 'active/pending + slow SQL', 'Shorten hold; right-size pool'],
  ['DB CPU high', 'top SQL / EXPLAIN', 'Index or rewrite query'],
  ['Kafka lag↑', 'Consume rate vs produce', 'Faster handler / more partitions'],
  ['Only one pod bad', 'Per-instance metrics', 'Drain/replace; fix skew'],
  ['504 at ALB', 'Target p99 vs idle timeout', 'Cut backend latency / budgets'],
  ['Cache miss storm', 'Hit ratio + DB QPS', 'Singleflight + softer TTL'],
  ['Local fast, AWS slow', 'Cross-AZ / data volume', 'Topology + prod-like load test'],
  ['Errors after deploy', 'Version marker + diff', 'Rollback or flag OFF'],
  ['Thread pool full', 'Dump wait stacks', 'Fix blocking dep; bulkhead'],
  ['P50 OK, P99 bad', 'Histogram + GC + misses', 'Attack tail causes'],
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'nplus1-800-120',
    title: 'N+1 list endpoint: 800ms → 120ms',
    architecture: 'ALB → Spring MVC → JPA/Hibernate → PostgreSQL',
    before: 'GET /orders returned 50 orders; each triggered lazy loads for items/customer → ~100+ queries; p95 ~800ms',
    rootCause: 'Classic N+1 from lazy associations under Open Session In View',
    fix: 'Entity graph / join fetch / DTO query; disable OSIV for API; add covering index on order_id',
    after: '2–3 queries total; p95 ~120ms at same concurrency; DB CPU −60%',
    interview: 'Show Hibernate statistics, EXPLAIN, and why join-fetch can over-fetch if unbounded',
  },
  {
    id: 'pool-20x30',
    title: 'Pool exhaustion: 20 pods × 30 connections',
    architecture: 'ECS/EKS → Spring Boot HikariCP → RDS max_connections≈400',
    before: 'Under peak, intermittent Hikari timeouts; RDS connections pegged; new pods made it worse',
    rootCause: '20×30=600 > DB max; plus slow queries held connections during outbound HTTP inside transactions',
    fix: 'Cap pool to 10; global budget < max_connections; move HTTP out of @Transactional; kill slow SQL',
    after: 'No acquire timeouts; DB sessions stable ~200; p99 recovered',
    interview: 'Derive pool size from Little\'s Law and fleet math, not "defaults"',
  },
  {
    id: 'kafka-lag-payments',
    title: 'Kafka lag on payment events',
    architecture: 'Producer services → Kafka → @KafkaListener → DB + RestClient',
    before: 'Lag grew to millions overnight; settlement delayed; scaling consumers barely helped',
    rootCause: 'Per-record sync HTTP + DB in listener; 12 partitions but heavy GC caused rebalances',
    fix: 'Batch DB writes, async outbox for HTTP, increase partitions, tune session.timeout, fix alloc',
    after: 'Lag drained in <30m at peak produce; rebalance rate near zero',
    interview: 'Lag is a rate problem; more consumers than partitions does nothing',
  },
  {
    id: 'jvm-memory-leak',
    title: 'JVM memory: unbounded cache leak',
    architecture: 'Spring Boot on K8s (512Mi limit) → Caffeine/Redis hybrid',
    before: 'RSS climbed over 6h soak; OOMKilled; restart "fixed" until next soak',
    rootCause: 'Local ConcurrentHashMap cache without max size; keys included raw request payloads',
    fix: 'Caffeine maximumSize+TTL; key by id hash; heap dump confirmed retained map',
    after: 'Heap flat on 24h soak; no OOM; p99 stable',
    interview: 'Restart is mitigation; dump proves root; soak tests catch leaks CI misses',
  },
  {
    id: 'aws-layered-latency',
    title: 'AWS layered latency: CloudFront → RDS',
    architecture: 'CloudFront → APIGW → ALB → Spring → Redis/Kafka → RDS (multi-AZ)',
    before: 'End-to-end p95 1.8s; local p95 80ms; each hop looked "fine" in isolation',
    rootCause: 'App in AZ-a, RDS primary AZ-b; chatty N+1; Redis in another region for "DR"; TLS+JSON on every hop',
    fix: 'Co-locate app+Redis+RDS AZ; cut chattiness; cache hot reads; compress; budget timeouts per hop',
    after: 'Prod p95 ~180ms; cross-AZ bytes −70%; SLO green',
    interview: 'Sum of hop budgets; measure each layer; locality beats blind scale-out',
  },
];

export const BEFORE_AFTER: BeforeAfter[] = [
  {
    id: 'ba-nplus1',
    title: 'N+1 queries',
    problem: 'List endpoint issues one query per child row',
    bad: 'orders.forEach(o -> o.getItems().size()) under OSIV',
    whySlow: 'Latency and DB CPU scale with rows × associations',
    good: 'JOIN FETCH / @EntityGraph / DTO projection query',
    whyFaster: 'Constant query count; less round-trip RTT',
    tradeoff: 'Join can multiply rows — paginate and select carefully',
    interview: 'How do you detect N+1 in prod without guessing?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-select-star',
    title: 'SELECT *',
    problem: 'Fetching wide rows for a narrow API',
    bad: 'SELECT * FROM customer_profile',
    whySlow: 'I/O, network, JSON serialization of unused columns',
    good: 'SELECT id, status, updated_at …',
    whyFaster: 'Less data moved and less GC from fat objects',
    tradeoff: 'Schema changes need projection updates',
    interview: 'When is SELECT * acceptable?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-missing-index',
    title: 'Missing index',
    problem: 'Filter on unindexed column under growth',
    bad: 'WHERE status=? AND created_at>? sequential scan',
    whySlow: 'CPU+I/O grow with table size',
    good: 'Composite index matching predicate + EXPLAIN verify',
    whyFaster: 'Index range scan; stable latency as data grows',
    tradeoff: 'Writes slower; index storage',
    interview: 'Show EXPLAIN before/after and write-path cost',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-object-churn',
    title: 'Object churn',
    problem: 'Per-request temporary object explosion',
    bad: 'Stream boxing, string concat in hot loop, new DTOs×N',
    whySlow: 'Alloc → GC pauses → P99 spikes',
    good: 'Reuse buffers, primitive collections, flyweight mappers',
    whyFaster: 'Lower alloc rate; smoother GC',
    tradeoff: 'Slightly more complex code',
    interview: 'Which metric proves alloc was the issue?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-loops',
    title: 'Chatty loops to DB/HTTP',
    problem: 'Loop calling repository or RestClient',
    bad: 'for (id : ids) client.get(id)',
    whySlow: 'Serial RTT compounds; holds threads',
    good: 'Batch API / IN query / parallel with bounded concurrency',
    whyFaster: 'Fewer round trips; better utilization',
    tradeoff: 'Batch size vs payload; partial failure handling',
    interview: 'How do you bound parallelism safely?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-sync-external',
    title: 'Sync external calls on request path',
    problem: 'User request waits on vendor HTTP',
    bad: 'RestClient in controller with 10s timeout',
    whySlow: 'Thread+pool occupied; cascades under vendor slowness',
    good: 'Timeout budget, CB, async+202 when UX allows',
    whyFaster: 'Fail fast; free capacity; isolate vendor',
    tradeoff: 'Eventual consistency if async',
    interview: 'Draw timeout hierarchy gateway→service→client',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-logging',
    title: 'Expensive logging',
    problem: 'Debug logs or toString on large graphs in hot path',
    bad: 'log.info("payload={}", hugeObject)',
    whySlow: 'CPU serialization even if level disabled poorly; disk I/O',
    good: 'Parameterized logs, sampling, structured fields only',
    whyFaster: 'Less CPU and GC; cheaper I/O',
    tradeoff: 'Less forensic detail — use traces for that',
    interview: 'How can logging dominate a CPU profile?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-large-json',
    title: 'Large JSON payloads',
    problem: 'Multi-MB request/response bodies',
    bad: 'Return entire aggregate graph as JSON',
    whySlow: 'Parse/serialize CPU, network, memory spikes',
    good: 'Paginate, sparse fields, compression, binary where fit',
    whyFaster: 'Less bytes and CPU per request',
    tradeoff: 'API shape complexity; client changes',
    interview: 'When prefer protobuf/Avro over JSON?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-no-pagination',
    title: 'No pagination',
    problem: 'Unbounded list queries',
    bad: 'findAll() returning 100k rows',
    whySlow: 'Huge result sets; OOM risk; long GC',
    good: 'Keyset pagination + hard max page size',
    whyFaster: 'Bounded work and memory per call',
    tradeoff: 'Clients must page; total count is expensive',
    interview: 'Offset vs keyset pagination tradeoffs?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-wrong-cache',
    title: 'Wrong cache usage',
    problem: 'Caching mutable money state or tiny rarely-read keys',
    bad: 'Cache balances forever; or cache miss-heavy keys',
    whySlow: 'Stale reads or wasted memory + stampede',
    good: 'Cache-aside hot immutable/slowly-changing reads; TTL+version',
    whyFaster: 'Hit ratio where it matters; safe consistency',
    tradeoff: 'Invalidation design effort',
    interview: 'What must never be cached without versioning?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-oversized-threads',
    title: 'Oversized thread pool',
    problem: 'Tomcat/executor maxThreads set "high to be safe"',
    bad: 'maxThreads=800 on 2 vCPU',
    whySlow: 'Context switch + DB pool stampede',
    good: 'Size from blocking profile + Little\'s Law; bulkheads',
    whyFaster: 'Less contention; predictable queueing',
    tradeoff: 'May need queue + load shed under spike',
    interview: 'How do virtual threads change this answer?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-wrong-db-pool',
    title: 'Wrong DB pool size',
    problem: 'Pool copy-pasted from another service',
    bad: 'maximumPoolSize=50 on every pod',
    whySlow: 'Fleet oversubscribe DB; or undersize causes waits',
    good: 'Fleet budget + P99×RPS math; measure pending',
    whyFaster: 'Stable acquires without drowning RDS',
    tradeoff: 'Requires capacity governance across teams',
    interview: 'Compute max pods given DB max_connections',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-kafka-no-batch',
    title: 'Kafka without batching',
    problem: 'Produce/consume one record per DB round trip',
    bad: 'flush every send; listener processes singly with sync commit',
    whySlow: 'Throughput capped by RTT; lag grows',
    good: 'linger.ms/batch.size; consumer batch + transactional outbox',
    whyFaster: 'Amortize network and DB overhead',
    tradeoff: 'Slightly higher produce latency; harder error handling',
    interview: 'How does ack mode interact with batching?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
  {
    id: 'ba-bad-serialization',
    title: 'Bad serialization',
    problem: 'Reflection-heavy or chatty serializers on hot path',
    bad: 'Default Jackson on giant graphs; Java serialization',
    whySlow: 'CPU and alloc dominate profiles',
    good: 'Afterburner/record DTOs, slim models, binary codecs',
    whyFaster: 'Lower CPU per message; less GC',
    tradeoff: 'Schema evolution discipline',
    interview: 'How do you prove serializer cost in JFR?',
    validate: 'Same load profile; prove P95/P99 and errors improved; watch related saturation.',
  },
];
