/** Interview Q bank — Question → Short → Why → Real-world example. */

export type CapBankQ = {
  id: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  question: string;
  short: string;
  why: string;
  example: string;
};

export const CAP_BANK: CapBankQ[] = [
  {
    id: 'b1',
    level: 'Beginner',
    question: 'What is CAP theorem?',
    short:
      'In a partitioned distributed data system, you cannot simultaneously guarantee strong Consistency and Availability.',
    why: 'When nodes cannot communicate, they cannot both always answer and always agree on one latest value.',
    example: 'Bangalore and Mumbai payment replicas cut off — debit must reject (CP) or accept locally (AP).',
  },
  {
    id: 'b2',
    level: 'Beginner',
    question: 'What does C mean in CAP?',
    short: 'Successful reads reflect the latest successful write under the consistency contract (strong/linearizable sense).',
    why: 'Without C, two clients can see conflicting balances after a write.',
    example: 'Write ₹500 on A; a read on B must not return ₹1000 if you claimed strong C.',
  },
  {
    id: 'b3',
    level: 'Beginner',
    question: 'What does A mean in CAP?',
    short: 'Every non-failing node returns a non-error response for requests it receives.',
    why: 'CAP availability is response semantics under partition — not an uptime marketing SLA.',
    example: 'Node A still returns 200 with a balance even though it cannot reach Node B.',
  },
  {
    id: 'b4',
    level: 'Beginner',
    question: 'What is a network partition?',
    short: 'Nodes are alive but cannot reliably communicate (lost/delayed messages).',
    why: 'This is the failure mode CAP analyzes — not total node death.',
    example: 'Cross-AZ fiber cut: both DBs up, replication channel down.',
  },
  {
    id: 'b5',
    level: 'Beginner',
    question: 'Why is partition tolerance important?',
    short: 'Real networks fail; multi-AZ/region systems must keep operating somehow when links break.',
    why: 'If you ignore P, your design assumes a single failure domain that does not exist in the cloud.',
    example: 'AWS AZ isolation — design for the cut, not hope it never happens.',
  },
  {
    id: 'i1',
    level: 'Intermediate',
    question: 'Why is CAP really a C vs A choice?',
    short: 'For distributed multi-node systems, P is effectively required; during a partition you trade C against A.',
    why: 'You cannot freely drop P without becoming a single-node (or single-failure-domain) system.',
    example: 'Payment cluster: when the link breaks, 503 (CP) or local accept (AP).',
  },
  {
    id: 'i2',
    level: 'Intermediate',
    question: 'What is CP?',
    short: 'Prefer Consistency + Partition tolerance: refuse/wait rather than return possibly wrong data.',
    why: 'Protects invariants like “money does not invent itself”.',
    example: 'ATM withdraw returns unavailable when quorum cannot be reached.',
  },
  {
    id: 'i3',
    level: 'Intermediate',
    question: 'What is AP?',
    short: 'Prefer Availability + Partition tolerance: keep answering; reconcile later (eventual consistency).',
    why: 'User continuity matters more than instant global agreement for that data.',
    example: 'Like counters still increment locally during a regional split.',
  },
  {
    id: 'i4',
    level: 'Intermediate',
    question: 'Why isn’t “pick any two” completely accurate?',
    short: 'It suggests a permanent design-time menu; practically you assume P and choose C vs A under partition.',
    why: 'CA without P is mostly the single-node case, not how multi-region systems work.',
    example: 'Saying “we chose CA for our multi-region bank” is an interview red flag.',
  },
  {
    id: 'i5',
    level: 'Intermediate',
    question: 'Give a real-world CP example.',
    short: 'Ledger debit / seat reservation / distributed lock coordination under partition.',
    why: 'Double-spend or double-book costs more than a temporary error.',
    example: 'ZooKeeper/etcd leader election; quorum debit on payment balance.',
  },
  {
    id: 'i6',
    level: 'Intermediate',
    question: 'Give a real-world AP example.',
    short: 'Social likes, product catalog browse, analytics counters, some shopping-cart drafts.',
    why: 'Brief staleness is acceptable; rejecting the feature feels broken.',
    example: 'Cassandra CL=ONE for a feed metric; heal with read repair later.',
  },
  {
    id: 'i7',
    level: 'Intermediate',
    question: 'What happens during a network partition?',
    short: 'Live nodes must either refuse some ops (CP) or proceed with possible divergence (AP).',
    why: 'Without communication they cannot both always answer and always agree.',
    example: 'Node A shows ₹200 after debit; Node B still shows ₹1000 until heal.',
  },
  {
    id: 'a1',
    level: 'Advanced',
    question: 'CAP vs ACID?',
    short: 'CAP is about distributed guarantees under partition; ACID is about local transactional properties.',
    why: 'Same word “consistency” — different contracts. Confusing them is a classic trap.',
    example: 'SERIALIZABLE txn on a lagging replica can satisfy ACID locally while violating CAP-C globally.',
  },
  {
    id: 'a2',
    level: 'Advanced',
    question: 'CAP vs PACELC?',
    short: 'CAP covers the partition fork; PACELC adds latency vs consistency when the system is healthy.',
    why: 'Even without a partition, sync replication trades latency for stronger C.',
    example: 'Healthy multi-region: sync commit (C, higher L) vs async (lower L, weaker C).',
  },
  {
    id: 'a3',
    level: 'Advanced',
    question: 'What is quorum?',
    short: 'Require acknowledgment from W replicas on write and R on read, often with W+R > N.',
    why: 'Overlapping sets increase the chance a read sees the latest write.',
    example: 'N=3, W=2, R=2 for a balance key.',
  },
  {
    id: 'a4',
    level: 'Advanced',
    question: 'What are R and W?',
    short: 'R = read quorum size; W = write quorum size in an N-replica group.',
    why: 'Tuning R/W slides the op toward stronger C or higher A/lower latency.',
    example: 'W=1 favors fast writes (weaker C); W=majority favors stronger C.',
  },
  {
    id: 'a5',
    level: 'Advanced',
    question: 'Does quorum eliminate CAP?',
    short: 'No. Quorum shapes the trade-off; it does not repeal the partition fork.',
    why: 'If a majority is unreachable, quorum CP ops fail — that is the availability cost.',
    example: 'Minority AZ cannot form W=2 of 3 → writes time out (CP behavior).',
  },
  {
    id: 'a6',
    level: 'Advanced',
    question: 'Can a system be both strongly consistent and highly available?',
    short: 'Not with CAP’s strong definitions during a partition across the relevant nodes.',
    why: 'You can be highly available in the SLA sense while rejecting minority partitions.',
    example: 'Primary region serves; secondary returns 503 — “available” overall, not CAP-A on every node.',
  },
  {
    id: 'a7',
    level: 'Advanced',
    question: 'How would you design a payment system under CAP constraints?',
    short: 'Strong path for authorize/debit (quorum/CP-leaning); AP for receipts/notifications; idempotent keys everywhere.',
    why: 'Different data domains have different failure costs inside one product.',
    example: 'Debit needs quorum; email “payment received” can be eventually consistent.',
  },
  {
    id: 'a8',
    level: 'Advanced',
    question: 'How would you handle duplicate payments?',
    short: 'Idempotency keys + conditional ledger updates; never “sum duplicates” on merge.',
    why: 'Retries and partitions create duplicates; merge-add invents money.',
    example: 'toMap(idemKey, keep-first) or DB unique constraint on payment_id.',
  },
  {
    id: 'a9',
    level: 'Advanced',
    question: 'How does Kafka affect consistency?',
    short: 'Producer acks, ISR, and consumer offsets define durability/ordering — not a single CAP stamp.',
    why: 'acks=all + min ISR leans safer; acks=1 risks loss under broker failure.',
    example: 'Payment events: acks=all, idempotent producer, transactional outbox.',
  },
  {
    id: 'a10',
    level: 'Advanced',
    question: 'How does eventual consistency work?',
    short: 'Accept locally, replicate asynchronously, converge via anti-entropy/repair when updates stop.',
    why: 'Trades immediate agreement for availability and lower coordination latency.',
    example: 'AP withdraw on A; after heal, B catches up to ₹200.',
  },
  {
    id: 'a11',
    level: 'Advanced',
    question: 'How do you handle conflicts after a partition?',
    short: 'Domain rules: LWW, version vectors, CRDTs, or human/compensating workflows — pick by invariant.',
    why: 'AP writes create divergent histories that must reconcile.',
    example: 'Inventory: cancel one of two accepted orders; counters: CRDT sum.',
  },
  {
    id: 'a12',
    level: 'Advanced',
    question: 'How would you design inventory under partition?',
    short: 'Browse AP; hard reserve/unique SKU CP or lease with fencing; compensate oversell explicitly.',
    why: 'Oversell may be business-acceptable for soft goods, unacceptable for last concert seat.',
    example: 'Seat S1: compare-and-set qty 1→0 with quorum; else 503.',
  },
  {
    id: 'a13',
    level: 'Advanced',
    question: 'How would you choose consistency for different microservices?',
    short: 'Per aggregate/API: ask cost of stale vs cost of downtime; document SLOs and conflict policy.',
    why: 'One org-wide CP or AP stamp fights the product.',
    example: 'Cart soft AP; inventory reserve CP; notification AP; FX rates near-real-time with TTL.',
  },
];
