import type {TocItem} from './types';

export const CAP_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview'},
  {id: 'fundamentals', label: '01. CAP fundamentals'},
  {id: 'consistency', label: '02. Consistency (CAP C)'},
  {id: 'availability', label: '03. Availability (CAP A)'},
  {id: 'partition', label: '04. Partition tolerance'},
  {id: 'tradeoff', label: '05. Core C vs A trade-off'},
  {id: 'pick-two', label: '06. Not “pick any two”'},
  {id: 'normal-vs-partition', label: '07. Normal vs partition'},
  {id: 'cp', label: '08. CP systems'},
  {id: 'ap', label: '09. AP systems'},
  {id: 'ca', label: '10. CA systems'},
  {id: 'triangle', label: '11. CAP triangle (misleading)'},
  {id: 'pacelc', label: '12. CAP vs PACELC'},
  {id: 'acid', label: '13. CAP vs ACID'},
  {id: 'base', label: '14. CAP vs BASE'},
  {id: 'strong', label: '15. Strong consistency models'},
  {id: 'eventual', label: '16. Eventual consistency'},
  {id: 'models', label: '17. Consistency model ladder'},
  {id: 'quorum', label: '18. Quorum N/W/R'},
  {id: 'quorum-fail', label: '19. Quorum failure scenarios'},
  {id: 'leader', label: '20. Leader replication'},
  {id: 'consensus', label: '21. Consensus and CAP'},
  {id: 'split-brain', label: '22. Split brain'},
  {id: 'partition-scenarios', label: '23. Partition scenarios'},
  {id: 'microservices', label: '24. Microservices'},
  {id: 'databases', label: '25. Database selection'},
  {id: 'kafka', label: '26. Kafka'},
  {id: 'redis', label: '27. Redis'},
  {id: 'dynamodb', label: '28. DynamoDB'},
  {id: 'cassandra', label: '29. Cassandra'},
  {id: 'mongodb', label: '30. MongoDB'},
  {id: 'xa', label: '31. Distributed transactions'},
  {id: 'saga', label: '32. Saga pattern'},
  {id: 'caching', label: '33. Caching'},
  {id: 'locks', label: '34. Distributed locking'},
  {id: 'discovery', label: '35. Service discovery'},
  {id: 'dns-cdn', label: '36. DNS / CDN'},
  {id: 'multi-region', label: '37. Multi-region'},
  {id: 'rpo-rto', label: '38. RPO / RTO'},
  {id: 'routing', label: '39. Read/write routing'},
  {id: 'api', label: '40. API design'},
  {id: 'idempotency', label: '41. Idempotency'},
  {id: 'exactly-once', label: '42. Exactly-once'},
  {id: 'failure-handling', label: '43. Failure handling'},
  {id: 'observability', label: '44. Observability'},
  {id: 'design-examples', label: '45. System design examples'},
  {id: 'design-qs', label: '46. Design interview Qs'},
  {id: 'traps', label: '47. Interview traps'},
  {id: 'formal', label: '48. Formal intuition'},
  {id: 'linearizability', label: '49. CAP vs linearizability'},
  {id: 'sla', label: '50. CAP A vs SLA uptime'},
  {id: 'matrix', label: '51. Decision matrix'},
  {id: 'patterns', label: '52. Architecture patterns'},
  {id: 'hybrid', label: '53. Hybrid systems'},
  {id: 'framework', label: '54. Interview framework'},
  {id: 'spoken', label: '55–57. 60s / 2m / Staff answers'},
  {id: 'rapid', label: '58. Rapid-fire'},
  {id: 'predict', label: '59. Predict behavior'},
  {id: 'pseudocode', label: '60. Pseudocode exercises'},
  {id: 'incidents', label: '61. Production incidents'},
  {id: 'diagrams', label: '62. Architecture diagrams'},
  {id: 'tech-map', label: '63. Technology mapping'},
  {id: 'senior-tradeoffs', label: '64. Senior trade-off Qs'},
  {id: 'cheatsheet', label: '65. Cheat sheet'},
  {id: 'checklist', label: '66. Coverage checklist'},
  {id: 'interview', label: 'Interview mode'},
];

export const MEMORY_SENTENCE =
  'During a partition you choose Consistency or Availability — P is not optional in real distributed systems. CAP ≠ pick any two. CAP C ≠ ACID C. Prefer PACELC for the no-partition case. Never stamp a product permanently CP/AP without config.';

export const VERSION_NOTE =
  'CAP + PACELC + consistency models interview board for Senior/Staff/Principal system design. Related: /distributed-locking · /kafka-interview · /microservices-patterns · /distributed-caching · /system-design.';
