spring:
  config:
    activate:
      on-profile: redis
  autoconfigure:
    exclude: []
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms

app:
  lock:
    redis-enabled: true
