services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: multitenant
      POSTGRES_USER: mt
      POSTGRES_PASSWORD: mt
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mt -d multitenant"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://127.0.0.1:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: multitenant-lab-cluster

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: multitenant
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    depends_on:
      - kafka

  app:
    build: .
    ports:
      - "8096:8096"
    environment:
      SPRING_PROFILES_ACTIVE: infra
      MT_DB_URL: jdbc:postgresql://postgres:5432/multitenant
      MT_DB_USER: mt
      MT_DB_PASSWORD: mt
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP: kafka:19092
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
