server:
  port: 8082

spring:
  application:
    name: client-app
  security:
    oauth2:
      client:
        registration:
          web-client:
            provider: auth-server
            client-id: web-client
            client-secret: web-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,payment.read,payment.write,account.read,report.read
        provider:
          auth-server:
            issuer-uri: http://localhost:9000

app:
  resource-base-url: http://localhost:8081
