/** Interview cheat sheet — term → one-line memory hook. */
export const CHEAT_SHEET: string[][] = [
  ['HTTP', 'Stateless request/response over TCP — no encryption by default'],
  ['HTTPS', 'HTTP + TLS — encrypts wire, authenticates server (and optionally client)'],
  ['TLS 1.3', 'Modern handshake: 1-RTT, AEAD ciphers, no RSA key exchange'],
  ['mTLS', 'Both sides present X.509 certs — common for service-to-service'],
  ['Keystore', 'Private key + identity cert chain — "who I am"'],
  ['Truststore', 'Trusted CA / peer certs — "who I trust"'],
  ['keytool', 'JDK CLI for PKCS12/JKS import, export, list, genkeypair'],
  ['Symmetric', 'Same key encrypt/decrypt — AES-GCM for bulk data'],
  ['Asymmetric', 'Public encrypt/sign, private decrypt/verify — RSA/EC'],
  ['Hybrid', 'RSA/EC wrap AES key — TLS and field encryption pattern'],
  ['Hash', 'One-way digest — SHA-256; not reversible'],
  ['Encoding', 'Base64/hex — representation, not security'],
  ['Digital signature', 'Private sign, public verify — integrity + non-repudiation'],
  ['X.509', 'Standard cert format — subject, issuer, SAN, validity'],
  ['CA chain', 'Leaf → intermediate → root — trust anchor in truststore'],
  ['Authn', 'Who are you? — login, JWT, mTLS, API key'],
  ['Authz', 'What may you do? — roles, scopes, ABAC policies'],
  ['JWT', 'Signed (JWS) claims — readable; verify sig + exp + aud'],
  ['JWE', 'Encrypted JWT — hides claims from holder'],
  ['OAuth2', 'Delegated authorization framework — access tokens, scopes'],
  ['OIDC', 'OAuth2 + ID Token + /userinfo — identity layer'],
  ['PKCE', 'code_challenge for public clients — blocks auth code interception'],
  ['SAML', 'XML assertions via IdP redirect/POST — enterprise SSO'],
  ['RBAC', 'Role → permission mapping — ROLE_ADMIN, hasRole'],
  ['ABAC', 'Attribute/policy engine — tenant, amount, region rules'],
  ['Scope', 'OAuth fine-grained permission — payment:write'],
  ['Filter chain', 'Ordered SecurityFilterChain — auth before authorize'],
  ['CSRF', 'Forged cross-site POST with session cookie — token or SameSite'],
  ['CORS', 'Browser Origin policy — ACAO allowlist + preflight OPTIONS'],
  ['XSS', 'Inject script into page — escape output, CSP, HttpOnly cookies'],
  ['SQLi', 'Untrusted input in SQL — PreparedStatement / JPA params'],
  ['SSRF', 'Server fetches attacker URL — blocklist, no raw user URLs'],
  ['Replay', 'Reuse captured request — nonce, timestamp, idempotency key'],
  ['MITM', 'Intercept/modify traffic — TLS + cert pinning + HSTS'],
  ['Security headers', 'HSTS, CSP, X-Frame-Options, X-Content-Type-Options'],
  ['BCrypt/Argon2', 'Adaptive password hashing — never AES for passwords'],
  ['KMS', 'Cloud HSM-backed key service — envelope encryption, audit'],
  ['Secrets Manager', 'Rotating credentials store — DB passwords, API keys'],
  ['ACM', 'Managed TLS certs for ALB/CloudFront — auto renewal'],
  ['Kafka SASL', 'SCRAM/OAUTHBEARER — broker authentication'],
  ['Kafka ACL', 'Principal → topic/group permission — least privilege'],
  ['Rate limit', 'Token bucket / sliding window — 429 + Retry-After'],
  ['DDoS', 'Volumetric vs app-layer — CDN/WAF + RL + circuit break'],
  ['Zero Trust', 'Never trust network location — verify every request'],
  ['Observability', 'Audit auth denials, cert expiry, anomaly alerts'],
  ['Idempotency-Key', 'Safe payment retries — same key → same outcome'],
  ['JWKS', '/oauth2/jwks — public keys for JWT signature verify'],
  ['Bearer', 'Authorization: Bearer <token> — OAuth/JWT APIs'],
  ['Session', 'Server-side state + JSESSIONID cookie — CSRF relevant'],
  ['SameSite', 'Cookie attribute — Lax/Strict reduces CSRF'],
  ['WAF', 'Edge exploit filter — SQLi/XSS patterns at CDN'],
  ['API Gateway', 'North-south policy — JWT, RL, TLS termination'],
  ['Defense in depth', 'Edge + service + DB layers — never one gate'],
  ['Fail closed', 'Auth/validation error → deny, not bypass'],
  ['Fail open', 'Dangerous — allow traffic when IdP down'],
  ['Principal', 'Authenticated identity in SecurityContext'],
  ['GrantedAuthority', 'ROLE_* or SCOPE_* — used in hasAuthority'],
  ['@PreAuthorize', 'Method-level SpEL authz — runs after filter chain'],
  ['Resource server', 'Validates JWT/access token — stateless API'],
  ['Auth server', 'Issues codes/tokens — :9000 in oauth-jwt-demo'],
  ['Client credentials', 'Machine-to-machine OAuth — no user consent'],
  ['Authorization code', 'Browser redirect flow — most secure for SPAs with PKCE'],
  ['Refresh token', 'Long-lived opaque token — rotate on use, store hashed'],
  ['CORS preflight', 'OPTIONS before cross-origin mutating request'],
  ['Invalid CORS', 'Spring 403 when Origin not in allowlist'],
  ['Invalid CSRF', 'Spring 403 when session POST lacks token'],
  ['401 vs 403', '401 not authenticated · 403 authenticated but forbidden'],
  ['TLS termination', 'LB decrypts — re-encrypt east-west or use mTLS behind'],
  ['Envelope encryption', 'DEK encrypts data, KMS encrypts DEK'],
  ['Field encryption', 'AES-GCM column-level — survives DB backup exposure'],
  ['HMAC', 'Keyed hash — lookup tokens without storing plaintext'],
  ['Certificate pinning', 'App trusts only known pub key — mobile/API clients'],
  ['HSTS', 'Force HTTPS — max-age + includeSubDomains'],
  ['CSP', 'Content-Security-Policy — block inline script injection'],
  ['Actuator exposure', 'Lock /actuator/** — health only publicly'],
  ['PCI scope', 'Card data boundaries — tokenize, segment network'],
];
