export type ComparisonTable = {title: string; headers: string[]; rows: string[][]};

export const COMPARISON_TABLES: ComparisonTable[] = [
  {
    title: 'HTTP vs HTTPS',
    headers: ['Aspect', 'HTTP', 'HTTPS'],
    rows: [
      ['Port default', '80', '443'],
      ['Encryption', 'None — plaintext on wire', 'TLS — ciphertext + integrity'],
      ['Server identity', 'None', 'X.509 certificate verified by client'],
      ['MITM risk', 'High on untrusted networks', 'Low if cert + hostname verified'],
      ['Spring config', 'server.port: 8080', 'server.ssl.enabled: true + keystore'],
      ['Production', 'Never for auth/data', 'Always — HSTS at edge'],
    ],
  },
  {
    title: 'TLS vs mTLS',
    headers: ['Aspect', 'TLS (1-way)', 'mTLS (2-way)'],
    rows: [
      ['Client cert', 'Not required', 'Required (client-auth: need)'],
      ['Server cert', 'Required', 'Required'],
      ['Typical use', 'Browser → API, public HTTPS', 'Service → service, Kafka, mesh'],
      ['Spring Boot', 'server.ssl.enabled: true', '+ client-auth: need + trust-store'],
      ['Identity proof', 'Server only', 'Both peers'],
      ['Ops burden', 'ACM/Let\'s Encrypt at edge', 'Per-service cert rotation + trust bundles'],
    ],
  },
  {
    title: 'Keystore vs Truststore',
    headers: ['Aspect', 'Keystore', 'Truststore'],
    rows: [
      ['Contains', 'Private key + own cert chain', 'Trusted CA / peer public certs'],
      ['Password', 'key-store-password', 'trust-store-password'],
      ['Spring property', 'server.ssl.key-store', 'server.ssl.trust-store'],
      ['Analogy', 'Your passport + signing key', 'List of embassies you trust'],
      ['Leak impact', 'Critical — impersonation', 'Lower — no private key'],
      ['keytool', '-genkeypair → keystore', '-importcert CA → truststore'],
    ],
  },
  {
    title: 'JWT vs SAML',
    headers: ['Aspect', 'JWT (JWS)', 'SAML 2.0'],
    rows: [
      ['Format', 'Compact JSON base64url', 'XML assertion'],
      ['Transport', 'Bearer header, URL fragment', 'Browser POST/redirect binding'],
      ['Mobile/SPA', 'Native fit + OIDC', 'Heavier — often via broker'],
      ['Validation', 'JWKS sig + exp + aud', 'XML sig + IdP metadata'],
      ['Spring', 'oauth2ResourceServer().jwt()', 'spring-security-saml2-service-provider'],
      ['Enterprise', 'Growing — Okta/Azure AD OIDC', 'Legacy AD FS, banks, gov'],
    ],
  },
  {
    title: 'OAuth2 vs OIDC',
    headers: ['Aspect', 'OAuth 2.0', 'OpenID Connect'],
    rows: [
      ['Purpose', 'Authorization — access token', 'Authentication + authorization'],
      ['ID Token', 'Not defined', 'JWT with sub, iss, aud, nonce'],
      ['User info', 'Optional proprietary', 'Standard /userinfo + claims'],
      ['Discovery', 'Per-provider docs', '/.well-known/openid-configuration'],
      ['Spring', 'oauth2Client + resourceServer', '+ oidcUserService for login'],
      ['Interview', '"OAuth tells what you can access"', '"OIDC tells who you are"'],
    ],
  },
  {
    title: 'RBAC vs ABAC',
    headers: ['Aspect', 'RBAC', 'ABAC'],
    rows: [
      ['Model', 'Role → permissions', 'Attributes + policy rules'],
      ['Spring', 'hasRole("ADMIN")', '@PreAuthorize + custom PermissionEvaluator'],
      ['Example', 'ROLE_TELLER sees accounts', 'teller + branch=NY + amount<10k'],
      ['Change cost', 'Add role matrix rows', 'Update policy engine rules'],
      ['Scale', 'Simple teams', 'Multi-tenant fintech, fine-grained'],
      ['OAuth mapping', 'groups → ROLE_*', 'scopes + custom claims'],
    ],
  },
  {
    title: 'CSRF vs CORS',
    headers: ['Aspect', 'CSRF', 'CORS'],
    rows: [
      ['Threat', 'Forged request with victim cookie', 'Cross-origin read/write policy'],
      ['Enforced by', 'Server validates token', 'Browser blocks response'],
      ['Affects', 'Cookie/session auth', 'Any cross-origin fetch/XHR'],
      ['JWT API', 'Usually disabled (stateless)', 'Still needed for browser SPAs'],
      ['Spring fix', 'CsrfFilter + _csrf token', 'CorsConfigurationSource allowlist'],
      ['Lab ports', 'spring-csrf-demo :8090', 'spring-cors-demo :8091'],
    ],
  },
  {
    title: 'Authn vs Authz',
    headers: ['Aspect', 'Authentication', 'Authorization'],
    rows: [
      ['Question', 'Who are you?', 'What may you do?'],
      ['HTTP code', '401 Unauthorized', '403 Forbidden'],
      ['Spring', 'AuthenticationManager, JwtDecoder', 'authorizeHttpRequests, @PreAuthorize'],
      ['Failure', 'Bad password / expired JWT', 'Valid user, wrong role/scope'],
      ['Order', 'Always first in filter chain', 'After authenticated Principal exists'],
      ['Demo', 'POST /api/auth/login :8092', 'GET /api/admin/users (ADMIN)'],
    ],
  },
  {
    title: 'Symmetric vs Asymmetric',
    headers: ['Aspect', 'Symmetric (AES)', 'Asymmetric (RSA/EC)'],
    rows: [
      ['Keys', 'One shared secret', 'Public + private key pair'],
      ['Speed', 'Fast — bulk data', 'Slow — key wrap / signatures only'],
      ['Key distribution', 'Hard — must share secret safely', 'Public key is publishable'],
      ['Use case', 'Field encryption, TLS record layer', 'TLS handshake, JWT RS256, signatures'],
      ['Spring', 'SecretKey + Cipher AES/GCM', 'KeyPair + RSA/ECDSA'],
      ['Lab', 'POST /api/crypto/encrypt :8093', 'POST /api/crypto/hybrid :8093'],
    ],
  },
  {
    title: 'Hash vs Encrypt vs Encode',
    headers: ['Aspect', 'Hash (SHA-256)', 'Encrypt (AES)', 'Encode (Base64)'],
    rows: [
      ['Reversible', 'No', 'Yes (with key)', 'Yes (no key)'],
      ['Purpose', 'Integrity / fingerprint', 'Confidentiality', 'Transport representation'],
      ['Passwords', 'Use bcrypt/Argon2 not SHA alone', 'Never', 'Never'],
      ['Lookup token', 'HMAC-SHA256', 'AES-GCM field', 'Not for secrets'],
      ['Interview trap', '"We hashed with Base64"', 'Key in source code', 'Security through obscurity'],
    ],
  },
  {
    title: 'KMS vs Secrets Manager',
    headers: ['Aspect', 'AWS KMS', 'AWS Secrets Manager'],
    rows: [
      ['Primary job', 'Encrypt/decrypt with CMK — envelope', 'Store + rotate credentials'],
      ['Typical payload', 'DEK, small blobs', 'DB password, API key JSON'],
      ['Rotation', 'Manual CMK alias re-key', 'Automatic secret rotation Lambda'],
      ['Audit', 'CloudTrail every Decrypt', 'GetSecretValue events'],
      ['Spring', 'AWS SDK + EncryptionSDK', 'spring-cloud-aws-secrets-manager'],
      ['Cost model', 'Per API call + key/month', 'Per secret/month + API'],
    ],
  },
  {
    title: 'Session vs JWT',
    headers: ['Aspect', 'Server session', 'JWT (stateless)'],
    rows: [
      ['State', 'Server store / Redis', 'Claims in token — optional blocklist'],
      ['Logout', 'Invalidate session', 'Short TTL + refresh rotation / denylist'],
      ['CSRF', 'Required for cookie auth', 'Usually off for pure Bearer API'],
      ['Scale', 'Sticky session or shared store', 'Horizontally easy — verify sig only'],
      ['Spring demo', 'spring-auth-demo :8080', 'spring-jwt-demo :8092'],
      ['Secret leak', 'Session ID replay until expiry', 'Forge tokens if signing key leaked'],
    ],
  },
  {
    title: '401 vs 403 vs 419',
    headers: ['Code', 'Meaning', 'Spring trigger'],
    rows: [
      ['401', 'Not authenticated', 'No/invalid Bearer, expired JWT'],
      ['403', 'Authenticated but denied', 'hasRole fails, CSRF invalid, CORS blocked'],
      ['419', 'Non-standard — session expired (Laravel)', 'Use 401 + problem detail in Spring'],
      ['429', 'Rate limited', 'BucketLimiter / Gateway throttle'],
      ['Fix 401', 'Login / refresh token', '—'],
      ['Fix 403', 'Grant role/scope or fix CSRF/CORS', '—'],
    ],
  },
  {
    title: 'WAF vs API Gateway vs mTLS',
    headers: ['Layer', 'WAF', 'API Gateway', 'mTLS'],
    rows: [
      ['Focus', 'Exploit signatures', 'API policy (JWT, RL, route)', 'Transport peer identity'],
      ['Placement', 'CloudFront/ALB edge', 'North-south entry', 'Every hop S2S'],
      ['Blocks', 'SQLi/XSS patterns', '429, bad JWT, wrong route', 'Unknown client cert'],
      ['Spring overlap', 'None in app', 'SCG or AWS APIGW', 'server.ssl.client-auth'],
      ['Complement', 'All three stack — not either/or', '—', '—'],
    ],
  },
  {
    title: 'BCrypt vs Argon2',
    headers: ['Aspect', 'BCrypt', 'Argon2id'],
    rows: [
      ['Memory hard', 'No', 'Yes — resists GPU/ASIC'],
      ['Spring', 'BCryptPasswordEncoder (default)', 'Argon2PasswordEncoder (custom)'],
      ['Parameters', 'strength (log rounds)', 'memory, iterations, parallelism'],
      ['Legacy', 'Ubiquitous — fine for most', 'Winner PHC — preferred greenfield'],
      ['Never', 'MD5/SHA1 for passwords', 'Reversible encryption for passwords'],
    ],
  },
];
