import Link from 'next/link';
import {ArrowRight, BookOpen, Layers3, Server, Database, MessageSquare, Zap} from 'lucide-react';
import {getAllPosts} from '@/lib/posts';
import {hrefForPost} from '@/lib/href';
const starts=[
  ['Master Index','FAANG Staff/Principal curriculum map, study order and design portfolio.','/system-design/system-design-master-index'],
  ['Interview Preparation','Step-by-step framework for requirements, HLD, LLD, trade-offs and common designs.','/system-design/system-design-interview-preparation'],
  ['30-Day Plan','Focused month of designs, failure drills and estimation practice.','/system-design/30-day-system-design-plan'],
  ['Distributed Systems','Locking curriculum (Redis/Postgres/fencing) + replication, messaging, resilience.','/distributed-systems'],
  ['FinTech','Payments and correctness under retries and uncertainty.','/fintech'],
  ['Behavior','Ownership, conflict, leadership and stakeholder stories.','/behavior'],
  ['Behavioral Interview','Staff+/Principal STAR bank — leadership & business impact.','/behavioral-interview'],
  ['Leadership Principles','All 16 Amazon LPs with STAR answers and Kafka follow-ups.','/leadership-principles'],
  ['Complexity','Master guide: derive Big-O from Java code — DS, graphs, DP, practice.','/complexity'],
  ['Kafka Interview','Staff+/Principal Kafka — 130+ failure & design questions.','/kafka-interview'],
  ['Redis Interview','Staff+/Principal Redis — internals, HA, cache failures, locks.','/redis-interview'],
  ['Real-Time Issues','Stuck threads, dumps, DB locks, API hangs — Principal on-call playbooks.','/realtime-issues'],
];
const startIcons=[BookOpen,Layers3,Server,Zap,Database,MessageSquare,MessageSquare,Layers3,BookOpen,Server,Database,Zap];
export default function Home(){
  const all=getAllPosts();
  const prep=all.find(p=>p.slug==='system-design-interview-preparation');
  const posts=[...(prep?[prep]:[]),...all.filter(p=>p.slug!=='system-design-interview-preparation')];
  return <main><section className="border-b bg-white"><div className="mx-auto max-w-7xl px-5 py-20 md:py-24"><div className="max-w-4xl"><div className="mb-4 text-xs font-black uppercase tracking-[.18em] text-blue-600">System Design Interview Hub</div><h1 className="text-5xl font-black tracking-[-.055em] md:text-7xl">Learn system design through real-world architecture, stories & diagrams.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Understand how experienced engineers approach scalable, reliable and distributed systems — from requirements and estimation to bottlenecks, trade-offs and Staff-level follow-ups.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/learn" className="rounded-lg bg-slate-900 px-5 py-3 text-sm font-bold text-white">Start Learning <ArrowRight className="ml-2 inline" size={16}/></Link><Link href="/system-design" className="rounded-lg border px-5 py-3 text-sm font-bold">Explore System Designs</Link></div></div><div className="mt-10 flex flex-wrap gap-5 text-sm text-slate-500"><span><b className="text-slate-900">Vibhu Agarwal</b> · Senior Software Engineer</span><span>Java · Distributed Systems · Microservices · FinTech</span></div></div></section><section className="mx-auto max-w-7xl px-5 py-16"><div className="mb-8"><div className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Start Here</div><h2 className="mt-2 text-3xl font-black tracking-tight">Build your system-design foundation</h2></div><div className="grid gap-4 md:grid-cols-3">{starts.map(([t,d,u],i)=>{const Icon=startIcons[i]??BookOpen;return <Link href={u} key={t} className="card p-6 transition hover:-translate-y-1"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100 text-slate-700"><Icon size={19}/></div><h3 className="font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></Link>})}</div></section><section className="mx-auto max-w-7xl px-5 pb-16"><div className="mb-8 flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Featured</div><h2 className="mt-2 text-3xl font-black tracking-tight">Popular system-design problems</h2></div><Link href="/system-design" className="hidden text-sm font-bold text-blue-600 md:block">View all →</Link></div><div className="grid gap-4 md:grid-cols-3">{posts.slice(0,6).map(p=><Link href={hrefForPost(p.category,p.slug)} key={p.slug} className="card p-6"><div className="text-[10px] font-black uppercase tracking-wider text-blue-600">{p.category} · {p.difficulty}</div><h3 className="mt-3 text-xl font-bold">{p.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{p.description}</p><div className="mt-4 text-xs text-slate-400">{p.readingTime} · {p.tags.slice(0,3).join(' · ')}</div></Link>)}</div></section></main>}