export type PatternRevisionCard = {
  name:string;
  category:'Creational'|'Structural'|'Behavioral';
  rememberAs:string;
  whenToUse:string;
  whenNotToUse:string;
  interviewTrap:string;
  springBootExample:string;
};

export const DESIGN_PATTERN_REVISION_CARDS:PatternRevisionCard[]=[
  {name:'Singleton',category:'Creational',rememberAs:'One shared instance',whenToUse:'You need one shared stateless configuration/cache-style object per application context.',whenNotToUse:'When lifecycle should be container-managed or when hidden global state will hurt tests.',interviewTrap:'Saying Singleton is always good because it saves memory.',springBootExample:'Default singleton-scoped Spring beans.'},
  {name:'Factory Method',category:'Creational',rememberAs:'Choose implementation',whenToUse:'Object type changes by provider, region, payment method, or environment.',whenNotToUse:'When one direct constructor is already obvious and stable.',interviewTrap:'Confusing factory with builder.',springBootExample:'Conditional bean creation and factory-style service selection.'},
  {name:'Abstract Factory',category:'Creational',rememberAs:'Create families together',whenToUse:'A region or product pack must create matching related services.',whenNotToUse:'If only one object varies and there is no family compatibility concern.',interviewTrap:'Using it where simple factory method is enough.',springBootExample:'Environment-specific bundles of beans created together.'},
  {name:'Builder',category:'Creational',rememberAs:'Assemble complex object',whenToUse:'The object has many optional fields and construction readability matters.',whenNotToUse:'For tiny immutable objects with 2-3 fields.',interviewTrap:'Using builder to hide weak object design.',springBootExample:'Complex request/config objects built before service calls.'},
  {name:'Prototype',category:'Creational',rememberAs:'Clone template',whenToUse:'Base object creation is expensive and you need many variations.',whenNotToUse:'If copying creates identity confusion or deep-copy complexity is high.',interviewTrap:'Forgetting shallow vs deep copy discussion.',springBootExample:'Cloning report/job configuration templates before customization.'},
  {name:'Adapter',category:'Structural',rememberAs:'Translate APIs',whenToUse:'An old SDK or third-party contract does not match your internal interface.',whenNotToUse:'If you control both sides and can align the contract directly.',interviewTrap:'Calling every wrapper an adapter.',springBootExample:'Wrapping legacy REST/SOAP/vendor SDK clients.'},
  {name:'Bridge',category:'Structural',rememberAs:'Separate two dimensions',whenToUse:'Two independent axes vary, like channel and provider.',whenNotToUse:'If there is only one axis of change.',interviewTrap:'Using inheritance until classes explode, then adding Bridge too late.',springBootExample:'Notification abstraction with pluggable provider implementations.'},
  {name:'Composite',category:'Structural',rememberAs:'Treat one and many uniformly',whenToUse:'You have trees like bundles, org hierarchies, or folders.',whenNotToUse:'If the structure is flat and will stay flat.',interviewTrap:'Ignoring aggregation recursion costs.',springBootExample:'Order bundles, menu trees, permission trees.'},
  {name:'Decorator',category:'Structural',rememberAs:'Add behavior at runtime',whenToUse:'You need logging, metrics, retry, fraud, masking, or enrichment layered around core logic.',whenNotToUse:'When behavior order is fixed and a simple orchestrator is enough.',interviewTrap:'Mixing it up with Proxy or AOP without explaining intent.',springBootExample:'Manual service wrappers around core payment processing.'},
  {name:'Facade',category:'Structural',rememberAs:'One simple entry point',whenToUse:'Clients should not orchestrate many subsystem calls themselves.',whenNotToUse:'If the facade becomes a giant god-service with unrelated responsibilities.',interviewTrap:'Calling any service class a facade.',springBootExample:'Application service orchestrating fraud, account, payment, audit, and notify.'},
  {name:'Flyweight',category:'Structural',rememberAs:'Share immutable small state',whenToUse:'Massive object counts share the same metadata.',whenNotToUse:'If state is mutable or object count is small.',interviewTrap:'Ignoring cache lifecycle and memory trade-offs.',springBootExample:'Currency/country/payment-type metadata caches.'},
  {name:'Proxy',category:'Structural',rememberAs:'Control access',whenToUse:'You need auth, cache, rate limit, lazy load, or interception before target invocation.',whenNotToUse:'When you actually mean adding business behavior composition.',interviewTrap:'Confusing Proxy with Decorator.',springBootExample:'Spring AOP, transaction proxies, method security proxies.'},
  {name:'Chain of Responsibility',category:'Behavioral',rememberAs:'Validation/filter pipeline',whenToUse:'Multiple handlers may approve, enrich, or reject sequentially.',whenNotToUse:'If the sequence is tiny and unlikely to grow.',interviewTrap:'Hiding control flow so deeply that debugging becomes painful.',springBootExample:'Spring Security filters and request validation pipelines.'},
  {name:'Command',category:'Behavioral',rememberAs:'Action as object',whenToUse:'You need queue, retry, audit, scheduling, or undo semantics.',whenNotToUse:'For one direct service call with no lifecycle.',interviewTrap:'Creating command classes with no independent value.',springBootExample:'Job submission, async task, payment action execution objects.'},
  {name:'Interpreter',category:'Behavioral',rememberAs:'Evaluate small rule language',whenToUse:'Business wants simple in-memory rule expressions.',whenNotToUse:'If rules are complex enough to justify an existing rules engine or query language.',interviewTrap:'Overbuilding a parser for a tiny requirement.',springBootExample:'Simple transaction rules and feature flag expressions.'},
  {name:'Iterator',category:'Behavioral',rememberAs:'Traverse without exposing storage',whenToUse:'Clients should iterate without knowing internal collection details.',whenNotToUse:'If returning a stream/list is already enough.',interviewTrap:'Using it manually when Java collections already solve the problem.',springBootExample:'Custom repositories or paged result traversal.'},
  {name:'Mediator',category:'Behavioral',rememberAs:'Centralize communication',whenToUse:'Too many services/components talk to each other directly.',whenNotToUse:'If the mediator would become a bottleneck or god-object.',interviewTrap:'Centralizing everything into one giant coordinator.',springBootExample:'Order workflow coordinators or saga orchestrator-style services.'},
  {name:'Memento',category:'Behavioral',rememberAs:'Save and restore snapshot',whenToUse:'You need rollback of configuration or draft workflow state.',whenNotToUse:'If object graphs are huge or snapshots are too expensive.',interviewTrap:'Ignoring snapshot versioning and mutation safety.',springBootExample:'Rollback of payment config or staged order edits.'},
  {name:'Observer',category:'Behavioral',rememberAs:'One event, many listeners',whenToUse:'Audit, notify, analytics, and reporting react to one business event.',whenNotToUse:'If strong ordering/transactional guarantees require a different design.',interviewTrap:'Not discussing delivery guarantees and listener failure handling.',springBootExample:'ApplicationEventPublisher, @EventListener, Kafka consumers.'},
  {name:'State',category:'Behavioral',rememberAs:'Lifecycle-specific behavior',whenToUse:'Behavior changes as object lifecycle changes and invalid transitions matter.',whenNotToUse:'If a tiny enum and one check are enough.',interviewTrap:'Confusing state transitions with strategy selection.',springBootExample:'Payment or order lifecycle management.'},
  {name:'Strategy',category:'Behavioral',rememberAs:'Swap algorithm',whenToUse:'One operation has multiple interchangeable algorithms.',whenNotToUse:'If the algorithm list is tiny and stable forever.',interviewTrap:'Forgetting who selects the strategy and why.',springBootExample:'Payment method processing, pricing policy selection, retry policy selection.'},
  {name:'Template Method',category:'Behavioral',rememberAs:'Fixed workflow, variable steps',whenToUse:'The overall workflow is stable but some steps differ.',whenNotToUse:'If inheritance harms flexibility more than it helps.',interviewTrap:'Forcing subclassing when composition would be simpler.',springBootExample:'Framework support classes and fixed processing skeletons.'},
  {name:'Visitor',category:'Behavioral',rememberAs:'Add operations to stable object structure',whenToUse:'Object structure is stable, but operations keep growing.',whenNotToUse:'If object types change frequently.',interviewTrap:'Using Visitor where simple polymorphism is enough.',springBootExample:'Account/report/audit calculations over stable domain object sets.'},
];
