import type {IQ} from './types';

function q(id: string, topic: string, question: string, answer: string): IQ {
  return {id, topic, question, answer};
}

export const INTERVIEW_40: IQ[] = [
  q('q1', 'Basics', 'What is Spring Cache?', 'An abstraction for applying caching to methods via annotations/AOP. It delegates storage to a CacheManager/provider — it is not itself a distributed cache.'),
  q('q2', 'Basics', 'Is Spring Cache distributed?', 'Only if the backend is (e.g. Redis). Caffeine/ConcurrentMap are local per JVM. Spring Cache does not make Caffeine shared across pods.'),
  q('q3', 'Basics', 'What is CacheManager?', 'SPI that creates/looks up named Cache instances. Beans: CaffeineCacheManager, RedisCacheManager, ConcurrentMapCacheManager, composite setups.'),
  q('q4', 'Providers', 'Caffeine vs Redis?', 'Caffeine: in-process, ultra-low latency, per-pod. Redis: shared, network hop, central memory, needs serialization and failure policy. Often L1 Caffeine + L2 Redis.'),
  q('q5', 'Annotations', '@Cacheable vs @CachePut?', '@Cacheable checks cache first and may skip the method. @CachePut always runs the method and updates the cache.'),
  q('q6', 'Annotations', '@CachePut vs @CacheEvict?', 'Put refreshes the cached value; Evict removes a key or allEntries so the next read reloads.'),
  q('q7', 'Annotations', 'condition vs unless?', 'condition is evaluated BEFORE the method (whether to use cache ops). unless AFTER (whether to store the result). Memory: condition BEFORE, unless AFTER.'),
  q('q8', 'Annotations', 'What is sync=true?', 'Synchronizes concurrent loads for the same key inside one JVM to reduce local stampedes. It does not lock across application instances.'),
  q('q9', 'Patterns', 'What is cache-aside?', 'Application checks cache, on miss loads DB, then puts into cache. Writes update DB then invalidate/update cache. Most common Spring pattern.'),
  q('q10', 'Patterns', 'Read-through vs cache-aside?', 'Read-through: cache layer loads data on miss. Cache-aside: application code loads. @Cacheable is closer to cache-aside via AOP.'),
  q('q11', 'Patterns', 'Write-through vs write-behind?', 'Write-through updates cache and DB synchronously. Write-behind writes cache then async DB — faster writes, risk of loss/eventual consistency.'),
  q('q12', 'TTL', 'What is TTL?', 'Time-to-live from write (expireAfterWrite / Redis EX). Entry expires after fixed duration from creation/update regardless of reads.'),
  q('q13', 'TTL', 'TTL vs TTI?', 'TTL = expire after write. TTI (expireAfterAccess) resets idle timer on each access. Hot keys live longer with TTI.'),
  q('q14', 'Algo', 'What is LRU?', 'Least Recently Used eviction — discard the entry not accessed for the longest time. LinkedHashMap accessOrder or HashMap+DLL for O(1).'),
  q('q15', 'Algo', 'What is LFU?', 'Least Frequently Used — discard lowest access-count entry. Needs frequency structures; good for stable popularity.'),
  q('q16', 'Algo', 'LRU vs LFU?', 'LRU favors recency; LFU favors lifetime popularity. Caffeine uses Window TinyLFU admission — do not say “Spring Cache is LRU”.'),
  q('q17', 'Failures', 'What is cache stampede?', 'Many concurrent misses on one expired hot key overload the DB. Also called thundering herd.'),
  q('q18', 'Failures', 'How prevent stampede?', 'sync=true locally; single-flight; distributed lock; soft TTL + background refresh; L1 shielding; probabilistic early expiration.'),
  q('q19', 'Failures', 'What is cache penetration?', 'Queries for missing keys bypass cache forever and hammer DB. Attackers can exploit random IDs.'),
  q('q20', 'Failures', 'How prevent penetration?', 'Negative caching with short TTL; Bloom filters; strict ID validation; WAF/rate limits.'),
  q('q21', 'Failures', 'What is cache avalanche?', 'Mass simultaneous expiry of many keys → DB overload. Fix with TTL jitter, staggered warmup, multi-level cache.'),
  q('q22', 'Failures', 'What is a hot key?', 'One key receives disproportionate traffic. Mitigate with local L1, replication, sharding, coalescing, CDN.'),
  q('q23', 'Distributed', 'How invalidate distributed caches?', 'Delete Redis key on write; pub/sub or Kafka to drop L1 on other pods; versioned keys; short TTL as backstop.'),
  q('q24', 'Distributed', 'How do instances share Redis?', 'All apps point at same Redis; identical key prefixes/serializers; careful multi-tenant key design.'),
  q('q25', 'Distributed', 'What if Redis goes down?', 'With fail-open CacheErrorHandler, fall back to DB (higher load). Fail-closed returns errors. Keep L1 if acceptable staleness.'),
  q('q26', 'Serialization', 'How serialize Redis values?', 'Prefer JSON (GenericJackson2JsonRedisSerializer) for evolvability; JDK serialization is brittle across versions. Version cache keys on breaking changes.'),
  q('q27', 'AOP', 'Why can @Cacheable fail on self-invocation?', 'Default proxy mode only intercepts external calls. this.method() skips the proxy — move method, self-inject, or AspectJ.'),
  q('q28', 'SPI', 'CacheManager vs CacheResolver?', 'cacheManager picks a fixed manager bean; CacheResolver dynamically chooses which Cache(s) to use per invocation.'),
  q('q29', 'SPI', 'What is KeyGenerator?', 'Strategy to build cache keys from method args when key SpEL is omitted. Custom generators add tenant/version prefixes.'),
  q('q30', 'Internal', 'How does Spring Cache work internally?', '@EnableCaching registers advisor; CacheInterceptor wraps calls; resolves caches; SpEL key; get→miss→invoke→put; handles put/evict ops.'),
  q('q31', 'Internal', 'Does Spring Cache use AOP?', 'Yes — typically JDK/CGLIB proxies. AspectJ mode available for broader interception.'),
  q('q32', 'Flow', 'What happens on cache miss?', 'Interceptor invokes target method, optionally stores result (unless/null rules), returns value. Metrics: miss + load time.'),
  q('q33', 'Flow', 'What happens on cache hit?', 'Cached value returned; method body skipped (for @Cacheable). Watch mutable cached objects shared across threads.'),
  q('q34', 'Null', 'Should we cache null?', 'Sometimes — short TTL negative cache vs penetration. Risk: hide newly inserted rows. Often disableCachingNullValues + Bloom.'),
  q('q35', 'Metrics', 'How monitor cache?', 'Caffeine recordStats; Spring Boot Actuator cache metrics; hit ratio = hits/(hits+misses); Redis INFO/latency; alert on miss storms.'),
  q('q36', 'TTL', 'How choose TTL?', 'Bound acceptable staleness; shorter for mutable data; jitter to avoid avalanche; measure refresh cost vs hit gain.'),
  q('q37', 'Consistency', 'How prevent stale data?', 'Evict/put on writes; short TTL; pub/sub invalidation; don’t cache strong-consistency money state without design.'),
  q('q38', 'L1L2', 'Design L1 + L2?', 'L1 Caffeine tiny/hot; L2 Redis shared; on miss cascade; on write invalidate both + broadcast L1 drop; monitor both hit ratios.'),
  q('q39', 'FinTech', 'Caching in high-scale finance?', 'Cache reference/instrument/config aggressively; balances/positions need careful TTL/invalidation or skip; never treat cache as ledger SoT; audit miss paths.'),
  q('q40', 'Design', 'When NOT to cache?', 'Write-heavy, strong consistency required, tiny QPS, unbounded key cardinality (user IDs with low reuse), sensitive data without controls.'),
  q('q41', 'Algo', 'Does Spring Cache implement LRU?', 'No. Eviction is provider-specific. Caffeine ≈ TinyLFU; Redis maxmemory-policy; ConcurrentMap often unbounded unless wrapped.'),
  q('q42', 'Tx', 'Transactional + @CacheEvict pitfalls?', 'Evict before rollback can drop good cache; prefer after-commit synchronization. Cache is derived data, not transactional SoT.'),
  q('q43', 'Keys', 'Multi-tenant cache keys?', 'Always include tenantId in key or KeyGenerator. Missing tenant → cross-tenant data leak via cache.'),
  q('q44', 'Warmup', 'How warm caches?', 'ApplicationReadyEvent or scheduled jobs load top-N; avoid blocking @PostConstruct for heavy IO; stagger TTLs.'),
  q('q45', 'Security', 'Cache security concerns?', 'No secrets/PII in clear Redis; AUTH/TLS/VPC; authorize before returning cached personalized data; tenant isolation in keys.'),
];
