import type {InterviewQ} from './types';

export const SENIOR: InterviewQ[] = [
  {id:'s1',topic:'Basics',question:'What is a Bloom Filter?',answer30s:'Probabilistic set-membership structure using a bit array and k hashes. false⇒absent; true⇒maybe.',answer2m:'Stores no keys. Insert sets k bits. Lookup checks those bits. Trades false positives for tiny memory. No false negatives for inserted elements in the classic structure.',followUps:['Analogy?'],trick:'Calling it an exact cache.'},
  {id:'s2',topic:'Basics',question:'Why can Bloom Filters have FPs but not FNs?',answer30s:'Bits only turn 1 on insert; collisions can make another key look present. A missing 0-bit proves absence.',answer2m:'We never clear bits on classic BF, so every inserted key keeps its k bits set. Another key may hash into already-set bits → FP. If any required bit is 0, that key could not have been inserted.',followUps:['What about deletes?'],trick:'Saying FNs are rare but possible in classic BF without races/deletes.'},
  {id:'s3',topic:'Delete',question:'Why can’t a normal Bloom Filter delete?',answer30s:'Clearing a shared bit can make another key look absent.',answer2m:'Alice and Bob may share bit 5. Clearing it for Alice creates a false negative for Bob. Counting BF increments/decrements counters instead.',followUps:['Counting BF memory cost?']},
  {id:'s4',topic:'Math',question:'How do you calculate size?',answer30s:'m≈−n ln(p)/(ln2)²; k≈(m/n)ln2.',answer2m:'Choose expected n and target FPP p. Larger n or smaller p → larger m. At 1% FPP expect ~10 bits/key. 1M keys ≈1.2MB.',followUps:['What if n is unknown?']},
  {id:'s5',topic:'Math',question:'How do you choose k?',answer30s:'k≈(m/n)ln2 — often 5–10 in practice.',answer2m:'Too few hashes → more FPs; too many → more CPU and denser bits also hurting FPP. Optimal balances both.',followUps:['Double hashing?']},
  {id:'s6',topic:'Compare',question:'Bloom Filter vs Redis Set?',answer30s:'Bloom is probabilistic tiny bits; Redis Set is exact keys over the network.',answer2m:'Use Bloom to avoid work; Redis Set when you need exact shared membership or deletes. Often compose: Bloom local, Redis exact.',followUps:['RedisBloom module?'],trick:'Replacing Redis Set with Bloom for sessions.'},
  {id:'s7',topic:'Compare',question:'Bloom Filter vs database index?',answer30s:'Index locates existing rows; Bloom accelerates “probably nonexistent” checks.',answer2m:'SELECT still needs B-Tree/hash index among real data. Bloom sits above to skip queries for garbage ids. It does not replace indexes.',followUps:['Where does each live in the stack?']},
  {id:'s8',topic:'Cache',question:'How do you use it for cache penetration?',answer30s:'On miss path, Bloom says definitely absent → 404 without Redis/DB.',answer2m:'Bots hammering random UUIDs never reach the database. Maybes still go Redis→DB. Measure blocked vs DB queries.',followUps:['Null-cache TTL alternative?']},
  {id:'s9',topic:'Kafka',question:'How would you use Bloom with Kafka?',answer30s:'Optional negative check before an exact idempotency store.',answer2m:'If Bloom says no, process and record. If maybe, check Redis/DB UNIQUE. Never skip on Bloom true alone.',followUps:['Can Bloom guarantee idempotency?'],trick:'Bloom-only dedupe.'},
  {id:'s10',topic:'Ops',question:'How do you handle a stale Bloom Filter?',answer30s:'Add-on-write, periodic rebuild, monitor filter age and false 404s.',answer2m:'New rows must update all instances via event or shared filter. Rebuild from SELECT id and atomic swap for zero downtime.',followUps:['Multi-instance drift?']},
];

export const ARCHITECT: InterviewQ[] = [
  {id:'a1',topic:'Scale',question:'How would you scale Bloom Filters across 100 app instances?',answer30s:'Shared RedisBloom, or local filters with pub/sub adds + scheduled rebuild.',answer2m:'Local is lowest latency but drifts. Broadcast create events; rebuild from DB as backstop; alert on digest mismatch. Partition filters by key range if memory tight.',followUps:['Sticky sessions?'],trick:'Sticky sessions fix drift.'},
  {id:'a2',topic:'Scale',question:'What happens when capacity is exceeded?',answer30s:'Bit density rises and FPP approaches 1 — everything looks like maybe.',answer2m:'You lose the benefit and hammer Redis/DB. Detect via estimated FPP/cardinality; rebuild a larger filter and swap; rate-limit meanwhile.',followUps:['Scalable Bloom Filter?']},
  {id:'a3',topic:'Ops',question:'Rebuild without downtime?',answer30s:'Build a new filter in the background, then atomic reference swap.',answer2m:'Dual-running uses 2× memory briefly. Drain or lock only during swap. Keep accepting reads on the old filter until swap completes.',followUps:['Who coordinates across pods?']},
  {id:'a4',topic:'Idempotency',question:'Can Bloom Filter guarantee idempotency?',answer30s:'No. False positives would skip never-seen work.',answer2m:'Idempotency needs exact once-seen storage: DB unique, Redis SET NX, Kafka exactly-once story with caveats. Bloom only reduces checks for cold ids.',followUps:['Where does UNIQUE live?']},
  {id:'a5',topic:'Obs',question:'How do you estimate FPP in production?',answer30s:'Track maybe→DB-miss rate; compare to theoretical (1-e^{-kn/m})^k.',answer2m:'Sample absent synthetic probes. Alert when observed FP rate drifts. Cardinality of BitSet also signals fill.',followUps:['Cardinality vs inserted n?']},
  {id:'a6',topic:'When not',question:'When should you NOT use a Bloom Filter?',answer30s:'Need exact answers, frequent deletes, tiny n, or correctness-critical membership alone.',answer2m:'AuthZ allow-lists, financial dedupe sole store, small HashSet fits in RAM exactly, or when almost all queries are hits so negatives are rare.',followUps:['Cuckoo instead?']},
  {id:'a7',topic:'LSM',question:'How do Cassandra/RocksDB use Bloom Filters?',answer30s:'Per-SSTable/HFile filters skip files that cannot contain a key.',answer2m:'Point read checks memtable then SSTables. Bloom miss skips index/data block reads — huge for absent keys. Compaction rebuilds filters for new files.',followUps:['Bits per key config?']},
  {id:'a8',topic:'Security',question:'Hash flooding / adversarial FPs?',answer30s:'Attackers may craft keys colliding into set bits; rate-limit and verify always.',answer2m:'Non-crypto hashes are fine for trusted ids. For hostile inputs, keyed hashes / secret seed reduce crafting. Still verify maybes. Cap filter memory to avoid exhaustion.',followUps:['Need SHA-256×k?']},
  {id:'a9',topic:'Java',question:'BitSet concurrency approach in production?',answer30s:'Immutable rebuild+swap for read-mostly; RW lock or striped atomics for incremental writes.',answer2m:'BitSet is unsafe. Guava’s BloomFilter is not synchronized. Document single-writer or wrap. Never claim thread safety you did not implement.',followUps:['Virtual threads impact?']},
  {id:'a10',topic:'Design',question:'Design anti-penetration for 100M users at 10k RPS.',answer30s:'Local/shared Bloom ~120MB@1%, Redis, Postgres, metrics, rebuild pipeline.',answer2m:'Gateway→app: Bloom miss 404; maybe→Redis→DB. Seed from DB; Kafka user-created adds; HPA on CPU; alert FPP and DB QPS; fail open if Bloom unhealthy with bulkhead.',followUps:['Multi-region?']},
];

export const RAPID: InterviewQ[] = [
  {id:'r1',topic:'Rapid',question:'Time complexity insert/lookup?',answer30s:'O(k).',answer2m:'k typically < 10.',followUps:['Space?']},
  {id:'r2',topic:'Rapid',question:'1M keys at 1% FPP memory?',answer30s:'~1.2 MB.',answer2m:'~10 bits/key.',followUps:['100M?']},
  {id:'r3',topic:'Rapid',question:'Alice inserted, mightContain Alice?',answer30s:'Must be true.',answer2m:'No FN.',followUps:['David?']},
  {id:'r4',topic:'Rapid',question:'Double hashing formula?',answer30s:'h1 + i*h2 mod m.',answer2m:'Keep h2 odd.',followUps:['Why two hashes?']},
  {id:'r5',topic:'Rapid',question:'Counting BF stores?',answer30s:'Counters not bits.',answer2m:'Enables delete.',followUps:['Cost?']},
  {id:'r6',topic:'Rapid',question:'Bloom vs Cuckoo delete?',answer30s:'Cuckoo supports delete better.',answer2m:'Slightly more memory.',followUps:['FP behavior?']},
  {id:'r7',topic:'Rapid',question:'Lab port?',answer30s:'8097',answer2m:'mvn spring-boot:run',followUps:['Stats path?']},
  {id:'r8',topic:'Rapid',question:'Fail if Bloom down?',answer30s:'Fall back to Redis/DB.',answer2m:'Never mass-404.',followUps:['Alert?']},
  {id:'r9',topic:'Rapid',question:'Source of truth?',answer30s:'Never Bloom.',answer2m:'DB/Redis/UNIQUE.',followUps:['Why?']},
  {id:'r10',topic:'Rapid',question:'SSTable Bloom purpose?',answer30s:'Skip disk reads.',answer2m:'Per file filter.',followUps:['MemTable?']},
];

export const ALL: InterviewQ[] = [...SENIOR, ...ARCHITECT, ...RAPID];
