import type {StreamProblem} from './types';

export const PROBLEMS_CORE: StreamProblem[] = [
  {
    id: "f01",
    category: "fundamentals",
    difficulty: "Beginner",
    title: "Stream from List",
    problem: "Create a Stream from a List and print each element.",
    input: "List.of(\"java\",\"spring\",\"kafka\")",
    output: "java / spring / kafka",
    solution: "List.of(\"java\",\"spring\",\"kafka\").stream().forEach(System.out::println);",
    pipeline: "List \u2192 stream \u2192 forEach",
    why: "Canonical collection source for Stream pipelines.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Reusing a Stream after a terminal operation throws IllegalStateException.",
    senior: "Prefer forEach for pure side effects; use collect when you need a result.",
    javaSince: "Java 8",
    tags: ["fundamentals"],
  },
  {
    id: "f02",
    category: "fundamentals",
    difficulty: "Beginner",
    title: "Stream from Set then sort",
    problem: "Stream unique departments and sort for stable output.",
    input: "Set.copyOf(List.of(\"ENG\",\"HR\",\"ENG\"))",
    output: "[ENG, HR]",
    solution: "Set.copyOf(List.of(\"ENG\",\"HR\",\"ENG\")).stream().sorted().toList();",
    pipeline: "Set \u2192 stream \u2192 sorted \u2192 toList",
    why: "Set already unique; sorted makes output deterministic.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Assuming HashSet encounter order is stable.",
    senior: "Document ordering contracts when APIs return Sets.",
    javaSince: "Java 16",
    tags: ["fundamentals"],
  },
  {
    id: "f03",
    category: "fundamentals",
    difficulty: "Beginner",
    title: "Stream Map entries",
    problem: "Print map entries as key=value lines.",
    input: "Map.of(\"a\",1,\"b\",2)",
    output: "a=1 and b=2 (unordered)",
    solution: "Map.of(\"a\",1,\"b\",2).entrySet().stream()\n  .forEach(e -> System.out.println(e.getKey() + \"=\" + e.getValue()));",
    pipeline: "entrySet \u2192 stream \u2192 forEach",
    why: "Map itself is not a Stream source; stream the entrySet.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Calling map.stream() does not compile.",
    senior: "Use LinkedHashMap when insertion order must be preserved.",
    javaSince: "Java 8",
    tags: ["fundamentals"],
  },
  {
    id: "f04",
    category: "fundamentals",
    difficulty: "Intermediate",
    title: "Primitive IntStream sum",
    problem: "Sum an int[] without boxing.",
    input: "[1,2,3,4]",
    output: "10",
    solution: "int sum = Arrays.stream(new int[]{1, 2, 3, 4}).sum();",
    pipeline: "int[] \u2192 IntStream \u2192 sum",
    why: "Primitive streams avoid Integer boxing overhead.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Using Stream<Integer> on large arrays wastes CPU and GC.",
    senior: "Prefer IntStream/LongStream/DoubleStream for numeric hot paths.",
    javaSince: "Java 8",
    tags: ["fundamentals"],
  },
  {
    id: "f05",
    category: "fundamentals",
    difficulty: "Intermediate",
    title: "Stream.generate with limit",
    problem: "Generate 5 random doubles safely from an infinite source.",
    input: "n=5",
    output: "5 doubles in [0,1)",
    solution: "List<Double> xs = Stream.generate(Math::random).limit(5).toList();",
    pipeline: "generate \u2192 limit \u2192 toList",
    why: "Infinite sources must be bounded before a terminal op.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
    trap: "Collecting without limit hangs forever.",
    senior: "Prefer RandomGenerator (Java 17+) when you need reproducible tests.",
    javaSince: "Java 8",
    tags: ["fundamentals"],
  },
  {
    id: "f06",
    category: "fundamentals",
    difficulty: "Advanced",
    title: "Files.lines try-with-resources",
    problem: "Count non-blank lines in a CSV using Files.lines and ensure the file is closed.",
    input: "payments.csv",
    output: "N non-blank lines",
    solution: "try (Stream<String> lines = Files.lines(Path.of(\"payments.csv\"))) {\n  long n = lines.filter(l -> !l.isBlank()).count();\n}",
    pipeline: "Files.lines \u2192 filter \u2192 count",
    why: "Files.lines returns a Stream that holds an open file channel.",
    timeComplexity: "O(lines)",
    spaceComplexity: "O(1)",
    trap: "Forgetting try-with-resources leaks file descriptors.",
    senior: "Always close Files.lines / BufferedReader.lines in production code.",
    javaSince: "Java 8",
    tags: ["fundamentals", "production", "io"],
  },
  {
    id: "f07",
    category: "fundamentals",
    difficulty: "Intermediate",
    title: "Optional.stream flatten",
    problem: "Flatten a List of Optional<String> into present values only.",
    input: "[Optional.of(\"A\"), Optional.empty(), Optional.of(\"B\")]",
    output: "[A, B]",
    solution: "List<String> names = List.of(Optional.of(\"A\"), Optional.<String>empty(), Optional.of(\"B\"))\n  .stream()\n  .flatMap(Optional::stream)\n  .toList();",
    pipeline: "stream \u2192 flatMap(Optional::stream) \u2192 toList",
    why: "Optional.stream() yields 0 or 1 element \u2014 ideal for flatMap.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "filter(Optional::isPresent).map(Optional::get) is noisier and easier to misuse.",
    senior: "Prefer Optional.stream in Stream pipelines (Java 9+).",
    javaSince: "Java 9",
    tags: ["fundamentals", "datetime-optional"],
  },
  {
    id: "f08",
    category: "fundamentals",
    difficulty: "Intermediate",
    title: "iterate evens",
    problem: "First 10 even numbers from 0.",
    input: "seed=0",
    output: "[0,2,4,6,8,10,12,14,16,18]",
    solution: "Stream.iterate(0,n->n+2).limit(10).toList();",
    pipeline: "iterate \u2192 limit \u2192 toList",
    why: "Lazy arithmetic sequence.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
    trap: "Infinite collect without limit.",
    senior: "Java 9 iterate(seed,hasNext,next) for finite sequences.",
    javaSince: "Java 8/9",
    tags: ["fundamentals"],
  },
  {
    id: "f09",
    category: "fundamentals",
    difficulty: "Advanced",
    title: "Fibonacci pairs",
    problem: "First 10 Fibonacci via iterate pairs.",
    input: "n=10",
    output: "[0,1,1,2,3,5,8,13,21,34]",
    solution: "Stream.iterate(new long[]{0,1},p->new long[]{p[1],p[0]+p[1]}).limit(10).map(p->p[0]).toList();",
    pipeline: "iterate \u2192 map \u2192 limit",
    why: "Carry state in pairs.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
    trap: "Parallelizing iterate.",
    senior: "Keep iterate sequential.",
    tags: ["fundamentals"],
  },
  {
    id: "f10",
    category: "fundamentals",
    difficulty: "Intermediate",
    title: "Box/unbox",
    problem: "IntStream boxed then mapToInt sum.",
    input: "1..5",
    output: "15",
    solution: "IntStream.rangeClosed(1,5).boxed().toList().stream().mapToInt(Integer::intValue).sum();",
    pipeline: "boxed \u2192 mapToInt \u2192 sum",
    why: "Boundary boxing.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "map(Integer::intValue) still Stream<Integer>.",
    senior: "Boxing churn is a silent tax.",
    tags: ["fundamentals"],
  },
  {
    id: "f11",
    category: "fundamentals",
    difficulty: "Advanced",
    title: "Files.lines close",
    problem: "Count non-blank lines with try-with-resources.",
    input: "file",
    output: "N",
    solution: "try(Stream<String> s=Files.lines(Path.of(\"f.txt\"))){ return s.filter(l->!l.isBlank()).count(); }",
    pipeline: "Files.lines \u2192 filter \u2192 count",
    why: "AutoCloseable stream.",
    timeComplexity: "O(lines)",
    spaceComplexity: "O(1)",
    trap: "Resource leak.",
    senior: "Always close file streams.",
    javaSince: "Java 8",
    tags: ["fundamentals"],
  },
  {
    id: "f12",
    category: "fundamentals",
    difficulty: "Beginner",
    title: "Stream.ofNullable",
    problem: "0-or-1 element stream from nullable.",
    input: "null or \"x\"",
    output: "empty or [x]",
    solution: "Stream.ofNullable(value).toList();",
    pipeline: "ofNullable \u2192 toList",
    why: "Java 9 null-safe source.",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    trap: "Stream.of(null) NPE.",
    senior: "Prefer ofNullable at boundaries.",
    javaSince: "Java 9",
    tags: ["fundamentals"],
  },
  {
    id: "f13",
    category: "fundamentals",
    difficulty: "Intermediate",
    title: "takeWhile dropWhile",
    problem: "Take while n<5 from sorted list.",
    input: "[1,2,3,4,5,6]",
    output: "[1,2,3,4]",
    solution: "List.of(1,2,3,4,5,6).stream().takeWhile(n->n<5).toList();",
    pipeline: "takeWhile \u2192 toList",
    why: "Java 9 short-circuit prefix.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
    trap: "On unordered parallel sources semantics weaken.",
    senior: "Know ordered assumption.",
    javaSince: "Java 9",
    tags: ["fundamentals"],
  },
  {
    id: "f14",
    category: "fundamentals",
    difficulty: "Advanced",
    title: "parallel LongStream sum",
    problem: "Parallel sum 1..1e6.",
    input: "1..1e6",
    output: "500000500000",
    solution: "LongStream.rangeClosed(1,1_000_000).parallel().sum();",
    pipeline: "range \u2192 parallel \u2192 sum",
    why: "CPU-bound associative.",
    timeComplexity: "O(n/p)",
    spaceComplexity: "O(1)",
    trap: "IO on commonPool.",
    senior: "Measure; tiny lists slower.",
    tags: ["fundamentals"],
  },
  {
    id: "fi01",
    category: "filter",
    difficulty: "Beginner",
    title: "Filter even numbers",
    problem: "Keep even integers from a list.",
    input: "[1,2,3,4,5,6]",
    output: "[2, 4, 6]",
    solution: "List<Integer> evens = List.of(1,2,3,4,5,6).stream().filter(n -> n % 2 == 0).toList();",
    pipeline: "stream \u2192 filter \u2192 toList",
    why: "filter keeps elements matching a Predicate.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Mutating the source list while streaming.",
    senior: "Keep predicates pure and side-effect free.",
    javaSince: "Java 16",
    tags: ["filter"],
  },
  {
    id: "fi02",
    category: "filter",
    difficulty: "Intermediate",
    title: "Predicate and / or / negate",
    problem: "Keep salaries that are either junior band (<50k) or executive band (>=200k) using composed Predicates.",
    input: "salaries [40k,80k,220k,45k]",
    output: "[40000, 220000, 45000]",
    solution: "Predicate<Integer> junior = s -> s < 50_000;\nPredicate<Integer> exec = s -> s >= 200_000;\nList<Integer> band = salaries.stream().filter(junior.or(exec)).toList();\nList<Integer> mid = salaries.stream().filter(junior.or(exec).negate()).toList();",
    pipeline: "stream \u2192 filter(predicate.or/and/negate) \u2192 toList",
    why: "Predicate composition avoids nested boolean soup and is reusable.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Negating a complex predicate without parentheses clarity.",
    senior: "Name predicates; compose with and/or/negate for interview clarity.",
    javaSince: "Java 8",
    tags: ["filter", "predicate"],
  },
  {
    id: "fi03",
    category: "filter",
    difficulty: "Beginner",
    title: "Filter non-blank strings",
    problem: "Remove null and blank strings after trim.",
    input: "[\"  \",\"java\",null,\"  spring \"]",
    output: "[java, spring]",
    solution: "List<String> clean = Stream.of(\"  \", \"java\", null, \"  spring \")\n  .filter(Objects::nonNull)\n  .map(String::trim)\n  .filter(s -> !s.isBlank())\n  .toList();",
    pipeline: "stream \u2192 filter(nonNull) \u2192 map(trim) \u2192 filter(!blank) \u2192 toList",
    why: "Null-safe filtering before mapping prevents NPEs.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Calling trim before null check.",
    senior: "filter(Objects::nonNull) early; prefer isBlank over isEmpty for whitespace.",
    javaSince: "Java 11",
    tags: ["filter"],
  },
  {
    id: "fi04",
    category: "filter",
    difficulty: "Intermediate",
    title: "Filter employees by department",
    problem: "Return Engineering employees only.",
    input: "emps with ENG/HR/SALES",
    output: "only ENG records",
    solution: "List<Employee> eng = employees.stream()\n  .filter(e -> \"ENG\".equals(e.department()))\n  .toList();",
    pipeline: "stream \u2192 filter(dept) \u2192 toList",
    why: "Domain filtering is the most common Stream use case.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Using == for String department comparison.",
    senior: "Prefer constants or enums for department codes.",
    javaSince: "Java 16",
    tags: ["filter"],
  },
  {
    id: "fi05",
    category: "filter",
    difficulty: "Advanced",
    title: "takeWhile / dropWhile sorted prefix",
    problem: "From a sorted transaction amount list, take while amounts stay under 1000, then dropWhile under 100.",
    input: "sorted [50,80,120,900,1500]",
    output: "takeWhile:<1000 \u2192 [50,80,120,900]",
    solution: "List<Integer> under1k = amounts.stream().takeWhile(a -> a < 1000).toList();\nList<Integer> from100 = amounts.stream().dropWhile(a -> a < 100).toList();",
    pipeline: "sorted stream \u2192 takeWhile/dropWhile \u2192 toList",
    why: "takeWhile/dropWhile require sorted (or prefix-meaningful) encounter order.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Using takeWhile on unsorted data and expecting a global filter.",
    senior: "Interview: contrast takeWhile (prefix) vs filter (all matches).",
    javaSince: "Java 9",
    tags: ["filter"],
  },
  {
    id: "fi06",
    category: "filter",
    difficulty: "Intermediate",
    title: "Predicate and()",
    problem: "High salary AND engineering.",
    input: "emps",
    output: "subset",
    solution: "Predicate<Employee> high=e->e.salary()>100_000; Predicate<Employee> eng=e->\"ENG\".equals(e.department()); emps.stream().filter(high.and(eng)).toList();",
    pipeline: "and \u2192 filter",
    why: "Composable predicates.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Stateful predicates.",
    senior: "Name predicates for readability.",
    tags: ["filter"],
  },
  {
    id: "fi07",
    category: "filter",
    difficulty: "Intermediate",
    title: "Predicate or/negate",
    problem: "Use or and negate.",
    input: "emps",
    output: "subset",
    solution: "emps.stream().filter(high.or(eng)).toList(); emps.stream().filter(high.negate()).toList();",
    pipeline: "or/negate \u2192 filter",
    why: "Full Predicate API.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "De Morgan mistakes.",
    senior: "Keep pure.",
    tags: ["filter"],
  },
  {
    id: "fi08",
    category: "filter",
    difficulty: "Advanced",
    title: "BigDecimal amount filter",
    problem: "SUCCESS and amount>=1000.",
    input: "txs",
    output: "subset",
    solution: "txs.stream().filter(t->\"SUCCESS\".equals(t.status()) && t.amount().compareTo(new BigDecimal(\"1000\"))>=0).toList();",
    pipeline: "filter(compound)",
    why: "Money-safe.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Using > on BigDecimal.",
    senior: "compareTo only.",
    tags: ["filter"],
  },
  {
    id: "m01",
    category: "map",
    difficulty: "Beginner",
    title: "Map to uppercase",
    problem: "Transform strings to uppercase.",
    input: "[\"upi\",\"neft\"]",
    output: "[UPI, NEFT]",
    solution: "List<String> up = List.of(\"upi\",\"neft\").stream().map(String::toUpperCase).toList();",
    pipeline: "stream \u2192 map \u2192 toList",
    why: "map is 1:1 element transformation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Confusing map with flatMap for nested lists.",
    senior: "Prefer method references when the mapping is a single method call.",
    javaSince: "Java 16",
    tags: ["map"],
  },
  {
    id: "m02",
    category: "map",
    difficulty: "Intermediate",
    title: "mapToInt for salaries",
    problem: "Compute average salary as double without boxing in the average step.",
    input: "Employee salaries",
    output: "avg as double",
    solution: "double avg = employees.stream().mapToInt(Employee::salary).average().orElse(0);",
    pipeline: "stream \u2192 mapToInt \u2192 average",
    why: "mapToInt yields IntStream with numeric terminals.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "map(Employee::salary).collect(averaging) boxes unnecessarily.",
    senior: "Use mapToInt/Long/Double for aggregates on primitives.",
    javaSince: "Java 8",
    tags: ["map"],
  },
  {
    id: "m03",
    category: "map",
    difficulty: "Beginner",
    title: "Extract employee names",
    problem: "Map Employee records to name strings.",
    input: "List<Employee>",
    output: "[Ada, Linus, Grace]",
    solution: "List<String> names = employees.stream().map(Employee::name).toList();",
    pipeline: "stream \u2192 map(name) \u2192 toList",
    why: "Projection is the core map pattern in domain models.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Mapping to mutable shared objects.",
    senior: "Records + method refs keep projections readable.",
    javaSince: "Java 16",
    tags: ["map"],
  },
  {
    id: "m04",
    category: "map",
    difficulty: "Intermediate",
    title: "map vs peek side effects",
    problem: "Demonstrate that peek should not replace map for transformations.",
    input: "[\"a\",\"b\"]",
    output: "[A, B]",
    solution: "// correct\nList<String> out = list.stream().map(String::toUpperCase).toList();\n// wrong interview trap: peek(s -> s.toUpperCase()) does nothing to immutable String",
    pipeline: "stream \u2192 map \u2192 toList",
    why: "peek is for debugging; map returns the new value.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Relying on peek for business logic (may be elided).",
    senior: "Staff answer: peek is not guaranteed to run for short-circuit ops.",
    javaSince: "Java 8",
    tags: ["map"],
  },
  {
    id: "m05",
    category: "map",
    difficulty: "Advanced",
    title: "mapMulti for conditional emit",
    problem: "Use mapMulti to emit square only for even ints (Java 16).",
    input: "[1,2,3,4]",
    output: "[4, 16]",
    solution: "List<Integer> squares = List.of(1,2,3,4).stream()\n  .<Integer>mapMulti((n, sink) -> { if (n % 2 == 0) sink.accept(n * n); })\n  .toList();",
    pipeline: "stream \u2192 mapMulti \u2192 toList",
    why: "mapMulti is an imperative flatMap alternative with less allocation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Overusing mapMulti when filter+map is clearer.",
    senior: "Prefer filter+map unless you need 0..N emits with shared state in the lambda.",
    javaSince: "Java 16",
    tags: ["map"],
  },
  {
    id: "mp09",
    category: "map",
    difficulty: "Intermediate",
    title: "String to LocalDate",
    problem: "Parse ISO dates.",
    input: "[\"2024-01-01\"]",
    output: "LocalDate list",
    solution: "List.of(\"2024-01-01\").stream().map(LocalDate::parse).toList();",
    pipeline: "map(parse)",
    why: "Type conversion.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Custom format without formatter.",
    senior: "Pass DateTimeFormatter.",
    tags: ["map"],
  },
  {
    id: "mp10",
    category: "map",
    difficulty: "Advanced",
    title: "Entity to DTO",
    problem: "Map entities to API DTOs.",
    input: "entities",
    output: "dtos",
    solution: "entities.stream().map(e->new PaymentDto(e.id(),e.amount(),e.status())).toList();",
    pipeline: "map \u2192 DTO",
    why: "Boundary mapping.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Lazy load inside map.",
    senior: "DTO query / fetch join.",
    tags: ["map"],
  },
  {
    id: "fm01",
    category: "flatmap",
    difficulty: "Beginner",
    title: "Flatten list of lists",
    problem: "Flatten List<List<String>> into one list.",
    input: "[[a,b],[c]]",
    output: "[a, b, c]",
    solution: "List<String> flat = List.of(List.of(\"a\",\"b\"), List.of(\"c\")).stream()\n  .flatMap(Collection::stream)\n  .toList();",
    pipeline: "stream \u2192 flatMap(Collection::stream) \u2192 toList",
    why: "flatMap maps each element to a stream and concatenates.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Using map instead of flatMap leaves Stream<Stream<T>>.",
    senior: "flatMap = map + flatten; interviewers watch for the nested Stream type.",
    javaSince: "Java 16",
    tags: ["flatmap"],
  },
  {
    id: "fm02",
    category: "flatmap",
    difficulty: "Intermediate",
    title: "Orders to line items",
    problem: "From orders, collect all SKUs across line items.",
    input: "Order{items[{sku},{sku}]}",
    output: "[SKU1, SKU2, ...]",
    solution: "List<String> skus = orders.stream()\n  .flatMap(o -> o.items().stream())\n  .map(LineItem::sku)\n  .toList();",
    pipeline: "orders \u2192 flatMap(items) \u2192 map(sku) \u2192 toList",
    why: "One-to-many domain navigation is the textbook flatMap case.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Null items list without Optional/emptyStream guard.",
    senior: "Model empty collections as empty lists, not null.",
    javaSince: "Java 16",
    tags: ["flatmap", "ecommerce"],
  },
  {
    id: "fm03",
    category: "flatmap",
    difficulty: "Intermediate",
    title: "Split sentences to words",
    problem: "FlatMap sentences into lowercase words.",
    input: "[\"Java Streams\",\"are lazy\"]",
    output: "[java, streams, are, lazy]",
    solution: "List<String> words = sentences.stream()\n  .flatMap(s -> Arrays.stream(s.toLowerCase().split(\"\\\\s+\")))\n  .toList();",
    pipeline: "stream \u2192 flatMap(split\u2192stream) \u2192 toList",
    why: "String.split returns array; Arrays.stream bridges to Stream.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Pattern.compile per element instead of reusing Pattern.",
    senior: "Reuse Pattern.splitAsStream for hot paths.",
    javaSince: "Java 8",
    tags: ["flatmap", "strings"],
  },
  {
    id: "fm04",
    category: "flatmap",
    difficulty: "Advanced",
    title: "flatMapToInt code points",
    problem: "Sum Unicode code points of all strings.",
    input: "[\"A\",\"\u20ac\"]",
    output: "sum of code points",
    solution: "int sum = List.of(\"A\", \"\u20ac\").stream()\n  .flatMapToInt(String::codePoints)\n  .sum();",
    pipeline: "stream \u2192 flatMapToInt(codePoints) \u2192 sum",
    why: "codePoints handles supplementary characters correctly vs chars().",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Using chars() for emoji-heavy text.",
    senior: "Prefer codePoints for internationalized text processing.",
    javaSince: "Java 8",
    tags: ["flatmap"],
  },
  {
    id: "fm05",
    category: "flatmap",
    difficulty: "Advanced",
    title: "Nested Optional flatMap",
    problem: "Chain Optional lookups with flatMap then bridge into a Stream.",
    input: "Optional<User> \u2192 Optional<Address>",
    output: "city or empty",
    solution: "List<String> cities = users.stream()\n  .map(User::address)\n  .flatMap(Optional::stream)\n  .map(Address::city)\n  .toList();",
    pipeline: "stream \u2192 map(Optional) \u2192 flatMap(Optional::stream) \u2192 map \u2192 toList",
    why: "Optional.stream turns absent into empty contribution.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Calling get() without isPresent in a map.",
    senior: "Never Optional.get in Streams; use stream()/orElse.",
    javaSince: "Java 9",
    tags: ["flatmap"],
  },
  {
    id: "d01",
    category: "distinct",
    difficulty: "Beginner",
    title: "Distinct strings",
    problem: "Remove duplicate tags preserving encounter order.",
    input: "[\"java\",\"spring\",\"java\"]",
    output: "[java, spring]",
    solution: "List<String> uniq = List.of(\"java\",\"spring\",\"java\").stream().distinct().toList();",
    pipeline: "stream \u2192 distinct \u2192 toList",
    why: "distinct uses equals/hashCode; encounter order for sequential.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "distinct on objects without proper equals/hashCode.",
    senior: "For custom uniqueness, use toMap/collectingAndThen or a LinkedHashSet collector.",
    javaSince: "Java 16",
    tags: ["distinct"],
  },
  {
    id: "d02",
    category: "distinct",
    difficulty: "Advanced",
    title: "Distinct-by-key warning (parallel)",
    problem: "Explain why a stateful distinct-by-key with a shared HashSet breaks under parallel().",
    input: "employees by email",
    output: "unique by email",
    solution: "// sequential OK-ish (still impure):\nSet<String> seen = ConcurrentHashMap.newKeySet();\nList<Employee> uniq = employees.stream()\n  .filter(e -> seen.add(e.email()))\n  .toList();\n// Prefer:\nMap<String, Employee> byEmail = employees.stream()\n  .collect(Collectors.toMap(Employee::email, Function.identity(), (a, b) -> a, LinkedHashMap::new));",
    pipeline: "stream \u2192 toMap(key, identity, merge, LinkedHashMap)",
    why: "Shared mutable Set in filter is a race under parallel and a hidden side effect.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "filter(seen.add) in parallelStream \u2014 lost updates / ConcurrentModification.",
    senior: "Staff: distinct-by-key needs ConcurrentHashMap or toMap merge; never a plain HashSet in parallel.",
    javaSince: "Java 8",
    tags: ["distinct", "parallel"],
  },
  {
    id: "d03",
    category: "distinct",
    difficulty: "Intermediate",
    title: "Distinct after map",
    problem: "Map orders to customerId then distinct.",
    input: "orders",
    output: "unique customer ids",
    solution: "List<String> customers = orders.stream().map(Order::customerId).distinct().toList();",
    pipeline: "stream \u2192 map \u2192 distinct \u2192 toList",
    why: "distinct after projection is cheaper than distinct on heavy objects.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "distinct before map when only the projected key matters.",
    senior: "Project early; distinct on the key you care about.",
    javaSince: "Java 16",
    tags: ["distinct"],
  },
  {
    id: "d04",
    category: "distinct",
    difficulty: "Intermediate",
    title: "Distinct primitives",
    problem: "Unique ints via IntStream.",
    input: "[1,2,2,3]",
    output: "[1,2,3]",
    solution: "int[] uniq = IntStream.of(1,2,2,3).distinct().toArray();",
    pipeline: "IntStream \u2192 distinct \u2192 toArray",
    why: "Primitive distinct uses a specialized set.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Boxing then distinct on Stream<Integer> for large arrays.",
    senior: "Stay on IntStream for numeric uniqueness.",
    javaSince: "Java 8",
    tags: ["distinct"],
  },
  {
    id: "ds01",
    category: "distinct",
    difficulty: "Advanced",
    title: "distinct-by-key caution",
    problem: "Unique by name without proper parallel-safe distinctByKey.",
    input: "emps",
    output: "unique names",
    solution: "emps.stream().collect(Collectors.toMap(Employee::name,e->e,(a,b)->a,LinkedHashMap::new)).values().stream().toList();",
    pipeline: "toMap merge \u2192 values",
    why: "Stable distinct-by-key.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "ConcurrentHashMap.newKeySet filter distinctByKey in parallel is subtle/racy if wrong.",
    senior: "Prefer toMap/grouping for distinct-by-key.",
    tags: ["distinct"],
  },
  {
    id: "so01",
    category: "sort",
    difficulty: "Beginner",
    title: "Natural sort strings",
    problem: "Sort names alphabetically.",
    input: "[\"Zoe\",\"Ada\",\"Lin\"]",
    output: "[Ada, Lin, Zoe]",
    solution: "List<String> sorted = List.of(\"Zoe\",\"Ada\",\"Lin\").stream().sorted().toList();",
    pipeline: "stream \u2192 sorted \u2192 toList",
    why: "sorted() uses natural ordering.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "sorted() on streams of non-Comparable types.",
    senior: "Provide Comparator when natural order is wrong for the domain.",
    javaSince: "Java 16",
    tags: ["sort"],
  },
  {
    id: "so02",
    category: "sort",
    difficulty: "Intermediate",
    title: "Sort employees by salary desc",
    problem: "Sort employees by salary descending, then name ascending.",
    input: "Employee list",
    output: "highest salary first",
    solution: "List<Employee> ranked = employees.stream()\n  .sorted(Comparator.comparingInt(Employee::salary).reversed()\n      .thenComparing(Employee::name))\n  .toList();",
    pipeline: "stream \u2192 sorted(comparator) \u2192 toList",
    why: "thenComparing breaks ties stably for reporting.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "comparing salary as Integer nulls without nullsLast.",
    senior: "Always define a total order for production sorts.",
    javaSince: "Java 16",
    tags: ["sort", "employee"],
  },
  {
    id: "so03",
    category: "sort",
    difficulty: "Advanced",
    title: "Sort BigDecimal amounts",
    problem: "Sort payment amounts ascending with BigDecimal.",
    input: "[10.00, 2.5, 10.0]",
    output: "[2.5, 10.00, 10.0] by compareTo",
    solution: "List<BigDecimal> sorted = amounts.stream()\n  .sorted(Comparator.naturalOrder())\n  .toList();",
    pipeline: "stream \u2192 sorted(naturalOrder) \u2192 toList",
    why: "BigDecimal.compareTo ignores scale; equals does not \u2014 know the difference.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Using equals for money uniqueness vs compareTo for sort.",
    senior: "FinTech: never sort money as double; use BigDecimal.",
    javaSince: "Java 8",
    tags: ["sort", "fintech"],
  },
  {
    id: "so04",
    category: "sort",
    difficulty: "Intermediate",
    title: "reverseOrder",
    problem: "Sort integers descending.",
    input: "[1,3,2]",
    output: "[3, 2, 1]",
    solution: "List<Integer> desc = List.of(1,3,2).stream().sorted(Comparator.reverseOrder()).toList();",
    pipeline: "stream \u2192 sorted(reverseOrder) \u2192 toList",
    why: "reverseOrder is the concise descending Comparator.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "sorted(Comparator.comparing(x->x).reversed()) verbosity without need.",
    senior: "Use reverseOrder for Comparable elements.",
    javaSince: "Java 16",
    tags: ["sort"],
  },
  {
    id: "so05",
    category: "sort",
    difficulty: "Advanced",
    title: "Multi-field Comparator",
    problem: "Sort by dept then salary desc then name.",
    input: "emps",
    output: "ordered",
    solution: "emps.stream().sorted(Comparator.comparing(Employee::department).thenComparing(Comparator.comparingDouble(Employee::salary).reversed()).thenComparing(Employee::name)).toList();",
    pipeline: "sorted(multi)",
    why: "thenComparing chains.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "reversed() scope mistakes.",
    senior: "nullsFirst/Last for nullable fields.",
    tags: ["sort"],
  },
  {
    id: "so06",
    category: "sort",
    difficulty: "Intermediate",
    title: "nullsLast salary",
    problem: "Sort salaries nulls last.",
    input: "emps with null salary boxed",
    output: "ordered",
    solution: "emps.stream().sorted(Comparator.comparing(Employee::salary, Comparator.nullsLast(Double::compareTo))).toList();",
    pipeline: "sorted(nullsLast)",
    why: "Null-safe sort.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "NPE in comparingDouble on null.",
    senior: "Model nullability explicitly.",
    tags: ["sort"],
  },
  {
    id: "ls01",
    category: "limit-skip",
    difficulty: "Beginner",
    title: "Top 3 with limit",
    problem: "Take first 3 elements after sorting descending.",
    input: "[5,1,9,3,7]",
    output: "[9, 7, 5]",
    solution: "List<Integer> top3 = List.of(5,1,9,3,7).stream()\n  .sorted(Comparator.reverseOrder())\n  .limit(3)\n  .toList();",
    pipeline: "stream \u2192 sorted \u2192 limit \u2192 toList",
    why: "limit short-circuits after N elements when ordered.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(k)",
    trap: "limit before sorted (wrong top-N).",
    senior: "For top-N, sort then limit \u2014 or use a heap for large n.",
    javaSince: "Java 16",
    tags: ["limit-skip"],
  },
  {
    id: "ls02",
    category: "limit-skip",
    difficulty: "Intermediate",
    title: "Pagination skip/limit",
    problem: "Page size 10, page index 2 (0-based) of transaction ids.",
    input: "ids stream",
    output: "elements 20..29",
    solution: "List<String> page = ids.stream().skip(2L * 10).limit(10).toList();",
    pipeline: "stream \u2192 skip \u2192 limit \u2192 toList",
    why: "skip+limit models offset pagination.",
    timeComplexity: "O(offset+page)",
    spaceComplexity: "O(page)",
    trap: "Deep offsets on huge streams are expensive.",
    senior: "Prefer keyset pagination in production APIs.",
    javaSince: "Java 16",
    tags: ["limit-skip", "production"],
  },
  {
    id: "ls03",
    category: "limit-skip",
    difficulty: "Beginner",
    title: "skip first header",
    problem: "Skip CSV header line then parse.",
    input: "lines with header",
    output: "data rows only",
    solution: "List<String> rows = lines.stream().skip(1).toList();",
    pipeline: "stream \u2192 skip(1) \u2192 toList",
    why: "skip drops the first N encounter-order elements.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "skip on unordered parallel sources is nondeterministic.",
    senior: "Keep header handling sequential when order matters.",
    javaSince: "Java 16",
    tags: ["limit-skip"],
  },
  {
    id: "ls04",
    category: "limit-skip",
    difficulty: "Advanced",
    title: "limit on infinite iterate",
    problem: "Materialize first 100 primes-like candidates from iterate (illustrative bound).",
    input: "iterate from 2",
    output: "100 ints",
    solution: "List<Integer> first = Stream.iterate(2, n -> n + 1).limit(100).toList();",
    pipeline: "iterate \u2192 limit \u2192 toList",
    why: "limit is mandatory on infinite sources.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
    trap: "forEach on unbounded iterate.",
    senior: "Library APIs should require a bound for infinite factories.",
    javaSince: "Java 8",
    tags: ["limit-skip"],
  },
  {
    id: "ls05",
    category: "limit-skip",
    difficulty: "Staff",
    title: "skip pagination cost",
    problem: "Why skip(10_000_000) is bad in-memory.",
    input: "huge list",
    output: "page",
    solution: "// Prefer DB keyset pagination\n// stream.skip(huge).limit(20) still walks huge elements",
    pipeline: "skip \u2192 limit",
    why: "skip is O(n) on encounter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Using skip for deep pages on big lists.",
    senior: "Keyset pagination in SQL.",
    tags: ["limit-skip"],
  },
  {
    id: "fmch01",
    category: "find-match",
    difficulty: "Beginner",
    title: "anyMatch / allMatch / noneMatch",
    problem: "Check if any employee is in ENG, all have salary > 0, none are contractors.",
    input: "employees",
    output: "booleans",
    solution: "boolean anyEng = employees.stream().anyMatch(e -> \"ENG\".equals(e.department()));\nboolean allPaid = employees.stream().allMatch(e -> e.salary() > 0);\nboolean noContractors = employees.stream().noneMatch(Employee::contractor);",
    pipeline: "stream \u2192 anyMatch|allMatch|noneMatch",
    why: "Short-circuiting boolean terminals.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "allMatch on empty stream is true (vacuous truth).",
    senior: "Know empty-stream semantics for allMatch/noneMatch.",
    javaSince: "Java 8",
    tags: ["find-match"],
  },
  {
    id: "fmch02",
    category: "find-match",
    difficulty: "Intermediate",
    title: "findFirst vs findAny",
    problem: "Contrast findFirst and findAny on parallel streams of payment ids.",
    input: "parallel payment stream",
    output: "Optional id",
    solution: "Optional<String> first = ids.stream().filter(id -> id.startsWith(\"P\")).findFirst();\nOptional<String> any = ids.parallelStream().filter(id -> id.startsWith(\"P\")).findAny();",
    pipeline: "stream \u2192 filter \u2192 findFirst|findAny",
    why: "findFirst respects encounter order; findAny may return any match (faster parallel).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Assuming findAny is deterministic under parallel.",
    senior: "Use findFirst when order matters; findAny when any witness is enough.",
    javaSince: "Java 8",
    tags: ["find-match", "parallel"],
  },
  {
    id: "fmch03",
    category: "find-match",
    difficulty: "Beginner",
    title: "findFirst present name",
    problem: "Find first name starting with A.",
    input: "[\"Bob\",\"Ada\",\"Amy\"]",
    output: "Optional[Ada]",
    solution: "Optional<String> name = List.of(\"Bob\",\"Ada\",\"Amy\").stream()\n  .filter(s -> s.startsWith(\"A\"))\n  .findFirst();",
    pipeline: "stream \u2192 filter \u2192 findFirst",
    why: "findFirst returns Optional.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Calling get() without isPresent/orElseThrow.",
    senior: "Prefer orElseThrow in domain code when absence is a bug.",
    javaSince: "Java 8",
    tags: ["find-match"],
  },
  {
    id: "fmch04",
    category: "find-match",
    difficulty: "Advanced",
    title: "Short-circuit vs full scan",
    problem: "Show anyMatch can stop early vs count() always scans.",
    input: "large list",
    output: "true early",
    solution: "boolean ok = huge.stream().anyMatch(x -> x == 42);\nlong n = huge.stream().filter(x -> x == 42).count(); // full scan",
    pipeline: "stream \u2192 anyMatch (short-circuit)",
    why: "Choose the terminal that matches the question.",
    timeComplexity: "O(k) best",
    spaceComplexity: "O(1)",
    trap: "Using collect just to check existence.",
    senior: "Interview: pick anyMatch for existence, findFirst for the value.",
    javaSince: "Java 8",
    tags: ["find-match"],
  },
  {
    id: "fmch05",
    category: "find-match",
    difficulty: "Intermediate",
    title: "max / min with Comparator",
    problem: "Find employee with max salary.",
    input: "employees",
    output: "Optional<Employee>",
    solution: "Optional<Employee> top = employees.stream().max(Comparator.comparingInt(Employee::salary));",
    pipeline: "stream \u2192 max(comparator)",
    why: "max/min are reductions returning Optional.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "max on empty stream \u2014 handle Optional.",
    senior: "For ties, chain thenComparing to define a winner.",
    javaSince: "Java 8",
    tags: ["find-match", "employee"],
  },
  {
    id: "r01",
    category: "reduce",
    difficulty: "Beginner",
    title: "Sum with reduce",
    problem: "Sum integers with reduce.",
    input: "[1,2,3,4]",
    output: "10",
    solution: "int sum = List.of(1,2,3,4).stream().reduce(0, Integer::sum);",
    pipeline: "stream \u2192 reduce(identity, accumulator)",
    why: "Identity must be identity for the operator.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "reduce without identity returns Optional.",
    senior: "Prefer mapToInt.sum for primitives.",
    javaSince: "Java 8",
    tags: ["reduce"],
  },
  {
    id: "r02",
    category: "reduce",
    difficulty: "Advanced",
    title: "Reduce with combiner (parallel)",
    problem: "Implement parallel-safe String joining of account ids with reduce identity/accumulator/combiner.",
    input: "[\"A1\",\"A2\",\"A3\"]",
    output: "A1,A2,A3",
    solution: "String joined = ids.parallelStream().reduce(\n  \"\",\n  (acc, id) -> acc.isEmpty() ? id : acc + \",\" + id,\n  (a, b) -> a.isEmpty() ? b : b.isEmpty() ? a : a + \",\" + b\n);",
    pipeline: "parallelStream \u2192 reduce(id, acc, combiner)",
    why: "Combiner merges partial results from parallel splits; must be associative.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Omitting combiner on parallel reduce of non-associative ops.",
    senior: "Staff: joining Collector is clearer; know combiner for whiteboard reduce.",
    javaSince: "Java 8",
    tags: ["reduce", "parallel"],
  },
  {
    id: "r03",
    category: "reduce",
    difficulty: "Intermediate",
    title: "Reduce BigDecimal totals",
    problem: "Sum payment amounts with BigDecimal reduce.",
    input: "[10.50, 2.00]",
    output: "12.50",
    solution: "BigDecimal total = amounts.stream()\n  .reduce(BigDecimal.ZERO, BigDecimal::add);",
    pipeline: "stream \u2192 reduce(ZERO, add)",
    why: "Money aggregation must use BigDecimal.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Summing money with double.",
    senior: "ZERO is the correct identity for add.",
    javaSince: "Java 8",
    tags: ["reduce", "fintech"],
  },
  {
    id: "r04",
    category: "reduce",
    difficulty: "Intermediate",
    title: "Optional reduce without identity",
    problem: "Find longest string via reduce without identity.",
    input: "[\"java\",\"stream\",\"api\"]",
    output: "Optional[stream]",
    solution: "Optional<String> longest = words.stream()\n  .reduce((a, b) -> a.length() >= b.length() ? a : b);",
    pipeline: "stream \u2192 reduce(BinaryOperator)",
    why: "Empty stream \u2192 Optional.empty().",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Assuming reduce always returns a value.",
    senior: "Contrast with max(Comparator.comparingInt(String::length)).",
    javaSince: "Java 8",
    tags: ["reduce"],
  },
  {
    id: "r05",
    category: "reduce",
    difficulty: "Advanced",
    title: "Mutable reduction anti-pattern",
    problem: "Show why reduce into a shared mutable List is wrong vs collect.",
    input: "strings",
    output: "list",
    solution: "// WRONG under parallel:\nList<String> bad = stream.reduce(new ArrayList<>(), (l, s) -> { l.add(s); return l; }, (a,b) -> { a.addAll(b); return a; });\n// RIGHT:\nList<String> ok = stream.collect(Collectors.toList());",
    pipeline: "collect \u2192 toList",
    why: "collect is designed for mutable reduction; reduce for immutable folds.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Identity ArrayList shared across threads if mis-specified.",
    senior: "Architect: use collect for mutable accumulators; reduce for pure folds.",
    javaSince: "Java 8",
    tags: ["reduce", "parallel"],
  },
];
