import type {StreamProblem} from './types';

/**
 * Dedicated programs ensuring less-common Stream / primitive / Collector APIs
 * are each covered with a concrete interview-grade example (API coverage matrix).
 */
export const PROBLEMS_API_MATRIX: StreamProblem[] = [
  {
    id: 'api01',
    category: 'api-coverage',
    difficulty: 'Beginner',
    title: 'Stream.of varargs',
    problem: 'Build a stream of known literals without a Collection.',
    input: 'Stream.of("a","b","c")',
    output: '[a, b, c]',
    solution: 'List<String> xs = Stream.of("a", "b", "c").toList();',
    pipeline: 'Stream.of → toList',
    why: 'Lightweight source for fixed elements; ordered, sized.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    alternative: 'List.of(...).stream()',
    trap: 'Stream.of(array) treats the array as ONE element if typed as Object[] — use Arrays.stream.',
    senior: 'Prefer List.of().stream() when you already have a collection; Stream.of for ad-hoc literals.',
    javaSince: 'Java 8',
    tags: ['Stream.of'],
  },
  {
    id: 'api02',
    category: 'api-coverage',
    difficulty: 'Beginner',
    title: 'Stream.empty',
    problem: 'Return an empty stream from a method when there is nothing to process.',
    input: 'no data',
    output: 'count=0; allMatch=true; anyMatch=false',
    solution:
      'Stream<String> s = Stream.empty();\nassert s.count() == 0;\nassert Stream.empty().allMatch(x -> false);\nassert !Stream.empty().anyMatch(x -> true);',
    pipeline: 'Stream.empty → terminal',
    why: 'Avoids null Stream returns; vacuously true allMatch/noneMatch.',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    trap: 'Returning null instead of empty stream — NPE at call site.',
    senior: 'Empty streams are the Stream analogue of Optional.empty / empty collections.',
    javaSince: 'Java 8',
    tags: ['Stream.empty'],
  },
  {
    id: 'api03',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.builder',
    problem: 'Accumulate elements imperatively, then stream once.',
    input: 'conditional adds of tags',
    output: '[java, kafka]',
    solution:
      'Stream.Builder<String> b = Stream.builder();\nif (hasJava) b.add("java");\nif (hasKafka) b.add("kafka");\nList<String> tags = b.build().toList();',
    pipeline: 'builder.add* → build → toList',
    why: 'Useful when the set of elements is decided by branching logic before streaming.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    alternative: 'ArrayList then .stream()',
    trap: 'Calling build() twice — IllegalStateException.',
    senior: 'Builder is rarely needed; ArrayList + stream is usually clearer. Know it for API completeness.',
    javaSince: 'Java 8',
    tags: ['Stream.builder'],
  },
  {
    id: 'api04',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.concat',
    problem: 'Merge two streams into one ordered concatenation.',
    input: 'Stream.of(1,2) + Stream.of(3,4)',
    output: '[1, 2, 3, 4]',
    solution: 'List<Integer> all = Stream.concat(Stream.of(1, 2), Stream.of(3, 4)).toList();',
    pipeline: 'concat(a,b) → toList',
    why: 'Preserves encounter order of first then second; both streams consumed.',
    timeComplexity: 'O(n+m)',
    spaceComplexity: 'O(n+m) if collected',
    alternative: 'Stream.of(a,b).flatMap(s -> s)',
    trap: 'Nested concat of many streams → deep call stacks; prefer flatMap of a list of streams.',
    senior: 'For N streams: sources.stream().flatMap(s -> s) avoids concat nesting.',
    javaSince: 'Java 8',
    tags: ['Stream.concat'],
  },
  {
    id: 'api05',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.iterate with Predicate (Java 9)',
    problem: 'Generate 1,2,4,… while value < 1000.',
    input: 'seed=1, predicate n<1000, next=n*2',
    output: '[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]',
    solution:
      'List<Integer> powers = Stream.iterate(1, n -> n < 1000, n -> n * 2).toList();',
    pipeline: 'iterate(seed, hasNext, next) → toList',
    why: 'Java 9 three-arg iterate is finite without limit — safer than infinite + limit.',
    timeComplexity: 'O(k) steps until predicate fails',
    spaceComplexity: 'O(k)',
    alternative: 'Stream.iterate(1, n -> n * 2).takeWhile(n -> n < 1000)',
    trap: 'Two-arg iterate is infinite — forgetting limit/takeWhile hangs collect.',
    senior: 'Prefer three-arg iterate or takeWhile for bounded sequences in production.',
    javaSince: 'Java 9',
    tags: ['Stream.iterate'],
  },
  {
    id: 'api06',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.generate + limit',
    problem: 'Generate 5 random UUIDs safely.',
    input: 'UUID.randomUUID',
    output: '5 UUID strings',
    solution:
      'List<String> ids = Stream.generate(() -> UUID.randomUUID().toString()).limit(5).toList();',
    pipeline: 'generate → limit → toList',
    why: 'Infinite supplier must be bounded by limit/find*/takeWhile.',
    timeComplexity: 'O(limit)',
    spaceComplexity: 'O(limit)',
    trap: 'collect without limit on generate → OOM.',
    senior: 'generate is for synthetic data / fuzzing — not business event streams (use Kafka).',
    javaSince: 'Java 8',
    tags: ['Stream.generate'],
  },
  {
    id: 'api07',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.ofNullable edge cases',
    problem: 'Flatten a nullable field into 0 or 1 elements.',
    input: 'null vs "x"',
    output: '[] vs [x]',
    solution:
      'List<String> a = Stream.ofNullable(null).toList();\nList<String> b = Stream.ofNullable("x").toList();',
    pipeline: 'ofNullable → toList',
    why: 'Replaces null-check before Stream.of(value).',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    alternative: 'Optional.ofNullable(v).stream()',
    trap: 'ofNullable does not deep-flatten nested Optionals.',
    senior: 'Use at API boundaries where nulls still exist; prefer Optional.stream inside pipelines.',
    javaSince: 'Java 9',
    tags: ['Stream.ofNullable'],
  },
  {
    id: 'api08',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'takeWhile vs filter',
    problem: 'On sorted amounts, take prefix under 100 vs filter all under 100.',
    input: '[10,20,150,30] sorted? assume sorted [10,20,30,150]',
    output: 'takeWhile→[10,20,30]; filter→[10,20,30]',
    solution:
      'var sorted = List.of(10, 20, 30, 150);\nList<Integer> prefix = sorted.stream().takeWhile(n -> n < 100).toList();\nList<Integer> all = sorted.stream().filter(n -> n < 100).toList();',
    pipeline: 'takeWhile (stops) vs filter (scans all)',
    why: 'takeWhile short-circuits on first failure — O(k) prefix.',
    timeComplexity: 'takeWhile O(k); filter O(n)',
    spaceComplexity: 'O(k)',
    trap: 'takeWhile on unsorted data is NOT a global filter.',
    senior: 'Interview differentiator: prefix semantics vs global filter.',
    javaSince: 'Java 9',
    tags: ['takeWhile'],
  },
  {
    id: 'api09',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'dropWhile',
    problem: 'Skip a sorted header of amounts under 100, keep the rest.',
    input: '[10,20,30,150,200]',
    output: '[150, 200]',
    solution: 'List.of(10, 20, 30, 150, 200).stream().dropWhile(n -> n < 100).toList();',
    pipeline: 'dropWhile → toList',
    why: 'Complement of takeWhile for prefix skipping.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n-k)',
    trap: 'Parallel unordered sources weaken dropWhile guarantees.',
    senior: 'Pair with sorted streams or ordered files/logs.',
    javaSince: 'Java 9',
    tags: ['dropWhile'],
  },
  {
    id: 'api10',
    category: 'api-coverage',
    difficulty: 'Expert',
    title: 'mapMulti (Java 16)',
    problem: 'Emit 0..n for each n without allocating nested streams.',
    input: '[2,3]',
    output: '[0,1, 0,1,2]',
    solution:
      'List<Integer> out = List.of(2, 3).stream()\n  .<Integer>mapMulti((n, sink) -> { for (int i = 0; i < n; i++) sink.accept(i); })\n  .toList();',
    pipeline: 'mapMulti → toList',
    why: 'Imperative flatMap; can be cheaper than flatMap(IntStream::boxed).',
    timeComplexity: 'O(sum of emitted)',
    spaceComplexity: 'O(output)',
    alternative: 'flatMap(n -> IntStream.range(0, n).boxed())',
    trap: 'Unreadable mapMulti when filter+map suffices.',
    senior: 'Reach for mapMulti in hot paths after profiling — not by default.',
    javaSince: 'Java 16',
    tags: ['mapMulti'],
  },
  {
    id: 'api11',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.toList vs Collectors.toList',
    problem: 'Materialize an unmodifiable list (Java 16+).',
    input: 'Stream.of(1,2,3)',
    output: 'unmodifiable [1,2,3]',
    solution:
      'List<Integer> a = Stream.of(1, 2, 3).toList(); // unmodifiable\nList<Integer> b = Stream.of(1, 2, 3).collect(Collectors.toList()); // mutable ArrayList',
    pipeline: 'toList() vs collect(toList())',
    why: 'toList() is concise and unmodifiable — safer API returns.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    trap: 'Calling add on Stream.toList() → UnsupportedOperationException.',
    senior: 'Know Java 16 toList(); Collectors.toUnmodifiableList() is Java 10 equivalent collect form.',
    javaSince: 'Java 16',
    tags: ['Stream.toList'],
  },
  {
    id: 'api12',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Stream.toArray',
    problem: 'Convert stream to typed array for legacy APIs.',
    input: 'Stream.of("a","b")',
    output: 'String[]{"a","b"}',
    solution: 'String[] arr = Stream.of("a", "b").toArray(String[]::new);',
    pipeline: 'stream → toArray(generator)',
    why: 'Interops with array-based APIs; prefer List in modern code.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    trap: 'toArray() without generator returns Object[].',
    senior: 'IntStream.toArray() returns int[] without boxing — prefer for primitives.',
    javaSince: 'Java 8',
    tags: ['Stream.toArray'],
  },
  {
    id: 'api13',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'Stream.iterator',
    problem: 'Hand a stream to a legacy Iterator consumer once.',
    input: 'Stream.of(1,2,3)',
    output: 'consume via hasNext/next',
    solution:
      'Iterator<Integer> it = Stream.of(1, 2, 3).iterator();\nint sum = 0;\nwhile (it.hasNext()) sum += it.next();',
    pipeline: 'stream → iterator (terminal-ish pull)',
    why: 'Bridge to Iterator-based libraries; still single-use.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) extra',
    trap: 'Holding the iterator while also using the stream.',
    senior: 'Prefer forEachRemaining / collect; iterator is an escape hatch.',
    javaSince: 'Java 8',
    tags: ['Stream.iterator'],
  },
  {
    id: 'api14',
    category: 'api-coverage',
    difficulty: 'Staff',
    title: 'Stream.spliterator',
    problem: 'Obtain the Spliterator to inspect characteristics or custom traverse.',
    input: 'List.of(1,2,3).stream()',
    output: 'SIZED|ORDERED|…; tryAdvance visits elements',
    solution:
      'Spliterator<Integer> sp = List.of(1, 2, 3).stream().spliterator();\nassert (sp.characteristics() & Spliterator.SIZED) != 0;\nsp.forEachRemaining(System.out::println);',
    pipeline: 'stream → spliterator → tryAdvance/forEachRemaining',
    why: 'Exposes parallel splitting contract without parallelStream().',
    timeComplexity: 'O(n) to drain',
    spaceComplexity: 'O(1)',
    trap: 'Using both stream terminal and spliterator on same stream.',
    senior: 'Staff topic: characteristics explain when parallel pays off.',
    javaSince: 'Java 8',
    tags: ['Stream.spliterator'],
  },
  {
    id: 'api15',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'isParallel / sequential / parallel',
    problem: 'Toggle parallel mode mid-pipeline and inspect.',
    input: 'list.stream()',
    output: 'false → true → false',
    solution:
      'var s = List.of(1, 2, 3, 4).stream();\nboolean a = s.isParallel(); // false\nvar p = List.of(1, 2, 3, 4).stream().parallel();\nboolean b = p.isParallel(); // true\nvar back = p.sequential();\nboolean c = back.isParallel(); // false\nint sum = back.mapToInt(Integer::intValue).sum();',
    pipeline: 'stream → parallel → sequential → terminal',
    why: 'Mode is a pipeline property; last mode before terminal wins.',
    timeComplexity: 'same O(n); constant factors differ',
    spaceComplexity: 'O(1) for sum',
    trap: 'Calling parallel() then assuming order-sensitive ops stay stable.',
    senior: 'Don\'t flip parallel mid-pipeline as a "micro-optimization"; decide at source.',
    javaSince: 'Java 8',
    tags: ['isParallel', 'parallel', 'sequential'],
  },
  {
    id: 'api16',
    category: 'api-coverage',
    difficulty: 'Expert',
    title: 'unordered for parallel distinct',
    problem: 'Relax encounter order to speed parallel distinct when order unused.',
    input: 'large List with duplicates',
    output: 'count of unique',
    solution: 'long n = data.parallelStream().unordered().distinct().count();',
    pipeline: 'parallel → unordered → distinct → count',
    why: 'ORDERED + distinct forces coordination; unordered helps.',
    timeComplexity: 'O(n) average',
    spaceComplexity: 'O(unique)',
    trap: 'unordered when API contract requires stable first-occurrence order.',
    senior: 'Document determinism loss; measure before/after.',
    javaSince: 'Java 8',
    tags: ['unordered'],
  },
  {
    id: 'api17',
    category: 'api-coverage',
    difficulty: 'Staff',
    title: 'onClose + close (Files.lines)',
    problem: 'Register cleanup and ensure AutoCloseable streams release resources.',
    input: 'Path to log file',
    output: 'line count; file handle closed',
    solution:
      'long lines;\ntry (Stream<String> s = Files.lines(path).onClose(() -> log.info("closed"))) {\n  lines = s.count();\n} // close() invoked by try-with-resources; runs onClose handlers',
    pipeline: 'Files.lines → onClose → count → close',
    why: 'Resource streams must close; onClose composes cleanup hooks.',
    timeComplexity: 'O(lines)',
    spaceComplexity: 'O(1) for count',
    trap: 'Forgetting try-with-resources → FD leak under load.',
    senior: 'Any Stream from IO (JDBC, Files) is AutoCloseable — treat like a connection.',
    javaSince: 'Java 8',
    tags: ['onClose', 'close'],
  },
  {
    id: 'api18',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'IntStream.range vs rangeClosed',
    problem: 'Sum 1..n inclusive and exclusive upper bound.',
    input: 'n=5',
    output: 'range(1,5)=10; rangeClosed(1,5)=15',
    solution:
      'int a = IntStream.range(1, 5).sum();\nint b = IntStream.rangeClosed(1, 5).sum();',
    pipeline: 'range / rangeClosed → sum',
    why: 'Classic off-by-one interview trap.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    trap: 'Using range when inclusive end was required.',
    senior: 'Prefer rangeClosed when domain is inclusive integers.',
    javaSince: 'Java 8',
    tags: ['range', 'rangeClosed'],
  },
  {
    id: 'api19',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Primitive summaryStatistics',
    problem: 'One pass min/max/sum/avg/count on doubles.',
    input: 'DoubleStream.of(1.5, 2.5, 3.0)',
    output: 'count=3, sum=7.0, min=1.5, max=3.0, avg≈2.333',
    solution:
      'DoubleSummaryStatistics st = DoubleStream.of(1.5, 2.5, 3.0).summaryStatistics();\n// st.getCount(), getSum(), getMin(), getMax(), getAverage()',
    pipeline: 'DoubleStream → summaryStatistics',
    why: 'Single pass multi-stat without teeing.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    alternative: 'Collectors.summarizingDouble on Stream<T>',
    trap: 'Empty stream: min/max are ±Infinity for DoubleSummaryStatistics.',
    senior: 'Prefer summaryStatistics over multiple terminals (stream is single-use).',
    javaSince: 'Java 8',
    tags: ['summaryStatistics'],
  },
  {
    id: 'api20',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'boxed + mapToObj',
    problem: 'Convert IntStream to Stream<Integer> and to Stream<String>.',
    input: 'IntStream.rangeClosed(1,3)',
    output: '[1,2,3] and ["#1","#2","#3"]',
    solution:
      'List<Integer> boxed = IntStream.rangeClosed(1, 3).boxed().toList();\nList<String> labels = IntStream.rangeClosed(1, 3).mapToObj(i -> "#" + i).toList();',
    pipeline: 'IntStream → boxed|mapToObj → toList',
    why: 'Bridge primitives to object collectors / DTOs.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    trap: 'Boxing large streams then grouping — GC pressure.',
    senior: 'Stay primitive until you need object Collectors.',
    javaSince: 'Java 8',
    tags: ['boxed', 'mapToObj'],
  },
  {
    id: 'api21',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'mapToInt / mapToLong / mapToDouble',
    problem: 'Extract numeric fields without boxing in the reduction.',
    input: 'employees salaries',
    output: 'sum / longSum / avg',
    solution:
      'int sum = emps.stream().mapToInt(e -> (int) e.salary()).sum();\nlong longSum = emps.stream().mapToLong(e -> (long) e.salary()).sum();\ndouble avg = emps.stream().mapToDouble(Employee::salary).average().orElse(0);',
    pipeline: 'stream → mapTo* → sum|average',
    why: 'Avoids Stream<Integer> boxing on hot paths.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    trap: 'Casting double salary to int silently truncates money — use BigDecimal in FinTech.',
    senior: 'mapToDouble for analytics; BigDecimal + reducing for money.',
    javaSince: 'Java 8',
    tags: ['mapToInt', 'mapToLong', 'mapToDouble'],
  },
  {
    id: 'api22',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'flatMapToInt / flatMapToLong / flatMapToDouble',
    problem: 'Flatten nested numeric structures into one primitive stream.',
    input: 'List<int[]> segments',
    output: 'sum of all ints; sum of longs; sum of doubles',
    solution:
      'int sumI = segments.stream().flatMapToInt(Arrays::stream).sum();\nlong sumL = longSegments.stream().flatMapToLong(Arrays::stream).sum();\ndouble sumD = doubleSegments.stream().flatMapToDouble(Arrays::stream).sum();',
    pipeline: 'stream → flatMapTo* → sum',
    why: 'Primitive flatMap avoids boxing nested arrays.',
    timeComplexity: 'O(total elements)',
    spaceComplexity: 'O(1) for sum',
    trap: 'flatMap(arr -> Arrays.stream(arr).boxed()) when flatMapToInt works.',
    senior: 'Prefer flatMapTo* for sensor/time-series buffers.',
    javaSince: 'Java 8',
    tags: ['flatMapToInt', 'flatMapToLong', 'flatMapToDouble'],
  },
  {
    id: 'api23',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'Collectors.toUnmodifiable*',
    problem: 'Publish immutable list/set/map results from a collector.',
    input: 'names / ids',
    output: 'unmodifiable collections',
    solution:
      'List<String> list = names.stream().collect(Collectors.toUnmodifiableList());\nSet<String> set = names.stream().collect(Collectors.toUnmodifiableSet());\nMap<Long,String> map = emps.stream().collect(\n  Collectors.toUnmodifiableMap(Employee::id, Employee::name));',
    pipeline: 'collect(toUnmodifiable*)',
    why: 'Defensive API returns without wrapping later.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    alternative: 'stream.toList() for lists (Java 16+)',
    trap: 'toUnmodifiableMap without merge on duplicate keys throws.',
    senior: 'Immutability at boundaries beats documenting "please don’t mutate".',
    javaSince: 'Java 10',
    tags: ['toUnmodifiableList', 'toUnmodifiableSet', 'toUnmodifiableMap'],
  },
  {
    id: 'api24',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'summarizingLong / summarizingDouble',
    problem: 'Collect multi-stats for long and double fields.',
    input: 'orders volumes / prices',
    output: 'LongSummaryStatistics / DoubleSummaryStatistics',
    solution:
      'LongSummaryStatistics vol = orders.stream().collect(Collectors.summarizingLong(Order::volume));\nDoubleSummaryStatistics px = orders.stream().collect(Collectors.summarizingDouble(Order::price));',
    pipeline: 'collect(summarizingLong|Double)',
    why: 'Same one-pass idea as summarizingInt.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    trap: 'Using summarizingDouble for money — prefer BigDecimal reducing.',
    senior: 'Pick the summarizing* matching field width to avoid overflow/cast.',
    javaSince: 'Java 8',
    tags: ['summarizingLong', 'summarizingDouble'],
  },
  {
    id: 'api25',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'Collectors.reducing',
    problem: 'Downstream reduce inside groupingBy for BigDecimal totals.',
    input: 'payments by merchant',
    output: 'Map<merchant, BigDecimal total>',
    solution:
      'Map<String, BigDecimal> totals = payments.stream().collect(\n  Collectors.groupingBy(Payment::merchantId,\n    Collectors.mapping(Payment::amount,\n      Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))));',
    pipeline: 'groupingBy → mapping → reducing',
    why: 'reducing as downstream when summingInt cannot apply (BigDecimal).',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(groups)',
    alternative: 'teeing count+sum; or custom collector',
    trap: 'reducing without identity returns Optional — easy NPE if ignored.',
    senior: 'Know 1/2/3-arg Collectors.reducing overloads.',
    javaSince: 'Java 8',
    tags: ['Collectors.reducing'],
  },
  {
    id: 'api26',
    category: 'api-coverage',
    difficulty: 'Staff',
    title: 'Collector characteristics (CONCURRENT / UNORDERED / IDENTITY_FINISH)',
    problem: 'Explain why a custom collector may or may not run concurrently.',
    input: 'custom Collector',
    output: 'characteristics set drives parallel strategy',
    solution:
      'Collector<T, List<T>, List<T>> c = Collector.of(\n  ArrayList::new, List::add,\n  (a, b) -> { a.addAll(b); return a; },\n  Collector.Characteristics.IDENTITY_FINISH);\n// CONCURRENT: accumulator thread-safe shared container\n// UNORDERED: order irrelevant\n// IDENTITY_FINISH: finisher is identity — skip finish step',
    pipeline: 'Collector.of(..., characteristics)',
    why: 'Framework uses flags to pick concurrent accumulation vs partial+combiner.',
    timeComplexity: 'depends',
    spaceComplexity: 'depends',
    trap: 'Marking CONCURRENT without a thread-safe container → races.',
    senior: 'IDENTITY_FINISH is why casting A→R is safe for toList-like collectors.',
    javaSince: 'Java 8',
    tags: ['CONCURRENT', 'UNORDERED', 'IDENTITY_FINISH'],
  },
  {
    id: 'api27',
    category: 'api-coverage',
    difficulty: 'Staff',
    title: 'Associativity of reduce',
    problem: 'Show why string concat reduce needs a combiner and still may be wrong for parallel.',
    input: '["a","b","c"]',
    output: 'sequential "abc"; parallel needs associative op',
    solution:
      'String seq = Stream.of("a", "b", "c").reduce("", String::concat);\nString par = Stream.of("a", "b", "c").parallel().reduce("", String::concat, String::concat);\n// Prefer Collectors.joining() — designed for this',
    pipeline: 'reduce(id, acc, combiner)',
    why: 'Parallel splits require associative combiner matching accumulator.',
    timeComplexity: 'O(n) but concat is O(n²) chars — bad',
    spaceComplexity: 'O(n)',
    alternative: 'Collectors.joining()',
    trap: 'Non-associative accumulator (e.g. subtraction) → wrong parallel results.',
    senior: 'Interview gold: associativity + identity laws for parallel reduce.',
    javaSince: 'Java 8',
    tags: ['reduce', 'associativity'],
  },
  {
    id: 'api28',
    category: 'api-coverage',
    difficulty: 'Expert',
    title: 'Custom Spliterator trySplit',
    problem: 'Sketch a sized range Spliterator that splits in half.',
    input: 'range [0, 8)',
    output: 'split into [0,4) and [4,8)',
    solution:
      'final class RangeSpliterator implements Spliterator.OfInt {\n  int start, end;\n  RangeSpliterator(int s, int e) { start = s; end = e; }\n  public boolean tryAdvance(IntConsumer a) {\n    if (start >= end) return false; a.accept(start++); return true;\n  }\n  public OfInt trySplit() {\n    int size = end - start; if (size < 2) return null;\n    int mid = start + size / 2;\n    OfInt left = new RangeSpliterator(start, mid); start = mid; return left;\n  }\n  public long estimateSize() { return (long) end - start; }\n  public int characteristics() { return SIZED | SUBSIZED | ORDERED | IMMUTABLE; }\n}',
    pipeline: 'trySplit → ForkJoin tasks → tryAdvance',
    why: 'Shows how parallel streams get work.',
    timeComplexity: 'O(n) total advances',
    spaceComplexity: 'O(log n) split tree',
    trap: 'Broken trySplit (overlapping ranges) → lost/duplicate elements.',
    senior: 'You rarely write this — but Staff interviews expect the story.',
    javaSince: 'Java 8',
    tags: ['Spliterator', 'trySplit', 'tryAdvance'],
  },
  {
    id: 'api29',
    category: 'api-coverage',
    difficulty: 'Intermediate',
    title: 'LongStream / DoubleStream factories',
    problem: 'Use LongStream.rangeClosed and DoubleStream.of for analytics.',
    input: '1..1_000_000L; prices',
    output: 'sum; average',
    solution:
      'long sum = LongStream.rangeClosed(1, 1_000_000L).sum();\ndouble avg = DoubleStream.of(1.0, 2.0, 4.0).average().orElseThrow();',
    pipeline: 'LongStream/DoubleStream → sum|average',
    why: 'Symmetric primitive APIs to IntStream.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    trap: 'Mixing DoubleStream sum with money.',
    senior: 'Know all three primitive stream types exist with parallel support.',
    javaSince: 'Java 8',
    tags: ['LongStream', 'DoubleStream'],
  },
  {
    id: 'api30',
    category: 'api-coverage',
    difficulty: 'Advanced',
    title: 'Collectors.toCollection + filtering + flatMapping',
    problem: 'TreeSet of distinct cities from active employees only; flatten skills to a Set.',
    input: 'employees',
    output: 'TreeSet cities; Set skills',
    solution:
      'TreeSet<String> cities = emps.stream()\n  .collect(Collectors.filtering(Employee::active,\n    Collectors.mapping(Employee::city, Collectors.toCollection(TreeSet::new))));\nSet<String> skills = emps.stream()\n  .collect(Collectors.flatMapping(e -> e.skills().stream(), Collectors.toSet()));',
    pipeline: 'filtering/flatMapping downstream → toCollection/toSet',
    why: 'Downstream collectors compose without extra filter stages.',
    timeComplexity: 'O(n log k) for TreeSet',
    spaceComplexity: 'O(k)',
    trap: 'filtering collector still sees all upstream elements — filter early if huge.',
    senior: 'Java 9 filtering/flatMapping collectors — know vs intermediate filter/flatMap.',
    javaSince: 'Java 9',
    tags: ['toCollection', 'filtering', 'flatMapping'],
  },
];
