import type {StreamProblem} from './types';

export const PROBLEMS_DOMAIN: StreamProblem[] = [
  {
    id: "s01",
    category: "strings",
    difficulty: "Beginner",
    title: "Count characters",
    problem: "Count occurrences of a character in a string via chars().",
    input: "\"banana\", char a",
    output: "3",
    solution: "long n = \"banana\".chars().filter(c -> c == 'a').count();",
    pipeline: "chars \u2192 filter \u2192 count",
    why: "chars() is IntStream of UTF-16 code units.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "chars() vs codePoints() for supplementary chars.",
    senior: "Mention codePoints in Unicode follow-ups.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s02",
    category: "strings",
    difficulty: "Intermediate",
    title: "Anagram check with Streams",
    problem: "Check if two strings are anagrams (ignore case, ignore spaces).",
    input: "\"Listen\",\"Silent\"",
    output: "true",
    solution: "boolean anagram = Stream.of(a, b)\n  .map(s -> s.toLowerCase(Locale.ROOT).replaceAll(\"\\\\s+\", \"\"))\n  .map(s -> s.chars().sorted().mapToObj(c -> String.valueOf((char)c)).collect(Collectors.joining()))\n  .distinct().count() == 1;",
    pipeline: "normalize \u2192 sort chars \u2192 compare",
    why: "Anagrams share the same sorted character multiset.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Not normalizing case/spaces.",
    senior: "Alternative: frequency maps with groupingBy.",
    alternative: "Map<Character, Long> freq(String s) {\n  return s.toLowerCase(Locale.ROOT).replaceAll(\"\\\\s+\", \"\").chars()\n    .mapToObj(c -> (char)c)\n    .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));\n}\nboolean ok = freq(a).equals(freq(b));",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s03",
    category: "strings",
    difficulty: "Intermediate",
    title: "Reverse words in sentence",
    problem: "Reverse word order using Streams.",
    input: "\"java stream api\"",
    output: "api stream java",
    solution: "String rev = Arrays.stream(\"java stream api\".split(\"\\\\s+\"))\n  .collect(Collectors.collectingAndThen(Collectors.toList(), list -> {\n    Collections.reverse(list);\n    return String.join(\" \", list);\n  }));",
    pipeline: "split \u2192 stream \u2192 reverse list \u2192 join",
    why: "collectingAndThen allows an in-place reverse finisher.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Reversing characters instead of words.",
    senior: "Clarify word vs character reverse.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s04",
    category: "strings",
    difficulty: "Beginner",
    title: "Join with joining",
    problem: "CSV-join tokens.",
    input: "[\"a\",\"b\",\"c\"]",
    output: "a,b,c",
    solution: "String csv = Stream.of(\"a\",\"b\",\"c\").collect(Collectors.joining(\",\"));",
    pipeline: "stream \u2192 joining",
    why: "Idiomatic join.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Trailing comma from manual loops.",
    senior: "joining handles separators cleanly.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s05",
    category: "strings",
    difficulty: "Advanced",
    title: "Longest word",
    problem: "Find longest word in a sentence.",
    input: "\"the stream pipeline\"",
    output: "pipeline",
    solution: "Optional<String> longest = Arrays.stream(sentence.split(\"\\\\s+\"))\n  .max(Comparator.comparingInt(String::length));",
    pipeline: "split \u2192 stream \u2192 max(by length)",
    why: "max with Comparator on length.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Ties \u2014 define first vs last policy.",
    senior: "thenComparing for stable tie-break.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s06",
    category: "strings",
    difficulty: "Intermediate",
    title: "Palindrome words filter",
    problem: "Keep palindromic tokens ignoring case.",
    input: "\"Level stream Kayak\"",
    output: "[Level, Kayak]",
    solution: "List<String> pals = Arrays.stream(sentence.split(\"\\\\s+\"))\n  .filter(w -> {\n    String s = w.toLowerCase(Locale.ROOT);\n    return new StringBuilder(s).reverse().toString().equals(s);\n  })\n  .toList();",
    pipeline: "split \u2192 filter(palindrome) \u2192 toList",
    why: "Filter with a local normalization.",
    timeComplexity: "O(n*m)",
    spaceComplexity: "O(k)",
    trap: "Mutating StringBuilder across elements.",
    senior: "Keep predicate pure.",
    javaSince: "Java 16",
    tags: ["strings"],
  },
  {
    id: "s07",
    category: "strings",
    difficulty: "Expert",
    title: "First non-repeated char (string category)",
    problem: "Return first non-repeated character or empty.",
    input: "\"aabbcdde\"",
    output: "c",
    solution: "Optional<Character> c = \"aabbcdde\".chars().mapToObj(ch -> (char) ch)\n  .collect(Collectors.groupingBy(Function.identity(), LinkedHashMap::new, Collectors.counting()))\n  .entrySet().stream().filter(e -> e.getValue() == 1).map(Map.Entry::getKey).findFirst();",
    pipeline: "chars \u2192 LinkedHashMap frequencies \u2192 findFirst count==1",
    why: "Order-preserving frequency map.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(alphabet)",
    trap: "Using HashMap then min index scan without care.",
    senior: "LinkedHashMap is the Stream-friendly solution.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s08",
    category: "strings",
    difficulty: "Intermediate",
    title: "Remove duplicate chars preserve order",
    problem: "Distinct characters in encounter order.",
    input: "\"banana\"",
    output: "ban",
    solution: "String out = \"banana\".chars().mapToObj(c -> String.valueOf((char)c))\n  .distinct().collect(Collectors.joining());",
    pipeline: "chars \u2192 mapToObj \u2192 distinct \u2192 joining",
    why: "distinct preserves encounter order sequentially.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Parallel distinct order.",
    senior: "Keep sequential for order-sensitive string transforms.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s09",
    category: "strings",
    difficulty: "Beginner",
    title: "Count vowels",
    problem: "Count vowels in a word.",
    input: "\"Meridian\"",
    output: "4",
    solution: "long v = \"Meridian\".toLowerCase(Locale.ROOT).chars().filter(c -> \"aeiou\".indexOf(c) >= 0).count();",
    pipeline: "chars \u2192 filter(vowel) \u2192 count",
    why: "Simple IntStream filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Locale issues with Turkish i.",
    senior: "Use Locale.ROOT for ASCII-oriented interview problems.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s10",
    category: "strings",
    difficulty: "Advanced",
    title: "Group words by length",
    problem: "Map length \u2192 list of words.",
    input: "[\"java\",\"go\",\"rust\",\"c\"]",
    output: "{4=[java,rust], 2=[go], 1=[c]}",
    solution: "Map<Integer, List<String>> byLen = words.stream()\n  .collect(Collectors.groupingBy(String::length));",
    pipeline: "stream \u2192 groupingBy(length)",
    why: "Classifier on String::length.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Sorting groups without TreeMap.",
    senior: "Add TreeMap::new if sorted lengths required.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s11",
    category: "strings",
    difficulty: "Intermediate",
    title: "Pattern.splitAsStream",
    problem: "Extract numbers from a noisy string.",
    input: "\"order-12,qty=3;ok\"",
    output: "[12, 3]",
    solution: "List<Integer> nums = Pattern.compile(\"\\\\D+\").splitAsStream(\"order-12,qty=3;ok\")\n  .filter(s -> !s.isBlank())\n  .map(Integer::valueOf)\n  .toList();",
    pipeline: "Pattern.splitAsStream \u2192 filter \u2192 map \u2192 toList",
    why: "splitAsStream avoids intermediate arrays.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Compiling Pattern inside a loop.",
    senior: "Reuse static final Pattern.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s12",
    category: "strings",
    difficulty: "Staff",
    title: "Case-insensitive frequency",
    problem: "Word frequency ignoring case.",
    input: "\"Java java JAVA\"",
    output: "{java=3}",
    solution: "Map<String, Long> freq = Arrays.stream(text.split(\"\\\\s+\"))\n  .map(s -> s.toLowerCase(Locale.ROOT))\n  .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));",
    pipeline: "split \u2192 toLowerCase \u2192 groupingBy counting",
    why: "Normalize before grouping.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Grouping raw case variants as different keys.",
    senior: "Normalize early in text pipelines.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s13",
    category: "strings",
    difficulty: "Beginner",
    title: "StartsWith filter",
    problem: "Filter packages starting with com.bank.",
    input: "package names",
    output: "filtered list",
    solution: "List<String> bank = pkgs.stream().filter(p -> p.startsWith(\"com.bank.\")).toList();",
    pipeline: "stream \u2192 filter(startsWith) \u2192 toList",
    why: "Prefix filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "regex when startsWith suffices.",
    senior: "Prefer startsWith for literal prefixes.",
    javaSince: "Java 16",
    tags: ["strings"],
  },
  {
    id: "s14",
    category: "strings",
    difficulty: "Advanced",
    title: "Longest common prefix via Streams (pairwise reduce)",
    problem: "Find LCP of a list of strings using reduce.",
    input: "[\"flower\",\"flow\",\"flight\"]",
    output: "fl",
    solution: "Optional<String> lcp = words.stream().reduce((a, b) -> {\n  int i = 0;\n  int n = Math.min(a.length(), b.length());\n  while (i < n && a.charAt(i) == b.charAt(i)) i++;\n  return a.substring(0, i);\n});",
    pipeline: "stream \u2192 reduce(pairwise LCP)",
    why: "Associative LCP reduction.",
    timeComplexity: "O(n*m)",
    spaceComplexity: "O(m)",
    trap: "Parallel reduce with non-associative string ops carefully.",
    senior: "LCP reduce is associative \u2014 parallel-safe.",
    javaSince: "Java 8",
    tags: ["strings"],
  },
  {
    id: "s15",
    category: "strings",
    difficulty: "Intermediate",
    title: "Sort by length then alpha",
    problem: "Sort words by length ascending, then alphabetically.",
    input: "[\"pear\",\"fig\",\"apple\"]",
    output: "[fig, pear, apple]",
    solution: "List<String> sorted = words.stream()\n  .sorted(Comparator.comparingInt(String::length).thenComparing(Comparator.naturalOrder()))\n  .toList();",
    pipeline: "stream \u2192 sorted(length then alpha) \u2192 toList",
    why: "thenComparing chains criteria.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Only sorting by length leaving unstable ties.",
    senior: "Always define tie-breakers in interviews.",
    javaSince: "Java 16",
    tags: ["strings"],
  },
  {
    id: "al01",
    category: "arrays-lists",
    difficulty: "Beginner",
    title: "Array to Stream sum",
    problem: "Sum int array.",
    input: "[1,2,3]",
    output: "6",
    solution: "int sum = Arrays.stream(new int[]{1,2,3}).sum();",
    pipeline: "Arrays.stream \u2192 sum",
    why: "Arrays.stream for primitives.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Stream.of(intArray) boxes to Stream<int[]> one element.",
    senior: "Critical trap: Stream.of(array) vs Arrays.stream(array).",
    javaSince: "Java 8",
    tags: ["arrays-lists"],
  },
  {
    id: "al02",
    category: "arrays-lists",
    difficulty: "Intermediate",
    title: "Two lists zip via IntStream",
    problem: "Zip names and scores into 'name=score' strings.",
    input: "names, scores same length",
    output: "[Ada=10, ...]",
    solution: "List<String> zipped = IntStream.range(0, names.size())\n  .mapToObj(i -> names.get(i) + \"=\" + scores.get(i))\n  .toList();",
    pipeline: "IntStream.range \u2192 mapToObj \u2192 toList",
    why: "Index-based zip without third-party libs.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Assuming lists same size without check.",
    senior: "Validate sizes; Streams don't zip natively.",
    javaSince: "Java 16",
    tags: ["arrays-lists"],
  },
  {
    id: "al03",
    category: "arrays-lists",
    difficulty: "Intermediate",
    title: "Partition list by predicate to two lists",
    problem: "Split numbers into evens and odds lists via partitioningBy.",
    input: "[1,2,3,4]",
    output: "evens/odds",
    solution: "Map<Boolean, List<Integer>> m = nums.stream().collect(Collectors.partitioningBy(n -> n % 2 == 0));\nList<Integer> evens = m.get(true);\nList<Integer> odds = m.get(false);",
    pipeline: "stream \u2192 partitioningBy",
    why: "Cleaner than two filters.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Two-pass filter for both sides on huge data.",
    senior: "One pass with partitioningBy.",
    javaSince: "Java 8",
    tags: ["arrays-lists"],
  },
  {
    id: "al04",
    category: "arrays-lists",
    difficulty: "Advanced",
    title: "Sliding window sums",
    problem: "Compute sum of each window of size k.",
    input: "[1,2,3,4,5], k=3",
    output: "[6,9,12]",
    solution: "List<Integer> windowSums = IntStream.rangeClosed(0, nums.size() - k)\n  .mapToObj(i -> nums.subList(i, i + k).stream().mapToInt(Integer::intValue).sum())\n  .toList();",
    pipeline: "range \u2192 mapToObj(subList sum)",
    why: "Index windows over a random-access list.",
    timeComplexity: "O(n*k)",
    spaceComplexity: "O(n)",
    trap: "subList on non-RandomAccess lists repeatedly.",
    senior: "Follow-up: O(n) sliding with running sum.",
    javaSince: "Java 16",
    tags: ["arrays-lists"],
  },
  {
    id: "al05",
    category: "arrays-lists",
    difficulty: "Beginner",
    title: "Convert Stream to array",
    problem: "Materialize String stream to array.",
    input: "[\"a\",\"b\"]",
    output: "String[]",
    solution: "String[] arr = Stream.of(\"a\",\"b\").toArray(String[]::new);",
    pipeline: "stream \u2192 toArray(generator)",
    why: "toArray with generator avoids Object[].",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "toArray() returning Object[].",
    senior: "Always pass String[]::new (or typed generator).",
    javaSince: "Java 8",
    tags: ["arrays-lists"],
  },
  {
    id: "mp01",
    category: "maps",
    difficulty: "Beginner",
    title: "Stream map values",
    problem: "Collect values greater than 10.",
    input: "{a:5,b:15}",
    output: "[15]",
    solution: "List<Integer> vals = map.values().stream().filter(v -> v > 10).toList();",
    pipeline: "values \u2192 filter \u2192 toList",
    why: "Stream map.values() or entrySet().",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "map.stream() compile error.",
    senior: "entrySet when you need keys too.",
    javaSince: "Java 16",
    tags: ["maps"],
  },
  {
    id: "mp02",
    category: "maps",
    difficulty: "Intermediate",
    title: "Invert map (value \u2192 list of keys)",
    problem: "Invert Map<String,String> grouping keys by value.",
    input: "{a:X,b:Y,c:X}",
    output: "{X=[a,c], Y=[b]}",
    solution: "Map<String, List<String>> inverted = map.entrySet().stream()\n  .collect(Collectors.groupingBy(Map.Entry::getValue,\n      Collectors.mapping(Map.Entry::getKey, Collectors.toList())));",
    pipeline: "entrySet \u2192 groupingBy(value, mapping(key))",
    why: "Multi-valued invert handles non-unique values.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "toMap invert without merge on duplicate values.",
    senior: "groupingBy is the safe invert.",
    javaSince: "Java 8",
    tags: ["maps"],
  },
  {
    id: "mp03",
    category: "maps",
    difficulty: "Advanced",
    title: "Sort map by value",
    problem: "Return keys sorted by value descending.",
    input: "{a:2,b:5,c:1}",
    output: "[b, a, c]",
    solution: "List<String> keys = map.entrySet().stream()\n  .sorted(Map.Entry.<String,Integer>comparingByValue().reversed())\n  .map(Map.Entry::getKey)\n  .toList();",
    pipeline: "entrySet \u2192 sorted(byValue) \u2192 map(key)",
    why: "Maps don't sort in place via Streams; produce a list/LinkedHashMap.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Expecting HashMap to become sorted.",
    senior: "Collect to LinkedHashMap if a map view is required.",
    javaSince: "Java 16",
    tags: ["maps"],
  },
  {
    id: "mp04",
    category: "maps",
    difficulty: "Intermediate",
    title: "Merge two maps with Streams",
    problem: "Merge two Map<String,Integer> summing values for common keys.",
    input: "m1, m2",
    output: "merged sums",
    solution: "Map<String, Integer> merged = Stream.concat(m1.entrySet().stream(), m2.entrySet().stream())\n  .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, Integer::sum));",
    pipeline: "concat(entrySet streams) \u2192 toMap(sum)",
    why: "concat + merge function.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "putAll overwriting instead of summing.",
    senior: "Map.merge in a loop is also fine; Streams shine for multi-source.",
    javaSince: "Java 8",
    tags: ["maps"],
  },
  {
    id: "emp01",
    category: "employee",
    difficulty: "Beginner",
    title: "List employee names",
    problem: "Collect all employee names.",
    input: "List<Employee>",
    output: "[...]",
    solution: "List<String> names = employees.stream().map(Employee::name).toList();",
    pipeline: "stream \u2192 map(name) \u2192 toList",
    why: "Basic projection.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Null names without filter.",
    senior: "record Employee(String id, String name, String department, int salary, String title, String email, List<String> skills, boolean contractor) {}",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp02",
    category: "employee",
    difficulty: "Beginner",
    title: "Filter by department ENG",
    problem: "Engineering employees only.",
    input: "employees",
    output: "ENG list",
    solution: "List<Employee> eng = employees.stream().filter(e -> \"ENG\".equals(e.department())).toList();",
    pipeline: "stream \u2192 filter(dept) \u2192 toList",
    why: "Department filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Null department NPE with e.department().equals.",
    senior: "Constant.equals(variable) pattern.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp03",
    category: "employee",
    difficulty: "Intermediate",
    title: "Average salary by department",
    problem: "Map department \u2192 average salary.",
    input: "employees",
    output: "Map<String, Double>",
    solution: "Map<String, Double> avg = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, Collectors.averagingInt(Employee::salary)));",
    pipeline: "groupingBy(dept, averagingInt)",
    why: "HR analytics staple.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "Integer division mistakes if manual.",
    senior: "averagingInt returns Double.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp04",
    category: "employee",
    difficulty: "Intermediate",
    title: "Highest paid employee",
    problem: "Find max salary employee.",
    input: "employees",
    output: "Optional<Employee>",
    solution: "Optional<Employee> top = employees.stream().max(Comparator.comparingInt(Employee::salary));",
    pipeline: "stream \u2192 max(salary)",
    why: "Optional max.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "get() on empty company list.",
    senior: "orElseThrow with domain exception.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp05",
    category: "employee",
    difficulty: "Intermediate",
    title: "Sort by salary then name",
    problem: "Order employees for a compensation report.",
    input: "employees",
    output: "sorted list",
    solution: "List<Employee> sorted = employees.stream()\n  .sorted(Comparator.comparingInt(Employee::salary).reversed().thenComparing(Employee::name))\n  .toList();",
    pipeline: "stream \u2192 sorted \u2192 toList",
    why: "Stable multi-key sort.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Inconsistent ordering across pages without total order.",
    senior: "thenComparing prevents jittery ties.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp06",
    category: "employee",
    difficulty: "Advanced",
    title: "Top earner per department",
    problem: "Map dept \u2192 highest paid employee.",
    input: "employees",
    output: "Map<String, Employee>",
    solution: "Map<String, Employee> top = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.collectingAndThen(\n          Collectors.maxBy(Comparator.comparingInt(Employee::salary)),\n          Optional::orElseThrow)));",
    pipeline: "groupingBy \u2192 maxBy \u2192 orElseThrow",
    why: "Best-per-group pattern.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "Multiple employees same max without tie-break.",
    senior: "Add thenComparing(name) inside maxBy.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp07",
    category: "employee",
    difficulty: "Intermediate",
    title: "Payroll total",
    problem: "Sum all salaries.",
    input: "employees",
    output: "int/long sum",
    solution: "long payroll = employees.stream().mapToLong(Employee::salary).sum();",
    pipeline: "stream \u2192 mapToLong \u2192 sum",
    why: "Avoid int overflow.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "mapToInt.sum on large orgs.",
    senior: "Use long for payroll aggregates.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp08",
    category: "employee",
    difficulty: "Beginner",
    title: "Count contractors",
    problem: "How many contractors?",
    input: "employees",
    output: "long",
    solution: "long n = employees.stream().filter(Employee::contractor).count();",
    pipeline: "stream \u2192 filter(contractor) \u2192 count",
    why: "Boolean accessor filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Counting with collect(counting) verbosity.",
    senior: "count() is enough.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp09",
    category: "employee",
    difficulty: "Advanced",
    title: "Partition full-time vs contractor",
    problem: "Partition by contractor flag.",
    input: "employees",
    output: "Map<Boolean, List<Employee>>",
    solution: "Map<Boolean, List<Employee>> parts = employees.stream().collect(Collectors.partitioningBy(Employee::contractor));",
    pipeline: "stream \u2192 partitioningBy(contractor)",
    why: "Workforce split.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Missing false key assumption.",
    senior: "Both keys always present.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp10",
    category: "employee",
    difficulty: "Intermediate",
    title: "Employees with salary in range",
    problem: "Filter salary between 80k and 120k inclusive.",
    input: "employees",
    output: "filtered",
    solution: "List<Employee> mid = employees.stream()\n  .filter(e -> e.salary() >= 80_000 && e.salary() <= 120_000)\n  .toList();",
    pipeline: "stream \u2192 filter(range) \u2192 toList",
    why: "Inclusive band filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Off-by-one on bounds.",
    senior: "Confirm inclusive/exclusive with interviewer.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp11",
    category: "employee",
    difficulty: "Advanced",
    title: "Department headcount and payroll",
    problem: "Using teeing at top level: total headcount and total payroll.",
    input: "employees",
    output: "record(count, payroll)",
    solution: "record HeadcountPayroll(long count, long payroll) {}\nHeadcountPayroll hp = employees.stream().collect(Collectors.teeing(\n  Collectors.counting(),\n  Collectors.summingLong(Employee::salary),\n  HeadcountPayroll::new));",
    pipeline: "stream \u2192 teeing(counting, summingLong)",
    why: "Single-pass dual aggregate.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Two separate stream passes without need.",
    senior: "teeing is Java 12+ interview signal.",
    javaSince: "Java 12",
    tags: ["employee"],
  },
  {
    id: "emp12",
    category: "employee",
    difficulty: "Intermediate",
    title: "Join names in department",
    problem: "Comma-separated ENG names sorted.",
    input: "employees",
    output: "Ada, Grace, Linus",
    solution: "String names = employees.stream()\n  .filter(e -> \"ENG\".equals(e.department()))\n  .map(Employee::name)\n  .sorted()\n  .collect(Collectors.joining(\", \"));",
    pipeline: "filter \u2192 map \u2192 sorted \u2192 joining",
    why: "Readable roster string.",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
    trap: "Unsorted joining for UI lists.",
    senior: "Sort before joining for deterministic UI.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp13",
    category: "employee",
    difficulty: "Expert",
    title: "Detect duplicate emails",
    problem: "Find emails used by more than one employee.",
    input: "employees",
    output: "dup emails",
    solution: "Set<String> dups = employees.stream()\n  .collect(Collectors.groupingBy(e -> e.email().toLowerCase(Locale.ROOT), Collectors.counting()))\n  .entrySet().stream()\n  .filter(e -> e.getValue() > 1)\n  .map(Map.Entry::getKey)\n  .collect(Collectors.toSet());",
    pipeline: "groupingBy(email) \u2192 filter count>1",
    why: "HR data quality.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Case-sensitive duplicates missed.",
    senior: "Normalize emails.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp14",
    category: "employee",
    difficulty: "Intermediate",
    title: "Group titles per department",
    problem: "Map dept \u2192 set of titles.",
    input: "employees",
    output: "Map<String, Set<String>>",
    solution: "Map<String, Set<String>> titles = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.mapping(Employee::title, Collectors.toSet())));",
    pipeline: "groupingBy \u2192 mapping \u2192 toSet",
    why: "Org structure summary.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "List with duplicates when Set needed.",
    senior: "toSet for uniqueness.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp15",
    category: "employee",
    difficulty: "Advanced",
    title: "Nth highest salary distinct",
    problem: "Return the nth highest distinct salary.",
    input: "employees, n=3",
    output: "3rd distinct salary",
    solution: "OptionalInt nth = employees.stream().mapToInt(Employee::salary).distinct()\n  .boxed().sorted(Comparator.reverseOrder()).skip(n - 1L).mapToInt(Integer::intValue).findFirst();",
    pipeline: "mapToInt \u2192 distinct \u2192 sorted desc \u2192 skip \u2192 findFirst",
    why: "Distinct ranking for compensation bands.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Skipping without distinct when required.",
    senior: "Confirm distinct with interviewer.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp16",
    category: "employee",
    difficulty: "Beginner",
    title: "Any employee in Sales",
    problem: "Boolean: is there at least one SALES employee?",
    input: "employees",
    output: "true/false",
    solution: "boolean ok = employees.stream().anyMatch(e -> \"SALES\".equals(e.department()));",
    pipeline: "stream \u2192 anyMatch",
    why: "Existence check.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(1)",
    trap: "filter+findFirst verbosity.",
    senior: "anyMatch is the clearest API.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp17",
    category: "employee",
    difficulty: "Intermediate",
    title: "Skills flatMap search",
    problem: "Find employees who have skill 'Kafka'.",
    input: "employees.skills",
    output: "filtered employees",
    solution: "List<Employee> kafka = employees.stream()\n  .filter(e -> e.skills().stream().anyMatch(s -> s.equalsIgnoreCase(\"Kafka\")))\n  .toList();",
    pipeline: "stream \u2192 filter(skills.anyMatch) \u2192 toList",
    why: "Nested stream for membership.",
    timeComplexity: "O(n*s)",
    spaceComplexity: "O(k)",
    trap: "flatMap skills then losing employee context.",
    senior: "Keep employee as outer stream; query skills inside.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp18",
    category: "employee",
    difficulty: "Advanced",
    title: "All skills union",
    problem: "Unique skills across company.",
    input: "employees",
    output: "Set<String>",
    solution: "Set<String> all = employees.stream()\n  .flatMap(e -> e.skills().stream())\n  .collect(Collectors.toCollection(TreeSet::new));",
    pipeline: "flatMap(skills) \u2192 TreeSet",
    why: "Company skill inventory.",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
    trap: "Null skills list.",
    senior: "Empty list over null.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp19",
    category: "employee",
    difficulty: "Staff",
    title: "Salary raise simulation",
    problem: "Return new list with ENG salaries * 1.10 (immutable records).",
    input: "employees",
    output: "updated list",
    solution: "List<Employee> raised = employees.stream()\n  .map(e -> \"ENG\".equals(e.department())\n      ? new Employee(e.id(), e.name(), e.department(), (int)(e.salary()*1.10), e.title(), e.email(), e.skills(), e.contractor())\n      : e)\n  .toList();",
    pipeline: "stream \u2192 map(copy with raise) \u2192 toList",
    why: "Immutable update via map.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Mutating employee objects inside peek.",
    senior: "map to new records; never mutate in peek.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp20",
    category: "employee",
    difficulty: "Intermediate",
    title: "Median salary (sort)",
    problem: "Compute median salary (odd/even sizes).",
    input: "employees",
    output: "median double",
    solution: "double median = employees.stream().mapToInt(Employee::salary).sorted().toArray() instanceof int[] a\n  ? (a.length % 2 == 1 ? a[a.length/2] : (a[a.length/2 - 1] + a[a.length/2]) / 2.0)\n  : 0;",
    pipeline: "mapToInt \u2192 sorted \u2192 toArray \u2192 median index",
    why: "Classic median after sort.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Average vs median confusion.",
    senior: "Clarify odd/even policy.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp21",
    category: "employee",
    difficulty: "Expert",
    title: "Managers vs ICs by title prefix",
    problem: "Partition titles starting with 'Manager'.",
    input: "employees",
    output: "partition map",
    solution: "Map<Boolean, List<Employee>> parts = employees.stream()\n  .collect(Collectors.partitioningBy(e -> e.title().startsWith(\"Manager\")));",
    pipeline: "stream \u2192 partitioningBy(title prefix)",
    why: "Org role split.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Fragile string prefix vs role enum.",
    senior: "Prefer Role enum in real systems.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp22",
    category: "employee",
    difficulty: "Intermediate",
    title: "Group by first letter of name",
    problem: "Directory index by starting letter.",
    input: "employees",
    output: "Map<Character, List<Employee>>",
    solution: "Map<Character, List<Employee>> dir = employees.stream()\n  .collect(Collectors.groupingBy(e -> Character.toUpperCase(e.name().charAt(0))));",
    pipeline: "stream \u2192 groupingBy(first letter)",
    why: "Phonebook style index.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Empty name charAt(0).",
    senior: "Guard blank names.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp23",
    category: "employee",
    difficulty: "Advanced",
    title: "Compare department averages",
    problem: "Return department with highest average salary.",
    input: "employees",
    output: "Optional<String> dept",
    solution: "Optional<String> best = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, Collectors.averagingInt(Employee::salary)))\n  .entrySet().stream()\n  .max(Map.Entry.comparingByValue())\n  .map(Map.Entry::getKey);",
    pipeline: "groupingBy averaging \u2192 max entry",
    why: "Leadership metric.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "Empty map max.",
    senior: "Handle empty company.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp24",
    category: "employee",
    difficulty: "Beginner",
    title: "Map id to employee",
    problem: "Index employees by id (unique).",
    input: "employees",
    output: "Map<String, Employee>",
    solution: "Map<String, Employee> byId = employees.stream()\n  .collect(Collectors.toMap(Employee::id, Function.identity()));",
    pipeline: "stream \u2192 toMap(id, identity)",
    why: "Primary key index.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Duplicate ids without merge.",
    senior: "Provide merge or ensure uniqueness upstream.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp25",
    category: "employee",
    difficulty: "Intermediate",
    title: "Filter then sort page",
    problem: "ENG employees, salary desc, page size 10.",
    input: "employees",
    output: "page list",
    solution: "List<Employee> page = employees.stream()\n  .filter(e -> \"ENG\".equals(e.department()))\n  .sorted(Comparator.comparingInt(Employee::salary).reversed())\n  .limit(10)\n  .toList();",
    pipeline: "filter \u2192 sorted \u2192 limit",
    why: "Filtered top page.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(k)",
    trap: "limit before sorted.",
    senior: "Order of intermediate ops matters.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp26",
    category: "employee",
    difficulty: "Advanced",
    title: "Nested group dept \u2192 title \u2192 names",
    problem: "Build Map dept \u2192 title \u2192 joined names.",
    input: "employees",
    output: "nested map of strings",
    solution: "Map<String, Map<String, String>> roster = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.groupingBy(Employee::title,\n          Collectors.mapping(Employee::name, Collectors.joining(\", \")))));",
    pipeline: "groupingBy \u2192 groupingBy \u2192 mapping joining",
    why: "Nested HR roster.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Too much nesting for API payloads.",
    senior: "Consider DTOs beyond two levels.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp27",
    category: "employee",
    difficulty: "Staff",
    title: "Salary band histogram",
    problem: "Bucket salaries: <50k, 50-100k, 100k+.",
    input: "employees",
    output: "Map<String, Long>",
    solution: "Map<String, Long> bands = employees.stream().collect(Collectors.groupingBy(e -> {\n  int s = e.salary();\n  if (s < 50_000) return \"<50k\";\n  if (s < 100_000) return \"50-100k\";\n  return \"100k+\";\n}, Collectors.counting()));",
    pipeline: "stream \u2192 groupingBy(band classifier, counting)",
    why: "Compensation distribution.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Overlapping band predicates.",
    senior: "Use clear half-open intervals.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp28",
    category: "employee",
    difficulty: "Intermediate",
    title: "AllMatch positive salary",
    problem: "Validate all salaries are positive.",
    input: "employees",
    output: "boolean",
    solution: "boolean ok = employees.stream().allMatch(e -> e.salary() > 0);",
    pipeline: "stream \u2192 allMatch",
    why: "Data validation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Vacuous true on empty list \u2014 may hide bugs.",
    senior: "Decide empty policy explicitly.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp29",
    category: "employee",
    difficulty: "Expert",
    title: "Find first employee by email domain",
    problem: "findFirst employee with email ending @meridian.bank.",
    input: "employees",
    output: "Optional<Employee>",
    solution: "Optional<Employee> e = employees.stream()\n  .filter(x -> x.email().endsWith(\"@meridian.bank\"))\n  .findFirst();",
    pipeline: "stream \u2192 filter \u2192 findFirst",
    why: "Domain membership.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "findAny when order matters for HR seniority lists.",
    senior: "findFirst for encounter-order dependent rules.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp30",
    category: "employee",
    difficulty: "Advanced",
    title: "CollectingAndThen to unmodifiable dept map",
    problem: "Unmodifiable map of dept \u2192 employee list.",
    input: "employees",
    output: "unmodifiable map",
    solution: "Map<String, List<Employee>> frozen = employees.stream()\n  .collect(Collectors.collectingAndThen(\n      Collectors.groupingBy(Employee::department),\n      Map::copyOf));",
    pipeline: "groupingBy \u2192 collectingAndThen(Map::copyOf)",
    why: "Defensive publish of reports.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Map.copyOf does shallow freeze \u2014 lists inside still mutable if not copied.",
    senior: "Deep freeze needs mapping lists to List.copyOf too.",
    javaSince: "Java 10",
    tags: ["employee"],
  },
  {
    id: "emp31",
    category: "employee",
    difficulty: "Intermediate",
    title: "Min salary in department",
    problem: "Minimum salary in ENG.",
    input: "employees",
    output: "OptionalInt",
    solution: "OptionalInt min = employees.stream()\n  .filter(e -> \"ENG\".equals(e.department()))\n  .mapToInt(Employee::salary)\n  .min();",
    pipeline: "filter \u2192 mapToInt \u2192 min",
    why: "Dept-scoped aggregate.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "min on empty OptionalInt.",
    senior: "orElseThrow / orElse.",
    javaSince: "Java 8",
    tags: ["employee"],
  },
  {
    id: "emp32",
    category: "employee",
    difficulty: "Beginner",
    title: "Distinct departments",
    problem: "Sorted unique departments.",
    input: "employees",
    output: "[ENG, HR, ...]",
    solution: "List<String> deps = employees.stream().map(Employee::department).distinct().sorted().toList();",
    pipeline: "map \u2192 distinct \u2192 sorted \u2192 toList",
    why: "Org unit list.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(d)",
    trap: "distinct after sorted vs before \u2014 both OK; sorted after distinct is fine.",
    senior: "TreeSet collector also works.",
    javaSince: "Java 16",
    tags: ["employee"],
  },
  {
    id: "emp33",
    category: "employee",
    difficulty: "Architect",
    title: "Parallel payroll sum with caution",
    problem: "Parallel sum salaries when n is large and CPU-bound.",
    input: "1e6 employees",
    output: "long sum",
    solution: "long sum = employees.parallelStream().mapToLong(Employee::salary).sum();",
    pipeline: "parallelStream \u2192 mapToLong \u2192 sum",
    why: "Associative sum is parallel-safe.",
    timeComplexity: "O(n/p)",
    spaceComplexity: "O(1)",
    trap: "parallelStream for tiny lists or blocking HR calls inside map.",
    senior: "Only parallelize pure CPU aggregates on large datasets.",
    javaSince: "Java 8",
    tags: ["employee", "parallel"],
  },
  {
    id: "emp34",
    category: "employee",
    difficulty: "Advanced",
    title: "Employees joined this year via Optional date",
    problem: "Filter employees whose Optional<LocalDate> startDate is present and in current year.",
    input: "employees with Optional startDate",
    output: "filtered",
    solution: "int year = Year.now().getValue();\nList<Employee> newbie = employees.stream()\n  .filter(e -> e.startDate().filter(d -> d.getYear() == year).isPresent())\n  .toList();",
    pipeline: "stream \u2192 filter(Optional date year)",
    why: "Optional in domain filters.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "get() on Optional startDate.",
    senior: "Use Optional.filter / stream.",
    javaSince: "Java 8",
    tags: ["employee", "datetime-optional"],
  },
  {
    id: "emp35",
    category: "employee",
    difficulty: "Staff",
    title: "Department skill matrix",
    problem: "Map dept \u2192 skill \u2192 employee count having that skill.",
    input: "employees",
    output: "Map<String, Map<String, Long>>",
    solution: "Map<String, Map<String, Long>> matrix = employees.stream()\n  .flatMap(e -> e.skills().stream().map(skill -> Map.entry(e.department(), skill)))\n  .collect(Collectors.groupingBy(Map.Entry::getKey,\n      Collectors.groupingBy(Map.Entry::getValue, Collectors.counting())));",
    pipeline: "flatMap(dept,skill pairs) \u2192 nested groupingBy counting",
    why: "Capability heatmap for org planning.",
    timeComplexity: "O(n*s)",
    spaceComplexity: "O(d*s)",
    trap: "Cartesian explosion without care.",
    senior: "Architect-level nested grouping with flatMap pair expansion.",
    javaSince: "Java 9",
    tags: ["employee"],
  },
  {
    id: "ec01",
    category: "ecommerce",
    difficulty: "Beginner",
    title: "Order totals list",
    problem: "Map orders to BigDecimal totals.",
    input: "orders",
    output: "list of totals",
    solution: "List<BigDecimal> totals = orders.stream().map(Order::total).toList();",
    pipeline: "stream \u2192 map(total) \u2192 toList",
    why: "Order projection.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Using double for money.",
    senior: "record Order(String id, String customerId, Status status, BigDecimal total, List<LineItem> items, Instant createdAt) {}",
    javaSince: "Java 16",
    tags: ["ecommerce"],
  },
  {
    id: "ec02",
    category: "ecommerce",
    difficulty: "Intermediate",
    title: "GMV sum",
    problem: "Gross merchandise value: sum of order totals.",
    input: "orders",
    output: "BigDecimal GMV",
    solution: "BigDecimal gmv = orders.stream().map(Order::total).reduce(BigDecimal.ZERO, BigDecimal::add);",
    pipeline: "stream \u2192 map(total) \u2192 reduce(add)",
    why: "GMV aggregation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "double GMV.",
    senior: "BigDecimal ZERO identity.",
    javaSince: "Java 8",
    tags: ["ecommerce"],
  },
  {
    id: "ec03",
    category: "ecommerce",
    difficulty: "Intermediate",
    title: "Orders by status count",
    problem: "Count orders per Status enum.",
    input: "orders",
    output: "Map<Status, Long>",
    solution: "Map<Status, Long> byStatus = orders.stream()\n  .collect(Collectors.groupingBy(Order::status, Collectors.counting()));",
    pipeline: "groupingBy(status, counting)",
    why: "Fulfillment dashboard.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "String status typos.",
    senior: "Enum status keys.",
    javaSince: "Java 8",
    tags: ["ecommerce"],
  },
  {
    id: "ec04",
    category: "ecommerce",
    difficulty: "Advanced",
    title: "Flatten line item SKUs",
    problem: "All SKUs across all orders.",
    input: "orders.items",
    output: "List<String>",
    solution: "List<String> skus = orders.stream()\n  .flatMap(o -> o.items().stream())\n  .map(LineItem::sku)\n  .toList();",
    pipeline: "orders \u2192 flatMap(items) \u2192 map(sku)",
    why: "Catalog pull from carts.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Null items.",
    senior: "Empty list default.",
    javaSince: "Java 16",
    tags: ["ecommerce"],
  },
  {
    id: "ec05",
    category: "ecommerce",
    difficulty: "Advanced",
    title: "SKU quantity merge toMap",
    problem: "Aggregate quantity per SKU across all orders.",
    input: "orders",
    output: "Map<String, Integer>",
    solution: "Map<String, Integer> qty = orders.stream()\n  .flatMap(o -> o.items().stream())\n  .collect(Collectors.toMap(LineItem::sku, LineItem::qty, Integer::sum));",
    pipeline: "flatMap items \u2192 toMap(sku, qty, sum)",
    why: "Inventory demand signal.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(skus)",
    trap: "toMap without merge.",
    senior: "Always merge quantities.",
    javaSince: "Java 8",
    tags: ["ecommerce"],
  },
  {
    id: "ec06",
    category: "ecommerce",
    difficulty: "Intermediate",
    title: "Top customers by spend",
    problem: "Top 5 customerIds by sum of totals.",
    input: "orders",
    output: "List<String> customer ids",
    solution: "List<String> top = orders.stream()\n  .collect(Collectors.groupingBy(Order::customerId,\n      Collectors.mapping(Order::total, Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))))\n  .entrySet().stream()\n  .sorted(Map.Entry.<String, BigDecimal>comparingByValue().reversed())\n  .limit(5)\n  .map(Map.Entry::getKey)\n  .toList();",
    pipeline: "groupingBy spend \u2192 sort \u2192 limit",
    why: "VIP customers.",
    timeComplexity: "O(n log c)",
    spaceComplexity: "O(c)",
    trap: "Averaging instead of summing spend.",
    senior: "Reduce BigDecimal per customer.",
    javaSince: "Java 16",
    tags: ["ecommerce"],
  },
  {
    id: "ec07",
    category: "ecommerce",
    difficulty: "Beginner",
    title: "Filter PAID orders",
    problem: "Keep orders with Status.PAID.",
    input: "orders",
    output: "paid orders",
    solution: "List<Order> paid = orders.stream().filter(o -> o.status() == Status.PAID).toList();",
    pipeline: "stream \u2192 filter(PAID) \u2192 toList",
    why: "Payment-complete subset.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "equals on enums unnecessarily.",
    senior: "== for enum status.",
    javaSince: "Java 16",
    tags: ["ecommerce"],
  },
  {
    id: "ec08",
    category: "ecommerce",
    difficulty: "Expert",
    title: "Average basket size (items count)",
    problem: "Average number of line items per order.",
    input: "orders",
    output: "double",
    solution: "double avgBasket = orders.stream()\n  .collect(Collectors.averagingInt(o -> o.items().size()));",
    pipeline: "stream \u2192 averagingInt(items.size)",
    why: "Basket analytics.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Averaging totals instead of item counts.",
    senior: "Clarify basket size metric.",
    javaSince: "Java 8",
    tags: ["ecommerce"],
  },
  {
    id: "ec09",
    category: "ecommerce",
    difficulty: "Advanced",
    title: "Partition free shipping",
    problem: "Partition orders by total >= 50 for free shipping.",
    input: "orders",
    output: "Map<Boolean, List<Order>>",
    solution: "Map<Boolean, List<Order>> parts = orders.stream()\n  .collect(Collectors.partitioningBy(o -> o.total().compareTo(new BigDecimal(\"50.00\")) >= 0));",
    pipeline: "stream \u2192 partitioningBy(total>=50)",
    why: "Shipping threshold.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Comparing BigDecimal with equals for threshold.",
    senior: "compareTo for numeric thresholds.",
    javaSince: "Java 8",
    tags: ["ecommerce"],
  },
  {
    id: "ec10",
    category: "ecommerce",
    difficulty: "Intermediate",
    title: "Recent orders limit",
    problem: "Latest 20 orders by createdAt desc.",
    input: "orders",
    output: "20 orders",
    solution: "List<Order> recent = orders.stream()\n  .sorted(Comparator.comparing(Order::createdAt).reversed())\n  .limit(20)\n  .toList();",
    pipeline: "sorted(createdAt desc) \u2192 limit",
    why: "Activity feed.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(k)",
    trap: "Sorting after limit.",
    senior: "Sort then limit.",
    javaSince: "Java 16",
    tags: ["ecommerce"],
  },
  {
    id: "ec11",
    category: "ecommerce",
    difficulty: "Staff",
    title: "Revenue by day",
    problem: "Sum totals grouped by LocalDate of createdAt.",
    input: "orders",
    output: "Map<LocalDate, BigDecimal>",
    solution: "Map<LocalDate, BigDecimal> byDay = orders.stream()\n  .collect(Collectors.groupingBy(o -> LocalDate.ofInstant(o.createdAt(), ZoneOffset.UTC),\n      Collectors.mapping(Order::total, Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))));",
    pipeline: "groupingBy(date) \u2192 reducing BigDecimal",
    why: "Daily revenue report.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(days)",
    trap: "System default zone surprises.",
    senior: "Pin ZoneOffset/ZoneId explicitly.",
    javaSince: "Java 8",
    tags: ["ecommerce", "datetime-optional"],
  },
  {
    id: "ec12",
    category: "ecommerce",
    difficulty: "Advanced",
    title: "Distinct products purchased by customer",
    problem: "For one customerId, distinct SKUs ordered.",
    input: "orders, customer C1",
    output: "sorted SKUs",
    solution: "List<String> skus = orders.stream()\n  .filter(o -> \"C1\".equals(o.customerId()))\n  .flatMap(o -> o.items().stream())\n  .map(LineItem::sku)\n  .distinct()\n  .sorted()\n  .toList();",
    pipeline: "filter \u2192 flatMap \u2192 map \u2192 distinct \u2192 sorted",
    why: "Customer purchase history.",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
    trap: "distinct without sorted when UI needs alpha order.",
    senior: "distinct then sorted for display.",
    javaSince: "Java 16",
    tags: ["ecommerce"],
  },
  {
    id: "ft01",
    category: "fintech",
    difficulty: "Beginner",
    title: "Sum payment amounts",
    problem: "Sum BigDecimal payment amounts.",
    input: "payments",
    output: "total",
    solution: "BigDecimal total = payments.stream().map(Payment::amount).reduce(BigDecimal.ZERO, BigDecimal::add);",
    pipeline: "stream \u2192 map(amount) \u2192 reduce(add)",
    why: "Ledger sum.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "double for currency.",
    senior: "record Payment(String id, String merchantId, String currency, BigDecimal amount, boolean settled, Instant bookedAt) {}",
    javaSince: "Java 8",
    tags: ["fintech"],
  },
  {
    id: "ft02",
    category: "fintech",
    difficulty: "Intermediate",
    title: "Group volume by currency",
    problem: "Sum amounts per ISO currency code.",
    input: "payments",
    output: "Map<String, BigDecimal>",
    solution: "Map<String, BigDecimal> byCcy = payments.stream()\n  .collect(Collectors.toMap(Payment::currency, Payment::amount, BigDecimal::add));",
    pipeline: "stream \u2192 toMap(ccy, amount, add)",
    why: "Multi-currency book.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(c)",
    trap: "Mixing FX without conversion.",
    senior: "Don't sum different currencies into one total without FX.",
    javaSince: "Java 8",
    tags: ["fintech"],
  },
  {
    id: "ft03",
    category: "fintech",
    difficulty: "Intermediate",
    title: "Filter settled payments",
    problem: "Only settled=true payments.",
    input: "payments",
    output: "settled list",
    solution: "List<Payment> settled = payments.stream().filter(Payment::settled).toList();",
    pipeline: "stream \u2192 filter(settled) \u2192 toList",
    why: "Settlement subset.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Confusing booked vs settled.",
    senior: "Name domain flags carefully.",
    javaSince: "Java 16",
    tags: ["fintech"],
  },
  {
    id: "ft04",
    category: "fintech",
    difficulty: "Advanced",
    title: "High-value transaction alert",
    problem: "Payments with amount compareTo 10_000 >= 0.",
    input: "payments",
    output: "alerts",
    solution: "List<Payment> hv = payments.stream()\n  .filter(p -> p.amount().compareTo(new BigDecimal(\"10000\")) >= 0)\n  .toList();",
    pipeline: "stream \u2192 filter(amount>=10k)",
    why: "AML-style thresholding (illustrative).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Using double thresholds.",
    senior: "BigDecimal thresholds from config.",
    javaSince: "Java 16",
    tags: ["fintech"],
  },
  {
    id: "ft05",
    category: "fintech",
    difficulty: "Expert",
    title: "Merchant teeing count and volume",
    problem: "Per merchantId: count and total amount.",
    input: "payments",
    output: "Map to Stats",
    solution: "record MerchantStats(long count, BigDecimal volume) {}\nMap<String, MerchantStats> stats = payments.stream()\n  .collect(Collectors.groupingBy(Payment::merchantId,\n      Collectors.teeing(\n          Collectors.counting(),\n          Collectors.mapping(Payment::amount, Collectors.reducing(BigDecimal.ZERO, BigDecimal::add)),\n          MerchantStats::new)));",
    pipeline: "groupingBy \u2192 teeing(count, volume)",
    why: "Merchant performance.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(m)",
    trap: "Two grouping passes.",
    senior: "teeing downstream is staff-level.",
    javaSince: "Java 12",
    tags: ["fintech"],
  },
  {
    id: "ft06",
    category: "fintech",
    difficulty: "Intermediate",
    title: "Sort by amount desc",
    problem: "Rank payments by amount.",
    input: "payments",
    output: "sorted",
    solution: "List<Payment> ranked = payments.stream()\n  .sorted(Comparator.comparing(Payment::amount).reversed())\n  .toList();",
    pipeline: "stream \u2192 sorted(amount desc)",
    why: "Value ranking.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "equals vs compareTo scale issues for uniqueness.",
    senior: "compareTo for ordering money.",
    javaSince: "Java 16",
    tags: ["fintech"],
  },
  {
    id: "ft07",
    category: "fintech",
    difficulty: "Advanced",
    title: "Daily settled volume",
    problem: "Sum settled amounts by UTC date.",
    input: "payments",
    output: "Map<LocalDate, BigDecimal>",
    solution: "Map<LocalDate, BigDecimal> daily = payments.stream()\n  .filter(Payment::settled)\n  .collect(Collectors.groupingBy(p -> LocalDate.ofInstant(p.bookedAt(), ZoneOffset.UTC),\n      Collectors.mapping(Payment::amount, Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))));",
    pipeline: "filter settled \u2192 groupingBy(date) \u2192 reduce",
    why: "Ops settlement report.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(days)",
    trap: "Local timezone drift.",
    senior: "Fix ZoneOffset in financial reporting.",
    javaSince: "Java 8",
    tags: ["fintech", "datetime-optional"],
  },
  {
    id: "ft08",
    category: "fintech",
    difficulty: "Beginner",
    title: "Count by currency",
    problem: "Number of payments per currency.",
    input: "payments",
    output: "Map<String, Long>",
    solution: "Map<String, Long> counts = payments.stream()\n  .collect(Collectors.groupingBy(Payment::currency, Collectors.counting()));",
    pipeline: "groupingBy(currency, counting)",
    why: "Traffic mix.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(c)",
    trap: "Assuming only USD.",
    senior: "Always group multi-ccy explicitly.",
    javaSince: "Java 8",
    tags: ["fintech"],
  },
  {
    id: "ft09",
    category: "fintech",
    difficulty: "Staff",
    title: "Running balance style reduce",
    problem: "Compute ending balance from ordered signed ledger deltas.",
    input: "List<BigDecimal> deltas",
    output: "ending balance",
    solution: "BigDecimal end = deltas.stream().reduce(BigDecimal.ZERO, BigDecimal::add);",
    pipeline: "stream \u2192 reduce(ZERO, add)",
    why: "Ledger fold.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Parallel unordered ledger reduce when order defines causality \u2014 usually sequential.",
    senior: "Keep ledger folds sequential when audit order matters.",
    javaSince: "Java 8",
    tags: ["fintech"],
  },
  {
    id: "ft10",
    category: "fintech",
    difficulty: "Intermediate",
    title: "Partition settled vs open",
    problem: "partitioningBy settled flag.",
    input: "payments",
    output: "Map<Boolean, List<Payment>>",
    solution: "Map<Boolean, List<Payment>> parts = payments.stream().collect(Collectors.partitioningBy(Payment::settled));",
    pipeline: "stream \u2192 partitioningBy(settled)",
    why: "Settlement WIP vs done.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Empty side missing key myth.",
    senior: "Both keys exist.",
    javaSince: "Java 8",
    tags: ["fintech"],
  },
  {
    id: "ft11",
    category: "fintech",
    difficulty: "Advanced",
    title: "Top N merchants by volume",
    problem: "Top 3 merchants by summed amount.",
    input: "payments",
    output: "List merchantIds",
    solution: "List<String> top = payments.stream()\n  .collect(Collectors.groupingBy(Payment::merchantId,\n      Collectors.mapping(Payment::amount, Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))))\n  .entrySet().stream()\n  .sorted(Map.Entry.<String, BigDecimal>comparingByValue().reversed())\n  .limit(3)\n  .map(Map.Entry::getKey)\n  .toList();",
    pipeline: "groupingBy volume \u2192 sort \u2192 limit",
    why: "Partner ranking.",
    timeComplexity: "O(n log m)",
    spaceComplexity: "O(m)",
    trap: "Top-N before aggregate.",
    senior: "Aggregate then rank.",
    javaSince: "Java 16",
    tags: ["fintech"],
  },
  {
    id: "ft12",
    category: "fintech",
    difficulty: "Expert",
    title: "FX-aware filter then convert (illustrative)",
    problem: "Filter USD payments and scale amounts by a given FX rate to INR (BigDecimal).",
    input: "payments, rate",
    output: "INR amounts",
    solution: "BigDecimal rate = new BigDecimal(\"83.20\");\nList<BigDecimal> inr = payments.stream()\n  .filter(p -> \"USD\".equals(p.currency()))\n  .map(p -> p.amount().multiply(rate))\n  .toList();",
    pipeline: "filter(USD) \u2192 map(multiply FX)",
    why: "Simple FX projection (not a full FX engine).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Floating FX rates.",
    senior: "Use BigDecimal rate tables; document as-of time.",
    javaSince: "Java 16",
    tags: ["fintech"],
  },
  {
    id: "ft13",
    category: "fintech",
    difficulty: "Intermediate",
    title: "FindAny failed payment id parallel",
    problem: "Discover any unsettled payment id using findAny on parallel stream.",
    input: "payments",
    output: "Optional id",
    solution: "Optional<String> id = payments.parallelStream()\n  .filter(p -> !p.settled())\n  .map(Payment::id)\n  .findAny();",
    pipeline: "parallelStream \u2192 filter \u2192 map \u2192 findAny",
    why: "Existence witness without order.",
    timeComplexity: "O(n/p)",
    spaceComplexity: "O(1)",
    trap: "findFirst when any unsettled is enough \u2014 slower parallel.",
    senior: "findAny for unordered existence in parallel.",
    javaSince: "Java 8",
    tags: ["fintech", "parallel"],
  },
  {
    id: "ft14",
    category: "fintech",
    difficulty: "Architect",
    title: "Idempotent ledger merge by payment id",
    problem: "toMap payment id \u2192 payment, last booked wins.",
    input: "payments possibly redelivered",
    output: "Map id\u2192Payment",
    solution: "Map<String, Payment> idem = payments.stream()\n  .collect(Collectors.toMap(Payment::id, Function.identity(),\n      (a, b) -> a.bookedAt().isAfter(b.bookedAt()) ? a : b));",
    pipeline: "stream \u2192 toMap(id, identity, latest booked)",
    why: "At-least-once ingestion dedupe.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "First-win silently dropping newer bookings.",
    senior: "Merge by business timestamp, not encounter order.",
    javaSince: "Java 8",
    tags: ["fintech"],
  },
  {
    id: "ft15",
    category: "fintech",
    difficulty: "Advanced",
    title: "Percentile-ish top 1% by amount (approx via sort)",
    problem: "Take top 1% payments by amount (ceil at least 1).",
    input: "payments n>=1",
    output: "top slice",
    solution: "int k = Math.max(1, (int)Math.ceil(payments.size() * 0.01));\nList<Payment> top = payments.stream()\n  .sorted(Comparator.comparing(Payment::amount).reversed())\n  .limit(k)\n  .toList();",
    pipeline: "sorted desc \u2192 limit(1%)",
    why: "High-value cohort.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(k)",
    trap: "True percentile algorithms differ \u2014 say so.",
    senior: "Clarify approximate vs exact percentile.",
    javaSince: "Java 16",
    tags: ["fintech"],
  },
  {
    id: "dt01",
    category: "datetime-optional",
    difficulty: "Beginner",
    title: "Optional orElse",
    problem: "Map Optional names to upper or default.",
    input: "Optional.of(\"ada\")",
    output: "ADA",
    solution: "String name = Optional.of(\"ada\").map(String::toUpperCase).orElse(\"UNKNOWN\");",
    pipeline: "Optional \u2192 map \u2192 orElse",
    why: "Optional is not a Stream but pairs with map/flatMap.",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    trap: "orElse(getExpensive()) always evaluates \u2014 use orElseGet.",
    senior: "orElseGet for lazy defaults.",
    javaSince: "Java 8",
    tags: ["datetime-optional"],
  },
  {
    id: "dt02",
    category: "datetime-optional",
    difficulty: "Intermediate",
    title: "Optional.stream in pipeline",
    problem: "FlatMap list of Optional<LocalDate> to dates in 2024.",
    input: "Optionals of dates",
    output: "2024 dates",
    solution: "List<LocalDate> dates = optionals.stream()\n  .flatMap(Optional::stream)\n  .filter(d -> d.getYear() == 2024)\n  .toList();",
    pipeline: "stream \u2192 flatMap(Optional::stream) \u2192 filter \u2192 toList",
    why: "Optional.stream bridges to Stream API.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "filter(isPresent).map(get).",
    senior: "Optional::stream is preferred.",
    javaSince: "Java 9",
    tags: ["datetime-optional"],
  },
  {
    id: "dt03",
    category: "datetime-optional",
    difficulty: "Advanced",
    title: "Group events by YearMonth",
    problem: "Group Instant events by YearMonth UTC.",
    input: "events",
    output: "Map<YearMonth, Long>",
    solution: "Map<YearMonth, Long> byMonth = events.stream()\n  .collect(Collectors.groupingBy(\n      e -> YearMonth.from(LocalDate.ofInstant(e.at(), ZoneOffset.UTC)),\n      Collectors.counting()));",
    pipeline: "stream \u2192 groupingBy(YearMonth) \u2192 counting",
    why: "Time-bucket KPIs.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(m)",
    trap: "System zone default.",
    senior: "Be explicit with ZoneOffset.",
    javaSince: "Java 8",
    tags: ["datetime-optional"],
  },
  {
    id: "dt04",
    category: "datetime-optional",
    difficulty: "Intermediate",
    title: "Filter weekends",
    problem: "Keep LocalDates that are weekdays.",
    input: "dates",
    output: "Mon-Fri",
    solution: "List<LocalDate> weekdays = dates.stream()\n  .filter(d -> d.getDayOfWeek().getValue() <= 5)\n  .toList();",
    pipeline: "stream \u2192 filter(weekday) \u2192 toList",
    why: "Business-day filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Ignoring holidays \u2014 mention limitation.",
    senior: "Weekday \u2260 business day in banking.",
    javaSince: "Java 16",
    tags: ["datetime-optional"],
  },
  {
    id: "dt05",
    category: "datetime-optional",
    difficulty: "Expert",
    title: "Earliest Optional timestamp",
    problem: "Min of Optional<Instant> values that are present.",
    input: "list of Optional<Instant>",
    output: "Optional min",
    solution: "Optional<Instant> earliest = stamps.stream()\n  .flatMap(Optional::stream)\n  .min(Comparator.naturalOrder());",
    pipeline: "flatMap(Optional::stream) \u2192 min",
    why: "Earliest present event.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Comparing empty Optionals directly.",
    senior: "Flatten first, then min.",
    javaSince: "Java 9",
    tags: ["datetime-optional"],
  },
];
