import type {StreamProblem} from './types';

export const PROBLEMS_ADVANCED: StreamProblem[] = [
  {
    id: "par01",
    category: "parallel",
    difficulty: "Advanced",
    title: "Parallel sum associative",
    problem: "Parallel sum of 1..1_000_000.",
    input: "range",
    output: "500000500000",
    solution: "long sum = LongStream.rangeClosed(1, 1_000_000).parallel().sum();",
    pipeline: "range \u2192 parallel \u2192 sum",
    why: "Associative reduction parallelizes well.",
    timeComplexity: "O(n/p)",
    spaceComplexity: "O(1)",
    trap: "Parallel on tiny n \u2014 overhead dominates.",
    senior: "Measure; don't cargo-cult parallel.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par02",
    category: "parallel",
    difficulty: "Expert",
    title: "Mutable state trap in parallel",
    problem: "Show why a shared ArrayList add in forEach/parallel is unsafe.",
    input: "parallel stream",
    output: "race / CME / lost updates",
    solution: "List<Integer> unsafe = new ArrayList<>();\nIntStream.range(0, 1000).parallel().forEach(unsafe::add); // BROKEN\nList<Integer> safe = IntStream.range(0, 1000).parallel().boxed().toList();",
    pipeline: "parallel \u2192 collect/toList (safe) vs shared mutable (unsafe)",
    why: "Parallel + shared mutable structure is a classic production bug.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Synchronizing ArrayList as a 'fix' \u2014 still poor design.",
    senior: "Prefer concurrent collectors / toList; never mutate shared lists.",
    javaSince: "Java 8",
    tags: ["parallel", "production"],
  },
  {
    id: "par03",
    category: "parallel",
    difficulty: "Advanced",
    title: "findFirst vs findAny parallel",
    problem: "Explain performance/order trade-off.",
    input: "parallel filtered stream",
    output: "Optional",
    solution: "Optional<Integer> ordered = IntStream.range(0, 10_000).parallel().filter(i -> i % 997 == 0).findFirst();\nOptional<Integer> any = IntStream.range(0, 10_000).parallel().filter(i -> i % 997 == 0).findAny();",
    pipeline: "parallel \u2192 filter \u2192 findFirst|findAny",
    why: "findFirst may do more coordination to respect order.",
    timeComplexity: "O(n/p)",
    spaceComplexity: "O(1)",
    trap: "Asserting findAny == findFirst in tests under parallel.",
    senior: "Tests for findAny must allow any matching value.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par04",
    category: "parallel",
    difficulty: "Staff",
    title: "Distinct-by-key parallel safe",
    problem: "Deduplicate employees by email under parallel using ConcurrentHashMap.",
    input: "employees parallel",
    output: "unique by email",
    solution: "Map<String, Employee> uniq = employees.parallelStream()\n  .collect(Collectors.toConcurrentMap(Employee::email, Function.identity(), (a, b) -> a));",
    pipeline: "parallelStream \u2192 toConcurrentMap(email, identity, first)",
    why: "Concurrent map merge is the safe distinct-by-key.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "HashSet seen in filter with parallelStream.",
    senior: "toConcurrentMap or groupingByConcurrent.",
    javaSince: "Java 8",
    tags: ["parallel", "distinct"],
  },
  {
    id: "par05",
    category: "parallel",
    difficulty: "Intermediate",
    title: "parallelStream vs stream.parallel",
    problem: "Two ways to request parallel execution.",
    input: "list",
    output: "parallel pipeline",
    solution: "long a = list.parallelStream().mapToLong(Long::longValue).sum();\nlong b = list.stream().parallel().mapToLong(Long::longValue).sum();",
    pipeline: "parallelStream | stream.parallel \u2192 sum",
    why: "Equivalent parallel flags.",
    timeComplexity: "O(n/p)",
    spaceComplexity: "O(1)",
    trap: "Calling sequential() later accidentally.",
    senior: "Know sequential()/parallel() toggles.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par06",
    category: "parallel",
    difficulty: "Architect",
    title: "commonPool blocking trap",
    problem: "Why blocking IO inside parallel map starves ForkJoinPool.commonPool.",
    input: "URLs",
    output: "don't",
    solution: "// BAD: urls.parallelStream().map(this::httpGet).toList();\n// GOOD: use a dedicated Executor / reactive IO; keep commonPool CPU-bound.",
    pipeline: "avoid parallel + blocking IO",
    why: "commonPool is shared JVM-wide.",
    timeComplexity: "N/A",
    spaceComplexity: "N/A",
    trap: "parallelStream for HTTP fan-out.",
    senior: "Architect red flag: blocking in commonPool.",
    javaSince: "Java 8",
    tags: ["parallel", "production"],
  },
  {
    id: "par07",
    category: "parallel",
    difficulty: "Advanced",
    title: "Reduce combiner required",
    problem: "Parallel reduce of sets needs combiner.",
    input: "stream of ints",
    output: "sum of squares",
    solution: "int sumSq = IntStream.rangeClosed(1, 100).parallel()\n  .reduce(0, (acc, x) -> acc + x * x); // IntStream 2-arg reduce OK\n// For Stream<T> parallel reduce of non-associative string concat, provide combiner.",
    pipeline: "parallel \u2192 reduce(+ combiner when needed)",
    why: "Combiner merges partials.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Identity side effects in accumulator.",
    senior: "Identity must be true identity; accumulator/combiner associative.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par08",
    category: "parallel",
    difficulty: "Expert",
    title: "groupingBy vs groupingByConcurrent",
    problem: "Parallel group merchants safely.",
    input: "payments",
    output: "ConcurrentMap",
    solution: "Map<String, List<Payment>> m = payments.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Payment::merchantId));",
    pipeline: "parallelStream \u2192 groupingByConcurrent",
    why: "Thread-safe grouping.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "groupingBy with parallel and custom non-concurrent downstream mutation.",
    senior: "Prefer groupingByConcurrent for parallel grouping.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par09",
    category: "parallel",
    difficulty: "Intermediate",
    title: "Unordered for speed",
    problem: "Call unordered() before distinct on parallel to relax constraints.",
    input: "parallel stream",
    output: "faster distinct possibly",
    solution: "long n = data.parallelStream().unordered().distinct().count();",
    pipeline: "parallel \u2192 unordered \u2192 distinct \u2192 count",
    why: "unordered removes encounter-order constraints.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "unordered when caller needed stable order.",
    senior: "Document that unordered sacrifices determinism.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par10",
    category: "parallel",
    difficulty: "Staff",
    title: "Thread-confined mutable accumulator via collect",
    problem: "Correct mutable parallel collection with Collector.",
    input: "strings",
    output: "List",
    solution: "List<String> out = strings.parallelStream()\n  .collect(Collectors.toList()); // supplier/accumulator/combiner managed",
    pipeline: "parallelStream \u2192 collect(toList)",
    why: "Collector contract handles partial lists.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "reduce(new ArrayList(), ... ) sharing one list identity.",
    senior: "collect is the mutable parallel story.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par11",
    category: "parallel",
    difficulty: "Advanced",
    title: "Side-effect logging race",
    problem: "Why peek(System.out::println) order is nondeterministic in parallel.",
    input: "parallel",
    output: "jumbled logs",
    solution: "list.parallelStream().peek(System.out::println).toList();",
    pipeline: "parallel \u2192 peek \u2192 toList",
    why: "Encounter order not preserved for peek side effects.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Relying on peek order in parallel for audit logs.",
    senior: "Log after sequential materialization if order matters.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "par12",
    category: "parallel",
    difficulty: "Expert",
    title: "Custom Spliterator awareness",
    problem: "Note that poor splitability (linked lists) hurts parallel speedup.",
    input: "LinkedList vs ArrayList",
    output: "weak speedup on LinkedList",
    solution: "// ArrayList / arrays split well; LinkedList splits poorly.\nlong sum = arrayList.parallelStream().mapToLong(Long::longValue).sum();",
    pipeline: "parallelStream on random-access sources",
    why: "Parallel efficiency depends on Spliterator.",
    timeComplexity: "O(n/p) best",
    spaceComplexity: "O(1)",
    trap: "Expecting LinkedList parallel to scale linearly.",
    senior: "Know your source's Spliterator characteristics.",
    javaSince: "Java 8",
    tags: ["parallel"],
  },
  {
    id: "pr01",
    category: "production",
    difficulty: "Staff",
    title: "Files.lines must close",
    problem: "Production-safe line count with try-with-resources.",
    input: "path",
    output: "count",
    solution: "try (Stream<String> lines = Files.lines(path)) {\n  return lines.filter(l -> !l.isBlank()).count();\n}",
    pipeline: "Files.lines \u2192 filter \u2192 count (closed)",
    why: "IO streams hold resources.",
    timeComplexity: "O(lines)",
    spaceComplexity: "O(1)",
    trap: "Returning Stream from method without closing.",
    senior: "Never return open Files.lines to callers without ownership rules.",
    javaSince: "Java 8",
    tags: ["production"],
  },
  {
    id: "pr02",
    category: "production",
    difficulty: "Architect",
    title: "Avoid parallel in request thread blindly",
    problem: "Why servlet/request threads should not blindly use parallelStream for light work.",
    input: "HTTP handler",
    output: "sequential preferred",
    solution: "// Prefer sequential streams in request path unless CPU-bound and measured.",
    pipeline: "sequential by default in request path",
    why: "commonPool contention across requests.",
    timeComplexity: "N/A",
    spaceComplexity: "N/A",
    trap: "parallelStream per request on small collections.",
    senior: "Measure under load; isolate heavy jobs to dedicated pools.",
    javaSince: "Java 8",
    tags: ["production", "parallel"],
  },
  {
    id: "pr03",
    category: "production",
    difficulty: "Advanced",
    title: "Lazy pipeline until terminal",
    problem: "Demonstrate filter/map not running before terminal collect.",
    input: "list",
    output: "side effects only on terminal",
    solution: "List<String> out = source.stream()\n  .filter(s -> { System.out.println(\"f=\"+s); return true; })\n  .map(s -> { System.out.println(\"m=\"+s); return s; })\n  .toList();",
    pipeline: "lazy intermediates \u2192 terminal toList",
    why: "Debugging laziness.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Assuming intermediate ops run at declaration.",
    senior: "Interview: Streams are lazy; pull-based by terminal.",
    javaSince: "Java 16",
    tags: ["production"],
  },
  {
    id: "pr04",
    category: "production",
    difficulty: "Expert",
    title: "Exception wrapping in map",
    problem: "Handle checked exceptions in map without silent swallow.",
    input: "paths",
    output: "list of contents",
    solution: "List<String> texts = paths.stream().map(p -> {\n  try { return Files.readString(p); }\n  catch (IOException e) { throw new UncheckedIOException(e); }\n}).toList();",
    pipeline: "stream \u2192 map(readString unchecked) \u2192 toList",
    why: "Bridge checked exceptions.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "swallowing exceptions returning null.",
    senior: "UncheckedIOException preserves cause for ops.",
    javaSince: "Java 11",
    tags: ["production"],
  },
  {
    id: "pr05",
    category: "production",
    difficulty: "Staff",
    title: "Deterministic collectors for APIs",
    problem: "Publish stable ordered JSON: LinkedHashMap grouping.",
    input: "events",
    output: "stable map",
    solution: "Map<String, Long> stable = events.stream()\n  .collect(Collectors.groupingBy(Event::type, LinkedHashMap::new, Collectors.counting()));",
    pipeline: "groupingBy(type, LinkedHashMap::new, counting)",
    why: "API stability.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "HashMap key order flapping in snapshots/tests.",
    senior: "Specify map supplier for deterministic outputs.",
    javaSince: "Java 8",
    tags: ["production"],
  },
];
