import type {StreamProblem} from './types';

export const PROBLEMS_COLLECTORS: StreamProblem[] = [
  {
    id: "c01",
    category: "collectors",
    difficulty: "Beginner",
    title: "toList / toSet / toCollection",
    problem: "Collect names to List, Set, and LinkedList.",
    input: "names",
    output: "List / Set / LinkedList",
    solution: "List<String> list = names.stream().toList(); // unmodifiable\nSet<String> set = names.stream().collect(Collectors.toSet());\nLinkedList<String> ll = names.stream().collect(Collectors.toCollection(LinkedList::new));",
    pipeline: "stream \u2192 collect(toList|toSet|toCollection)",
    why: "Choose the collection semantics you need.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Mutating Stream.toList() result (UnsupportedOperationException).",
    senior: "Java 16 toList() is unmodifiable; use toCollection for mutable.",
    javaSince: "Java 16",
    tags: ["collectors"],
  },
  {
    id: "c02",
    category: "collectors",
    difficulty: "Intermediate",
    title: "summarizingInt",
    problem: "Get count, sum, min, max, average of salaries in one pass.",
    input: "employees",
    output: "IntSummaryStatistics",
    solution: "IntSummaryStatistics stats = employees.stream().collect(Collectors.summarizingInt(Employee::salary));",
    pipeline: "stream \u2192 collect(summarizingInt)",
    why: "One pass multi-stat aggregation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Multiple separate sum/min/max passes on huge lists.",
    senior: "summarizing* is ideal for dashboards.",
    javaSince: "Java 8",
    tags: ["collectors", "employee"],
  },
  {
    id: "c03",
    category: "collectors",
    difficulty: "Intermediate",
    title: "averaging / summing",
    problem: "Average and sum of order totals.",
    input: "orders",
    output: "avg and sum",
    solution: "double avg = orders.stream().collect(Collectors.averagingDouble(o -> o.total().doubleValue()));\nBigDecimal sum = orders.stream().map(Order::total).reduce(BigDecimal.ZERO, BigDecimal::add);",
    pipeline: "stream \u2192 averagingDouble | reduce(BigDecimal)",
    why: "averagingDouble is convenient but lossy for money \u2014 prefer BigDecimal sum.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Using averagingDouble for currency.",
    senior: "FinTech interviews fail people who average money as double.",
    javaSince: "Java 8",
    tags: ["collectors"],
  },
  {
    id: "c04",
    category: "collectors",
    difficulty: "Beginner",
    title: "counting collector",
    problem: "Count elements with Collectors.counting.",
    input: "stream of events",
    output: "Long",
    solution: "long n = events.stream().collect(Collectors.counting());",
    pipeline: "stream \u2192 collect(counting)",
    why: "Useful as a downstream collector.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Using counting when stream.count() is enough.",
    senior: "Prefer stream.count() unless nesting in groupingBy.",
    javaSince: "Java 8",
    tags: ["collectors"],
  },
  {
    id: "c05",
    category: "collectors",
    difficulty: "Advanced",
    title: "collectingAndThen wrap unmodifiable",
    problem: "Collect to a mutable list then wrap as unmodifiable via collectingAndThen.",
    input: "tags",
    output: "unmodifiable List",
    solution: "List<String> frozen = tags.stream()\n  .collect(Collectors.collectingAndThen(Collectors.toList(), List::copyOf));",
    pipeline: "stream \u2192 collectingAndThen(toList, copyOf)",
    why: "collectingAndThen finishes a downstream result with a finisher function.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Returning the same mutable list from the finisher.",
    senior: "Common pattern: toMap then Collections.unmodifiableMap.",
    javaSince: "Java 8",
    tags: ["collectors", "advanced-collectors"],
  },
  {
    id: "g01",
    category: "grouping",
    difficulty: "Beginner",
    title: "groupingBy department",
    problem: "Group employees by department.",
    input: "employees",
    output: "Map<String, List<Employee>>",
    solution: "Map<String, List<Employee>> byDept = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department));",
    pipeline: "stream \u2192 collect(groupingBy)",
    why: "Classic classifier \u2192 List downstream.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Assuming map iteration order is sorted.",
    senior: "Use groupingBy(classifier, TreeMap::new, downstream) for sorted keys.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g02",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy with counting",
    problem: "Count employees per department.",
    input: "employees",
    output: "Map<String, Long>",
    solution: "Map<String, Long> counts = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, Collectors.counting()));",
    pipeline: "stream \u2192 groupingBy(dept, counting)",
    why: "Downstream collectors specialize the value type.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "Expecting Integer instead of Long from counting.",
    senior: "counting always returns Long.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g03",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy summing salaries",
    problem: "Sum salary per department.",
    input: "employees",
    output: "Map<String, Integer>",
    solution: "Map<String, Integer> payroll = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, Collectors.summingInt(Employee::salary)));",
    pipeline: "stream \u2192 groupingBy(dept, summingInt)",
    why: "Downstream numeric collectors avoid manual reduce.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "summingInt overflow for huge payrolls \u2014 use summingLong.",
    senior: "Prefer Long for money-like ints at scale.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g04",
    category: "grouping",
    difficulty: "Advanced",
    title: "Nested groupingBy",
    problem: "Group by department then by title.",
    input: "employees",
    output: "Map<String, Map<String, List<Employee>>>",
    solution: "Map<String, Map<String, List<Employee>>> nested = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.groupingBy(Employee::title)));",
    pipeline: "stream \u2192 groupingBy(dept, groupingBy(title))",
    why: "Nested groupingBy builds multi-level reports.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Deep nesting without a view/DTO becomes unreadable.",
    senior: "Staff: two-level grouping is common; three+ levels need named types.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g05",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingBy averagingDouble",
    problem: "Average order value per customer.",
    input: "orders",
    output: "Map<String, Double>",
    solution: "Map<String, Double> avg = orders.stream()\n  .collect(Collectors.groupingBy(Order::customerId,\n      Collectors.averagingDouble(o -> o.total().doubleValue())));",
    pipeline: "stream \u2192 groupingBy(customer, averagingDouble)",
    why: "Downstream average for cohort metrics.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(c)",
    trap: "Money as double in financial ledgers.",
    senior: "For money, group then reduce BigDecimal separately.",
    javaSince: "Java 8",
    tags: ["grouping", "ecommerce"],
  },
  {
    id: "g06",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy mapping names",
    problem: "Map department \u2192 list of employee names.",
    input: "employees",
    output: "Map<String, List<String>>",
    solution: "Map<String, List<String>> names = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.mapping(Employee::name, Collectors.toList())));",
    pipeline: "stream \u2192 groupingBy(dept, mapping(name, toList))",
    why: "mapping adapts element type before downstream collect.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Forgetting mapping and ending with List<Employee> when names needed.",
    senior: "mapping + joining is a frequent interview combo.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g07",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingBy collectingAndThen max",
    problem: "Per department, the highest-paid employee (Optional unwrapped).",
    input: "employees",
    output: "Map<String, Employee>",
    solution: "Map<String, Employee> top = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.collectingAndThen(\n          Collectors.maxBy(Comparator.comparingInt(Employee::salary)),\n          Optional::orElseThrow)));",
    pipeline: "stream \u2192 groupingBy(dept, collectingAndThen(maxBy, orElseThrow))",
    why: "Finish Optional downstream into a concrete value.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "orElseThrow when a group could theoretically be empty (it won't after grouping).",
    senior: "Elegant pattern for 'best per group'.",
    javaSince: "Java 8",
    tags: ["grouping", "employee", "advanced-collectors"],
  },
  {
    id: "g08",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy to Set",
    problem: "Unique job titles per department.",
    input: "employees",
    output: "Map<String, Set<String>>",
    solution: "Map<String, Set<String>> titles = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.mapping(Employee::title, Collectors.toSet())));",
    pipeline: "stream \u2192 groupingBy(dept, mapping(title, toSet))",
    why: "toSet downstream deduplicates within each group.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "toList when uniqueness is required.",
    senior: "Choose Set vs List based on reporting needs.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g09",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingByConcurrent",
    problem: "Parallel group transactions by currency.",
    input: "transactions parallel",
    output: "ConcurrentMap<String, List<Tx>>",
    solution: "Map<String, List<Tx>> byCcy = txs.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Tx::currency));",
    pipeline: "parallelStream \u2192 groupingByConcurrent",
    why: "Concurrent grouping for parallel pipelines; key order not defined.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Using groupingBy (non-concurrent) with parallelStream and shared mutable state.",
    senior: "groupingByConcurrent returns ConcurrentMap; don't rely on ordering.",
    javaSince: "Java 8",
    tags: ["grouping", "parallel", "fintech"],
  },
  {
    id: "g10",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy filtering downstream",
    problem: "Per department, only employees with salary >= 100000.",
    input: "employees",
    output: "Map with filtered lists",
    solution: "Map<String, List<Employee>> high = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.filtering(e -> e.salary() >= 100_000, Collectors.toList())));",
    pipeline: "stream \u2192 groupingBy(dept, filtering(pred, toList))",
    why: "filtering downstream keeps empty groups for departments with no matches.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Pre-filter before grouping drops empty department keys.",
    senior: "Interview nuance: filter before vs Collectors.filtering.",
    javaSince: "Java 9",
    tags: ["grouping", "employee"],
  },
  {
    id: "g11",
    category: "grouping",
    difficulty: "Expert",
    title: "groupingBy teeing aggregates",
    problem: "Per merchant, compute count and total amount together (teeing inside groups via custom approach).",
    input: "payments",
    output: "Map merchant \u2192 stats",
    solution: "record Stats(long count, BigDecimal total) {}\nMap<String, Stats> byMerchant = payments.stream()\n  .collect(Collectors.groupingBy(Payment::merchantId,\n      Collectors.teeing(\n          Collectors.counting(),\n          Collectors.mapping(Payment::amount, Collectors.reducing(BigDecimal.ZERO, BigDecimal::add)),\n          Stats::new)));",
    pipeline: "stream \u2192 groupingBy(merchant, teeing(counting, reducing))",
    why: "teeing runs two downstream collectors and merges results.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(m)",
    trap: "Writing two separate grouping passes on large ledgers.",
    senior: "Java 12+ teeing is a staff-level collector answer.",
    javaSince: "Java 12",
    tags: ["grouping", "fintech", "advanced-collectors"],
  },
  {
    id: "g12",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy order status",
    problem: "Count orders by status (NEW, PAID, SHIPPED).",
    input: "orders",
    output: "Map<Status, Long>",
    solution: "Map<Status, Long> byStatus = orders.stream()\n  .collect(Collectors.groupingBy(Order::status, Collectors.counting()));",
    pipeline: "stream \u2192 groupingBy(status, counting)",
    why: "Enum keys make reports type-safe.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Stringly-typed status keys.",
    senior: "Prefer enums for finite domain statuses.",
    javaSince: "Java 8",
    tags: ["grouping", "ecommerce"],
  },
  {
    id: "g13",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingBy year-month",
    problem: "Group trades by YearMonth of trade date.",
    input: "trades",
    output: "Map<YearMonth, List<Trade>>",
    solution: "Map<YearMonth, List<Trade>> byMonth = trades.stream()\n  .collect(Collectors.groupingBy(t -> YearMonth.from(t.tradeDate())));",
    pipeline: "stream \u2192 groupingBy(YearMonth.from)",
    why: "Temporal classifiers for financial calendars.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Grouping by Date.toString() formats.",
    senior: "Use java.time classifiers, never legacy Date strings.",
    javaSince: "Java 8",
    tags: ["grouping", "fintech", "datetime-optional"],
  },
  {
    id: "g14",
    category: "grouping",
    difficulty: "Staff",
    title: "groupingBy with TreeMap and summing",
    problem: "Department payroll report with departments sorted alphabetically.",
    input: "employees",
    output: "TreeMap dept \u2192 sum",
    solution: "Map<String, Integer> report = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, TreeMap::new,\n      Collectors.summingInt(Employee::salary)));",
    pipeline: "stream \u2192 groupingBy(dept, TreeMap::new, summingInt)",
    why: "Supplier map type controls key ordering.",
    timeComplexity: "O(n log d)",
    spaceComplexity: "O(d)",
    trap: "HashMap when UI expects sorted keys.",
    senior: "Pass map factory as second groupingBy arg.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g15",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy flatMapping skills",
    problem: "Union of skills per department.",
    input: "employees with List<String> skills",
    output: "Map<String, Set<String>>",
    solution: "Map<String, Set<String>> skills = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.flatMapping(e -> e.skills().stream(), Collectors.toSet())));",
    pipeline: "stream \u2192 groupingBy(dept, flatMapping(skills, toSet))",
    why: "flatMapping flattens nested collections inside a group.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "mapping(List) instead of flatMapping(stream).",
    senior: "Java 9 flatMapping is the clean nested-collection answer.",
    javaSince: "Java 9",
    tags: ["grouping", "employee"],
  },
  {
    id: "g16",
    category: "grouping",
    difficulty: "Beginner",
    title: "All 3 sequential groupingBy overloads",
    problem: "Show classifier-only, classifier+downstream, and classifier+mapFactory+downstream on the same data.",
    input: "employees",
    output: "three Map shapes",
    solution: "Map<String, List<Employee>> a = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department));\n\nMap<String, Long> b = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, Collectors.counting()));\n\nMap<String, Long> c = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department, TreeMap::new, Collectors.counting()));",
    pipeline: "groupingBy ×3 overloads",
    why: "Memorize the three sequential overloads — interviews ask which Map you get.",
    timeComplexity: "O(n log d) with TreeMap",
    spaceComplexity: "O(n)",
    trap: "Confusing mapFactory position with downstream.",
    senior: "3-arg is (classifier, mapFactory, downstream) — factory is middle.",
    javaSince: "Java 8",
    tags: ["grouping", "overloads"],
  },
  {
    id: "g17",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy + summarizingInt",
    problem: "Per-department salary count/sum/min/max/avg in one pass.",
    input: "employees",
    output: "Map<String, IntSummaryStatistics>",
    solution: "Map<String, IntSummaryStatistics> stats = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.summarizingInt(Employee::salary)));",
    pipeline: "groupingBy(dept, summarizingInt)",
    why: "One-pass multi-stat per group — dashboard classic.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "Running five separate groupingBy passes.",
    senior: "summarizing* is the Staff answer for KPI cards.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g18",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy + summarizingLong / Double",
    problem: "Summarize bytes transferred per host (long) and latency per route (double).",
    input: "metrics",
    output: "LongSummaryStatistics / DoubleSummaryStatistics maps",
    solution: "Map<String, LongSummaryStatistics> bytes = metrics.stream()\n  .collect(Collectors.groupingBy(Metric::host,\n      Collectors.summarizingLong(Metric::bytes)));\nMap<String, DoubleSummaryStatistics> latency = metrics.stream()\n  .collect(Collectors.groupingBy(Metric::route,\n      Collectors.summarizingDouble(Metric::latencyMs)));",
    pipeline: "groupingBy + summarizingLong|Double",
    why: "Pick the primitive summarizing collector that matches the measure.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "summarizingInt when values exceed Integer.MAX_VALUE.",
    senior: "Bytes/counters → Long; scientific measures → Double.",
    javaSince: "Java 8",
    tags: ["grouping"],
  },
  {
    id: "g19",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy + minBy",
    problem: "Lowest-paid employee per department.",
    input: "employees",
    output: "Map<String, Employee>",
    solution: "Map<String, Employee> lowest = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.collectingAndThen(\n          Collectors.minBy(Comparator.comparingInt(Employee::salary)),\n          Optional::orElseThrow)));",
    pipeline: "groupingBy → minBy → orElseThrow",
    why: "Symmetric to maxBy; always define tie-break in production.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(d)",
    trap: "Leaving Optional in the map type without a finisher.",
    senior: "Add thenComparing(Employee::id) for deterministic ties.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g20",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingBy + reducing BigDecimal",
    problem: "Sum payment amounts per merchant without double.",
    input: "payments",
    output: "Map<String, BigDecimal>",
    solution: "Map<String, BigDecimal> totals = payments.stream()\n  .collect(Collectors.groupingBy(Payment::merchantId,\n      Collectors.mapping(Payment::amount,\n          Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))));",
    pipeline: "groupingBy → mapping → reducing(ZERO, add)",
    why: "Money-safe per-group totals.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(m)",
    trap: "averagingDouble / summingDouble for currency.",
    senior: "Identity reducing avoids Optional.empty for empty groups that never appear.",
    javaSince: "Java 8",
    tags: ["grouping", "fintech"],
  },
  {
    id: "g21",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy + mapping + joining",
    problem: "Comma-separated employee names per department.",
    input: "employees",
    output: "Map<String, String>",
    solution: "Map<String, String> roster = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.mapping(Employee::name, Collectors.joining(\", \"))));",
    pipeline: "groupingBy → mapping(name, joining)",
    why: "joining is a downstream of mapping, not of groupingBy directly on Employee.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Collectors.joining on Employee (needs CharSequence).",
    senior: "Add sorted names via collectingAndThen if UI needs order.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g22",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingBy + partitioningBy downstream",
    problem: "Per department, partition high vs low earners.",
    input: "employees",
    output: "Map<String, Map<Boolean, List<Employee>>>",
    solution: "Map<String, Map<Boolean, List<Employee>>> bands = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.partitioningBy(e -> e.salary() >= 100_000)));",
    pipeline: "groupingBy(dept, partitioningBy(high))",
    why: "Combine arbitrary keys with a boolean split inside each group.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Swapping order (partition then group) changes the report shape.",
    senior: "Inner Map always has true and false keys — even if a list is empty.",
    javaSince: "Java 8",
    tags: ["grouping", "partitioning", "employee"],
  },
  {
    id: "g23",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingByConcurrent + downstream",
    problem: "Parallel count events by type.",
    input: "events (large)",
    output: "ConcurrentMap<String, Long>",
    solution: "ConcurrentMap<String, Long> counts = events.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Event::type, Collectors.counting()));",
    pipeline: "parallelStream → groupingByConcurrent(type, counting)",
    why: "2-arg concurrent overload with a real downstream.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "groupingBy + parallelStream mutating shared state.",
    senior: "Result is ConcurrentMap — no encounter order.",
    javaSince: "Java 8",
    tags: ["grouping", "parallel"],
  },
  {
    id: "g24",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingByConcurrent 3-arg mapFactory",
    problem: "Parallel group with an explicit ConcurrentHashMap supplier and summingLong.",
    input: "txs",
    output: "ConcurrentHashMap<String, Long>",
    solution: "ConcurrentHashMap<String, Long> volume = txs.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Tx::currency,\n      ConcurrentHashMap::new,\n      Collectors.summingLong(Tx::amountMinor)));",
    pipeline: "groupingByConcurrent(ccy, ConcurrentHashMap::new, summingLong)",
    why: "Completes the third concurrent overload.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(c)",
    trap: "Passing HashMap::new to groupingByConcurrent.",
    senior: "mapFactory must supply a ConcurrentMap.",
    javaSince: "Java 8",
    tags: ["grouping", "parallel", "overloads"],
  },
  {
    id: "g25",
    category: "grouping",
    difficulty: "Intermediate",
    title: "LinkedHashMap factory — encounter order",
    problem: "Frequency map that preserves first-seen key order.",
    input: "words stream",
    output: "LinkedHashMap<String, Long>",
    solution: "Map<String, Long> freq = words.stream()\n  .collect(Collectors.groupingBy(Function.identity(), LinkedHashMap::new, Collectors.counting()));",
    pipeline: "groupingBy(id, LinkedHashMap::new, counting)",
    why: "Stable iteration for JSON / first-unique scans.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(u)",
    trap: "Assuming HashMap iteration is stable.",
    senior: "First non-repeated char uses this pattern.",
    javaSince: "Java 8",
    tags: ["grouping", "overloads"],
  },
  {
    id: "g26",
    category: "grouping",
    difficulty: "Advanced",
    title: "EnumMap factory",
    problem: "Group orders by Status enum using EnumMap.",
    input: "orders",
    output: "EnumMap<Status, List<Order>>",
    solution: "Map<Status, List<Order>> byStatus = orders.stream()\n  .collect(Collectors.groupingBy(Order::status,\n      () -> new EnumMap<>(Status.class),\n      Collectors.toList()));",
    pipeline: "groupingBy(status, EnumMap::new, toList)",
    why: "Enum classifiers → dense array-backed map.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "HashMap when the key domain is a small enum.",
    senior: "EnumMap cannot hold null keys — status must be non-null.",
    javaSince: "Java 8",
    tags: ["grouping", "overloads"],
  },
  {
    id: "g27",
    category: "grouping",
    difficulty: "Advanced",
    title: "Composite key record classifier",
    problem: "Group by department + title without string concat.",
    input: "employees",
    output: "Map<DeptTitle, List<Employee>>",
    solution: "record DeptTitle(String department, String title) {}\nMap<DeptTitle, List<Employee>> m = employees.stream()\n  .collect(Collectors.groupingBy(e -> new DeptTitle(e.department(), e.title())));",
    pipeline: "groupingBy(record classifier)",
    why: "Type-safe multi-field keys; equals/hashCode from the record.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "name + \"|\" + dept concat collisions and locale bugs.",
    senior: "Records are the Java 16+ interview answer for composite keys.",
    javaSince: "Java 16",
    tags: ["grouping", "employee"],
  },
  {
    id: "g28",
    category: "grouping",
    difficulty: "Advanced",
    title: "Null-safe classifier",
    problem: "Group by optional team name without NPE.",
    input: "employees (team may be null)",
    output: "Map<String, List<Employee>>",
    solution: "Map<String, List<Employee>> byTeam = employees.stream()\n  .filter(e -> e.team() != null)\n  .collect(Collectors.groupingBy(Employee::team));\n// or: groupingBy(e -> Objects.requireNonNullElse(e.team(), \"UNASSIGNED\"))",
    pipeline: "filter(nonNull) → groupingBy | requireNonNullElse",
    why: "Null classifiers blow up HashMap compute; decide filter vs sentinel.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Silent NPE mid-collect on dirty data.",
    senior: "Staff answer: define null policy before grouping.",
    javaSince: "Java 8",
    tags: ["grouping", "edges"],
  },
  {
    id: "g29",
    category: "grouping",
    difficulty: "Intermediate",
    title: "groupingBy + toCollection",
    problem: "Department → LinkedList of employees (mutable, deque-friendly).",
    input: "employees",
    output: "Map<String, LinkedList<Employee>>",
    solution: "Map<String, LinkedList<Employee>> m = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.toCollection(LinkedList::new)));",
    pipeline: "groupingBy(dept, toCollection(LinkedList::new))",
    why: "toList/toSet are not the only collection downstreams.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Using Stream.toList() inside a custom downstream incorrectly.",
    senior: "toCollection is how you pick ArrayDeque/TreeSet per group.",
    javaSince: "Java 8",
    tags: ["grouping"],
  },
  {
    id: "g30",
    category: "grouping",
    difficulty: "Advanced",
    title: "groupingBy + reducing without identity",
    problem: "Optional max BigDecimal tip per waiter (empty group never created).",
    input: "tips",
    output: "Map<String, Optional<BigDecimal>>",
    solution: "Map<String, Optional<BigDecimal>> maxTip = tips.stream()\n  .collect(Collectors.groupingBy(Tip::waiterId,\n      Collectors.mapping(Tip::amount,\n          Collectors.reducing(BinaryOperator.maxBy(Comparator.naturalOrder())))));",
    pipeline: "groupingBy → mapping → reducing(maxBy)",
    why: "Optional-valued reducing downstream — different from identity form.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(w)",
    trap: "Confusing reducing(identity,op) with reducing(BinaryOperator).",
    senior: "Know both reducing overloads under groupingBy.",
    javaSince: "Java 8",
    tags: ["grouping", "fintech"],
  },
  {
    id: "g31",
    category: "grouping",
    difficulty: "Expert",
    title: "Three-level nested groupingBy",
    problem: "Region → department → title → list of names.",
    input: "employees",
    output: "Map<String, Map<String, Map<String, List<String>>>>",
    solution: "Map<String, Map<String, Map<String, List<String>>>> tree = employees.stream()\n  .collect(Collectors.groupingBy(Employee::region,\n      Collectors.groupingBy(Employee::department,\n          Collectors.groupingBy(Employee::title,\n              Collectors.mapping(Employee::name, Collectors.toList())))));",
    pipeline: "groupingBy³ → mapping(toList)",
    why: "Shows nested downstream chaining; prefer named DTOs past two levels.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Unreadable anonymous nesting in production code reviews.",
    senior: "Staff: stop at 2 levels or introduce a report type.",
    javaSince: "Java 8",
    tags: ["grouping", "employee"],
  },
  {
    id: "g32",
    category: "grouping",
    difficulty: "Advanced",
    title: "Freeze grouped map with collectingAndThen",
    problem: "Unmodifiable Map of unmodifiable lists per department.",
    input: "employees",
    output: "immutable Map<String, List<Employee>>",
    solution: "Map<String, List<Employee>> frozen = employees.stream()\n  .collect(Collectors.collectingAndThen(\n      Collectors.groupingBy(Employee::department,\n          Collectors.collectingAndThen(Collectors.toList(), List::copyOf)),\n      Map::copyOf));",
    pipeline: "collectingAndThen(groupingBy(…, copyOf lists), Map::copyOf)",
    why: "Publish-safe snapshots after grouping.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Only wrapping the outer map while lists stay mutable.",
    senior: "Defense in depth: freeze both map and values.",
    javaSince: "Java 10",
    tags: ["grouping"],
  },
  {
    id: "g33",
    category: "grouping",
    difficulty: "Staff",
    title: "groupingBy vs toMap — when values are unique",
    problem: "Employee id → employee when ids are unique; contrast with groupingBy.",
    input: "employees",
    output: "Map<Long, Employee> vs Map<Long, List<Employee>>",
    solution: "Map<Long, Employee> byId = employees.stream()\n  .collect(Collectors.toMap(Employee::id, Function.identity()));\n// groupingBy(Employee::id) → Map<Long, List<Employee>> even if lists are size 1\nMap<Long, Employee> also = employees.stream()\n  .collect(Collectors.groupingBy(Employee::id,\n      Collectors.collectingAndThen(Collectors.toList(), list -> list.get(0))));",
    pipeline: "toMap vs groupingBy+andThen",
    why: "toMap is the right tool for unique keys; groupingBy always bags.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Using groupingBy then get(0) when toMap was intended.",
    senior: "Say aloud: unique → toMap; multi → groupingBy.",
    javaSince: "Java 8",
    tags: ["grouping", "tomap"],
  },
  {
    id: "g34",
    category: "grouping",
    difficulty: "Intermediate",
    title: "Empty stream and missing keys",
    problem: "What does groupingBy return for empty input? Are empty departments present?",
    input: "empty list / subset of depts",
    output: "{} ; only keys that appeared",
    solution: "Map<String, List<Employee>> empty = List.<Employee>of().stream()\n  .collect(Collectors.groupingBy(Employee::department)); // {}\n// Unlike partitioningBy, keys never seen are ABSENT — not present with empty lists.",
    pipeline: "empty → groupingBy → empty Map",
    why: "Contrast with partitioningBy always having true/false.",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    trap: "NPEing on map.get(dept).size() when dept never appeared.",
    senior: "getOrDefault(dept, List.of()) for safe reads.",
    javaSince: "Java 8",
    tags: ["grouping", "edges"],
  },
  {
    id: "g35",
    category: "grouping",
    difficulty: "Staff",
    title: "All 3 groupingByConcurrent overloads",
    problem: "Demonstrate classifier-only, +downstream, and +mapFactory+downstream concurrent forms.",
    input: "events parallelStream",
    output: "three ConcurrentMap shapes",
    solution: "ConcurrentMap<String, List<Event>> a = events.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Event::type));\n\nConcurrentMap<String, Long> b = events.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Event::type, Collectors.counting()));\n\nConcurrentMap<String, Long> c = events.parallelStream()\n  .collect(Collectors.groupingByConcurrent(Event::type,\n      ConcurrentHashMap::new, Collectors.counting()));",
    pipeline: "groupingByConcurrent ×3 overloads",
    why: "Closes the concurrent overload matrix next to g16.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Expecting List encounter order from concurrent grouping.",
    senior: "Use only when grouping dominates and key cardinality is high enough.",
    javaSince: "Java 8",
    tags: ["grouping", "parallel", "overloads"],
  },
  {
    id: "p01",
    category: "partitioning",
    difficulty: "Beginner",
    title: "partitioningBy predicate",
    problem: "Partition integers into even/odd.",
    input: "[1,2,3,4]",
    output: "{false=[1,3], true=[2,4]}",
    solution: "Map<Boolean, List<Integer>> parts = List.of(1,2,3,4).stream()\n  .collect(Collectors.partitioningBy(n -> n % 2 == 0));",
    pipeline: "stream → partitioningBy(pred)",
    why: "Always returns both true and false keys.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Expecting missing key when one side is empty — key still present with empty list.",
    senior: "partitioningBy is a specialized groupingBy(Boolean).",
    javaSince: "Java 8",
    tags: ["partitioning"],
  },
  {
    id: "p02",
    category: "partitioning",
    difficulty: "Intermediate",
    title: "partitioningBy employees high earner",
    problem: "Partition employees by salary >= 150000.",
    input: "employees",
    output: "Map<Boolean, List<Employee>>",
    solution: "Map<Boolean, List<Employee>> bands = employees.stream()\n  .collect(Collectors.partitioningBy(e -> e.salary() >= 150_000));",
    pipeline: "stream → partitioningBy(salary>=)",
    why: "Boolean partitions for HR bands.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Using groupingBy with Boolean manually.",
    senior: "Prefer partitioningBy for two-way splits.",
    javaSince: "Java 8",
    tags: ["partitioning", "employee"],
  },
  {
    id: "p03",
    category: "partitioning",
    difficulty: "Advanced",
    title: "partitioningBy with downstream counting",
    problem: "Count paid vs unpaid invoices.",
    input: "invoices",
    output: "Map<Boolean, Long>",
    solution: "Map<Boolean, Long> counts = invoices.stream()\n  .collect(Collectors.partitioningBy(Invoice::paid, Collectors.counting()));",
    pipeline: "stream → partitioningBy(paid, counting)",
    why: "Downstream works like groupingBy.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Ignoring that both keys always exist.",
    senior: "Useful for KPI dashboards (paid ratio).",
    javaSince: "Java 8",
    tags: ["partitioning", "fintech"],
  },
  {
    id: "p04",
    category: "partitioning",
    difficulty: "Intermediate",
    title: "partitioningBy prime check",
    problem: "Partition 1..20 into primes vs non-primes.",
    input: "1..20",
    output: "true=primes",
    solution: "Map<Boolean, List<Integer>> parts = IntStream.rangeClosed(1, 20).boxed()\n  .collect(Collectors.partitioningBy(n -> n > 1 && IntStream.rangeClosed(2, (int)Math.sqrt(n)).noneMatch(d -> n % d == 0)));",
    pipeline: "range \u2192 boxed \u2192 partitioningBy(isPrime)",
    why: "Illustrates partitioning with a non-trivial predicate.",
    timeComplexity: "O(n\u221an)",
    spaceComplexity: "O(n)",
    trap: "Calling isPrime with trial division in a hot path without caching.",
    senior: "Show clarity first; optimize later.",
    javaSince: "Java 8",
    tags: ["partitioning"],
  },
  {
    id: "tj01",
    category: "tomap-joining",
    difficulty: "Beginner",
    title: "joining with delimiter",
    problem: "Join names with comma and space.",
    input: "[\"Ada\",\"Lin\"]",
    output: "Ada, Lin",
    solution: "String s = List.of(\"Ada\",\"Lin\").stream().collect(Collectors.joining(\", \"));",
    pipeline: "stream \u2192 joining",
    why: "joining is the idiomatic Collector for String concatenation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "reduce with + for many strings (quadratic risk).",
    senior: "Prefer Collectors.joining over manual StringBuilder in Streams.",
    javaSince: "Java 8",
    tags: ["tomap-joining"],
  },
  {
    id: "tj02",
    category: "tomap-joining",
    difficulty: "Intermediate",
    title: "toMap with merge function",
    problem: "Build Map sku\u2192qty merging duplicate SKUs by summing quantities.",
    input: "line items with duplicate sku",
    output: "{SKU1=5, ...}",
    solution: "Map<String, Integer> qty = items.stream()\n  .collect(Collectors.toMap(LineItem::sku, LineItem::qty, Integer::sum));",
    pipeline: "stream \u2192 toMap(key, value, merge)",
    why: "Merge function resolves duplicate keys; without it duplicates throw.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "toMap without merge on duplicate keys \u2192 IllegalStateException.",
    senior: "Always provide merge when keys may collide.",
    javaSince: "Java 8",
    tags: ["tomap-joining", "ecommerce"],
  },
  {
    id: "tj03",
    category: "tomap-joining",
    difficulty: "Advanced",
    title: "toMap last-win LinkedHashMap",
    problem: "Index employees by id keeping insertion order; last duplicate wins.",
    input: "employees possibly duplicate id",
    output: "LinkedHashMap",
    solution: "Map<String, Employee> byId = employees.stream()\n  .collect(Collectors.toMap(Employee::id, Function.identity(), (a, b) -> b, LinkedHashMap::new));",
    pipeline: "stream \u2192 toMap(id, identity, last-win, LinkedHashMap)",
    why: "Four-arg toMap controls map type and collision policy.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "First-win vs last-win ambiguity in ETL.",
    senior: "Document merge policy in data ingestion code.",
    javaSince: "Java 8",
    tags: ["tomap-joining", "employee"],
  },
  {
    id: "tj04",
    category: "tomap-joining",
    difficulty: "Intermediate",
    title: "joining with prefix suffix",
    problem: "Render SQL IN clause list.",
    input: "[\"u1\",\"u2\"]",
    output: "(u1,u2)",
    solution: "String in = ids.stream().collect(Collectors.joining(\",\", \"(\", \")\"));",
    pipeline: "stream \u2192 joining(delim, prefix, suffix)",
    why: "Prefix/suffix form complete literal fragments.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "SQL injection if ids aren't sanitized \u2014 Streams don't make SQL safe.",
    senior: "Use parameters/bind variables; joining is only for display or trusted ids.",
    javaSince: "Java 8",
    tags: ["tomap-joining"],
  },
  {
    id: "tj05",
    category: "tomap-joining",
    difficulty: "Expert",
    title: "toMap with BigDecimal merge",
    problem: "Aggregate ledger entries accountId \u2192 balance delta.",
    input: "entries",
    output: "Map<String, BigDecimal>",
    solution: "Map<String, BigDecimal> balances = entries.stream()\n  .collect(Collectors.toMap(Entry::accountId, Entry::amount, BigDecimal::add));",
    pipeline: "stream \u2192 toMap(account, amount, BigDecimal::add)",
    why: "Merge with BigDecimal::add for monetary aggregation.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(a)",
    trap: "double sums for balances.",
    senior: "Core FinTech Stream pattern.",
    javaSince: "Java 8",
    tags: ["tomap-joining", "fintech"],
  },
  {
    id: "tn01",
    category: "topn-nth",
    difficulty: "Intermediate",
    title: "Top N salaries",
    problem: "Return top 3 salaries descending.",
    input: "salary list",
    output: "[220000, 180000, 150000]",
    solution: "List<Integer> top3 = salaries.stream()\n  .sorted(Comparator.reverseOrder())\n  .limit(3)\n  .toList();",
    pipeline: "stream \u2192 sorted(desc) \u2192 limit(3)",
    why: "Simple top-N via sort+limit.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "For huge n, sort-all is wasteful vs heap of size k.",
    senior: "Mention PriorityQueue for O(n log k) follow-up.",
    javaSince: "Java 16",
    tags: ["topn-nth"],
  },
  {
    id: "tn02",
    category: "topn-nth",
    difficulty: "Advanced",
    title: "Nth highest distinct vs non-distinct",
    problem: "Find 2nd highest distinct salary vs 2nd highest allowing duplicates.",
    input: "[100,100,90,80]",
    output: "distinct 2nd=90; non-distinct 2nd=100",
    solution: "OptionalInt secondDistinct = salaries.stream().mapToInt(Integer::intValue)\n  .distinct().boxed().sorted(Comparator.reverseOrder()).skip(1).mapToInt(Integer::intValue).findFirst();\nOptionalInt secondRaw = salaries.stream().mapToInt(Integer::intValue)\n  .boxed().sorted(Comparator.reverseOrder()).skip(1).mapToInt(Integer::intValue).findFirst();",
    pipeline: "stream \u2192 (distinct?) \u2192 sorted(desc) \u2192 skip(n-1) \u2192 findFirst",
    why: "Interviewers test whether you distinct before ranking.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Forgetting distinct when the problem says unique salaries.",
    senior: "Clarify distinct vs multiset ranking before coding.",
    javaSince: "Java 8",
    tags: ["topn-nth", "employee"],
  },
  {
    id: "tn03",
    category: "topn-nth",
    difficulty: "Intermediate",
    title: "Nth order by total",
    problem: "Find the 3rd largest order by BigDecimal total.",
    input: "orders",
    output: "Optional<Order>",
    solution: "Optional<Order> third = orders.stream()\n  .sorted(Comparator.comparing(Order::total).reversed())\n  .skip(2)\n  .findFirst();",
    pipeline: "stream \u2192 sorted(desc total) \u2192 skip(2) \u2192 findFirst",
    why: "skip(n-1)+findFirst is the nth pattern.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "skip(3) off-by-one for 3rd.",
    senior: "State n clearly; off-by-one is the common bug.",
    javaSince: "Java 16",
    tags: ["topn-nth", "ecommerce"],
  },
  {
    id: "tn04",
    category: "topn-nth",
    difficulty: "Expert",
    title: "Top N per group",
    problem: "Top 2 earners per department.",
    input: "employees",
    output: "Map<String, List<Employee>>",
    solution: "Map<String, List<Employee>> top2 = employees.stream()\n  .collect(Collectors.groupingBy(Employee::department,\n      Collectors.collectingAndThen(Collectors.toList(), list -> list.stream()\n          .sorted(Comparator.comparingInt(Employee::salary).reversed())\n          .limit(2)\n          .toList())));",
    pipeline: "groupingBy \u2192 collectingAndThen(sort+limit)",
    why: "Per-group top-N needs finisher sort or a custom accumulator.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    trap: "Global top-N then group (wrong).",
    senior: "Staff follow-up: bounded PriorityQueue per group.",
    javaSince: "Java 16",
    tags: ["topn-nth", "grouping", "employee"],
  },
  {
    id: "tn05",
    category: "topn-nth",
    difficulty: "Beginner",
    title: "First N words",
    problem: "Take first 5 words from a list.",
    input: "words",
    output: "5 words",
    solution: "List<String> first = words.stream().limit(5).toList();",
    pipeline: "stream \u2192 limit \u2192 toList",
    why: "limit without sort = first encounter order.",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
    trap: "Calling this top-N when order isn't ranked.",
    senior: "Name the method carefully: prefix vs top.",
    javaSince: "Java 16",
    tags: ["topn-nth"],
  },
  {
    id: "df01",
    category: "duplicates-freq",
    difficulty: "Beginner",
    title: "Frequency map with groupingBy",
    problem: "Build frequency map of words.",
    input: "[\"a\",\"b\",\"a\"]",
    output: "{a=2, b=1}",
    solution: "Map<String, Long> freq = words.stream()\n  .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));",
    pipeline: "stream \u2192 groupingBy(identity, counting)",
    why: "Standard frequency histogram.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "toMap without merge on duplicates.",
    senior: "groupingBy+counting is the default interview answer.",
    javaSince: "Java 8",
    tags: ["duplicates-freq"],
  },
  {
    id: "df02",
    category: "duplicates-freq",
    difficulty: "Intermediate",
    title: "Find duplicates only",
    problem: "Return elements that appear more than once.",
    input: "[1,2,2,3,3,3]",
    output: "[2, 3]",
    solution: "List<Integer> dups = nums.stream()\n  .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))\n  .entrySet().stream()\n  .filter(e -> e.getValue() > 1)\n  .map(Map.Entry::getKey)\n  .toList();",
    pipeline: "groupingBy \u2192 filter(count>1) \u2192 keys",
    why: "Two-stage: count then filter.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Using distinct thinking it returns duplicates.",
    senior: "distinct removes dups; it does not list them.",
    javaSince: "Java 16",
    tags: ["duplicates-freq"],
  },
  {
    id: "df03",
    category: "duplicates-freq",
    difficulty: "Advanced",
    title: "First non-repeated character",
    problem: "Find the first character in a string that appears exactly once.",
    input: "\"swiss\"",
    output: "w",
    solution: "Optional<Character> first = \"swiss\".chars()\n  .mapToObj(c -> (char) c)\n  .collect(Collectors.groupingBy(Function.identity(), LinkedHashMap::new, Collectors.counting()))\n  .entrySet().stream()\n  .filter(e -> e.getValue() == 1)\n  .map(Map.Entry::getKey)\n  .findFirst();",
    pipeline: "chars \u2192 groupingBy(LinkedHashMap, counting) \u2192 filter \u2192 findFirst",
    why: "LinkedHashMap preserves first-seen order for 'first' semantics.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1) alphabet",
    trap: "HashMap loses encounter order for first-non-repeated.",
    senior: "Classic string+Stream interview question.",
    javaSince: "Java 8",
    tags: ["duplicates-freq", "strings"],
  },
  {
    id: "df04",
    category: "duplicates-freq",
    difficulty: "Intermediate",
    title: "Mode of a list",
    problem: "Find the most frequent integer (mode).",
    input: "[1,1,2,2,2,3]",
    output: "2",
    solution: "Optional<Integer> mode = nums.stream()\n  .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))\n  .entrySet().stream()\n  .max(Map.Entry.comparingByValue())\n  .map(Map.Entry::getKey);",
    pipeline: "groupingBy \u2192 max(byValue)",
    why: "Mode via frequency then max.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    trap: "Undefined behavior on ties \u2014 specify policy.",
    senior: "Clarify tie-break in product requirements.",
    javaSince: "Java 8",
    tags: ["duplicates-freq"],
  },
  {
    id: "df05",
    category: "duplicates-freq",
    difficulty: "Expert",
    title: "Duplicate emails in employees",
    problem: "List emails that appear more than once.",
    input: "employees",
    output: "[dup@corp.com]",
    solution: "List<String> dupEmails = employees.stream()\n  .collect(Collectors.groupingBy(Employee::email, Collectors.counting()))\n  .entrySet().stream()\n  .filter(e -> e.getValue() > 1)\n  .map(Map.Entry::getKey)\n  .toList();",
    pipeline: "groupingBy(email, counting) \u2192 filter",
    why: "Data-quality check via Streams.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Case-sensitive email compare without normalizing.",
    senior: "Normalize email.toLowerCase(Locale.ROOT) before grouping.",
    javaSince: "Java 16",
    tags: ["duplicates-freq", "employee"],
  },
  {
    id: "ac01",
    category: "advanced-collectors",
    difficulty: "Expert",
    title: "Collectors.teeing basics",
    problem: "Compute count and sum of ints in one pass with teeing.",
    input: "[1,2,3,4]",
    output: "count=4 sum=10",
    solution: "record CountSum(long count, int sum) {}\nCountSum cs = List.of(1,2,3,4).stream().collect(Collectors.teeing(\n  Collectors.counting(),\n  Collectors.summingInt(Integer::intValue),\n  CountSum::new));",
    pipeline: "stream \u2192 teeing(counting, summingInt, merge)",
    why: "Dual collector fan-out.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Java version < 12.",
    senior: "teeing is Java 12+.",
    javaSince: "Java 12",
    tags: ["advanced-collectors"],
  },
  {
    id: "ac02",
    category: "advanced-collectors",
    difficulty: "Advanced",
    title: "collectingAndThen to unmodifiable Set",
    problem: "Finish toSet with Set.copyOf.",
    input: "tags",
    output: "unmodifiable Set",
    solution: "Set<String> frozen = tags.stream()\n  .collect(Collectors.collectingAndThen(Collectors.toSet(), Set::copyOf));",
    pipeline: "collectingAndThen(toSet, copyOf)",
    why: "Finisher transforms result.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Returning mutable set from API.",
    senior: "Defensive copies at API boundaries.",
    javaSince: "Java 10",
    tags: ["advanced-collectors"],
  },
  {
    id: "ac03",
    category: "advanced-collectors",
    difficulty: "Staff",
    title: "filtering + flatMapping combo",
    problem: "Group orders by customer keeping only SKUs starting with 'A'.",
    input: "orders",
    output: "Map customer \u2192 Set sku",
    solution: "Map<String, Set<String>> m = orders.stream()\n  .collect(Collectors.groupingBy(Order::customerId,\n      Collectors.flatMapping(o -> o.items().stream().map(LineItem::sku),\n          Collectors.filtering(sku -> sku.startsWith(\"A\"), Collectors.toSet()))));",
    pipeline: "groupingBy \u2192 flatMapping \u2192 filtering \u2192 toSet",
    why: "Java 9 downstream combinators.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Wrong order filtering vs flatMapping.",
    senior: "Compose downstream collectors deliberately.",
    javaSince: "Java 9",
    tags: ["advanced-collectors", "ecommerce"],
  },
  {
    id: "ac04",
    category: "advanced-collectors",
    difficulty: "Expert",
    title: "Custom Collector sketch via of",
    problem: "Outline Collector.of for joining uniquely with '|'.",
    input: "strings",
    output: "a|b|c",
    solution: "Collector<String, ?, String> uniquePipe = Collector.of(\n  LinkedHashSet::new,\n  Set::add,\n  (a, b) -> { a.addAll(b); return a; },\n  set -> String.join(\"|\", set));\nString out = stream.collect(uniquePipe);",
    pipeline: "Collector.of(supplier, acc, combiner, finisher)",
    why: "Custom collector anatomy.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    trap: "Non-concurrent collector used with CONCURRENT characteristic wrongly.",
    senior: "Know the four functions + characteristics.",
    javaSince: "Java 8",
    tags: ["advanced-collectors"],
  },
  {
    id: "ac05",
    category: "advanced-collectors",
    difficulty: "Architect",
    title: "teeing min and max salary",
    problem: "Single pass min and max employee salary.",
    input: "employees",
    output: "record(min,max)",
    solution: "record MinMax(int min, int max) {}\nMinMax mm = employees.stream().collect(Collectors.teeing(\n  Collectors.collectingAndThen(Collectors.minBy(Comparator.comparingInt(Employee::salary)),\n      o -> o.orElseThrow().salary()),\n  Collectors.collectingAndThen(Collectors.maxBy(Comparator.comparingInt(Employee::salary)),\n      o -> o.orElseThrow().salary()),\n  MinMax::new));",
    pipeline: "teeing(minBy, maxBy)",
    why: "Range in one pass.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    trap: "Two passes summarizing without need.",
    senior: "summarizingInt also exposes min/max \u2014 mention both.",
    alternative: "IntSummaryStatistics stats = employees.stream().collect(Collectors.summarizingInt(Employee::salary));",
    javaSince: "Java 12",
    tags: ["advanced-collectors", "employee"],
  },
];
