import type {CodingRoundQ, DebugQ, PredictionQ, RankedProblem} from './types';
import {ALL_PROBLEMS} from './catalog';

export const CODING_ROUND: CodingRoundQ[] = [
  {
    id: 'cr01',
    question: 'Given employees, return Map<department, Double> average salary.',
    difficulty: 'Intermediate',
    expectedMinutes: 8,
    approach: 'groupingBy + averagingDouble',
    hints: ['Collectors.groupingBy', 'averagingDouble(Employee::salary)'],
    solution:
      'emps.stream().collect(Collectors.groupingBy(Employee::department, Collectors.averagingDouble(Employee::salary)));',
    complexity: 'O(n) time, O(d) space',
    followUp: 'Use BigDecimal averaging? How?',
  },
  {
    id: 'cr02',
    question: 'Second highest distinct salary.',
    difficulty: 'Intermediate',
    expectedMinutes: 10,
    approach: 'map salary → distinct → sorted desc → skip 1 → findFirst',
    hints: ['Ask if duplicates count', 'distinct before skip'],
    solution:
      'emps.stream().map(Employee::salary).distinct().sorted(Comparator.reverseOrder()).skip(1).findFirst();',
    complexity: 'O(n log n) with sort; can do O(n) selection',
    followUp: 'Per department?',
  },
  {
    id: 'cr03',
    question: 'Flatten customer→orders→items to total revenue.',
    difficulty: 'Advanced',
    expectedMinutes: 12,
    approach: 'flatMap twice + reduce BigDecimal',
    hints: ['flatMap orders', 'flatMap items', 'qty * unitPrice'],
    solution:
      'customers.stream().flatMap(c->c.orders().stream()).flatMap(o->o.items().stream())\n  .map(i->i.unitPrice().multiply(BigDecimal.valueOf(i.qty()))).reduce(BigDecimal.ZERO, BigDecimal::add);',
    complexity: 'O(n) over items',
    followUp: 'Group revenue by category.',
  },
  {
    id: 'cr04',
    question: 'First non-repeated character in a string (preserve order).',
    difficulty: 'Intermediate',
    expectedMinutes: 10,
    approach: 'LinkedHashMap frequency then filter count==1',
    hints: ['groupingBy with LinkedHashMap', 'or two-pass'],
    solution:
      's.chars().mapToObj(c->(char)c).collect(Collectors.groupingBy(c->c, LinkedHashMap::new, Collectors.counting()))\n  .entrySet().stream().filter(e->e.getValue()==1L).map(Map.Entry::getKey).findFirst();',
    complexity: 'O(n)',
    followUp: 'Unicode code points?',
  },
  {
    id: 'cr05',
    question: 'Word frequency for a sentence (lowercase).',
    difficulty: 'Beginner',
    expectedMinutes: 6,
    approach: 'split → filter blank → groupingBy counting',
    hints: ['Arrays.stream(split)', 'toLowerCase'],
    solution:
      'Arrays.stream(sentence.toLowerCase().split("\\\\W+")).filter(w->!w.isBlank())\n  .collect(Collectors.groupingBy(w->w, Collectors.counting()));',
    complexity: 'O(n)',
    followUp: 'Top-K words?',
  },
  {
    id: 'cr06',
    question: 'Intersection of two integer lists (unique).',
    difficulty: 'Beginner',
    expectedMinutes: 5,
    approach: 'toSet + filter contains',
    hints: ['HashSet for O(1) lookup'],
    solution: 'Set<Integer> b=new HashSet<>(list2);\nlist1.stream().filter(b::contains).distinct().toList();',
    complexity: 'O(n+m)',
    followUp: 'Preserve order of list1?',
  },
  {
    id: 'cr07',
    question: 'Top 3 employees by salary per department.',
    difficulty: 'Advanced',
    expectedMinutes: 15,
    approach: 'groupingBy + collectingAndThen sorted limit',
    hints: ['downstream collectingAndThen'],
    solution:
      'emps.stream().collect(Collectors.groupingBy(Employee::department,\n  Collectors.collectingAndThen(Collectors.toList(),\n    list -> list.stream().sorted(Comparator.comparingDouble(Employee::salary).reversed()).limit(3).toList())));',
    complexity: 'O(n log n) per group worst-case',
    followUp: 'Priority queue per group for large n?',
  },
  {
    id: 'cr08',
    question: 'Partition transactions success vs failed counts.',
    difficulty: 'Intermediate',
    expectedMinutes: 7,
    approach: 'partitioningBy + counting',
    hints: ['partitioningBy(predicate, counting())'],
    solution:
      'txs.stream().collect(Collectors.partitioningBy(t->"SUCCESS".equals(t.status()), Collectors.counting()));',
    complexity: 'O(n)',
    followUp: 'Success rate percentage?',
  },
  {
    id: 'cr09',
    question: 'Anagram check with streams.',
    difficulty: 'Intermediate',
    expectedMinutes: 8,
    approach: 'normalize → chars sorted → equals OR frequency maps',
    hints: ['sorted joining', 'frequency O(n) better'],
    solution:
      'String norm(String s){ return s.toLowerCase().chars().sorted().collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append).toString(); }\nreturn norm(a).equals(norm(b));',
    complexity: 'O(n log n) sort; O(n) freq better',
    followUp: 'Which is faster for long strings?',
  },
  {
    id: 'cr10',
    question: 'Safe parallel sum of integers.',
    difficulty: 'Intermediate',
    expectedMinutes: 5,
    approach: 'mapToInt.sum',
    hints: ['No shared array'],
    solution: 'list.parallelStream().mapToInt(Integer::intValue).sum();',
    complexity: 'O(n/p)',
    followUp: 'Why forEach+= is wrong?',
  },
  {
    id: 'cr11',
    question: 'Join employee names as CSV with brackets.',
    difficulty: 'Beginner',
    expectedMinutes: 4,
    approach: 'Collectors.joining',
    hints: ['joining(delim, prefix, suffix)'],
    solution: 'emps.stream().map(Employee::name).collect(Collectors.joining(",","[","]"));',
    complexity: 'O(n)',
    followUp: 'Escape commas in names?',
  },
  {
    id: 'cr12',
    question: 'Min and max salary in one pass (teeing).',
    difficulty: 'Advanced',
    expectedMinutes: 10,
    approach: 'Collectors.teeing minBy maxBy',
    hints: ['Java 12+ teeing'],
    solution:
      'emps.stream().collect(Collectors.teeing(\n  Collectors.minBy(Comparator.comparingDouble(Employee::salary)),\n  Collectors.maxBy(Comparator.comparingDouble(Employee::salary)),\n  (min,max)->Map.of("min",min,"max",max)));',
    complexity: 'O(n)',
    followUp: 'Without teeing?',
  },
  {
    id: 'cr13',
    question: 'Employees with skill "Java".',
    difficulty: 'Beginner',
    expectedMinutes: 4,
    approach: 'filter skills contains',
    hints: ['List.contains'],
    solution: 'emps.stream().filter(e->e.skills().contains("Java")).toList();',
    complexity: 'O(n*k)',
    followUp: 'Case insensitive skills?',
  },
  {
    id: 'cr14',
    question: 'Most common skill across employees.',
    difficulty: 'Advanced',
    expectedMinutes: 12,
    approach: 'flatMap skills → groupingBy counting → maxBy',
    hints: ['flatMap Collection::stream'],
    solution:
      'emps.stream().flatMap(e->e.skills().stream()).collect(Collectors.groupingBy(s->s, Collectors.counting()))\n  .entrySet().stream().max(Map.Entry.comparingByValue());',
    complexity: 'O(total skills)',
    followUp: 'Top 3 skills?',
  },
  {
    id: 'cr15',
    question: 'Latest transaction per accountId.',
    difficulty: 'Advanced',
    expectedMinutes: 12,
    approach: 'toMap merge by timestamp',
    hints: ['BinaryOperator.maxBy'],
    solution:
      'txs.stream().collect(Collectors.toMap(Tx::accountId, t->t, BinaryOperator.maxBy(Comparator.comparing(Tx::ts))));',
    complexity: 'O(n)',
    followUp: 'groupingBy + maxBy downstream?',
  },
  {
    id: 'cr16',
    question: 'Department with highest average salary.',
    difficulty: 'Advanced',
    expectedMinutes: 10,
    approach: 'groupingBy averagingDouble then max entry',
    hints: ['entrySet stream max'],
    solution:
      'emps.stream().collect(Collectors.groupingBy(Employee::department, Collectors.averagingDouble(Employee::salary)))\n  .entrySet().stream().max(Map.Entry.comparingByValue());',
    complexity: 'O(n)',
    followUp: 'Tie-break by department name?',
  },
  {
    id: 'cr17',
    question: 'Failed transaction percentage.',
    difficulty: 'Intermediate',
    expectedMinutes: 8,
    approach: 'partitioningBy counting then math',
    hints: ['avoid div by zero'],
    solution:
      'Map<Boolean,Long> p=txs.stream().collect(Collectors.partitioningBy(t->"FAILED".equals(t.status()), Collectors.counting()));\ndouble pct=p.values().stream().mapToLong(Long::longValue).sum()==0?0:(100.0*p.get(true))/(p.get(true)+p.get(false));',
    complexity: 'O(n)',
    followUp: 'Per currency?',
  },
  {
    id: 'cr18',
    question: 'Sort map by value descending; top 5 keys.',
    difficulty: 'Intermediate',
    expectedMinutes: 8,
    approach: 'entrySet stream sorted limit',
    hints: ['comparingByValue reversed'],
    solution:
      'map.entrySet().stream().sorted(Map.Entry.<String,Long>comparingByValue().reversed()).limit(5).map(Map.Entry::getKey).toList();',
    complexity: 'O(n log n)',
    followUp: 'Priority queue for top-K?',
  },
  {
    id: 'cr19',
    question: 'Symmetric difference of two lists.',
    difficulty: 'Intermediate',
    expectedMinutes: 10,
    approach: 'sets: (a-b)∪(b-a)',
    hints: ['filter !contains both ways'],
    solution:
      'Set<Integer> A=new HashSet<>(a), B=new HashSet<>(b);\nStream.concat(A.stream().filter(x->!B.contains(x)), B.stream().filter(x->!A.contains(x))).toList();',
    complexity: 'O(n+m)',
    followUp: 'Multiset semantics?',
  },
  {
    id: 'cr20',
    question: 'Group orders by year-month.',
    difficulty: 'Intermediate',
    expectedMinutes: 8,
    approach: 'groupingBy YearMonth.from',
    hints: ['placedAt to YearMonth'],
    solution:
      'orders.stream().collect(Collectors.groupingBy(o -> YearMonth.from(o.placedAt())));',
    complexity: 'O(n)',
    followUp: 'Timezone for Instant?',
  },
  {
    id: 'cr21',
    question: 'Immutable list via collectingAndThen.',
    difficulty: 'Intermediate',
    expectedMinutes: 5,
    approach: 'collectingAndThen toList + unmodifiable / toList already unmodifiable in 16',
    hints: ['Java 16 toList is unmodifiable'],
    solution: 'list.stream().map(String::trim).toList(); // already unmodifiable (Java 16+)',
    complexity: 'O(n)',
    followUp: 'Difference vs collect(toList())?',
  },
  {
    id: 'cr22',
    question: 'AnyMatch allMatch noneMatch on payments.',
    difficulty: 'Beginner',
    expectedMinutes: 5,
    approach: 'short-circuit matchers',
    hints: ['any failed', 'all success', 'none negative'],
    solution:
      'boolean anyFail=txs.stream().anyMatch(t->"FAILED".equals(t.status()));\nboolean allOk=txs.stream().allMatch(t->"SUCCESS".equals(t.status()));',
    complexity: 'O(n) worst; short-circuit best',
    followUp: 'Empty stream allMatch?',
  },
  {
    id: 'cr23',
    question: 'Reduce product of integers with identity 1.',
    difficulty: 'Beginner',
    expectedMinutes: 4,
    approach: 'reduce(1, (a,b)->a*b)',
    hints: ['overflow?'],
    solution: 'list.stream().reduce(1, (a,b)->a*b);',
    complexity: 'O(n)',
    followUp: 'Parallel combiner?',
  },
  {
    id: 'cr24',
    question: 'Custom Collector that joins with AND.',
    difficulty: 'Expert',
    expectedMinutes: 15,
    approach: 'supplier StringBuilder, accumulator append, combiner append, finisher toString',
    hints: ['Collector.of'],
    solution:
      'Collector.of(StringBuilder::new, (sb,s)->{ if(sb.length()>0) sb.append(" AND "); sb.append(s); }, StringBuilder::append, StringBuilder::toString)',
    complexity: 'O(n)',
    followUp: 'When not to write custom collectors?',
  },
  {
    id: 'cr25',
    question: 'Detect duplicate transaction IDs.',
    difficulty: 'Intermediate',
    expectedMinutes: 8,
    approach: 'groupingBy id counting filter >1',
    hints: ['entrySet filter'],
    solution:
      'txs.stream().collect(Collectors.groupingBy(Tx::id, Collectors.counting()))\n  .entrySet().stream().filter(e->e.getValue()>1).map(Map.Entry::getKey).toList();',
    complexity: 'O(n)',
    followUp: 'First duplicate only?',
  },
  {
    id: 'cr26',
    question: 'Employees joined after a date.',
    difficulty: 'Beginner',
    expectedMinutes: 4,
    approach: 'filter joiningDate',
    hints: ['isAfter'],
    solution: 'emps.stream().filter(e->e.joiningDate().isAfter(cutoff)).toList();',
    complexity: 'O(n)',
    followUp: 'Inclusive boundary?',
  },
  {
    id: 'cr27',
    question: 'Revenue by product category (ecommerce).',
    difficulty: 'Advanced',
    expectedMinutes: 12,
    approach: 'flatMap items + join product category + grouping summing',
    hints: ['Need product lookup map'],
    solution:
      'Map<Long,Product> byId=products.stream().collect(Collectors.toMap(Product::id,p->p));\nitems.stream().collect(Collectors.groupingBy(i->byId.get(i.productId()).category(),\n  Collectors.mapping(i->i.unitPrice().multiply(BigDecimal.valueOf(i.qty())), Collectors.reducing(BigDecimal.ZERO, BigDecimal::add))));',
    complexity: 'O(n)',
    followUp: 'Missing product id?',
  },
  {
    id: 'cr28',
    question: 'Explain empty stream allMatch/anyMatch results.',
    difficulty: 'Intermediate',
    expectedMinutes: 5,
    approach: 'vacuous truth',
    hints: ['allMatch true, anyMatch false, noneMatch true'],
    solution: 'Stream.empty().allMatch(x->false) == true; anyMatch == false; noneMatch == true;',
    complexity: 'O(1)',
    followUp: 'Why vacuous truth?',
  },
  {
    id: 'cr29',
    question: 'Group employees by salary range buckets.',
    difficulty: 'Advanced',
    expectedMinutes: 10,
    approach: 'groupingBy classifier function ranges',
    hints: ['if salary < X "LOW" else …'],
    solution:
      'emps.stream().collect(Collectors.groupingBy(e -> e.salary()<80_000?"LOW":e.salary()<150_000?"MID":"HIGH"));',
    complexity: 'O(n)',
    followUp: 'NavigableMap buckets?',
  },
  {
    id: 'cr30',
    question: 'Parallel groupingBy vs groupingByConcurrent trade-off.',
    difficulty: 'Staff',
    expectedMinutes: 10,
    approach: 'discuss merge vs concurrent map',
    hints: ['ORDERED', 'contention'],
    solution:
      '// Prefer groupingBy (thread-local then merge) unless profiling says otherwise\nemps.parallelStream().collect(Collectors.groupingByConcurrent(Employee::department));',
    complexity: 'O(n)',
    followUp: 'When concurrent loses?',
  },
];

export const PREDICTIONS: PredictionQ[] = [
  {
    id: 'pr01',
    code: `List.of(1,2,3).stream()\n  .filter(n -> { System.out.print("f"+n); return n>1; })\n  .map(n -> { System.out.print("m"+n); return n; })\n  .findFirst();`,
    question: 'What is printed before the Optional result?',
    answer: 'f1f2m2',
    explanation: 'Lazy short-circuit: 1 fails filter; 2 passes filter+map; findFirst stops.',
  },
  {
    id: 'pr02',
    code: `Stream.iterate(0,n->n+1).limit(3).peek(System.out::println).count();`,
    question: 'Does peek print 0 1 2?',
    answer: 'Yes',
    explanation: 'count traverses all limited elements; peek observes them.',
  },
  {
    id: 'pr03',
    code: `var s=List.of(1,2).stream(); s.count(); s.count();`,
    question: 'What happens?',
    answer: 'IllegalStateException on second terminal',
    explanation: 'Streams are single-use.',
  },
  {
    id: 'pr04',
    code: `List.of(3,1,2).stream().sorted().peek(System.out::print).findFirst();`,
    question: 'Typical print order?',
    answer: '123 then Optional[1]',
    explanation: 'sorted buffers; then findFirst takes smallest.',
  },
  {
    id: 'pr05',
    code: `IntStream.range(0,5).filter(x->x%2==0).map(x->x*x).boxed().toList();`,
    question: 'Result list?',
    answer: '[0, 4, 16]',
    explanation: '0,2,4 squared.',
  },
  {
    id: 'pr06',
    code: `Stream.of("a","b").peek(System.out::print).findAny();`,
    question: 'Must both letters print?',
    answer: 'Not necessarily — short-circuit may print one',
    explanation: 'findAny can stop early.',
  },
  {
    id: 'pr07',
    code: `List.<String>of().stream().allMatch(s -> false);`,
    question: 'Result?',
    answer: 'true',
    explanation: 'Vacuous truth: allMatch on empty is true.',
  },
  {
    id: 'pr08',
    code: `List.<String>of().stream().anyMatch(s -> true);`,
    question: 'Result?',
    answer: 'false',
    explanation: 'anyMatch on empty is false.',
  },
  {
    id: 'pr09',
    code: `Stream.generate(() -> 1).limit(2).toList();`,
    question: 'Result?',
    answer: '[1, 1]',
    explanation: 'generate + limit materializes two ones.',
  },
  {
    id: 'pr10',
    code: `List.of(1,2,3).stream().reduce(0, Integer::sum, Integer::sum);`,
    question: 'Why combiner present?',
    answer: 'Needed for parallel splits; sequential may ignore',
    explanation: 'Three-arg reduce supports parallel.',
  },
  {
    id: 'pr11',
    code: `List.of("x").stream().map(String::length).map(Object::toString).toList();`,
    question: 'Result?',
    answer: '["1"]',
    explanation: 'length 1 then stringified.',
  },
  {
    id: 'pr12',
    code: `Stream.of(1,2,3).skip(1).limit(1).toList();`,
    question: 'Result?',
    answer: '[2]',
    explanation: 'skip first, take one.',
  },
  {
    id: 'pr13',
    code: `Stream.of(2,1,2).distinct().sorted().toList();`,
    question: 'Result?',
    answer: '[1, 2]',
    explanation: 'distinct then sort.',
  },
  {
    id: 'pr14',
    code: `Stream.of("ab","c").flatMap(s -> s.chars().mapToObj(c -> (char)c)).toList();`,
    question: 'Result size?',
    answer: '3 — a,b,c',
    explanation: 'flatMap flattens characters.',
  },
  {
    id: 'pr15',
    code: `Optional.of("x").stream().toList();`,
    question: 'Result? (Java 9+)',
    answer: '["x"]',
    explanation: 'Optional.stream is 0/1 element.',
  },
  {
    id: 'pr16',
    code: `List.of(1,2,3).stream().takeWhile(n -> n < 3).toList();`,
    question: 'Result? (Java 9+)',
    answer: '[1, 2]',
    explanation: 'Stops before 3.',
  },
  {
    id: 'pr17',
    code: `List.of(1,2,3).stream().dropWhile(n -> n < 3).toList();`,
    question: 'Result?',
    answer: '[3]',
    explanation: 'Drops while predicate true.',
  },
  {
    id: 'pr18',
    code: `Stream.of(1,2).parallel().forEachOrdered(System.out::print);`,
    question: 'Order guarantee?',
    answer: '12 encounter order',
    explanation: 'forEachOrdered respects order; forEach may not.',
  },
  {
    id: 'pr19',
    code: `Collectors.counting() // used as downstream`,
    question: 'Return type of counting()?',
    answer: 'Collector yielding Long',
    explanation: 'Downstream counting boxes to Long.',
  },
  {
    id: 'pr20',
    code: `List.of(1,2).stream().collect(Collectors.toList()).getClass();`,
    question: 'Modifiable? vs toList()',
    answer: 'collect(toList()) typically ArrayList modifiable; stream.toList() unmodifiable (16+)',
    explanation: 'Java 16 behavioral difference interview favorite.',
  },
];

export const DEBUGS: DebugQ[] = [
  {
    id: 'db01',
    badCode: `emps.stream().collect(Collectors.toMap(Employee::name, Employee::salary));`,
    bug: 'Duplicate names → IllegalStateException.',
    fix: `toMap(Employee::name, Employee::salary, (a,b)->a)`,
    lesson: 'Always define merge policy.',
  },
  {
    id: 'db02',
    badCode: `int[] t={0}; list.parallelStream().forEach(x->t[0]+=x);`,
    bug: 'Data race / lost updates.',
    fix: `list.parallelStream().mapToInt(Integer::intValue).sum();`,
    lesson: 'No shared mutable in parallel forEach.',
  },
  {
    id: 'db03',
    badCode: `Stream<String> s=list.stream(); s.forEach(System.out::println); s.count();`,
    bug: 'Stream reused.',
    fix: 'New stream per terminal.',
    lesson: 'Single-use pipeline.',
  },
  {
    id: 'db04',
    badCode: `Files.lines(path).filter(...).toList();`,
    bug: 'Resource leak.',
    fix: 'try-with-resources around Files.lines',
    lesson: 'Close file streams.',
  },
  {
    id: 'db05',
    badCode: `Stream.iterate(0,n->n+1).collect(Collectors.toList());`,
    bug: 'Infinite stream hang/OOM.',
    fix: 'limit / takeWhile',
    lesson: 'Bound infinite sources.',
  },
  {
    id: 'db06',
    badCode: `list.stream().map(Integer::valueOf) // unchecked parse`,
    bug: 'NumberFormatException mid-pipeline.',
    fix: 'Validate earlier; flatMap Optional',
    lesson: 'Fail fast before map.',
  },
  {
    id: 'db07',
    badCode: `Comparator.comparing(A::x).reversed().thenComparing(A::y)`,
    bug: 'reversed may apply broader than intended.',
    fix: 'Nest reversed on the specific thenComparing comparator',
    lesson: 'Parenthesize comparator fragments.',
  },
  {
    id: 'db08',
    badCode: `repo.findAll().stream().map(e->e.getItems().size())`,
    bug: 'Lazy OneToMany N+1.',
    fix: 'Fetch join / DTO query',
    lesson: 'Streams do not fix ORM plans.',
  },
  {
    id: 'db09',
    badCode: `users.parallelStream().map(this::httpCall).toList()`,
    bug: 'Blocking IO on commonPool.',
    fix: 'Sequential or virtual-thread executor for IO',
    lesson: 'parallelStream ≠ general concurrency.',
  },
  {
    id: 'db10',
    badCode: `stream.peek(this::charge).collect(toList())`,
    bug: 'Business side effects in peek.',
    fix: 'Explicit service call outside debugging peek',
    lesson: 'peek is for debugging.',
  },
];

export const TOP100_RANKED: RankedProblem[] = (() => {
  const order = {must: 0, advanced: 1, expert: 2, staff: 3} as const;
  return ALL_PROBLEMS.map((p) => {
    let rank: RankedProblem['rank'] = 'advanced';
    if (p.difficulty === 'Beginner' || p.difficulty === 'Intermediate') rank = 'must';
    if (p.difficulty === 'Advanced') rank = 'advanced';
    if (p.difficulty === 'Expert') rank = 'expert';
    if (p.difficulty === 'Staff' || p.difficulty === 'Architect') rank = 'staff';
    if (p.category === 'parallel' || p.category === 'production') rank = 'staff';
    if (p.category === 'employee' || p.category === 'grouping' || p.category === 'fintech') {
      if (rank === 'advanced') rank = 'must';
    }
    return {id: p.id, title: p.title, category: p.category, rank};
  })
    .sort((a, b) => order[a.rank] - order[b.rank] || a.title.localeCompare(b.title))
    .slice(0, 100);
})();
