import type {TocItem} from './types';

/** Consumer + consumer-group curriculum — maps the master prompt into navigable boards. */
export const KAFKA_CONSUMER_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview & version'},
  {id: 'fundamentals', label: '01. Fundamentals'},
  {id: 'lifecycle', label: '02. poll() lifecycle'},
  {id: 'architecture', label: '03. Internals & threads'},
  {id: 'subscribe', label: '04. subscribe vs assign'},
  {id: 'poll', label: '05. poll() & poll loop'},
  {id: 'deser', label: '06. Deserialization & records'},
  {id: 'offsets', label: '07. Position · commit · reset'},
  {id: 'commits', label: '08. Auto · sync · async commit'},
  {id: 'semantics', label: '09. Delivery · EOS · read_committed'},
  {id: 'group', label: '10. Consumer group & coordinator'},
  {id: 'membership', label: '11. Join · heartbeat · generation'},
  {id: 'timeouts', label: '12. session vs max.poll.interval'},
  {id: 'rebalance', label: '13. Rebalancing · eager · coop'},
  {id: 'assignors', label: '14. Partition assignors'},
  {id: 'static', label: '15. Static membership & listeners'},
  {id: 'fetch', label: '16. Fetch protocol & configs'},
  {id: 'backpressure', label: '17. Pause · resume · workers'},
  {id: 'seek', label: '18. Seek · replay · ListOffsets'},
  {id: 'lag', label: '19. Lag & performance'},
  {id: 'scaling', label: '20. Scaling · ordering · poison'},
  {id: 'errors', label: '21. Retry · DLQ · error tree'},
  {id: 'failures', label: '22. Failure matrix'},
  {id: 'config', label: '23. Config & interactions'},
  {id: 'security', label: '24. Security'},
  {id: 'obs', label: '25. Observability & alerts'},
  {id: 'ops', label: '26. K8s · DR · multi-cluster'},
  {id: 'source', label: '27. Source & protocol'},
  {id: 'finance', label: '28. Payments consumer'},
  {id: 'antipatterns', label: '29. Anti-patterns'},
  {id: 'staff-gaps', label: '30. Staff zero-gap (protocol deep)'},
  {id: 'interview', label: '31. Interview & cheatsheets'},
];
