/** Scenario-based interview bank. */

export type IQ = {
  id: string;
  level: 'Beginner' | 'Intermediate' | 'Senior' | 'Principal';
  question: string;
  thought: string;
  strong: string;
  wrong: string;
  followUp: string;
};

export const INTERVIEW_BANK: IQ[] = [
  // Beginner
  {
    id: 'b1',
    level: 'Beginner',
    question: 'Why not new Thread() for every payment request?',
    thought: 'Cost, lifecycle, backpressure',
    strong: 'Thread creation is expensive; no shared queue/rejection; hard to shut down cleanly. Use a pool.',
    wrong: 'Threads are free / JVM optimizes everything',
    followUp: 'What does an unbounded queue do under flood?',
  },
  {
    id: 'b2',
    level: 'Beginner',
    question: 'Difference between Executor and ExecutorService?',
    thought: 'API surface',
    strong: 'Executor only execute(); ExecutorService adds submit, invokeAll, shutdown lifecycle.',
    wrong: 'They are the same interface',
    followUp: 'What does shutdown() reject?',
  },
  {
    id: 'b3',
    level: 'Beginner',
    question: 'Runnable vs Callable?',
    thought: 'Return + exceptions',
    strong: 'Callable returns value and can throw checked; submit gives Future.',
    wrong: 'Callable is just faster Runnable',
    followUp: 'Where does Callable’s exception surface?',
  },
  {
    id: 'b4',
    level: 'Beginner',
    question: 'What does Future.get() do?',
    thought: 'Blocking join',
    strong: 'Blocks until done; wraps task failures in ExecutionException; supports timeout overload.',
    wrong: 'Non-blocking poll of result',
    followUp: 'What if get() times out — is the task cancelled?',
  },
  {
    id: 'b5',
    level: 'Beginner',
    question: 'When is a worker thread created in TPE?',
    thought: 'core path',
    strong: 'If workers < core on submit, create; else queue; only if queue refuses and < max, create more.',
    wrong: 'Always create up to max first',
    followUp: 'Show with core=5 max=10 queue=100',
  },
  {
    id: 'b6',
    level: 'Beginner',
    question: 'Does a worker die after finishing a task?',
    thought: 'Reuse',
    strong: 'No — it loops and takes the next task from the queue until keepAlive/shutdown.',
    wrong: 'Yes, every task gets a new thread',
    followUp: 'When are excess workers removed?',
  },
  {
    id: 'b7',
    level: 'Beginner',
    question: 'shutdown vs shutdownNow?',
    thought: 'Drain vs interrupt',
    strong: 'shutdown stops new tasks and drains; shutdownNow interrupts and returns queued runnables.',
    wrong: 'shutdownNow kills threads instantly always',
    followUp: 'Why might a task ignore shutdownNow?',
  },
  {
    id: 'b8',
    level: 'Beginner',
    question: 'What is RejectedExecutionException?',
    thought: 'Saturation',
    strong: 'Handler AbortPolicy when pool at max and queue full (or shutdown).',
    wrong: 'A checked business error from Callable',
    followUp: 'Name three other rejection policies',
  },
  {
    id: 'b9',
    level: 'Beginner',
    question: 'Why name threads payment-worker-N?',
    thought: 'Ops',
    strong: 'Thread dumps and logs become searchable during incidents.',
    wrong: 'Only for aesthetics',
    followUp: 'Show a ThreadFactory snippet',
  },
  {
    id: 'b10',
    level: 'Beginner',
    question: 'Fixed thread pool queue type?',
    thought: 'Factory pitfall',
    strong: 'Unbounded LinkedBlockingQueue — maxPoolSize unused; risk of memory growth.',
    wrong: 'SynchronousQueue',
    followUp: 'How do you fix it for an API?',
  },
  // Intermediate
  {
    id: 'i1',
    level: 'Intermediate',
    question: 'core=5 max=10 queue=100 — where does task 6 go?',
    thought: 'Apply algorithm',
    strong: 'Into the queue; still 5 workers.',
    wrong: 'Creates 6th thread immediately',
    followUp: 'When is the 6th thread created?',
  },
  {
    id: 'i2',
    level: 'Intermediate',
    question: 'Why might maximumPoolSize never increase?',
    thought: 'Queue always accepts',
    strong: 'Unbounded (or never-full) queue — offer succeeds; max path never taken.',
    wrong: 'JVM bug',
    followUp: 'How to force max growth?',
  },
  {
    id: 'i3',
    level: 'Intermediate',
    question: 'execute(failingRunnable) vs submit(failingRunnable)?',
    thought: 'Exception visibility',
    strong: 'execute → uncaught handler; submit → stored until Future.get().',
    wrong: 'Identical behavior',
    followUp: 'How do you log submit failures centrally?',
  },
  {
    id: 'i4',
    level: 'Intermediate',
    question: 'When is CallerRunsPolicy a bad idea on a web server?',
    thought: 'Caller = request thread',
    strong: 'Saturates Tomcat/Jetty threads running business work → latency cascade.',
    wrong: 'It is always safest',
    followUp: 'When is it appropriate?',
  },
  {
    id: 'i5',
    level: 'Intermediate',
    question: 'CPU-bound pool sizing intuition?',
    thought: 'Cores',
    strong: '≈ cores (or cores+1); extra threads mostly contend for CPU.',
    wrong: 'Always 200 for throughput',
    followUp: 'How does I/O-bound sizing differ?',
  },
  {
    id: 'i6',
    level: 'Intermediate',
    question: '200 threads, DB pool 20 — what happens?',
    thought: 'Bottleneck',
    strong: 'At most 20 concurrent DB ops; others block borrowing → latency with possibly low CPU.',
    wrong: '200 parallel queries',
    followUp: 'What metric do you watch on HikariCP?',
  },
  {
    id: 'i7',
    level: 'Intermediate',
    question: 'scheduleAtFixedRate vs fixedDelay for reconcile?',
    thought: 'Overlap',
    strong: 'fixedDelay waits after completion — better when duration varies; fixedRate aims at cadence.',
    wrong: 'They are identical',
    followUp: 'What if reconcile > interval?',
  },
  {
    id: 'i8',
    level: 'Intermediate',
    question: 'Why pass an executor to supplyAsync?',
    thought: 'Avoid commonPool',
    strong: 'Default uses FJP commonPool; blocking I/O there hurts the whole JVM.',
    wrong: 'Only for naming',
    followUp: 'What uses commonPool besides CF?',
  },
  {
    id: 'i9',
    level: 'Intermediate',
    question: 'ThreadLocal tenant id leak symptom?',
    thought: 'Reuse',
    strong: 'Next request on same worker sees previous tenant → wrong data/authz.',
    wrong: 'ThreadLocal is cleared automatically always',
    followUp: 'Mitigations?',
  },
  {
    id: 'i10',
    level: 'Intermediate',
    question: 'SynchronousQueue role in cached pools?',
    thought: 'Handoff',
    strong: 'No storage — if no idle worker, create thread (up to max) or reject.',
    wrong: 'Unbounded buffer',
    followUp: 'Contrast with ArrayBlockingQueue(100)',
  },
  // Senior
  {
    id: 's1',
    level: 'Senior',
    question: 'Design a payment authorize executor for 20 cores, DB=50, gateway p50=200ms, 500 RPS/instance.',
    thought: 'Concurrent≈RPS×lat; cap by pools',
    strong: '≈100 concurrent; core~32 max~64; bounded queue hundreds; Abort→503; timeouts; names; bulkhead.',
    wrong: 'core=500 to be safe',
    followUp: 'How do you validate in prod?',
  },
  {
    id: 's2',
    level: 'Senior',
    question: '100 app threads, DB=20, executor=200, latency spikes — investigate?',
    thought: 'Metrics + dumps',
    strong: 'Check Hikari waits, executor queue/active, thread dumps WAITING on pool, dependency SLOs; shrink executor.',
    wrong: 'Add more executor threads',
    followUp: 'What dashboard panels do you want?',
  },
  {
    id: 's3',
    level: 'Senior',
    question: 'Show a pool deadlock with nested tasks.',
    thought: 'submit+get',
    strong: 'Workers blocked on inner.get while inners sit in queue on same small pool.',
    wrong: 'Java cannot deadlock with executors',
    followUp: 'Fixes?',
  },
  {
    id: 's4',
    level: 'Senior',
    question: '@Transactional method submits DB work to executor — bug?',
    thought: 'ThreadLocal txn',
    strong: 'Txn/persistence context not on worker; need separate txn on bean called by worker or stay sync.',
    wrong: 'Spring propagates automatically',
    followUp: 'SecurityContext propagation?',
  },
  {
    id: 's5',
    level: 'Senior',
    question: 'Kafka consumer hands messages to a large executor — risks?',
    thought: 'Offsets/order',
    strong: 'Commit races, rebalance mid-flight, broken partition order, unbounded handoff queues.',
    wrong: 'Always increases throughput safely',
    followUp: 'Safer patterns?',
  },
  {
    id: 's6',
    level: 'Senior',
    question: 'Graceful deploy while payment in-flight?',
    thought: 'Drain + idempotency',
    strong: 'Fail readiness, shutdown pool, await, interrupt leftover; idempotent charge keys prevent double-pay on retry.',
    wrong: 'Kill -9 is fine with Kubernetes',
    followUp: 'Where do you store idempotency keys?',
  },
  {
    id: 's7',
    level: 'Senior',
    question: 'When are virtual threads the wrong tool?',
    thought: 'CPU / pinning / pools',
    strong: 'CPU-bound; heavy synchronized pinning; still limited by JDBC pool — VT do not invent connections.',
    wrong: 'Always faster than platform threads',
    followUp: 'How to adopt incrementally?',
  },
  {
    id: 's8',
    level: 'Senior',
    question: 'DiscardOldestPolicy on payment queue?',
    thought: 'Fairness/money',
    strong: 'Drops earliest customer intents — unacceptable; prefer Abort/503 or controlled shed.',
    wrong: 'Great for fairness',
    followUp: 'Any domain where DiscardOldest is OK?',
  },
  {
    id: 's9',
    level: 'Senior',
    question: 'How do you monitor executor health?',
    thought: 'Leading indicators',
    strong: 'active/pool/queue/rejected/latency histograms; alert on queue growth + reject rate.',
    wrong: 'Only heap usage',
    followUp: 'Relate to dependency metrics',
  },
  {
    id: 's10',
    level: 'Senior',
    question: '@Async self-invocation — what happens?',
    thought: 'Proxy',
    strong: 'this.async() skips Spring proxy → runs sync on caller thread.',
    wrong: 'Still async via bytecode',
    followUp: 'How to fix?',
  },
  // Principal
  {
    id: 'p1',
    level: 'Principal',
    question: 'Design bulkheads for payment, reporting, notifications sharing one JVM.',
    thought: 'Blast radius',
    strong: 'Separate ThreadPoolTaskExecutors + queues + metrics; report flood cannot exhaust payment workers; independent rejection.',
    wrong: 'One giant shared executor with priority queue only',
    followUp: 'How do you prevent DB pool cross-talk?',
  },
  {
    id: 'p2',
    level: 'Principal',
    question: '10k TPS payment platform — executor strategy across instances?',
    thought: 'Horizontal + local limits',
    strong: 'Per-instance bounded pools sized to local DB/HTTP; gateway load-balances; global concurrency via pools not one JVM mega-pool; idempotent consumers.',
    wrong: 'Single JVM cached pool for 10k TPS',
    followUp: 'Where does backpressure start?',
  },
  {
    id: 'p3',
    level: 'Principal',
    question: 'Relate circuit breaker, executor rejection, and client retries.',
    thought: 'Feedback loops',
    strong: 'Rejection/503 + CB open reduce fan-out; clients must backoff/jitter or amplify; budget retries.',
    wrong: 'Retry immediately forever on RejectedExecution',
    followUp: 'How to test the feedback loop?',
  },
  {
    id: 'p4',
    level: 'Principal',
    question: 'Migrating a blocking payment stack to virtual threads — plan?',
    thought: 'Measure constraints',
    strong: 'Pilot I/O paths; keep DB pool size; watch pinning; retain bulkheads; compare latency/CPU/error budgets before wide rollout.',
    wrong: 'Flip all executors to VT overnight without metrics',
    followUp: 'What breaks with ThreadLocal-heavy libs?',
  },
  {
    id: 'p5',
    level: 'Principal',
    question: 'How would you prove an unbounded queue caused an outage?',
    thought: 'Evidence',
    strong: 'Heap histogram of FutureTask/Linked*, queue size metrics absent, GC logs, factory code review, recreate with load test.',
    wrong: 'Blame GC without tying to queue growth',
    followUp: 'Prevent recurrence in platform standards?',
  },
  {
    id: 'p6',
    level: 'Principal',
    question: 'Duplicate payments after timeout — root cause analysis?',
    thought: 'At-least-once',
    strong: 'Client retry + server timeout after charge success without idempotent key; executor reuse irrelevant. Fix key + state machine.',
    wrong: 'ThreadPoolExecutor randomly doubles tasks',
    followUp: 'Design the idempotency record lifecycle',
  },
  {
    id: 'p7',
    level: 'Principal',
    question: 'ForkJoin vs TPE for payment authorize?',
    thought: 'Workload shape',
    strong: 'Authorize is I/O — TPE/VT; FJP for CPU parse/risk scoring batch, not blocking gateway calls.',
    wrong: 'Always FJP because modern',
    followUp: 'parallelStream in request path?',
  },
  {
    id: 'p8',
    level: 'Principal',
    question: 'Multi-tenant SaaS: noisy neighbor via executors?',
    thought: 'Isolation',
    strong: 'Per-tenant or per-class bulkheads/semaphores; fair queues; reject/throttle heavy tenants; separate report pools.',
    wrong: 'Trust one FIFO queue',
    followUp: 'Fairness vs latency SLOs',
  },
  {
    id: 'p9',
    level: 'Principal',
    question: 'What production standards would you mandate for all services?',
    thought: 'Platform engineering',
    strong: 'No Executors factories on ingress; bounded queues; named threads; micrometer; shutdown hooks; no Discard for money; CF must pass executor.',
    wrong: 'Let teams choose freely without review',
    followUp: 'How enforced in CI/arch unit?',
  },
  {
    id: 'p10',
    level: 'Principal',
    question: 'Explain ExecutorService in 2 minutes for a staff interview.',
    thought: 'Derive from model',
    strong:
      'Managed pool; core→queue→max→reject; size to downstream; bound queue; observe Futures; graceful shutdown; idempotent payments. (See TWO_MIN.)',
    wrong: 'Recite interface method list only',
    followUp: 'Draw the decision tree on the whiteboard',
  },
  {
    id: 'p11',
    level: 'Principal',
    question: 'Your API is 20k RPS and DB supports only 100 concurrent connections. Design the executor strategy.',
    thought: 'Global vs per-instance; smallest pool wins',
    strong:
      'Horizontalize: per instance concurrency ≪ 100 total across fleet. Cap local TPE by share of DB pool; bound queues; Abort→503; timeouts; never 20k threads in one JVM.',
    wrong: 'One JVM with 20k cached threads',
    followUp: 'Where does admission control start?',
  },
  {
    id: 'p12',
    level: 'Principal',
    question: 'Queue grew to 100k tasks but CPU is only 20%. What is happening?',
    thought: 'Waiting not computing',
    strong:
      'Workers blocked on I/O/locks/pool borrows; tasks pile in queue. Dump threads; fix downstream or reduce concurrency — do not add CPU cores first.',
    wrong: 'Need a bigger CPU machine immediately',
    followUp: 'Which metrics confirm it in 2 minutes?',
  },
  {
    id: 'p13',
    level: 'Principal',
    question: 'Increasing thread count reduced throughput. Why?',
    thought: 'Oversubscription',
    strong:
      'Past the bottleneck, extra threads add context switches, cache thrash, and longer waits on the same DB/HTTP pools — throughput falls.',
    wrong: 'Impossible — threads only help',
    followUp: 'How do you find the sweet spot?',
  },
  {
    id: 'p14',
    level: 'Principal',
    question: 'Kafka consumer lag rises continuously after introducing an executor. Diagnose it.',
    thought: 'Handoff / commit / pause',
    strong:
      'Check unbounded handoff queue, commit-before-complete, rebalance mid-flight, worker slower than poll rate. Pause consumer on depth; sync processing or bounded handoff with ack-after-success.',
    wrong: 'Just raise concurrency to 100',
    followUp: 'How do you preserve per-key order?',
  },
  {
    id: 'p15',
    level: 'Principal',
    question: 'How do you safely shut down an executor during a blue/green payment deploy?',
    thought: 'Traffic → drain → interrupt → idempotency',
    strong:
      'Fail readiness, stop enqueues, shutdown + awaitTermination budget, shutdownNow leftovers, verify in-flight via idempotency store; clients retry safely.',
    wrong: 'SIGKILL after 1s is fine',
    followUp: 'What must every charge task guarantee?',
  },
];
