import type {InterviewQ} from './types';

export const INTERVIEW: InterviewQ[] = [
  // —— Mid (20) ——
  {
    id: 'm1',
    level: 'mid',
    question: 'Why is ReentrantLock called reentrant?',
    testing: 'Hold count / same-thread reacquire',
    thought: 'Nested calls on same lock',
    strong: 'Owner may re-acquire; hold count increments; unlock until zero; other threads blocked while count>0.',
    wrong: 'It means multiple threads can enter.',
    followUp: 'What if unlock is called by a non-owner?',
  },
  {
    id: 'm2',
    level: 'mid',
    question: 'When prefer ReentrantLock over synchronized?',
    testing: 'Feature-driven choice',
    thought: 'tryLock / interrupt / fair / Condition',
    strong: 'Need timed tryLock, interruptible acquire, fairness, multiple Conditions, or lock introspection.',
    wrong: 'Always — ReentrantLock is newer/faster.',
    followUp: 'When is synchronized better?',
  },
  {
    id: 'm3',
    level: 'mid',
    question: 'Correct unlock pattern?',
    testing: 'finally discipline',
    thought: 'Exceptions',
    strong: 'lock(); try { … } finally { unlock(); }',
    wrong: 'unlock at end of method without finally',
    followUp: 'What happens if unlock is skipped?',
  },
  {
    id: 'm4',
    level: 'mid',
    question: 'Difference lock() vs lockInterruptibly()?',
    testing: 'Cancellation while waiting',
    thought: 'Interrupt during wait',
    strong: 'lockInterruptibly can throw InterruptedException while waiting; lock() does not abort wait on interrupt.',
    wrong: 'They are identical.',
    followUp: 'Where does this matter in web apps?',
  },
  {
    id: 'm5',
    level: 'mid',
    question: 'What does tryLock() return on contention?',
    testing: 'Non-blocking acquire',
    thought: 'false path',
    strong: 'Immediately false if not acquired (untimed); timed version waits up to timeout.',
    wrong: 'Blocks forever then returns false.',
    followUp: 'Danger of ignoring false?',
  },
  {
    id: 'm6',
    level: 'mid',
    question: 'Fair vs non-fair ReentrantLock default?',
    testing: 'Defaults & trade-offs',
    thought: 'Throughput',
    strong: 'Default non-fair; barging allowed; usually higher throughput; fair reduces starvation.',
    wrong: 'Default is fair for safety.',
    followUp: 'Does fair guarantee absolute FIFO?',
  },
  {
    id: 'm7',
    level: 'mid',
    question: 'Can multiple readers hold ReentrantReadWriteLock?',
    testing: 'Shared mode',
    thought: 'Readers concurrent',
    strong: 'Yes, shared read lock; writer exclusive against readers and writers.',
    wrong: 'Only one reader like mutex.',
    followUp: 'Reader + writer simultaneously?',
  },
  {
    id: 'm8',
    level: 'mid',
    question: 'Why while around condition.await()?',
    testing: 'Spurious wakeups / predicate',
    thought: 'Re-check invariant',
    strong: 'Wake ≠ condition true; loop until predicate holds.',
    wrong: 'if is enough because signal is reliable.',
    followUp: 'What does await do to the lock?',
  },
  {
    id: 'm9',
    level: 'mid',
    question: 'signal vs signalAll?',
    testing: 'Condition API',
    thought: 'One vs all',
    strong: 'signal wakes one waiter; signalAll wakes all — use when any waiter may proceed or predicates differ.',
    wrong: 'Always signalAll for speed.',
    followUp: 'Why multiple Condition objects?',
  },
  {
    id: 'm10',
    level: 'mid',
    question: 'Does ReentrantLock work across two Spring Boot instances?',
    testing: 'JVM boundary',
    thought: 'Process-local',
    strong: 'No — each JVM has its own lock. Use DB/distributed coordination.',
    wrong: 'Yes if the bean is singleton.',
    followUp: 'What would you use instead for account debit?',
  },
  {
    id: 'm11',
    level: 'mid',
    question: 'Why prefer AtomicInteger for a counter?',
    testing: 'Lock vs atomic',
    thought: 'Single variable',
    strong: 'CAS without blocking; lower overhead for simple increments; LongAdder under high contention.',
    wrong: 'Atomics replace all locks always.',
    followUp: 'When atomics are insufficient?',
  },
  {
    id: 'm12',
    level: 'mid',
    question: 'What is a Condition used for?',
    testing: 'Wait/notify upgrade',
    thought: 'Wait sets',
    strong: 'Await a predicate under Lock; multiple named wait sets vs single monitor wait set.',
    wrong: 'Replace the Lock entirely.',
    followUp: 'Payment queue notEmpty/notFull design?',
  },
  {
    id: 'm13',
    level: 'mid',
    question: 'Write → read downgrade — allowed?',
    testing: 'RRWL semantics',
    thought: 'Acquire read while holding write',
    strong: 'Yes — acquire readLock while holding write, then unlock write.',
    wrong: 'Same as upgrade — both forbidden.',
    followUp: 'Why upgrade differs?',
  },
  {
    id: 'm14',
    level: 'mid',
    question: 'Four conditions for deadlock?',
    testing: 'Classic theory applied',
    thought: 'ME, hold-wait, no preempt, cycle',
    strong: 'Mutual exclusion, hold and wait, no preemption, circular wait.',
    wrong: 'Only circular wait matters.',
    followUp: 'How to break circular wait for transfers?',
  },
  {
    id: 'm15',
    level: 'mid',
    question: 'What does LockSupport.park do?',
    testing: 'AQS parking',
    thought: 'Block until unpark/interrupt',
    strong: 'Parks current thread; permit-based; used inside AQS — prefer higher-level locks in app code.',
    wrong: 'Same as Thread.sleep.',
    followUp: 'Role in unlock path?',
  },
  {
    id: 'm16',
    level: 'mid',
    question: 'Coarse vs fine-grained locking?',
    testing: 'Granularity trade-off',
    thought: 'Concurrency vs complexity',
    strong: 'Coarse simpler/less concurrent; fine more concurrent, more deadlock risk.',
    wrong: 'Fine always better.',
    followUp: 'What is lock striping?',
  },
  {
    id: 'm17',
    level: 'mid',
    question: 'StampedLock reentrant?',
    testing: 'Stamped pitfalls',
    thought: 'No',
    strong: 'Not reentrant — nested acquire can deadlock.',
    wrong: 'Yes like ReentrantLock.',
    followUp: 'When still choose StampedLock?',
  },
  {
    id: 'm18',
    level: 'mid',
    question: 'What is AQS state for ReentrantLock?',
    testing: 'Internals basics',
    thought: 'Hold count',
    strong: '0 free; positive = exclusive hold count; owner thread tracked.',
    wrong: 'Boolean only.',
    followUp: 'How does CAS help?',
  },
  {
    id: 'm19',
    level: 'mid',
    question: 'Holding lock during payment gateway call — risk?',
    testing: 'I/O under lock',
    thought: 'Starvation',
    strong: 'Long hold blocks others; pool threads stuck; cascading latency.',
    wrong: 'Safer because consistent.',
    followUp: 'Better structure?',
  },
  {
    id: 'm20',
    level: 'mid',
    question: 'How to detect deadlock in Java?',
    testing: 'Tooling',
    thought: 'jstack / MXBean',
    strong: 'jstack, JConsole, JFR, ThreadMXBean.findDeadlockedThreads(); look for circular locked/waiting.',
    wrong: 'Only restart the JVM.',
    followUp: 'What does a deadlock look like in a dump?',
  },

  // —— Senior (30) ——
  {
    id: 's1',
    level: 'senior',
    question: 'What happens internally when lock.lock() cannot acquire?',
    testing: 'AQS queueing',
    thought: 'Enqueue + park',
    strong: 'Failed tryAcquire → add waiter node → park via LockSupport until predecessor releases and unparks; re-try acquire.',
    wrong: 'Busy-spin forever.',
    followUp: 'Fair vs non-fair tryAcquire difference?',
  },
  {
    id: 's2',
    level: 'senior',
    question: 'Why is non-fair usually preferred?',
    testing: 'Throughput reasoning',
    thought: 'Barging reduces switching',
    strong: 'Barging can hand lock to a hot thread already running; fewer context switches; fair increases fairness cost.',
    wrong: 'Non-fair is always incorrect.',
    followUp: 'When fairness matters in payments?',
  },
  {
    id: 's3',
    level: 'senior',
    question: 'Why can read-to-write upgrade deadlock?',
    testing: 'RRWL corner',
    thought: 'Hold read while waiting write',
    strong: 'Readers block writers; upgraders still hold read → no writer can proceed → cycle among upgraders.',
    wrong: 'JDK bug — never happens.',
    followUp: 'Show correct re-check pattern.',
  },
  {
    id: 's4',
    level: 'senior',
    question: 'Can RRWL starve writers?',
    testing: 'Starvation',
    thought: 'Unfair + reader flood',
    strong: 'Yes under continuous readers with unfair policy; fair mode or design changes mitigate.',
    wrong: 'Impossible — writers always preferred.',
    followUp: 'Market data example?',
  },
  {
    id: 's5',
    level: 'senior',
    question: 'Why might StampedLock outperform RRWL?',
    testing: 'Optimistic path',
    thought: 'No reader lock traffic',
    strong: 'Optimistic read avoids acquiring read lock when validate succeeds; less coherency traffic under read-heavy loads.',
    wrong: 'Always faster — replace RRWL everywhere.',
    followUp: 'Cost when writes are frequent?',
  },
  {
    id: 's6',
    level: 'senior',
    question: 'Design account transfer without deadlock.',
    testing: 'Ordering',
    thought: 'Sort ids',
    strong: 'Lock accounts in deterministic order (min id then max); or single DB txn with ordered row locks.',
    wrong: 'tryLock randomly until success without backoff strategy.',
    followUp: 'Multi-instance version?',
  },
  {
    id: 's7',
    level: 'senior',
    question: 'Java lock then DB lock vs reverse — risk?',
    testing: 'Cross-layer deadlock',
    thought: 'Inconsistent order',
    strong: 'Different code paths taking opposite orders create cycles across JVM and DB wait graphs.',
    wrong: 'Layers are independent so safe.',
    followUp: 'Preferred authority for money?',
  },
  {
    id: 's8',
    level: 'senior',
    question: 'How to debug lock contention in production?',
    testing: 'Ops skill',
    thought: 'Dump + profile',
    strong: 'jstack hot spots, async-profiler lock, JFR, hold-time metrics, identify owner stack (often I/O).',
    wrong: 'Only look at CPU graphs.',
    followUp: 'Why CPU can be low during outage?',
  },
  {
    id: 's9',
    level: 'senior',
    question: 'Lock striping for 100k accounts — trade-offs?',
    testing: 'Scalability design',
    thought: 'Modulo stripes',
    strong: 'Fewer locks than accounts; better than one global; collisions couple unrelated keys; still JVM-local.',
    wrong: 'Stripe count irrelevant.',
    followUp: 'How choose stripe count?',
  },
  {
    id: 's10',
    level: 'senior',
    question: 'Why increasing executor size fails under one hot lock?',
    testing: 'Queueing theory intuition',
    thought: 'Serial bottleneck',
    strong: 'Throughput capped by critical section; more threads add waiters and overhead.',
    wrong: 'Double pool doubles TPS.',
    followUp: 'Pool starvation with I/O under lock?',
  },
  {
    id: 's11',
    level: 'senior',
    question: 'Implement timeout for acquiring account lock.',
    testing: 'tryLock timed',
    thought: 'SLA',
    strong: 'tryLock(timeout) → on false fail request / enqueue async; never ignore false.',
    wrong: 'lock() in a loop with sleep.',
    followUp: 'Interaction with fair lock?',
  },
  {
    id: 's12',
    level: 'senior',
    question: 'Compare wait/notify vs Condition.',
    testing: 'API design',
    thought: 'Multiple wait sets',
    strong: 'Condition allows multiple wait sets per Lock; clearer signal targets; same while-loop discipline.',
    wrong: 'Condition does not release the lock.',
    followUp: 'await steps?',
  },
  {
    id: 's13',
    level: 'senior',
    question: 'Choose sync for order book vs RRWL for risk table — why?',
    testing: 'Workload fit',
    thought: 'Write vs read dominance',
    strong: 'Order book mutate-heavy → exclusive lock; risk table read-heavy → RW/snapshot.',
    wrong: 'Always RRWL for finance.',
    followUp: 'StampedLock for mid price cache?',
  },
  {
    id: 's14',
    level: 'senior',
    question: 'What breaks if another thread calls unlock()?',
    testing: 'Ownership',
    thought: 'Exception',
    strong: 'IllegalMonitorStateException — only owner unlocks.',
    wrong: 'Lock silently transfers.',
    followUp: 'How does that differ from hand-over patterns?',
  },
  {
    id: 's15',
    level: 'senior',
    question: 'Optimistic read validate fails often — meaning?',
    testing: 'StampedLock ops',
    thought: 'Write hot',
    strong: 'Writers invalidate stamps frequently; optimistic path thrashing — fall back or use different structure.',
    wrong: 'Bug in validate.',
    followUp: 'When abandon StampedLock?',
  },
  {
    id: 's16',
    level: 'senior',
    question: 'Singleton Spring bean lock field — what is protected?',
    testing: 'Scope clarity',
    thought: 'One JVM',
    strong: 'Threads inside that process sharing the bean instance — not other pods, not other classloaders.',
    wrong: 'Entire cluster because Spring is singleton.',
    followUp: '@Async interaction?',
  },
  {
    id: 's17',
    level: 'senior',
    question: 'How does fairness affect context switching?',
    testing: 'Perf nuance',
    thought: 'More handoffs',
    strong: 'Fair tends to wake next waiter strictly → more switches; unfair may let barging thread continue.',
    wrong: 'Fair always fewer switches.',
    followUp: 'Measure how?',
  },
  {
    id: 's18',
    level: 'senior',
    question: 'Compound check balance + book txn — why not only AtomicLong?',
    testing: 'Invariant span',
    thought: 'Multi-step',
    strong: 'Multiple fields/collections must change together; need critical section or DB txn.',
    wrong: 'Two atomics are enough.',
    followUp: 'CAS loop alternative?',
  },
  {
    id: 's19',
    level: 'senior',
    question: 'Reader starvation — can it happen?',
    testing: 'Symmetric starvation',
    thought: 'Writer preference designs',
    strong: 'Possible under policies that prefer writers or long write holds; fair mode balances differently.',
    wrong: 'Only writers starve ever.',
    followUp: 'FinTech example?',
  },
  {
    id: 's20',
    level: 'senior',
    question: 'Minimize lock scope around Kafka publish?',
    testing: 'I/O pattern',
    thought: 'Snapshot then send',
    strong: 'Build message under lock; unlock; send; optionally confirm under short lock — never block network under lock.',
    wrong: 'Publish inside lock for ordering (prefer partition key).',
    followUp: 'Ordering without JVM lock?',
  },
  {
    id: 's21',
    level: 'senior',
    question: 'Explain AQS in 60 seconds.',
    testing: 'Teaching clarity',
    thought: 'State+queue+park',
    strong: 'Template for synchronizers: atomic state, CLH-style queue, park/unpark; subclasses define tryAcquire/tryRelease.',
    wrong: 'AQS is only for ReentrantLock.',
    followUp: 'Name for Semaphore?',
  },
  {
    id: 's22',
    level: 'senior',
    question: 'Unsafe upgrade alternative patterns?',
    testing: 'Design alternatives',
    thought: 'Release/reacquire; stamped convert',
    strong: 'Drop read then write+recheck; or use StampedLock tryConvertToWriteLock carefully; or exclusive from start.',
    wrong: 'synchronized upgrade intrinsic.',
    followUp: 'Stamped convert pitfalls?',
  },
  {
    id: 's23',
    level: 'senior',
    question: 'Detecting hold-time regressions in CI?',
    testing: 'Engineering practice',
    thought: 'Load + metrics',
    strong: 'Micrometer timers around lock; load tests; fail on p99 hold/wait thresholds.',
    wrong: 'Unit tests with two threads suffice.',
    followUp: 'Which SLIs?',
  },
  {
    id: 's24',
    level: 'senior',
    question: 'Why BlockingQueue often beats hand-rolled Condition?',
    testing: 'Prefer library',
    thought: 'Less bugs',
    strong: 'Battle-tested await/signal, fairness options, fewer foot-guns — roll Condition only for custom multi-predicate needs.',
    wrong: 'Always write your own for control.',
    followUp: 'When custom Condition wins?',
  },
  {
    id: 's25',
    level: 'senior',
    question: 'Virtual threads + ReentrantLock — concern?',
    testing: 'Modern Java',
    thought: 'Pinning',
    strong: 'Pinning carrier when parking on synchronized/native; ReentrantLock parks without pinning in modern JDKs — still avoid long holds.',
    wrong: 'Virtual threads make locks unnecessary.',
    followUp: 'synchronized pinning?',
  },
  {
    id: 's26',
    level: 'senior',
    question: 'Hot account key — mitigation strategies?',
    testing: 'Hot partition',
    thought: 'Shard / async',
    strong: 'Shard balances, queue per account single-writer, tryLock reject, move invariant to DB with careful isolation.',
    wrong: 'Bigger lock.',
    followUp: 'Idempotency role?',
  },
  {
    id: 's27',
    level: 'senior',
    question: 'getQueueLength / hasQueuedThreads — use?',
    testing: 'Monitoring API',
    thought: 'Diagnostics',
    strong: 'Expose contention gauges; not for hard control logic (racy).',
    wrong: 'Spin until queue empty then lock.',
    followUp: 'isHeldByCurrentThread use case?',
  },
  {
    id: 's28',
    level: 'senior',
    question: 'Payment timeout interrupts worker waiting on lock — design?',
    testing: 'Interruptibility',
    thought: 'lockInterruptibly',
    strong: 'Use lockInterruptibly; restore interrupt; map to 503/timeout; ensure unlock only if acquired.',
    wrong: 'Ignore interrupt and keep waiting.',
    followUp: 'Interaction with tryLock timeout?',
  },
  {
    id: 's29',
    level: 'senior',
    question: 'Immutable snapshot publish vs RRWL?',
    testing: 'Lock-free publish',
    thought: 'volatile ref',
    strong: 'Writer builds new immutable structure, publishes reference; readers see consistent snapshot without read locks.',
    wrong: 'Always worse than locks.',
    followUp: 'GC cost trade-off?',
  },
  {
    id: 's30',
    level: 'senior',
    question: 'Explain production incident: latency high, CPU low, DB fine.',
    testing: 'Incident narrative',
    thought: 'Blocked threads',
    strong: 'Likely lock or pool wait — dump shows AQS WAITING; fix hold time / hot lock / I/O under lock.',
    wrong: 'Need more CPU cores first.',
    followUp: 'First three commands?',
  },

  // —— Staff / Principal (30) ——
  {
    id: 'p1',
    level: 'staff',
    question: 'Progression from race to distributed coordination — teach it.',
    testing: 'Mental model leadership',
    thought: 'Layered tools',
    strong: 'Race→mutex→sync→RL→Condition→RRWL→Stamped→multi-JVM needs DB/lease/Kafka — choose by scope and workload.',
    wrong: 'List APIs without scope.',
    followUp: 'Where do juniors usually jump wrong?',
  },
  {
    id: 'p2',
    level: 'staff',
    question: 'When is a Java lock the wrong layer for money movement?',
    testing: 'Architecture authority',
    thought: 'Durability + multi-writer',
    strong: 'Whenever multiple processes can mutate; durability/audit required — DB constraints + idempotency own the invariant.',
    wrong: 'Never use Java locks in finance.',
    followUp: 'Valid in-process uses?',
  },
  {
    id: 'p3',
    level: 'staff',
    question: 'Design matching engine concurrency for one instrument.',
    testing: 'Trading systems',
    thought: 'Single writer',
    strong: 'Prefer single-threaded actor / disruptor per instrument; if locks, per-instrument exclusive; avoid global lock.',
    wrong: 'RRWL on shared global book.',
    followUp: 'Cross-instrument risk checks?',
  },
  {
    id: 'p4',
    level: 'staff',
    question: 'Fairness SLOs vs throughput SLOs — decide lock mode.',
    testing: 'Product trade-off',
    thought: 'Measure starvation',
    strong: 'Default non-fair; if max wait SLO breached by barging, fair or external queueing with admission control.',
    wrong: 'Always fair in banks.',
    followUp: 'How prove starvation?',
  },
  {
    id: 'p5',
    level: 'staff',
    question: 'Cross-region active-active account updates — locks?',
    testing: 'Distributed reality',
    thought: 'Not JVM',
    strong: 'Conflict resolution via consensus/DB/partition ownership; Java locks irrelevant across regions.',
    wrong: 'Redis lock without fencing is enough forever.',
    followUp: 'Fencing tokens why?',
  },
  {
    id: 'p6',
    level: 'staff',
    question: 'Define lock hold-time budget for a payment API.',
    testing: 'SRE + eng',
    thought: 'SLA math',
    strong: 'Hold ≪ request SLO; never include downstream RTT; alert on hold p99; reject when tryLock exceeds budget.',
    wrong: 'Hold as long as txn needs.',
    followUp: 'Budget vs DB txn time?',
  },
  {
    id: 'p7',
    level: 'staff',
    question: 'Migrate global synchronized service to striped locks — risks?',
    testing: 'Migration safety',
    thought: 'Invariants spanning stripes',
    strong: 'Cross-account ops need multi-stripe order; dual-running; correctness tests under concurrency.',
    wrong: 'Drop-in performance win only.',
    followUp: 'How test?',
  },
  {
    id: 'p8',
    level: 'staff',
    question: 'StampedLock in a codebase with deep call stacks — policy?',
    testing: 'Governance',
    thought: 'Ban nested',
    strong: 'Restrict to leaf read methods; forbid re-entrant service calls under stamp; prefer RRWL if nesting common.',
    wrong: 'Educate only, no guardrails.',
    followUp: 'Static analysis ideas?',
  },
  {
    id: 'p9',
    level: 'staff',
    question: 'Kafka partition ordering vs ReentrantLock for account events?',
    testing: 'Platform choice',
    thought: 'Single writer log',
    strong: 'Partition by accountId gives ordered single-writer processing across consumers — often better than JVM locks for pipeline.',
    wrong: 'Still need ReentrantLock in each consumer always.',
    followUp: 'Exactly-once interplay?',
  },
  {
    id: 'p10',
    level: 'staff',
    question: 'Incident review: writer starvation in market data — lead response.',
    testing: 'Incident leadership',
    thought: 'Mitigate then fix',
    strong: 'Immediate: restart unfair → fair or pause readers; lasting: snapshot publish; dashboards for writer wait.',
    wrong: 'Only add more reader threads.',
    followUp: 'Postmortem metrics?',
  },
  {
    id: 'p11',
    level: 'staff',
    question: 'How do biased locking / JVM opts change synchronized vs RL advice?',
    testing: 'Depth without pedantry',
    thought: 'Measure',
    strong: 'Historically synchronized optimized for uncontended; modern advice: prefer simplest correct API; measure contended paths.',
    wrong: 'Memorize obsolete HotSpot myths as law.',
    followUp: 'Virtual threads era impact?',
  },
  {
    id: 'p12',
    level: 'staff',
    question: 'Library API: expose Lock or encapsulate?',
    testing: 'API design',
    thought: 'Encapsulation',
    strong: 'Encapsulate; expose high-level ops; leaking Lock invites misuse/deadlocks across modules.',
    wrong: 'Public final ReentrantLock for flexibility.',
    followUp: 'Testing seams?',
  },
  {
    id: 'p13',
    level: 'staff',
    question: 'Prove a critical section is small enough.',
    testing: 'Evidence culture',
    thought: 'Instrumentation',
    strong: 'Histograms of hold time under prod-like load; flamegraphs; assert no I/O frames under lock in reviews.',
    wrong: 'Code looks short.',
    followUp: 'CI gate design?',
  },
  {
    id: 'p14',
    level: 'staff',
    question: 'Multi-condition payment queue vs Disruptor — choose?',
    testing: 'Architecture options',
    thought: 'Throughput needs',
    strong: 'Disruptor/single-writer for ultra-low latency; Condition/BlockingQueue for simpler ops with modest rates.',
    wrong: 'Condition always fine at exchange scale.',
    followUp: 'Failure modes of each?',
  },
  {
    id: 'p15',
    level: 'staff',
    question: 'False sharing near AtomicLong vs padded — relate to locks?',
    testing: 'Perf adjacency',
    thought: 'Contended lines',
    strong: 'High CAS contention may push toward striping or LongAdder; locks have different costs — profile before changing.',
    wrong: 'Replace all atomics with locks to fix false sharing.',
    followUp: 'LongAdder mechanics briefly?',
  },
  {
    id: 'p16',
    level: 'staff',
    question: 'Organizational standard: lock ordering document.',
    testing: 'Process',
    thought: 'Prevent deadlock classes',
    strong: 'Global partial order of lock ranks; review checklist; deadlock tests; forbid new ranks without RFC.',
    wrong: 'Rely on senior memory.',
    followUp: 'Enforce in code?',
  },
  {
    id: 'p17',
    level: 'staff',
    question: 'When optimistic concurrency (@Version) beats JVM locks?',
    testing: 'Data layer',
    thought: 'Multi-instance + low conflict',
    strong: 'Shared DB rows, rare conflicts — retry on version fail; no cross-pod Java lock.',
    wrong: 'Optimistic always replaces locks in-process too.',
    followUp: 'High conflict accounts?',
  },
  {
    id: 'p18',
    level: 'staff',
    question: 'Read-mostly FX cache: RRWL vs volatile snapshot vs StampedLock?',
    testing: 'Nuanced choice',
    thought: 'Consistency needs',
    strong: 'Snapshot publish often simplest; Stamped if in-place mutate + measured; RRWL if need blocking readers during write.',
    wrong: 'One true answer forever.',
    followUp: 'Tear reads acceptable?',
  },
  {
    id: 'p19',
    level: 'staff',
    question: 'Security: can lock timing leak?',
    testing: 'Side channels awareness',
    thought: 'Rare but real',
    strong: 'Contended auth paths may leak via timing; prefer constant-ish handling and rate limits — usually secondary to correctness.',
    wrong: 'Locks encrypt data.',
    followUp: 'More relevant FinTech leaks?',
  },
  {
    id: 'p20',
    level: 'staff',
    question: 'Teach juniors the one progression diagram — what must stick?',
    testing: 'Mentorship',
    thought: 'Scope expansion',
    strong: 'Tool escalates with need; multi-JVM breaks Java locks — that sentence saves outages.',
    wrong: 'Memorize method names only.',
    followUp: 'Quiz question you use?',
  },
  {
    id: 'p21',
    level: 'staff',
    question: 'Capacity plan: lock wait in p99 budget.',
    testing: 'Quantitative',
    thought: 'Little’s law intuition',
    strong: 'Estimate arrival on hot key; service time under lock; queue wait; shed load before saturation.',
    wrong: 'Scale pods only.',
    followUp: 'Hot key detection?',
  },
  {
    id: 'p22',
    level: 'staff',
    question: 'Combine idempotency keys with in-process locks.',
    testing: 'End-to-end correctness',
    thought: 'Defense in depth',
    strong: 'Idempotency for retries/multi-pod; locks for local structure — neither replaces the other.',
    wrong: 'Idempotency means no synchronization needed.',
    followUp: 'Where store idempotency?',
  },
  {
    id: 'p23',
    level: 'staff',
    question: 'Deadlock as a SEV — communication template?',
    testing: 'Leadership',
    thought: 'Clear narrative',
    strong: 'Impact, blast radius, dump evidence, temporary mitigate (restart/kill), permanent order fix, prevention tests.',
    wrong: 'Blame a library.',
    followUp: 'How prevent recurrence?',
  },
  {
    id: 'p24',
    level: 'staff',
    question: 'Should platform provide a shared LockService bean?',
    testing: 'Platform instincts',
    thought: 'Usually no',
    strong: 'Global lock service invites coupling and cluster myths; provide patterns/libraries for striping + docs, not one lock.',
    wrong: 'Yes — one Redis-backed lock for everything.',
    followUp: 'When a platform lock API is justified?',
  },
  {
    id: 'p25',
    level: 'staff',
    question: 'Evaluate replacing synchronized with RL in a legacy module.',
    testing: 'Change control',
    thought: 'Need features?',
    strong: 'Only if tryLock/Condition/etc. required; else risk unlock bugs for little gain.',
    wrong: 'Modernize all synchronized.',
    followUp: 'Migration checklist?',
  },
  {
    id: 'p26',
    level: 'staff',
    question: 'Thread dump shows Condition wait + empty queue — causes?',
    testing: 'Diagnosis depth',
    thought: 'Lost signal / predicate',
    strong: 'Signal without waiters earlier; bug using if; wrong Condition; producer crashed before signal.',
    wrong: 'JVM spurious only.',
    followUp: 'How harden?',
  },
  {
    id: 'p27',
    level: 'staff',
    question: 'Align Java locking training with DB isolation training.',
    testing: 'Holistic concurrency',
    thought: 'Same mental models',
    strong: 'Race, isolation, deadlock graphs — teach unified; show where each layer applies.',
    wrong: 'Separate silos forever.',
    followUp: 'Example curriculum module?',
  },
  {
    id: 'p28',
    level: 'staff',
    question: 'Risk of lock elision mental models in interviews vs prod?',
    testing: 'Honesty',
    thought: 'Do not overfit',
    strong: 'Discuss visibility/exclusion first; mention JVM opts as secondary; prod decisions from measurement.',
    wrong: 'Lead with biased locking trivia.',
    followUp: 'What must every senior say first?',
  },
  {
    id: 'p29',
    level: 'staff',
    question: 'Build a FinTech concurrency checklist for PRs.',
    testing: 'Standards',
    thought: 'Practical gates',
    strong: 'finally unlock; no I/O under lock; order documented; multi-instance considered; tests for races; metrics.',
    wrong: 'Style-only checklist.',
    followUp: 'Automated checks?',
  },
  {
    id: 'p30',
    level: 'staff',
    question: '2-minute explanation of RL and RRWL for an interviewer.',
    testing: 'Communication',
    thought: 'Production voice',
    strong: 'See Final Pitch section — problem, when escalate from synchronized, AQS briefly, RW for read-heavy, multi-JVM caveat.',
    wrong: 'API laundry list.',
    followUp: 'One failure story?',
  },

  // —— Architecture (20) ——
  {
    id: 'a1',
    level: 'architecture',
    question: 'Pick coordination for ledger across 50 services.',
    testing: 'System design',
    thought: 'Source of truth',
    strong: 'Ledger DB + idempotent commands + partition; not ReentrantLock.',
    wrong: 'Distributed lock around every post.',
    followUp: 'Role of JVM locks inside a service?',
  },
  {
    id: 'a2',
    level: 'architecture',
    question: 'Single-writer account pipeline on Kafka — still need RW locks?',
    testing: 'Redundancy',
    thought: 'Ordering provides exclusion',
    strong: 'Per-key single consumer removes multi-thread races for that key; locks only for in-process shared structures.',
    wrong: 'Always both.',
    followUp: 'Rebalance hazards?',
  },
  {
    id: 'a3',
    level: 'architecture',
    question: 'CQRS read models — locking strategy?',
    testing: 'Read path design',
    thought: 'Snapshots',
    strong: 'Publish immutable projections; readers lock-free; writers serialize via queue/DB.',
    wrong: 'RRWL on shared mutable read model globally.',
    followUp: 'Stale read SLO?',
  },
  {
    id: 'a4',
    level: 'architecture',
    question: 'Where do distributed locks fit vs DB transactions?',
    testing: 'Tool boundaries',
    thought: 'Short critical non-DB',
    strong: 'DB txn for data invariants; distributed lock for leader election / non-transactional resources — with fencing.',
    wrong: 'Redis lock replaces DB txn.',
    followUp: 'Fencing example?',
  },
  {
    id: 'a5',
    level: 'architecture',
    question: 'Multi-tenant SaaS: lock per tenant vs per account?',
    testing: 'Blast radius',
    thought: 'Granularity',
    strong: 'Per account (or finer) to avoid tenant-wide stalls; watch cross-account deadlocks.',
    wrong: 'One lock per JVM.',
    followUp: 'Noisy neighbor?',
  },
  {
    id: 'a6',
    level: 'architecture',
    question: 'Blue/green deploy with in-memory locks?',
    testing: 'Lifecycle',
    thought: 'State loss',
    strong: 'In-memory lock state dies with instance; do not rely for cross-request durability; drain carefully.',
    wrong: 'Sticky sessions fix locking.',
    followUp: 'Session stickiness myth?',
  },
  {
    id: 'a7',
    level: 'architecture',
    question: 'Event sourcing concurrency control?',
    testing: 'Alt model',
    thought: 'OCC on stream',
    strong: 'Expected version on append; JVM locks only for in-memory projections rebuild.',
    wrong: 'Lock world before append.',
    followUp: 'Idempotent handlers?',
  },
  {
    id: 'a8',
    level: 'architecture',
    question: 'Global risk limit across pods — design?',
    testing: 'Shared counter hard problem',
    thought: 'Centralize or approximate',
    strong: 'Central risk service / DB / Redis with careful semantics; local locks insufficient; consider reserved quotas.',
    wrong: 'ReentrantReadWriteLock on each pod.',
    followUp: 'Over-reservation pattern?',
  },
  {
    id: 'a9',
    level: 'architecture',
    question: 'Latency SLO 50ms — max acceptable lock wait?',
    testing: 'Budgeting',
    thought: 'Fraction of SLO',
    strong: 'Budget explicitly (e.g. few ms); tryLock; shed; do not let unbounded lock wait eat SLO.',
    wrong: 'No budget — correctness first always blocks.',
    followUp: 'User-visible degrade modes?',
  },
  {
    id: 'a10',
    level: 'architecture',
    question: 'Shared library offering AccountLocks.stripe(id) — API shape?',
    testing: 'Platform API',
    thought: 'Safe defaults',
    strong: 'Acquire by ordered multi-id API; AutoCloseable; metrics hooks; no raw Lock escape.',
    wrong: 'Return ReentrantLock publicly.',
    followUp: 'Multi-account acquire?',
  },
  {
    id: 'a11',
    level: 'architecture',
    question: 'Read-heavy reference data in 200 pods.',
    testing: 'Scale reads',
    thought: 'Replicate snapshots',
    strong: 'Push immutable config to each pod; atomic ref swap; avoid cross-pod read locks.',
    wrong: 'Remote RRWL service.',
    followUp: 'Update propagation?',
  },
  {
    id: 'a12',
    level: 'architecture',
    question: 'Avoid deadlock classes in a microservices estate.',
    testing: 'Org architecture',
    thought: 'One lock authority',
    strong: 'Ban multi-service lock chains; sagas/outbox; single data owner per entity.',
    wrong: 'Distributed lock around every cross-call.',
    followUp: 'Saga vs 2PC?',
  },
  {
    id: 'a13',
    level: 'architecture',
    question: 'Observability standard for locks.',
    testing: 'Prod readiness',
    thought: 'Metrics+dumps',
    strong: 'Hold/wait histograms, timeout rates, contention alerts, runbook for jstack/JFR.',
    wrong: 'Logs only on unlock.',
    followUp: 'Alert thresholds?',
  },
  {
    id: 'a14',
    level: 'architecture',
    question: 'Batch settlement job: coarse lock OK?',
    testing: 'Workload context',
    thought: 'Often yes',
    strong: 'Single-threaded batch may use coarse locking or none; do not copy into online path.',
    wrong: 'Same locking as online API.',
    followUp: 'Overlap with online writers?',
  },
  {
    id: 'a15',
    level: 'architecture',
    question: 'Hedge fund colocation — lock choice pressure?',
    testing: 'Ultra-low latency',
    thought: 'Prefer wait-free paths',
    strong: 'Single-writer designs, disruptors, minimize locks; Stamped/atomics carefully; measure nanos.',
    wrong: 'Fair ReentrantLock everywhere.',
    followUp: 'GC interaction?',
  },
  {
    id: 'a16',
    level: 'architecture',
    question: 'Multi-account atomic transfer across DBs?',
    testing: 'Distributed txn',
    thought: 'Outbox/saga',
    strong: 'Not Java locks; orchestrate with saga + idempotency; or single DB boundary.',
    wrong: 'Take distributed locks on both DBs then hope.',
    followUp: 'Failure midway?',
  },
  {
    id: 'a17',
    level: 'architecture',
    question: 'Feature flag to switch fair RRWL in prod?',
    testing: 'Operability',
    thought: 'Runtime safety',
    strong: 'Possible but changing fairness under load is subtle; prefer restart with config; test first.',
    wrong: 'Flip freely mid-flight.',
    followUp: 'What to monitor after flip?',
  },
  {
    id: 'a18',
    level: 'architecture',
    question: 'Where ConcurrentHashMap replaces RRWL around a Map?',
    testing: 'Structure choice',
    thought: 'CHM internals',
    strong: 'Per-bin concurrency for map ops; still need external locking for compound multi-key invariants.',
    wrong: 'CHM makes all compound ops safe.',
    followUp: 'compute atomicity?',
  },
  {
    id: 'a19',
    level: 'architecture',
    question: 'Compliance audit: prove mutual exclusion for a control.',
    testing: 'Evidence',
    thought: 'Design + tests',
    strong: 'Document authority (DB unique constraint / serializable txn); concurrency tests; not just "we used ReentrantLock".',
    wrong: 'Show lock field in code review only.',
    followUp: 'Regulator-friendly artifact?',
  },
  {
    id: 'a20',
    level: 'architecture',
    question: 'North-star decision tree for your org?',
    testing: 'Synthesis',
    thought: 'Progression',
    strong: 'Simple mutex→sync; need control→RL; read-heavy→RRWL/snapshot; optimistic measured→Stamped; multi-process→DB/partition/lease.',
    wrong: 'Always StampedLock for modernity.',
    followUp: 'Where does this tree live?',
  },
];

export function interviewByLevel(level: InterviewQ['level']) {
  return INTERVIEW.filter((q) => q.level === level);
}
