import type {AntiPattern, Incident} from './types';

export const ANTI_PATTERNS: AntiPattern[] = [
  {
    id: 'ap1',
    title: 'Forgetting finally / unlock',
    why: 'Exception path skips unlock',
    impact: 'Permanent block → pool drain → outage',
    detect: 'jstack one owner forever; stuck waiters',
    better: 'lock → try → finally unlock',
  },
  {
    id: 'ap2',
    title: 'Locking too much code',
    why: 'Fear of races → giant critical sections',
    impact: 'Artificial serialization, latency',
    detect: 'Lock hold time metrics high',
    better: 'Minimize scope; immutable snapshots',
  },
  {
    id: 'ap3',
    title: 'Holding lock during HTTP calls',
    why: 'Convenience — do everything inside lock',
    impact: 'Pool starvation, cascading timeouts',
    detect: 'Owner in socketRead; many waiters',
    better: 'Prepare under lock; I/O outside',
  },
  {
    id: 'ap4',
    title: 'Holding lock during unnecessary DB calls',
    why: 'Same as HTTP — "keep it consistent"',
    impact: 'Java waiters + DB connection hold',
    detect: 'Lock + DB time correlated',
    better: 'Short lock; DB txn as source of truth',
  },
  {
    id: 'ap5',
    title: 'Lock ordering inconsistency',
    why: 'Ad-hoc lock acquisition',
    impact: 'Deadlock',
    detect: 'ThreadMXBean deadlocks; circular dump',
    better: 'Global order (e.g. sorted ids)',
  },
  {
    id: 'ap6',
    title: 'One global lock',
    why: 'Simplest mental model',
    impact: 'Throughput ceiling',
    detect: 'All traffic waits one monitor',
    better: 'Per-key / striping / partition',
  },
  {
    id: 'ap7',
    title: 'Ignoring contention',
    why: 'Works in QA with low QPS',
    impact: 'Prod p99 collapse',
    detect: 'JFR lock events; profiler',
    better: 'Load test; redesign hot keys',
  },
  {
    id: 'ap8',
    title: 'Fair locks without measurement',
    why: 'Fair sounds safer',
    impact: 'Throughput drop, more switching',
    detect: 'A/B fair vs unfair',
    better: 'Default non-fair; fair if starvation proven',
  },
  {
    id: 'ap9',
    title: 'ReadWriteLock when writes are frequent',
    why: 'ReadWrite sounds advanced',
    impact: 'Worse than ReentrantLock',
    detect: 'Write wait dominates; low reader overlap',
    better: 'ReentrantLock / synchronized',
  },
  {
    id: 'ap10',
    title: 'Read → write upgrade',
    why: 'Looks like a natural pattern',
    impact: 'Deadlock under concurrent readers',
    detect: 'Readers waiting for write, holding read',
    better: 'Release read; acquire write; re-check',
  },
  {
    id: 'ap11',
    title: 'Ignoring interruption',
    why: 'catch (InterruptedException) empty',
    impact: 'Cancel/shutdown broken',
    detect: 'Hung shutdown; ignored interrupts',
    better: 'lockInterruptibly + restore interrupt',
  },
  {
    id: 'ap12',
    title: 'Ignoring tryLock for SLA paths',
    why: 'Always block for correctness',
    impact: 'Latency SLO breach',
    detect: 'Queue wait ≫ SLA',
    better: 'Timed tryLock + backpressure/reject',
  },
  {
    id: 'ap13',
    title: 'StampedLock without need',
    why: 'Optimistic sounds faster',
    impact: 'Complexity, reentrancy bugs',
    detect: 'Deadlocks on nested stamped; high retries',
    better: 'RRWL/RL until profiler says otherwise',
  },
  {
    id: 'ap14',
    title: 'Locking immutable data',
    why: 'Habit',
    impact: 'Needless contention',
    detect: 'Locks around final/unmodifiable',
    better: 'Publish immutable snapshots',
  },
  {
    id: 'ap15',
    title: 'Locking local variables / wrong object',
    why: 'synchronized(new Object()) or lock on temp',
    impact: 'No shared exclusion — races remain',
    detect: 'Code review; race still reproduces',
    better: 'Lock the shared guard intentionally',
  },
  {
    id: 'ap16',
    title: 'Java locks for distributed coordination',
    why: 'Works on one box',
    impact: 'Cross-pod races / double spend',
    detect: 'Duplicates across instances',
    better: 'DB / lease+fencing / partition ownership',
  },
  {
    id: 'ap17',
    title: 'Mixing DB and Java locks carelessly',
    why: 'Belt and suspenders',
    impact: 'Cross-layer deadlock',
    detect: 'DB + jstack cycle',
    better: 'One authority; consistent order',
  },
  {
    id: 'ap18',
    title: 'Nested locks without ordering policy',
    why: 'Organic growth of helpers',
    impact: 'Intermittent deadlock',
    detect: 'findDeadlockedThreads',
    better: 'Document hierarchy; lock helper',
  },
  {
    id: 'ap19',
    title: 'Locks instead of better structures',
    why: 'Default to mutex',
    impact: 'Miss ConcurrentHashMap / queues / atomics',
    detect: 'Coarse lock around map ops',
    better: 'CHM, BlockingQueue, LongAdder',
  },
  {
    id: 'ap20',
    title: 'Growing thread pool to fix contention',
    why: 'More threads = more work myth',
    impact: 'Worse queues, more context switches',
    detect: 'Pool↑ latency↑ same lock',
    better: 'Reduce hold time; shard; async',
  },
];

export const INCIDENTS: Incident[] = [
  {
    id: 'i1',
    title: 'Incident 1 — Low CPU, huge latency',
    signals: 'CPU=20% · Threads=500 · Latency=8s · Lock contention very high',
    question: 'What is probably happening?',
    answer:
      'Threads are blocked/parked on locks (or I/O), not burning CPU. One or few hot locks serialize work; wait queues explode; p99 latency follows queueing delay.',
    fix: 'Find lock owner via jstack/JFR; shrink critical section; remove I/O under lock; shard keys; consider tryLock+reject.',
  },
  {
    id: 'i2',
    title: 'Incident 2 — Payment API slow, DB fine',
    signals: 'API latency↑ · DB latency normal · CPU normal · thread count↑',
    question: 'Where do you look?',
    answer:
      'Application-level lock contention or pool exhaustion waiting on locks — not the database. Thread dumps show WAITING on ReentrantLock/AQS; pool size saturates.',
    fix: 'Profile locks; break global locks; async non-critical paths; SLA tryLock.',
  },
  {
    id: 'i3',
    title: 'Incident 3 — Writer waiting forever',
    signals: 'One writer waiting · thousands of continuous readers',
    question: 'What failure mode?',
    answer:
      'Writer starvation under unfair ReadWriteLock (or continuous optimistic success with rare write never scheduled fairly). Readers keep entering; writer never exclusive.',
    fix: 'Fair RRWL, writer preference design, or snapshot publish so writers do not need long exclusive sections.',
  },
  {
    id: 'i4',
    title: 'Incident 4 — Cross-layer deadlock',
    signals: 'Two services hang · one Java lock · one DB lock',
    question: 'How can this happen?',
    answer:
      'Service A: Java lock → waits DB row. Service B: holds DB row → waits Java lock (or reverse order across paths). Circular wait across layers.',
    fix: 'Unify lock authority; document global order; never take Java lock while holding DB lock inconsistently.',
  },
  {
    id: 'i5',
    title: 'Incident 5 — 20 instances, one account',
    signals: '20 pods each with ReentrantLock · two requests update same account on different instances',
    question: 'Does ReentrantLock protect the account?',
    answer:
      'No. Each JVM has its own lock object. Concurrent updates across pods race unless DB constraints/row locks/idempotency/partitioning coordinate.',
    fix: 'DB transaction + row lock or optimistic versioning; idempotent keys; single-writer partition.',
  },
];
