import type {TocItem} from './types';

export const RL_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview & progression'},
  {id: 'race', label: '01. Race — why locking exists'},
  {id: 'mental-model', label: '02. Locking mental model'},
  {id: 'reentrancy', label: '03. What reentrant means'},
  {id: 'sync-vs-rl', label: '04. synchronized vs ReentrantLock'},
  {id: 'aqs', label: '05. AQS internals'},
  {id: 'fair', label: '06. Fair vs non-fair'},
  {id: 'trylock', label: '07. tryLock'},
  {id: 'interrupt', label: '08. lockInterruptibly'},
  {id: 'unlock', label: '09. Unlock pattern'},
  {id: 'condition', label: '10. Condition'},
  {id: 'await', label: '11. await / signal internals'},
  {id: 'spurious', label: '12. Spurious wakeups'},
  {id: 'rw', label: '13. ReentrantReadWriteLock'},
  {id: 'rw-rules', label: '14–15. Read/Write rules matrix'},
  {id: 'rw-reentrancy', label: '16. RW reentrancy'},
  {id: 'upgrade', label: '17. Read→write upgrade'},
  {id: 'downgrade', label: '18. Write→read downgrade'},
  {id: 'starvation', label: '19–20. Fairness & writer starvation'},
  {id: 'compare', label: '21. Lock comparison'},
  {id: 'stamped', label: '22. StampedLock'},
  {id: 'scenarios', label: '23. Scenario choices'},
  {id: 'atomics', label: '24. Lock vs atomics'},
  {id: 'db', label: '25. Java vs DB vs distributed'},
  {id: 'transfer', label: '26. Transfer & deadlock order'},
  {id: 'trading', label: '27. Trading-system map'},
  {id: 'deadlock', label: '28. Deadlock detection'},
  {id: 'contention', label: '29–31. Contention, granularity, striping'},
  {id: 'pool', label: '32–34. Pools, I/O, starvation'},
  {id: 'spring', label: '35–36. Transactions & Spring'},
  {id: 'antipatterns', label: '37. Anti-patterns (20)'},
  {id: 'incidents', label: '38. Production incidents'},
  {id: 'interview', label: '39. Interview bank'},
  {id: 'decision', label: '41. Decision tree'},
  {id: 'onepager', label: '42. One-page mental model'},
  {id: 'revision', label: '43. 30-minute revision'},
  {id: 'pitch', label: '44. 2-minute pitch'},
];
