export type CoverageRow = {
  category: string;
  expected: string;
  covered: 'complete' | 'partial' | 'missing';
  deepInternals: boolean;
  processorIdentified: boolean;
  proxyIdentified: boolean;
  lifecycleIdentified: boolean;
  interviewQs: boolean;
  versionChecked: boolean;
  notes: string;
};

export const COVERAGE_AUDIT: CoverageRow[] = [
  {
    category: 'Core',
    expected: '@Component, @Autowired, @Value, @Profile, @Conditional, @Order, @AliasFor',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Deep cards + inventory-core; SCAN→REGISTER→INJECT pipeline documented.',
  },
  {
    category: 'Beans',
    expected: '@Bean, @Configuration, @Import, @Primary, @Qualifier, @DependsOn',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'ConfigurationClassPostProcessor, CGLIB @Configuration proxyBeanMethods covered.',
  },
  {
    category: 'Context',
    expected: '@ComponentScan, @PropertySource, @ImportResource, ApplicationContext lifecycle',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Startup pipeline + context refresh phases in parts-startup.',
  },
  {
    category: 'AOP',
    expected: '@Aspect, @Around, @Pointcut, @EnableAspectJAutoProxy',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Advisor ordering, self-invocation trap, proxy matrix.',
  },
  {
    category: 'TX',
    expected: '@Transactional, @EnableTransactionManagement, propagation, rollbackFor',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'TransactionInterceptor, REQUIRES_NEW proxy requirement, afterCommit events.',
  },
  {
    category: 'Cache',
    expected: '@Cacheable, @CacheEvict, @CachePut, @EnableCaching, @Caching',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Cache advisor vs TX ordering documented.',
  },
  {
    category: 'Async',
    expected: '@Async, @EnableAsync, TaskExecutor, exception handler',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'AsyncAnnotationBeanPostProcessor; self-invocation trap.',
  },
  {
    category: 'Scheduling',
    expected: '@Scheduled, @EnableScheduling, cron/fixedDelay',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'ScheduledAnnotationBeanPostProcessor; no proxy unless @Transactional on same bean.',
  },
  {
    category: 'Events',
    expected: '@EventListener, @TransactionalEventListener, ApplicationEvent',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'AFTER_COMMIT phase and async listener proxy covered.',
  },
  {
    category: 'MVC',
    expected: '@RestController, @GetMapping, @RequestBody, @ControllerAdvice, @ExceptionHandler',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'DispatcherServlet pipeline, HandlerMapping, validation on @RequestBody.',
  },
  {
    category: 'WebFlux',
    expected: '@RestController (reactive), RouterFunction, WebClient',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'parts-gaps-web-test; reactive vs blocking trap documented.',
  },
  {
    category: 'Validation',
    expected: '@Valid, @Validated, Bean Validation constraints',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Method vs class-level @Validated; jakarta.validation namespace.',
  },
  {
    category: 'Boot',
    expected: '@SpringBootApplication, SpringApplication.run, profiles, properties',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Boot 3 jakarta, condition report, exclude patterns.',
  },
  {
    category: 'Auto-config',
    expected: '@EnableAutoConfiguration, @ConditionalOn*, AutoConfiguration.imports',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'DeferredImportSelector ordering; spring.factories → imports migration.',
  },
  {
    category: 'Actuator',
    expected: '@Endpoint, @ReadOperation, health, metrics, /refresh',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Actuator endpoints + RefreshScope interaction in gaps-data-sec.',
  },
  {
    category: 'Security',
    expected: '@EnableWebSecurity, SecurityFilterChain, @PreAuthorize, @EnableMethodSecurity',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'WebSecurityConfigurerAdapter removal; filter chain vs method security.',
  },
  {
    category: 'Data Commons',
    expected: '@EnableJdbcRepositories, auditing, Pageable, @Query (commons)',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Repository abstraction, auditing annotations in inventory.',
  },
  {
    category: 'JPA',
    expected: '@Entity, @Repository, @Query, @Modifying, @Version, @Transactional (data)',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'javax.persistence → jakarta.persistence; Open Session In View trap.',
  },
  {
    category: 'Mongo',
    expected: '@Document, MongoRepository, @Indexed',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Inventory rows; interview Qs on repository proxy vs entity.',
  },
  {
    category: 'Redis',
    expected: '@Cacheable (Redis), RedisTemplate, @RedisHash',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Cache + Redis data annotations; serialization traps.',
  },
  {
    category: 'JDBC',
    expected: '@JdbcTemplate usage, @Sql (test), DataSource auto-config',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Less annotation-heavy; DataSource conditions covered.',
  },
  {
    category: 'ES',
    expected: '@Document (Elasticsearch), ElasticsearchRepository',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: false,
    interviewQs: true,
    versionChecked: true,
    notes: 'Inventory mention; not deep card — niche in many interviews.',
  },
  {
    category: 'Data REST',
    expected: '@RepositoryRestResource, HAL exporters',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: false,
    interviewQs: true,
    versionChecked: false,
    notes: 'Overview in inventory; HAL hypermedia less common in modern APIs.',
  },
  {
    category: 'Kafka',
    expected: '@EnableKafka, @KafkaListener, @SendTo, error handlers',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'KLABPP pipeline, manual ack, DLQ patterns.',
  },
  {
    category: 'Integration',
    expected: '@EnableIntegration, @ServiceActivator, @Gateway, channels',
    covered: 'partial',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: false,
    notes: 'Ecosystem card for @ServiceActivator; not every EIP annotation.',
  },
  {
    category: 'Batch',
    expected: '@EnableBatchProcessing, @StepScope, Job/Step @Bean',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Deep in parts-ecosystem + gaps overview; chunk/restart semantics.',
  },
  {
    category: 'Cloud',
    expected: '@EnableDiscoveryClient, bootstrap, config client',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Discovery + RefreshScope; not every Spring Cloud project annotation.',
  },
  {
    category: 'Config',
    expected: '@RefreshScope, spring.config.import, Config Server client',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'RefreshScope deep card; bootstrap context changes in Boot 2.4+.',
  },
  {
    category: 'Gateway',
    expected: '@EnableGateway, RouteLocator, Predicate/Filter factories',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: false,
    interviewQs: true,
    versionChecked: false,
    notes: 'Overview only — reactive gateway routes are config-heavy, few annotations.',
  },
  {
    category: 'Feign',
    expected: '@FeignClient, @EnableFeignClients, fallback',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'JDK Feign proxy; does not join local JPA TX.',
  },
  {
    category: 'LoadBalancer',
    expected: '@LoadBalanced RestTemplate/WebClient, @LoadBalancerClient',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: false,
    interviewQs: true,
    versionChecked: true,
    notes: 'Client-side LB annotation; inventory + proxy matrix row.',
  },
  {
    category: 'Circuit Breaker',
    expected: '@CircuitBreaker, @Retry, Resilience4j annotations',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: false,
    interviewQs: true,
    versionChecked: true,
    notes: 'Resilience4j AOP overview; not full Netflix Hystrix history.',
  },
  {
    category: 'Stream',
    expected: '@EnableBinding (legacy), spring.cloud.function, @Bean Consumer/Supplier',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Complete for legacy @EnableBinding + modern functional model migration note.',
  },
  {
    category: 'Session',
    expected: '@EnableRedisHttpSession, @EnableJdbcHttpSession',
    covered: 'partial',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: false,
    notes: 'Ecosystem card for Redis session; JDBC session inventory only.',
  },
  {
    category: 'HATEOAS',
    expected: '@EnableHypermediaSupport, RepresentationModel, links',
    covered: 'partial',
    deepInternals: false,
    processorIdentified: false,
    proxyIdentified: false,
    lifecycleIdentified: false,
    interviewQs: true,
    versionChecked: false,
    notes: 'Overview only — HAL declining vs plain JSON APIs in practice.',
  },
  {
    category: 'Testing',
    expected: '@SpringBootTest, @WebMvcTest, @DataJpaTest, @MockBean/@MockitoBean',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Test slices, Testcontainers, @MockitoBean Boot 3.4+.',
  },
  {
    category: 'Test Context',
    expected: 'TestContextManager, @DirtiesContext, @DynamicPropertySource',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'TestContextManager pipeline card in parts-ecosystem.',
  },
  {
    category: 'custom',
    expected: 'Composed stereotype, custom @Conditional, @Import selectors',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: '@BusinessService @AliasFor example in parts-ecosystem.',
  },
  {
    category: 'meta',
    expected: '@AliasFor, @Inherited, composed annotations, MergedAnnotations',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'MergedAnnotations card; AnnotationUtils synthesis.',
  },
  {
    category: 'processors',
    expected: 'BeanPostProcessor, BPP ordering, ConfigurationClassPostProcessor',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: false,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'WHO_PROCESSES + PROCESSOR_MAP in proxy-matrix.',
  },
  {
    category: 'proxies',
    expected: 'JDK vs CGLIB, scoped proxy, self-invocation',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'PROXY_MATRIX, DOES_PROXY, payment trace.',
  },
  {
    category: 'lifecycle',
    expected: '@PostConstruct, @PreDestroy, SmartLifecycle, @DependsOn',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'javax→jakarta lifecycle annotations; InitDestroyAnnotationBeanPostProcessor.',
  },
  {
    category: 'version diffs',
    expected: 'Boot 2→3, javax→jakarta, removed adapters',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'VERSION_MATRIX file; version notes on inventory rows.',
  },
  {
    category: 'deprecated',
    expected: '@EnableGlobalMethodSecurity, WebSecurityConfigurerAdapter, @EnableBinding',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Migration paths documented in version-matrix and boot/security cards.',
  },
  {
    category: 'traps',
    expected: 'Self-invocation, stale RefreshScope, wrong advisor order',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'TRAP_QS, SCENARIOS, MEMORY_RULES.',
  },
  {
    category: 'debugging',
    expected: 'Condition report, DEBUG logging, actuator beans, stack traces',
    covered: 'complete',
    deepInternals: true,
    processorIdentified: true,
    proxyIdentified: true,
    lifecycleIdentified: true,
    interviewQs: true,
    versionChecked: true,
    notes: 'Per-card debug sections + scenario browser.',
  },
];

/** 45 zero-missed gate questions (Part 110 audit checklist). */
export const ZERO_MISSED_CHECKS: {q: string; answer: 'YES' | 'PARTIAL' | 'NO'; notes: string}[] = [
  {q: 'Does Core stereotype/DI coverage include processors and proxy traps?', answer: 'YES', notes: 'parts-stereotype, parts-di, parts-gaps-core'},
  {q: 'Are @Bean/@Configuration CGLIB semantics documented?', answer: 'YES', notes: 'parts-config full vs lite'},
  {q: 'Is context refresh / startup pipeline explained?', answer: 'YES', notes: 'parts-startup'},
  {q: 'Does AOP section name AnnotationAwareAspectJAutoProxyCreator?', answer: 'YES', notes: 'parts-aop-tx + proxy-matrix'},
  {q: 'Is @Transactional self-invocation trap explicit?', answer: 'YES', notes: 'MEMORY_RULES + scenarios'},
  {q: 'Are TX propagation and rollback rules covered?', answer: 'YES', notes: 'parts-aop-tx deep card'},
  {q: 'Is cache vs TX advisor ordering addressed?', answer: 'YES', notes: 'ORDERING_NOTES in proxy-matrix'},
  {q: 'Does @Async require proxy and @EnableAsync?', answer: 'YES', notes: 'parts-async-cache-events'},
  {q: 'Is @Scheduled infrastructure identified?', answer: 'YES', notes: 'inventory + async-cache part'},
  {q: 'Are @EventListener and AFTER_COMMIT phases covered?', answer: 'YES', notes: 'parts-async-cache-events'},
  {q: 'Is MVC DispatcherServlet flow documented?', answer: 'YES', notes: 'parts-web'},
  {q: 'Is WebFlux vs MVC blocking trap covered?', answer: 'YES', notes: 'parts-gaps-web-test'},
  {q: 'Is @Valid on @RequestBody requirement stated?', answer: 'YES', notes: 'parts-web validation'},
  {q: 'Is @SpringBootApplication decomposition covered?', answer: 'YES', notes: 'parts-boot'},
  {q: 'Is AutoConfiguration.imports (Boot 3) documented?', answer: 'YES', notes: 'parts-boot + version-matrix'},
  {q: 'Are @ConditionalOn* conditions explained with debug tips?', answer: 'YES', notes: 'parts-boot condition report'},
  {q: 'Are Actuator @Endpoint annotations in inventory?', answer: 'YES', notes: 'inventory-modules actuator section'},
  {q: 'Is SecurityFilterChain DSL covered (no WebSecurityConfigurerAdapter)?', answer: 'YES', notes: 'parts-kafka-data-security + version-matrix'},
  {q: 'Is @EnableMethodSecurity migration from @EnableGlobalMethodSecurity noted?', answer: 'YES', notes: 'version-matrix row'},
  {q: 'Are Spring Data repository proxies distinguished from AOP proxies?', answer: 'YES', notes: 'proxy-matrix third proxy kind'},
  {q: 'Is JPA jakarta.persistence namespace noted?', answer: 'YES', notes: 'version-matrix @Entity row'},
  {q: 'Is Mongo @Document covered at interview depth?', answer: 'YES', notes: 'inventory-modules'},
  {q: 'Is Redis cache/data annotation coverage present?', answer: 'YES', notes: 'inventory + distributed-caching cross-link'},
  {q: 'Is JDBC/DataSource auto-config condition coverage adequate?', answer: 'YES', notes: 'parts-boot DataSource conditions'},
  {q: 'Is Elasticsearch deep-dived beyond inventory?', answer: 'PARTIAL', notes: 'Inventory row only — niche'},
  {q: 'Is Spring Data REST/HAL covered beyond overview?', answer: 'PARTIAL', notes: 'Inventory mention; HAL declining'},
  {q: 'Is @KafkaListener container pipeline documented?', answer: 'YES', notes: 'parts-kafka-data-security deep'},
  {q: 'Is Spring Integration covered for every EIP annotation?', answer: 'NO', notes: 'Ecosystem overview card only — honest partial'},
  {q: 'Is @EnableBatchProcessing + @StepScope deep?', answer: 'YES', notes: 'parts-ecosystem batch card'},
  {q: 'Is Spring Cloud discovery/refresh covered?', answer: 'PARTIAL', notes: 'RefreshScope deep; not every cloud project'},
  {q: 'Is @RefreshScope stale singleton trap documented?', answer: 'YES', notes: 'scenarios + ecosystem card'},
  {q: 'Is Spring Cloud Gateway annotation-deep?', answer: 'PARTIAL', notes: 'Overview — routes are mostly config'},
  {q: 'Is @FeignClient proxy type identified (JDK Feign)?', answer: 'YES', notes: 'proxy-matrix + parts-ecosystem'},
  {q: 'Is @LoadBalanced client behavior explained?', answer: 'PARTIAL', notes: 'Inventory + ecosystem card'},
  {q: 'Is Resilience4j @CircuitBreaker deep-dived?', answer: 'PARTIAL', notes: 'Interview Qs + checklist; not full module'},
  {q: 'Does Stream coverage include legacy @EnableBinding AND modern functions?', answer: 'YES', notes: 'version-matrix + inventory legacy row'},
  {q: 'Is @EnableRedisHttpSession covered?', answer: 'PARTIAL', notes: 'Ecosystem card; JDBC session lighter'},
  {q: 'Is Spring HATEOAS annotation encyclopedia complete?', answer: 'PARTIAL', notes: 'Overview only — honest'},
  {q: 'Are test slices (@WebMvcTest, @DataJpaTest) documented?', answer: 'YES', notes: 'parts-gaps-web-test'},
  {q: 'Is TestContextManager bootstrap pipeline explained?', answer: 'YES', notes: 'parts-ecosystem card'},
  {q: 'Is custom composed stereotype with @AliasFor exemplified?', answer: 'YES', notes: 'parts-ecosystem @BusinessService'},
  {q: 'Is MergedAnnotations / meta-annotation merge documented?', answer: 'YES', notes: 'parts-ecosystem + gaps-core'},
  {q: 'Is processor map (who processes what) complete for core annotations?', answer: 'YES', notes: 'WHO_PROCESSES + PROCESSOR_MAP'},
  {q: 'Is proxy matrix complete for advised annotations?', answer: 'YES', notes: 'PROXY_MATRIX + DOES_PROXY'},
  {q: 'Are javax→jakarta and Boot 2→3 diffs in a version matrix?', answer: 'YES', notes: 'version-matrix.ts'},
];

const _summary = COVERAGE_AUDIT.reduce(
  (acc, row) => {
    acc[row.covered] += 1;
    return acc;
  },
  {complete: 0, partial: 0, missing: 0},
);

export const COVERAGE_SUMMARY = {
  ..._summary,
  verdict:
    'Enterprise interview encyclopedia for Spring/Boot production annotations — deep on Core, Boot, MVC/WebFlux, Security, Data, Kafka, Test, AOP/TX, and proxy/processor internals. Known ecosystem partials: Gateway, Circuit Breaker, HATEOAS, ES, Data REST, Integration EIP breadth, Session JDBC variant. NOT a literal catalog of every Spring Cloud annotation ever shipped.',
};

export const COVERAGE_AUDIT_COUNT = COVERAGE_AUDIT.length;
export const ZERO_MISSED_CHECKS_COUNT = ZERO_MISSED_CHECKS.length;
