import type { InventoryEntry } from './types';

export const INVENTORY_DISCLAIMER: string =
  'This inventory targets enterprise production patterns and staff-level Spring interviews (Framework 6 / Boot 3). It is deliberately curated — not a literal catalog of every annotation across Spring Cloud, Netflix-era modules, Spring Integration DSL markers, or retired integrations. Use it for interview prep and architecture review coverage, not as completeness proof against the entire Spring ecosystem.';

export const INVENTORY_CORE: InventoryEntry[] = [
  {
    id: 'alias-for',
    annotation: '@AliasFor',
    family: 'core-meta',
    module: 'spring-core',
    javaPackage: 'org.springframework.core.annotation.AliasFor',
    elementType: 'ANNOTATION_TYPE',
    what: 'Meta-annotation declaring that an attribute on one annotation mirrors another attribute on the same or a specified annotation. Powers composed stereotypes without duplicating attribute names.',
    why: 'Keeps composed annotations consistent; MergedAnnotations and AnnotationUtils resolve aliases during metadata merge.',
    when: 'Custom composed annotations; overriding attributes on @ImportAutoConfiguration or request-mapping composites.',
    processor: 'AnnotationUtils / MergedAnnotations honor @AliasFor during ConfigurationClassParser, RequestMappingHandlerMapping, and condition evaluation.',
    example: '@AliasFor(annotation = RequestMapping.class, attribute = "path")\nString[] value() default {};',
    interviewImportance: 'must',
    versionNotes: 'Stable since Spring 4.2 in spring-core. No javax/jakarta migration.',
    proxyRelevant: 'No — affects annotation attribute merge only.',
    lifecyclePhase: 'Annotation parsing at startup and on MergedAnnotations reads.',
    commonMistakes: ['Omitting @AliasFor on custom stereotype — attribute ignored', 'Aliasing wrong target attribute name'],
    interviewTraps: ['@RestController applies @ResponseBody via @AliasFor on @Controller', 'AliasFor across different annotation types'],
    relatedAnnotations: ['@Component', '@RequestMapping', '@Conditional'],
    memory: 'ALIASFOR = mirror attribute names on composed annotations.',
  },
  {
    id: 'order',
    annotation: '@Order',
    family: 'core-meta',
    module: 'spring-core',
    javaPackage: 'org.springframework.core.annotation.Order',
    elementType: 'TYPE, METHOD, ANNOTATION_TYPE',
    what: 'Declares precedence for Ordered beans — lower integer value means higher priority when Spring sorts lists of extensions.',
    why: 'Deterministic ordering for BeanPostProcessors, ApplicationListeners, @Configuration classes, and advisor chains.',
    when: 'Custom BeanPostProcessor, ApplicationListener, HandlerInterceptor, or ordered @Configuration imports.',
    processor: 'OrderComparator / AnnotationAwareOrderComparator sorts beans implementing Ordered or carrying @Order.',
    example: '@Order(Ordered.HIGHEST_PRECEDENCE)\n@Component\npublic class EarlyBpp implements BeanPostProcessor {}',
    interviewImportance: 'high',
    versionNotes: 'spring-core; Ordered interface is alternative. Not jakarta-specific.',
    proxyRelevant: 'No — sorts processors/listeners, not solely @Transactional order.',
    lifecyclePhase: 'Bean registration and ordered list assembly during context refresh.',
    commonMistakes: ['@Order on random @Service expecting TX ordering', 'Equal order values — unstable relative order'],
    interviewTraps: ['Lower int = higher priority in Spring — opposite of @Priority JSR-250'],
    relatedAnnotations: ['@Priority', '@AutoConfigureOrder'],
    memory: 'ORDER = lower int runs first in Spring.',
  },
  {
    id: 'priority',
    annotation: '@Priority',
    family: 'core-meta',
    module: 'jakarta.annotation-api',
    javaPackage: 'jakarta.annotation.Priority',
    elementType: 'TYPE, PARAMETER',
    what: 'JSR-250 priority: higher value means higher priority in Jakarta EE interceptor/alternative selection.',
    why: 'Portable EE annotation; Spring uses @Order more commonly for Spring-native ordering.',
    when: 'CDI-style multiple implementations in hybrid Jakarta/Spring deployments.',
    processor: 'Limited Spring support; CommonAnnotationBeanPostProcessor paths; not primary autowire resolver.',
    example: '@Priority(1)\n@Service\npublic class PrimaryGateway implements Gateway {}',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3: jakarta.annotation.Priority. Boot 2: javax.annotation.Priority.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Bean selection in hybrid CDI/Spring setups.',
    commonMistakes: ['Confusing @Priority (higher wins) with @Order (lower wins)', 'Expecting @Priority alone to fix @Autowired ambiguity'],
    interviewTraps: ['Spring @Order vs Jakarta @Priority opposite conventions'],
    relatedAnnotations: ['@Order', '@Primary'],
    memory: 'PRIORITY = JSR-250; higher value = higher priority.',
  },
  {
    id: 'lookup',
    annotation: '@Lookup',
    family: 'core-meta',
    module: 'spring-beans',
    javaPackage: 'org.springframework.beans.factory.annotation.Lookup',
    elementType: 'METHOD',
    what: 'Replaces annotated method body with BeanFactory.getBean(returnType) — injects prototype/request bean into singleton per call.',
    why: 'Singleton cannot hold shorter-lived scope directly without proxy or lookup.',
    when: 'Singleton service needs fresh prototype or request-scoped helper each invocation.',
    processor: 'LookupOverrideAnnotationParser registers CGLIB LookupOverrideMethodInterceptor on singleton subclass.',
    example: '@Lookup\npublic CommandProcessor processor() { return null; }',
    interviewImportance: 'high',
    versionNotes: 'Since Spring 4.3. Class and method must not be final for CGLIB.',
    proxyRelevant: 'Yes — CGLIB intercepts lookup method to call getBean().',
    lifecyclePhase: 'Singleton bean enhancement at instantiation.',
    commonMistakes: ['final lookup method or class — enhancement fails', 'Expecting null return from stub body'],
    interviewTraps: ['@Lookup vs ObjectProvider<T> modern alternative'],
    relatedAnnotations: ['@Scope', 'ObjectProvider'],
    memory: 'LOOKUP = singleton stub method becomes getBean().',
  },
  {
    id: 'description',
    annotation: '@Description',
    family: 'core-meta',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Description',
    elementType: 'TYPE, METHOD, FIELD, PARAMETER',
    what: 'Human-readable description copied into BeanDefinition metadata for tooling and documentation.',
    why: 'Ops and IDE tooling surface bean purpose without parsing source comments.',
    when: 'Large contexts, generated bean catalogs, actuator metadata.',
    processor: 'ConfigurationClassBeanDefinitionReader sets BeanDefinition.setDescription from @Description.',
    example: '@Description("OLTP primary pool")\n@Bean DataSource ds() {}',
    interviewImportance: 'low',
    versionNotes: 'spring-context only; no jakarta change.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Bean definition registration.',
    commonMistakes: ['Expecting wiring or naming effect'],
    interviewTraps: ['Rare interview — metadata only'],
    relatedAnnotations: ['@Bean', '@Component'],
    memory: 'DESCRIPTION = BeanDefinition human text.',
  },
  {
    id: 'nullable',
    annotation: '@Nullable',
    family: 'core-meta',
    module: 'spring-core',
    javaPackage: 'org.springframework.lang.Nullable',
    elementType: 'TYPE_USE, METHOD, PARAMETER, FIELD',
    what: 'Spring nullability marker for static analysis — null is allowed. Not enforced by DI at runtime.',
    why: 'Documents optional injection/API for IDE and Kotlin nullness checkers.',
    when: 'Optional dependencies, nullable return contracts in libraries.',
    processor: 'No runtime BeanPostProcessor — tooling and compile-time checkers.',
    example: '@Autowired\npublic Svc(@Nullable AuditClient audit) {}',
    interviewImportance: 'medium',
    versionNotes: 'org.springframework.lang — not javax/jakarta validation.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Static analysis only.',
    commonMistakes: ['Expecting runtime NPE guard from container', 'Mixing javax.annotation.Nullable vs spring.lang'],
    interviewTraps: ['Container does not enforce @Nullable at runtime'],
    relatedAnnotations: ['@NonNull', '@NonNullApi'],
    memory: 'NULLABLE = hint only; DI ignores at runtime.',
  },
  {
    id: 'non-null',
    annotation: '@NonNull',
    family: 'core-meta',
    module: 'spring-core',
    javaPackage: 'org.springframework.lang.NonNull',
    elementType: 'TYPE_USE, METHOD, PARAMETER, FIELD',
    what: 'Documents non-null contract for parameters, returns, fields — tooling hint, not runtime DI enforcement.',
    why: 'API clarity in Spring modules and public packages.',
    when: 'Library public methods; constructor params that must always be provided.',
    processor: 'Tooling; distinct from Bean Validation @NotNull which runs at validation phase.',
    example: 'public @NonNull String id() { return id; }',
    interviewImportance: 'medium',
    versionNotes: 'spring.lang.NonNull ≠ jakarta.validation.NotNull.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Static analysis.',
    commonMistakes: ['@NonNull vs @NotNull — different processors'],
    interviewTraps: ['@NotNull triggers validation; @NonNull is documentation'],
    relatedAnnotations: ['@Nullable', '@NotNull'],
    memory: 'NONNULL = Spring lang hint, not validation.',
  },
  {
    id: 'non-null-api',
    annotation: '@NonNullApi',
    family: 'core-meta',
    module: 'spring-core',
    javaPackage: 'org.springframework.lang.NonNullApi',
    elementType: 'PACKAGE',
    what: 'Package-level default: parameters and returns are non-null unless @Nullable. Declared in package-info.java.',
    why: 'Avoid repeating @NonNull on every method in large API packages.',
    when: 'Library package-info for strict null contracts.',
    processor: 'Compile-time / IDE only.',
    example: '@NonNullApi\npackage com.example.api;',
    interviewImportance: 'low',
    versionNotes: 'spring-core lang package annotation.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Compile time.',
    commonMistakes: ['Expecting runtime enforcement', 'Forgetting package-info.java'],
    interviewTraps: ['Package-level null defaults interview rarity'],
    relatedAnnotations: ['@NonNullFields', '@Nullable'],
    memory: 'NONNULLAPI = package default non-null API.',
  },
  {
    id: 'non-null-fields',
    annotation: '@NonNullFields',
    family: 'core-meta',
    module: 'spring-core',
    javaPackage: 'org.springframework.lang.NonNullFields',
    elementType: 'PACKAGE',
    what: 'Package-level default that fields are non-null unless marked @Nullable.',
    why: 'Field-level nullness defaults for domain packages.',
    when: 'package-info in domain modules with static analysis.',
    processor: 'Tooling only.',
    example: '@NonNullFields\npackage com.example.domain;',
    interviewImportance: 'low',
    versionNotes: 'spring-core.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Compile time.',
    commonMistakes: ['Assuming @NonNullApi covers fields — need @NonNullFields'],
    interviewTraps: ['Difference NonNullApi vs NonNullFields'],
    relatedAnnotations: ['@NonNullApi'],
    memory: 'NONNULLFIELDS = package field null defaults.',
  },
  {
    id: 'named',
    annotation: '@Named',
    family: 'core-meta',
    module: 'jakarta.inject',
    javaPackage: 'jakarta.inject.Named',
    elementType: 'TYPE, METHOD, FIELD',
    what: 'JSR-330 qualifier assigning explicit bean name for @Inject resolution. Spring treats @Named as a qualifier.',
    why: 'Portable CDI/Spring apps; alternative to @Component("name") + @Qualifier.',
    when: '@Inject-based modules, CDI migration, explicit bean name at injection point.',
    processor: 'AutowiredAnnotationBeanPostProcessor resolves @Named value as qualifier.',
    example: '@Named("auditJdbc")\n@Inject JdbcTemplate jdbc;',
    interviewImportance: 'high',
    versionNotes: 'Boot 3: jakarta.inject.Named. Boot 2: javax.inject.Named.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'populateBean dependency resolution.',
    commonMistakes: ['@Named without value — decapitalized class name', 'Mixing @Autowired and @Inject semantics'],
    interviewTraps: ['@Named vs @Qualifier — similar in Spring'],
    relatedAnnotations: ['@Qualifier', '@Inject'],
    memory: 'NAMED = JSR-330 named qualifier.',
  },
  {
    id: 'managed-resource',
    annotation: '@ManagedResource',
    family: 'jmx',
    module: 'spring-context',
    javaPackage: 'org.springframework.jmx.export.annotation.ManagedResource',
    elementType: 'TYPE',
    what: 'Marks bean as JMX managed resource with objectName for MBeanExporter.',
    why: 'Expose ops metrics and admin knobs via JMX for legacy/on-prem operations tooling.',
    when: 'Admin beans when JMX mandated; many Boot 3 apps prefer Actuator + Micrometer.',
    processor: 'AnnotationMBeanExporter / MBeanExportConfiguration registers SpringModelMBean.',
    example: '@ManagedResource(objectName="com.app:type=Orders")\n@Service class OrderService {}',
    interviewImportance: 'medium',
    versionNotes: 'spring-context JMX; secure JMX connector in production.',
    proxyRelevant: 'No — MBean wrapper, not AOP.',
    lifecyclePhase: 'Context refresh MBean registration.',
    commonMistakes: ['Sensitive ops without JMX auth', 'Duplicate objectName'],
    interviewTraps: ['Actuator vs JMX in cloud interview'],
    relatedAnnotations: ['@ManagedAttribute', '@ManagedOperation'],
    memory: 'MANAGEDRESOURCE = bean becomes JMX MBean.',
  },
  {
    id: 'managed-attribute',
    annotation: '@ManagedAttribute',
    family: 'jmx',
    module: 'spring-context',
    javaPackage: 'org.springframework.jmx.export.annotation.ManagedAttribute',
    elementType: 'METHOD, FIELD',
    what: 'Exposes property as JMX attribute (read/write) on @ManagedResource.',
    why: 'Operators read stats or tune settings via JConsole or jmxterm.',
    when: 'Queue depth, pool size, feature flag state.',
    processor: 'AnnotationMBeanExporter maps getter/setter/field to MBean attribute.',
    example: '@ManagedAttribute\npublic int getQueueDepth() { return q.size(); }',
    interviewImportance: 'medium',
    versionNotes: 'Prefer Micrometer gauges in Boot 3 cloud-native.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Runtime JMX read/write.',
    commonMistakes: ['Heavy getter polled frequently', 'Unvalidated setter'],
    interviewTraps: ['Attribute vs operation distinction'],
    relatedAnnotations: ['@ManagedResource', '@ManagedOperation'],
    memory: 'MANAGEDATTRIBUTE = JMX property.',
  },
  {
    id: 'managed-operation',
    annotation: '@ManagedOperation',
    family: 'jmx',
    module: 'spring-context',
    javaPackage: 'org.springframework.jmx.export.annotation.ManagedOperation',
    elementType: 'METHOD',
    what: 'Exposes method as invokable JMX operation for administrative actions.',
    why: 'Trigger cache clear, replay, drain outside normal REST API.',
    when: 'Manual ops tasks with JMX access control.',
    processor: 'AnnotationMBeanExporter registers invokable operation metadata.',
    example: '@ManagedOperation\npublic int replayFailed() { return outbox.replay(); }',
    interviewImportance: 'medium',
    versionNotes: 'Guard dangerous operations.',
    proxyRelevant: 'No — direct invoke via JMX.',
    lifecyclePhase: 'Runtime JMX invoke.',
    commonMistakes: ['Long blocking operation on JMX thread'],
    interviewTraps: ['Operation vs attribute'],
    relatedAnnotations: ['@ManagedResource'],
    memory: 'MANAGEDOPERATION = JMX callable method.',
  },
  {
    id: 'property-source',
    annotation: '@PropertySource',
    family: 'config',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.PropertySource',
    elementType: 'TYPE',
    what: 'Registers a PropertySource (classpath file, URL) into Environment for ${} placeholders, @Value, and @ConfigurationProperties.',
    why: 'Modular property files beyond Boot application.yaml.',
    when: 'Module-specific defaults, vendor property files, non-Boot Spring apps.',
    processor: 'PropertySourceRegistry during ConfigurationClassParser; Environment resolves placeholders.',
    example: '@PropertySource("classpath:billing.properties")\n@Configuration class BillingConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 spring-context; factory attribute for custom PropertySourceFactory.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Early refresh before property binding.',
    commonMistakes: ['Missing file failures', 'Wrong precedence vs application.properties'],
    interviewTraps: ['vs spring.config.import Boot 2.4+'],
    relatedAnnotations: ['@PropertySources', '@Value'],
    memory: 'PROPERTYSOURCE = add properties file to Environment.',
  },
  {
    id: 'property-sources',
    annotation: '@PropertySources',
    family: 'config',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.PropertySources',
    elementType: 'TYPE',
    what: 'Container holding multiple @PropertySource declarations with defined order.',
    why: 'Load several property files from one @Configuration.',
    when: 'Defaults + environment overlay + optional missing file.',
    processor: 'PropertySourceRegistry processes each nested @PropertySource.',
    example: '@PropertySources({@PropertySource("defaults.properties"), @PropertySource("override.properties")})',
    interviewImportance: 'high',
    versionNotes: 'ignoreResourceNotFound per nested source.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Environment prep.',
    commonMistakes: ['Key conflicts — order matters'],
    interviewTraps: ['Repeatable @PropertySource vs container'],
    relatedAnnotations: ['@PropertySource'],
    memory: 'PROPERTYSOURCES = multiple property files.',
  },
  {
    id: 'import-resource',
    annotation: '@ImportResource',
    family: 'config',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.ImportResource',
    elementType: 'TYPE',
    what: 'Imports XML or Groovy bean definitions into annotation-based ApplicationContext.',
    why: 'Gradual XML-to-Java migration; vendor XML wiring.',
    when: 'Legacy Spring XML, integration fragments.',
    processor: 'ImportResourceBeanDefinitionRegistrar + XmlBeanDefinitionReader.',
    example: '@ImportResource("classpath:legacy.xml")\n@SpringBootApplication class App {}',
    interviewImportance: 'high',
    versionNotes: 'Supported Boot 3; prefer Java config when possible.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Bean definition loading.',
    commonMistakes: ['Duplicate bean names XML vs scan'],
    interviewTraps: ['XML migration interview'],
    relatedAnnotations: ['@Import', '@Configuration'],
    memory: 'IMPORTRESOURCE = XML beans into context.',
  },
  {
    id: 'profile',
    annotation: '@Profile',
    family: 'config',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Profile',
    elementType: 'TYPE, METHOD',
    what: 'Activates bean or @Bean when Environment profile expression matches (e.g. prod, !local).',
    why: 'Environment-specific wiring without separate deployables.',
    when: 'Prod vs dev beans, feature toggles via profiles.',
    processor: 'ProfileCondition evaluates against active profiles; inactive beans not registered.',
    example: '@Profile("postgres")\n@Bean DataSource ds() {}',
    interviewImportance: 'must',
    versionNotes: 'spring.profiles.active in Boot 3 unchanged.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Bean definition — inactive skipped.',
    commonMistakes: ['Profile not active — silent missing bean', 'Wrong negation syntax'],
    interviewTraps: ['@Profile vs @ConditionalOnProperty'],
    relatedAnnotations: ['@ActiveProfiles', '@ConditionalOnProperty'],
    memory: 'PROFILE = bean gated by profile expression.',
  },
  {
    id: 'active-profiles',
    annotation: '@ActiveProfiles',
    family: 'config',
    module: 'spring-test',
    javaPackage: 'org.springframework.test.context.ActiveProfiles',
    elementType: 'TYPE',
    what: 'Activates Spring profiles for test ApplicationContext.',
    why: 'Test @Profile beans without global property files.',
    when: 'Integration tests for prod profile beans.',
    processor: 'ActiveProfilesContextCustomizer applies before test context bootstrap.',
    example: '@ActiveProfiles("integration")\n@SpringBootTest class IT {}',
    interviewImportance: 'must',
    versionNotes: 'spring-test 6.x / Boot 3.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Test context init.',
    commonMistakes: ['Missing profile — beans absent in tests'],
    interviewTraps: ['vs @DynamicPropertySource'],
    relatedAnnotations: ['@Profile', '@TestPropertySource'],
    memory: 'ACTIVEPROFILES = profiles in tests.',
  },
  {
    id: 'test-property-source',
    annotation: '@TestPropertySource',
    family: 'config',
    module: 'spring-test',
    javaPackage: 'org.springframework.test.context.TestPropertySource',
    elementType: 'TYPE',
    what: 'Adds PropertySource to test context via inline properties or locations.',
    why: 'Override individual keys per test class.',
    when: 'Stub flags, disable schedulers, point to test DB.',
    processor: 'TestPropertySourceUtils adds MapPropertySource early.',
    example: '@TestPropertySource(properties="payment.mode=stub")',
    interviewImportance: 'must',
    versionNotes: 'properties override locations in same annotation.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Test bootstrap.',
    commonMistakes: ['Key not overriding — wrong name'],
    interviewTraps: ['vs @SpringBootTest properties attribute'],
    relatedAnnotations: ['@DynamicPropertySource'],
    memory: 'TESTPROPERTYSOURCE = static test property overrides.',
  },
  {
    id: 'dynamic-property-source',
    annotation: '@DynamicPropertySource',
    family: 'config',
    module: 'spring-test',
    javaPackage: 'org.springframework.test.context.DynamicPropertySource',
    elementType: 'METHOD',
    what: 'Static method registering dynamic properties into test Environment before context refresh.',
    why: 'Runtime-computed URLs — Testcontainers ports, WireMock.',
    when: 'Testcontainers JDBC URL, random server port.',
    processor: 'DynamicPropertyRegistry callback before context refresh.',
    example: '@DynamicPropertySource\nstatic void props(DynamicPropertyRegistry r) { r.add("db.url", pg::getJdbcUrl); }',
    interviewImportance: 'must',
    versionNotes: 'Since Boot 2.2.5; method must be static.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Pre-context refresh in tests.',
    commonMistakes: ['Non-static method ignored', 'Too late registration'],
    interviewTraps: ['Testcontainers standard pattern'],
    relatedAnnotations: ['@TestPropertySource'],
    memory: 'DYNAMICPROPERTYSOURCE = runtime test properties.',
  },
  {
    id: 'component',
    annotation: '@Component',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.stereotype.Component',
    elementType: 'TYPE',
    what: 'Generic stereotype marking a class as a Spring-managed component discovered by classpath scanning.',
    why: 'Automatic bean registration without manual @Bean; root of @Service/@Repository/@Controller.',
    when: 'Helpers, adapters, infrastructure not fitting specialized stereotypes.',
    processor: 'ClassPathBeanDefinitionScanner + MetadataReader registers AnnotatedGenericBeanDefinition.',
    example: '@Component\npublic class EmailValidator {}',
    interviewImportance: 'must',
    versionNotes: 'Stable spring-context; meta @Indexed for classpath index in Boot.',
    proxyRelevant: 'No — plain singleton unless other features wrap bean.',
    lifecyclePhase: 'Scan → register definition → instantiate → inject.',
    commonMistakes: ['Class outside scanned packages', 'Duplicate default bean names'],
    interviewTraps: ['@Service does not add extra processor — same scan pipeline'],
    relatedAnnotations: ['@Service', '@ComponentScan'],
    memory: 'COMPONENT = scan → register → inject.',
  },
  {
    id: 'service',
    annotation: '@Service',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.stereotype.Service',
    elementType: 'TYPE',
    what: 'Stereotype meta-annotated @Component for business/service layer — no extra BeanPostProcessor in SF 6.',
    why: 'Documents architectural layer; identical container registration to @Component.',
    when: 'Business logic classes; pair with @Transactional explicitly when needed.',
    processor: 'Same ClassPathBeanDefinitionScanner pipeline as @Component.',
    example: '@Service\npublic class OrderService { @Transactional public Order place() {} }',
    interviewImportance: 'must',
    versionNotes: 'No javax/jakarta on stereotype itself.',
    proxyRelevant: 'No — unless @Transactional/@Async/@Cacheable applied.',
    lifecyclePhase: 'Same as @Component.',
    commonMistakes: ['Believing @Service enables @Transactional', 'Self-invocation on @Transactional methods'],
    interviewTraps: ['@Service does NOT enable transactions'],
    relatedAnnotations: ['@Component', '@Transactional'],
    memory: 'SERVICE = @Component + layer label; TX needs @Transactional.',
  },
  {
    id: 'repository',
    annotation: '@Repository',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.stereotype.Repository',
    elementType: 'TYPE',
    what: 'Stereotype @Component for persistence layer; triggers PersistenceExceptionTranslationPostProcessor.',
    why: 'Translates vendor persistence exceptions to Spring DataAccessException hierarchy.',
    when: 'JDBC, JPA, Mongo data access beans.',
    processor: 'Scanner + PersistenceExceptionTranslationPostProcessor for @Repository beans.',
    example: '@Repository\npublic class JdbcOrderRepo implements OrderRepository {}',
    interviewImportance: 'must',
    versionNotes: 'Exception translation requires PersistenceExceptionTranslationPostProcessor bean.',
    proxyRelevant: 'No — exception translation wraps calls via advisor on template usage.',
    lifecyclePhase: 'Scan + post-processor registration.',
    commonMistakes: ['Expecting JPA repository without @EnableJpaRepositories', 'SQLException not translated without setup'],
    interviewTraps: ['@Repository vs Spring Data interface repos'],
    relatedAnnotations: ['@Service', '@Transactional'],
    memory: 'REPOSITORY = @Component + exception translation.',
  },
  {
    id: 'controller',
    annotation: '@Controller',
    family: 'stereotype',
    module: 'spring-webmvc',
    javaPackage: 'org.springframework.stereotype.Controller',
    elementType: 'TYPE',
    what: 'Stereotype @Component for MVC presentation layer; often paired with @RequestMapping.',
    why: 'Marks web controller for RequestMappingHandlerMapping handler detection.',
    when: 'Server-side MVC returning views or @ResponseBody on methods.',
    processor: 'Component scan + RequestMappingHandlerMapping detects @RequestMapping on @Controller.',
    example: '@Controller\npublic class HomeController { @GetMapping("/") String home() { return "index"; } }',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 MVC uses jakarta.servlet.',
    proxyRelevant: 'No — MVC invokes handler directly unless @Transactional on method.',
    lifecyclePhase: 'Scan → handler mapping → request dispatch.',
    commonMistakes: ['@Controller without @ResponseBody returns view name — not JSON', 'Mixing @RestController semantics'],
    interviewTraps: ['@Controller vs @RestController'],
    relatedAnnotations: ['@RestController', '@RequestMapping'],
    memory: 'CONTROLLER = MVC handler stereotype.',
  },
  {
    id: 'rest-controller',
    annotation: '@RestController',
    family: 'stereotype',
    module: 'spring-web',
    javaPackage: 'org.springframework.web.bind.annotation.RestController',
    elementType: 'TYPE',
    what: 'Composed @Controller + @ResponseBody — return values serialized via HttpMessageConverter.',
    why: 'REST APIs returning JSON/XML without per-method @ResponseBody.',
    when: 'REST endpoints in Boot 3 web apps.',
    processor: 'RequestMappingHandlerMapping + RequestResponseBodyMethodProcessor.',
    example: '@RestController\n@RequestMapping("/api/orders")\npublic class OrderApi {}',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: jakarta.servlet / jakarta.validation on params.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'HTTP request handling.',
    commonMistakes: ['Returning entity without proper converter', 'Validation without @Valid'],
    interviewTraps: ['@RestController = @Controller + @ResponseBody via @AliasFor'],
    relatedAnnotations: ['@Controller', '@ResponseBody'],
    memory: 'RESTCONTROLLER = @Controller + @ResponseBody.',
  },
  {
    id: 'configuration',
    annotation: '@Configuration',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Configuration',
    elementType: 'TYPE',
    what: '@Component class declaring @Bean methods; default proxyBeanMethods=true CGLIB-enhances for singleton @Bean inter-calls.',
    why: 'Java-based bean factory grouping; replaces XML <beans>.',
    when: 'Central Java config, library @Bean exports, @AutoConfiguration base.',
    processor: 'ConfigurationClassPostProcessor + ConfigurationClassEnhancer (CGLIB when proxyBeanMethods=true).',
    example: '@Configuration(proxyBeanMethods = true)\npublic class AppConfig { @Bean ObjectMapper mapper() {} }',
    interviewImportance: 'must',
    versionNotes: 'proxyBeanMethods default true since SF 5.2 / Boot 2.2.',
    proxyRelevant: 'Yes — CGLIB proxy of @Configuration for @Bean inter-calls when full mode.',
    lifecyclePhase: 'Early refresh — config class parsed before dependent beans.',
    commonMistakes: ['proxyBeanMethods=false with inter-@Bean calls — multiple instances', 'final @Configuration class fails enhancement'],
    interviewTraps: ['Lite @Configuration interview trap'],
    relatedAnnotations: ['@Bean', '@Import'],
    memory: 'CONFIGURATION = @Bean factory + optional CGLIB config proxy.',
  },
  {
    id: 'bean',
    annotation: '@Bean',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Bean',
    elementType: 'METHOD, ANNOTATION_TYPE',
    what: 'Factory annotation on @Configuration/@Component methods — container invokes method to produce bean instance.',
    why: 'Programmatic construction for third-party types and explicit wiring.',
    when: 'Third-party libraries, multi-step object graphs, conditional factories.',
    processor: 'ConfigurationClassBeanDefinitionReader → RootBeanDefinition with factoryMethodName.',
    example: '@Bean\npublic ObjectMapper objectMapper() { return new ObjectMapper(); }',
    interviewImportance: 'must',
    versionNotes: 'destroyMethod inference in Boot — watch close() on unintended beans.',
    proxyRelevant: 'Returned bean may be AOP-proxied if advised; config class may be CGLIB proxy.',
    lifecyclePhase: 'Factory invocation during bean creation.',
    commonMistakes: ['Direct @Bean method call bypasses singleton cache', 'List<T> parameter injects all beans of type T'],
    interviewTraps: ['@Bean on @Component without full @Configuration'],
    relatedAnnotations: ['@Configuration', '@Component'],
    memory: 'BEAN = factory method registered in container.',
  },
  {
    id: 'component-scan',
    annotation: '@ComponentScan',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.ComponentScan',
    elementType: 'TYPE',
    what: 'Configures classpath scanning for @Component stereotypes in base packages or classes.',
    why: 'Discovery without XML or per-class @Bean registration.',
    when: 'Explicit scan roots in library modules; custom filters.',
    processor: 'ComponentScanAnnotationParser → ClassPathBeanDefinitionScanner.',
    example: '@ComponentScan(basePackages = "com.acme.orders")\n@Configuration class ScanConfig {}',
    interviewImportance: 'must',
    versionNotes: '@SpringBootApplication includes @ComponentScan on main package.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Bean definition registration during refresh.',
    commonMistakes: ['Overly broad base package scanning test classes', 'Missing scan when not using @SpringBootApplication'],
    interviewTraps: ['scanBasePackages vs scanBasePackageClasses'],
    relatedAnnotations: ['@Component', '@SpringBootApplication'],
    memory: 'COMPONENTSCAN = drive ClassPathBeanDefinitionScanner.',
  },
  {
    id: 'import',
    annotation: '@Import',
    family: 'stereotype',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Import',
    elementType: 'TYPE, ANNOTATION_TYPE',
    what: 'Imports additional @Configuration classes, ImportSelector, or ImportBeanDefinitionRegistrar into parsing set.',
    why: 'Modular configuration assembly without component scanning.',
    when: 'Feature modules exporting configuration; @EnableXxx meta-annotations use @Import.',
    processor: 'ConfigurationClassParser processes @Import entries during configuration class parsing.',
    example: '@Import({KafkaConfig.class, MetricsConfig.class})\n@Configuration class AppConfig {}',
    interviewImportance: 'must',
    versionNotes: 'ImportSelector used heavily in Boot auto-config.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Configuration parsing phase.',
    commonMistakes: ['Importing class not on classpath — failure at parse', 'Circular @Import between configs'],
    interviewTraps: ['@Import vs @ComponentScan'],
    relatedAnnotations: ['@Configuration', '@EnableAutoConfiguration'],
    memory: 'IMPORT = pull configuration classes into context.',
  },
  {
    id: 'autowired',
    annotation: '@Autowired',
    family: 'di',
    module: 'spring-beans',
    javaPackage: 'org.springframework.beans.factory.annotation.Autowired',
    elementType: 'CONSTRUCTOR, METHOD, FIELD, PARAMETER',
    what: 'Marks injection points resolved by type during populateBean.',
    why: 'Declarative wiring without manual getBean().',
    when: 'Constructor injection (preferred); optional on single constructor since 4.3.',
    processor: 'AutowiredAnnotationBeanPostProcessor → InjectionMetadata → resolveDependency.',
    example: 'public PaymentService(PaymentGateway gateway) {} // @Autowired optional',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 unchanged; jakarta types on injection points.',
    proxyRelevant: 'Injects proxy if target bean is advised.',
    lifecyclePhase: 'populateBean during bean creation.',
    commonMistakes: ['Missing @Qualifier with multiple candidates', 'Circular constructor injection'],
    interviewTraps: ['populateBean → InjectionMetadata → DependencyDescriptor chain'],
    relatedAnnotations: ['@Qualifier', '@Primary'],
    memory: 'AUTOWIRED = populateBean resolves injection points.',
  },
  {
    id: 'qualifier',
    annotation: '@Qualifier',
    family: 'di',
    module: 'spring-beans',
    javaPackage: 'org.springframework.beans.factory.annotation.Qualifier',
    elementType: 'FIELD, METHOD, PARAMETER, TYPE, ANNOTATION_TYPE',
    what: 'Disambiguates injection when multiple beans match type — qualifier string or custom annotation.',
    why: 'Explicit wiring when @Primary is wrong or multiple implementations coexist.',
    when: 'Multiple PaymentGateway beans, named JDBC templates.',
    processor: 'determineAutowireCandidate filters by @Qualifier on injection point — beats @Primary when specified.',
    example: '@Qualifier("stripe")\nPaymentGateway gateway;',
    interviewImportance: 'must',
    versionNotes: 'Custom @Qualifier annotations are meta @Qualifier.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Dependency resolution.',
    commonMistakes: ['@Qualifier on bean vs injection point confusion', 'Typo in qualifier string'],
    interviewTraps: ['@Qualifier beats @Primary on injection point'],
    relatedAnnotations: ['@Primary', '@Autowired'],
    memory: 'QUALIFIER = disambiguate autowire candidates.',
  },
  {
    id: 'primary',
    annotation: '@Primary',
    family: 'di',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Primary',
    elementType: 'TYPE, METHOD, ANNOTATION_TYPE',
    what: 'Marks preferred bean when multiple candidates match type and no @Qualifier on injection point.',
    why: 'Default implementation among several beans of same type.',
    when: 'Default DataSource, primary RestTemplate among many.',
    processor: 'determineAutowireCandidate prefers @Primary among remaining candidates.',
    example: '@Primary\n@Bean DataSource dataSource() {}',
    interviewImportance: 'must',
    versionNotes: 'Only one @Primary per type expected — multiple @Primary causes ambiguity.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Dependency resolution.',
    commonMistakes: ['Two @Primary beans — still ambiguous', 'Expecting @Primary to override @Qualifier'],
    interviewTraps: ['@Qualifier wins over @Primary when on injection point'],
    relatedAnnotations: ['@Qualifier', '@Autowired'],
    memory: 'PRIMARY = default candidate when no qualifier.',
  },
  {
    id: 'resource',
    annotation: '@Resource',
    family: 'di',
    module: 'jakarta.annotation-api',
    javaPackage: 'jakarta.annotation.Resource',
    elementType: 'TYPE, FIELD, METHOD',
    what: 'JSR-250 injection by name first, then type. Processed by CommonAnnotationBeanPostProcessor.',
    why: 'EE-standard name-based injection; alternative to @Autowired + @Qualifier.',
    when: 'Legacy EE migrations, explicit JNDI-style names.',
    processor: 'CommonAnnotationBeanPostProcessor resolves name from @Resource name/mappedName then type.',
    example: '@Resource(name = "auditJdbcTemplate")\nprivate JdbcTemplate jdbc;',
    interviewImportance: 'high',
    versionNotes: 'Boot 3: jakarta.annotation.Resource. Boot 2: javax.annotation.Resource.',
    proxyRelevant: 'Injects container bean reference; may be proxy.',
    lifecyclePhase: 'populateBean via CommonAnnotationBeanPostProcessor.',
    commonMistakes: ['Name mismatch — falls back to type and may still fail', 'Mixing @Resource and @Autowired on same field'],
    interviewTraps: ['@Resource name-first vs @Autowired type-first'],
    relatedAnnotations: ['@Autowired', '@Qualifier'],
    memory: 'RESOURCE = JSR-250 name-first injection.',
  },
  {
    id: 'value',
    annotation: '@Value',
    family: 'di',
    module: 'spring-beans',
    javaPackage: 'org.springframework.beans.factory.annotation.Value',
    elementType: 'FIELD, METHOD, PARAMETER',
    what: 'Injects property, SpEL expression, or default literal into field/parameter.',
    why: 'Externalized config without @ConfigurationProperties for simple values.',
    when: 'Feature flags, timeouts, secrets from Environment.',
    processor: 'AutowiredAnnotationBeanPostProcessor resolves @Value via EmbeddedValueResolver / SpEL.',
    example: '@Value("${payment.timeout:30s}")\nDuration timeout;',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: same; relaxed binding not applied to @Value — use exact key.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'populateBean.',
    commonMistakes: ['Missing property without default — failure', 'SpEL injection of bean refs — surprising coupling'],
    interviewTraps: ['@Value vs @ConfigurationProperties interview'],
    relatedAnnotations: ['@ConfigurationProperties', '@PropertySource'],
    memory: 'VALUE = inject property or SpEL from Environment.',
  },
  {
    id: 'configuration-properties',
    annotation: '@ConfigurationProperties',
    family: 'di',
    module: 'spring-boot',
    javaPackage: 'org.springframework.boot.context.properties.ConfigurationProperties',
    elementType: 'TYPE, METHOD, ANNOTATION_TYPE',
    what: 'Binds Environment properties to structured POJO with relaxed binding and validation.',
    why: 'Type-safe config groups vs many @Value fields.',
    when: 'app.*, spring.kafka.* style grouped configuration.',
    processor: 'ConfigurationPropertiesBindingPostProcessor + Binder (Boot).',
    example: '@ConfigurationProperties(prefix = "payment")\npublic class PaymentProps { Duration timeout; }',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: jakarta.validation on properties class. Boot 2: javax.validation.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Post-process after bean creation — bind properties.',
    commonMistakes: ['Missing @EnableConfigurationProperties or @ConfigurationPropertiesScan', 'Not a @Component — needs registration'],
    interviewTraps: ['@ConfigurationProperties vs @Value'],
    relatedAnnotations: ['@Value', '@Validated'],
    memory: 'CONFIGURATIONPROPERTIES = bind prefix to POJO.',
  },
  {
    id: 'lazy',
    annotation: '@Lazy',
    family: 'lifecycle',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Lazy',
    elementType: 'TYPE, METHOD, PARAMETER, FIELD, ANNOTATION_TYPE',
    what: 'Defers bean creation until first access; on injection point injects lazy-init proxy.',
    why: 'Faster startup, break some circular dependencies, optional heavy beans.',
    when: 'Heavy clients, @Lazy on injection to break cycles, lazy singleton beans.',
    processor: 'LazyInitializationBeanFactoryPostProcessor / lazy flag on BeanDefinition; injection point lazy resolves proxy.',
    example: '@Lazy\n@Service class HeavyClient {}',
    interviewImportance: 'high',
    versionNotes: 'Lazy injection proxy resolves on first method call.',
    proxyRelevant: 'Yes — lazy injection often uses proxy wrapping target.',
    lifecyclePhase: 'Creation deferred until getBean/first use.',
    commonMistakes: ['@Lazy does not make @Transactional async', 'Lazy bean still singleton once initialized'],
    interviewTraps: ['@Lazy injection point proxy behavior'],
    relatedAnnotations: ['@DependsOn', 'ObjectProvider'],
    memory: 'LAZY = create on first use; injection may use proxy.',
  },
  {
    id: 'depends-on',
    annotation: '@DependsOn',
    family: 'lifecycle',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.DependsOn',
    elementType: 'TYPE, METHOD',
    what: 'Explicit startup order — depended-on beans initialized before this bean (no injection implied).',
    why: 'Initialize infrastructure beans before consumers without injection link.',
    when: 'Cache manager before caches, security filter ordering setup.',
    processor: 'BeanDefinition.setDependsOn processed during singleton pre-instantiation sort.',
    example: '@DependsOn("cacheManager")\n@Bean Cache ordersCache() {}',
    interviewImportance: 'high',
    versionNotes: 'Does not inject dependency — only ordering.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Singleton pre-instantiation ordering.',
    commonMistakes: ['Expecting @DependsOn to inject bean', 'Circular depends-on chain'],
    interviewTraps: ['@DependsOn vs @Autowired difference'],
    relatedAnnotations: ['@Lazy', '@Order'],
    memory: 'DEPENDSON = init order only, not injection.',
  },
  {
    id: 'scope',
    annotation: '@Scope',
    family: 'lifecycle',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Scope',
    elementType: 'TYPE, METHOD',
    what: 'Sets bean scope: singleton, prototype, request, session, etc. Configurable via Scope custom scopes.',
    why: 'Non-singleton lifecycles for web and custom contexts.',
    when: 'Prototype beans, request-scoped controllers, custom tenant scope.',
    processor: 'ScopeMetadataResolver on BeanDefinition; ScopedProxyFactoryBean for scoped injection into singleton.',
    example: '@Scope(value = WebApplicationContext.SCOPE_REQUEST, proxyMode = TARGET_CLASS)\n@Component class RequestUser {}',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 web scopes use jakarta.servlet context.',
    proxyRelevant: 'proxyMode TARGET_CLASS/INTERFACES creates scoped proxy for singleton injection.',
    lifecyclePhase: 'Scope determines creation and destruction policy.',
    commonMistakes: ['Prototype injected into singleton without proxy — shared mutable state', 'Wrong scope in non-web context'],
    interviewTraps: ['request scope needs web context'],
    relatedAnnotations: ['@Lazy', '@Lookup'],
    memory: 'SCOPE = lifecycle boundary; proxyMode for singleton injection.',
  },
  {
    id: 'post-construct',
    annotation: '@PostConstruct',
    family: 'lifecycle',
    module: 'jakarta.annotation-api',
    javaPackage: 'jakarta.annotation.PostConstruct',
    elementType: 'METHOD',
    what: 'Callback after dependency injection and before bean is considered ready.',
    why: 'Lightweight initialization without implementing InitializingBean interface.',
    when: 'Open connections, validate config, register metrics after DI complete.',
    processor: 'CommonAnnotationBeanPostProcessor invokes @PostConstruct after populateBean.',
    example: '@PostConstruct void init() { validator.validate(config); }',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: jakarta.annotation.PostConstruct. Boot 2: javax.annotation.PostConstruct.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'initializeBean after injection.',
    commonMistakes: ['Heavy work slowing startup', '@PostConstruct on static method — invalid'],
    interviewTraps: ['@PostConstruct vs InitializingBean vs @Bean initMethod'],
    relatedAnnotations: ['@PreDestroy', '@Bean'],
    memory: 'POSTCONSTRUCT = init callback after DI.',
  },
  {
    id: 'pre-destroy',
    annotation: '@PreDestroy',
    family: 'lifecycle',
    module: 'jakarta.annotation-api',
    javaPackage: 'jakarta.annotation.PreDestroy',
    elementType: 'METHOD',
    what: 'Callback before bean destruction on context shutdown.',
    why: 'Graceful cleanup — close pools, flush buffers.',
    when: 'Shutdown hooks for executors, connection drains.',
    processor: 'CommonAnnotationBeanPostProcessor + DisposableBeanAdapter on context close.',
    example: '@PreDestroy void shutdown() { executor.shutdown(); }',
    interviewImportance: 'high',
    versionNotes: 'Boot 3: jakarta.annotation.PreDestroy. Boot 2: javax.annotation.PreDestroy.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Context shutdown / scope destruction.',
    commonMistakes: ['Long @PreDestroy blocking shutdown', 'Missing shutdown for thread pools'],
    interviewTraps: ['vs @Bean destroyMethod inference in Boot'],
    relatedAnnotations: ['@PostConstruct', '@Bean'],
    memory: 'PRE_DESTROY = cleanup before bean removal.',
  },
  {
    id: 'conditional',
    annotation: '@Conditional',
    family: 'conditional-boot',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.Conditional',
    elementType: 'TYPE, METHOD',
    what: 'Meta-annotation registering Condition evaluated at bean registration time.',
    why: 'Foundation for @Profile and all Boot @ConditionalOn* annotations.',
    when: 'Custom feature flags and environment gates on @Bean/@Configuration.',
    processor: 'ConditionEvaluator.evaluate before registering BeanDefinition.',
    example: '@Conditional(OnKafkaEnabledCondition.class)\n@Configuration class KafkaConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Custom Condition implements matches(ConditionContext, AnnotatedTypeMetadata).',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Bean definition registration.',
    commonMistakes: ['Condition false — bean absent silently', 'Heavy work in Condition.matches slowing startup'],
    interviewTraps: ['@Conditional vs @Profile overlap'],
    relatedAnnotations: ['@Profile', '@ConditionalOnProperty'],
    memory: 'CONDITIONAL = Condition gates bean registration.',
  },
  {
    id: 'conditional-on-class',
    annotation: '@ConditionalOnClass',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnClass',
    elementType: 'TYPE, METHOD',
    what: 'Matches when specified classes are on classpath (ASM name check — class not loaded).',
    why: 'Auto-config activates only when optional library present.',
    when: 'Kafka/Rabbit auto-config, optional driver activation.',
    processor: 'OnClassCondition using ASM ClassReader for presence.',
    example: '@ConditionalOnClass(KafkaTemplate.class)\n@AutoConfiguration class KafkaAutoConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 auto-config in spring-boot-autoconfigure.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config import filtering.',
    commonMistakes: ['Class name string typo — condition false', 'Using class literal loads class — prefer string name for optional deps'],
    interviewTraps: ['OnClass uses ASM — does not load class'],
    relatedAnnotations: ['@ConditionalOnMissingClass', '@AutoConfiguration'],
    memory: 'CONDITIONALONCLASS = classpath has class (ASM).',
  },
  {
    id: 'conditional-on-missing-class',
    annotation: '@ConditionalOnMissingClass',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnMissingClass',
    elementType: 'TYPE, METHOD',
    what: 'Matches when specified classes are NOT on classpath.',
    why: 'Fallback config when optional library absent.',
    when: 'Legacy driver fallback, disable feature when newer client present.',
    processor: 'OnClassCondition inverted match.',
    example: '@ConditionalOnMissingClass("com.example.LegacyClient")',
    interviewImportance: 'high',
    versionNotes: 'String class names to avoid loading.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['Wrong negation logic in custom conditions'],
    interviewTraps: ['Pair with @ConditionalOnClass for branches'],
    relatedAnnotations: ['@ConditionalOnClass'],
    memory: 'CONDITIONALONMISSINGCLASS = class absent from classpath.',
  },
  {
    id: 'conditional-on-bean',
    annotation: '@ConditionalOnBean',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnBean',
    elementType: 'TYPE, METHOD',
    what: 'Matches when specified beans already registered in BeanFactory.',
    why: 'Layered auto-config depending on user or prior auto-config beans.',
    when: 'Configurer beans after DataSource exists.',
    processor: 'OnBeanCondition queries BeanFactory for bean definitions/types.',
    example: '@ConditionalOnBean(DataSource.class)\n@AutoConfiguration class JdbcTemplateAutoConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Evaluated during auto-config processing order matters.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config registration.',
    commonMistakes: ['Bean defined later in order — false negative', 'Annotation on @Bean method vs @Configuration'],
    interviewTraps: ['AutoConfigureAfter ordering interview'],
    relatedAnnotations: ['@ConditionalOnMissingBean', '@AutoConfigureAfter'],
    memory: 'CONDITIONALONBEAN = required beans exist.',
  },
  {
    id: 'conditional-on-missing-bean',
    annotation: '@ConditionalOnMissingBean',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean',
    elementType: 'TYPE, METHOD',
    what: 'Matches when no bean of specified type/name exists — default auto-config pattern.',
    why: 'User @Bean overrides auto-configured default.',
    when: 'Default DataSource, RestTemplate, ObjectMapper in Boot auto-config.',
    processor: 'OnBeanCondition inverted; searchedByType and name attributes.',
    example: '@ConditionalOnMissingBean\n@Bean DataSource dataSource() {}',
    interviewImportance: 'must',
    versionNotes: 'Core pattern for Boot auto-configuration beans.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config bean registration.',
    commonMistakes: ['@Bean without @ConditionalOnMissingBean overrides user bean — Boot uses pattern on auto-config side', 'Multiple missing beans ambiguity'],
    interviewTraps: ['User @Bean wins when auto-config uses this'],
    relatedAnnotations: ['@ConditionalOnBean', '@Bean'],
    memory: 'CONDITIONALONMISSINGBEAN = register default if user did not.',
  },
  {
    id: 'conditional-on-property',
    annotation: '@ConditionalOnProperty',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnProperty',
    elementType: 'TYPE, METHOD',
    what: 'Matches when Environment property matches prefix/name/havingValue/matchIfMissing.',
    why: 'Feature flags and environment toggles without @Profile alone.',
    when: 'spring.kafka.enabled, feature toggles in auto-config.',
    processor: 'OnPropertyCondition reads Environment with relaxed binding.',
    example: '@ConditionalOnProperty(name="feature.x", havingValue="true")',
    interviewImportance: 'must',
    versionNotes: 'Relaxed binding applies to property names.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Condition evaluation at registration.',
    commonMistakes: ['havingValue mismatch due to wrong key', 'matchIfMissing surprises'],
    interviewTraps: ['vs @Profile for feature flags'],
    relatedAnnotations: ['@Profile', '@Value'],
    memory: 'CONDITIONALONPROPERTY = property gate for beans.',
  },
  {
    id: 'conditional-on-resource',
    annotation: '@ConditionalOnResource',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnResource',
    elementType: 'TYPE, METHOD',
    what: 'Matches when specified classpath resource exists.',
    why: 'Activate config when config file or marker resource present.',
    when: 'classpath:schema.sql, META-INF marker files.',
    processor: 'OnResourceCondition checks ResourceLoader.',
    example: '@ConditionalOnResource(resources = "classpath:custom.yaml")',
    interviewImportance: 'high',
    versionNotes: 'Resource pattern supported.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Condition evaluation.',
    commonMistakes: ['Resource moved — config silently disabled'],
    interviewTraps: ['Resource exists vs property set'],
    relatedAnnotations: ['@ConditionalOnProperty'],
    memory: 'CONDITIONALONRESOURCE = classpath resource exists.',
  },
  {
    id: 'conditional-on-web-application',
    annotation: '@ConditionalOnWebApplication',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnWebApplication',
    elementType: 'TYPE, METHOD',
    what: 'Matches in servlet or reactive web application context.',
    why: 'Web-only auto-config — MVC, embedded server beans.',
    when: 'DispatcherServlet auto-config, web security filters.',
    processor: 'OnWebApplicationCondition inspects ApplicationContext type.',
    example: '@ConditionalOnWebApplication(type = SERVLET)',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 distinguishes SERVLET vs REACTIVE.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['Running non-web test context — web beans missing'],
    interviewTraps: ['SERVLET vs REACTIVE type attribute'],
    relatedAnnotations: ['@ConditionalOnNotWebApplication'],
    memory: 'CONDITIONALONWEBAPPLICATION = web context detected.',
  },
  {
    id: 'conditional-on-not-web-application',
    annotation: '@ConditionalOnNotWebApplication',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnNotWebApplication',
    elementType: 'TYPE, METHOD',
    what: 'Matches when NOT a web application context.',
    why: 'Batch/CLI-only beans excluded from web apps.',
    when: 'CommandLineRunner config, non-web metrics.',
    processor: 'OnWebApplicationCondition negated.',
    example: '@ConditionalOnNotWebApplication\n@Configuration class CliConfig {}',
    interviewImportance: 'high',
    versionNotes: 'Pair with web condition for split modules.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['Wrong SpringApplication web type deduction'],
    interviewTraps: ['SpringApplication web application type'],
    relatedAnnotations: ['@ConditionalOnWebApplication'],
    memory: 'CONDITIONALONNOTWEBAPPLICATION = non-web context.',
  },
  {
    id: 'conditional-on-expression',
    annotation: '@ConditionalOnExpression',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnExpression',
    elementType: 'TYPE, METHOD',
    what: 'Matches when SpEL expression evaluates to true against BeanFactory/Environment.',
    why: 'Complex conditions combining multiple properties and beans.',
    when: 'Expression referencing @bean and environment properties.',
    processor: 'OnExpressionCondition evaluates SpEL with BeanExpressionContext.',
    example: '@ConditionalOnExpression("${feature.a:false} and ${feature.b:false}")',
    interviewImportance: 'high',
    versionNotes: 'SpEL errors fail condition or context refresh.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Condition evaluation.',
    commonMistakes: ['SpEL typo fails startup', 'Expression bean not yet defined — ordering'],
    interviewTraps: ['SpEL in conditions vs @Value'],
    relatedAnnotations: ['@ConditionalOnProperty'],
    memory: 'CONDITIONALONEXPRESSION = SpEL true gate.',
  },
  {
    id: 'conditional-on-java',
    annotation: '@ConditionalOnJava',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnJava',
    elementType: 'TYPE, METHOD',
    what: 'Matches JVM version range using JavaVersion enum (EQUAL_OR_NEWER, etc.).',
    why: 'Auto-config variants for Java 17+ APIs.',
    when: 'Multi-release behavior in auto-config modules.',
    processor: 'OnJavaCondition compares JavaVersion.getJavaVersion().',
    example: '@ConditionalOnJava(JavaVersion.SEVENTEEN)',
    interviewImportance: 'medium',
    versionNotes: 'Useful as teams move Boot 3 on Java 17+.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['Wrong JavaVersion constant'],
    interviewTraps: ['Java 17 baseline for Boot 3'],
    relatedAnnotations: ['@ConditionalOnCloudPlatform'],
    memory: 'CONDITIONALONJAVA = JVM version gate.',
  },
  {
    id: 'conditional-on-cloud-platform',
    annotation: '@ConditionalOnCloudPlatform',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnCloudPlatform',
    elementType: 'TYPE, METHOD',
    what: 'Matches detected CloudPlatform (KUBERNETES, AWS, AZURE, etc.).',
    why: 'Cloud-specific service discovery and binding.',
    when: 'Kubernetes config maps, CF bindings when detectable.',
    processor: 'OnCloudPlatformCondition reads CloudPlatform.getActive(context).',
    example: '@ConditionalOnCloudPlatform(CloudPlatform.KUBERNETES)',
    interviewImportance: 'medium',
    versionNotes: 'Detection heuristics — verify in target environment.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['False negative in custom K8s environments'],
    interviewTraps: ['CloudPlatform detection signals'],
    relatedAnnotations: ['@ConditionalOnProperty'],
    memory: 'CONDITIONALONCLOUDPLATFORM = cloud environment gate.',
  },
  {
    id: 'conditional-on-jndi',
    annotation: '@ConditionalOnJndi',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnJndi',
    elementType: 'TYPE, METHOD',
    what: 'Matches when JNDI lookup for specified names succeeds.',
    why: 'Traditional EE JNDI DataSource in managed servers.',
    when: 'Legacy deployments on application servers.',
    processor: 'OnJndiCondition attempts InitialContext lookup.',
    example: '@ConditionalOnJndi("java:comp/env/jdbc/main")',
    interviewImportance: 'low',
    versionNotes: 'Rare in embedded Boot; still in enterprise EE migrations.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Condition evaluation.',
    commonMistakes: ['JNDI not available in embedded Tomcat default'],
    interviewTraps: ['EE vs embedded Boot'],
    relatedAnnotations: ['@ConditionalOnResource'],
    memory: 'CONDITIONALONJNDI = JNDI name resolvable.',
  },
  {
    id: 'conditional-on-war-deployment',
    annotation: '@ConditionalOnWarDeployment',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnWarDeployment',
    elementType: 'TYPE, METHOD',
    what: 'Matches when application deployed as WAR to external servlet container.',
    why: 'Different from executable jar — ServletContext bootstrapping.',
    when: 'SpringBootServletInitializer WAR deployments.',
    processor: 'OnWarDeploymentCondition checks WarDeploymentDetector.',
    example: '@ConditionalOnWarDeployment\n@Configuration class WarSetup {}',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 WAR still supported with jakarta.servlet.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['Assuming same auto-config as executable jar'],
    interviewTraps: ['WAR vs jar deployment interview'],
    relatedAnnotations: ['@ConditionalOnWebApplication'],
    memory: 'CONDITIONALONWAR = deployed as WAR to container.',
  },
  {
    id: 'conditional-on-single-candidate',
    annotation: '@ConditionalOnSingleCandidate',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnSingleCandidate',
    elementType: 'TYPE, METHOD',
    what: 'Matches when exactly one autowire candidate exists for type (or only one after @Primary).',
    why: 'Auto-wire configurer when unambiguous type.',
    when: 'JdbcTemplate auto-config when single DataSource candidate.',
    processor: 'OnBeanCondition specialized for single candidate check.',
    example: '@ConditionalOnSingleCandidate(DataSource.class)',
    interviewImportance: 'high',
    versionNotes: 'Fails if zero or multiple without @Primary resolution.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config registration.',
    commonMistakes: ['Multiple DataSources without @Primary — condition false'],
    interviewTraps: ['Single candidate vs @ConditionalOnBean'],
    relatedAnnotations: ['@ConditionalOnBean', '@Primary'],
    memory: 'CONDITIONALONSINGLECANDIDATE = exactly one autowire candidate.',
  },
  {
    id: 'conditional-on-missing-filter-bean',
    annotation: '@ConditionalOnMissingFilterBean',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnMissingFilterBean',
    elementType: 'TYPE, METHOD',
    what: 'Matches when no servlet FilterRegistrationBean for specified filter types exists.',
    why: 'Servlet filter auto-config defaults without overriding user filters.',
    when: 'Spring Security filter chain customizations.',
    processor: 'OnBeanCondition specialized for FilterRegistrationBean types.',
    example: '@ConditionalOnMissingFilterBean',
    interviewImportance: 'medium',
    versionNotes: 'Servlet stack — jakarta.servlet.Filter in Boot 3.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Web auto-config.',
    commonMistakes: ['Custom filter registration disables auto filter'],
    interviewTraps: ['FilterRegistrationBean pattern'],
    relatedAnnotations: ['@ConditionalOnMissingBean'],
    memory: 'CONDITIONALONMISSINGFILTERBEAN = no filter registration bean.',
  },
  {
    id: 'conditional-on-threading',
    annotation: '@ConditionalOnThreading',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.condition.ConditionalOnThreading',
    elementType: 'TYPE, METHOD',
    what: 'Matches application threading model (PLATFORM vs VIRTUAL) — Boot 3.2+ virtual threads support.',
    why: 'Conditional beans for virtual thread executors.',
    when: 'spring.threads.virtual.enabled configurations.',
    processor: 'OnThreadingCondition reads Threading property.',
    example: '@ConditionalOnThreading(Threading.VIRTUAL)',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3.2+ virtual threads feature.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config filtering.',
    commonMistakes: ['Virtual threads require Java 21+'],
    interviewTraps: ['Platform vs virtual threading'],
    relatedAnnotations: ['@EnableAsync', '@Scheduled'],
    memory: 'CONDITIONALONTHREADING = platform vs virtual threads.',
  },
  {
    id: 'spring-boot-application',
    annotation: '@SpringBootApplication',
    family: 'conditional-boot',
    module: 'spring-boot',
    javaPackage: 'org.springframework.boot.autoconfigure.SpringBootApplication',
    elementType: 'TYPE',
    what: 'Composed @SpringBootConfiguration + @EnableAutoConfiguration + @ComponentScan on main class package.',
    why: 'Single entry annotation for Boot apps.',
    when: 'Every Boot executable main class.',
    processor: 'SpringApplication.run → refresh with scan + auto-config import.',
    example: '@SpringBootApplication(scanBasePackages = "com.acme")\npublic class App { main... }',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: jakarta.* stack; AutoConfiguration.imports file.',
    proxyRelevant: 'Main @Configuration may be CGLIB proxy; advised beans proxied separately.',
    lifecyclePhase: 'Application bootstrap.',
    commonMistakes: ['Main class in sub-package — siblings not scanned', 'javax.servlet imports fail on Boot 3'],
    interviewTraps: ['=@Configuration + @EnableAutoConfiguration + @ComponentScan'],
    relatedAnnotations: ['@EnableAutoConfiguration', '@ComponentScan'],
    memory: 'SPRINGBOOTAPPLICATION = config + auto-config + scan.',
  },
  {
    id: 'enable-auto-configuration',
    annotation: '@EnableAutoConfiguration',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.EnableAutoConfiguration',
    elementType: 'TYPE',
    what: 'Enables Boot auto-configuration import via AutoConfigurationImportSelector.',
    why: 'Loads META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports.',
    when: 'Non-@SpringBootApplication tests or custom context needing auto-config.',
    processor: 'AutoConfigurationImportSelector @Import selector.',
    example: '@EnableAutoConfiguration(exclude = DataSourceAutoConfiguration.class)',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 uses imports file; Boot 2 used spring.factories.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Context refresh import phase.',
    commonMistakes: ['exclude typo leaves unwanted config', '@EnableAutoConfiguration on wrong class'],
    interviewTraps: ['AutoConfiguration.imports vs spring.factories'],
    relatedAnnotations: ['@SpringBootApplication', '@AutoConfiguration'],
    memory: 'ENABLEAUTOCONFIGURATION = import auto-config classes.',
  },
  {
    id: 'auto-configure-after',
    annotation: '@AutoConfigureAfter',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.AutoConfigureAfter',
    elementType: 'TYPE, PACKAGE',
    what: 'Orders auto-configuration class after specified configurations processed.',
    why: 'Ensure dependencies registered before this auto-config runs.',
    when: 'JdbcTemplate after DataSource auto-config.',
    processor: 'AutoConfigurationImportSelector sorting by annotations.',
    example: '@AutoConfigureAfter(DataSourceAutoConfiguration.class)',
    interviewImportance: 'high',
    versionNotes: 'Ordering among auto-config classes only.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config sort.',
    commonMistakes: ['Wrong order — @ConditionalOnBean false'],
    interviewTraps: ['After vs Before interview'],
    relatedAnnotations: ['@AutoConfigureBefore', '@AutoConfigureOrder'],
    memory: 'AUTOCONFIGUREAFTER = process after listed auto-configs.',
  },
  {
    id: 'auto-configure-before',
    annotation: '@AutoConfigureBefore',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.AutoConfigureBefore',
    elementType: 'TYPE, PACKAGE',
    what: 'Orders auto-configuration before specified configurations.',
    why: 'Register beans before another auto-config consumes them.',
    when: 'Security config ordering relative to defaults.',
    processor: 'AutoConfigurationImportSelector sorting.',
    example: '@AutoConfigureBefore(SecurityAutoConfiguration.class)',
    interviewImportance: 'high',
    versionNotes: 'Does not replace @ConditionalOnBean.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config sort.',
    commonMistakes: ['Conflicting After/Before cycles'],
    interviewTraps: ['Ordering vs conditions'],
    relatedAnnotations: ['@AutoConfigureAfter'],
    memory: 'AUTOCONFIGUREBEFORE = process before listed auto-configs.',
  },
  {
    id: 'auto-configure-order',
    annotation: '@AutoConfigureOrder',
    family: 'conditional-boot',
    module: 'spring-boot-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.AutoConfigureOrder',
    elementType: 'TYPE, PACKAGE',
    what: 'Absolute order value for auto-configuration class (lower = earlier).',
    why: 'Fine-grained ordering beyond After/Before chains.',
    when: 'Early security or metrics auto-config.',
    processor: 'AutoConfigurationImportSelector applies @Order on auto-config classes.',
    example: '@AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE)',
    interviewImportance: 'high',
    versionNotes: 'Lower value runs earlier like @Order.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Auto-config sort.',
    commonMistakes: ['Equal order — unstable', 'Confusion with @Order on regular beans'],
    interviewTraps: ['@Order on @AutoConfiguration'],
    relatedAnnotations: ['@AutoConfigureAfter', '@Order'],
    memory: 'AUTOCONFIGUREORDER = numeric auto-config precedence.',
  },
  {
    id: 'import-auto-configuration',
    annotation: '@ImportAutoConfiguration',
    family: 'conditional-boot',
    module: 'spring-boot-test-autoconfigure',
    javaPackage: 'org.springframework.boot.autoconfigure.ImportAutoConfiguration',
    elementType: 'TYPE',
    what: 'Imports specified auto-configuration classes in tests or slices.',
    why: 'Test slices pulling subset of auto-config without full @SpringBootApplication.',
    when: '@DataJpaTest, @JsonTest style test slices.',
    processor: '@Import with listed auto-configuration classes.',
    example: '@ImportAutoConfiguration(OAuth2ClientAutoConfiguration.class)',
    interviewImportance: 'high',
    versionNotes: 'Primarily test autoconfigure module.',
    proxyRelevant: 'No.',
    lifecyclePhase: 'Test context bootstrap.',
    commonMistakes: ['Import wrong auto-config set — missing beans'],
    interviewTraps: ['Test slice annotations use this internally'],
    relatedAnnotations: ['@SpringBootTest', '@EnableAutoConfiguration'],
    memory: 'IMPORTAUTOCONFIGURATION = explicit auto-config in tests.',
  },
  {
    id: 'enable-aspectj-auto-proxy',
    annotation: '@EnableAspectJAutoProxy',
    family: 'aop',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.annotation.EnableAspectJAutoProxy',
    elementType: 'TYPE',
    what: 'Enables Spring AOP proxy infrastructure — AnnotationAwareAspectJAutoProxyCreator.',
    why: 'Required for @Aspect advice and default Spring AOP (not full AspectJ weaving).',
    when: 'Custom @Aspect beans; explicit enable in non-Boot apps.',
    processor: 'AopConfigUtils.registerAspectJAnnotationAutoProxyCreatorIfNecessary.',
    example: '@EnableAspectJAutoProxy(proxyTargetClass = true)\n@Configuration class AopConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Boot auto-configures when spring-aop on classpath.',
    proxyRelevant: 'Enables proxy creation for advised beans.',
    lifecyclePhase: 'BeanPostProcessor registration at refresh.',
    commonMistakes: ['Forgot @EnableAspectJAutoProxy in plain Spring', 'exposeProxy=true for AopContext'],
    interviewTraps: ['Spring AOP vs AspectJ LTW'],
    relatedAnnotations: ['@Aspect', '@Transactional'],
    memory: 'ENABLEASPECTJAUTOPROXY = register auto-proxy creator.',
  },
  {
    id: 'aspect',
    annotation: '@Aspect',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.Aspect',
    elementType: 'TYPE',
    what: 'Declares class as AspectJ-style aspect containing pointcuts and advice — processed by Spring AOP when @Aspect bean.',
    why: 'Cross-cutting logging, metrics, security without polluting business code.',
    when: 'Custom aspects beyond @Transactional.',
    processor: 'AnnotationAwareAspectJAutoProxyCreator + AspectJExpressionPointcut from @Aspect bean.',
    example: '@Aspect @Component\npublic class AuditAspect { @Before("execution(* svc.*(..))") void log() {} }',
    interviewImportance: 'must',
    versionNotes: 'AspectJ annotation API; Spring applies runtime proxy weaving by default.',
    proxyRelevant: 'Advised beans wrapped in JDK/CGLIB proxy.',
    lifecyclePhase: 'Advisor registration when aspect bean initialized.',
    commonMistakes: ['@Aspect without @Component — not a bean', 'Self-invocation skips aspect'],
    interviewTraps: ['Spring AOP = proxy not compile-time AspectJ by default'],
    relatedAnnotations: ['@Pointcut', '@Around'],
    memory: 'ASPECT = aspect bean + pointcuts/advice.',
  },
  {
    id: 'pointcut',
    annotation: '@Pointcut',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.Pointcut',
    elementType: 'METHOD',
    what: 'Named pointcut expression reused by advice annotations in same @Aspect class.',
    why: 'DRY for AspectJ expression strings; combine pointcuts with && || !.',
    when: 'Package-scoped execution expressions shared across advice.',
    processor: 'Parsed into AspectJExpressionPointcut at aspect initialization.',
    example: '@Pointcut("execution(* com.app.service.*.*(..))")\nvoid serviceLayer() {}',
    interviewImportance: 'high',
    versionNotes: 'AspectJ pointcut language subset.',
    proxyRelevant: 'No — defines matching rules for advisors.',
    lifecyclePhase: 'Aspect metadata parsing.',
    commonMistakes: ['Overly broad pointcut — performance', 'Pointcut syntax errors at startup'],
    interviewTraps: ['Pointcut expression language interview'],
    relatedAnnotations: ['@Aspect', '@Before'],
    memory: 'POINTCUT = named AspectJ location predicate.',
  },
  {
    id: 'before',
    annotation: '@Before',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.Before',
    elementType: 'METHOD',
    what: 'Before advice runs prior to matched method execution — cannot prevent proceed.',
    why: 'Logging entry, auth check before method.',
    when: 'Audit log before service method.',
    processor: 'MethodBeforeAdvice adapter in advisor chain before target invocation.',
    example: '@Before("serviceLayer()")\nvoid before(JoinPoint jp) { log.info("enter"); }',
    interviewImportance: 'high',
    versionNotes: 'Runs on proxy path only.',
    proxyRelevant: 'Part of AOP interceptor chain.',
    lifecyclePhase: 'Before target method in proxy chain.',
    commonMistakes: ['Advice on private methods — not advised', 'Self-invocation skips'],
    interviewTraps: ['@Before cannot change return value'],
    relatedAnnotations: ['@Around', '@After'],
    memory: 'BEFORE = pre-invoke advice on proxy path.',
  },
  {
    id: 'after',
    annotation: '@After',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.After',
    elementType: 'METHOD',
    what: 'After advice runs after method exits regardless of success or exception (like finally).',
    why: 'Cleanup tied to method exit.',
    when: 'Release thread-local style resources after method.',
    processor: 'AspectJAfterAdvice in advisor chain.',
    example: '@After("serviceLayer()")\nvoid after() { MDC.clear(); }',
    interviewImportance: 'medium',
    versionNotes: 'Unlike @AfterReturning — runs on exception too.',
    proxyRelevant: 'Proxy chain.',
    lifecyclePhase: 'After method completes (finally style).',
    commonMistakes: ['Confusing @After with @AfterReturning'],
    interviewTraps: ['@After vs @AfterReturning vs @AfterThrowing'],
    relatedAnnotations: ['@AfterReturning', '@AfterThrowing'],
    memory: 'AFTER = finally-style advice after method.',
  },
  {
    id: 'after-returning',
    annotation: '@AfterReturning',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.AfterReturning',
    elementType: 'METHOD',
    what: 'After returning advice runs after successful method return with optional binding to return value.',
    why: 'Metrics on success path, audit successful outcomes.',
    when: 'Record payment success metrics.',
    processor: 'AfterReturningAdvice adapter — not run on exception.',
    example: '@AfterReturning(pointcut="serviceLayer()", returning="result")\nvoid ok(Object result) {}',
    interviewImportance: 'high',
    versionNotes: 'returning attribute must match parameter name/type.',
    proxyRelevant: 'Proxy chain on success path.',
    lifecyclePhase: 'After normal return.',
    commonMistakes: ['Wrong returning parameter name', 'Expecting run on exception'],
    interviewTraps: ['Only on successful return'],
    relatedAnnotations: ['@AfterThrowing', '@Around'],
    memory: 'AFTERRETURNING = advice after normal return.',
  },
  {
    id: 'after-throwing',
    annotation: '@AfterThrowing',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.AfterThrowing',
    elementType: 'METHOD',
    what: 'After throwing advice runs when matched method throws — can bind exception type.',
    why: 'Error metrics, exception audit.',
    when: 'Log and meter specific business exceptions.',
    processor: 'ThrowsAdvice / AspectJAfterThrowingAdvice.',
    example: '@AfterThrowing(pointcut="serviceLayer()", throwing="ex")\nvoid err(Exception ex) {}',
    interviewImportance: 'high',
    versionNotes: 'throwing attribute binds exception parameter.',
    proxyRelevant: 'Proxy chain on exceptional path.',
    lifecyclePhase: 'When matched method throws.',
    commonMistakes: ['Too broad throwing type catches everything', 'Swallowing exception incorrectly'],
    interviewTraps: ['Exception handler vs @AfterThrowing'],
    relatedAnnotations: ['@AfterReturning', '@Around'],
    memory: 'AFTERTHROWING = advice when method throws.',
  },
  {
    id: 'around',
    annotation: '@Around',
    family: 'aop',
    module: 'aspectjweaver',
    javaPackage: 'org.aspectj.lang.annotation.Around',
    elementType: 'METHOD',
    what: 'Around advice wraps method — controls proceed(), return value, and exception handling.',
    why: 'Most powerful advice — timing, retry, transaction-like custom boundaries.',
    when: 'Metrics timing, retry wrappers, authorization gate with proceed().',
    processor: 'MethodInterceptor around ProceedingJoinPoint.proceed().',
    example: '@Around("serviceLayer()")\npublic Object around(ProceedingJoinPoint pjp) throws Throwable {\n  return pjp.proceed();\n}',
    interviewImportance: 'must',
    versionNotes: 'Must call proceed() or skip target method.',
    proxyRelevant: 'Full proxy wrap.',
    lifecyclePhase: 'Surrounds target invocation.',
    commonMistakes: ['Forgetting proceed()', 'Blocking retry on hot path'],
    interviewTraps: ['@Around most powerful — controls proceed'],
    relatedAnnotations: ['@Before', '@Transactional'],
    memory: 'AROUND = wrap call; must invoke proceed().',
  },
  {
    id: 'enable-transaction-management',
    annotation: '@EnableTransactionManagement',
    family: 'transaction',
    module: 'spring-tx',
    javaPackage: 'org.springframework.transaction.annotation.EnableTransactionManagement',
    elementType: 'TYPE',
    what: 'Enables @Transactional processing — TransactionInterceptor advisors and transaction infrastructure.',
    why: 'Without it @Transactional is ignored in plain Spring (Boot starters auto-enable).',
    when: 'Explicit TX in non-Boot or custom isolation from Boot auto-config.',
    processor: 'TransactionManagementConfigurationSelector imports TX advisor infrastructure.',
    example: '@EnableTransactionManagement(proxyTargetClass = true)\n@Configuration class TxConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: spring-boot-starter-jdbc/jpa enables automatically.',
    proxyRelevant: 'Creates transactional proxies for advised beans.',
    lifecyclePhase: 'Advisor registration at refresh.',
    commonMistakes: ['Missing PlatformTransactionManager bean', 'mode=ASPECTJ for compile-time weaving rare'],
    interviewTraps: ['@EnableTransactionManagement required for @Transactional'],
    relatedAnnotations: ['@Transactional', '@EnableAspectJAutoProxy'],
    memory: 'ENABLETXMANAGEMENT = register TransactionInterceptor.',
  },
  {
    id: 'transactional',
    annotation: '@Transactional',
    family: 'transaction',
    module: 'spring-tx',
    javaPackage: 'org.springframework.transaction.annotation.Transactional',
    elementType: 'TYPE, METHOD',
    what: 'Declares transactional boundary on class or method — rollback, propagation, isolation, readOnly.',
    why: 'Atomic business operations with declarative TX management.',
    when: 'Service layer database operations.',
    processor: 'TransactionInterceptor advisor + PlatformTransactionManager.',
    example: '@Transactional(rollbackFor = BusinessException.class)\npublic Order place(Order o) {}',
    interviewImportance: 'must',
    versionNotes: 'Boot 3: jakarta.persistence if JPA; self-invocation skips proxy.',
    proxyRelevant: 'Yes — TX applied via AOP proxy (default).',
    lifecyclePhase: 'Around advised method via TransactionInterceptor.',
    commonMistakes: ['Private @Transactional not advised', 'Self-invocation no TX', 'Checked exception no rollback default'],
    interviewTraps: ['Self-invocation TX trap — top interview'],
    relatedAnnotations: ['@EnableTransactionManagement', '@TransactionalEventListener'],
    memory: 'TRANSACTIONAL = TX interceptor on proxy path.',
  },
  {
    id: 'transactional-event-listener',
    annotation: '@TransactionalEventListener',
    family: 'transaction',
    module: 'spring-tx',
    javaPackage: 'org.springframework.transaction.event.TransactionalEventListener',
    elementType: 'METHOD',
    what: 'Event listener invoked in specific transaction phase (AFTER_COMMIT default) relative to publisher TX.',
    why: 'Reliable side effects after successful commit — outbox, notifications.',
    when: 'Post-commit email, Kafka publish after DB commit.',
    processor: 'TransactionalEventListenerMethodProcessor registers ApplicationListener with TX phase binding.',
    example: '@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)\nvoid on(OrderPlaced e) {}',
    interviewImportance: 'high',
    versionNotes: 'Falls back to after commit if no TX active (configurable).',
    proxyRelevant: 'Listener invoked via event multicaster — not method proxy on business bean.',
    lifecyclePhase: 'After transaction phase transition.',
    commonMistakes: ['Listener runs before commit if phase wrong', 'AFTER_COMMIT with no TX — fallback behavior'],
    interviewTraps: ['vs plain @EventListener timing'],
    relatedAnnotations: ['@EventListener', '@Transactional'],
    memory: 'TRANSACTIONALEVENTLISTENER = event tied to TX phase.',
  },
  {
    id: 'enable-caching',
    annotation: '@EnableCaching',
    family: 'cache',
    module: 'spring-context',
    javaPackage: 'org.springframework.cache.annotation.EnableCaching',
    elementType: 'TYPE',
    what: 'Enables @Cacheable/@CacheEvict processing — CacheInterceptor advisors.',
    why: 'Without it cache annotations are no-ops.',
    when: 'Any annotated caching in Boot/non-Boot apps.',
    processor: 'CachingConfigurationSelector imports cache advisor infrastructure.',
    example: '@EnableCaching\n@Configuration class CacheConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Boot auto-configures when cache starter present.',
    proxyRelevant: 'CacheInterceptor creates advised proxies.',
    lifecyclePhase: 'Advisor registration.',
    commonMistakes: ['No CacheManager bean — failure or no-op depending setup', 'Wrong cache manager for multiple caches'],
    interviewTraps: ['@EnableCaching required for @Cacheable'],
    relatedAnnotations: ['@Cacheable', '@CacheConfig'],
    memory: 'ENABLECACHING = register CacheInterceptor.',
  },
  {
    id: 'cacheable',
    annotation: '@Cacheable',
    family: 'cache',
    module: 'spring-context',
    javaPackage: 'org.springframework.cache.annotation.Cacheable',
    elementType: 'TYPE, METHOD',
    what: 'Caches method return value keyed by cache names and key SpEL — skip method if cache hit.',
    why: 'Reduce repeated expensive reads.',
    when: 'Read-heavy reference data, product catalog lookups.',
    processor: 'CacheInterceptor → CacheOperationSource → CacheManager.get.',
    example: '@Cacheable(cacheNames = "orders", key = "#id")\npublic Order find(UUID id) {}',
    interviewImportance: 'must',
    versionNotes: 'Self-invocation bypasses cache proxy.',
    proxyRelevant: 'Yes — cache advice via AOP proxy.',
    lifecyclePhase: 'Around advised method — may skip proceed on hit.',
    commonMistakes: ['Caching mutable objects', 'Null results not cached by default (@Cacheable unless)'],
    interviewTraps: ['Cache key SpEL interview'],
    relatedAnnotations: ['@CacheEvict', '@EnableCaching'],
    memory: 'CACHEABLE = cache hit skips method body.',
  },
  {
    id: 'cache-put',
    annotation: '@CachePut',
    family: 'cache',
    module: 'spring-context',
    javaPackage: 'org.springframework.cache.annotation.CachePut',
    elementType: 'TYPE, METHOD',
    what: 'Always executes method and updates cache with return value.',
    why: 'Update cache after write without skipping method execution.',
    when: 'After updateOrder always refresh cache entry.',
    processor: 'CacheInterceptor put after method proceeds.',
    example: '@CachePut(cacheNames = "orders", key = "#order.id")\npublic Order update(Order order) {}',
    interviewImportance: 'high',
    versionNotes: 'Always runs target method.',
    proxyRelevant: 'Proxy advised.',
    lifecyclePhase: 'After method execution — cache put.',
    commonMistakes: ['Confusing with @Cacheable', 'Wrong key expression — stale wrong entry'],
    interviewTraps: ['@CachePut always invokes method'],
    relatedAnnotations: ['@Cacheable', '@CacheEvict'],
    memory: 'CACHEPUT = always run + update cache.',
  },
  {
    id: 'cache-evict',
    annotation: '@CacheEvict',
    family: 'cache',
    module: 'spring-context',
    javaPackage: 'org.springframework.cache.annotation.CacheEvict',
    elementType: 'TYPE, METHOD',
    what: 'Removes entries from cache — before or after method via allEntries/key.',
    why: 'Invalidate stale data on writes or deletes.',
    when: 'Evict order cache on delete.',
    processor: 'CacheInterceptor evict phase before/after invocation.',
    example: '@CacheEvict(cacheNames = "orders", key = "#id")\npublic void delete(UUID id) {}',
    interviewImportance: 'high',
    versionNotes: 'allEntries=true clears entire cache name.',
    proxyRelevant: 'Proxy advised.',
    lifecyclePhase: 'Before or after advised method per attribute.',
    commonMistakes: ['Evict wrong key — stale data remains', 'allEntries on large cache — latency spike'],
    interviewTraps: ['beforeInvocation=true evicts even if method fails'],
    relatedAnnotations: ['@Caching', '@Cacheable'],
    memory: 'CACHEEVICT = remove cache entries on method.',
  },
  {
    id: 'caching',
    annotation: '@Caching',
    family: 'cache',
    module: 'spring-context',
    javaPackage: 'org.springframework.cache.annotation.Caching',
    elementType: 'TYPE, METHOD',
    what: 'Groups multiple @Cacheable/@CachePut/@CacheEvict on one method.',
    why: 'Complex cache update/evict on single operation.',
    when: 'Update multiple cache regions on one write.',
    processor: 'CacheInterceptor processes combined cache operations.',
    example: '@Caching(evict = {@CacheEvict("a"), @CacheEvict("b")})\npublic void refresh() {}',
    interviewImportance: 'high',
    versionNotes: 'Composable cache annotations container.',
    proxyRelevant: 'Proxy advised.',
    lifecyclePhase: 'Single method multiple cache ops.',
    commonMistakes: ['Order of operations matters', 'Duplicate keys across ops'],
    interviewTraps: ['@Caching bundles cache annotations'],
    relatedAnnotations: ['@Cacheable', '@CacheEvict'],
    memory: 'CACHING = multiple cache ops one method.',
  },
  {
    id: 'cache-config',
    annotation: '@CacheConfig',
    family: 'cache',
    module: 'spring-context',
    javaPackage: 'org.springframework.cache.annotation.CacheConfig',
    elementType: 'TYPE',
    what: 'Class-level default cacheNames and keyGenerator for @Cacheable methods in class.',
    why: 'Avoid repeating cacheNames on every method.',
    when: 'Service class using one primary cache region.',
    processor: 'CacheAnnotationParser reads class-level defaults.',
    example: '@CacheConfig(cacheNames = "products")\n@Service class ProductService {}',
    interviewImportance: 'medium',
    versionNotes: 'Method-level annotations override defaults.',
    proxyRelevant: 'Proxy advised on methods.',
    lifecyclePhase: 'Metadata for cache operations.',
    commonMistakes: ['Assuming @CacheConfig registers CacheManager'],
    interviewTraps: ['Class-level cache defaults'],
    relatedAnnotations: ['@Cacheable', '@EnableCaching'],
    memory: 'CACHECONFIG = default cache names for class.',
  },
  {
    id: 'enable-async',
    annotation: '@EnableAsync',
    family: 'async',
    module: 'spring-context',
    javaPackage: 'org.springframework.scheduling.annotation.EnableAsync',
    elementType: 'TYPE',
    what: 'Enables @Async method processing — AsyncAnnotationBeanPostProcessor.',
    why: 'Without it @Async runs synchronously.',
    when: 'Async notifications, offload from HTTP/Kafka threads.',
    processor: 'AsyncConfigurationRegistrar registers ABPP.',
    example: '@EnableAsync\n@Configuration class AsyncConfig {}',
    interviewImportance: 'must',
    versionNotes: 'Configure TaskExecutor for production pools.',
    proxyRelevant: '@Async methods proxied for async submission.',
    lifecyclePhase: 'ABPP at refresh.',
    commonMistakes: ['No @EnableAsync — silent sync', 'Default SimpleAsyncTaskExecutor per thread in Boot'],
    interviewTraps: ['ThreadLocal not copied unless TaskDecorator'],
    relatedAnnotations: ['@Async', '@EnableScheduling'],
    memory: 'ENABLEASYNC = ABPP proxies @Async methods.',
  },
  {
    id: 'async',
    annotation: '@Async',
    family: 'async',
    module: 'spring-context',
    javaPackage: 'org.springframework.scheduling.annotation.Async',
    elementType: 'TYPE, METHOD',
    what: 'Method runs asynchronously on TaskExecutor — caller gets Future/CompletableFuture or void.',
    why: 'Non-blocking offload of work.',
    when: 'Send email, audit log async from request thread.',
    processor: 'AsyncAnnotationAdvisor → AnnotationAsyncExecutionInterceptor.',
    example: '@Async\npublic CompletableFuture<Result> process() {}',
    interviewImportance: 'must',
    versionNotes: 'Self-invocation runs sync.',
    proxyRelevant: 'Yes — async advisor proxy.',
    lifecyclePhase: 'TaskExecutor worker thread.',
    commonMistakes: ['@Async on private method not advised', 'Lost SecurityContext/MDC on worker'],
    interviewTraps: ['Self-invocation async trap'],
    relatedAnnotations: ['@EnableAsync', '@Transactional'],
    memory: 'ASYNC = proxy submits to TaskExecutor.',
  },
  {
    id: 'enable-scheduling',
    annotation: '@EnableScheduling',
    family: 'schedule',
    module: 'spring-context',
    javaPackage: 'org.springframework.scheduling.annotation.EnableScheduling',
    elementType: 'TYPE',
    what: 'Enables @Scheduled method execution via ScheduledAnnotationBeanPostProcessor.',
    why: 'Periodic tasks without external scheduler.',
    when: 'Cron jobs, fixedRate polling in app.',
    processor: 'SchedulingConfiguration registers scheduled task registrar.',
    example: '@EnableScheduling\n@SpringBootApplication class App {}',
    interviewImportance: 'must',
    versionNotes: 'Distributed systems prefer external scheduler — know tradeoffs.',
    proxyRelevant: 'Scheduled methods invoked on scheduler thread — not full AOP proxy unless also advised.',
    lifecyclePhase: 'Task registrar at refresh.',
    commonMistakes: ['Multiple instances run duplicate schedules — need distributed lock', '@Scheduled on missing @EnableScheduling'],
    interviewTraps: ['@EnableScheduling vs external Quartz'],
    relatedAnnotations: ['@Scheduled', '@Schedules'],
    memory: 'ENABLESCHEDULING = register scheduled task infrastructure.',
  },
  {
    id: 'scheduled',
    annotation: '@Scheduled',
    family: 'schedule',
    module: 'spring-context',
    javaPackage: 'org.springframework.scheduling.annotation.Scheduled',
    elementType: 'METHOD',
    what: 'Schedules method execution — fixedRate, fixedDelay, cron, zone.',
    why: 'In-process periodic execution.',
    when: 'Nightly cleanup, heartbeat, metrics push.',
    processor: 'ScheduledAnnotationBeanPostProcessor registers ScheduledTask.',
    example: '@Scheduled(cron = "0 0 * * * *")\npublic void cleanup() {}',
    interviewImportance: 'must',
    versionNotes: 'cron uses six fields in Spring (seconds).',
    proxyRelevant: 'Invoked by scheduler — concurrent runs need careful config.',
    lifecyclePhase: 'Scheduler thread pool.',
    commonMistakes: ['cron typo — silent wrong schedule', 'long task blocks fixedRate semantics'],
    interviewTraps: ['fixedRate vs fixedDelay interview'],
    relatedAnnotations: ['@Schedules', '@EnableScheduling'],
    memory: 'SCHEDULED = cron/fixedRate/fixedDelay invocation.',
  },
  {
    id: 'schedules',
    annotation: '@Schedules',
    family: 'schedule',
    module: 'spring-context',
    javaPackage: 'org.springframework.scheduling.annotation.Schedules',
    elementType: 'METHOD',
    what: 'Container for multiple @Scheduled definitions on one method — Spring Framework 6.1+.',
    why: 'Multiple cron triggers for same method without duplicate methods.',
    when: 'Run job at two schedules, business + off-hours.',
    processor: 'ScheduledAnnotationBeanPostProcessor registers multiple tasks for method.',
    example: '@Schedules({@Scheduled(cron="0 0 9 * * *"), @Scheduled(cron="0 0 18 * * *")})\npublic void sync() {}',
    interviewImportance: 'medium',
    versionNotes: 'Added in Spring Framework 6.1.',
    proxyRelevant: 'Same scheduler infrastructure.',
    lifecyclePhase: 'Multiple scheduled tasks one method.',
    commonMistakes: ['Requires SF 6.1+', 'Overlapping runs if method long-running'],
    interviewTraps: ['@Schedules vs multiple methods'],
    relatedAnnotations: ['@Scheduled'],
    memory: 'SCHEDULES = multiple @Scheduled on one method (SF 6.1+).',
  },
  {
    id: 'event-listener',
    annotation: '@EventListener',
    family: 'events',
    module: 'spring-context',
    javaPackage: 'org.springframework.context.event.EventListener',
    elementType: 'METHOD',
    what: 'Registers method as ApplicationListener for event type — invoked by ApplicationEventMulticaster.',
    why: 'In-process domain events decoupling.',
    when: 'React to OrderPlaced, cache warm on ContextRefreshedEvent.',
    processor: 'EventListenerMethodProcessor registers listener adapter on context refresh.',
    example: '@EventListener\npublic void on(OrderPlaced event) {}',
    interviewImportance: 'high',
    versionNotes: 'condition SpEL attribute filters events.',
    proxyRelevant: 'Direct invocation on multicaster thread — not proxy unless @Async @Transactional on listener.',
    lifecyclePhase: 'When event published to context.',
    commonMistakes: ['Listener exception affects publisher depending on multicaster', 'Wrong event type parameter — not invoked'],
    interviewTraps: ['@EventListener vs @TransactionalEventListener'],
    relatedAnnotations: ['@TransactionalEventListener', '@EnableAsync'],
    memory: 'EVENTLISTENER = method listens for ApplicationEvent.',
  },
];

export const INVENTORY_CORE_COUNT = INVENTORY_CORE.length;
