import type {InventoryModuleEntry} from './types';

const STACK = 'Boot 3 / SF 6';

/** Compact inventory rows for MVC/Web, WebFlux, Validation, Security, Data, Kafka, Test, Actuator, Integration/Batch/Cloud. */
export const INVENTORY_MODULES: InventoryModuleEntry[] = [
  // ── MVC / Web ──────────────────────────────────────────────────────────────
  {
    id: 'request-mapping',
    annotation: '@RequestMapping',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Base mapping annotation on class or method: path/value, method, params, headers, consumes, produces.',
    processor: 'RequestMappingHandlerMapping.detectHandlerMethods at startup; RequestMappingInfo match per request.',
    proxy: 'None — metadata on controller; controller may still be proxied for TX/security.',
    phase: 'Startup registration; per-request HandlerMapping lookup.',
    when: 'Class-level path prefix; use composed @GetMapping etc. for HTTP verbs on methods.',
    trap: 'Method without HTTP method matches all verbs; ambiguous mapping if paths collide.',
    memory: '@RequestMapping → RequestMappingHandlerMapping → HandlerMethod.',
  },
  {
    id: 'get-mapping',
    annotation: '@GetMapping',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Composed @RequestMapping(method = GET) for read/idempotent HTTP GET handlers.',
    processor: 'Same as @RequestMapping — RequestMappingHandlerMapping + RequestMappingHandlerAdapter.',
    proxy: 'None on mapping; stereotype/controller proxies separate.',
    phase: 'Startup mapping; runtime dispatch.',
    when: 'All read endpoints; prefer over @RequestMapping(method=GET).',
    trap: 'Interview flow: DispatcherServlet → HandlerMapping → HandlerAdapter → converter.',
    memory: '@GetMapping = GET-only RequestMappingInfo.',
  },
  {
    id: 'post-mapping',
    annotation: '@PostMapping',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Composed @RequestMapping(method = POST) for create/non-idempotent writes.',
    processor: 'RequestMappingHandlerMapping registers POST-only RequestMappingInfo.',
    proxy: 'None.',
    phase: 'Startup; per-request.',
    when: 'Create resources, commands, non-idempotent actions.',
    trap: 'POST without @RequestBody still binds form fields via @RequestParam.',
    memory: '@PostMapping = POST verb mapping.',
  },
  {
    id: 'put-mapping',
    annotation: '@PutMapping',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Composed @RequestMapping(method = PUT) for full resource replacement.',
    processor: 'RequestMappingHandlerMapping.',
    proxy: 'None.',
    phase: 'Startup; per-request.',
    when: 'Replace entire resource representation at known URI.',
    trap: 'PUT vs PATCH semantics — full replace vs partial update.',
    memory: '@PutMapping = full replace HTTP PUT.',
  },
  {
    id: 'patch-mapping',
    annotation: '@PatchMapping',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Composed @RequestMapping(method = PATCH) for partial updates.',
    processor: 'RequestMappingHandlerMapping.',
    proxy: 'None.',
    phase: 'Startup; per-request.',
    when: 'JSON Merge Patch or partial field updates.',
    trap: 'Clients sending PATCH as POST workaround — document API contract.',
    memory: '@PatchMapping = partial update verb.',
  },
  {
    id: 'delete-mapping',
    annotation: '@DeleteMapping',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Composed @RequestMapping(method = DELETE) for resource removal.',
    processor: 'RequestMappingHandlerMapping.',
    proxy: 'None.',
    phase: 'Startup; per-request.',
    when: 'Delete by id; return 204 No Content or 404.',
    trap: 'DELETE with body — discouraged; some clients/proxies strip body.',
    memory: '@DeleteMapping = DELETE verb mapping.',
  },
  {
    id: 'path-variable',
    annotation: '@PathVariable',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds URI template variable {name} from matched path to method parameter.',
    processor: 'PathVariableMethodArgumentResolver via RequestMappingHandlerAdapter.',
    proxy: 'None — argument resolution layer.',
    phase: 'Per-request before handler invoke.',
    when: 'Resource identity in path (/orders/{id}).',
    trap: 'Param name mismatch without -parameters flag — use @PathVariable("id").',
    memory: 'PathVariableMethodArgumentResolver + ConversionService.',
  },
  {
    id: 'request-param',
    annotation: '@RequestParam',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds query string, form field, or multipart simple part to parameter.',
    processor: 'RequestParamMethodArgumentResolver.',
    proxy: 'None.',
    phase: 'Per-request.',
    when: 'Filters, pagination (?page=0&size=20), optional flags.',
    trap: 'defaultValue implies required=false; contrast @PathVariable for identity.',
    memory: '@RequestParam = query/form; not path segment.',
  },
  {
    id: 'request-header',
    annotation: '@RequestHeader',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds HTTP request header value to method parameter.',
    processor: 'RequestHeaderMethodArgumentResolver.',
    proxy: 'None.',
    phase: 'Per-request.',
    when: 'Authorization passthrough, custom headers (X-Request-Id), If-Match.',
    trap: 'Header names case-insensitive; required=false for optional headers.',
    memory: '@RequestHeader = HTTP header → param.',
  },
  {
    id: 'cookie-value',
    annotation: '@CookieValue',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds cookie value by name to method parameter.',
    processor: 'ServletCookieValueMethodArgumentResolver.',
    proxy: 'None.',
    phase: 'Per-request.',
    when: 'Legacy session cookies; prefer HttpOnly Secure cookies set server-side.',
    trap: 'Cookie not sent on cross-site requests without SameSite=None.',
    memory: '@CookieValue reads named cookie from request.',
  },
  {
    id: 'request-body',
    annotation: '@RequestBody',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Deserializes HTTP body to object via HttpMessageConverter (Jackson JSON).',
    processor: 'RequestResponseBodyMethodProcessor + MappingJackson2HttpMessageConverter.',
    proxy: 'None.',
    phase: 'Per-request after Content-Type negotiation.',
    when: 'POST/PUT/PATCH JSON/XML payloads; pair with @Valid.',
    trap: 'Missing @Valid — jakarta constraints ignored; HttpMessageNotReadableException on bad JSON.',
    memory: '@RequestBody = converter read; add @Valid.',
  },
  {
    id: 'response-body',
    annotation: '@ResponseBody',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Serializes method return value to response body instead of view name.',
    processor: 'RequestResponseBodyMethodProcessor writeWithMessageConverters.',
    proxy: 'None.',
    phase: 'Post-handler return value handling.',
    when: 'REST JSON APIs; @RestController includes @ResponseBody on class.',
    trap: '@Controller without @ResponseBody returns view name string.',
    memory: '@RestController = @Controller + @ResponseBody.',
  },
  {
    id: 'response-status',
    annotation: '@ResponseStatus',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Sets HTTP status on method return or exception class (code/reason).',
    processor: 'ResponseStatusExceptionResolver or ServletInvocableHandlerMethod for methods.',
    proxy: 'None.',
    phase: 'Return handling or exception resolution.',
    when: 'Simple 404/201 without ResponseEntity wrapper.',
    trap: '@ResponseStatus on exception less flexible than @ExceptionHandler.',
    memory: '@ResponseStatus sets status without ResponseEntity.',
  },
  {
    id: 'cross-origin',
    annotation: '@CrossOrigin',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Enables CORS for controller/handler: origins, methods, headers, credentials.',
    processor: 'RequestMappingHandlerMapping adds CrossOrigin metadata; CorsInterceptor/CorsFilter.',
    proxy: 'None.',
    phase: 'Pre-handler CORS check on cross-origin requests.',
    when: 'Browser SPA calling API on different origin; prefer global CorsConfigurationSource for APIs.',
    trap: 'CORS is browser-only — does not replace auth; credentials require explicit origin not *.',
    memory: '@CrossOrigin = handler-level CORS metadata.',
  },
  {
    id: 'matrix-variable',
    annotation: '@MatrixVariable',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds matrix URI variables (path segments with key=value pairs).',
    processor: 'MatrixVariableMethodArgumentResolver; requires enableMatrixVariables on mapping handler.',
    proxy: 'None.',
    phase: 'Per-request.',
    when: 'Rare REST matrix URIs (/orders;status=open;region=eu).',
    trap: 'Almost never used in production APIs — know it exists for completeness.',
    memory: '@MatrixVariable = matrix URI key=value segments.',
  },
  {
    id: 'request-attribute',
    annotation: '@RequestAttribute',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds request-scoped attribute set by filter/interceptor to parameter.',
    processor: 'RequestAttributeMethodArgumentResolver.',
    proxy: 'None.',
    phase: 'Per-request after filters.',
    when: 'Filter sets attribute; controller reads without HttpServletRequest.',
    trap: 'Attribute missing if filter order wrong or path skipped filter.',
    memory: '@RequestAttribute = request attribute from filter chain.',
  },
  {
    id: 'session-attribute',
    annotation: '@SessionAttribute',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds existing session attribute to method parameter.',
    processor: 'SessionAttributeMethodArgumentResolver.',
    proxy: 'None.',
    phase: 'Per-request with HTTP session.',
    when: 'Stateful MVC apps; avoid in stateless JWT APIs.',
    trap: 'SessionCreationException if no session and required=true.',
    memory: '@SessionAttribute reads HttpSession attribute.',
  },
  {
    id: 'request-part',
    annotation: '@RequestPart',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Binds multipart part (file or JSON part) with own Content-Type.',
    processor: 'RequestPartMethodArgumentResolver + MultipartResolver.',
    proxy: 'None.',
    phase: 'Per-request multipart parsing.',
    when: 'multipart/form-data with file + JSON metadata part.',
    trap: 'Contrast @RequestParam MultipartFile — @RequestPart for typed parts with Content-Type.',
    memory: '@RequestPart = multipart part with converter.',
  },
  {
    id: 'exception-handler',
    annotation: '@ExceptionHandler',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Maps thrown exceptions to handler method returning error response.',
    processor: 'ExceptionHandlerExceptionResolver in DispatcherServlet resolver chain.',
    proxy: 'Advice bean invoked directly.',
    phase: 'After controller throws.',
    when: 'Global JSON errors via @ControllerAdvice; ProblemDetail in Boot 3.',
    trap: 'Generic Exception handler before specific handlers if @Order wrong.',
    memory: '@ExceptionHandler → ExceptionHandlerExceptionResolver.',
  },
  {
    id: 'controller-advice',
    annotation: '@ControllerAdvice',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Global @ExceptionHandler, @InitBinder, @ModelAttribute across controllers.',
    processor: 'ControllerAdviceBean registered with MVC exception/binder infrastructure.',
    proxy: 'Advice is singleton bean.',
    phase: 'Startup scan; per-request for model/binder advice.',
    when: 'Package-scoped global error handling; narrow basePackages.',
    trap: 'Over-broad advice catching actuator errors — scope with basePackages.',
    memory: '@ControllerAdvice = global MVC cross-cut; scope it.',
  },
  {
    id: 'rest-controller-advice',
    annotation: '@RestControllerAdvice',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: '@ControllerAdvice + @ResponseBody on advice method returns.',
    processor: 'Same as @ControllerAdvice; JSON serialization on advice returns.',
    proxy: 'None.',
    phase: 'Startup; exception resolution.',
    when: 'REST APIs returning ProblemDetail/JSON from @ExceptionHandler.',
    trap: '@RestControllerAdvice = @ControllerAdvice + @ResponseBody meta.',
    memory: '@RestControllerAdvice = JSON global advice.',
  },
  {
    id: 'init-binder',
    annotation: '@InitBinder',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Registers WebDataBinder custom editors/formatters for controller binding.',
    processor: 'InitBinderDataBinderFactory from @ControllerAdvice or controller.',
    proxy: 'None.',
    phase: 'Before @ModelAttribute/@RequestParam binding per request.',
    when: 'Custom date parsing, disallow fields on form objects.',
    trap: 'InitBinder on wrong controller — use @ControllerAdvice for global.',
    memory: '@InitBinder configures WebDataBinder per controller/advice.',
  },
  {
    id: 'model-attribute',
    annotation: '@ModelAttribute',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'On method: adds model attribute before handler. On param: binds form/query to object.',
    processor: 'ModelAttributeMethodProcessor / ServletModelAttributeMethodProcessor.',
    proxy: 'None.',
    phase: 'Pre-invoke model population or argument binding.',
    when: 'Form-backed MVC; @ModelAttribute methods in @ControllerAdvice.',
    trap: 'Contrast @RequestBody for JSON vs @ModelAttribute for form binding.',
    memory: '@ModelAttribute = form model bind or shared model method.',
  },
  {
    id: 'valid',
    annotation: '@Valid',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'jakarta.validation',
    what: 'Triggers JSR-380 validation on @RequestBody/@ModelAttribute object graph after binding.',
    processor: 'Hibernate Validator after HttpMessageConverter read or WebDataBinder.',
    proxy: 'None on @Valid itself.',
    phase: 'Pre-handler validation.',
    when: 'Every request DTO with constraint annotations.',
    trap: 'Constraints without @Valid silently ignored; MethodArgumentNotValidException.',
    memory: '@Valid = validate bound object; not method params alone.',
  },
  {
    id: 'validated',
    annotation: '@Validated',
    module: 'mvc-web',
    category: 'Spring MVC',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.validation.annotation',
    what: 'Spring @Validated on class enables method-level validation (params) via AOP.',
    processor: 'MethodValidationPostProcessor + MethodValidationInterceptor.',
    proxy: 'AOP proxy on @Validated class for param constraints.',
    phase: 'Before advised method invoke.',
    when: '@Positive on @PathVariable/@RequestParam; validation groups.',
    trap: '@Validated vs @Valid — different exceptions and mechanisms.',
    memory: '@Validated = Spring method param validation AOP.',
  },

  // ── WebFlux ────────────────────────────────────────────────────────────────
  {
    id: 'webflux-request-mapping',
    annotation: '@RequestMapping (WebFlux)',
    module: 'webflux',
    category: 'Spring WebFlux',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Same annotation family on @RestController in reactive stack; returns Mono/Flux.',
    processor: 'RequestMappingHandlerMapping on DispatcherHandler (reactive); HandlerAdapter invokes reactive return types.',
    proxy: 'None on mapping.',
    phase: 'Startup registration; reactive dispatch per request.',
    when: 'Annotated reactive controllers alongside or instead of RouterFunction.',
    trap: 'Blocking JDBC in WebFlux controller blocks event loop — use bounded elastic or separate service.',
    memory: 'WebFlux @RequestMapping → DispatcherHandler reactive chain.',
  },
  {
    id: 'webflux-annotated-controller',
    annotation: '@RestController (WebFlux)',
    module: 'webflux',
    category: 'Spring WebFlux',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.web.bind.annotation',
    what: 'Annotation-driven reactive controllers returning Mono/Flux; shares MVC annotation model.',
    processor: 'DispatcherHandler + InvocableHandlerMethod with reactive adapters.',
    proxy: 'None for stereotype.',
    phase: 'Per-request reactive pipeline.',
    when: 'Familiar MVC style on Netty; good for CRUD APIs.',
    trap: 'Do not mix blocking calls — schedule on Scheduler if needed.',
    memory: 'WebFlux @RestController = reactive annotated controllers.',
  },
  {
    id: 'router-function',
    annotation: 'RouterFunction',
    module: 'webflux',
    category: 'Spring WebFlux',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.web.reactive.function.server',
    what: 'Functional routing: RouterFunctions.route() maps paths to HandlerFunction without annotations.',
    processor: 'RouterFunctionMapping in DispatcherHandler; no @RequestMapping metadata.',
    proxy: 'None.',
    phase: 'Startup bean registration; per-request route match.',
    when: 'Functional style, lambda handlers, programmatic routes, testing clarity.',
    trap: 'Interview contrast: annotated @RestController vs RouterFunction — same DispatcherHandler, different mapping.',
    memory: 'RouterFunction = functional WebFlux routing alternative.',
  },
  {
    id: 'webflux-valid',
    annotation: '@Valid (WebFlux)',
    module: 'webflux',
    category: 'Spring WebFlux',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.validation',
    what: 'Validation on @RequestBody Mono<Dto> or sync body in WebFlux controllers.',
    processor: 'WebFlux ValidatingHandlerMethodValidator (Boot 3.2+) or manual validate in service.',
    proxy: 'None.',
    phase: 'Before handler in reactive chain.',
    when: 'Reactive APIs with jakarta validation constraints.',
    trap: 'Validation errors map to 400 via WebExceptionHandler or @ControllerAdvice.',
    memory: 'WebFlux validates @RequestBody like MVC with reactive adapters.',
  },

  // ── Jakarta Validation ─────────────────────────────────────────────────────
  {
    id: 'constraint',
    annotation: '@Constraint',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.validation',
    what: 'Meta-annotation linking custom constraint to ConstraintValidator implementation.',
    processor: 'ConstraintValidatorFactory (Spring-aware in Boot) validates at bind/validate call.',
    proxy: 'None.',
    phase: 'Validation phase after binding.',
    when: 'Domain-specific rules (valid IBAN, tax id) as reusable constraint.',
    trap: 'Validator bean injection requires SpringConstraintValidatorFactory.',
    memory: '@Constraint links annotation to ConstraintValidator.',
  },
  {
    id: 'constraint-composition',
    annotation: 'Constraint composition',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.validation',
    what: '@ConstraintComposition or composing annotations (@NotBlank = @NotNull + @Size) stacking constraints.',
    processor: 'Hibernate Validator expands composed constraints in metadata.',
    proxy: 'None.',
    phase: 'Validator bootstrap metadata.',
    when: 'Reusable constraint bundles; custom stereotypes for validation.',
    trap: 'Composed constraints inherit groups from composing annotation.',
    memory: 'Compose constraints via meta-annotations on custom annotations.',
  },
  {
    id: 'validation-groups',
    annotation: 'Validation groups',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.validation',
    what: 'Group interfaces (Create.class, Update.class) on constraints; activated via @Validated(Group.class).',
    processor: 'Validator.validate(object, group) or Spring @Validated groups on class.',
    proxy: '@Validated enables group-aware method validation.',
    phase: 'Per validation invocation.',
    when: 'Create requires all fields; update allows partial — different group sets.',
    trap: 'Default group Default.class when no groups specified on constraint.',
    memory: 'Groups via @Validated(Create.class) + constraint groups=.',
  },
  {
    id: 'not-null',
    annotation: '@NotNull',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'Element must not be null (reference); does not reject empty string.',
    processor: 'NotNullValidator in Hibernate Validator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Required reference fields on DTOs.',
    trap: '@NotNull on String allows ""; use @NotBlank for strings.',
    memory: '@NotNull ≠ not empty string.',
  },
  {
    id: 'not-blank',
    annotation: '@NotBlank',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'String must be non-null and trimmed length > 0.',
    processor: 'NotBlankValidator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Required string fields (names, codes).',
    trap: 'Whitespace-only fails; contrast @NotEmpty (any char).',
    memory: '@NotBlank = non-null non-empty trimmed string.',
  },
  {
    id: 'size',
    annotation: '@Size',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'Collection/array/String length between min and max.',
    processor: 'SizeValidatorForCollection/Array/CharSequence.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Password length, list size caps.',
    trap: 'Size on String is char length not byte length.',
    memory: '@Size min/max on string/collection length.',
  },
  {
    id: 'min',
    annotation: '@Min',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'Numeric value must be >= min (long).',
    processor: 'MinValidatorForNumber/CharSequence.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Minimum quantity, age floors.',
    trap: 'Use @DecimalMin for BigDecimal with inclusive flag.',
    memory: '@Min numeric lower bound.',
  },
  {
    id: 'max',
    annotation: '@Max',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'Numeric value must be <= max (long).',
    processor: 'MaxValidator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Pagination size caps, rate limits on input.',
    trap: 'Pair with @Min for range validation.',
    memory: '@Max numeric upper bound.',
  },
  {
    id: 'email',
    annotation: '@Email',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'String must be well-formed email (regex per spec).',
    processor: 'EmailValidator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Email fields on registration DTOs.',
    trap: 'Spec regex is permissive — not deliverability check.',
    memory: '@Email format check only.',
  },
  {
    id: 'pattern',
    annotation: '@Pattern',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'String must match regex regexp attribute.',
    processor: 'PatternValidator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Phone codes, SKU formats, ISO country codes.',
    trap: 'Invalid regex fails at validator factory init.',
    memory: '@Pattern regexp on String.',
  },
  {
    id: 'positive',
    annotation: '@Positive',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'Number must be strictly positive (> 0).',
    processor: 'PositiveValidator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Amounts, counts that cannot be zero.',
    trap: '@Positive vs @PositiveOrZero — zero allowed in latter.',
    memory: '@Positive strictly > 0.',
  },
  {
    id: 'negative',
    annotation: '@Negative',
    module: 'validation',
    category: 'Jakarta Validation',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'jakarta.validation.constraints',
    what: 'Number must be strictly negative (< 0).',
    processor: 'NegativeValidator.',
    proxy: 'None.',
    phase: 'Validation.',
    when: 'Rare domain signs (adjustment deltas); mostly use @Positive on magnitude.',
    trap: 'Interview niche — know Positive/Negative symmetry.',
    memory: '@Negative strictly < 0.',
  },

  // ── Security ───────────────────────────────────────────────────────────────
  {
    id: 'enable-web-security',
    annotation: '@EnableWebSecurity',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.security.config.annotation.web.configuration',
    what: 'Enables Spring Security web filter chain configuration.',
    processor: 'WebSecurityConfiguration @Import; FilterChainProxy + SecurityFilterChain beans.',
    proxy: 'Filters before DispatcherServlet; not method AOP.',
    phase: 'Context refresh; per-request filter chain.',
    when: 'Custom SecurityFilterChain @Bean; JWT, form login, authorizeHttpRequests.',
    trap: 'WebSecurityConfigurerAdapter removed — use @Bean SecurityFilterChain.',
    memory: '@EnableWebSecurity → FilterChainProxy before MVC.',
  },
  {
    id: 'enable-method-security',
    annotation: '@EnableMethodSecurity',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.security.config.annotation.method.configuration',
    what: 'Enables @PreAuthorize/@PostAuthorize/@Secured method security (replaces @EnableGlobalMethodSecurity).',
    processor: 'MethodSecurityConfiguration; AuthorizationManagerBeforeMethodInterceptor.',
    proxy: 'AOP on secured beans — self-invocation bypasses.',
    phase: 'Per method invocation.',
    when: 'Service-layer authorization beyond URL rules.',
    trap: 'prePostEnabled=true needed for @PreAuthorize; self-invocation trap.',
    memory: '@EnableMethodSecurity activates method security AOP.',
  },
  {
    id: 'pre-authorize',
    annotation: '@PreAuthorize',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.security.access.prepost',
    what: 'SpEL authorization check before method execution.',
    processor: 'MethodSecurityInterceptor / AuthorizationManagerBeforeMethodInterceptor.',
    proxy: 'Requires proxied bean; external call only.',
    phase: 'Pre-invoke.',
    when: 'Role and argument-based authorization (#accountId).',
    trap: 'hasRole adds ROLE_ prefix; this.secured() bypasses.',
    memory: '@PreAuthorize SpEL before method.',
  },
  {
    id: 'post-authorize',
    annotation: '@PostAuthorize',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.security.access.prepost',
    what: 'SpEL check on method return value after execution.',
    processor: 'AuthorizationManagerAfterMethodInterceptor.',
    proxy: 'AOP proxy required.',
    phase: 'Post-invoke.',
    when: 'Return object must belong to caller (returnObject.owner == auth).',
    trap: 'Method runs even if post-check fails — side effects already happened.',
    memory: '@PostAuthorize checks return value SpEL.',
  },
  {
    id: 'pre-filter',
    annotation: '@PreFilter',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.security.access.prepost',
    what: 'Filters collection argument before method (filterObject SpEL).',
    processor: 'PreFilterAuthorizationMethodInterceptor.',
    proxy: 'AOP proxy.',
    phase: 'Pre-invoke argument mutation.',
    when: 'Service receives list — filter to authorized subset.',
    trap: 'Requires @EnableMethodSecurity(prePostEnabled); collection param only.',
    memory: '@PreFilter filters collection args pre-method.',
  },
  {
    id: 'post-filter',
    annotation: '@PostFilter',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.security.access.prepost',
    what: 'Filters collection return value after method (filterObject SpEL).',
    processor: 'PostFilterAuthorizationMethodInterceptor.',
    proxy: 'AOP proxy.',
    phase: 'Post-invoke return filtering.',
    when: 'Hide unauthorized rows from returned collection.',
    trap: 'Lazy collections may load before filter — perf consideration.',
    memory: '@PostFilter filters collection return.',
  },
  {
    id: 'secured',
    annotation: '@Secured',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.security.access.annotation',
    what: 'Simple role list authorization without SpEL.',
    processor: 'SecuredAuthorizationManager / legacy securedEnabled.',
    proxy: 'AOP proxy.',
    phase: 'Pre-invoke.',
    when: 'Simple ROLE_ADMIN checks; less flexible than @PreAuthorize.',
    trap: 'Requires securedEnabled=true on @EnableMethodSecurity.',
    memory: '@Secured = simple role list check.',
  },
  {
    id: 'roles-allowed',
    annotation: '@RolesAllowed',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.annotation.security',
    what: 'JSR-250 roles allowed on method/class; bridged by Spring Security.',
    processor: 'Jsr250MethodSecurityMetadataSource when jsr250Enabled.',
    proxy: 'AOP proxy.',
    phase: 'Pre-invoke.',
    when: 'Portable JSR-250 style; same semantics as @Secured.',
    trap: 'Enable jsr250Enabled on @EnableMethodSecurity.',
    memory: '@RolesAllowed JSR-250 → Spring Security bridge.',
  },
  {
    id: 'authentication-principal',
    annotation: '@AuthenticationPrincipal',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.security.core.annotation',
    what: 'Resolves current Authentication principal to method parameter (UserDetails/custom).',
    processor: 'AuthenticationPrincipalArgumentResolver in MVC/WebFlux.',
    proxy: 'None — argument resolver.',
    phase: 'Per-request before controller.',
    when: 'Inject current user without SecurityContextHolder in controller.',
    trap: 'expression attribute maps principal to DTO field subset.',
    memory: '@AuthenticationPrincipal = inject current user.',
  },
  {
    id: 'current-security-context',
    annotation: '@CurrentSecurityContext',
    module: 'security',
    category: 'Spring Security',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.security.core.annotation',
    what: 'Injects SecurityContext or expression from current SecurityContextHolder.',
    processor: 'SecurityContextArgumentResolver.',
    proxy: 'None.',
    phase: 'Per-request.',
    when: 'Need full SecurityContext not just principal.',
    trap: 'Empty context on @Async thread without propagation.',
    memory: '@CurrentSecurityContext injects SecurityContext.',
  },

  // ── Data / JPA ─────────────────────────────────────────────────────────────
  {
    id: 'enable-jpa-repositories',
    annotation: '@EnableJpaRepositories',
    module: 'data',
    category: 'Spring Data JPA',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.data.jpa.repository.config',
    what: 'Activates Spring Data JPA repository scanning and JDK proxy factory beans.',
    processor: 'JpaRepositoriesRegistrar → JpaRepositoryFactoryBean per interface.',
    proxy: 'Repository beans are JDK dynamic proxies.',
    phase: 'Context refresh scanning.',
    when: 'Any JpaRepository interface; Boot auto-config includes when starter present.',
    trap: 'Boot auto-config already enables — explicit for custom basePackages/EMF ref.',
    memory: '@EnableJpaRepositories → JDK repo proxies.',
  },
  {
    id: 'enable-mongo-repositories',
    annotation: '@EnableMongoRepositories',
    module: 'data',
    category: 'Spring Data MongoDB',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.mongodb.repository.config',
    what: 'Scans MongoRepository interfaces; MongoRepositoryFactoryBean proxies.',
    processor: 'MongoRepositoriesRegistrar.',
    proxy: 'JDK proxy on repository interface.',
    phase: 'Startup.',
    when: 'MongoDB document persistence with Spring Data.',
    trap: 'Document mapping @Document is Spring Data Mongo not JPA @Entity.',
    memory: '@EnableMongoRepositories = Mongo repo scan.',
  },
  {
    id: 'enable-redis-repositories',
    annotation: '@EnableRedisRepositories',
    module: 'data',
    category: 'Spring Data Redis',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.data.redis.repository.configuration',
    what: 'Redis hash-based repository support for @RedisHash entities.',
    processor: 'RedisRepositoriesRegistrar.',
    proxy: 'Repository proxy.',
    phase: 'Startup.',
    when: 'Key-value domain objects in Redis with repo abstraction.',
    trap: 'Not a replacement for cache — different use case than @Cacheable.',
    memory: '@EnableRedisRepositories for @RedisHash repos.',
  },
  {
    id: 'enable-elasticsearch-repositories',
    annotation: '@EnableElasticsearchRepositories',
    module: 'data',
    category: 'Spring Data Elasticsearch',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.data.elasticsearch.repository.config',
    what: 'Scans ElasticsearchRepository interfaces for search index CRUD.',
    processor: 'ElasticsearchRepositoriesRegistrar.',
    proxy: 'JDK repository proxy.',
    phase: 'Startup.',
    when: 'Elasticsearch as search/read model store.',
    trap: 'Index mapping vs JPA entity — separate stack.',
    memory: '@EnableElasticsearchRepositories = ES repo scan.',
  },
  {
    id: 'query',
    annotation: '@Query',
    module: 'data',
    category: 'Spring Data JPA',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.data.jpa.repository',
    what: 'Explicit JPQL or native SQL on repository method.',
    processor: 'QueryExecutorMethodInterceptor → JpaQueryExecution.',
    proxy: 'On repository JDK proxy.',
    phase: 'Per repository method call.',
    when: 'Complex queries beyond derived method names.',
    trap: 'nativeQuery=true bypasses JPQL validation; name param binding.',
    memory: '@Query explicit JPQL/native on repo method.',
  },
  {
    id: 'modifying',
    annotation: '@Modifying',
    module: 'data',
    category: 'Spring Data JPA',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.data.jpa.repository',
    what: 'Marks @Query as UPDATE/DELETE requiring flush/clear semantics.',
    processor: 'ModifyingQueryExecution; requires transactional EntityManager.',
    proxy: 'Repository proxy.',
    phase: 'Per modifying query execution.',
    when: 'Bulk updates/deletes via @Query.',
    trap: 'Must be @Transactional — often forgotten on service; clearAutomatically default.',
    memory: '@Modifying @Query needs @Transactional.',
  },
  {
    id: 'param',
    annotation: '@Param',
    module: 'data',
    category: 'Spring Data',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.data.repository.query',
    what: 'Binds method parameter to :name in @Query JPQL/native.',
    processor: 'Query parameter binding in QueryMethod.',
    proxy: 'Repository proxy.',
    phase: 'Query execution.',
    when: 'Named parameters in @Query (:accountId).',
    trap: 'Without @Param, derived queries use param name — needs -parameters compile.',
    memory: '@Param binds :name in @Query.',
  },
  {
    id: 'entity-graph',
    annotation: '@EntityGraph',
    module: 'data',
    category: 'Spring Data JPA',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.jpa.repository',
    what: 'Fetch graph on query to eager-fetch associations avoiding N+1.',
    processor: 'JpaQueryMethod applies EntityGraph to EntityManager query.',
    proxy: 'Repository proxy.',
    phase: 'Query execution.',
    when: 'Controlled fetch joins on specific repository methods.',
    trap: 'Over-fetching large graphs — tune attributePaths.',
    memory: '@EntityGraph fights N+1 on repo queries.',
  },
  {
    id: 'lock',
    annotation: '@Lock',
    module: 'data',
    category: 'Spring Data JPA',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.data.jpa.repository',
    what: 'JPA LockModeType on repository method (PESSIMISTIC_WRITE, OPTIMISTIC).',
    processor: 'LockModeParser sets lock on JPA Query.',
    proxy: 'Repository proxy.',
    phase: 'Query execution within transaction.',
    when: 'Pessimistic row lock via SELECT FOR UPDATE.',
    trap: 'Requires active transaction; timeout and lock wait DB-specific.',
    memory: '@Lock sets JPA LockModeType on query.',
  },
  {
    id: 'created-date',
    annotation: '@CreatedDate',
    module: 'data',
    category: 'Spring Data JPA Auditing',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.annotation',
    what: 'Auditing field auto-populated on entity persist.',
    processor: 'AuditingEntityListener + AuditorAware clock.',
    proxy: 'None on entity.',
    phase: 'Pre-persist auditing callback.',
    when: 'Created timestamp on @Entity with @EntityListeners(AuditingEntityListener).',
    trap: 'Requires @EnableJpaAuditing.',
    memory: '@CreatedDate + @EnableJpaAuditing.',
  },
  {
    id: 'last-modified-date',
    annotation: '@LastModifiedDate',
    module: 'data',
    category: 'Spring Data JPA Auditing',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.annotation',
    what: 'Auditing field updated on each entity change.',
    processor: 'AuditingEntityListener on @PreUpdate/@PrePersist.',
    proxy: 'None.',
    phase: 'Persist/update callbacks.',
    when: 'Track last modified timestamp automatically.',
    trap: 'Clock skew across nodes — use DB or centralized time for audit.',
    memory: '@LastModifiedDate auto on update.',
  },
  {
    id: 'created-by',
    annotation: '@CreatedBy',
    module: 'data',
    category: 'Spring Data JPA Auditing',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.annotation',
    what: 'Auditing field set to current auditor on create.',
    processor: 'AuditorAware<String> bean provides principal.',
    proxy: 'None.',
    phase: 'Pre-persist.',
    when: 'Who created record — pair with Spring Security AuditorAware.',
    trap: 'AuditorAware returns null for anonymous — handle default.',
    memory: '@CreatedBy from AuditorAware bean.',
  },
  {
    id: 'last-modified-by',
    annotation: '@LastModifiedBy',
    module: 'data',
    category: 'Spring Data JPA Auditing',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.annotation',
    what: 'Auditing field set to current auditor on each update.',
    processor: 'AuditingEntityListener + AuditorAware.',
    proxy: 'None.',
    phase: 'Pre-update.',
    when: 'Audit trail of last editor.',
    trap: 'Batch updates may skip listener if bypassing JPA.',
    memory: '@LastModifiedBy on entity updates.',
  },
  {
    id: 'enable-jpa-auditing',
    annotation: '@EnableJpaAuditing',
    module: 'data',
    category: 'Spring Data JPA Auditing',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.data.jpa.repository.config',
    what: 'Registers AuditingEntityListener and auditing infrastructure.',
    processor: 'JpaAuditingRegistrar.',
    proxy: 'None.',
    phase: 'Context refresh.',
    when: 'Any @CreatedDate/@CreatedBy on entities.',
    trap: 'Provide AuditorAware @Bean for user fields.',
    memory: '@EnableJpaAuditing enables auditing listeners.',
  },
  {
    id: 'repository-rest-resource',
    annotation: '@RepositoryRestResource',
    module: 'data',
    category: 'Spring Data REST',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.data.rest.core.annotation',
    what: 'Exposes repository as HAL REST resource at collectionRel path.',
    processor: 'RepositoryEntityController + Spring Data REST event exporters.',
    proxy: 'Repository still JDK proxy underneath.',
    phase: 'Startup MVC mapping; per HTTP request.',
    when: 'Rapid hypermedia APIs — less common vs explicit @RestController.',
    trap: 'Security exposure — secure endpoints; not default in many teams.',
    memory: '@RepositoryRestResource auto HAL REST from repo.',
  },
  {
    id: 'entity',
    annotation: '@Entity',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'JPA entity mapped to database table by provider (Hibernate).',
    processor: 'Hibernate MetadataSourceProcessor at EMF bootstrap — not Spring BPP.',
    proxy: 'Hibernate lazy association proxies — not Spring AOP.',
    phase: 'EMF startup metadata.',
    when: 'ORM persistence; jakarta.persistence in Boot 3.',
    trap: 'NOT a Spring annotation — interview trap attribution.',
    memory: '@Entity = JPA spec; Hibernate maps it.',
  },
  {
    id: 'table',
    annotation: '@Table',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'Optional table name, schema, indexes on @Entity.',
    processor: 'Hibernate table mapping metadata.',
    proxy: 'None.',
    phase: 'EMF bootstrap.',
    when: 'Table name differs from entity name.',
    trap: 'Schema management via Flyway not @Table alone.',
    memory: '@Table names physical table for @Entity.',
  },
  {
    id: 'id',
    annotation: '@Id',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'Primary key field or property on entity.',
    processor: 'JPA provider identifier mapping.',
    proxy: 'None.',
    phase: 'Metadata.',
    when: 'Every entity needs @Id.',
    trap: 'Composite @IdClass vs @EmbeddedId — know both.',
    memory: '@Id = JPA primary key.',
  },
  {
    id: 'generated-value',
    annotation: '@GeneratedValue',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'PK generation strategy: IDENTITY, SEQUENCE, TABLE, AUTO.',
    processor: 'Hibernate identifier generator.',
    proxy: 'None.',
    phase: 'Persist.',
    when: 'Auto-increment or sequence PKs.',
    trap: 'IDENTITY incompatible with batch insert optimizations.',
    memory: '@GeneratedValue strategy on @Id.',
  },
  {
    id: 'column',
    annotation: '@Column',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'Column mapping: name, nullable, length, unique.',
    processor: 'Hibernate column metadata.',
    proxy: 'None.',
    phase: 'Metadata.',
    when: 'Fine-tune column constraints and names.',
    trap: 'nullable=false without DB constraint if ddl-auto create.',
    memory: '@Column maps field to column.',
  },
  {
    id: 'one-to-many',
    annotation: '@OneToMany',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'One-to-many association; default LAZY collection.',
    processor: 'Hibernate collection mapping.',
    proxy: 'Lazy collection proxy / bag.',
    phase: 'Load when accessed.',
    when: 'Parent has many children; define mappedBy owning side.',
    trap: 'LazyInitializationException outside transaction.',
    memory: '@OneToMany LAZY — open session or fetch join.',
  },
  {
    id: 'many-to-one',
    annotation: '@ManyToOne',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'Many-to-one association; often owning side with @JoinColumn.',
    processor: 'Hibernate association mapping.',
    proxy: 'Lazy proxy on reference optional.',
    phase: 'Load on access.',
    when: 'Foreign key relationships.',
    trap: 'Bidirectional sync both sides in domain or use unidirectional.',
    memory: '@ManyToOne + @JoinColumn = FK side.',
  },
  {
    id: 'version',
    annotation: '@Version',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'high',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'Optimistic locking version field incremented on each update.',
    processor: 'Hibernate adds version check to UPDATE WHERE version=?.',
    proxy: 'None.',
    phase: 'Flush/update.',
    when: 'Concurrent updates — OptimisticLockException on conflict.',
    trap: 'Pair with retry or merge strategy; not pessimistic lock.',
    memory: '@Version optimistic lock column.',
  },
  {
    id: 'transient',
    annotation: '@Transient',
    module: 'data',
    category: 'Jakarta Persistence',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'jakarta.persistence',
    what: 'Field not persisted to database (JPA @Transient).',
    processor: 'Excluded from Hibernate mapping.',
    proxy: 'None.',
    phase: 'Metadata.',
    when: 'Computed fields, DTO helpers on entity (prefer separate DTO).',
    trap: 'Contrast java.beans.Transient and Jackson @JsonIgnore.',
    memory: 'JPA @Transient = not mapped to DB.',
  },

  // ── Kafka ──────────────────────────────────────────────────────────────────
  {
    id: 'enable-kafka',
    annotation: '@EnableKafka',
    module: 'kafka',
    category: 'Spring Kafka',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.kafka.annotation',
    what: 'Enables @KafkaListener infrastructure: KLABPP, endpoint registry, containers.',
    processor: 'KafkaListenerAnnotationBeanPostProcessor + KafkaListenerEndpointRegistry.',
    proxy: 'None on enable; listener invoked by container adapter.',
    phase: 'Context refresh; containers start on ApplicationStarted.',
    when: 'Any @KafkaListener; Boot may auto-enable via KafkaAnnotationDrivenConfiguration.',
    trap: 'Without @EnableKafka listeners not registered in plain Spring context.',
    memory: '@EnableKafka → KLABPP → registry → containers.',
  },
  {
    id: 'kafka-listener',
    annotation: '@KafkaListener',
    module: 'kafka',
    category: 'Spring Kafka',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.kafka.annotation',
    what: 'Marks method as Kafka consumer for topics/groupId/containerFactory.',
    processor: 'KLABPP → MethodKafkaListenerEndpoint → KafkaMessageListenerContainer poll loop.',
    proxy: 'Adapter invokes bean method; @Transactional listener uses service proxy.',
    phase: 'Container poll loop runtime.',
    when: 'Event consumption; manual ack with Acknowledgment param.',
    trap: 'Same groupId shares partitions; different groups broadcast.',
    memory: '@KafkaListener → container.poll → invoke method.',
  },
  {
    id: 'kafka-handler',
    annotation: '@KafkaHandler',
    module: 'kafka',
    category: 'Spring Kafka',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.kafka.annotation',
    what: 'Multiple handler methods on @KafkaListener class discriminated by payload type.',
    processor: 'KafkaHandlerMethodFactory selects method by message type.',
    proxy: 'None.',
    phase: 'Listener invocation.',
    when: 'Single listener class handles multiple event types on same topic.',
    trap: 'Class-level @KafkaListener required; one @KafkaHandler per payload type.',
    memory: '@KafkaHandler multi-method on @KafkaListener class.',
  },
  {
    id: 'send-to',
    annotation: '@SendTo',
    module: 'kafka',
    category: 'Spring Kafka',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.kafka.annotation',
    what: 'Reply topic for @KafkaListener return value (request-reply pattern).',
    processor: 'ReplyingKafkaTemplate / listener adapter sends return to SendTo topic.',
    proxy: 'None.',
    phase: 'After listener method returns.',
    when: 'Kafka request-reply; RPC-style over topics.',
    trap: 'Requires ReplyingKafkaTemplate configuration and correlation headers.',
    memory: '@SendTo routes listener return to topic.',
  },
  {
    id: 'retryable-topic',
    annotation: '@RetryableTopic',
    module: 'kafka',
    category: 'Spring Kafka',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.kafka.annotation',
    what: 'Non-blocking retry via retry topics with backoff and DLT suffix strategy.',
    processor: 'RetryTopicConfigurationProcessor post-processes @KafkaListener endpoints.',
    proxy: 'None — topic topology change.',
    phase: 'Startup endpoint enhancement.',
    when: 'Retry without blocking consumer thread; DLT after attempts.',
    trap: 'Creates additional topics; same partition count alignment matters.',
    memory: '@RetryableTopic = retry topics + DLT strategy.',
  },
  {
    id: 'dlt-handler',
    annotation: '@DltHandler',
    module: 'kafka',
    category: 'Spring Kafka',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.kafka.annotation',
    what: 'Handler method for dead-letter topic messages after retries exhausted.',
    processor: 'DeadLetterPublishingRecoverer / @RetryableTopic DLT routing.',
    proxy: 'None.',
    phase: 'DLT consumer invocation.',
    when: 'Alerting, manual repair pipeline on poison messages.',
    trap: 'DLT handler must use separate consumer or same @RetryableTopic config.',
    memory: '@DltHandler processes DLT topic records.',
  },

  // ── Test ───────────────────────────────────────────────────────────────────
  {
    id: 'spring-boot-test',
    annotation: '@SpringBootTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.boot.test.context',
    what: 'Full (or configured) application context integration test.',
    processor: 'SpringBootContextLoader; merges @SpringBootConfiguration.',
    proxy: 'Real or test context proxies as in production.',
    phase: 'Test context startup.',
    when: 'Integration tests needing multiple layers; use slices when possible.',
    trap: 'Slow — prefer @WebMvcTest/@DataJpaTest slices for focused tests.',
    memory: '@SpringBootTest full context integration test.',
  },
  {
    id: 'web-mvc-test',
    annotation: '@WebMvcTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.web.servlet',
    what: 'MVC slice: @Controller, Jackson, MockMvc — mocks other beans.',
    processor: 'WebMvcTestContextBootstrapper limited component scan.',
    proxy: 'Only MVC layer beans; @MockBean for services.',
    phase: 'Test context slice.',
    when: 'Controller JSON mapping and security slice tests.',
    trap: 'Service not loaded — must @MockBean service layer.',
    memory: '@WebMvcTest = MVC slice + MockMvc.',
  },
  {
    id: 'web-flux-test',
    annotation: '@WebFluxTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.web.reactive',
    what: 'WebFlux slice: @Controller/WebFlux controllers with WebTestClient.',
    processor: 'WebFluxTestContextBootstrapper.',
    proxy: 'Reactive controller only slice.',
    phase: 'Test context.',
    when: 'Reactive controller tests without full Netty server.',
    trap: 'WebTestClient bindToController vs full @SpringBootTest RANDOM_PORT.',
    memory: '@WebFluxTest = reactive MVC slice.',
  },
  {
    id: 'data-jpa-test',
    annotation: '@DataJpaTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.orm.jpa',
    what: 'JPA slice: entities, repos, TestEntityManager — default @Transactional rollback.',
    processor: 'DataJpaTestContextBootstrapper; embedded DB often auto-configured.',
    proxy: 'Real repository JDK proxies against test DB.',
    phase: 'Test context.',
    when: 'Repository query tests without full web stack.',
    trap: '@Transactional rolls back by default — differs from prod commit behavior.',
    memory: '@DataJpaTest JPA repo slice + rollback TX.',
  },
  {
    id: 'data-mongo-test',
    annotation: '@DataMongoTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.data.mongo',
    what: 'Mongo slice: MongoTemplate/repos with embedded or Testcontainers Mongo.',
    processor: 'DataMongoTestContextBootstrapper.',
    proxy: 'Mongo repository proxies.',
    phase: 'Test context.',
    when: 'Mongo repository integration tests.',
    trap: 'Flapdoodle embedded vs Testcontainers for version parity.',
    memory: '@DataMongoTest Mongo slice.',
  },
  {
    id: 'json-test',
    annotation: '@JsonTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.json',
    what: 'Jackson ObjectMapper slice for JSON serialize/deserialize tests.',
    processor: 'JsonTestContextBootstrapper loads Jackson auto-config only.',
    proxy: 'None.',
    phase: 'Test context minimal.',
    when: 'Custom serializers, DTO JSON contract tests.',
    trap: 'No MVC — use @WebMvcTest for full HTTP JSON round trip.',
    memory: '@JsonTest Jackson-only slice.',
  },
  {
    id: 'rest-client-test',
    annotation: '@RestClientTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.web.client',
    what: 'Slice for @RestClient / RestTemplateBuilder with MockRestServiceServer.',
    processor: 'RestClientTestContextBootstrapper.',
    proxy: 'Mock HTTP client not real network.',
    phase: 'Test.',
    when: 'Test HTTP client adapters without wire mock server process.',
    trap: 'Boot 3 RestClient vs legacy RestTemplate test setup.',
    memory: '@RestClientTest HTTP client slice + mock server.',
  },
  {
    id: 'jdbc-test',
    annotation: '@JdbcTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.jdbc',
    what: 'JdbcTemplate slice without full JPA.',
    processor: 'JdbcTestContextBootstrapper.',
    proxy: 'None.',
    phase: 'Test context.',
    when: 'Raw SQL repository tests with @Sql scripts.',
    trap: 'No @EntityManager — JDBC only slice.',
    memory: '@JdbcTest JdbcTemplate slice.',
  },
  {
    id: 'jooq-test',
    annotation: '@JooqTest',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.boot.test.autoconfigure.jooq',
    what: 'jOOQ DSL context slice for typed SQL tests.',
    processor: 'JooqTestContextBootstrapper.',
    proxy: 'None.',
    phase: 'Test context.',
    when: 'jOOQ query integration tests.',
    trap: 'Requires spring-boot-starter-jooq on test classpath.',
    memory: '@JooqTest jOOQ DSL slice.',
  },
  {
    id: 'mock-bean',
    annotation: '@MockBean',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.springframework.boot.test.mock.mockito',
    what: 'Adds Mockito mock to test ApplicationContext replacing or augmenting bean.',
    processor: 'MockitoPostProcessor / DefinitionRegistryPostProcessor in test context.',
    proxy: 'Mock is injected instead of real bean.',
    phase: 'Test context refresh before tests.',
    when: 'Slice tests mocking service layer from @WebMvcTest.',
    trap: '@MockBean on every test slows context — reuse context or @MockitoBean (Boot 3.4+).',
    memory: '@MockBean Spring context Mockito mock.',
  },
  {
    id: 'spy-bean',
    annotation: '@SpyBean',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.boot.test.mock.mockito',
    what: 'Wraps real bean with Mockito spy in test context.',
    processor: 'MockitoPostProcessor spy wrapper.',
    proxy: 'Spy delegates to real instance unless stubbed.',
    phase: 'Test context.',
    when: 'Partial mock of real bean behavior in integration test.',
    trap: 'Spy still runs real code paths — side effects remain.',
    memory: '@SpyBean partial mock of real bean.',
  },
  {
    id: 'mockito-bean',
    annotation: '@MockitoBean',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'medium',
    stack: 'Boot 3.4+',
    package: 'org.springframework.test.context.bean.override.mockito',
    what: 'Bean override API replacing @MockBean — @MockitoBean on field for Mockito mock.',
    processor: 'BeanOverrideTestExecutionListener + MockitoBeanOverrideProcessor.',
    proxy: 'Mock injected via bean override mechanism.',
    phase: 'Test context (new override model).',
    when: 'Boot 3.4+ tests; cleaner than legacy @MockBean for some cases.',
    trap: 'Migrate from @MockBean — different package org.springframework.test.context.bean.override.',
    memory: '@MockitoBean Boot 3.4+ bean override mock.',
  },
  {
    id: 'context-configuration',
    annotation: '@ContextConfiguration',
    module: 'test',
    category: 'Spring Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.test.context',
    what: 'Specifies @Configuration classes or XML for test ApplicationContext.',
    processor: 'ContextLoader / AnnotationConfigContextLoader.',
    proxy: 'As configured.',
    phase: 'Test bootstrap.',
    when: 'Non-Boot Spring tests or custom minimal context.',
    trap: '@SpringBootTest often supersedes for Boot apps.',
    memory: '@ContextConfiguration defines test context sources.',
  },
  {
    id: 'dirties-context',
    annotation: '@DirtiesContext',
    module: 'test',
    category: 'Spring Test',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.test.annotation',
    what: 'Marks test context dirty — rebuilt after test class/method.',
    processor: 'DirtiesContextTestExecutionListener.',
    proxy: 'None.',
    phase: 'After test when dirty.',
    when: 'Tests mutate global static state or singleton beans.',
    trap: 'Slow — rebuilds context; avoid when possible.',
    memory: '@DirtiesContext forces context reload.',
  },
  {
    id: 'test-configuration',
    annotation: '@TestConfiguration',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.boot.test.context',
    what: 'Extra @Configuration imported into test context only (not component scan).',
    processor: 'Imported explicitly in test or @Import.',
    proxy: 'Beans as defined.',
    phase: 'Test context.',
    when: 'Test-only beans, mock clocks, fake clients.',
    trap: 'Not picked up by production scan — must @Import in test.',
    memory: '@TestConfiguration test-only @Bean config.',
  },
  {
    id: 'test-component',
    annotation: '@TestComponent',
    module: 'test',
    category: 'Spring Boot Test',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.boot.test.context',
    what: 'Marks @Component included in test slice scan only.',
    processor: 'Test slice filters include @TestComponent.',
    proxy: 'As component.',
    phase: 'Test context scan.',
    when: 'Helper component visible only in slice tests.',
    trap: 'Regular @Component would load in slice unexpectedly.',
    memory: '@TestComponent slice-scanned test helper.',
  },
  {
    id: 'sql',
    annotation: '@Sql',
    module: 'test',
    category: 'Spring Test',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.springframework.test.context.jdbc',
    what: 'Runs SQL scripts before/after test method or class.',
    processor: 'SqlScriptsTestExecutionListener executes scripts on DataSource.',
    proxy: 'None.',
    phase: 'Test setup/teardown.',
    when: 'Seed data for @JdbcTest/@DataJpaTest integration tests.',
    trap: 'Script order and execution phase BEFORE_TEST_METHOD vs BEFORE_TEST_CLASS.',
    memory: '@Sql runs classpath SQL scripts on DataSource.',
  },
  {
    id: 'sql-config',
    annotation: '@SqlConfig',
    module: 'test',
    category: 'Spring Test',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.test.context.jdbc',
    what: 'Configures @Sql script encoding, separator, error mode, data source.',
    processor: 'SqlScriptsTestExecutionListener config.',
    proxy: 'None.',
    phase: 'Script execution.',
    when: 'Custom separator or separate datasource for scripts.',
    trap: 'Nested @SqlConfig on class vs method inheritance.',
    memory: '@SqlConfig tunes @Sql execution.',
  },
  {
    id: 'mock',
    annotation: '@Mock',
    module: 'test',
    category: 'Mockito',
    interviewImportance: 'critical',
    stack: STACK,
    package: 'org.mockito',
    what: 'Mockito mock field or parameter — not a Spring annotation.',
    processor: 'MockitoExtension / MockitoAnnotations.openMocks in unit tests.',
    proxy: 'Pure Mockito mock — no Spring context.',
    phase: 'Test init.',
    when: 'Pure unit tests without Spring context.',
    trap: 'Contrast @Mock vs @MockBean — only latter in Spring context.',
    memory: '@Mock = Mockito only; not Spring @MockBean.',
  },
  {
    id: 'inject-mocks',
    annotation: '@InjectMocks',
    module: 'test',
    category: 'Mockito',
    interviewImportance: 'high',
    stack: STACK,
    package: 'org.mockito',
    what: 'Mockito injects @Mock fields into tested instance.',
    processor: 'Mockito injectMocks — no Spring.',
    proxy: 'Tests real class with mocked dependencies.',
    phase: 'Test init.',
    when: 'Unit test service with mocked repos.',
    trap: 'Cannot mock final classes without mockito-inline.',
    memory: '@InjectMocks wires @Mock into test subject.',
  },

  // ── Actuator ───────────────────────────────────────────────────────────────
  {
    id: 'endpoint',
    annotation: '@Endpoint',
    module: 'actuator',
    category: 'Spring Boot Actuator',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.actuate.endpoint',
    what: 'Custom actuator endpoint id with read/write/delete operations.',
    processor: 'EndpointDiscoverer registers @Endpoint bean; exposed via JMX/HTTP if enabled.',
    proxy: 'None.',
    phase: 'Startup discovery; invoke on management request.',
    when: 'Custom ops metrics/health extensions beyond built-in endpoints.',
    trap: 'Expose via management.endpoints.web.exposure.include — default limited.',
    memory: '@Endpoint custom actuator endpoint id.',
  },
  {
    id: 'read-operation',
    annotation: '@ReadOperation',
    module: 'actuator',
    category: 'Spring Boot Actuator',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.boot.actuate.endpoint.web.annotation',
    what: 'GET handler on @Endpoint bean returning operation data.',
    processor: 'WebEndpointServletHandlerMapping maps GET /actuator/{id}.',
    proxy: 'None.',
    phase: 'Management HTTP request.',
    when: 'Read-only custom actuator data.',
    trap: 'Secure management port/auth — endpoints leak infra data.',
    memory: '@ReadOperation GET on @Endpoint.',
  },
  {
    id: 'write-operation',
    annotation: '@WriteOperation',
    module: 'actuator',
    category: 'Spring Boot Actuator',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.boot.actuate.endpoint.web.annotation',
    what: 'POST handler on @Endpoint for mutating operations.',
    processor: 'Web endpoint POST mapping.',
    proxy: 'None.',
    phase: 'Management request.',
    when: 'Trigger cache clear, feature toggle via actuator.',
    trap: 'Dangerous in prod — restrict exposure and auth.',
    memory: '@WriteOperation POST mutating actuator op.',
  },
  {
    id: 'delete-operation',
    annotation: '@DeleteOperation',
    module: 'actuator',
    category: 'Spring Boot Actuator',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.boot.actuate.endpoint.web.annotation',
    what: 'DELETE handler on @Endpoint.',
    processor: 'Web endpoint DELETE mapping.',
    proxy: 'None.',
    phase: 'Management request.',
    when: 'Rare custom cleanup operations.',
    trap: 'Same security concerns as @WriteOperation.',
    memory: '@DeleteOperation DELETE on @Endpoint.',
  },
  {
    id: 'endpoint-web-extension',
    annotation: '@EndpointWebExtension',
    module: 'actuator',
    category: 'Spring Boot Actuator',
    interviewImportance: 'niche',
    stack: STACK,
    package: 'org.springframework.boot.actuate.endpoint.web.annotation',
    what: 'Web-specific extension of existing endpoint with additional web operations.',
    processor: 'WebEndpointDiscoverer composes base @Endpoint + extension.',
    proxy: 'None.',
    phase: 'Startup; HTTP invoke.',
    when: 'Add web-only ops to existing endpoint (e.g. custom health detail).',
    trap: 'Extension endpointId must match base @Endpoint.',
    memory: '@EndpointWebExtension extends endpoint for web.',
  },

  // ── Integration / Batch / Cloud ────────────────────────────────────────────
  {
    id: 'enable-batch-processing',
    annotation: '@EnableBatchProcessing',
    module: 'integration',
    category: 'Spring Batch',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.batch.core.configuration.annotation',
    what: 'Enables Spring Batch: JobRepository, JobLauncher, @Step/@Job infrastructure.',
    processor: 'BatchConfigurationSelector imports batch infrastructure beans.',
    proxy: 'None.',
    phase: 'Context refresh.',
    when: 'Chunk-oriented batch jobs, scheduled ETL.',
    trap: 'Requires JobRepository DataSource; not for streaming Kafka primary pattern.',
    memory: '@EnableBatchProcessing = Batch infra beans.',
  },
  {
    id: 'enable-binding',
    annotation: '@EnableBinding',
    module: 'integration',
    category: 'Spring Cloud Stream (legacy)',
    interviewImportance: 'niche',
    stack: 'Legacy Spring Cloud Stream',
    package: 'org.springframework.cloud.stream.annotation',
    what: 'Legacy annotation binding interfaces to message channels (pre-functional model).',
    processor: 'Deprecated — BindableProxyFactory in older Cloud Stream.',
    proxy: 'Binding interface JDK proxy.',
    phase: 'Legacy apps only.',
    when: 'Maintain legacy Stream apps; migrate to spring.cloud.function definition.',
    trap: 'Removed/deprecated in modern Cloud Stream 3+ — cite functional model in interview.',
    memory: '@EnableBinding legacy — use function beans now.',
  },
  {
    id: 'enable-discovery-client',
    annotation: '@EnableDiscoveryClient',
    module: 'integration',
    category: 'Spring Cloud',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.cloud.client.discovery',
    what: 'Registers app with service registry (Eureka, Consul) when client on classpath.',
    processor: 'Auto-config + DiscoveryClient lifecycle heartbeat.',
    proxy: 'None.',
    phase: 'Application startup registration.',
    when: 'Microservices service discovery registration.',
    trap: 'Boot may auto-register without explicit annotation when starter present.',
    memory: '@EnableDiscoveryClient service registry registration.',
  },
  {
    id: 'refresh-scope',
    annotation: '@RefreshScope',
    module: 'integration',
    category: 'Spring Cloud Context',
    interviewImportance: 'medium',
    stack: STACK,
    package: 'org.springframework.cloud.context.config.annotation',
    what: 'Scoped proxy bean recreated on /actuator/refresh or config refresh event.',
    processor: 'RefreshScope registers scoped proxy; ContextRefresher destroys scope.',
    proxy: 'CGLIB scoped proxy — required for singletons injecting refresh bean.',
    phase: 'Refresh event destroys and recreates bean.',
    when: 'Cloud Config dynamic @ConfigurationProperties without restart.',
    trap: 'Singleton holding direct reference to @RefreshScope bean stays stale — need proxy injection.',
    memory: '@RefreshScope scoped proxy + refresh destroys bean.',
  },
];

export const INVENTORY_MODULES_COUNT = INVENTORY_MODULES.length;
