/**
 * Extended ecosystem inventory — Integration, Batch, Cloud, Session, Data stores,
 * HATEOAS, test slices, actuator extensions, and JPA ownership clarifiers.
 * Baseline: Boot 3 / Spring Framework 6.
 */

export type EcosystemOwner =
  | 'Spring Framework'
  | 'Spring Boot'
  | 'Spring Security'
  | 'Spring Data'
  | 'Spring Kafka'
  | 'Spring Batch'
  | 'Spring Integration'
  | 'Spring Cloud'
  | 'Spring Session'
  | 'Spring HATEOAS'
  | 'Jakarta Persistence'
  | 'Jakarta Validation'
  | 'Hibernate'
  | 'JUnit'
  | 'Mockito'
  | 'Third-party';

export type EcosystemInventoryEntry = {
  annotation: string;
  fqn: string;
  module: string;
  packageName: string;
  owner: EcosystemOwner;
  introduced: string;
  deprecated: string; // 'no' or version
  status: 'current' | 'legacy' | 'deprecated' | 'removed' | 'experimental';
  target: string;
  retention: string;
  purpose: string;
  processor: string;
  phase: string;
  beanDefinitionImpact: string;
  beanPostProcessor: string;
  proxy: string;
  runtimeInterception: string;
  productionUse: string;
  interviewQuestion: string;
  interviewImportance: 'must' | 'high' | 'medium' | 'low' | 'niche';
  versionNotes: string;
  category: string;
};

export const ECOSYSTEM_DISCLAIMER: string =
  'Ecosystem inventory covers Spring-adjacent modules (Integration, Batch, Cloud, Session, Data stores, HATEOAS) plus Jakarta/JUnit ownership rows. Baseline Boot 3 / Spring Framework 6. Spring Cloud Stream @EnableBinding/@Input/@Output/@StreamListener are legacy — prefer the functional programming model (spring.cloud.function.definition). JPA @Entity/@Id are Jakarta Persistence, not Spring. Curated for staff interviews — not every annotation in Spring Cloud Netflix history.';

type EcoPartial = Omit<
  EcosystemInventoryEntry,
  'introduced' | 'deprecated' | 'retention' | 'target' | 'status'
> &
  Partial<Pick<EcosystemInventoryEntry, 'introduced' | 'deprecated' | 'retention' | 'target' | 'status'>>;

function eco(row: EcoPartial): EcosystemInventoryEntry {
  return {
    introduced: 'module-specific',
    deprecated: 'no',
    retention: 'RUNTIME',
    target: 'TYPE, METHOD',
    status: 'current',
    ...row,
  };
}

export const INVENTORY_ECOSYSTEM: EcosystemInventoryEntry[] = [
  // ── Spring Integration ───────────────────────────────────────────────────────
  eco({
    annotation: '@EnableIntegration',
    fqn: 'org.springframework.integration.config.EnableIntegration',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.config',
    owner: 'Spring Integration',
    introduced: '2.0',
    target: 'TYPE',
    purpose: 'Enables Spring Integration infrastructure: MessageChannel beans, endpoint registry, conversion and error channels.',
    processor: 'IntegrationRegistrar / IntegrationManagementConfigurer imports IntegrationConfiguration.',
    phase: 'Context refresh — registers channel factories and endpoint post-processors.',
    beanDefinitionImpact: 'Registers IntegrationInfrastructureBeanFactoryPostProcessor and default channels.',
    beanPostProcessor: 'IntegrationManagementConfigurer; endpoint discovery post-processors.',
    proxy: 'None on annotation; @MessagingGateway creates JDK interface proxy.',
    runtimeInterception: 'Message-driven endpoints intercept channel dispatch.',
    productionUse: 'ETL adapters, file polling, JMS/Kafka bridges, legacy enterprise messaging.',
    interviewQuestion: 'What does @EnableIntegration register at startup?',
    interviewImportance: 'high',
    versionNotes: 'Stable in SI 6.x / Boot 3. Often implicit when spring-integration-core on classpath.',
    category: 'Spring Integration — bootstrap',
  }),
  eco({
    annotation: '@ServiceActivator',
    fqn: 'org.springframework.integration.annotation.ServiceActivator',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '1.0',
    target: 'METHOD',
    purpose: 'Marks method as message handler subscribed to input channel; invokes on Message arrival.',
    processor: 'ServiceActivatorAnnotationBeanPostProcessor registers MethodInvokingMessageHandler endpoint.',
    phase: 'Startup endpoint registration; runtime per-message invoke.',
    beanDefinitionImpact: 'Creates IntegrationConsumer endpoint bean linked to input channel.',
    beanPostProcessor: 'ServiceActivatorAnnotationBeanPostProcessor.',
    proxy: 'None — direct method invoke on target bean (may be @Poller-managed).',
    runtimeInterception: 'Dispatcher routes Message to handler method via MessageHandler.',
    productionUse: 'Core pattern: transform/enrich/route payloads in integration flows.',
    interviewQuestion: 'Difference between @ServiceActivator and @Transformer?',
    interviewImportance: 'high',
    versionNotes: 'inputChannel attribute required unless default channel configured.',
    category: 'Spring Integration — endpoints',
  }),
  eco({
    annotation: '@Transformer',
    fqn: 'org.springframework.integration.annotation.Transformer',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '1.0',
    target: 'METHOD',
    purpose: 'Message endpoint converting input payload type to output type (1:1 transform).',
    processor: 'TransformerAnnotationBeanPostProcessor → MethodInvokingTransformer.',
    phase: 'Startup registration; per-message transform.',
    beanDefinitionImpact: 'Endpoint bean with transformer role on channel pipeline.',
    beanPostProcessor: 'TransformerAnnotationBeanPostProcessor.',
    proxy: 'None.',
    runtimeInterception: 'Transformer endpoint in messaging pipeline.',
    productionUse: 'Format conversion (XML→DTO), header enrichment, normalization.',
    interviewQuestion: 'When use @Transformer vs plain @ServiceActivator?',
    interviewImportance: 'medium',
    versionNotes: 'Semantically a specialized @ServiceActivator with transform contract.',
    category: 'Spring Integration — endpoints',
  }),
  eco({
    annotation: '@Filter',
    fqn: 'org.springframework.integration.annotation.Filter',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '1.0',
    target: 'METHOD',
    purpose: 'Boolean filter endpoint — drops or accepts Message based on method return (true passes).',
    processor: 'FilterAnnotationBeanPostProcessor.',
    phase: 'Startup; runtime filter chain.',
    beanDefinitionImpact: 'Filter endpoint bean on input channel.',
    beanPostProcessor: 'FilterAnnotationBeanPostProcessor.',
    proxy: 'None.',
    runtimeInterception: 'Filter discards or forwards Message.',
    productionUse: 'Route only valid orders, drop poison payloads before downstream.',
    interviewQuestion: 'What happens when @Filter method returns false?',
    interviewImportance: 'medium',
    versionNotes: 'throwExceptionOnRejection option for error channel routing.',
    category: 'Spring Integration — endpoints',
  }),
  eco({
    annotation: '@Router',
    fqn: 'org.springframework.integration.annotation.Router',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '1.0',
    target: 'METHOD',
    purpose: 'Routes Message to one or more output channels based on method return (channel name or Collection).',
    processor: 'RouterAnnotationBeanPostProcessor.',
    phase: 'Startup; runtime routing decision.',
    beanDefinitionImpact: 'Router endpoint with dynamic channel resolution.',
    beanPostProcessor: 'RouterAnnotationBeanPostProcessor.',
    proxy: 'None.',
    runtimeInterception: 'AbstractMessageRouter selects destination channel(s).',
    productionUse: 'Content-based routing, priority queues, multi-tenant channel fan-out.',
    interviewQuestion: 'How does @Router differ from Spring Integration DSL router()?',
    interviewImportance: 'medium',
    versionNotes: 'Annotation model vs Java DSL/ XML config — same runtime.',
    category: 'Spring Integration — endpoints',
  }),
  eco({
    annotation: '@Splitter',
    fqn: 'org.springframework.integration.annotation.Splitter',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '1.0',
    target: 'METHOD',
    purpose: 'Splits one Message into multiple Messages (1:N) from collection/array return.',
    processor: 'SplitterAnnotationBeanPostProcessor.',
    phase: 'Startup; runtime split.',
    beanDefinitionImpact: 'Splitter endpoint producing multiple downstream messages.',
    beanPostProcessor: 'SplitterAnnotationBeanPostProcessor.',
    proxy: 'None.',
    runtimeInterception: 'SplitterHandler emits Message list to output channel.',
    productionUse: 'Batch file lines → per-line processing; order lines fan-out.',
    interviewQuestion: 'Splitter output channel when returning List<Message>?',
    interviewImportance: 'medium',
    versionNotes: 'applySequence flag for correlation headers.',
    category: 'Spring Integration — endpoints',
  }),
  eco({
    annotation: '@Aggregator',
    fqn: 'org.springframework.integration.annotation.Aggregator',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '1.0',
    target: 'METHOD',
    purpose: 'Correlates and aggregates multiple Messages into one (N:1) using correlation strategy.',
    processor: 'AggregatorAnnotationBeanPostProcessor.',
    phase: 'Startup; runtime correlation store.',
    beanDefinitionImpact: 'Aggregator endpoint with MessageGroupStore.',
    beanPostProcessor: 'AggregatorAnnotationBeanPostProcessor.',
    proxy: 'None.',
    runtimeInterception: 'Aggregator releases combined Message when release strategy fires.',
    productionUse: 'Reassemble chunked responses, batch completion gates.',
    interviewQuestion: 'Aggregator correlation key — where configured?',
    interviewImportance: 'high',
    versionNotes: 'expireGroupsUponCompletion, sendPartialResultOnExpiry tuning.',
    category: 'Spring Integration — endpoints',
  }),
  eco({
    annotation: '@MessagingGateway',
    fqn: 'org.springframework.integration.annotation.MessagingGateway',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '2.0',
    target: 'TYPE',
    purpose: 'Creates JDK dynamic proxy for interface — method calls become Messages on request channel.',
    processor: 'MessagingGatewayRegistrar creates GatewayProxyFactoryBean.',
    phase: 'Startup proxy creation; runtime sync/async gateway invoke.',
    beanDefinitionImpact: 'Registers proxy bean implementing annotated interface.',
    beanPostProcessor: 'GatewayProxyFactoryBean factory.',
    proxy: 'JDK dynamic proxy on gateway interface.',
    runtimeInterception: 'GatewayMethodInboundMessageMapper sends/receives on channels.',
    productionUse: 'Clean API facade over messaging without exposing Message API to callers.',
    interviewQuestion: 'MessagingGateway proxy type — JDK or CGLIB?',
    interviewImportance: 'high',
    versionNotes: 'defaultRequestChannel / defaultReplyChannel on annotation.',
    category: 'Spring Integration — gateways',
  }),
  eco({
    annotation: '@InboundChannelAdapter',
    fqn: 'org.springframework.integration.annotation.InboundChannelAdapter',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Pollable or event-driven producer endpoint — method return value sent to output channel.',
    processor: 'InboundChannelAdapterAnnotationBeanPostProcessor.',
    phase: 'Startup; scheduled or lifecycle-triggered poll.',
    beanDefinitionImpact: 'SourcePollingChannelAdapter or event adapter bean.',
    beanPostProcessor: 'InboundChannelAdapterAnnotationBeanPostProcessor.',
    proxy: 'None.',
    runtimeInterception: 'Poller triggers method; result becomes Message.',
    productionUse: 'FTP/SFTP/file tail ingress, scheduled DB poll producing messages.',
    interviewQuestion: 'InboundChannelAdapter vs @InboundAdapter from spring-kafka?',
    interviewImportance: 'medium',
    versionNotes: 'Often paired with @Poller for fixed-delay polling.',
    category: 'Spring Integration — adapters',
  }),
  eco({
    annotation: '@IntegrationComponentScan',
    fqn: 'org.springframework.integration.annotation.IntegrationComponentScan',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '4.3',
    target: 'TYPE',
    purpose: 'Component-scan for @MessagingGateway interfaces and SI stereotype beans in base packages.',
    processor: 'IntegrationComponentScanRegistrar.',
    phase: 'Configuration class parsing.',
    beanDefinitionImpact: 'Adds gateway and endpoint beans from scanned packages.',
    beanPostProcessor: 'None — registrar only.',
    proxy: 'Gateway interfaces get proxies at bean creation.',
    runtimeInterception: 'N/A at scan phase.',
    productionUse: 'Organize integration flows in dedicated packages.',
    interviewQuestion: '@IntegrationComponentScan vs @ComponentScan?',
    interviewImportance: 'medium',
    versionNotes: 'Analogous to @EnableKafka but for SI gateways.',
    category: 'Spring Integration — bootstrap',
  }),
  eco({
    annotation: '@Poller',
    fqn: 'org.springframework.integration.annotation.Poller',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '2.0',
    target: 'METHOD, ANNOTATION_TYPE',
    purpose: 'Defines fixed-delay/rate poller metadata for inbound adapters and some endpoints.',
    processor: 'PollerMetadata annotation merged into endpoint PollerMetadata bean.',
    phase: 'Startup poller registration; runtime TaskScheduler triggers.',
    beanDefinitionImpact: 'Poller bean with trigger/cron from annotation attributes.',
    beanPostProcessor: 'Endpoint discovers @Poller on composed annotations.',
    proxy: 'None.',
    runtimeInterception: 'TaskScheduler executes poll cycle.',
    productionUse: 'Tune poll interval for file/FTP sources; max-messages-per-poll.',
    interviewQuestion: 'Default poller when @Poller omitted on inbound adapter?',
    interviewImportance: 'medium',
    versionNotes: 'fixedDelay vs fixedRate; taskExecutor for concurrent polls.',
    category: 'Spring Integration — polling',
  }),
  eco({
    annotation: '@MessageEndpoint',
    fqn: 'org.springframework.integration.annotation.MessageEndpoint',
    module: 'spring-integration',
    packageName: 'org.springframework.integration.annotation',
    owner: 'Spring Integration',
    introduced: '2.0',
    target: 'TYPE',
    purpose: 'Stereotype marking class containing @ServiceActivator/@Transformer etc. endpoint methods.',
    processor: 'Component-scan treats as SI-managed bean; endpoint BPPs process methods.',
    phase: 'Component scan + endpoint registration.',
    beanDefinitionImpact: 'Standard @Component-like bean with SI endpoint processing.',
    beanPostProcessor: 'Various *AnnotationBeanPostProcessor on methods.',
    proxy: 'None on class.',
    runtimeInterception: 'Per-endpoint method handlers.',
    productionUse: 'Group related handlers in one Spring bean.',
    interviewQuestion: '@MessageEndpoint vs @Component for SI handlers?',
    interviewImportance: 'low',
    versionNotes: 'Semantic clarity; functionally similar to @Component in scanned context.',
    category: 'Spring Integration — stereotypes',
  }),

  // ── Spring Batch ─────────────────────────────────────────────────────────────
  eco({
    annotation: '@EnableBatchProcessing',
    fqn: 'org.springframework.batch.core.configuration.annotation.EnableBatchProcessing',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.configuration.annotation',
    owner: 'Spring Batch',
    introduced: '2.2',
    target: 'TYPE',
    purpose: 'Enables Batch infrastructure: JobRepository, JobLauncher, JobBuilderFactory (legacy), builders.',
    processor: 'BatchConfigurationSelector / BatchAutoConfiguration (Boot 3).',
    phase: 'Context refresh — batch infra beans.',
    beanDefinitionImpact: 'Registers JobRepository, PlatformTransactionManager for batch, JobExplorer.',
    beanPostProcessor: 'None — @Configuration import selector.',
    proxy: 'None.',
    runtimeInterception: 'JobLauncher.run executes Job with Step pipeline.',
    productionUse: 'Nightly ETL, payment file ingestion, reconciliation jobs.',
    interviewQuestion: 'Boot 3: still need @EnableBatchProcessing explicitly?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 BatchAutoConfiguration often sufficient; modular Java config preferred.',
    category: 'Spring Batch — bootstrap',
  }),
  eco({
    annotation: '@StepScope',
    fqn: 'org.springframework.batch.core.configuration.annotation.StepScope',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.configuration.annotation',
    owner: 'Spring Batch',
    introduced: '3.0',
    target: 'TYPE, METHOD',
    purpose: 'Scoped proxy bean recreated per Step execution — late binding of jobParameters via SpEL.',
    processor: 'BatchScopeConfigurationRegistrar; ScopedProxyFactoryBean for step scope.',
    phase: 'Step start creates scope; step end destroys.',
    beanDefinitionImpact: 'Bean definition scoped to step with CGLIB proxy.',
    beanPostProcessor: 'Scope registration in batch context.',
    proxy: 'CGLIB scoped proxy — inject into singleton step @Bean methods.',
    runtimeInterception: 'Proxy resolves target per step execution with job parameters.',
    productionUse: 'ItemReader with #{jobParameters[fileName]} path; partition workers.',
    interviewQuestion: '@StepScope vs @JobScope — lifecycle difference?',
    interviewImportance: 'must',
    versionNotes: 'SpEL #{jobParameters[...]} and #{stepExecutionContext[...]}.',
    category: 'Spring Batch — scoping',
  }),
  eco({
    annotation: '@JobScope',
    fqn: 'org.springframework.batch.core.configuration.annotation.JobScope',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.configuration.annotation',
    owner: 'Spring Batch',
    introduced: '4.1',
    target: 'TYPE, METHOD',
    purpose: 'Scoped proxy bean per Job execution — wider than @StepScope, shared across steps in same job.',
    processor: 'BatchScopeConfigurationRegistrar.',
    phase: 'Job start to job completion scope.',
    beanDefinitionImpact: 'Job-scoped bean definition with proxy.',
    beanPostProcessor: 'Batch scope post-processors.',
    proxy: 'CGLIB scoped proxy.',
    runtimeInterception: 'Resolves per JobExecution.',
    productionUse: 'Shared job-level counters, audit context across steps.',
    interviewQuestion: 'Can @JobScope bean see step execution context?',
    interviewImportance: 'high',
    versionNotes: 'Less common than @StepScope in chunk jobs.',
    category: 'Spring Batch — scoping',
  }),
  eco({
    annotation: '@BeforeStep',
    fqn: 'org.springframework.batch.core.annotation.BeforeStep',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Callback before Step executes — inject StepExecution via method parameter.',
    processor: 'StepListenerFactoryBean / annotation-driven listener registration.',
    phase: 'Immediately before step execution starts.',
    beanDefinitionImpact: 'Registers step listener on Step builder.',
    beanPostProcessor: 'Annotation-driven listener discovery.',
    proxy: 'None.',
    runtimeInterception: 'StepExecutionListener.beforeStep hook.',
    productionUse: 'Initialize step resources, log partition id, validate preconditions.',
    interviewQuestion: '@BeforeStep vs Tasklet before logic?',
    interviewImportance: 'medium',
    versionNotes: 'Method must accept StepExecution parameter.',
    category: 'Spring Batch — listeners',
  }),
  eco({
    annotation: '@AfterStep',
    fqn: 'org.springframework.batch.core.annotation.AfterStep',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Callback after Step completes — inspect ExitStatus, persist metrics.',
    processor: 'StepListenerFactoryBean.',
    phase: 'After step finishes (success or failure).',
    beanDefinitionImpact: 'Step listener registration.',
    beanPostProcessor: 'Annotation-driven listener discovery.',
    proxy: 'None.',
    runtimeInterception: 'StepExecutionListener.afterStep hook.',
    productionUse: 'Cleanup temp files, emit step metrics to monitoring.',
    interviewQuestion: 'Can @AfterStep change ExitStatus?',
    interviewImportance: 'medium',
    versionNotes: 'Return ExitStatus to override step exit.',
    category: 'Spring Batch — listeners',
  }),
  eco({
    annotation: '@BeforeJob',
    fqn: 'org.springframework.batch.core.annotation.BeforeJob',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Job-level listener invoked before JobExecution starts.',
    processor: 'JobListenerFactoryBean / annotation listener.',
    phase: 'Before job run.',
    beanDefinitionImpact: 'Job listener on Job builder.',
    beanPostProcessor: 'Listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'JobExecutionListener.beforeJob.',
    productionUse: 'Global job audit start, parameter validation.',
    interviewQuestion: '@BeforeJob on @Component vs JobExecutionListener bean?',
    interviewImportance: 'medium',
    versionNotes: 'JobExecution parameter injection supported.',
    category: 'Spring Batch — listeners',
  }),
  eco({
    annotation: '@AfterJob',
    fqn: 'org.springframework.batch.core.annotation.AfterJob',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Job-level listener after JobExecution completes.',
    processor: 'JobListenerFactoryBean.',
    phase: 'After job terminal state.',
    beanDefinitionImpact: 'Job listener registration.',
    beanPostProcessor: 'Listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'JobExecutionListener.afterJob.',
    productionUse: 'Send completion notification, archive job report.',
    interviewQuestion: 'Restart failed job — is @AfterJob called again?',
    interviewImportance: 'medium',
    versionNotes: 'Called on each job attempt completion.',
    category: 'Spring Batch — listeners',
  }),
  eco({
    annotation: '@OnSkipInRead',
    fqn: 'org.springframework.batch.core.annotation.OnSkipInRead',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Skip listener when ItemReader throws skippable exception.',
    processor: 'SkipListenerFactoryBean registers skip callback.',
    phase: 'During chunk processing on read skip.',
    beanDefinitionImpact: 'SkipListener on fault-tolerant step.',
    beanPostProcessor: 'Annotation skip listener discovery.',
    proxy: 'None.',
    runtimeInterception: 'SkipListener.onSkipInRead.',
    productionUse: 'Log bad records, write to skip file, metrics on read failures.',
    interviewQuestion: 'Skip vs retry policy — who decides?',
    interviewImportance: 'high',
    versionNotes: 'Requires faultTolerant() and skip limit on step.',
    category: 'Spring Batch — skip/error listeners',
  }),
  eco({
    annotation: '@OnSkipInProcess',
    fqn: 'org.springframework.batch.core.annotation.OnSkipInProcess',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Skip listener when ItemProcessor throws skippable exception.',
    processor: 'SkipListenerFactoryBean.',
    phase: 'Chunk process phase on skip.',
    beanDefinitionImpact: 'SkipListener endpoint on step.',
    beanPostProcessor: 'Skip listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'SkipListener.onSkipInProcess.',
    productionUse: 'Quarantine invalid business records during bulk import.',
    interviewQuestion: 'Difference between skip listener and @OnProcessError?',
    interviewImportance: 'medium',
    versionNotes: 'Skip = policy allowed; error listener = after retry exhausted.',
    category: 'Spring Batch — skip/error listeners',
  }),
  eco({
    annotation: '@OnSkipInWrite',
    fqn: 'org.springframework.batch.core.annotation.OnSkipInWrite',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '2.0',
    target: 'METHOD',
    purpose: 'Skip listener when ItemWriter throws skippable exception.',
    processor: 'SkipListenerFactoryBean.',
    phase: 'Chunk write phase on skip.',
    beanDefinitionImpact: 'SkipListener on step.',
    beanPostProcessor: 'Skip listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'SkipListener.onSkipInWrite.',
    productionUse: 'Handle DB constraint violations on bulk insert with skip audit.',
    interviewQuestion: 'Skip limit exceeded — what happens?',
    interviewImportance: 'high',
    versionNotes: 'Step fails when skip count exceeds limit.',
    category: 'Spring Batch — skip/error listeners',
  }),
  eco({
    annotation: '@OnReadError',
    fqn: 'org.springframework.batch.core.annotation.OnReadError',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '4.2',
    target: 'METHOD',
    purpose: 'Error listener after read failure when retries exhausted (non-skippable or skip disabled).',
    processor: 'ItemReadListener / annotation error listener factory.',
    phase: 'On read error terminal path.',
    beanDefinitionImpact: 'ItemReadListener registration.',
    beanPostProcessor: 'Error listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'onReadError callback with exception and item context.',
    productionUse: 'Dead-letter bad lines, alert on persistent read failures.',
    interviewQuestion: '@OnReadError vs @OnSkipInRead ordering?',
    interviewImportance: 'medium',
    versionNotes: 'Part of fault-tolerant step error handling family.',
    category: 'Spring Batch — skip/error listeners',
  }),
  eco({
    annotation: '@OnProcessError',
    fqn: 'org.springframework.batch.core.annotation.OnProcessError',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '4.2',
    target: 'METHOD',
    purpose: 'Error listener after processor failure when retries exhausted.',
    processor: 'ItemProcessListener error hook.',
    phase: 'Process error terminal path.',
    beanDefinitionImpact: 'ItemProcessListener registration.',
    beanPostProcessor: 'Error listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'onProcessError with item and exception.',
    productionUse: 'Capture failed DTO for manual review queue.',
    interviewQuestion: 'How configure retry vs skip for processor?',
    interviewImportance: 'medium',
    versionNotes: 'retryLimit, skip(Exception.class) on step builder.',
    category: 'Spring Batch — skip/error listeners',
  }),
  eco({
    annotation: '@OnWriteError',
    fqn: 'org.springframework.batch.core.annotation.OnWriteError',
    module: 'spring-batch',
    packageName: 'org.springframework.batch.core.annotation',
    owner: 'Spring Batch',
    introduced: '4.2',
    target: 'METHOD',
    purpose: 'Error listener after writer failure when retries exhausted.',
    processor: 'ItemWriteListener error hook.',
    phase: 'Write error terminal path.',
    beanDefinitionImpact: 'ItemWriteListener registration.',
    beanPostProcessor: 'Error listener annotation processing.',
    proxy: 'None.',
    runtimeInterception: 'onWriteError with chunk items and exception.',
    productionUse: 'Partial chunk write failure handling, compensating actions.',
    interviewQuestion: 'Chunk-oriented transaction rollback on write error?',
    interviewImportance: 'high',
    versionNotes: 'Whole chunk rolls back unless skip/retry configured.',
    category: 'Spring Batch — skip/error listeners',
  }),

  eco({
    annotation: '@EnableConfigServer',
    fqn: 'org.springframework.cloud.config.server.config.EnableConfigServer',
    module: 'spring-cloud-config',
    packageName: 'org.springframework.cloud.config.server.config',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Enables Config Server serving properties from Git/Vault/filesystem.',
    processor: 'ConfigServerConfiguration imports EnvironmentRepository.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableConfigServer do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Cloud Config',
  }),
  eco({
    annotation: '@RefreshScope',
    fqn: 'org.springframework.cloud.context.config.annotation.RefreshScope',
    module: 'spring-cloud-context',
    packageName: 'org.springframework.cloud.context.config.annotation',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Bean recreated on /actuator/refresh after Environment change.',
    processor: 'RefreshScope scoped proxy factory.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'CGLIB scoped proxy.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Dynamic config from Config Server without restart.',
    interviewQuestion: 'What does @RefreshScope do?',
    interviewImportance: 'must',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Cloud Context',
  }),
  eco({
    annotation: '@EnableFeignClients',
    fqn: 'org.springframework.cloud.openfeign.EnableFeignClients',
    module: 'spring-cloud-openfeign',
    packageName: 'org.springframework.cloud.openfeign',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Scans @FeignClient interfaces for declarative HTTP clients.',
    processor: 'FeignClientsRegistrar.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableFeignClients do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Cloud OpenFeign',
  }),
  eco({
    annotation: '@FeignClient',
    fqn: 'org.springframework.cloud.openfeign.FeignClient',
    module: 'spring-cloud-openfeign',
    packageName: 'org.springframework.cloud.openfeign',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Declares Feign HTTP client interface for remote service.',
    processor: 'FeignClientFactoryBean JDK proxy.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'JDK dynamic proxy.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @FeignClient do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Cloud OpenFeign',
  }),
  eco({
    annotation: '@LoadBalanced',
    fqn: 'org.springframework.cloud.client.loadbalancer.LoadBalanced',
    module: 'spring-cloud-loadbalancer',
    packageName: 'org.springframework.cloud.client.loadbalancer',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Marks RestTemplate/WebClient for client-side load balancing.',
    processor: 'LoadBalancerAutoConfiguration interceptor.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'Interceptor-based LB.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @LoadBalanced do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Cloud LoadBalancer',
  }),
  eco({
    annotation: '@EnableDiscoveryClient',
    fqn: 'org.springframework.cloud.client.discovery.EnableDiscoveryClient',
    module: 'spring-cloud-commons',
    packageName: 'org.springframework.cloud.client.discovery',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Registers app with service registry (Eureka, Consul).',
    processor: 'DiscoveryClient auto-config lifecycle.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableDiscoveryClient do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Cloud Discovery',
  }),
  eco({
    annotation: '@EnableBinding',
    fqn: 'org.springframework.cloud.stream.annotation.EnableBinding',
    module: 'spring-cloud-stream-legacy',
    packageName: 'org.springframework.cloud.stream.annotation',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: '3.x+',
    status: 'deprecated',
    target: 'TYPE, METHOD',
    purpose: 'Legacy binding interface to middleware channels.',
    processor: 'BindableProxyFactory (removed).',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableBinding do?',
    interviewImportance: 'high',
    versionNotes: 'Migrate to spring.cloud.function.definition functional model.',
    category: 'Spring Cloud Stream (legacy)',
  }),
  eco({
    annotation: '@Input',
    fqn: 'org.springframework.cloud.stream.annotation.Input',
    module: 'spring-cloud-stream-legacy',
    packageName: 'org.springframework.cloud.stream.annotation',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: '3.x+',
    status: 'deprecated',
    target: 'TYPE, METHOD',
    purpose: 'Legacy inbound channel on binding interface.',
    processor: 'Binding proxy method.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Input do?',
    interviewImportance: 'medium',
    versionNotes: 'Use Consumer<T> bean.',
    category: 'Spring Cloud Stream (legacy)',
  }),
  eco({
    annotation: '@Output',
    fqn: 'org.springframework.cloud.stream.annotation.Output',
    module: 'spring-cloud-stream-legacy',
    packageName: 'org.springframework.cloud.stream.annotation',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: '3.x+',
    status: 'deprecated',
    target: 'TYPE, METHOD',
    purpose: 'Legacy outbound channel on binding interface.',
    processor: 'Binding proxy method.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Output do?',
    interviewImportance: 'medium',
    versionNotes: 'Use Supplier or StreamBridge.',
    category: 'Spring Cloud Stream (legacy)',
  }),
  eco({
    annotation: '@StreamListener',
    fqn: 'org.springframework.cloud.stream.annotation.StreamListener',
    module: 'spring-cloud-stream-legacy',
    packageName: 'org.springframework.cloud.stream.annotation',
    owner: 'Spring Cloud',
    introduced: 'module-specific',
    deprecated: '3.x+',
    status: 'deprecated',
    target: 'TYPE, METHOD',
    purpose: 'Legacy message handler on input binding.',
    processor: 'StreamListenerAnnotationBeanPostProcessor (removed).',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @StreamListener do?',
    interviewImportance: 'high',
    versionNotes: '@Bean Consumer<T> with function definition.',
    category: 'Spring Cloud Stream (legacy)',
  }),
  eco({
    annotation: '@EnableRedisHttpSession',
    fqn: 'org.springframework.session.data.redis.config.annotation.web.http.EnableRedisHttpSession',
    module: 'spring-session-data-redis',
    packageName: 'org.springframework.session.data.redis.config.annotation.web.http',
    owner: 'Spring Session',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'HttpSession stored in Redis for horizontal scaling.',
    processor: 'RedisHttpSessionConfiguration + SessionRepositoryFilter.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableRedisHttpSession do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Session',
  }),
  eco({
    annotation: '@EnableJdbcHttpSession',
    fqn: 'org.springframework.session.jdbc.config.annotation.web.http.EnableJdbcHttpSession',
    module: 'spring-session-jdbc',
    packageName: 'org.springframework.session.jdbc.config.annotation.web.http',
    owner: 'Spring Session',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'HttpSession persisted to JDBC SPRING_SESSION tables.',
    processor: 'JdbcHttpSessionConfiguration.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableJdbcHttpSession do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Session',
  }),
  eco({
    annotation: '@EnableSpringHttpSession',
    fqn: 'org.springframework.session.config.annotation.web.http.EnableSpringHttpSession',
    module: 'spring-session-core',
    packageName: 'org.springframework.session.config.annotation.web.http',
    owner: 'Spring Session',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Generic HTTP session when custom SessionRepository @Bean provided.',
    processor: 'SpringHttpSessionConfiguration.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableSpringHttpSession do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Session',
  }),
  eco({
    annotation: '@EnableHypermediaSupport',
    fqn: 'org.springframework.hateoas.config.EnableHypermediaSupport',
    module: 'spring-hateoas',
    packageName: 'org.springframework.hateoas.config',
    owner: 'Spring HATEOAS',
    introduced: 'module-specific',
    deprecated: '1.0+',
    status: 'deprecated',
    target: 'TYPE',
    purpose: 'Legacy hypermedia enable (superseded by Boot auto-config).',
    processor: 'HypermediaSupportBeanDefinitionRegistrar.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableHypermediaSupport do?',
    interviewImportance: 'low',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring HATEOAS',
  }),
  eco({
    annotation: 'EntityModel<T> (class)',
    fqn: 'org.springframework.hateoas.EntityModel',
    module: 'spring-hateoas',
    packageName: 'org.springframework.hateoas',
    owner: 'Spring HATEOAS',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'N/A — type',
    purpose: 'Wrapper adding hypermedia links around single domain object.',
    processor: 'HalJackson2Module serialization.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does EntityModel<T> (class) do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring HATEOAS — model types',
  }),
  eco({
    annotation: 'RepresentationModel<T> (class)',
    fqn: 'org.springframework.hateoas.RepresentationModel',
    module: 'spring-hateoas',
    packageName: 'org.springframework.hateoas',
    owner: 'Spring HATEOAS',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'N/A — base class',
    purpose: 'Base hypermedia type carrying Link collection for HAL responses.',
    processor: 'WebMvcLinkBuilder + Jackson HAL module.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does RepresentationModel<T> (class) do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring HATEOAS — model types',
  }),
  eco({
    annotation: '@EnableJdbcRepositories',
    fqn: 'org.springframework.data.jdbc.repository.config.EnableJdbcRepositories',
    module: 'spring-data-jdbc',
    packageName: 'org.springframework.data.jdbc.repository.config',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Enables Spring Data JDBC repository scanning.',
    processor: 'JdbcRepositoryConfigurationExtension.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableJdbcRepositories do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data JDBC',
  }),
  eco({
    annotation: '@MappedCollection',
    fqn: 'org.springframework.data.relational.core.mapping.MappedCollection',
    module: 'spring-data-jdbc',
    packageName: 'org.springframework.data.relational.core.mapping',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Maps embedded collection of child rows in aggregate root table model.',
    processor: 'RelationalMappingContext.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @MappedCollection do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data JDBC',
  }),
  eco({
    annotation: '@ReadOnlyProperty',
    fqn: 'org.springframework.data.annotation.ReadOnlyProperty',
    module: 'spring-data-commons',
    packageName: 'org.springframework.data.annotation',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Marks property read-only on persist — excluded from INSERT/UPDATE.',
    processor: 'RelationalPersistentProperty metadata.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @ReadOnlyProperty do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data JDBC',
  }),
  eco({
    annotation: '@Document',
    fqn: 'org.springframework.data.mongodb.core.mapping.Document',
    module: 'spring-data-mongodb',
    packageName: 'org.springframework.data.mongodb.core.mapping',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Maps class to MongoDB collection (NOT JPA @Entity).',
    processor: 'MappingMongoConverter / MongoPersistentEntity.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Document do?',
    interviewImportance: 'must',
    versionNotes: 'Mongo @Document — distinguish from Elasticsearch @Document via module field.',
    category: 'Spring Data MongoDB',
  }),
  eco({
    annotation: '@Field',
    fqn: 'org.springframework.data.mongodb.core.mapping.Field',
    module: 'spring-data-mongodb',
    packageName: 'org.springframework.data.mongodb.core.mapping',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Custom BSON field name or write strategy on document property.',
    processor: 'Mongo mapping metadata.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Field do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data MongoDB',
  }),
  eco({
    annotation: '@DBRef',
    fqn: 'org.springframework.data.mongodb.core.mapping.DBRef',
    module: 'spring-data-mongodb',
    packageName: 'org.springframework.data.mongodb.core.mapping',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Reference to another document — lazy/eager DBRef resolution.',
    processor: 'DBRefResolver on read.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @DBRef do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data MongoDB',
  }),
  eco({
    annotation: '@EnableMongoRepositories',
    fqn: 'org.springframework.data.mongodb.repository.config.EnableMongoRepositories',
    module: 'spring-data-mongodb',
    packageName: 'org.springframework.data.mongodb.repository.config',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Scans MongoDB repository interfaces.',
    processor: 'MongoRepositoryConfigurationExtension.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableMongoRepositories do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data MongoDB',
  }),
  eco({
    annotation: '@Indexed',
    fqn: 'org.springframework.data.mongodb.core.index.Indexed',
    module: 'spring-data-mongodb',
    packageName: 'org.springframework.data.mongodb.core.index',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Declares MongoDB index on field — created at startup if auto-index.',
    processor: 'MongoPersistentEntityIndexCreator.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Indexed do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data MongoDB',
  }),
  eco({
    annotation: '@RedisHash',
    fqn: 'org.springframework.data.redis.core.RedisHash',
    module: 'spring-data-redis',
    packageName: 'org.springframework.data.redis.core',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Maps object to Redis hash keyspace.',
    processor: 'RedisMappingContext.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @RedisHash do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data Redis',
  }),
  eco({
    annotation: '@TimeToLive',
    fqn: 'org.springframework.data.redis.core.TimeToLive',
    module: 'spring-data-redis',
    packageName: 'org.springframework.data.redis.core',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'TTL seconds on Redis hash/object expiration.',
    processor: 'RedisKeyValueAdapter TTL.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @TimeToLive do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data Redis',
  }),
  eco({
    annotation: '@EnableRedisRepositories',
    fqn: 'org.springframework.data.redis.repository.configuration.EnableRedisRepositories',
    module: 'spring-data-redis',
    packageName: 'org.springframework.data.redis.repository.configuration',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Enables Spring Data Redis repositories.',
    processor: 'RedisRepositoriesRegistrar.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableRedisRepositories do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data Redis',
  }),
  eco({
    annotation: '@Document',
    fqn: 'org.springframework.data.elasticsearch.annotations.Document',
    module: 'spring-data-elasticsearch',
    packageName: 'org.springframework.data.elasticsearch.annotations',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Maps class to Elasticsearch index (NOT Mongo @Document).',
    processor: 'ElasticsearchPersistentEntity.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Document do?',
    interviewImportance: 'high',
    versionNotes: 'Elasticsearch module — indexName attribute; not spring-data-mongodb.',
    category: 'Spring Data Elasticsearch',
  }),
  eco({
    annotation: '@Field',
    fqn: 'org.springframework.data.elasticsearch.annotations.Field',
    module: 'spring-data-elasticsearch',
    packageName: 'org.springframework.data.elasticsearch.annotations',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Field mapping type/analyzer for ES document property.',
    processor: 'Elasticsearch mapping converter.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Field do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data Elasticsearch',
  }),
  eco({
    annotation: '@EnableElasticsearchRepositories',
    fqn: 'org.springframework.data.elasticsearch.repository.config.EnableElasticsearchRepositories',
    module: 'spring-data-elasticsearch',
    packageName: 'org.springframework.data.elasticsearch.repository.config',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Scans Elasticsearch repository interfaces.',
    processor: 'ElasticsearchRepositoryConfigExtension.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EnableElasticsearchRepositories do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data Elasticsearch',
  }),
  eco({
    annotation: '@RepositoryRestResource',
    fqn: 'org.springframework.data.rest.core.annotation.RepositoryRestResource',
    module: 'spring-data-rest',
    packageName: 'org.springframework.data.rest.core.annotation',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Exposes repository as hypermedia REST resource with path/customization.',
    processor: 'RepositoryRestHandlerMapping.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @RepositoryRestResource do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data REST',
  }),
  eco({
    annotation: '@RestResource',
    fqn: 'org.springframework.data.rest.core.annotation.RestResource',
    module: 'spring-data-rest',
    packageName: 'org.springframework.data.rest.core.annotation',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Customizes exported repository method path/description in REST layer.',
    processor: 'RepositoryEntityController.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @RestResource do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data REST',
  }),
  eco({
    annotation: '@Projection',
    fqn: 'org.springframework.data.rest.core.config.Projection',
    module: 'spring-data-rest',
    packageName: 'org.springframework.data.rest.core.config',
    owner: 'Spring Data',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Interface projection for abbreviated REST representation.',
    processor: 'ProjectionFactory on exported resources.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Projection do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Data REST',
  }),
  eco({
    annotation: '@DataJdbcTest',
    fqn: 'org.springframework.boot.test.autoconfigure.jdbc.DataJdbcTest',
    module: 'spring-boot-test-autoconfigure',
    packageName: 'org.springframework.boot.test.autoconfigure.jdbc',
    owner: 'Spring Boot',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Slice test: JDBC + Spring Data JDBC only, embedded DB, no full context.',
    processor: 'DataJdbcTestContextBootstrapper.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @DataJdbcTest do?',
    interviewImportance: 'high',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Boot Test — Data JDBC',
  }),
  eco({
    annotation: '@DataRedisTest',
    fqn: 'org.springframework.boot.test.autoconfigure.data.redis.DataRedisTest',
    module: 'spring-boot-test-autoconfigure',
    packageName: 'org.springframework.boot.test.autoconfigure.data.redis',
    owner: 'Spring Boot',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Slice test: Redis + Spring Data Redis with embedded or Testcontainers Redis.',
    processor: 'DataRedisTestContextBootstrapper.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @DataRedisTest do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Boot Test — Data Redis',
  }),
  eco({
    annotation: '@GraphQlTest',
    fqn: 'org.springframework.boot.test.autoconfigure.graphql.tester.GraphQlTest',
    module: 'spring-boot-test-autoconfigure',
    packageName: 'org.springframework.boot.test.autoconfigure.graphql.tester',
    owner: 'Spring Boot',
    introduced: 'Boot 3.2',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Slice test for GraphQL controllers/resolvers without full web stack.',
    processor: 'GraphQlTestContextBootstrapper.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @GraphQlTest do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Boot Test — GraphQL',
  }),
  eco({
    annotation: '@SqlGroup',
    fqn: 'org.junit.jupiter.api.sql.SqlGroup',
    module: 'junit-jupiter',
    packageName: 'org.junit.jupiter.api.sql',
    owner: 'JUnit',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Aggregates multiple @Sql scripts into ordered group for test method/class.',
    processor: 'JUnit Jupiter extension — not Spring processor.',
    phase: 'Test execution before/after method.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @SqlGroup do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'JUnit 5 — SQL testing',
  }),
  eco({
    annotation: '@WebEndpoint',
    fqn: 'org.springframework.boot.actuate.endpoint.web.annotation.WebEndpoint',
    module: 'spring-boot-actuator',
    packageName: 'org.springframework.boot.actuate.endpoint.web.annotation',
    owner: 'Spring Boot',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Marks custom actuator endpoint exposed over HTTP web extension.',
    processor: 'WebEndpointDiscoverer.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @WebEndpoint do?',
    interviewImportance: 'medium',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Boot Actuator',
  }),
  eco({
    annotation: '@Selector',
    fqn: 'org.springframework.boot.actuate.endpoint.annotation.Selector',
    module: 'spring-boot-actuator',
    packageName: 'org.springframework.boot.actuate.endpoint.annotation',
    owner: 'Spring Boot',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Path selector variable on @Endpoint operation method (e.g. {id}).',
    processor: 'Endpoint operation invocation model.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Selector do?',
    interviewImportance: 'niche',
    versionNotes: 'Boot 3 / SF 6 baseline.',
    category: 'Spring Boot Actuator',
  }),
  eco({
    annotation: '@Entity',
    fqn: 'jakarta.persistence.Entity',
    module: 'jakarta-persistence',
    packageName: 'jakarta.persistence',
    owner: 'Jakarta Persistence',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'JPA entity mapping — NOT a Spring annotation. Hibernate is provider; Spring Data JPA integrates EntityManager.',
    processor: 'Hibernate MetadataBuilder / EMF bootstrap — not Spring BPP.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Entity do?',
    interviewImportance: 'must',
    versionNotes: 'Interview trap: @Entity is jakarta.persistence, not org.springframework. Boot @EntityScan scans packages.',
    category: 'Jakarta Persistence — ownership',
  }),
  eco({
    annotation: '@Id',
    fqn: 'jakarta.persistence.Id',
    module: 'jakarta-persistence',
    packageName: 'jakarta.persistence',
    owner: 'Jakarta Persistence',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'JPA primary key marker — Jakarta spec, not Spring.',
    processor: 'ORM provider metadata at EMF startup.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @Id do?',
    interviewImportance: 'must',
    versionNotes: 'Pair with @GeneratedValue — still Jakarta API.',
    category: 'Jakarta Persistence — ownership',
  }),
  eco({
    annotation: '@EntityScan',
    fqn: 'org.springframework.boot.autoconfigure.domain.EntityScan',
    module: 'spring-boot-autoconfigure',
    packageName: 'org.springframework.boot.autoconfigure.domain',
    owner: 'Spring Boot',
    introduced: 'module-specific',
    deprecated: 'no',
    status: 'current',
    target: 'TYPE, METHOD',
    purpose: 'Spring Boot scans packages for JPA @Entity classes — this IS Spring.',
    processor: 'EntityScanPackagesRegistrar.',
    phase: 'Context refresh / runtime per module conventions.',
    beanDefinitionImpact: 'Module-specific bean or endpoint registration.',
    beanPostProcessor: 'Module annotation processors.',
    proxy: 'None.',
    runtimeInterception: 'Module runtime behavior.',
    productionUse: 'Enterprise microservices and data pipelines.',
    interviewQuestion: 'What does @EntityScan do?',
    interviewImportance: 'high',
    versionNotes: 'Distinguish @EntityScan (Spring Boot) from @Entity (Jakarta).',
    category: 'Spring Boot — JPA integration',
  }),
];

export type OwnershipRow = {
  annotation: string;
  owner: string;
  packageName: string;
  dependency: string;
};

export const OWNERSHIP_MATRIX: OwnershipRow[] = [
  {annotation: '@Component', owner: 'Spring Framework', packageName: 'org.springframework.stereotype', dependency: 'spring-context'},
  {annotation: '@Autowired', owner: 'Spring Framework', packageName: 'org.springframework.beans.factory.annotation', dependency: 'spring-beans'},
  {annotation: '@Configuration', owner: 'Spring Framework', packageName: 'org.springframework.context.annotation', dependency: 'spring-context'},
  {annotation: '@Bean', owner: 'Spring Framework', packageName: 'org.springframework.context.annotation', dependency: 'spring-context'},
  {annotation: '@Transactional', owner: 'Spring Framework', packageName: 'org.springframework.transaction.annotation', dependency: 'spring-tx'},
  {annotation: '@EnableWebSecurity', owner: 'Spring Security', packageName: 'org.springframework.security.config.annotation.web.configuration', dependency: 'spring-security-config'},
  {annotation: '@PreAuthorize', owner: 'Spring Security', packageName: 'org.springframework.security.access.prepost', dependency: 'spring-security-config'},
  {annotation: '@EnableKafka', owner: 'Spring Kafka', packageName: 'org.springframework.kafka.annotation', dependency: 'spring-kafka'},
  {annotation: '@KafkaListener', owner: 'Spring Kafka', packageName: 'org.springframework.kafka.annotation', dependency: 'spring-kafka'},
  {annotation: '@EnableBatchProcessing', owner: 'Spring Batch', packageName: 'org.springframework.batch.core.configuration.annotation', dependency: 'spring-batch-core'},
  {annotation: '@StepScope', owner: 'Spring Batch', packageName: 'org.springframework.batch.core.configuration.annotation', dependency: 'spring-batch-core'},
  {annotation: '@EnableIntegration', owner: 'Spring Integration', packageName: 'org.springframework.integration.config', dependency: 'spring-integration-core'},
  {annotation: '@ServiceActivator', owner: 'Spring Integration', packageName: 'org.springframework.integration.annotation', dependency: 'spring-integration-core'},
  {annotation: '@EnableConfigServer', owner: 'Spring Cloud', packageName: 'org.springframework.cloud.config.server.config', dependency: 'spring-cloud-config-server'},
  {annotation: '@RefreshScope', owner: 'Spring Cloud', packageName: 'org.springframework.cloud.context.config.annotation', dependency: 'spring-cloud-context'},
  {annotation: '@FeignClient', owner: 'Spring Cloud', packageName: 'org.springframework.cloud.openfeign', dependency: 'spring-cloud-starter-openfeign'},
  {annotation: '@LoadBalanced', owner: 'Spring Cloud', packageName: 'org.springframework.cloud.client.loadbalancer', dependency: 'spring-cloud-starter-loadbalancer'},
  {annotation: '@EnableDiscoveryClient', owner: 'Spring Cloud', packageName: 'org.springframework.cloud.client.discovery', dependency: 'spring-cloud-commons'},
  {annotation: '@EnableBinding', owner: 'Spring Cloud', packageName: 'org.springframework.cloud.stream.annotation', dependency: 'spring-cloud-stream (legacy)'},
  {annotation: '@EnableRedisHttpSession', owner: 'Spring Session', packageName: 'org.springframework.session.data.redis.config.annotation.web.http', dependency: 'spring-session-data-redis'},
  {annotation: '@RepositoryRestResource', owner: 'Spring Data', packageName: 'org.springframework.data.rest.core.annotation', dependency: 'spring-boot-starter-data-rest'},
  {annotation: '@EnableJpaRepositories', owner: 'Spring Data', packageName: 'org.springframework.data.jpa.repository.config', dependency: 'spring-boot-starter-data-jpa'},
  {annotation: '@Query', owner: 'Spring Data', packageName: 'org.springframework.data.jpa.repository', dependency: 'spring-data-jpa'},
  {annotation: '@Document (Mongo)', owner: 'Spring Data', packageName: 'org.springframework.data.mongodb.core.mapping', dependency: 'spring-boot-starter-data-mongodb'},
  {annotation: '@Document (ES)', owner: 'Spring Data', packageName: 'org.springframework.data.elasticsearch.annotations', dependency: 'spring-boot-starter-data-elasticsearch'},
  {annotation: '@RedisHash', owner: 'Spring Data', packageName: 'org.springframework.data.redis.core', dependency: 'spring-boot-starter-data-redis'},
  {annotation: '@EnableJdbcRepositories', owner: 'Spring Data', packageName: 'org.springframework.data.jdbc.repository.config', dependency: 'spring-boot-starter-data-jdbc'},
  {annotation: '@Entity', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@Id', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@Table', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@Column', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@NotNull', owner: 'Jakarta Validation', packageName: 'jakarta.validation.constraints', dependency: 'jakarta.validation-api'},
  {annotation: '@Valid', owner: 'Jakarta Validation', packageName: 'jakarta.validation', dependency: 'jakarta.validation-api'},
  {annotation: '@EntityListeners', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@GeneratedValue', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@Version', owner: 'Jakarta Persistence', packageName: 'jakarta.persistence', dependency: 'jakarta.persistence-api'},
  {annotation: '@SQLDelete', owner: 'Hibernate', packageName: 'org.hibernate.annotations', dependency: 'hibernate-core'},
  {annotation: '@Filter', owner: 'Hibernate', packageName: 'org.hibernate.annotations', dependency: 'hibernate-core'},
  {annotation: '@SpringBootApplication', owner: 'Spring Boot', packageName: 'org.springframework.boot.autoconfigure', dependency: 'spring-boot'},
  {annotation: '@RestController', owner: 'Spring Framework', packageName: 'org.springframework.web.bind.annotation', dependency: 'spring-web'},
  {annotation: '@ConditionalOnProperty', owner: 'Spring Boot', packageName: 'org.springframework.boot.autoconfigure.condition', dependency: 'spring-boot-autoconfigure'},
  {annotation: '@DataJpaTest', owner: 'Spring Boot', packageName: 'org.springframework.boot.test.autoconfigure.orm.jpa', dependency: 'spring-boot-starter-test'},
  {annotation: '@WebMvcTest', owner: 'Spring Boot', packageName: 'org.springframework.boot.test.autoconfigure.web.servlet', dependency: 'spring-boot-starter-test'},
  {annotation: '@MockBean', owner: 'Spring Boot', packageName: 'org.springframework.boot.test.mock.mockito', dependency: 'spring-boot-test'},
  {annotation: '@Test', owner: 'JUnit', packageName: 'org.junit.jupiter.api', dependency: 'junit-jupiter-api'},
  {annotation: '@ExtendWith', owner: 'JUnit', packageName: 'org.junit.jupiter.api.extension', dependency: 'junit-jupiter-api'},
  {annotation: '@Mock', owner: 'Mockito', packageName: 'org.mockito', dependency: 'mockito-core'},
  {annotation: '@InjectMocks', owner: 'Mockito', packageName: 'org.mockito', dependency: 'mockito-core'},
  {annotation: '@Sql', owner: 'Spring Framework', packageName: 'org.springframework.test.context.jdbc', dependency: 'spring-test'},
  {annotation: '@DirtiesContext', owner: 'Spring Framework', packageName: 'org.springframework.test.annotation', dependency: 'spring-test'},
];

export const OWNERSHIP_MATRIX_COUNT = OWNERSHIP_MATRIX.length;

export const INVENTORY_ECOSYSTEM_COUNT = INVENTORY_ECOSYSTEM.length;

export const ECOSYSTEM_STATS = {
  inventoryTotal: INVENTORY_ECOSYSTEM.length,
  ownershipTotal: OWNERSHIP_MATRIX.length,
  deprecated: INVENTORY_ECOSYSTEM.filter((r) => r.status === 'deprecated' || r.status === 'legacy').length,
  mustInterview: INVENTORY_ECOSYSTEM.filter((r) => r.interviewImportance === 'must').length,
  categories: [...new Set(INVENTORY_ECOSYSTEM.map((r) => r.category))].length,
} as const;
