/** Part 12–14: proxy matrix, processor cheat sheet, ordering, payment trace, who-processes Q&A. */

export const PROXY_MATRIX: {
  annotation: string;
  proxy: string;
  why: string;
  exception: string;
}[] = [
  {annotation: '@Transactional', proxy: 'CGLIB or JDK (class vs interface)', why: 'TransactionInterceptor opens/commits/rolls back around public methods', exception: 'Self-invocation, non-public, final class/method, REQUIRES_NEW on private via proxy bypass'},
  {annotation: '@Async', proxy: 'CGLIB (AsyncAnnotationBeanPostProcessor)', why: 'AsyncExecutionInterceptor submits to TaskExecutor instead of caller thread', exception: 'Self-invocation; return type void/Future/CompletableFuture only; @Async on @Configuration class method'},
  {annotation: '@Cacheable', proxy: 'CGLIB/JDK via CacheInterceptor', why: 'MethodInterceptor checks CacheManager before invoking target', exception: 'Self-invocation; internal calls skip cache; unless=true still needs proxy'},
  {annotation: '@CacheEvict', proxy: 'CGLIB/JDK', why: 'Evicts cache entries before/after advised method', exception: 'Self-invocation; allEntries=true on wrong cache name'},
  {annotation: '@CachePut', proxy: 'CGLIB/JDK', why: 'Always invokes method then stores result in cache', exception: 'Self-invocation'},
  {annotation: '@PreAuthorize', proxy: 'CGLIB/JDK (MethodSecurityInterceptor)', why: 'Evaluates SpEL before method entry via AuthorizationManager', exception: 'Self-invocation; method must be public; interface-only JDK proxy needs secured interface method'},
  {annotation: '@PostAuthorize', proxy: 'CGLIB/JDK', why: 'Evaluates SpEL on return value after method', exception: 'Self-invocation; null return breaks some expressions'},
  {annotation: '@Secured', proxy: 'CGLIB/JDK', why: 'Legacy role check via MethodSecurityInterceptor', exception: 'Self-invocation; ROLE_ prefix required'},
  {annotation: '@RolesAllowed', proxy: 'CGLIB/JDK (JSR-250)', why: 'Jakarta @RolesAllowed bridged to Spring Security', exception: 'Needs @EnableMethodSecurity'},
  {annotation: '@Scheduled', proxy: 'Usually none (ScheduledAnnotationBeanPostProcessor)', why: 'Scheduler invokes registered method on bean — not AOP around each call', exception: 'If you wrap bean in custom AOP, order matters'},
  {annotation: '@Retryable', proxy: 'CGLIB/JDK (Spring Retry)', why: 'RetryOperationsInterceptor wraps failures with backoff', exception: 'Self-invocation; stateful retry context lost'},
  {annotation: '@CircuitBreaker', proxy: 'CGLIB/JDK (Resilience4j/Spring)', why: 'Circuit breaker aspect around method', exception: 'Self-invocation'},
  {annotation: '@TimeLimiter', proxy: 'CGLIB/JDK', why: 'Timeout wrapper via aspect', exception: 'Self-invocation'},
  {annotation: '@RateLimiter', proxy: 'CGLIB/JDK', why: 'Rate limit aspect before proceed', exception: 'Self-invocation'},
  {annotation: '@Bulkhead', proxy: 'CGLIB/JDK', why: 'Concurrency limit via aspect', exception: 'Self-invocation'},
  {annotation: '@Validated (class)', proxy: 'None on class; method validation via AOP if @Validated on params', why: 'MethodValidationPostProcessor adds MethodValidationInterceptor for @Valid params', exception: 'Field-level @Validated on bean is not method AOP'},
  {annotation: '@Valid on parameter', proxy: 'None — MVC/WebFlux validates before controller method', why: 'HandlerMethodValidator / Bean Validation invoked by web layer', exception: 'Missed if @Valid omitted on nested object without @Valid'},
  {annotation: '@Controller', proxy: 'None for stereotype itself', why: 'Stereotype registers BeanDefinition only', exception: 'Controller bean may still be proxied for @Transactional etc.'},
  {annotation: '@RestController', proxy: 'None for stereotype', why: 'Combines @Controller + @ResponseBody metadata', exception: 'Same as @Controller for cross-cutting proxies'},
  {annotation: '@Service', proxy: 'None for stereotype', why: 'Semantic @Component — no AOP by itself', exception: 'PaymentService with @Transactional gets proxy at creation'},
  {annotation: '@Repository', proxy: 'None; exception translation via RepositoryAnnotationBeanPostProcessor', why: 'PersistenceExceptionTranslationPostProcessor wraps DAO — not classic AOP proxy for TX', exception: 'DataAccessException translation is BPP not MethodInterceptor'},
  {annotation: '@Component', proxy: 'None by default', why: 'Base stereotype — proxy only when advised annotations present', exception: '@Scope(proxyMode=TARGET_CLASS) forces scoped proxy'},
  {annotation: '@Configuration', proxy: 'CGLIB subclass for @Bean inter-method calls', why: 'ConfigurationClassEnhancer ensures @Bean method singleton semantics', exception: 'proxyBeanMethods=false uses lite @Configuration — no CGLIB between @Bean methods'},
  {annotation: '@Bean', proxy: 'None on factory method metadata', why: 'Registers factory method on @Configuration or @Component', exception: 'Returned object may be wrapped if advised'},
  {annotation: '@Lazy', proxy: 'Injection-time lazy proxy (LazyInitializationProxyFactory)', why: 'Defers bean creation until first method call on injected proxy', exception: '@Lazy false on already-eager singleton has no effect'},
  {annotation: '@Scope("request")', proxy: 'Scoped proxy (TARGET_CLASS CGLIB or INTERFACES JDK)', why: 'Singleton holding request bean needs proxy delegating to current request scope', exception: 'OBJECT target without proxy injects wrong scope'},
  {annotation: '@Scope("session")', proxy: 'Scoped proxy', why: 'Same as request — thread/session bound target', exception: 'Using session scope in stateless API without proxy'},
  {annotation: '@Scope("prototype")', proxy: 'None unless explicitly scoped proxy', why: 'New instance per getBean/injection', exception: 'Singleton injecting prototype without ObjectProvider gets one instance'},
  {annotation: '@Autowired', proxy: 'None — injects whatever container holds', why: 'Injection resolves reference; may be proxy if target bean is advised', exception: 'Injecting concrete class when only JDK interface proxy exists'},
  {annotation: '@TransactionalEventListener', proxy: 'None on listener; runs in TX phase callback', why: 'TransactionalApplicationListenerMethodAdapter registers phase hook', exception: 'AFTER_COMMIT without active TX — event dropped or mis-phased'},
  {annotation: '@EventListener', proxy: 'None', why: 'EventListenerMethodProcessor registers ApplicationListener adapter', exception: 'Async @EventListener needs @EnableAsync on executor'},
  {annotation: '@KafkaListener', proxy: 'None on annotation', why: 'KafkaListenerAnnotationBeanPostProcessor registers endpoint', exception: 'Listener method @Transactional still needs proxy on container bean'},
  {annotation: '@JmsListener', proxy: 'None', why: 'JmsListenerAnnotationBeanPostProcessor', exception: 'Same TX/self-invocation rules as Kafka'},
  {annotation: '@RabbitListener', proxy: 'None', why: 'RabbitListenerAnnotationBeanPostProcessor', exception: 'Manual ack in listener bypasses TX rollback semantics'},
  {annotation: '@Entity', proxy: 'None — JPA metadata', why: 'Processed by Hibernate/JPA bootstrap not Spring AOP', exception: '@Transactional still on service layer'},
  {annotation: '@Repository (Data)', proxy: 'None; Spring Data factory bean', why: 'JdkDynamicProxy for repository interface at runtime', exception: 'Custom impl class is concrete bean — may use CGLIB'},
  {annotation: '@FeignClient', proxy: 'JDK dynamic proxy for interface', why: 'Feign builds HTTP client proxy implementing interface', exception: 'Not Spring AOP — separate Feign invocation handler'},
  {annotation: '@Cacheable(sync=true)', proxy: 'CGLIB/JDK', why: 'CacheAspectSupport single-flight lock in advised method', exception: 'Self-invocation loses sync lock'},
  {annotation: '@Observed (Micrometer)', proxy: 'CGLIB/JDK (ObservationAspect)', why: 'Creates Observation around method for metrics/tracing', exception: 'Self-invocation'},
  {annotation: '@Timed', proxy: 'CGLIB/JDK', why: 'Metrics aspect records method timing', exception: 'Self-invocation'},
  {annotation: '@Counted', proxy: 'CGLIB/JDK', why: 'Increments counter on invocation', exception: 'Self-invocation'},
  {annotation: '@Lock (Spring Integration)', proxy: 'CGLIB/JDK', why: 'LockRegistry advice serializes method', exception: 'Self-invocation'},
  {annotation: '@SendTo (Spring Cloud Stream)', proxy: 'None', why: 'Message binding metadata', exception: 'Stream bridge still needs correct channel config'},
  {annotation: '@Transactional(readOnly=true)', proxy: 'CGLIB/JDK', why: 'Sets readOnly flag on Connection — Hibernate flush mode', exception: 'Write in readOnly TX may fail or flush unexpectedly'},
  {annotation: '@Modifying (@Query)', proxy: 'None on annotation', why: 'Spring Data query method metadata', exception: 'Requires @Transactional on calling service — repo TX easy to misuse'},
  {annotation: '@EnableAspectJAutoProxy', proxy: 'Global switch — not an annotation on bean', why: 'Registers AnnotationAwareAspectJAutoProxyCreator', exception: 'exposeProxy=true needed for AopContext.currentProxy()'},
  {annotation: '@Order on @Aspect', proxy: 'N/A — orders advisors', why: 'Lower order value = higher precedence in advisor chain', exception: 'Wrong order: security after TX commit'},
  {annotation: '@RefreshScope', proxy: 'Scoped proxy (CGLIB)', why: 'Cloud context refresh recreates bean behind proxy', exception: 'Stale references if injected non-proxied refresh bean into singleton'},
  {annotation: '@RequestScope/@SessionScope (web)', proxy: 'Scoped proxy when injected into singleton', why: 'WebApplicationContext scope delegation', exception: 'Background thread without request context'},
  {annotation: '@Lookup', proxy: 'CGLIB subclass method override', why: 'AbstractMethodOverride replaces method to getBean(prototype)', exception: 'Only works on abstract or @Lookup method in @Component/@Service'},
  {annotation: '@ConditionalOn* (Boot)', proxy: 'None', why: 'Condition evaluated at BeanDefinition registration', exception: 'Bean may still be proxied later if created'},
  {annotation: '@Primary', proxy: 'None', why: 'BeanDefinition candidate flag for autowiring', exception: 'Does not affect which proxy type is created'},
  {annotation: '@Qualifier', proxy: 'None', why: 'Autowire candidate metadata', exception: 'Selecting between two proxied beans still injects proxy'},
  {annotation: '@Value', proxy: 'None', why: 'Embedded value resolution at injection', exception: 'SpEL in @Value evaluated once at injection'},
  {annotation: '@ConfigurationProperties', proxy: 'None', why: 'ConfigurationPropertiesBindingPostProcessor binds env to bean', exception: '@RefreshScope + @ConfigurationProperties needs proxy for rebinding'},
  {annotation: '@ControllerAdvice', proxy: 'None for advice stereotype', why: 'Exception handler beans — MVC invokes directly', exception: '@ModelAttribute advice runs before controller — not AOP proxy'},
  {annotation: '@ExceptionHandler', proxy: 'None', why: 'Mapped by ExceptionHandlerExceptionResolver', exception: 'Must be on @ControllerAdvice or @RestController'},
  {annotation: '@InitBinder', proxy: 'None', why: 'WebDataBinder registration per controller advice', exception: 'Global vs local @ControllerAdvice order'},
  {annotation: '@ResponseStatus', proxy: 'None', why: 'ExceptionHandlerExceptionResolver reads annotation on exception', exception: 'On controller method — ResponseStatusExceptionResolver'},
  {annotation: '@Transactional(propagation=NESTED)', proxy: 'CGLIB/JDK', why: 'NestedTransactionInterceptor uses savepoint', exception: 'Requires JDBC savepoint support — not all JTA'},
  {annotation: '@Transactional(propagation=REQUIRES_NEW)', proxy: 'CGLIB/JDK', why: 'Suspends outer TX, opens new', exception: 'Self-invocation stays in same TX'},
  {annotation: '@EnableCaching', proxy: 'N/A — enables CacheInterceptor infrastructure', why: 'Registers proxy creator + CacheOperationSource', exception: 'Without it @Cacheable is ignored silently'},
  {annotation: '@EnableAsync', proxy: 'N/A', why: 'Registers AsyncAnnotationBeanPostProcessor', exception: 'Default SimpleAsyncTaskExecutor unbounded — prod use ThreadPoolTaskExecutor'},
  {annotation: '@EnableMethodSecurity', proxy: 'N/A', why: 'MethodSecurityConfiguration registers security advisors', exception: 'prePostEnabled vs securedEnabled flags'},
  {annotation: '@SpringBootApplication', proxy: 'None', why: 'Meta: @Configuration + @EnableAutoConfiguration + @ComponentScan', exception: 'Does not enable @EnableTransactionManagement by default in Boot — auto-config does'},
  {annotation: '@DirtiesContext', proxy: 'None', why: 'TestContext marks context dirty after test', exception: 'Not for production'},
  {annotation: '@MockBean', proxy: 'Replaces bean in test context', why: 'Test context replaces or adds mock definition', exception: '@Primary mock vs @Qualifier confusion in slice tests'},
  {annotation: '@SpyBean', proxy: 'Partial mock wrapper', why: 'Wraps real bean with Mockito spy', exception: 'Still a Spring bean — injection gets spy'},
  {annotation: '@ImportRuntimeHints', proxy: 'None', why: 'AOT/native image reflection registration', exception: 'GraalVM only'},
  {annotation: '@RegisterReflectionForBinding', proxy: 'None', why: 'Boot 3.2+ native hints for @ConfigurationProperties', exception: 'Missing hints → native runtime failure'},
  {annotation: '@HttpExchange (Boot 3)', proxy: 'JDK HTTP interface client', why: 'HttpServiceProxyFactory creates REST client proxy', exception: 'Not Spring AOP — WebClient-backed'},
  {annotation: '@RetryableTopic (Kafka)', proxy: 'None', why: 'KafkaListenerContainerFactory post-processor config', exception: 'Retry topics are infrastructure not method proxy'},
  {annotation: '@SendToUser (STOMP)', proxy: 'None', why: 'Messaging mapping metadata', exception: 'Session principal must exist'},
  {annotation: '@MessageMapping', proxy: 'None', why: 'WebSocket/STOMP handler mapping', exception: 'Security on messaging channel separate from @PreAuthorize on bean'},
  {annotation: '@Schema (OpenAPI)', proxy: 'None', why: 'springdoc scans for API documentation', exception: 'Runtime behavior unchanged'},
  {annotation: '@Hidden (OpenAPI)', proxy: 'None', why: 'Excludes from OpenAPI doc', exception: 'Endpoint still live'},
  {annotation: '@Transactional(rollbackFor=)', proxy: 'CGLIB/JDK', why: 'RuleBasedTransactionAttribute sets rollback rules', exception: 'Checked exceptions default no rollback unless specified'},
  {annotation: '@Cacheable(condition=)', proxy: 'CGLIB/JDK', why: 'SpEL evaluated in CacheOperationContext before cache lookup', exception: 'condition false still invokes method — no cache'},
  {annotation: '@Cacheable(unless=)', proxy: 'CGLIB/JDK', why: 'SpEL on result skips cache store', exception: 'unless on null result'},
  {annotation: '@Async("beanName")', proxy: 'CGLIB/JDK', why: 'Resolves named TaskExecutor bean', exception: 'Wrong executor bean name → startup failure'},
  {annotation: '@Transactional(timeout=)', proxy: 'CGLIB/JDK', why: 'Sets transaction timeout on TransactionStatus', exception: 'JPA may not enforce same as JDBC'},
  {annotation: '@Transactional(isolation=)', proxy: 'CGLIB/JDK', why: 'Maps to Connection transaction isolation', exception: 'Some pools ignore isolation change mid-app'},
  {annotation: '@PermitAll/@DenyAll', proxy: 'CGLIB/JDK when on method', why: 'Jakarta security annotations via method security', exception: 'URL security vs method security both needed'},
  {annotation: '@WithMockUser', proxy: 'None — test SecurityContext', why: 'SecurityContextTestExecutionListener sets context', exception: 'Does not test real filter chain'},
  {annotation: '@WebMvcTest', proxy: 'Loads slice — may mock @Controller only', why: 'Test slice excludes full context', exception: '@MockBean service — no real @Transactional proxy'},
  {annotation: '@DataJpaTest', proxy: 'JPA slice with @Transactional rollback', why: 'Test transaction wraps each test method', exception: 'Not same as production service-layer TX'},
  {annotation: '@Commit', proxy: 'None', why: 'Test annotation disables default rollback', exception: 'Pollutes test DB if misused'},
  {annotation: '@Rollback', proxy: 'None', why: 'Test @Transactional default true', exception: 'Forgot @Transactional on test class'},
  {annotation: '@DynamicPropertySource', proxy: 'None', why: 'TestPropertySource integration for containers', exception: 'Runs before context refresh'},
  {annotation: '@ServiceConnection', proxy: 'None', why: 'Boot 3.1 Testcontainers auto-configures DataSource etc.', exception: 'Requires testcontainers on classpath'},
  {annotation: '@ConstructorBinding', proxy: 'None', why: 'Immutable @ConfigurationProperties via constructor', exception: 'Cannot use with @Bean method binding same props'},
  {annotation: '@DefaultValue (Boot 3.2)', proxy: 'None', why: 'Constructor param default in @ConfigurationProperties', exception: 'Differs from @Value default'},
  {annotation: '@Named', proxy: 'None', why: 'JSR-330 bean name — same as @Component("name")', exception: 'javax.inject → jakarta.inject in Boot 3'},
  {annotation: '@PostConstruct', proxy: 'None', why: 'CommonAnnotationBeanPostProcessor lifecycle callback', exception: 'Runs after injection, before AOP proxy exposed to other beans? Actually after initialization — proxy exists'},
  {annotation: '@PreDestroy', proxy: 'None', why: 'DisposableBeanAdapter / @PreDestroy invocation on shutdown', exception: 'Prototype beans — container does not call destroy'},
  {annotation: '@DependsOn', proxy: 'None', why: 'BeanDefinition depends-on names control creation order', exception: 'Does not guarantee @PostConstruct order across depends-on alone'},
  {annotation: '@Role(ROLE_INFRASTRUCTURE)', proxy: 'None', why: 'BeanDefinition role for tooling', exception: 'Infrastructure beans still can be proxied'},
  {annotation: '@Profile', proxy: 'None', why: 'ProfileCondition gates BeanDefinition', exception: 'Active profiles at runtime via spring.profiles.active'},
  {annotation: '@Conditional', proxy: 'None', why: 'Custom Condition on BeanDefinition', exception: 'Evaluated once at context refresh unless @RefreshScope'},
  {annotation: '@Import', proxy: 'None', why: 'ConfigurationClassParser imports additional @Configuration', exception: 'Circular @Import between configs'},
  {annotation: '@PropertySource', proxy: 'None', why: 'PropertySourceFactory loads properties into Environment', exception: 'Does not override application.yml without order'},
  {annotation: '@EnableConfigurationProperties', proxy: 'None', why: 'Registers @ConfigurationProperties beans', exception: 'Must list classes or scan'},
  {annotation: '@AutoConfigureBefore/After', proxy: 'None', why: 'Auto-configuration ordering metadata', exception: 'Wrong order → missing bean at wiring'},
  {annotation: '@ControllerEndpoint (Actuator)', proxy: 'None', why: 'Actuator web endpoint as controller', exception: 'Expose only on management port'},
  {annotation: '@Endpoint (@Bean)', proxy: 'None', why: 'JMX/HTTP actuator endpoint bean', exception: 'Security on actuator paths'},
  {annotation: '@Scheduled(fixedDelay)', proxy: 'None per invocation', why: 'TaskScheduler triggers method on bean reference', exception: 'If bean is proxy, scheduler holds proxy — OK'},
  {annotation: '@CircuitBreaker(name=)', proxy: 'CGLIB/JDK', why: 'Resilience4j aspect uses registry name', exception: 'Name mismatch → default config'},
  {annotation: '@Bulkhead(type=THREADPOOL)', proxy: 'CGLIB/JDK', why: 'Thread pool bulkhead limits concurrent calls', exception: 'SEMAPHORE vs THREADPOOL semantics'},
  {annotation: '@NewSpan (Micrometer Tracing)', proxy: 'CGLIB/JDK', why: 'Creates child span around method', exception: 'Self-invocation loses trace'},
  {annotation: '@ContinueSpan', proxy: 'CGLIB/JDK', why: 'Adds tags to current span', exception: 'No active span → noop'},
  {annotation: '@CacheConfig', proxy: 'None — class-level cache defaults', why: 'CacheAnnotationParser reads metadata', exception: 'Does not enable caching without @EnableCaching'},
  {annotation: '@EnableWebSecurity', proxy: 'None', why: 'Registers SecurityFilterChain beans', exception: 'Filter order vs @Controller'},
  {annotation: '@CrossOrigin', proxy: 'None', why: 'RequestMappingHandlerMapping CORS metadata', exception: 'Preflight not hitting @PreAuthorize'},
  {annotation: '@RequestBody', proxy: 'None', why: 'HttpMessageConverter resolves body before invoke', exception: 'Missing @Valid → no automatic validation'},
  {annotation: '@ResponseBody', proxy: 'None', why: 'Return value handler serializes response', exception: 'String return with Jackson vs plain text'},
  {annotation: '@PathVariable', proxy: 'None', why: 'URI template variable binding', exception: 'Optional vs required default'},
  {annotation: '@RequestParam', proxy: 'None', why: 'Query param binding', exception: 'Collection params need explicit name'},
  {annotation: '@RequestHeader', proxy: 'None', why: 'Header binding', exception: 'Content-Type not for body type alone'},
  {annotation: '@CookieValue', proxy: 'None', why: 'Cookie binding', exception: 'Missing cookie on required param → 400'},
  {annotation: '@ModelAttribute', proxy: 'None', why: 'Form/model binding', exception: 'PUT with partial model'},
  {annotation: '@SessionAttribute', proxy: 'None', why: 'Session attribute injection', exception: 'No session in stateless JWT API'},
  {annotation: '@MatrixVariable', proxy: 'None', why: 'Matrix param in URI path', exception: 'Needs enableMatrixVariables'},
  {annotation: '@PageableDefault', proxy: 'None', why: 'Spring Data resolves Pageable argument', exception: 'Unpaged abuse → full table scan'},
  {annotation: '@SortDefault', proxy: 'None', why: 'Default Sort for Pageable', exception: 'SQL injection if sort unsanitized'},
  {annotation: '@CurrentSecurityContext', proxy: 'None', why: 'Resolves SecurityContextHolder', exception: 'Null outside request thread'},
  {annotation: '@AuthenticationPrincipal', proxy: 'None', why: 'Resolves principal from SecurityContext', exception: 'Anonymous user object type'},
  {annotation: '@WithRateLimiter', proxy: 'Custom aspect if added', why: 'Not stock Spring — community patterns', exception: 'Prefer Bucket4j filter or Resilience4j'},
];

export const PROCESSOR_MAP: {
  annotation: string;
  processor: string;
  proxy: string;
  phase: string;
  trap: string;
}[] = [
  {annotation: '@Component', processor: 'ClassPathBeanDefinitionScanner', proxy: 'No', phase: 'SCAN / REGISTER', trap: 'Scan does not instantiate — only BeanDefinition'},
  {annotation: '@Service', processor: 'ClassPathBeanDefinitionScanner', proxy: 'No*', phase: 'SCAN', trap: '*Proxied if @Transactional/@Async on class'},
  {annotation: '@Repository', processor: 'ClassPathBeanDefinitionScanner + PersistenceExceptionTranslationPostProcessor', proxy: 'No*', phase: 'SCAN + BPP', trap: 'Exception translation ≠ transaction proxy'},
  {annotation: '@Controller', processor: 'ClassPathBeanDefinitionScanner', proxy: 'No*', phase: 'SCAN', trap: 'MVC maps methods — not AOP'},
  {annotation: '@RestController', processor: 'ClassPathBeanDefinitionScanner', proxy: 'No*', phase: 'SCAN', trap: '@ResponseBody combined metadata'},
  {annotation: '@Configuration', processor: 'ConfigurationClassPostProcessor', proxy: 'CGLIB @Bean', phase: 'PARSE CONFIG', trap: 'proxyBeanMethods=false → lite config'},
  {annotation: '@Bean', processor: 'ConfigurationClassBeanDefinitionReader', proxy: 'On return type', phase: 'REGISTER', trap: '@Bean method call without @Configuration CGLIB → new instance each call'},
  {annotation: '@Import', processor: 'ConfigurationClassParser', proxy: 'No', phase: 'PARSE CONFIG', trap: 'ImportSelector vs plain @Import'},
  {annotation: '@ComponentScan', processor: 'ComponentScanAnnotationParser', proxy: 'No', phase: 'PARSE CONFIG', trap: 'basePackageClasses vs basePackages'},
  {annotation: '@SpringBootApplication', processor: 'SpringBootConfiguration + AutoConfigurationImportSelector', proxy: 'No', phase: 'BOOTSTRAP', trap: 'scanBasePackages empty uses package of main class'},
  {annotation: '@EnableAutoConfiguration', processor: 'AutoConfigurationImportSelector', proxy: 'No', phase: 'REGISTER', trap: 'exclude / spring.autoconfigure.exclude'},
  {annotation: '@ConditionalOnClass', processor: 'OnClassCondition', proxy: 'No', phase: 'CONDITION', trap: 'Class not on classpath → config skipped silently'},
  {annotation: '@ConditionalOnBean', processor: 'OnBeanCondition', proxy: 'No', phase: 'CONDITION', trap: 'Bean not yet registered → false negative ordering'},
  {annotation: '@ConditionalOnMissingBean', processor: 'OnBeanCondition', proxy: 'No', phase: 'CONDITION', trap: 'User @Bean blocks auto-config'},
  {annotation: '@ConditionalOnProperty', processor: 'OnPropertyCondition', proxy: 'No', phase: 'CONDITION', trap: 'matchIfMissing default'},
  {annotation: '@Autowired', processor: 'AutowiredAnnotationBeanPostProcessor', proxy: 'No', phase: 'INJECT', trap: 'Constructor cycle vs field fallback'},
  {annotation: '@Qualifier', processor: 'AutowiredAnnotationBeanPostProcessor + QualifierAnnotationAutowireCandidateResolver', proxy: 'No', phase: 'INJECT', trap: 'Beats @Primary on injection point'},
  {annotation: '@Primary', processor: 'BeanDefinition primary flag', proxy: 'No', phase: 'REGISTER', trap: 'Two @Primary → still ambiguous'},
  {annotation: '@Resource', processor: 'CommonAnnotationBeanPostProcessor', proxy: 'No', phase: 'INJECT', trap: 'Name-first not type-first'},
  {annotation: '@Inject', processor: 'AutowiredAnnotationBeanPostProcessor (JSR-330)', proxy: 'No', phase: 'INJECT', trap: 'No required=false — use Optional'},
  {annotation: '@Value', processor: 'AutowiredAnnotationBeanPostProcessor + EmbeddedValueResolver', proxy: 'No', phase: 'INJECT', trap: '${} vs #{} SpEL'},
  {annotation: '@ConfigurationProperties', processor: 'ConfigurationPropertiesBindingPostProcessor', proxy: 'No*', phase: 'BIND', trap: '*@RefreshScope needs scoped proxy'},
  {annotation: '@PostConstruct', processor: 'CommonAnnotationBeanPostProcessor / InitDestroyAnnotationBeanPostProcessor', proxy: 'No', phase: 'INIT', trap: 'Runs after injection on initialized bean'},
  {annotation: '@PreDestroy', processor: 'InitDestroyAnnotationBeanPostProcessor', proxy: 'No', phase: 'DESTROY', trap: 'Prototype — no container destroy'},
  {annotation: '@Scope', processor: 'BeanDefinition scope metadata', proxy: 'Scoped proxy if configured', phase: 'REGISTER', trap: 'prototype in singleton without ObjectProvider'},
  {annotation: '@Lazy', processor: 'LazyAnnotationBeanPostProcessor', proxy: 'Lazy init proxy', phase: 'CREATE / INJECT', trap: 'First call pays creation cost + failures'},
  {annotation: '@DependsOn', processor: 'BeanDefinition dependsOn', proxy: 'No', phase: 'ORDER', trap: 'Order ≠ @Order on aspects'},
  {annotation: '@Profile', processor: 'ProfileCondition', proxy: 'No', phase: 'CONDITION', trap: 'spring.profiles.active at runtime'},
  {annotation: '@Transactional', processor: 'TransactionManagementConfigurationSelector → TransactionInterceptor', proxy: 'Yes', phase: 'AOP ADVISE', trap: 'Self-invocation bypasses proxy'},
  {annotation: '@EnableTransactionManagement', processor: 'TransactionManagementConfigurationSelector', proxy: 'Infrastructure', phase: 'CONFIG', trap: 'mode=ASPECTJ needs weaving'},
  {annotation: '@Async', processor: 'AsyncAnnotationBeanPostProcessor', proxy: 'Yes', phase: 'AOP ADVISE', trap: 'Self-invocation; wrong executor'},
  {annotation: '@EnableAsync', processor: 'AsyncConfigurationSelector', proxy: 'Infrastructure', phase: 'CONFIG', trap: 'Default unbounded executor'},
  {annotation: '@Cacheable', processor: 'CacheInterceptor via CacheAnnotationAutoConfiguration', proxy: 'Yes', phase: 'AOP ADVISE', trap: 'Self-invocation → always miss'},
  {annotation: '@EnableCaching', processor: 'CachingConfigurationSelector', proxy: 'Infrastructure', phase: 'CONFIG', trap: 'Missing @EnableCaching → noop'},
  {annotation: '@PreAuthorize', processor: 'MethodSecurityConfiguration → AuthorizationManagerBeforeMethodInterceptor', proxy: 'Yes', phase: 'AOP ADVISE', trap: 'Self-invocation; URL vs method security'},
  {annotation: '@EnableMethodSecurity', processor: 'MethodSecurityConfiguration', proxy: 'Infrastructure', phase: 'CONFIG', trap: 'prePostEnabled default true Boot 3'},
  {annotation: '@EventListener', processor: 'EventListenerMethodProcessor', proxy: 'No', phase: 'REGISTER LISTENER', trap: 'Sync default — blocks publisher thread'},
  {annotation: '@TransactionalEventListener', processor: 'TransactionalEventListenerMethodProcessor', proxy: 'No', phase: 'TX CALLBACK', trap: 'AFTER_COMMIT without TX'},
  {annotation: '@Scheduled', processor: 'ScheduledAnnotationBeanPostProcessor', proxy: 'No', phase: 'SCHEDULE', trap: 'fixedRate vs fixedDelay'},
  {annotation: '@KafkaListener', processor: 'KafkaListenerAnnotationBeanPostProcessor', proxy: 'No', phase: 'REGISTER ENDPOINT', trap: 'Missing @EnableKafka'},
  {annotation: '@EnableKafka', processor: 'KafkaBootstrapConfiguration', proxy: 'No', phase: 'CONFIG', trap: 'ConcurrentKafkaListenerContainerFactory bean name'},
  {annotation: '@JpaRepositories', processor: 'JpaRepositoriesRegistrar', proxy: 'JDK on interface', phase: 'REGISTER', trap: 'package scan empty'},
  {annotation: '@Entity', processor: 'Hibernate MetadataSources / JPA bootstrap', proxy: 'No', phase: 'JPA STARTUP', trap: 'Not Spring bean unless @Entity scan'},
  {annotation: '@Valid', processor: 'MethodValidationPostProcessor / Web MVC validator', proxy: 'Partial', phase: 'VALIDATE', trap: 'Nested object needs @Valid on field'},
  {annotation: '@Validated', processor: 'MethodValidationPostProcessor', proxy: 'Method AOP', phase: 'VALIDATE', trap: 'Groups not applied without @Validated on param'},
  {annotation: '@ControllerAdvice', processor: 'RequestMappingHandlerMapping exception resolver', proxy: 'No', phase: 'WEB', trap: 'Order among multiple advice beans'},
  {annotation: '@ExceptionHandler', processor: 'ExceptionHandlerExceptionResolver', proxy: 'No', phase: 'WEB', trap: 'Most specific exception wins'},
  {annotation: '@RequestMapping', processor: 'RequestMappingHandlerMapping', proxy: 'No', phase: 'WEB MAP', trap: 'Class + method path concat'},
  {annotation: '@GetMapping', processor: 'RequestMappingHandlerMapping', proxy: 'No', phase: 'WEB MAP', trap: 'Produces/consumes mismatch 406'},
  {annotation: '@RequestBody', processor: 'RequestResponseBodyMethodProcessor', proxy: 'No', phase: 'WEB INVOKE', trap: 'No @Valid → invalid payload accepted'},
  {annotation: '@ResponseBody', processor: 'RequestResponseBodyMethodProcessor', proxy: 'No', phase: 'WEB OUT', trap: 'String vs object Jackson'},
  {annotation: '@PathVariable', processor: 'ServletRequestDataBinder / PathVariableMethodArgumentResolver', proxy: 'No', phase: 'WEB BIND', trap: 'Name mismatch without explicit value'},
  {annotation: '@EnableWebSecurity', processor: 'WebSecurityConfiguration', proxy: 'No', phase: 'SECURITY', trap: 'Multiple SecurityFilterChain @Order'},
  {annotation: '@Bean SecurityFilterChain', processor: 'HttpSecurity build', proxy: 'No', phase: 'SECURITY', trap: 'CSRF disabled on REST by mistake'},
  {annotation: '@Order', processor: 'Ordered interface on bean/advisor', proxy: 'N/A', phase: 'ORDER', trap: 'Lower number = higher precedence'},
  {annotation: '@Aspect', processor: 'AnnotationAwareAspectJAutoProxyCreator', proxy: 'Yes', phase: 'AOP', trap: 'AspectJ compile-time vs Spring AOP runtime'},
  {annotation: '@Around', processor: 'AspectJAdviceParameterNameDiscoverer + advisor', proxy: 'Yes', phase: 'AOP', trap: 'Must call proceed()'},
  {annotation: '@Pointcut', processor: 'AspectJExpressionPointcut', proxy: 'N/A', phase: 'AOP', trap: 'Wrong expression → advice never runs'},
  {annotation: '@EnableAspectJAutoProxy', processor: 'AopAutoConfiguration', proxy: 'Global', phase: 'CONFIG', trap: 'exposeProxy for self-call'},
  {annotation: '@RefreshScope', processor: 'RefreshScope + scoped proxy factory', proxy: 'Yes', phase: 'CLOUD', trap: 'Singleton holding direct ref stale'},
  {annotation: '@FeignClient', processor: 'FeignClientsRegistrar', proxy: 'JDK Feign', phase: 'REGISTER', trap: 'Not Spring TX proxy'},
  {annotation: '@LoadBalanced RestTemplate', processor: 'LoadBalancerAutoConfiguration', proxy: 'No', phase: 'CLIENT', trap: 'Blocking client in reactive app'},
  {annotation: '@Retryable', processor: 'RetryConfiguration', proxy: 'Yes', phase: 'AOP', trap: 'Retry on same thread unless @Async'},
  {annotation: '@CircuitBreaker', processor: 'Resilience4j auto-config aspect', proxy: 'Yes', phase: 'AOP', trap: 'State closed/open/half-open'},
  {annotation: '@Observed', processor: 'ObservationRegistryPostProcessor', proxy: 'Yes', phase: 'AOP/OBS', trap: 'Needs micrometer-tracing on classpath'},
  {annotation: '@Lookup', processor: 'LookupOverride in CGLIB subclass', proxy: 'CGLIB subclass', phase: 'CREATE', trap: 'Method must not be final'},
  {annotation: '@ImportRuntimeHints', processor: 'RuntimeHintsRegistrar', proxy: 'No', phase: 'AOT', trap: 'Native image only'},
  {annotation: '@TestConfiguration', processor: 'Test context @Import', proxy: 'No', phase: 'TEST', trap: 'Not picked by @SpringBootTest scan'},
  {annotation: '@MockBean', processor: 'MockitoPostProcessor', proxy: 'Mock', phase: 'TEST', trap: 'Replaces bean by type'},
  {annotation: '@DynamicPropertySource', processor: 'DynamicPropertyContextCustomizer', proxy: 'No', phase: 'TEST', trap: 'Runs before context'},
  {annotation: '@Sql', processor: 'SqlScriptsTestExecutionListener', proxy: 'No', phase: 'TEST', trap: '@Transactional test rolls back @Sql data'},
  {annotation: '@DirtiesContext', processor: 'DirtiesContextTestExecutionListener', proxy: 'No', phase: 'TEST', trap: 'Slow — reloads context'},
  {annotation: '@Transactional (test)', processor: 'TransactionalTestExecutionListener', proxy: 'Test TX', phase: 'TEST', trap: 'Not production proxy path'},
  {annotation: '@Commit', processor: 'TransactionalTestExecutionListener', proxy: 'No', phase: 'TEST', trap: 'Persists test data'},
  {annotation: '@AutoConfigureMockMvc', processor: 'MockMvcAutoConfiguration', proxy: 'No', phase: 'TEST', trap: 'No full security unless imported'},
  {annotation: '@WebMvcTest', processor: 'WebMvcTestContextBootstrapper', proxy: 'Slice', phase: 'TEST', trap: '@MockBean all services'},
  {annotation: '@DataJpaTest', processor: 'DataJpaTestContextBootstrapper', proxy: 'Slice + TX', phase: 'TEST', trap: 'No @Service beans loaded'},
  {annotation: '@SpringBootTest', processor: 'SpringBootContextLoader', proxy: 'Full', phase: 'TEST', trap: 'Slow — full context'},
  {annotation: '@PropertySource', processor: 'PropertySourceProcessor', proxy: 'No', phase: 'ENV', trap: 'Lowest precedence unless @Order'},
  {annotation: '@EnableConfigurationProperties', processor: 'EnableConfigurationPropertiesRegistrar', proxy: 'No', phase: 'REGISTER', trap: 'Class must be @ConfigurationProperties'},
  {annotation: '@ConstructorBinding', processor: 'ConfigurationPropertiesBeanRegistrar', proxy: 'No', phase: 'BIND', trap: 'Immutable — no setters'},
  {annotation: '@DefaultValue', processor: 'ConfigurationPropertiesBindingPostProcessor', proxy: 'No', phase: 'BIND', trap: 'Boot 3.2+ constructor defaults'},
  {annotation: '@HttpExchange', processor: 'HttpServiceProxyFactory', proxy: 'JDK HTTP', phase: 'CLIENT', trap: 'Declarative REST not Feign'},
  {annotation: '@SendTo (Stream)', processor: 'StreamListenerAnnotationBeanPostProcessor', proxy: 'No', phase: 'BINDING', trap: 'Deprecated in favor of functional'},
  {annotation: '@Bean Jackson ObjectMapper', processor: '@Bean method', proxy: 'No', phase: 'REGISTER', trap: 'Boot auto-config backs off if bean present'},
  {annotation: '@Primary DataSource', processor: 'BeanDefinition', proxy: 'No', phase: 'REGISTER', trap: 'Multiple datasources need @Qualifier'},
  {annotation: '@Modifying', processor: 'Spring Data query method', proxy: 'No', phase: 'REPO', trap: 'Needs clearAutomatically flush'},
  {annotation: '@Query', processor: 'Spring Data query derivation', proxy: 'No', phase: 'REPO', trap: 'Native query entity mapping'},
  {annotation: '@Version', processor: 'JPA optimistic lock', proxy: 'No', phase: 'JPA', trap: 'OptimisticLockException on conflict'},
  {annotation: '@Lock (JPA)', processor: 'JPA LockModeType', proxy: 'No', phase: 'JPA', trap: 'PESSIMISTIC_WRITE holds DB row'},
  {annotation: '@EntityGraph', processor: 'Spring Data fetch graph', proxy: 'No', phase: 'REPO', trap: 'Over-fetch vs N+1'},
  {annotation: '@BatchSize', processor: 'Hibernate batch fetching', proxy: 'No', phase: 'JPA', trap: 'Not same as JDBC batch insert'},
  {annotation: '@Filter (Hibernate)', processor: 'Session enableFilter', proxy: 'No', phase: 'JPA', trap: 'Must enable per session'},
  {annotation: '@NamedQuery', processor: 'JPA named query registration', proxy: 'No', phase: 'JPA', trap: 'Validated at startup'},
  {annotation: '@OrderBy', processor: 'JPA association ordering', proxy: 'No', phase: 'JPA', trap: 'Collection fetch order only'},
  {annotation: '@MappedSuperclass', processor: 'JPA inheritance', proxy: 'No', phase: 'JPA', trap: 'Not an entity table'},
  {annotation: '@Inheritance', processor: 'JPA SINGLE_TABLE/JOINED', proxy: 'No', phase: 'JPA', trap: 'SINGLE_TABLE nullable columns'},
  {annotation: '@DiscriminatorColumn', processor: 'JPA DTYPE', proxy: 'No', phase: 'JPA', trap: 'Wrong dtype → wrong class'},
  {annotation: '@Embeddable', processor: 'JPA embedded type', proxy: 'No', phase: 'JPA', trap: 'Equals/hashCode on embeddable'},
  {annotation: '@EmbeddedId', processor: 'JPA composite key', proxy: 'No', phase: 'JPA', trap: 'Must implement Serializable'},
  {annotation: '@Convert', processor: 'JPA AttributeConverter', proxy: 'No', phase: 'JPA', trap: 'Auto-applied if registered'},
  {annotation: '@JsonIgnore', processor: 'Jackson ObjectMapper', proxy: 'No', phase: 'SERIALIZE', trap: 'Lazy proxy serialization'},
  {annotation: '@JsonManagedReference', processor: 'Jackson bidirectional', proxy: 'No', phase: 'SERIALIZE', trap: 'Infinite loop without back ref'},
  {annotation: '@Schema', processor: 'springdoc OpenAPI scanner', proxy: 'No', phase: 'DOC', trap: 'Doc only'},
  {annotation: '@Hidden', processor: 'springdoc', proxy: 'No', phase: 'DOC', trap: 'Endpoint still exposed'},
  {annotation: '@CrossOrigin', processor: 'RequestMappingHandlerMapping CORS', proxy: 'No', phase: 'WEB', trap: 'Credentials + wildcard'},
  {annotation: '@RequestScope', processor: 'WebApplicationContext scope', proxy: 'Scoped proxy', phase: 'SCOPE', trap: 'Async thread no request'},
  {annotation: '@SessionScope', processor: 'WebApplicationContext scope', proxy: 'Scoped proxy', phase: 'SCOPE', trap: 'Stateful in REST'},
  {annotation: '@ApplicationScope (CDI)', processor: 'Not default Spring — use singleton', proxy: 'No', phase: '—', trap: 'Confuse with @ApplicationScope custom'},
  {annotation: '@RolesAllowed', processor: 'Jsr250MethodSecurityConfiguration', proxy: 'Yes', phase: 'SECURITY AOP', trap: 'Enable method security'},
  {annotation: '@PermitAll', processor: 'Method security metadata', proxy: 'Yes', phase: 'SECURITY', trap: 'Still need authentication filter'},
  {annotation: '@AuthenticationPrincipal', processor: 'AuthenticationPrincipalArgumentResolver', proxy: 'No', phase: 'WEB', trap: 'Principal type conversion'},
  {annotation: '@CurrentSecurityContext', processor: 'SecurityContextArgumentResolver', proxy: 'No', phase: 'WEB', trap: 'Null in @Async without propagation'},
  {annotation: '@WithMockUser', processor: 'SecurityContextTestExecutionListener', proxy: 'No', phase: 'TEST', trap: 'Not integration security'},
  {annotation: '@ImportAutoConfiguration', processor: 'ImportAutoConfigurationImportSelector', proxy: 'No', phase: 'TEST/SLICE', trap: 'Test slice imports'},
  {annotation: '@TestPropertySource', processor: 'TestPropertySourceUtils', proxy: 'No', phase: 'TEST', trap: 'Overrides application.yml'},
  {annotation: '@ServiceConnection', processor: 'ServiceConnectionContextCustomizer', proxy: 'No', phase: 'TEST', trap: 'Testcontainers required'},
  {annotation: '@Container', processor: 'Testcontainers JUnit extension', proxy: 'No', phase: 'TEST', trap: 'Static vs instance container'},
  {annotation: '@RegisterExtension', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Not Spring-specific'},
  {annotation: '@ParameterizedTest', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Spring context per param expensive'},
  {annotation: '@Nested', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Inner class scan'},
  {annotation: '@TempDir', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Filesystem isolation'},
  {annotation: '@Timeout', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Hung test thread'},
  {annotation: '@RepeatedTest', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Flaky test masking'},
  {annotation: '@Tag', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'CI filter tags'},
  {annotation: '@EnabledIf', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Conditional skip'},
  {annotation: '@Disabled', processor: 'JUnit 5', proxy: 'No', phase: 'TEST', trap: 'Forgotten disabled production test'},
  {annotation: '@ExtendWith(SpringExtension)', processor: 'Spring TestContext', proxy: 'No', phase: 'TEST', trap: 'Required for @SpringBootTest'},
  {annotation: '@ContextConfiguration', processor: 'ContextLoader', proxy: 'No', phase: 'TEST', trap: 'XML vs annotation config'},
  {annotation: '@ActiveProfiles', processor: 'ActiveProfilesResolver', proxy: 'No', phase: 'TEST', trap: 'Profile-specific beans missing'},
  {annotation: '@Import', processor: 'ConfigurationClassParser', proxy: 'No', phase: 'CONFIG', trap: 'Test @Import for extra beans'},
  {annotation: '@Bean @ConditionalOnMissingBean', processor: 'OnBeanCondition', proxy: 'No', phase: 'AUTO-CONFIG', trap: 'User bean blocks default'},
  {annotation: '@AutoConfigureTestDatabase', processor: 'Test database replace', proxy: 'No', phase: 'TEST', trap: 'REPLACE_ANY vs NONE'},
  {annotation: '@DataMongoTest', processor: 'Mongo slice', proxy: 'No', phase: 'TEST', trap: 'No relational JPA'},
  {annotation: '@JsonTest', processor: 'Jackson slice', proxy: 'No', phase: 'TEST', trap: 'JsonTester only'},
  {annotation: '@RestClientTest', processor: 'RestTemplate/WebClient slice', proxy: 'No', phase: 'TEST', trap: 'Mock server setup'},
  {annotation: '@AutoConfigureWebTestClient', processor: 'WebTestClient beans', proxy: 'No', phase: 'TEST', trap: 'WebFlux vs MVC'},
  {annotation: '@AutoConfigureObservability', processor: 'Micrometer test', proxy: 'No', phase: 'TEST', trap: 'Metrics in tests'},
  {annotation: '@NewSpan', processor: 'ObservationAspect / Brave', proxy: 'Yes', phase: 'TRACE', trap: 'Self-invocation'},
  {annotation: '@ContinueSpan', processor: 'Tracing aspect', proxy: 'Yes', phase: 'TRACE', trap: 'No parent span'},
  {annotation: '@CacheConfig', processor: 'CacheAnnotationParser metadata', proxy: 'No', phase: 'CACHE META', trap: 'Does not enable cache'},
  {annotation: '@Caching', processor: 'CacheInterceptor composite', proxy: 'Yes', phase: 'AOP', trap: 'Multiple cache ops one method'},
  {annotation: '@Bean Validation @NotNull', processor: 'LocalValidatorFactoryBean', proxy: 'No', phase: 'VALIDATE', trap: 'Groups on MVC need @Validated'},
  {annotation: '@Email', processor: 'Hibernate Validator', proxy: 'No', phase: 'VALIDATE', trap: 'Not DNS check'},
  {annotation: '@Size', processor: 'Bean Validation', proxy: 'No', phase: 'VALIDATE', trap: 'Collection vs string'},
  {annotation: '@Pattern', processor: 'Bean Validation', proxy: 'No', phase: 'VALIDATE', trap: 'ReDoS on complex regex'},
  {annotation: '@Past/@Future', processor: 'Bean Validation temporal', proxy: 'No', phase: 'VALIDATE', trap: 'Timezone'},
  {annotation: '@Min/@Max', processor: 'Bean Validation', proxy: 'No', phase: 'VALIDATE', trap: 'BigDecimal vs int'},
  {annotation: '@Positive', processor: 'Bean Validation 2.0', proxy: 'No', phase: 'VALIDATE', trap: 'Zero rejected'},
  {annotation: '@NegativeOrZero', processor: 'Bean Validation', proxy: 'No', phase: 'VALIDATE', trap: 'Sign rules'},
  {annotation: '@AssertTrue', processor: 'Bean Validation', proxy: 'No', phase: 'VALIDATE', trap: 'Boolean field only'},
  {annotation: '@Valid (cascade)', processor: 'Validator cascade', proxy: 'No', phase: 'VALIDATE', trap: 'Forgot on nested list items'},
];

export const ORDERING_NOTES = `
Spring AOP advisor order (@Transactional + @Async + @Cacheable + @PreAuthorize)
═══════════════════════════════════════════════════════════════════════════════

Default relative precedence (lower @Order value = runs FIRST in advisor chain):

  ┌─────────────────────────────────────────────────────────────────────────┐
  │  OUTERMOST (first to intercept incoming call)                           │
  │    @PreAuthorize / @PostAuthorize / @Secured  (security ~ order 0)      │
  │         ↓                                                               │
  │    @Transactional (platform order ~ Integer.MAX_VALUE-1 or custom)    │
  │         ↓                                                               │
  │    @Cacheable / @CacheEvict / @CachePut   (cache ~ after TX advisor)    │
  │         ↓                                                               │
  │    @Async  (often outer OR inner — configure explicitly; trap below)    │
  │         ↓                                                               │
  │    @Observed / @Timed / resilience aspects                              │
  │         ↓                                                               │
  │  TARGET METHOD (raw bean — never reached via this.*)                    │
  └─────────────────────────────────────────────────────────────────────────┘

Payment service call chain (typical Boot defaults):

  HTTP filter chain (SecurityFilterChain)  →  BEFORE any bean proxy
       │
       ▼
  Controller (usually no TX proxy on controller)
       │
       ▼
  paymentService.charge()  ──►  CGLIB proxy entry
       │
       ├─► Security advisor? (only if @PreAuthorize on service method)
       ├─► TransactionInterceptor: begin TX (Connection bound)
       ├─► CacheInterceptor: cache MISS → proceed
       ├─► Target.charge() runs
       │        ├─► repo.save() (participates in TX if repo is @Transactional or join)
       │        └─► publishEvent → AFTER_COMMIT listener scheduled
       ├─► CacheInterceptor: put result (if @Cacheable)
       ├─► TransactionInterceptor: commit
       └─► return to controller

  @Async on event listener: SEPARATE thread, SEPARATE proxy on listener bean
       TX from publisher does NOT propagate unless @TransactionalEventListener phase

Traps interviewers love:
  • @Transactional + @Cacheable: cache put after TX commit by default — stale if TX rolls back
      → use @Cacheable unless="#result==null" + afterCommit invalidation pattern
  • @Async + @Transactional: async method runs in NEW thread — TX NOT propagated
      → open TX inside async method or use @TransactionalEventListener(AFTER_COMMIT)
  • @PreAuthorize after @Transactional: TX already open before auth check (wrong order)
      → set security advisor order lower (higher precedence) than TX
  • Self-invocation: NONE of the above run on this.internal()
  • exposeProxy=true + AopContext.currentProxy() for controlled self-call through proxy

ASCII call stack (external caller):

    Caller
      → JDK/CGLIB Proxy
        → MethodSecurityInterceptor (auth)
          → TransactionInterceptor (begin)
            → CacheInterceptor (lookup)
              → TargetBean.method()
            → CacheInterceptor (store)
          → TransactionInterceptor (commit/rollback)
        → return

Rule: Draw proxy boundary FIRST. Then list advisors by @Order. Self-call skips entire left branch.
`;

export const PAYMENT_TRACE: {step: string; annotations: string; internals: string}[] = [
  {step: '1. HTTP POST /payments', annotations: '@RestController @PostMapping @RequestBody @Valid', internals: 'DispatcherServlet → HandlerMapping → HandlerAdapter invokes controller method. SecurityFilterChain already authenticated JWT (BearerTokenAuthenticationFilter).'},
  {step: '2. Security filter chain', annotations: '@EnableWebSecurity @Bean SecurityFilterChain', internals: 'Filter order: SecurityContextHolderFilter → Logout → BearerTokenAuthentication → AuthorizationFilter. Populates SecurityContext with JwtAuthenticationToken.'},
  {step: '3. Controller entry', annotations: '@PreAuthorize on controller OR service', internals: 'If on controller: AuthorizationManagerBeforeMethodInterceptor before invoke. MethodArgumentResolver binds PaymentRequest + runs Bean Validation on @Valid.'},
  {step: '4. DTO validation', annotations: '@Valid @NotNull @Positive @Size', internals: 'MethodValidationException or BindException → @ControllerAdvice @ExceptionHandler returns 400 ProblemDetail.'},
  {step: '5. Delegate to service', annotations: '@Autowired PaymentService', internals: 'Injected reference is CGLIB proxy if @Transactional on service. Controller calls proxy.charge(req).'},
  {step: '6. Service proxy entry', annotations: '@Service @Transactional @PreAuthorize("hasAuthority(\'pay\')")', internals: 'Advisors: security check → TransactionInterceptor.getTransaction() → bind Connection to TransactionSynchronizationManager.'},
  {step: '7. Idempotency check', annotations: '@Cacheable(value="idempotency", key="#req.idempotencyKey")', internals: 'CacheInterceptor: Redis GET. Hit → return cached PaymentResult without TX work (still inside TX advisor — watch ordering).'},
  {step: '8. Business logic', annotations: '@Transactional(readOnly=false)', internals: 'Target method: validate merchant, compute amount, fraud rules. this.fraudCheck() TRAP: self-invocation skips @Transactional readOnly on helper.'},
  {step: '9. Persist payment', annotations: '@Repository PaymentJpaRepository', internals: 'Spring Data JDK proxy → SimpleJpaRepository.save. EntityManager join current TX. @Version optimistic lock on PaymentEntity.'},
  {step: '10. Outbox / event', annotations: '@TransactionalEventListener(phase=AFTER_COMMIT) @EventListener', internals: 'PaymentCompletedEvent published in TX; listener registered for afterCommit only — not fired if rollback.'},
  {step: '11. TX commit', annotations: '@Transactional rollbackFor=PaymentException.class', internals: 'TransactionInterceptor commit. Connection released. Cache put if @Cacheable unless SpEL excludes.'},
  {step: '12. Kafka produce (after commit)', annotations: '@KafkaListener on consumer side; producer uses KafkaTemplate', internals: 'Outbox relay or direct kafkaTemplate.send after commit. Producer acks=all, idempotent producer enabled.'},
  {step: '13. Async notification', annotations: '@Async @EventListener on NotificationService', internals: 'AsyncAnnotationBeanPostProcessor proxy submits to taskExecutor. New thread — no HTTP context; propagate MDC manually.'},
  {step: '14. Async listener TX', annotations: '@Transactional on async method', internals: 'NEW transaction in worker thread. Email send + audit log. Failure → rollback async TX only, not original payment TX.'},
  {step: '15. HTTP response', annotations: '@ResponseBody ResponseEntity<PaymentResult>', internals: 'HttpMessageConverter serializes DTO. ObservationFilter records server span. Metrics counter increment.'},
  {step: '16. Error path rollback', annotations: '@Transactional + @ExceptionHandler', internals: 'Unchecked exception → rollback. @ControllerAdvice maps PaymentException to 402. Cache not updated (unless).'},
  {step: '17. Cache eviction on refund', annotations: '@CacheEvict @Transactional', internals: 'RefundService advises evict after successful TX. Wrong order may evict before commit → stale re-read.'},
  {step: '18. Feign ledger call', annotations: '@FeignClient @CircuitBreaker', internals: 'JDK Feign proxy HTTP call. NOT joining local JPA TX unless distributed TX (rare). Timeout + CB open → fail payment or compensate.'},
  {step: '19. Observability', annotations: '@Observed @NewSpan', internals: 'Micrometer Observation: parent server span, child spans for DB/Kafka. traceId in logs via MDC.'},
  {step: '20. Scheduled reconciliation', annotations: '@Scheduled @Transactional(readOnly=true)', internals: 'Scheduler thread calls bean directly (proxy if advised). Read-only TX for report query — no self-invocation issue.'},
];

export const WHO_PROCESSES: {q: string; a: string}[] = [
  {q: 'Who processes @Component during startup?', a: 'ClassPathBeanDefinitionScanner registers ScannedGenericBeanDefinition — no bean instance yet.'},
  {q: 'Who processes @Autowired on a field?', a: 'AutowiredAnnotationBeanPostProcessor during populateBean → InjectionMetadata.inject.'},
  {q: 'Who processes @Bean methods?', a: 'ConfigurationClassPostProcessor parses @Configuration; factory methods invoked by ConfigurationClassEnhancer CGLIB or direct call (lite mode).'},
  {q: 'Who processes @Transactional at runtime?', a: 'TransactionInterceptor (advisor) created by TransactionManagementConfigurationSelector / Boot JtaAutoConfiguration.'},
  {q: 'Who processes @Async?', a: 'AsyncAnnotationBeanPostProcessor registers AsyncExecutionAdvisor; AsyncExecutionInterceptor wraps method.'},
  {q: 'Who processes @Cacheable?', a: 'CacheInterceptor via CacheAnnotationAutoConfiguration after @EnableCaching.'},
  {q: 'Who processes @PreAuthorize?', a: 'AuthorizationManagerBeforeMethodInterceptor from @EnableMethodSecurity MethodSecurityConfiguration.'},
  {q: 'Who processes @PostConstruct?', a: 'InitDestroyAnnotationBeanPostProcessor (CommonAnnotationBeanPostProcessor) at initializeBean.'},
  {q: 'Who processes @Value("${app.name}")?', a: 'AutowiredAnnotationBeanPostProcessor + EmbeddedValueResolver from PropertySourcesPlaceholderConfigurer.'},
  {q: 'Who processes @ConfigurationProperties?', a: 'ConfigurationPropertiesBindingPostProcessor binds Environment to bean properties.'},
  {q: 'Who processes @KafkaListener?', a: 'KafkaListenerAnnotationBeanPostProcessor registers MessageListener endpoint on KafkaListenerEndpointRegistry.'},
  {q: 'Who processes @EventListener?', a: 'EventListenerMethodProcessor wraps method in ApplicationListenerMethodAdapter.'},
  {q: 'Who processes @TransactionalEventListener?', a: 'TransactionalEventListenerMethodProcessor + TransactionalApplicationListenerSynchronization.'},
  {q: 'Who processes @Scheduled?', a: 'ScheduledAnnotationBeanPostProcessor registers ScheduledMethodRunnable with TaskScheduler.'},
  {q: 'Who processes @Valid on controller param?', a: 'Web MVC HandlerMethodValidator / Bean Validation invoked before controller method (not BeanPostProcessor).'},
  {q: 'Who processes @ControllerAdvice?', a: 'RequestMappingHandlerMapping discovers beans; ExceptionHandlerExceptionResolver maps @ExceptionHandler.'},
  {q: 'Who processes @Import?', a: 'ConfigurationClassParser processes Import metadata during configuration class parsing.'},
  {q: 'Who processes @ConditionalOnClass?', a: 'OnClassCondition during auto-configuration class processing (Spring Boot).'},
  {q: 'Who processes @Scope("request")?', a: 'Bean definition scope metadata; WebApplicationContext creates scoped instance per request; scoped proxy from ScopedProxyUtils.'},
  {q: 'Who processes @Lazy injection?', a: 'LazyAnnotationBeanPostProcessor injects lazy-init proxy that calls getBean on first use.'},
  {q: 'Who processes @Primary?', a: 'DefaultListableBeanFactory.determineAutowireCandidate checks BeanDefinition.isPrimary().'},
  {q: 'Who processes @Qualifier?', a: 'QualifierAnnotationAutowireCandidateResolver during resolveDependency.'},
  {q: 'Who processes @Repository stereotype?', a: 'Scanner + PersistenceExceptionTranslationPostProcessor for SQLException translation.'},
  {q: 'Who processes JPA @Entity?', a: 'Hibernate MetadataBuilder / persistence unit bootstrap — not Spring core (unless entity scan).'},
  {q: 'Who processes Spring Data repository interface?', a: 'JpaRepositoriesRegistrar + JpaRepositoryFactory creates JDK dynamic proxy implementation.'},
  {q: 'Who processes @FeignClient?', a: 'FeignClientsRegistrar registers factory bean; Feign builds JDK proxy at runtime.'},
  {q: 'Who processes @RefreshScope?', a: 'RefreshScope lifecycle + scoped proxy; ContextRefresher recreates bean on /actuator/refresh.'},
  {q: 'Who processes @Aspect @Around?', a: 'AnnotationAwareAspectJAutoProxyCreator weaves advisor from @Aspect bean.'},
  {q: 'Who processes @EnableAutoConfiguration?', a: 'AutoConfigurationImportSelector loads META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports.'},
  {q: 'Who processes @SpringBootApplication?', a: 'Combination processed by SpringApplication.run → bootstrap readers for scan + auto-config.'},
  {q: 'Who processes @PropertySource?', a: 'PropertySourceAnnotationParser adds PropertySource to Environment.'},
  {q: 'Who processes @Profile?', a: 'ProfileCondition evaluates active profiles against @Profile value.'},
  {q: 'Who processes @DependsOn?', a: 'AbstractBeanFactory ensures dependent bean names created first (definition metadata).'},
  {q: 'Who processes @Lookup?', a: 'AutowiredAnnotationBeanPostProcessor / CGLIB subclass overrides lookup method to getBean().'},
  {q: 'Who processes @MockBean in tests?', a: 'MockitoPostProcessor replaces bean definition in test ApplicationContext.'},
  {q: 'Who processes @DynamicPropertySource?', a: 'DynamicPropertyRegistryContextCustomizer before context refresh.'},
  {q: 'Who processes @Sql test scripts?', a: 'SqlScriptsTestExecutionListener executes scripts around test method.'},
  {q: 'Who processes @DirtiesContext?', a: 'DirtiesContextTestExecutionListener marks context dirty for reload.'},
  {q: 'Who processes @CrossOrigin?', a: 'RequestMappingHandlerMapping stores CORS config; CorsFilter handles preflight.'},
  {q: 'Who processes @RequestBody JSON?', a: 'RequestResponseBodyMethodProcessor + MappingJackson2HttpMessageConverter.'},
  {q: 'Who processes @PathVariable?', a: 'PathVariableMethodArgumentResolver extracts URI template variables.'},
  {q: 'Who processes @PageableDefault?', a: 'PageableHandlerMethodArgumentResolver builds Pageable from query params.'},
  {q: 'Who processes @AuthenticationPrincipal?', a: 'AuthenticationPrincipalArgumentResolver reads SecurityContextHolder.'},
  {q: 'Who processes @WithMockUser?', a: 'SecurityContextTestExecutionListener sets SecurityContext before test.'},
  {q: 'Who processes @Retryable?', a: 'RetryOperationsInterceptor from spring-retry configuration.'},
  {q: 'Who processes @CircuitBreaker?', a: 'Resilience4j Spring Boot aspect / CircuitBreakerAspect.'},
  {q: 'Who processes @Observed?', a: 'ObservationBeanPostProcessor or ObservationAspect (Micrometer).'},
  {q: 'Who processes @HttpExchange client?', a: 'HttpServiceProxyFactory (Boot 3) creates HTTP interface proxy.'},
  {q: 'Who processes @ConstructorBinding?', a: 'ConfigurationPropertiesBeanRegistrar registers constructor-bound properties bean.'},
  {q: 'Who processes @ImportRuntimeHints?', a: 'RuntimeHintsRegistrar during AOT processing (Spring 6 native).'},
  {q: 'Who processes @EnableWebSecurity?', a: 'WebSecurityConfiguration / SecurityFilterChainConfiguration registers filter beans.'},
  {q: 'Who processes @Order on beans?', a: 'Not a processor — Ordered.getOrder() consulted when sorting advisors, filters, listeners.'},
  {q: 'Who processes @Transactional rollback rules?', a: 'RuleBasedTransactionAttribute inside TransactionInterceptor interprets annotation attributes.'},
  {q: 'Who processes @CacheEvict allEntries?', a: 'CacheInterceptor invokes Cache.clear() on named cache after/before method.'},
  {q: 'Who processes @Modifying @Query?', a: 'Spring Data query execution listener — requires @Transactional for flush.'},
  {q: 'Who processes @Version optimistic lock?', a: 'Hibernate dirty checking at flush — OptimisticLockException on stale version.'},
  {q: 'Who processes @EntityGraph on repository method?', a: 'JpaQueryLookupStrategy applies fetch graph to query.'},
  {q: 'Who processes @SendTo Kafka reply?', a: 'MessagingMessageListenerAdapter with @SendTo result handling (Spring Kafka).'},
  {q: 'Who processes @EnableKafka?', a: 'KafkaAnnotationDrivenConfiguration registers listener annotation processor.'},
  {q: 'Who processes @JmsListener?', a: 'JmsListenerAnnotationBeanPostProcessor.'},
  {q: 'Who processes @RabbitListener?', a: 'RabbitListenerAnnotationBeanPostProcessor.'},
  {q: 'Who processes @Validated on service class?', a: 'MethodValidationPostProcessor adds MethodValidationInterceptor for method-level constraints.'},
  {q: 'Who processes @InitBinder?', a: 'RequestMappingHandlerAdapter invokes @ControllerAdvice @InitBinder methods for WebDataBinder.'},
  {q: 'Who processes @ResponseStatus on exception?', a: 'ResponseStatusExceptionResolver / ExceptionHandlerExceptionResolver.'},
  {q: 'Who processes @Bean ObjectMapper customization?', a: 'JacksonAutoConfiguration backs off; your @Bean replaces auto-configured ObjectMapper.'},
  {q: 'Who processes @ConditionalOnMissingBean?', a: 'OnBeanCondition during auto-config — skips if bean type already defined.'},
  {q: 'Who processes @AutoConfigureAfter DataSource?', a: 'AutoConfigurationSorter orders configuration classes — not runtime processor.'},
  {q: 'Who processes @ServiceConnection Testcontainers?', a: 'ServiceConnectionContextCustomizer wires dynamic properties from container.'},
  {q: 'Who processes @Commit on test?', a: 'TransactionalTestExecutionListener disables default rollback.'},
  {q: 'Who processes @WebMvcTest slice?', a: 'WebMvcTestContextBootstrapper limits component scan to MVC layer.'},
  {q: 'Who processes @DataJpaTest slice?', a: 'DataJpaTestContextBootstrapper — JPA + repositories only.'},
  {q: 'Who processes @SpringBootTest full context?', a: 'SpringBootContextLoader loads entire application (slow integration test).'},
  {q: 'Who processes @RolesAllowed?', a: 'Jsr250MethodSecurityConfiguration → MethodSecurityInterceptor.'},
  {q: 'Who processes @PermitAll on method?', a: 'Method security metadata source — allows without role if authenticated.'},
  {q: 'Who processes @CacheConfig defaults?', a: 'CacheAnnotationParser reads class-level cache names/keyGenerator on advised methods.'},
  {q: 'Who processes @EnableCaching import?', a: 'CachingConfigurationSelector imports cache advisor infrastructure.'},
  {q: 'Who processes @EnableAsync import?', a: 'AsyncConfigurationSelector imports async annotation processor.'},
  {q: 'Who processes @EnableTransactionManagement?', a: 'TransactionManagementConfigurationSelector — proxyTargetClass from @EnableAspectJAutoProxy.'},
  {q: 'Who processes @ComponentScan filter?', a: 'ComponentScanAnnotationParser applies TypeFilter (regex, assignable, custom).'},
  {q: 'Who processes @ImportResource XML?', a: 'ConfigurationClassParser delegates to XmlBeanDefinitionReader.'},
  {q: 'Who processes DeferredImportSelector?', a: 'ConfigurationClassParser deferred import queue — AutoConfigurationImportSelector uses this.'},
  {q: 'Who processes @Bean initMethod?', a: 'AbstractAutowireCapableBeanFactory invokes named init after properties set.'},
  {q: 'Who processes DisposableBean destroy?', a: 'DisposableBeanAdapter calls destroy / @PreDestroy on context shutdown.'},
  {q: 'Who processes ApplicationContextAware?', a: 'AwareProcessor invokes setApplicationContext during initializeBean.'},
  {q: 'Who processes BeanFactoryPostProcessor?', a: 'AbstractApplicationContext.invokeBeanFactoryPostProcessors before bean instantiation.'},
  {q: 'Who processes BeanPostProcessor?', a: 'AbstractAutowireCapableBeanFactory registerBeanPostProcessors — applied per bean create.'},
  {q: 'Who processes @Conditional custom class?', a: 'Your Condition implementation matches ConditionContext during bean registration.'},
  {q: 'Who processes @Scheduled cron?', a: 'CronTrigger parsed by ScheduledAnnotationBeanPostProcessor.'},
  {q: 'Who processes @NewSpan tracing?', a: 'Micrometer ObservationAspect or Brave TracingAspect around advised methods.'},
  {q: 'Who processes @Bulkhead?', a: 'Resilience4j BulkheadAspect before method proceed.'},
  {q: 'Who processes @TimeLimiter?', a: 'Resilience4j TimeLimiterAspect wraps call with timeout.'},
  {q: 'Who processes @RateLimiter?', a: 'Resilience4j RateLimiterAspect acquires permit before proceed.'},
  {q: 'Who processes @Lock (Spring Integration)?', a: 'LockRegistryAdvisor around advised methods.'},
  {q: 'Who processes @Schema OpenAPI?', a: 'springdoc OpenAPIService scans @RestController at runtime/doc build.'},
  {q: 'Who processes @Hidden endpoint?', a: 'springdoc filters operations from OpenAPI model — endpoint still mapped by MVC.'},
  {q: 'Who processes @RequestScope in singleton?', a: 'ScopedProxyFactoryBean creates CGLIB scoped proxy delegating to current request bean.'},
  {q: 'Who processes @SessionScope in singleton?', a: 'Same scoped proxy pattern with session scope target.'},
  {q: 'Who processes @ApplicationListener interface?', a: 'GenericApplicationListenerAdapter registered as listener bean.'},
  {q: 'Who processes SmartLifecycle start?', a: 'DefaultLifecycleProcessor starts beans on context refresh.'},
  {q: 'Who processes @Endpoint Actuator?', a: 'WebEndpointDiscoverer maps @Endpoint bean to HTTP/JMX exposure.'},
  {q: 'Who processes @ControllerEndpoint?', a: 'ControllerEndpointHandlerMapping for actuator web extensions.'},
  {q: 'Who processes Environment property binding?', a: 'Binder (Boot) + PropertySourcesPropertyResolver for relaxed binding.'},
  {q: 'Who processes @DefaultValue on record props?', a: 'ConfigurationPropertiesBindingPostProcessor applies default when property missing (Boot 3.2+).'},
  {q: 'Who processes @Named (JSR-330)?', a: 'ComponentScan treats as stereotype with explicit bean name.'},
  {q: 'Who processes @Inject?', a: 'AutowiredAnnotationBeanPostProcessor (required=true always).'},
  {q: 'Who processes @Resource?', a: 'CommonAnnotationBeanPostProcessor — name from @Resource or field name.'},
  {q: 'Who processes @PostAuthorize return check?', a: 'AuthorizationManagerAfterMethodInterceptor after method returns.'},
  {q: 'Who processes @Secured("ROLE_ADMIN")?', a: 'AuthorizationManagerBeforeMethodInterceptor legacy secured metadata.'},
  {q: 'Who processes @EnableAspectJAutoProxy exposeProxy?', a: 'AnnotationAwareAspectJAutoProxyCreator sets exposeProxy flag on AopContext.'},
  {q: 'Who processes CGLIB vs JDK proxy choice?', a: 'AutoProxyCreator: interface → JDK if proxyTargetClass=false; else CGLIB subclass.'},
  {q: 'Who processes @Transactional(propagation=NESTED)?', a: 'TransactionInterceptor + NestedTransactionStatus with JDBC savepoint.'},
  {q: 'Who processes @TransactionalEventListener BEFORE_COMMIT?', a: 'TransactionalApplicationListenerSynchronization fires before commit phase.'},
  {q: 'Who processes @Async UncaughtExceptionHandler?', a: 'AsyncConfigurer.getAsyncUncaughtExceptionHandler on failed async method.'},
  {q: 'Who processes @Cacheable sync=true lock?', a: 'CacheAspectSupport sync block around cache load for same key.'},
  {q: 'Who processes @KafkaTransactional?', a: 'KafkaTransactionManager + ChainedKafkaTransactionManager if combined with DB.'},
  {q: 'Who processes @SendToUser STOMP?', a: 'SendToMethodReturnValueHandler routes to user session queue.'},
  {q: 'Who processes @MessageMapping WebSocket?', a: 'SimpAnnotationMethodMessageHandler maps STOMP destinations.'},
  {q: 'Who processes @EnableWebMvc?', a: 'WebMvcConfigurationSupport — disables Boot WebMvcAutoConfiguration defaults.'},
  {q: 'Who processes @RestControllerAdvice?', a: 'Same as @ControllerAdvice + @ResponseBody meta.'},
  {q: 'Who processes ProblemDetail (Boot 3)?', a: 'ResponseEntityExceptionHandler + RFC 7807 support in MVC exception handlers.'},
];

export const DOES_PROXY: {q: string; a: string}[] = [
  {q: 'Does @Transactional create a proxy?', a: 'Yes — TransactionInterceptor advises the bean; external calls go through CGLIB or JDK proxy.'},
  {q: 'Does @Async create a proxy?', a: 'Yes — AsyncAnnotationBeanPostProcessor wraps bean so @Async methods dispatch to TaskExecutor.'},
  {q: 'Does @Cacheable create a proxy?', a: 'Yes — CacheInterceptor wraps advised methods (requires @EnableCaching).'},
  {q: 'Does @PreAuthorize create a proxy?', a: 'Yes — method security interceptor advises bean when @EnableMethodSecurity enabled.'},
  {q: 'Does @Service alone create a proxy?', a: 'No — stereotype only registers bean; proxy appears if cross-cutting annotations present.'},
  {q: 'Does @Component alone create a proxy?', a: 'No — unless scoped proxy, @Lazy injection proxy, or advising annotations added.'},
  {q: 'Does @Repository create a proxy?', a: 'Not for TX — PersistenceExceptionTranslationPostProcessor is not MethodInterceptor AOP.'},
  {q: 'Does @Controller create a proxy?', a: 'No for stereotype; controller may still be proxied for @Transactional on class.'},
  {q: 'Does @Configuration create a proxy?', a: 'Yes for full @Configuration — CGLIB subclass so @Bean inter-calls respect singleton semantics.'},
  {q: 'Does @Bean create a proxy?', a: 'No on the factory method; returned object may be advised if type has @Transactional etc.'},
  {q: 'Does @Autowired create a proxy?', a: 'No — injects existing bean reference which may already be a proxy.'},
  {q: 'Does @Lazy on injection create a proxy?', a: 'Yes — lazy-init proxy resolves real bean on first method invocation.'},
  {q: 'Does @Scope(request) in singleton need proxy?', a: 'Yes — inject scoped proxy (TARGET_CLASS or INTERFACES) or wrong instance per call.'},
  {q: 'Does self-invocation use proxy?', a: 'No — this.method() calls target directly; all @Transactional/@Cacheable/@Async bypassed.'},
  {q: 'Does @EventListener create a proxy?', a: 'No — listener adapter invokes method on bean; @Async on listener method still needs async proxy.'},
  {q: 'Does @Scheduled create a proxy?', a: 'Scheduler holds bean reference — if bean is advised proxy, scheduled call goes through proxy (good).'},
  {q: 'Does @KafkaListener create a proxy?', a: 'No on annotation; listener container invokes method — advised bean → proxy used if container got proxy.'},
  {q: 'Does Spring Data JPA repository create a proxy?', a: 'Yes — JDK dynamic proxy implementing repository interface (different from Spring AOP).'},
  {q: 'Does @FeignClient create a proxy?', a: 'Yes — JDK proxy for HTTP client interface (Feign, not Spring AOP).'},
  {q: 'Does @Validated on class create a proxy?', a: 'MethodValidationPostProcessor may add MethodValidationInterceptor — partial AOP on public methods.'},
  {q: 'Does @Aspect create a proxy on target?', a: 'Aspect bean itself usually not proxied; it creates advisors applied to other beans.'},
  {q: 'Does @Retryable create a proxy?', a: 'Yes — RetryOperationsInterceptor advises matching methods.'},
  {q: 'Does @CircuitBreaker create a proxy?', a: 'Yes — resilience aspect wraps method.'},
  {q: 'Does @Observed create a proxy?', a: 'Yes — ObservationAspect advises methods for metrics/tracing.'},
  {q: 'Does @RefreshScope create a proxy?', a: 'Yes — scoped proxy recreates target on refresh.'},
  {q: 'Does @Lookup create a proxy?', a: 'CGLIB subclass overrides lookup method — subclass proxy of containing bean.'},
  {q: 'Does @Transactional on private method get proxy?', a: 'No — Spring AOP cannot advise private methods (subclass cannot override).'},
  {q: 'Does @Transactional on final method get proxy?', a: 'No with CGLIB — final methods cannot be overridden in subclass proxy.'},
  {q: 'Does interface-only bean use JDK proxy?', a: 'Yes when proxying interfaces and proxyTargetClass=false; only interface methods advised.'},
  {q: 'Does concrete class with interface use CGLIB?', a: 'Boot default proxyTargetClass=true → CGLIB even if interfaces exist.'},
  {q: 'Does @EnableAspectJAutoProxy force proxy?', a: 'Registers AutoProxyCreator — beans matching pointcuts get proxied at creation.'},
  {q: 'Does @PostConstruct run on proxy or target?', a: 'Lifecycle callbacks run on target object after initialization; proxy wraps initialized target.'},
  {q: 'Does injecting self with @Autowired create double proxy?', a: 'Usually injects same singleton proxy reference from cache — not second proxy.'},
  {q: 'Does AopContext.currentProxy() return proxy?', a: 'Yes if exposeProxy=true — use for intentional self-invocation through advisors.'},
  {q: 'Does @Transactional on controller create proxy?', a: 'Yes if advised — but prefer service-layer TX; controller proxy is antipattern.'},
  {q: 'Does @Cacheable on private method work?', a: 'No — not advised; no proxy interception on private methods.'},
  {q: 'Does @Async on same class internal call work?', a: 'No — self-invocation bypasses async proxy.'},
  {q: 'Does @PreAuthorize on repository interface work?', a: 'Yes if JDK proxy on repository — method security can advise Spring Data proxy.'},
  {q: 'Does @HttpExchange client use proxy?', a: 'Yes — JDK HTTP invoker proxy (Boot 3 declarative HTTP).'},
  {q: 'Does @MockBean replace with proxy?', a: 'Replaces bean with Mockito mock/spy in test context — not CGLIB advisor proxy.'},
  {q: 'Does @SpyBean wrap in proxy?', a: 'Spy wraps real bean — Mockito spy, not Spring AOP.'},
  {q: 'Does prototype bean get new proxy each time?', a: 'Each getBean creates new instance; if advised, new proxy per instance.'},
  {q: 'Does @Order affect proxy creation?', a: 'No — affects advisor chain order on existing proxy.'},
  {q: 'Does final class prevent @Transactional proxy?', a: 'Yes — CGLIB cannot subclass final class; use interface JDK proxy or remove final.'},
  {q: 'Does @Transactional on @Configuration class advise @Bean methods?', a: 'Trap: @Bean method invocation via CGLIB config proxy — TX may apply to factory method incorrectly.'},
  {q: 'Does lite @Configuration (proxyBeanMethods=false) proxy @Bean calls?', a: 'No — inter-@Bean method calls are plain Java — new instance each call.'},
  {q: 'Does @Scope prototype inside singleton inject proxy?', a: 'Without ObjectProvider/@Lookup, singleton gets one prototype instance — not scoped proxy.'},
  {q: 'Does @Cacheable on interface method advise impl?', a: 'Yes if proxy implements interface and annotation on interface (JDK) or impl class (CGLIB).'},
  {q: 'Does @Transactional on interface method work?', a: 'Yes — annotation on interface honored by Spring TX annotation parser.'},
  {q: 'Does @Async on interface default method work?', a: 'Depends on proxy type — generally put @Async on concrete public method.'},
  {q: 'Does WebClient create Spring AOP proxy?', a: 'No — WebClient is reactive client builder, not advised bean by default.'},
  {q: 'Does RestTemplate create proxy?', a: 'No — unless you wrap bean with custom aspect.'},
  {q: 'Does @Entity create proxy?', a: 'Hibernate may create runtime bytecode proxy for lazy associations — separate from Spring AOP.'},
  {q: 'Does Hibernate lazy collection create proxy?', a: 'Yes — persistence provider proxy, not Spring.'},
  {q: 'Does @JsonIgnore on entity avoid Hibernate proxy issues?', a: 'Serialization issue separate — use DTOs not Spring proxy question.'},
  {q: 'Does @Transactional REQUIRES_NEW need new proxy call?', a: 'Needs external proxy call — self-invocation cannot start new TX via annotation.'},
  {q: 'Does @Cacheable unless SpEL need proxy?', a: 'Yes — SpEL evaluated in CacheInterceptor around advised invocation.'},
  {q: 'Does @RolesAllowed need proxy?', a: 'Yes — same method security infrastructure as @PreAuthorize.'},
  {q: 'Does filter chain replace bean proxy?', a: 'No — servlet filters run before DispatcherServlet; bean proxies at service layer.'},
  {q: 'Does @ControllerAdvice use proxy?', a: 'No — MVC invokes advice bean methods directly for exception handling.'},
  {q: 'Does @ExceptionHandler need proxy?', a: 'No — resolved by exception resolver infrastructure.'},
  {q: 'Does @Valid need proxy?', a: 'No — validation runs in argument resolver before method body.'},
  {q: 'Does @InitBinder need proxy?', a: 'No.'},
  {q: 'Does @ModelAttribute need proxy?', a: 'No.'},
  {q: 'Does @RequestBody need proxy?', a: 'No.'},
  {q: 'Does @ResponseBody need proxy?', a: 'No.'},
  {q: 'Does @CrossOrigin need proxy?', a: 'No — CORS metadata on handler mapping.'},
  {q: 'Does @Timed need proxy?', a: 'Yes — metrics aspect.'},
  {q: 'Does @Counted need proxy?', a: 'Yes — metrics aspect.'},
  {q: 'Does @NewSpan need proxy?', a: 'Yes — tracing aspect wraps method.'},
  {q: 'Does @Bulkhead need proxy?', a: 'Yes.'},
  {q: 'Does @RateLimiter need proxy?', a: 'Yes.'},
  {q: 'Does @Lock (integration) need proxy?', a: 'Yes — advisory lock around method.'},
  {q: 'Does @SendTo need proxy?', a: 'No — messaging metadata.'},
  {q: 'Does @TransactionalEventListener need proxy?', a: 'No on registration; invoked by event multicaster in TX synchronization.'},
  {q: 'Does @DirtiesContext use proxy?', a: 'No — test framework reloads context.'},
  {q: 'Does @Sql use proxy?', a: 'No.'},
  {q: 'Does @Commit use proxy?', a: 'No.'},
  {q: 'Does @DynamicPropertySource use proxy?', a: 'No.'},
  {q: 'Does @ServiceConnection use proxy?', a: 'No.'},
  {q: 'Does @ConditionalOnBean use proxy?', a: 'No — condition at definition time.'},
  {q: 'Does @Primary use proxy?', a: 'No.'},
  {q: 'Does @Qualifier use proxy?', a: 'No.'},
  {q: 'Does @Value use proxy?', a: 'No.'},
  {q: 'Does @ConfigurationProperties use proxy?', a: 'No unless combined with @RefreshScope scoped proxy.'},
  {q: 'Does @Profile use proxy?', a: 'No.'},
  {q: 'Does @Import use proxy?', a: 'No.'},
  {q: 'Does @PropertySource use proxy?', a: 'No.'},
  {q: 'Does @EnableAutoConfiguration use proxy?', a: 'No.'},
  {q: 'Does @SpringBootApplication use proxy?', a: 'No.'},
  {q: 'Does @PostAuthorize need proxy?', a: 'Yes — after-method security interceptor.'},
  {q: 'Does @Secured need proxy?', a: 'Yes.'},
  {q: 'Does @PermitAll on method need proxy?', a: 'Yes when method security enabled.'},
  {q: 'Does exposing @Bean PaymentService return proxied instance?', a: 'If PaymentService has @Transactional, getBean returns exposed proxy from singleton cache.'},
  {q: 'Does calling bean from non-Spring code use proxy?', a: 'Only if you hold reference from container — new PaymentService() has no proxy.'},
  {q: 'Does @Transactional on package-private method work?', a: 'Spring 5.2+ may advise package-private via CGLIB if same module — prefer public; still no self-invocation.'},
  {q: 'Does AspectJ compile-time weaving need runtime proxy?', a: 'No — bytecode woven at compile time; self-invocation works if woven.'},
  {q: 'Does @EnableTransactionManagement(mode=ASPECTJ) use proxy?', a: 'AspectJ weaving — not Spring JDK/CGLIB proxy for TX.'},
];
