export type VersionMatrixRow = {
  annotation: string;
  spring4: string;
  spring5: string;
  spring6: string;
  boot2: string;
  boot3: string;
  current: string;
  status: string;
};

export const VERSION_MATRIX: VersionMatrixRow[] = [
  {
    annotation: '@PostConstruct',
    spring4: 'javax.annotation.PostConstruct (JSR-250)',
    spring5: 'javax.annotation.PostConstruct',
    spring6: 'jakarta.annotation.PostConstruct',
    boot2: 'javax — InitDestroyAnnotationBeanPostProcessor',
    boot3: 'jakarta — same BPP',
    current: 'jakarta.annotation.PostConstruct',
    status: 'javax→jakarta rename; mechanism unchanged',
  },
  {
    annotation: '@PreDestroy',
    spring4: 'javax.annotation.PreDestroy',
    spring5: 'javax.annotation.PreDestroy',
    spring6: 'jakarta.annotation.PreDestroy',
    boot2: 'javax',
    boot3: 'jakarta',
    current: 'jakarta.annotation.PreDestroy',
    status: 'javax→jakarta',
  },
  {
    annotation: '@Resource',
    spring4: 'javax.annotation.Resource',
    spring5: 'javax.annotation.Resource',
    spring6: 'jakarta.annotation.Resource',
    boot2: 'javax — name-first injection',
    boot3: 'jakarta — CommonAnnotationBeanPostProcessor',
    current: 'jakarta.annotation.Resource',
    status: 'javax→jakarta; still supported alongside @Autowired',
  },
  {
    annotation: '@Entity (JPA)',
    spring4: 'javax.persistence.Entity',
    spring5: 'javax.persistence.Entity',
    spring6: 'jakarta.persistence.Entity',
    boot2: 'javax.persistence.*',
    boot3: 'jakarta.persistence.* (Hibernate 6)',
    current: 'jakarta.persistence.Entity',
    status: 'javax.persistence → jakarta.persistence (Boot 3 breaking)',
  },
  {
    annotation: '@Valid',
    spring4: 'javax.validation.Valid',
    spring5: 'javax.validation.Valid',
    spring6: 'jakarta.validation.Valid',
    boot2: 'javax.validation (Bean Validation 2.0)',
    boot3: 'jakarta.validation (BV 3.0)',
    current: 'jakarta.validation.Valid',
    status: 'javax→jakarta validation API',
  },
  {
    annotation: '@Transactional',
    spring4: 'org.springframework.transaction.annotation',
    spring5: 'Same; reactive TX added',
    spring6: 'Same; jakarta EE alignment on dependencies',
    boot2: 'Auto-config JpaTransactionManager',
    boot3: 'Same; native image hints optional',
    current: 'Unchanged package; behavior stable',
    status: 'Stable — proxy semantics unchanged',
  },
  {
    annotation: 'WebSecurityConfigurerAdapter',
    spring4: 'Extend for SecurityFilterChain',
    spring5: 'Deprecated in 5.7',
    spring6: 'Removed',
    boot2: 'Still available Boot 2.7',
    boot3: 'Removed — @Bean SecurityFilterChain only',
    current: 'Use @Bean SecurityFilterChain DSL',
    status: 'Removed — component-based security config',
  },
  {
    annotation: '@EnableGlobalMethodSecurity',
    spring4: 'prePostEnabled, securedEnabled',
    spring5: 'Deprecated in 5.6',
    spring6: 'Removed',
    boot2: 'Still used in legacy apps',
    boot3: '@EnableMethodSecurity replaces',
    current: '@EnableMethodSecurity',
    status: 'Removed — use @EnableMethodSecurity',
  },
  {
    annotation: '@EnableMethodSecurity',
    spring4: 'N/A',
    spring5: 'Introduced (deprecated old enable)',
    spring6: 'Default for method security',
    boot2: 'Backported in late 2.7',
    boot3: 'Preferred entry annotation',
    current: '@EnableMethodSecurity(prePostEnabled=true)',
    status: 'Current method security enable',
  },
  {
    annotation: 'SecurityFilterChain @Bean',
    spring4: 'Via WebSecurityConfigurerAdapter',
    spring5: 'Lambda DSL introduced',
    spring6: 'Primary configuration style',
    boot2: 'Both styles in 2.7',
    boot3: 'Only @Bean SecurityFilterChain',
    current: 'HttpSecurity lambda DSL',
    status: 'Replaces adapter subclass pattern',
  },
  {
    annotation: 'spring.factories EnableAutoConfiguration',
    spring4: 'META-INF/spring.factories',
    spring5: 'Same',
    spring6: 'Legacy still read in some paths',
    boot2: 'spring.factories key',
    boot3: 'META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports',
    current: 'AutoConfiguration.imports file',
    status: 'Boot 3 splits auto-config registration file',
  },
  {
    annotation: '@AutoConfiguration',
    spring4: 'N/A',
    spring5: 'N/A',
    spring6: 'First-class @AutoConfiguration',
    boot2: '@Configuration in auto-config JARs',
    boot3: '@AutoConfiguration + imports file',
    current: '@AutoConfiguration with @AutoConfigureBefore/After',
    status: 'Boot 2.7+ formalizes auto-config stereotype',
  },
  {
    annotation: '@EnableBinding (Stream)',
    spring4: 'Spring Cloud Stream 1.x',
    spring5: 'Stream 2.x binding interfaces',
    spring6: 'Deprecated / removed in Stream 4+',
    boot2: 'Common in legacy microservices',
    boot3: 'Migrate to spring.cloud.function',
    current: 'Legacy only — function beans',
    status: 'Deprecated — functional programming model',
  },
  {
    annotation: 'Spring Cloud Stream (functional)',
    spring4: 'N/A',
    spring5: 'Stream 3 function support',
    spring6: 'Preferred model',
    boot2: 'Stream 3+ on Boot 2.5+',
    boot3: '@Bean Consumer/Supplier/Function',
    current: 'spring.cloud.function.definition',
    status: 'Replaces @EnableBinding',
  },
  {
    annotation: '@MockBean',
    spring4: 'Boot 1.4+',
    spring5: 'Stable',
    spring6: 'Still present but superseded',
    boot2: 'MockitoPostProcessor override',
    boot3: 'Still works; @MockitoBean preferred 3.4+',
    current: '@MockitoBean successor',
    status: 'Superseded by @MockitoBean (Boot 3.4)',
  },
  {
    annotation: '@MockitoBean',
    spring4: 'N/A',
    spring5: 'N/A',
    spring6: 'spring-test 6.2+ BeanOverride API',
    boot2: 'N/A',
    boot3: 'Boot 3.4+ preferred test mock',
    current: 'org.springframework.test.context.bean.override.mockito',
    status: 'New bean override infrastructure',
  },
  {
    annotation: '@SpyBean / @MockitoSpyBean',
    spring4: 'Boot 1.4+',
    spring5: 'Stable',
    spring6: '@MockitoSpyBean in spring-test 6.2+',
    boot2: '@SpyBean',
    boot3: 'Migrate to @MockitoSpyBean',
    current: '@MockitoSpyBean',
    status: 'Same migration as @MockBean',
  },
  {
    annotation: '@FeignClient',
    spring4: 'Spring Cloud Netflix Feign',
    spring5: 'OpenFeign; spring-cloud-openfeign',
    spring6: 'Same; HttpExchange alternative emerging',
    boot2: '@EnableFeignClients',
    boot3: 'Same; Boot 3 jakarta deps',
    current: '@FeignClient + @EnableFeignClients',
    status: 'Stable; consider @HttpExchange for Boot 3.2+',
  },
  {
    annotation: '@LoadBalanced',
    spring4: 'Netflix Ribbon era',
    spring5: 'Spring Cloud LoadBalancer',
    spring6: 'Spring Cloud LoadBalancer',
    boot2: 'Ribbon removed in Hoxton+',
    boot3: 'LoadBalancerClientFactory',
    current: '@LoadBalanced on RestTemplate/WebClient Builder',
    status: 'Ribbon→Spring Cloud LoadBalancer',
  },
  {
    annotation: '@RefreshScope',
    spring4: 'Spring Cloud Context',
    spring5: 'Stable scoped proxy',
    spring6: 'Stable',
    boot2: 'Config Server + /refresh',
    boot3: 'spring.config.import config trees',
    current: 'RefreshScope + ContextRefresher',
    status: 'Stable; bootstrap context changes in Boot 2.4+',
  },
  {
    annotation: '@ConfigurationProperties',
    spring4: 'Relaxed binding',
    spring5: '@ConstructorBinding preview',
    spring6: 'Constructor binding on records',
    boot2: '@EnableConfigurationProperties',
    boot3: 'Immutable @ConfigurationProperties records',
    current: '@ConfigurationPropertiesScan + records',
    status: 'Constructor binding first-class Boot 3',
  },
  {
    annotation: '@ConstructorBinding',
    spring4: 'N/A',
    spring5: 'On @ConfigurationProperties type',
    spring6: 'Implicit on constructor of @ConfigurationProperties',
    boot2: 'Explicit annotation required',
    boot3: 'Implicit when single constructor',
    current: 'Prefer immutable constructor-bound records',
    status: 'Annotation optional Boot 3 when single ctor',
  },
  {
    annotation: '@RequestMapping (javax.servlet)',
    spring4: 'javax.servlet',
    spring5: 'javax.servlet',
    spring6: 'jakarta.servlet',
    boot2: 'javax.servlet API',
    boot3: 'jakarta.servlet API',
    current: 'jakarta.servlet.* imports in controllers',
    status: 'Servlet API javax→jakarta',
  },
  {
    annotation: '@RestController',
    spring4: 'Stable',
    spring5: 'Stable',
    spring6: 'Same; ProblemDetail RFC 7807 support',
    boot2: 'Stable',
    boot3: 'Stable',
    current: '@RestController',
    status: 'Stable stereotype',
  },
  {
    annotation: '@Controller (WebFlux)',
    spring4: 'WebFlux introduced',
    spring5: 'Reactive stack mature',
    spring6: 'Same',
    boot2: 'spring-boot-starter-webflux',
    boot3: 'Same',
    current: '@RestController on reactive stack',
    status: 'Stable — do not mix blocking JDBC on event loop',
  },
  {
    annotation: '@Scheduled',
    spring4: 'Stable',
    spring5: 'Stable',
    spring6: 'Stable',
    boot2: '@EnableScheduling auto',
    boot3: 'Same',
    current: '@Scheduled',
    status: 'Stable',
  },
  {
    annotation: '@Async',
    spring4: 'Stable',
    spring5: 'Stable',
    spring6: 'Virtual thread TaskExecutor option Boot 3.2+',
    boot2: 'ThreadPoolTaskExecutor default',
    boot3: 'Optional virtual threads',
    current: '@Async + TaskExecutor bean',
    status: 'Stable; virtual threads optional enhancement',
  },
  {
    annotation: '@Cacheable',
    spring4: 'Stable',
    spring5: 'Stable',
    spring6: 'Stable',
    boot2: 'Cache auto-config',
    boot3: 'Same; Caffeine/Redis starters',
    current: '@EnableCaching + CacheManager',
    status: 'Stable',
  },
  {
    annotation: '@KafkaListener',
    spring4: 'spring-kafka 2.x',
    spring5: 'spring-kafka 2.8+',
    spring6: 'spring-kafka 3.x',
    boot2: 'spring-kafka 2.x',
    boot3: 'spring-kafka 3.x; observation API',
    current: '@KafkaListener + observation',
    status: 'Stable; Micrometer observation in kafka 3',
  },
  {
    annotation: '@EnableBatchProcessing',
    spring4: 'Required explicit enable',
    spring5: 'Stable',
    spring6: 'Modular BatchConfigurationSelector',
    boot2: 'Explicit or auto-config',
    boot3: 'BatchAutoConfiguration often sufficient',
    current: '@EnableBatchProcessing optional with Boot auto-config',
    status: 'Boot 3 may auto-configure without explicit enable',
  },
  {
    annotation: '@StepScope',
    spring4: 'Stable scoped proxy',
    spring5: 'Stable',
    spring6: 'Stable',
    boot2: 'Job parameter injection',
    boot3: 'Same',
    current: '@StepScope on @Bean step components',
    status: 'Stable batch scoped proxy',
  },
  {
    annotation: '@CircuitBreaker (Resilience4j)',
    spring4: 'Hystrix era (separate)',
    spring5: 'Resilience4j Spring Boot 2',
    spring6: 'Resilience4j 2.x',
    boot2: 'spring-cloud-starter-circuitbreaker-resilience4j',
    boot3: 'Same; AOP annotations',
    current: '@CircuitBreaker @Retry @RateLimiter',
    status: 'Hystrix removed — Resilience4j standard',
  },
  {
    annotation: '@EnableDiscoveryClient',
    spring4: 'Netflix Eureka',
    spring5: 'Abstract discovery',
    spring6: 'Stable',
    boot2: 'Eureka/Consul starters',
    boot3: 'Kubernetes often replaces',
    current: 'Optional — auto-config may suffice',
    status: 'Stable but K8s service discovery common',
  },
  {
    annotation: '@EnableRedisHttpSession',
    spring4: 'spring-session-data-redis',
    spring5: 'Stable',
    spring6: 'Stable',
    boot2: 'spring-session',
    boot3: 'Same',
    current: '@EnableRedisHttpSession',
    status: 'Stable distributed session',
  },
  {
    annotation: '@DirtiesContext',
    spring4: 'spring-test',
    spring5: 'Stable',
    spring6: 'Stable',
    boot2: 'Test context cache eviction',
    boot3: 'Same',
    current: '@DirtiesContext — expensive',
    status: 'Stable test annotation',
  },
  {
    annotation: '@DynamicPropertySource',
    spring4: 'N/A',
    spring5: 'Introduced spring-test 5.2.5',
    spring6: 'Stable',
    boot2: 'Boot 2.2+ Testcontainers pattern',
    boot3: 'Preferred over @TestPropertySource for dynamic ports',
    current: '@DynamicPropertySource static method',
    status: 'Stable — Testcontainers integration',
  },
  {
    annotation: '@HttpExchange (declarative HTTP)',
    spring4: 'N/A',
    spring5: 'N/A',
    spring6: 'Spring Framework 6 / Boot 3.2+',
    boot2: 'N/A',
    boot3: 'Alternative to @FeignClient',
    current: '@HttpExchange interface + HttpServiceProxyFactory',
    status: 'New — native Spring 6 declarative clients',
  },
  {
    annotation: '@Observed (Micrometer)',
    spring4: 'N/A',
    spring5: 'Micrometer Observation preview',
    spring6: 'ObservationRegistry AOP',
    boot2: 'Micrometer tracing evolving',
    boot3: 'Micrometer Observation first-class',
    current: '@Observed on beans/methods',
    status: 'Boot 3 observability standard',
  },
  {
    annotation: 'Native AOT / RuntimeHints',
    spring4: 'N/A',
    spring5: 'N/A',
    spring6: 'Spring AOT processing',
    boot2: 'N/A',
    boot3: 'GraalVM native image support',
    current: 'RuntimeHints + @RegisterReflectionForBinding',
    status: 'Boot 3 native — annotation reflection hints required',
  },
];

export const VERSION_MATRIX_COUNT = VERSION_MATRIX.length;
