import type {TocItem} from './types';

export const CMP_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview'},
  {id: 'comparable', label: '01. Comparable fundamentals'},
  {id: 'contract', label: '02. compareTo contract'},
  {id: 'implement', label: '03. Implementing Comparable'},
  {id: 'overflow', label: '04. Subtraction bug · overflow'},
  {id: 'comparator', label: '05. Comparator fundamentals'},
  {id: 'vs', label: '06. Comparable vs Comparator'},
  {id: 'create', label: '07. Creating Comparators'},
  {id: 'api', label: '08. Java 8+ Comparator API'},
  {id: 'primitive', label: '09. comparing vs comparingInt'},
  {id: 'multilevel', label: '10. Multi-level sorting'},
  {id: 'ascdesc', label: '11. Asc / desc · reverse'},
  {id: 'nulls', label: '12. Null handling'},
  {id: 'collections', label: '13. Sorting collections'},
  {id: 'treeset', label: '14. TreeSet'},
  {id: 'treemap', label: '15. TreeMap'},
  {id: 'priorityqueue', label: '16. PriorityQueue'},
  {id: 'streams', label: '17. Stream.sorted'},
  {id: 'stable', label: '18. Stable sorting · TimSort'},
  {id: 'strings', label: '19. Sorting strings'},
  {id: 'dates', label: '20. Sorting dates'},
  {id: 'domain', label: '21. Domain examples'},
  {id: 'inheritance', label: '22. Inheritance'},
  {id: 'generics', label: '23. Generics · ? super T'},
  {id: 'eqhc', label: '24. equals · hashCode · compareTo'},
  {id: 'bigdecimal', label: '25. BigDecimal corner case'},
  {id: 'cmp-contract', label: '26. Comparator contract'},
  {id: 'float', label: '27. Float / overflow traps'},
  {id: 'optional', label: '28. Optional / null fields'},
  {id: 'reuse', label: '29. Reuse · Strategy'},
  {id: 'perf', label: '30. Performance'},
  {id: 'sort-apis', label: '31. Arrays · Collections · List'},
  {id: 'production', label: '32. Production systems'},
  {id: 'mutable', label: '33. Mutable keys in Tree*'},
  {id: 'threads', label: '34. Thread safety · serialize'},
  {id: 'debug', label: '35. Debugging checklist'},
  {id: 'scenarios', label: '36. Interview scenarios'},
  {id: 'predict', label: '37. Predict the output'},
  {id: 'coding', label: '38. Coding problems'},
  {id: 'modern', label: '39. Java 8→21 · records · enums'},
  {id: 'mistakes', label: '40. Production mistakes'},
  {id: 'traps', label: '41. Trap questions'},
  {id: 'rapid', label: '42. Rapid-fire'},
  {id: 'staff', label: '43. Senior / Staff Qs'},
  {id: 'templates', label: '44. Spoken templates'},
  {id: 'cheatsheet', label: '45. Cheat sheet'},
  {id: 'decision', label: '46. Decision framework'},
  {id: 'checklist', label: '47. Coverage checklist'},
  {id: 'demo', label: '48. Runnable demos'},
  {id: 'interview', label: '49. Interview mode'},
];

export const MEMORY_SENTENCE =
  'Comparable = natural order inside the type · Comparator = external strategy · TreeSet/TreeMap uniqueness = compare==0 (not equals) · never subtract ints · prefer comparingInt · BigDecimal equals≠compareTo.';

export const VERSION_NOTE =
  'Core Java Comparable/Comparator interview board (Java 8–21). Related: /java-equals-hashcode for Map keys · TreeMap/TreeSet depth lives here.';
