server:
  port: ${SERVER_PORT:8086}
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: health
