import type {InterviewQ} from './types';

export const SENIOR: InterviewQ[] = [
  {id:'s1',topic:'DLQ',question:'What is a DLQ?',answer30s:'A parking topic/table for messages that will not succeed with the current payload or dependency after bounded retries.',answer2m:'In Hadron, poison JSON and invalid CashLines go to cashline-events-dlq and dead_letter_messages. The hot consumer stops looping. Ops correct or wait, then replay onto cashline-events.',followUps:['Topic vs table?'],trick:'Calling the retry topic a DLQ.'},
  {id:'s2',topic:'DLQ',question:'Why do we need a DLQ?',answer30s:'To bound poison/business failures so they do not stall partitions or burn CPU.',answer2m:'One malformed Neptune event with seek-to-current retry will pin a partition. DLQ isolates it, records evidence, and lets other CashLines move.',followUps:['What if we just log and skip?']},
  {id:'s3',topic:'Retry',question:'Retry vs DLQ?',answer30s:'Retry what time can fix. DLQ what data or humans must fix.',answer2m:'DB timeout → retry-1/2/3. Invalid amount → DLQ now. Exhausted timeout → DLQ so someone pages the database, not an infinite loop.',followUps:['Unknown participant?']},
  {id:'s4',topic:'Ordering',question:'When should DLQ not be used?',answer30s:'When skipping a middle lifecycle event corrupts state.',answer2m:'CREATED, UPDATE, SETTLED, COMPLETED. If UPDATE is DLQ’d and SETTLED succeeds, Hadron completes the wrong version. Hold later events.',followUps:['How do you hold them?'],trick:'DLQ Event 2 and keep consuming 3 and 4.'},
  {id:'s5',topic:'Kafka',question:'How do you preserve ordering?',answer30s:'Key by cashLineId so all events share a partition, consume sequentially, check sequence numbers.',answer2m:'Kafka orders per partition only. Same key + same partition count on retry topics + last_processed_sequence + open-DLQ gate.',followUps:['What does concurrency do?']},
  {id:'s6',topic:'Kafka',question:'How does partitioning help?',answer30s:'Parallelism across CashLines, order inside one CashLine.',answer2m:'Four partitions can process four different IDs at once. CL123 never splits. Hot keys skew; we accept skew over wrong settlement.',followUps:['Change partition count?']},
  {id:'s7',topic:'Ordering',question:'What happens if event 2 fails?',answer30s:'Do not apply event 3. Park it. Mark the CashLine blocked.',answer2m:'Event 101 UPDATE fails → DLQ + cashline_state blocked. Event 102 SETTLEMENT sees expected=2 received=3 → waiting_events, not SETTLED.',followUps:['How do you resume?']},
  {id:'s8',topic:'Replay',question:'How do you replay DLQ?',answer30s:'Claim REPLAYING with optimistic lock, publish back to cashline-events, never call the service directly.',answer2m:'POST /api/dlq/{id}/replay sets status, afterCommit produces with the same key. The consumer’s processed_events UNIQUE makes a double replay safe.',followUps:['Why not call process() from the API?']},
  {id:'s9',topic:'Idempotency',question:'How do you guarantee idempotency?',answer30s:'UNIQUE(event_id) in the same DB transaction as the CashLine write.',answer2m:'Application checks are racy. The constraint is the lock. Redelivery after a successful commit becomes DUPLICATE.',followUps:['HashSet in memory?'],trick:'If-not-exists without a unique index.'},
  {id:'s10',topic:'EOS',question:'Exactly once vs at least once?',answer30s:'Kafka is at-least-once for this consumer. Business is effectively-once via uniqueness.',answer2m:'Kafka transactions can atomically publish retry/DLQ but do not include Postgres. Do not claim EOS unless the whole path is proven.',followUps:['read_committed?']},
  {id:'s11',topic:'DLQ count',question:'How many DLQs?',answer30s:'One per source topic, reasons in the DB. Not one per exception.',answer2m:'cashline-events-dlq plus failure_reason. Split only for ACL isolation or unparseable schema dumps.',followUps:['Per service vs per topic?']},
  {id:'s12',topic:'Poison',question:'How do you prevent infinite retries?',answer30s:'Classifier sends poison/business to DLQ immediately; transients cap at 3.',answer2m:'DefaultErrorHandler recoverer + maxAttempts. PoisonMessageException is not retryable.',followUps:['What is a poison message?']},
  {id:'s13',topic:'Poison',question:'How do you handle poison messages?',answer30s:'Fail deserialize → DLQ + persist, commit, stop looping.',answer2m:'Malformed JSON, unknown enum, corrupt payload. Zero long retries. Fix schema or payload, replay.',followUps:['Unknown fields vs unknown enum?']},
  {id:'s14',topic:'Persist',question:'How do you persist DLQ?',answer30s:'REQUIRES_NEW insert with unique event_id and Kafka coordinates.',answer2m:'If it joined the failed TX, rollback would erase the ticket. Truncate payload, store exception type/reason/status.',followUps:['What indexes?']},
  {id:'s15',topic:'Persist',question:'DB fails while saving DLQ?',answer30s:'Do not ack. Alert. Let Kafka redeliver. Avoid a silent skip.',answer2m:'You may retry the poison a few times. Losing the DLQ row and committing is worse — the money event vanishes.',followUps:['Dual write DLQ topic and table?']},
  {id:'s16',topic:'TX',question:'DB commit succeeds, Kafka offset commit fails?',answer30s:'Redelivery hits UNIQUE(event_id) and is ignored.',answer2m:'This is the standard at-least-once gap. Effectively-once depends on that unique constraint living in the same SQL transaction as the CashLine mutate.',followUps:['Opposite: ack then DB fail?']},
  {id:'s17',topic:'Cost',question:'How does DLQ save money?',answer30s:'It caps amplification: 10k poison × 3 retries, not × 1000.',answer2m:'CPU, pool connections, Kafka traffic, logs, alerts, downstream APIs, engineer time. DLQ itself costs storage. The saving is stopping uncontrolled repeats.',followUps:['Is DLQ a cost feature?']},
  {id:'s18',topic:'Obs',question:'How do you monitor DLQ?',answer30s:'cashline.dlq counter, lag, retry rate, replay.failed, growth alerts.',answer2m:'DLQ spike + flat retry = bad deploy/payload. Retry spike + flat DLQ = dependency. Never put eventId on Prometheus.',followUps:['Which alert first?']},
  {id:'s19',topic:'Security',question:'How do you secure DLQ?',answer30s:'RBAC on replay, audit actor, mask logs, encrypt at rest, retention.',answer2m:'DLQ is a pile of financial payloads. Replay is a payment write. TLS, Kafka ACLs, least-privilege DB grants.',followUps:['Log the payload for debug?'],trick:'Logging amount and accountId.'},
  {id:'s20',topic:'Schema',question:'How do you handle schema evolution?',answer30s:'Ignore unknown fields; unknown enums are poison until the consumer is upgraded, then replay.',answer2m:'Version the event. Do not silently default an unknown transaction type to DRAWDOWN.',followUps:['Forward vs backward compatible?']},
];

export const ARCHITECT: InterviewQ[] = [
  {id:'a1',topic:'Replay',question:'How do you replay financial transactions safely?',answer30s:'Through Kafka, with optimistic replay lock, state machine, and event_id uniqueness.',answer2m:'Correct payload if needed. Claim REPLAYING. Publish same key. Consumer applies or rejects illegal transitions such as update-after-settle. Mark REPLAYED only after success.',followUps:['Two operators?']},
  {id:'a2',topic:'Money',question:'How do you avoid duplicate payments?',answer30s:'Stable event_id from Neptune plus UNIQUE and idempotent state transitions.',answer2m:'Poller uses neptune-{id}-v{version}. CDC uses offset+PK. Never generate a new UUID on each poll. COMPLETED→COMPLETED is a no-op.',followUps:['Duplicate CashLine ID with new event_id?']},
  {id:'a3',topic:'Rebalance',question:'What happens during consumer rebalance?',answer30s:'In-flight work may be retried by the new owner. Must be idempotent and under max.poll.interval.',answer2m:'Long blocking retry causes rebalances. That is why retry topics exist. Partition reassignment must not apply Event 3 twice as two settlements — uniqueness prevents it.',followUps:['session.timeout vs max.poll.interval']},
  {id:'a4',topic:'OOO',question:'How do you handle out-of-order events?',answer30s:'Partition key plus sequence plus park.',answer2m:'Option A: cashLineId key. Option B: expected=last+1. Use both. If received=3 expected=2, waiting_events, retry/DLQ the gap, do not settle.',followUps:['Tradeoff of blocking the partition?']},
  {id:'a5',topic:'Retry topics',question:'How do you implement retry topics?',answer30s:'On classified retryable failure, produce to retry-n with delay header and same key.',answer2m:'retry-1 5s, retry-2 30s, retry-3 5m, then DLQ. Same partition count. Listeners wait using retry-at or a delay mechanism — not a 5 minute DefaultErrorHandler sleep.',followUps:['Spring RetryTopicConfigurationBuilder?']},
  {id:'a6',topic:'Outbox',question:'Kafka TX vs outbox vs idempotent consumer?',answer30s:'Different gaps. We use idempotent consume for Neptune→Hadron.',answer2m:'Outbox is for Hadron producing downstream. Kafka TX ties consume+produce of retry. Neither replaces UNIQUE(event_id).',followUps:['When add outbox?']},
  {id:'a7',topic:'CDC',question:'CDC or polling from Neptune?',answer30s:'CDC if you can operate it; poller with (updated_at,id) if you cannot.',answer2m:'Polling is explicit and restartable. Timestamp-only cursors drop ties. Produce then advance cursor. Deletes become CANCELLED events.',followUps:['Two poller instances?']},
  {id:'a8',topic:'Hold',question:'Pause partition vs per-CashLine hold?',answer30s:'Prefer per-CashLine hold so other keys in the partition proceed.',answer2m:'Pause/resume is a blunt poison tool. DB blockedReason + sequence gate is the Hadron design.',followUps:['When pause the partition anyway?']},
  {id:'a9',topic:'Multi DLQ',question:'Would you split business/technical/schema/security DLQs?',answer30s:'Not at first. Column for reason. Split for ACL or unserdeable dumps only.',answer2m:'Four topics means four lag alerts, four replay UIs, four forgotten queues. Security isolation is the only strong split.',followUps:['Ops complexity?']},
  {id:'a10',topic:'Crash',question:'App crashes during the DB transaction?',answer30s:'SQL rolls back, Kafka does not ack, redelivery, process again.',answer2m:'If crash after commit before ack, uniqueness saves you. Design for both.',followUps:['Connection pool exhaustion?']},
  {id:'a11',topic:'Corner',question:'Walk the DLQ corner-case matrix.',answer30s:'Classify: RETRY, DLQ now, DLQ after cap, PARK later events, IGNORE duplicate/stale, CONFLICT on replay.',answer2m:'Poison/NPE/enum/invalid amount → DLQ now. Timeout/deadlock → retry then cap. Event 2 fail → park 3/4. Duplicate event_id → ignore. Ack-before-DB is the unrecoverable skip. Replay after SETTLED → reject. Null key and mismatched retry partitions break order.',followUps:['Which case is Sev-1 design vs ops?']},
  {id:'a12',topic:'Corner',question:'Hot poison key vs pause the partition?',answer30s:'DLQ that key and hold that CashLine; let other keys on the partition move.',answer2m:'Pause/resume is for unreadable fetch-layer poison. Per-CashLine open-DLQ hold is the Hadron default so one facility does not freeze a shared partition.',followUps:['Lag skew?']},
];

export const RAPID: InterviewQ[] = [
  {id:'r1',topic:'Rapid',question:'What is the partition key?',answer30s:'cashLineId.',answer2m:'All events for one facility share a partition.',followUps:['Null key?']},
  {id:'r2',topic:'Rapid',question:'Retry intervals in prod?',answer30s:'5s, 30s, 5m, then DLQ.',answer2m:'Lab uses 200/400/800ms so you can watch it.',followUps:['Why not 1 hour in-memory?']},
  {id:'r3',topic:'Rapid',question:'Which SQLSTATE is deadlock?',answer30s:'40P01 / 40001 → retry.',answer2m:'ExceptionClassifier maps those to RETRY.',followUps:['23505?']},
  {id:'r4',topic:'Rapid',question:'23505 means?',answer30s:'Unique violation — usually duplicate, not a hot retry.',answer2m:'processed_events conflict is success-as-duplicate.',followUps:['DLQ it?']},
  {id:'r5',topic:'Rapid',question:'Replay HTTP status on conflict?',answer30s:'409.',answer2m:'Optimistic lock or illegal status.',followUps:['Idempotent replay of REPLAYED?']},
  {id:'r6',topic:'Rapid',question:'Where does offset live?',answer30s:'Outside the SQL transaction.',answer2m:'Ack after successful listener return.',followUps:['auto-commit?']},
  {id:'r7',topic:'Rapid',question:'Cursor fields?',answer30s:'updated_at and id.',answer2m:'Never timestamp alone.',followUps:['Why id?']},
  {id:'r8',topic:'Rapid',question:'COMPLETED → COMPLETED?',answer30s:'Allowed idempotent.',answer2m:'COMPLETED → NEW is illegal.',followUps:['SETTLED → PROCESSING?']},
  {id:'r9',topic:'Rapid',question:'Default profile broker?',answer30s:'In-memory topics, same names.',answer2m:'kafka profile uses Spring Kafka.',followUps:['Why?']},
  {id:'r10',topic:'Rapid',question:'Metric for duplicates?',answer30s:'cashline.duplicate.',answer2m:'Also processed, failed, retry, dlq, replay, replay.failed, out.of.order.',followUps:['Alert on duplicate?']},
  {id:'r11',topic:'Rapid',question:'Header for replay?',answer30s:'hadron-replay-dlq-id.',answer2m:'On success, mark that row REPLAYED.',followUps:['correlationId?']},
  {id:'r12',topic:'Rapid',question:'Max payload in DLQ table?',answer30s:'Capped (256KiB in lab).',answer2m:'Truncate; never log the rest.',followUps:['Object store?']},
  {id:'r13',topic:'Rapid',question:'NPE: retry or DLQ?',answer30s:'DLQ now.',answer2m:'Code will throw again; classifier must not default NPE to RETRY.',followUps:['Timeout?']},
  {id:'r14',topic:'Rapid',question:'SETTLED then UPDATE?',answer30s:'Reject / DLQ. Do not reopen.',answer2m:'Lab: replay-after-settle.',followUps:['CANCELLED then SETTLE?']},
  {id:'r15',topic:'Rapid',question:'Stale seq ≤ last?',answer30s:'Ignore, do not DLQ.',answer2m:'Offset reset is history replay.',followUps:['New event_id old seq?']},
  {id:'r16',topic:'Rapid',question:'Ack before DB commit?',answer30s:'Unrecoverable skip.',answer2m:'Throw before ack; RECORD after return.',followUps:['Opposite gap?']},
];

export const ALL: InterviewQ[] = [...SENIOR, ...ARCHITECT, ...RAPID];
