import type {TocItem} from './types';

export const HADRON_DLQ_TOC: TocItem[] = [
  {id: 'overview', label: '01 Business Story'},
  {id: 'architecture', label: '02 Architecture'},
  {id: 'code-sequences', label: 'Lifecycle Sequences'},
  {id: 'why-dlq', label: '03 Why DLQ'},
  {id: 'retry-vs-dlq', label: '04 Retry vs DLQ'},
  {id: 'when-not', label: '05 When NOT DLQ'},
  {id: 'kafka-ordering', label: '06 Kafka Ordering'},
  {id: 'idempotency', label: '07 Idempotency'},
  {id: 'dlq-database', label: '08 DLQ Database'},
  {id: 'spring-kafka', label: '09 Spring Kafka Config'},
  {id: 'producer', label: '10 Producer'},
  {id: 'consumer', label: '11 Consumer'},
  {id: 'retry', label: '12 Retry Strategies'},
  {id: 'dlq', label: '13 DLQ Topics'},
  {id: 'dlq-persist', label: '14 DLQ Persistence'},
  {id: 'replay', label: '15 Replay'},
  {id: 'cashline-ordering', label: '16 CashLine Ordering'},
  {id: 'state-machine', label: '17 State Machine'},
  {id: 'neptune', label: '18 Neptune Integration'},
  {id: 'transactions', label: '19 Transaction Handling'},
  {id: 'observability', label: '20 Observability'},
  {id: 'security', label: '21 Security'},
  {id: 'docker', label: '22 Docker'},
  {id: 'testing', label: '23 Tests'},
  {id: 'failures', label: '24 DLQ Corner Cases'},
  {id: 'poison', label: 'Poison Messages'},
  {id: 'classifier', label: 'Exception Classifier'},
  {id: 'how-many-dlqs', label: 'How Many DLQs'},
  {id: 'cost', label: 'Cost Saving'},
  {id: 'mistakes', label: 'Production Mistakes'},
  {id: 'interview', label: 'Interview Qs'},
  {id: 'storytelling', label: '2-Minute Story'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'checklist', label: 'Production Checklist'},
  {id: 'cheat-sheet', label: 'Cheat Sheet'},
];
