export const DECISION_ROWS = [
  {problem:'Simple mutual exclusion',pick:'synchronized',why:'Structured, auto unlock'},
  {problem:'Timed/interruptible lock',pick:'ReentrantLock',why:'tryLock / lockInterruptibly'},
  {problem:'Atomic counter',pick:'AtomicLong',why:'CAS single value'},
  {problem:'Hot metrics counter',pick:'LongAdder',why:'Striped cells'},
  {problem:'Many readers / few writers',pick:'ReadWriteLock',why:'Shared read lock'},
  {problem:'Optimistic read-heavy',pick:'StampedLock',why:'tryOptimisticRead + validate'},
  {problem:'Producer/consumer',pick:'BlockingQueue',why:'Built-in coordination'},
  {problem:'Wait for N events once',pick:'CountDownLatch',why:'One-shot gate'},
  {problem:'Reusable rendezvous',pick:'CyclicBarrier',why:'Reusable barrier'},
  {problem:'Dynamic multi-phase',pick:'Phaser',why:'Register/deregister'},
  {problem:'Limit concurrent calls',pick:'Semaphore',why:'Permits / bulkhead'},
  {problem:'Async pipeline',pick:'CompletableFuture',why:'Composition + timeouts'},
  {problem:'CPU divide-and-conquer',pick:'ForkJoinPool',why:'Work stealing'},
  {problem:'Massive blocking I/O',pick:'Virtual Threads',why:'Cheap thread-per-task'},
  {problem:'Bounded child lifetimes',pick:'Structured Concurrency (preview in 25)',why:'Parent owns children'},
  {problem:'Bounded context',pick:'ScopedValue (final in 25)',why:'Immutable scope vs ThreadLocal'},
];

export const COMPARISONS = [
  {pair:'synchronized vs ReentrantLock',a:'Simple critical sections',b:'tryLock/timeout/Conditions/fairness',breaks:'Both JVM-local only'},
  {pair:'volatile vs AtomicInteger',a:'Flags/publication',b:'Atomic RMW counters',breaks:'volatile++ loses updates'},
  {pair:'AtomicLong vs LongAdder',a:'Exact identity/state',b:'Hot metrics sum()',breaks:'LongAdder get less snappy'},
  {pair:'Future vs CompletableFuture',a:'Single result handle',b:'Composable graph',breaks:'get() chains serialize'},
  {pair:'CF vs Structured Concurrency',a:'Stable composition today',b:'Preview lifetimes/cancel in 25',breaks:'Do not standardize SC yet'},
  {pair:'Platform vs Virtual Thread',a:'CPU / scarce native',b:'Wait-bound scale',breaks:'VT ≠ more CPU'},
  {pair:'ThreadLocal vs ScopedValue',a:'Legacy mutable',b:'Final bounded immutable (25)',breaks:'TL leaks on pools'},
  {pair:'Latch vs Barrier vs Phaser',a:'One-shot',b:'Fixed reusable',breaks:'Wrong one = stuck startup'},
  {pair:'HashMap sync vs CHM',a:'Coarse lock',b:'Bins/CAS',breaks:'Iteration rules differ'},
  {pair:'ArrayBQ vs LinkedBQ vs SyncQ',a:'Bounded array',b:'Optional bounded linked',c:'Zero capacity handoff',breaks:'Queue choice changes pool growth'},
];

export const CHEAT = [
  ['Visibility flag','volatile / AtomicBoolean'],
  ['Atomic counter','AtomicInteger/Long'],
  ['Hot metrics','LongAdder'],
  ['Simple mutex','synchronized'],
  ['Advanced mutex','ReentrantLock'],
  ['Many readers','ReadWriteLock'],
  ['Optimistic read','StampedLock'],
  ['Permits','Semaphore'],
  ['Wait N once','CountDownLatch'],
  ['Reusable checkpoint','CyclicBarrier'],
  ['Dynamic phases','Phaser'],
  ['Producer/consumer','BlockingQueue'],
  ['Concurrent map','ConcurrentHashMap'],
  ['Async pipeline','CompletableFuture'],
  ['CPU fork/join','ForkJoinPool'],
  ['Massive blocking I/O','Virtual Threads'],
  ['Child task ownership','Structured Concurrency (preview 25)'],
  ['Request context','ScopedValue (final 25)'],
];

export const REMEMBER = [
  ['Thread','Bank employee'],
  ['Thread pool','Team of employees'],
  ['BlockingQueue','Waiting line'],
  ['Lock','Vault key'],
  ['Semaphore','N parking slots'],
  ['CountDownLatch','Rocket countdown'],
  ['CyclicBarrier','Friends at checkpoint'],
  ['Phaser','Multi-round game'],
  ['Atomic/CAS','Try sticker, retry'],
  ['LongAdder','Many mini-counters'],
  ['CHM','Concurrent registry'],
  ['CompletableFuture','Orchestra score'],
  ['Virtual Thread','Lightweight teller per customer'],
  ['ScopedValue','Temporary badge'],
  ['Structured Concurrency','Manager owns the meeting'],
  ['AQS','Clipboard + dial + park tickets'],
];

export const THIRTY_MIN = [
  {id:'jmm',title:'JMM',facts:['HB edges','Safe publication','Reordering legal without HB'],trap:'Assuming wall-clock order',q:'Five HB sources?'},
  {id:'syncvol',title:'sync / volatile',facts:['Monitor exclusion','volatile visibility','not RMW atomic'],trap:'volatile++',q:'sync vs Lock?'},
  {id:'cas',title:'CAS / Atomic / LongAdder',facts:['CAS loop','ABA','striping'],trap:'Atomic for multi-field',q:'When LongAdder?'},
  {id:'aqs',title:'AQS / ReentrantLock',facts:['state','queue','park'],trap:'Forget unlock',q:'Fair cost?'},
  {id:'tpe',title:'ThreadPoolExecutor',facts:['core→queue→max→reject','queue choice','metrics'],trap:'Unbounded queue',q:'Why max ignored?'},
  {id:'chm',title:'ConcurrentHashMap',facts:['bins','compute*','weak iter'],trap:'containsKey+put',q:'Resize help?'},
  {id:'cf',title:'CompletableFuture',facts:['compose vs apply','custom executor','timeouts'],trap:'commonPool JDBC',q:'thenCompose?'},
  {id:'fjp',title:'ForkJoin',facts:['steal','CPU fit','commonPool'],trap:'Blocking tasks',q:'parallelStream pool?'},
  {id:'vt',title:'Virtual Threads',facts:['unmount','pinning','throttle sinks'],trap:'VT = faster CPU',q:'DB collapse why?'},
  {id:'scsv',title:'SC / ScopedValue',facts:['SC preview 505','SV final 506','bounded context'],trap:'Calling SC final in 25',q:'TL vs SV?'},
];
