import type {ApiCoverage} from './types';

export const API_COVERAGE: ApiCoverage[] = [
  {name:'Thread',pkg:'java.lang',introduced:'1.0',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Runnable',pkg:'java.lang',introduced:'1.0',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Callable',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Future',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'FutureTask',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'CompletableFuture',pkg:'java.util.concurrent',introduced:'8',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ExecutorService',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ThreadPoolExecutor',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ScheduledThreadPoolExecutor',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:false,diagram:true,production:true,interview:true},
  {name:'ForkJoinPool',pkg:'java.util.concurrent',introduced:'7',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'RecursiveTask',pkg:'java.util.concurrent',introduced:'7',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'CountedCompleter',pkg:'java.util.concurrent',introduced:'8',java25:'Stable',covered:true,code:false,diagram:false,production:false,interview:true},
  {name:'synchronized',pkg:'language',introduced:'1.0',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'volatile',pkg:'language',introduced:'1.0',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ReentrantLock',pkg:'java.util.concurrent.locks',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ReentrantReadWriteLock',pkg:'java.util.concurrent.locks',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'StampedLock',pkg:'java.util.concurrent.locks',introduced:'8',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Condition',pkg:'java.util.concurrent.locks',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'LockSupport',pkg:'java.util.concurrent.locks',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'AtomicInteger',pkg:'java.util.concurrent.atomic',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'LongAdder',pkg:'java.util.concurrent.atomic',introduced:'8',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'AtomicStampedReference',pkg:'java.util.concurrent.atomic',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'VarHandle',pkg:'java.lang.invoke',introduced:'9',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ConcurrentHashMap',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'CopyOnWriteArrayList',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ConcurrentLinkedQueue',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ArrayBlockingQueue',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'LinkedBlockingQueue',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'SynchronousQueue',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'DelayQueue',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:false,diagram:true,production:true,interview:true},
  {name:'LinkedTransferQueue',pkg:'java.util.concurrent',introduced:'7',java25:'Stable',covered:true,code:false,diagram:true,production:true,interview:true},
  {name:'Semaphore',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'CountDownLatch',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'CyclicBarrier',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Phaser',pkg:'java.util.concurrent',introduced:'7',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Exchanger',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Flow / SubmissionPublisher',pkg:'java.util.concurrent',introduced:'9',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ThreadLocal',pkg:'java.lang',introduced:'1.2',java25:'Stable',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'Virtual Threads',pkg:'java.lang',introduced:'21',java25:'Stable (final since 21)',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ScopedValue',pkg:'java.lang',introduced:'20 preview / 25 final',java25:'FINAL (JEP 506)',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'StructuredTaskScope',pkg:'java.util.concurrent',introduced:'21 preview lineage',java25:'PREVIEW (JEP 505 5th)',covered:true,code:true,diagram:true,production:true,interview:true},
  {name:'ConcurrentSkipListMap',pkg:'java.util.concurrent',introduced:'6',java25:'Stable',covered:true,code:false,diagram:false,production:true,interview:true},
  {name:'PriorityBlockingQueue',pkg:'java.util.concurrent',introduced:'5',java25:'Stable',covered:true,code:false,diagram:true,production:true,interview:true},
];
