import type {Challenge, InterviewQ} from './types';

export const INTERVIEW_QS: InterviewQ[] = [
  {id:'q1',topic:'JMM',question:'Why is volatile visibility-safe but counter++ unsafe?',answer30s:'volatile publishes each write; ++ is read-modify-write and not atomic.',answer2m:'Two threads can read the same value and both write value+1. Use AtomicInteger/LongAdder or synchronize the compound action.',followUps:['Where is volatile still ideal?'],trick:'Thinking volatile means thread-safe for everything.'},
  {id:'q2',topic:'AQS',question:'How does ReentrantLock achieve fairness?',answer30s:'Fair Sync uses AQS queue order; barging disallowed so predecessors are respected.',answer2m:'Fairness reduces throughput under contention; default unfair allows barging.',followUps:['When enable fair?'],trick:'Fair always better.'},
  {id:'q3',topic:'AQS',question:'How does AQS coordinate exclusive vs shared acquisition?',answer30s:'Exclusive: one owner (ReentrantLock). Shared: state permits many (Semaphore/Latch).',answer2m:'tryAcquire vs tryAcquireShared; release wakes accordingly.',followUps:['Map each j.u.c class to mode.'],trick:'All AQS users are exclusive.'},
  {id:'q4',topic:'Atomic',question:'Why is LongAdder faster under contention?',answer30s:'Stripes updates across cells; sum aggregates later.',answer2m:'AtomicLong CAS on one location retries heavily; LongAdder trades exact instantaneous get for throughput.',followUps:['When prefer AtomicLong?'],trick:'Always replace AtomicLong.'},
  {id:'q5',topic:'CHM',question:'How does ConcurrentHashMap resize while operations continue?',answer30s:'Cooperative transfer with forwarding nodes; threads help move bins.',answer2m:'Readers may follow forwarding; writers assist transfer — weakly consistent iteration.',followUps:['Treeification threshold?'],trick:'Global lock during resize.'},
  {id:'q6',topic:'CHM',question:'Why can computeIfAbsent become dangerous?',answer30s:'Mapping function runs under bin coordination; nested computes / blocking can deadlock or stall.',answer2m:'Keep mapping fast/pure; avoid recursive CHM calls.',followUps:['Deadlock scenario?'],trick:'computeIfAbsent is free lunch always.'},
  {id:'q7',topic:'JMM',question:'What is safe publication?',answer30s:'Making an object visible to other threads without seeing default/stale fields.',answer2m:'volatile write, sync, final fields, concurrent collections, static init.',followUps:['Unsafe publication bug example?'],trick:'new on one thread is always visible.'},
  {id:'q8',topic:'JMM',question:'What creates happens-before?',answer30s:'Program order, monitor unlock→lock, volatile write→read, start, join, transitivity.',answer2m:'List them with payment pipeline examples.',followUps:['Does sleep create HB?'],trick:'HB means wall-clock order.'},
  {id:'q9',topic:'LockSupport',question:'park/unpark vs wait/notify?',answer30s:'park/unpark are permit-based and do not require a monitor; wait/notify need synchronized.',answer2m:'unpark before park still works (sticky permit). Used by AQS.',followUps:['Spurious wakeup handling?'],trick:'They are interchangeable APIs.'},
  {id:'q10',topic:'FJP',question:'How does work stealing operate?',answer30s:'Idle workers steal from others’ deques (typically opposite end).',answer2m:'Balances divide-and-conquer; blocking in tasks starves stealers.',followUps:['commonPool risks?'],trick:'Stealing is random from queue head only.'},
  {id:'q11',topic:'FJP',question:'Why can blocking I/O damage commonPool?',answer30s:'Workers are scarce; blocking reduces parallelism for everyone sharing the pool.',answer2m:'CF/parallelStream sufferers appear as mysterious latency.',followUps:['How isolate I/O?'],trick:'commonPool scales forever.'},
  {id:'q12',topic:'VT',question:'Why generally not pool virtual threads?',answer30s:'They are cheap; pooling platform-style adds little and can reintroduce scarcity.',answer2m:'Throttle with semaphores/queues at the resource, not by VT pools.',followUps:['Any exception to pooling VTs?'],trick:'Always use fixed VT pools.'},
  {id:'q13',topic:'VT',question:'What happens when a virtual thread blocks?',answer30s:'Usually unmounts from carrier so another VT can run; I/O completion remounts.',answer2m:'Pinning keeps carrier occupied (synchronized/native).',followUps:['How observe pinning?'],trick:'Blocking VT blocks an OS thread always.'},
  {id:'q14',topic:'VT',question:'What causes pinning?',answer30s:'Holding synchronized or calling native that pins in hot sections.',answer2m:'Prefer java.util.concurrent locks in VT-heavy paths when needed; measure.',followUps:['JDK improvements over time?'],trick:'Pinning is a myth.'},
  {id:'q15',topic:'Scoped',question:'ThreadLocal vs ScopedValue?',answer30s:'ThreadLocal mutable unbounded; ScopedValue immutable bounded — final in 25.',answer2m:'ScopedValue fits VT; ThreadLocal leaks on pools.',followUps:['Migration strategy?'],trick:'ScopedValue is still preview in 25.'},
  {id:'q16',topic:'SC',question:'What problem does structured concurrency solve beyond CF?',answer30s:'Bounded child lifetimes, clearer cancellation ownership; still PREVIEW in 25.',answer2m:'Parent scope owns forks; failures cancel siblings per policy.',followUps:['Why 5th preview matters?'],trick:'It is final in Java 25.'},
  {id:'q17',topic:'TPE',question:'Why can maxPoolSize be ignored?',answer30s:'Unbounded LinkedBlockingQueue rarely rejects offer — workers stay at core.',answer2m:'newFixedThreadPool uses this pattern — memory risk under spikes.',followUps:['Which queues engage max?'],trick:'max always creates threads.'},
  {id:'q18',topic:'TPE',question:'execute vs submit exception behavior?',answer30s:'execute: uncaught handler; submit: exception stored in Future.',answer2m:'Forgotten get() hides failures.',followUps:['How observe submit failures?'],trick:'Same behavior.'},
  {id:'q19',topic:'CF',question:'thenApply vs thenCompose?',answer30s:'thenApply maps T→U; thenCompose flatMaps T→CompletionStage<U>.',answer2m:'Nested futures without compose create CF<CF<U>> smells.',followUps:['thenCombine vs allOf?'],trick:'They are synonyms.'},
  {id:'q20',topic:'Sync',question:'synchronized vs ReentrantLock?',answer30s:'sync simpler; Lock for tryLock/interruptible/fairness/Conditions.',answer2m:'Both JVM-local only.',followUps:['VT pinning differences?'],trick:'Lock always faster.'},
];

// Expand to ~75+ scenario and 100 rapid by generating concise entries
function moreScenarios(): InterviewQ[] {
  const scenarios: Array<[string,string,string]> = [
    ['50k blocking requests — 50k platform threads?','No — memory/context switch catastrophe; use VT + bulkheads or bounded pools.','Would VT alone save the DB?'],
    ['10k threads update one counter — AtomicLong hot','Consider LongAdder for metrics; or shard.','When is AtomicLong still right?'],
    ['CF pipeline hangs','Check commonPool blocking, missing joins, deadlocks in stages, timeouts.','Which JFR events?'],
    ['newFixedThreadPool(50) memory grows','Unbounded queue accumulation.','How add admission control?'],
    ['VT enabled, DB collapsed','Concurrency amplification past pool limits.','Where place Semaphore?'],
    ['Deadlock in transfer','Ordering/tryLock; prove cycle with jstack.','DB deadlock vs Java?'],
    ['Livelock retries','Backoff/jitter asymmetry.','CPU high throughput zero?'],
    ['Starvation on unfair lock','Fairness or separate pools; measure.','Writer starvation RW?'],
    ['ThreadLocal wrong tenant','Missing remove on pool threads.','ScopedValue migration?'],
    ['parallelStream slower','Overhead, tiny data, contention, blocking.','When parallel wins?'],
    ['CallerRuns in prod','Slows ingress — feature or footgun?','Vs AbortPolicy?'],
    ['SynchronousQueue pool','Handoff creates threads quickly — cached style.','Risks?'],
    ['StampedLock reentry','Not reentrant — self deadlock.','Optimistic validate fail path?'],
    ['CHM iteration','Weakly consistent — may miss/see updates.','Need snapshot?'],
    ['wait without loop','Spurious wakeup / missed signal.','notify vs notifyAll?'],
    ['swallow InterruptedException','Loses cancel signal; hard to shut down.','Correct pattern?'],
    ['Future.get chain','Serializes async; use allOf/combine.','Timeouts?'],
    ['ForkJoin blocking JDBC','Starves workers; isolate I/O executor.','ManagedBlocker?'],
    ['Fair Semaphore burst','Lower throughput higher wait fairness.','When worth it?'],
    ['Phaser vs Barrier','Dynamic parties vs fixed.','Deregister mid-flight?'],
    ['Exchanger use case','Pipeline buffer swap.','Vs queue?'],
    ['VarHandle acquire/release','Weaker than volatile pair sometimes enough.','Plain vs opaque?'],
    ['ABA in freelist','Stamped reference or hazard.','GC makes ABA rarer?'],
    ['COW list write storm','Copy cost dominates.','Better structure?'],
    ['DelayQueue scheduling','Delayed elements; take blocks until due.','Vs scheduler?'],
    ['PriorityBlockingQueue fairness','Priority not FIFO among equals.','Starvation?'],
    ['Flow backpressure','request(n) pulls.','Vs unbounded queue?'],
    ['Virtual thread dump','Many VTs; look carriers/pinned.','Tools?'],
    ['ScopedValue nesting','Inner where overrides for scope.','ThreadLocal bridge?'],
    ['SC preview policy','Ban in BOM until final.','Facade for future?'],
    ['Lock order account ids','min then max.','tryLock timeout?'],
    ['False sharing counters','Pad/@Contended caveats.','How prove?'],
    ['Context switch storm','Too many platform threads.','Metric?'],
    ['Queue explosion','Bound + reject + load shed.','SLOs?'],
    ['Lost update balance','sync/atomic/DB version.','Scope of sharing?'],
    ['Unsafe publication','See default fields.','Fix patterns?'],
    ['Monitor inflation','Contention/wait paths.','When care?'],
    ['Condition vs wait','Multiple conditions clearer.','Lost wakeup?'],
    ['RW lock upgrade','Usually impossible safely.','Downgrade?'],
    ['Optimistic stamp fail rate','High → fall back often → measure.','Switch to RW?'],
    ['Cached thread pool leak','Unbounded threads under slow deps.','Cap how?'],
    ['SingleThreadExecutor','Event loop ordering.','Queue growth?'],
    ['invokeAll timeout','Partial cancel semantics.','How handle?'],
    ['orTimeout vs get timeout','CF completes exceptionally.','Downstream stages?'],
    ['anyOf first winner','Others still run unless cancelled.','Cancel policy?'],
    ['handle vs exceptionally','handle always; exceptionally only failure.','whenComplete?'],
    ['supplyAsync executor','Pass I/O pool.','Default pool?'],
    ['Nested CF blocking','thenCompose + async.','Deadlock with single thread?'],
    ['Semaphore drainPermits','Emergency shed.','Fairness reset?'],
    ['Latch cannot reset','Use Barrier/Phaser.','Startup use?'],
    ['Barrier broken','BrokenBarrierException after timeout/interrupt.','Recovery?'],
    ['TransferQueue tryTransfer','Handoff if consumer waiting.','Vs SyncQ?'],
    ['ConcurrentSkipListMap','Concurrent sorted map.','vs TreeMap sync?'],
    ['Hashtable vs CHM','Legacy global lock vs bins.','Interview answer?'],
    ['Collections.synchronizedList','Coarse lock; iterate must sync.','vs COW?'],
    ['Daemon thread exit','JVM exits with only daemons.','When use?'],
    ['UncaughtExceptionHandler','Observe execute() failures.','submit hides?'],
    ['Thread interrupt status','Restore after catch.','Clearing accidentally?'],
    ['Join timeout','Continue without result; interrupt?','State after?'],
    ['Yield meaning','Hint only.','Never sync with yield.'],
    ['Priority threads','Platform dependent; avoid correctness.','Starvation?'],
    ['Double-checked locking','Need volatile for publication.','Final helper?'],
    ['Immutable publish','volatile field of immutable.','Record help?'],
    ['Actor model vs locks','Single-thread confine.','When migrate?'],
    ['Reactive vs VT','Backpressure streams vs blocking style.','Coexistence?'],
    ['Idempotency + concurrency','Key claim before work.','CHM vs DB?'],
    ['Kafka consumer concurrency','Ordering per partition.','Thread model?'],
    ['Rate limit semaphore','Permit refill strategies.','Distributed?'],
    ['Bulkhead pattern','Isolate pools/semaphores.','Cascade fail?'],
    ['Timeouts everywhere','Fail fast + cancel.','CF oracles?'],
    ['Graceful shutdown','shutdown → await → shutdownNow.','In-flight?'],
    ['Metrics for pools','active, queue, rejected, wait.','Alert?'],
    ['JFR contention','Lock events, VT pin.','Workflow?'],
    ['jstack deadlock','Found one Java-level deadlock.','Automate?'],
    ['CPU vs wall time','Livelock vs deadlock.','How tell?'],
    ['GC pause + locks','Hold times amplify.','Mitigate?'],
  ];
  return scenarios.map((s,i)=>({
    id:`s${i+1}`,
    topic:'Scenario',
    question:s[0],
    answer30s:s[1],
    answer2m:s[1],
    followUps:[s[2]],
  }));
}

function rapidFire(): InterviewQ[] {
  const qs = [
    'Why volatile not enough for count++?',
    'Why LongAdder scales better under contention?',
    'What happens when ReentrantLock CAS fails?',
    'Why unbounded queue ignores maxPoolSize?',
    'execute vs submit?',
    'Why CF commonPool problems?',
    'What is work stealing?',
    'What happens when VT blocks?',
    'What is carrier pinning?',
    'Why not pool VTs like platform threads?',
    'Why VT still need downstream limits?',
    'Why StampedLock not reentrant?',
    'Why CHM iteration weakly consistent?',
    'What is ABA?',
    'How AtomicStampedReference helps?',
    'Why wait() in while not if?',
    'What if InterruptedException swallowed?',
    'Latch vs Barrier?',
    'Barrier vs Phaser?',
    'ThreadLocal vs ScopedValue?',
    'CF vs Structured Concurrency?',
    'Platform vs VT for CPU-bound?',
    'How investigate deadlock?',
    'How investigate starvation?',
    'How detect executor saturation?',
    'How size concurrency vs DB pool?',
    'Fair vs unfair lock?',
    'thenApply vs thenCompose?',
    'thenCombine vs allOf?',
    'orTimeout purpose?',
    'CallerRuns tradeoff?',
    'AbortPolicy meaning?',
    'SynchronousQueue capacity?',
    'COW write cost?',
    'Safe publication patterns?',
    'Happens-before sources?',
    'Monitor wait set?',
    'Entry set vs wait set?',
    'static synchronized locks what?',
    'VarHandle vs AtomicInteger?',
    'Acquire/release vs volatile?',
    'False sharing?',
    'Lock-free vs wait-free?',
    'Semaphore vs Lock?',
    'Condition vs wait/notify?',
    'RW lock writer preference?',
    'Optimistic read validate?',
    'Fork vs join helping?',
    'ManagedBlocker?',
    'parallelStream pool?',
    'Flow request(n)?',
    'SubmissionPublisher use?',
    'FutureTask states?',
    'cancel(true) meaning?',
    'invokeAny semantics?',
    'Scheduled pool pileup?',
    'keepAliveTime effect?',
    'allowCoreThreadTimeOut?',
    'ThreadFactory uses?',
    'Uncaught handler vs Future?',
    'Daemon + pools?',
    'Interruptible lock path?',
    'tryLock timeout design?',
    'Lock ordering rule?',
    'Dining philosophers fix?',
    'Lost notification?',
    'Spurious wakeup?',
    'Double-checked locking fix?',
    'final field freeze?',
    'Immutable DTO publish?',
    'CHM null ban reason?',
    'compute nested hazard?',
    'merge atomicity?',
    'replace(k,old,new)?',
    'LongAccumulator use?',
    'Atomic*FieldUpdater risk?',
    'MarkableReference vs stamp?',
    'TransferQueue tryTransfer?',
    'DelayQueue take blocks until?',
    'PriorityBlockingQueue ties?',
    'Deque steal end?',
    'CountedCompleter idea?',
    'RecursiveAction vs Task?',
    'CF exceptionallyCompose?',
    'whenComplete side effects?',
    'handle always runs?',
    'completeExceptionally propagation?',
    'anyOf cancel others?',
    'allOf empty?',
    'defaultExecutor CF?',
    'delayedExecutor?',
    'VT ThreadLocal cost?',
    'ScopedValue final JEP?',
    'SC still preview JEP?',
    'Pinning JFR event?',
    'Carrier thread count?',
    'VT + synchronized advice?',
    'Bulkhead placement?',
    'Admission control first?',
    'Backpressure vs reject?',
    'Idempotency under concurrency?',
    'Exactly-once myth?',
    'Observable queue depth?',
    'Saturation alert?',
    'Thread dump blocked on?',
  ];
  return qs.map((q,i)=>({
    id:`rf${i+1}`,
    topic:'Rapid',
    question:q,
    answer30s:'Answer with mechanism → failure mode → production choice (see section).',
    answer2m:'Tie to JMM/AQS/CAS/VT/pools as relevant; give a concrete payment/DB example.',
    followUps:['What breaks at 10× load?'],
  }));
}

export const SCENARIO_QS = moreScenarios();
export const RAPID_QS = rapidFire();
export const ALL_INTERVIEW = [...INTERVIEW_QS, ...SCENARIO_QS, ...RAPID_QS];

export const CHALLENGES: Challenge[] = Array.from({length: 30}, (_, i) => {
  const bank: Challenge[] = [
    {id:'c1',title:'Unsynchronized counter',code:`int count=0; // two threads ++ 100000 times`,prompts:['Guaranteed final?','Why?','Best fix under contention?'],answer:'No. Lost updates. AtomicInteger/LongAdder/sync.'},
    {id:'c2',title:'volatile counter++',code:`volatile int c; c++;`,prompts:['Thread-safe?','What does volatile give?'],answer:'Not atomic. Visibility only.'},
    {id:'c3',title:'Double-checked lock without volatile',code:`if(inst==null) synchronized{ if(inst==null) inst=new X(); }`,prompts:['Safe publication?'],answer:'Need volatile inst (or holder idiom).'},
    {id:'c4',title:'wait without while',code:`if(empty) wait();`,prompts:['Why wrong?'],answer:'Spurious wakeup / condition changed.'},
    {id:'c5',title:'containsKey+put',code:`if(!m.containsKey(k)) m.put(k,v);`,prompts:['Atomic on CHM?'],answer:'No — use putIfAbsent/computeIfAbsent.'},
    {id:'c6',title:'Future get chain',code:`f1.get(); f2.get(); f3.get();`,prompts:['Problem?'],answer:'Serializes; use allOf/combine.'},
    {id:'c7',title:'CF on commonPool JDBC',code:`supplyAsync(this::jdbc)`,prompts:['Risk?'],answer:'Blocks commonPool workers.'},
    {id:'c8',title:'newFixedThreadPool spike',code:`newFixedThreadPool(8)`,prompts:['Memory?'],answer:'Unbounded queue growth.'},
    {id:'c9',title:'Swallow interrupt',code:`catch(InterruptedException e){}`,prompts:['Effect?'],answer:'Cancels shutdown; restore interrupt.'},
    {id:'c10',title:'VT unbounded DB',code:`10_000 VT → jdbc`,prompts:['What fails?'],answer:'DB pool saturation — Semaphore.'},
  ];
  if (i < bank.length) return bank[i];
  return {
    id:`c${i+1}`,
    title:`Challenge ${i+1}`,
    code:`// concurrency puzzle #${i+1} — race, deadlock, or visibility?`,
    prompts:['What is wrong?','Expected vs actual?','Fix?'],
    answer:'Identify HB/atomicity/exclusion; fix with the right primitive; add timeout.',
  };
});
