import type {TocItem} from './types';

export const CONCURRENCY_TOC: TocItem[] = [
  {id: 'overview', label: 'Overview'},
  {id: 'timeline', label: 'Version Timeline'},
  {id: 'api-map', label: 'API Master Map'},
  {id: 'thread', label: 'Thread Fundamentals'},
  {id: 'runnable-callable', label: 'Runnable vs Callable'},
  {id: 'jmm', label: 'Java Memory Model'},
  {id: 'synchronized', label: 'synchronized'},
  {id: 'wait-notify', label: 'wait / notify'},
  {id: 'volatile', label: 'volatile'},
  {id: 'atomic', label: 'Atomic / CAS'},
  {id: 'aba', label: 'ABA Problem'},
  {id: 'varhandle', label: 'VarHandle'},
  {id: 'reentrant-lock', label: 'ReentrantLock'},
  {id: 'aqs', label: 'AQS Deep Dive'},
  {id: 'condition', label: 'Condition'},
  {id: 'rwlock', label: 'ReadWriteLock'},
  {id: 'stamped', label: 'StampedLock'},
  {id: 'locksupport', label: 'LockSupport'},
  {id: 'semaphore', label: 'Semaphore'},
  {id: 'latch', label: 'CountDownLatch'},
  {id: 'barrier', label: 'CyclicBarrier'},
  {id: 'phaser', label: 'Phaser'},
  {id: 'exchanger', label: 'Exchanger'},
  {id: 'executor', label: 'Executor Framework'},
  {id: 'tpe', label: 'ThreadPoolExecutor'},
  {id: 'queues', label: 'Pool Queues & Rejection'},
  {id: 'future', label: 'Future / FutureTask'},
  {id: 'cf', label: 'CompletableFuture'},
  {id: 'fjp', label: 'ForkJoinPool'},
  {id: 'chm', label: 'ConcurrentHashMap'},
  {id: 'cow', label: 'CopyOnWriteArrayList'},
  {id: 'bq', label: 'BlockingQueue Family'},
  {id: 'threadlocal', label: 'ThreadLocal'},
  {id: 'vt', label: 'Virtual Threads'},
  {id: 'structured', label: 'Structured Concurrency'},
  {id: 'scoped', label: 'Scoped Values'},
  {id: 'flow', label: 'Flow API'},
  {id: 'bugs', label: 'Concurrency Bug Lab'},
  {id: 'payment', label: 'Payment System'},
  {id: 'ecommerce', label: 'E-commerce Aggregator'},
  {id: 'decision', label: 'Decision Tree'},
  {id: 'comparison', label: 'Master Comparisons'},
  {id: 'coverage', label: 'API Coverage Matrix'},
  {id: 'challenges', label: 'Guess the Output'},
  {id: 'interview', label: 'Interview Mode'},
  {id: 'rapid-fire', label: 'Rapid-Fire 100'},
  {id: 'thirty-min', label: '30-Minute Revision'},
  {id: 'cheat', label: 'Cheat Sheet'},
  {id: 'architecture', label: 'Internal Architecture'},
];
