import type {InterviewQ} from './types';

export const SENIOR: InterviewQ[] = [
  {id:'s1',topic:'Basics',question:'What is multi-tenancy?',answer30s:'One application serving many isolated customers (tenants) with shared runtime but separated data.',answer2m:'Walmart and Amazon use the same Order SaaS deployment. Code is shared; data plane is isolated via tenant_id, keys, and policies. SaaS is the business model; multi-tenancy is the isolation technique.',followUps:['Single-tenant SaaS?'],trick:'Calling multiple single-tenant deploys multi-tenant.'},
  {id:'s2',topic:'Basics',question:'Tenant vs customer vs user?',answer30s:'Tenant is the company boundary; users belong to a tenant; customers may be the tenant’s end buyers.',answer2m:'In our lab, tenant=Walmart, user=walmart admin, customer=a Walmart shopper record — still scoped by tenant_id.',followUps:['Can one user belong to two tenants?']},
  {id:'s3',topic:'DB',question:'Shared schema vs DB-per-tenant?',answer30s:'Shared is cheapest with tenant_id; DB-per-tenant is strongest isolation and highest ops cost.',answer2m:'Recommend shared + RLS for startups; dedicated for banking SKUs; hybrid metadata to choose per tenant.',followUps:['Schema-per-tenant?'],trick:'DB-per-tenant for ten free users.'},
  {id:'s4',topic:'DB',question:'Why index tenant_id first?',answer30s:'Almost every query filters by tenant; leading tenant_id makes indexes selective and correct.',answer2m:'idx(tenant_id, status) serves list-by-status without scanning other tenants. Unique business keys often become (tenant_id, sku).',followUps:['Partial indexes?']},
  {id:'s5',topic:'Security',question:'How do you identify the tenant?',answer30s:'JWT claim preferred; header/subdomain as hints that must match.',answer2m:'CompositeTenantResolver: JWT wins. Mismatch → 403 tenant_mismatch. Prevents X-Tenant-ID spoofing.',followUps:['API keys?']},
  {id:'s6',topic:'Security',question:'JWT tenant ≠ header tenant?',answer30s:'Reject 403. Never let the header override the token.',answer2m:'The token is cryptographic proof of membership. A client-controlled header is not. Lab test: jwtTenantMismatchReturns403.',followUps:['Strip header at gateway?'],trick:'Prefer header for flexibility.'},
  {id:'s7',topic:'Security',question:'How do you prevent BOLA across tenants?',answer30s:'Load resources by id AND tenant_id from context; return 404 if missing.',answer2m:'Never findById alone. Ownership checks in service. Integration test: Amazon token + Walmart order id.',followUps:['403 vs 404?']},
  {id:'s8',topic:'Context',question:'ThreadLocal risks?',answer30s:'Uncleared values leak across pooled threads to the next request.',answer2m:'Always finally clear. Propagate explicitly to @Async and Kafka. WebFlux should use Reactor Context.',followUps:['Virtual threads?'],trick:'Assuming @Async inherits TenantContext.'},
  {id:'s9',topic:'RLS',question:'How does Postgres RLS help?',answer30s:'Policies filter rows by session tenant even if SQL forgets WHERE tenant_id.',answer2m:'SET LOCAL app.current_tenant; ENABLE/FORCE RLS. Defense in depth under app bugs. Reset GUC on pool return.',followUps:['BYPASSRLS roles?']},
  {id:'s10',topic:'Cache',question:'Design tenant-aware cache keys',answer30s:'Prefix every key with tenant id.',answer2m:'tenant:{id}:config, tenant:{id}:order:{orderId}. Evict on write; TTL backstop; never key "config".',followUps:['Stampede?'],trick:'Shared "feature-flags" key.'},
  {id:'s11',topic:'Kafka',question:'Why tenantId on every event?',answer30s:'Consumers must bind TenantContext before touching storage.',answer2m:'Envelope + headers. Missing tenant → reject/DLQ. Outbox rows store tenant_id for the same reason.',followUps:['Topic-per-tenant?']},
  {id:'s12',topic:'Kafka',question:'Partition by tenantId or orderId?',answer30s:'orderId for scale; tenantId if you need tenant-wide total order.',answer2m:'tenantId keys create hot partitions for whales. Prefer aggregate id; document ordering guarantees.',followUps:['Hot tenant mitigation?']},
  {id:'s13',topic:'Outbox',question:'Why outbox in multi-tenant SaaS?',answer30s:'Atomic business write + event intent; avoid dual-write loss.',answer2m:'Order + outbox in one SQL TX include tenant_id. Publisher/CDC emits to Kafka. Consumers idempotent.',followUps:['Debezium vs poller?'],trick:'Claiming exactly-once across DB+Kafka without proof.'},
  {id:'s14',topic:'DLQ',question:'Tenant-aware DLQ replay?',answer30s:'Persist tenantId; restore TenantContext on replay; idempotent handlers.',answer2m:'DLQ stores eventId, topic, offset, error, retryCount. Replay is a produce with same key, not a direct service call that skips context.',followUps:['Idempotency store key?']},
  {id:'s15',topic:'Onboarding',question:'How do you onboard a tenant?',answer30s:'Create PROVISIONING → provision storage → migrate → admin → ACTIVE.',answer2m:'Saga with PROVISIONING_FAILED and retry. Do not XA across CREATE DATABASE.',followUps:['Idempotent slug create?']},
  {id:'s16',topic:'Lifecycle',question:'What happens on suspend?',answer30s:'API returns 403; data retained; producers should stop.',answer2m:'Filter checks ACTIVE. Cache may TTL out. Billing can resume to ACTIVE. Delete is a later orchestrated purge.',followUps:['In-flight Kafka?']},
  {id:'s17',topic:'Rate limit',question:'Per-tenant rate limiting?',answer30s:'Redis key rate-limit:{tenantId} with plan ceilings.',answer2m:'Combine edge global limits, per-tenant, per-user, per-route. Return 429 Retry-After. Primary noisy-neighbor control.',followUps:['Fail open or closed if Redis down?']},
  {id:'s18',topic:'Obs',question:'What belongs in every log line?',answer30s:'tenantId, userId, traceId, requestId, service, operation.',answer2m:'Fill via MDC in TenantFilter; clear in finally. Propagate tenant on OTel baggage across HTTP and Kafka.',followUps:['Cardinality on metrics?']},
  {id:'s19',topic:'Scale',question:'Noisy neighbor?',answer30s:'One tenant’s load degrades shared resources for others.',answer2m:'Quotas, fair scheduling, statement timeouts, dedicated infra for whales, careful Kafka keys.',followUps:['When dedicated deployment?']},
  {id:'s20',topic:'Scale',question:'Connection pool math DB-per-tenant?',answer30s:'hotTenants × poolSize must stay under Postgres max_connections.',answer2m:'Use tiny pools, lazy open, idle evict, or multiplex through fewer DBs/shards. 500×10 is a pageable incident.',followUps:['PgBouncer?']},
];

export const ARCHITECT: InterviewQ[] = [
  {id:'a1',topic:'Hybrid',question:'Why hybrid multi-tenancy?',answer30s:'Cost for the long tail; dedicated isolation for enterprise/compliance.',answer2m:'Tenant row stores database_strategy. Router chooses shared discriminator vs dedicated DataSource. Upgrade path when a customer outgrows shared.',followUps:['Migration cutover?']},
  {id:'a2',topic:'Hibernate',question:'Hibernate multi-tenant modes?',answer30s:'DISCRIMINATOR, SCHEMA, DATABASE via resolver + connection provider.',answer2m:'Lab emphasizes explicit tenant predicates + RLS even in discriminator mode for clarity and defense in depth.',followUps:['search_path pitfalls?']},
  {id:'a3',topic:'Region',question:'Multi-region tenancy + GDPR?',answer30s:'Pin tenant.region and process/store in-region.',answer2m:'Gateway routes by residency. No casual cross-region PII replication. In-region DR first; failover is a product/legal decision.',followUps:['Global Redis?'],trick:'Active-active everywhere for personal data.'},
  {id:'a4',topic:'Shard',question:'Scaling 10 → 100k tenants?',answer30s:'Indexes → partition → replicas → shard by tenant or dedicate whales.',answer2m:'Avoid day-one sharding. Wave migrations. Hybrid reduces pressure by siloing top N.',followUps:['Citus/Vitess?']},
  {id:'a5',topic:'K8s',question:'Per-tenant or shared autoscaling?',answer30s:'Shared HPA by default; dedicated Deployments for enterprise/noisy whales.',answer2m:'Scale APIs on CPU/RPS; consumers on Kafka lag (KEDA). Do not create 100k Deployments.',followUps:['Multi-tenant vs multi-instance?']},
  {id:'a6',topic:'Sagas',question:'Distributed transactions across tenant DB + Kafka + payments?',answer30s:'No 2PC. Outbox, idempotency, retry, DLQ, saga.',answer2m:'Business TX writes outbox; publisher emits; payment saga compensates. tenant_id on every step.',followUps:['Orchestration vs choreography?']},
  {id:'a7',topic:'Security',question:'Threat: incorrect database routing?',answer30s:'Wrong DataSource → full tenant breach.',answer2m:'Resolver tests, sticky connection reset, integration tests that assert connection metadata/search_path, least privilege DB users.',followUps:['Canary tenants?']},
  {id:'a8',topic:'Files',question:'S3 isolation design?',answer30s:'Keys under tenant prefix; IAM conditions; short signed URLs after authz.',answer2m:'Enterprise: bucket + KMS CMK per tenant. Never list without prefix. Encrypt at rest.',followUps:['Cross-account buckets?']},
  {id:'a9',topic:'Migrate',question:'Flyway for thousands of tenant DBs?',answer30s:'Orchestrate versioned scripts with concurrency caps and canaries.',answer2m:'Expand/contract. Track per-tenant version. Pause on error rate. Do not block the fleet on one bad tenant without policy.',followUps:['Expand/contract example?']},
  {id:'a10',topic:'Cost',question:'When not to optimize for shared cost?',answer30s:'When law or contract demands silo isolation.',answer2m:'Banking/healthcare/residency. Sell dedicated as a SKU. Shared that fails an audit is more expensive.',followUps:['TCO slide?']},
  {id:'a11',topic:'Testing',question:'What isolation tests are mandatory?',answer30s:'Cross-tenant CRUD deny; JWT mismatch; suspended; missing tenant; cache/Kafka without tenant.',answer2m:'Testcontainers Postgres for RLS when claiming RLS. HTTP status assertions. CI gate.',followUps:['Property-based IDOR tests?']},
  {id:'a12',topic:'Perf',question:'How do you load-test multi-tenant systems?',answer30s:'Skewed tenants (Pareto), not uniform load.',answer2m:'Scenarios at 100/1k/10k tenants mentally; measure pools, lag, p99 per tier, rate-limit efficacy.',followUps:['Hot key in Redis/Kafka?']},
];

export const RAPID: InterviewQ[] = [
  {id:'r1',topic:'Rapid',question:'Default DB strategy?',answer30s:'Shared schema + tenant_id + RLS.',answer2m:'Hybrid dedicated for enterprise.',followUps:['Why?']},
  {id:'r2',topic:'Rapid',question:'HTTP status for JWT≠header?',answer30s:'403.',answer2m:'tenant_mismatch.',followUps:['Cross-tenant order id?']},
  {id:'r3',topic:'Rapid',question:'Cross-tenant GET order?',answer30s:'404 (preferred) or 403.',answer2m:'findByIdAndTenantId empty.',followUps:['Why 404?']},
  {id:'r4',topic:'Rapid',question:'Cache key for config?',answer30s:'tenant:{id}:config',answer2m:'Never "config".',followUps:['Evict when?']},
  {id:'r5',topic:'Rapid',question:'Kafka partition recommendation?',answer30s:'Key by orderId unless tenant-wide order required.',answer2m:'Envelope still has tenantId.',followUps:['Hot tenant?']},
  {id:'r6',topic:'Rapid',question:'Clear TenantContext where?',answer30s:'finally in filter/listener.',answer2m:'Also clear MDC.',followUps:['Batch listener?']},
  {id:'r7',topic:'Rapid',question:'RLS session variable?',answer30s:"app.current_tenant",answer2m:'SET LOCAL per TX.',followUps:['FORCE RLS?']},
  {id:'r8',topic:'Rapid',question:'Provisioning failure status?',answer30s:'PROVISIONING_FAILED',answer2m:'Retry/compensate.',followUps:['ACTIVE when?']},
  {id:'r9',topic:'Rapid',question:'Rate limit key?',answer30s:'rate-limit:{tenantId}',answer2m:'Plan drives ceiling.',followUps:['Per-user?']},
  {id:'r10',topic:'Rapid',question:'S3 key shape?',answer30s:'{tenant}/orders/{id}/file',answer2m:'Authz then sign.',followUps:['IAM?']},
  {id:'r11',topic:'Rapid',question:'Interview ladder?',answer30s:'IDENTIFY→VALIDATE→CONTEXT→ISOLATE→EXECUTE→OBSERVE',answer2m:'Memorize for 2-minute answers.',followUps:['Expand ISOLATE?']},
  {id:'r12',topic:'Rapid',question:'Lab port?',answer30s:'8096',answer2m:'infra: Postgres 5434 Redis 6380 Kafka 9094.',followUps:['Default broker?']},
  {id:'r13',topic:'Rapid',question:'Outbox must include?',answer30s:'tenant_id',answer2m:'Plus event type and payload.',followUps:['Same TX?']},
  {id:'r14',topic:'Rapid',question:'Suspended tenant HTTP?',answer30s:'403',answer2m:'Keep data for resume.',followUps:['Deleted?']},
  {id:'r15',topic:'Rapid',question:'Metric cardinality risk?',answer30s:'tenant label × endpoint × status explodes.',answer2m:'Use tier on RED metrics.',followUps:['Where put tenant then?']},
];

export const ALL: InterviewQ[] = [...SENIOR, ...ARCHITECT, ...RAPID];
