import type {InterviewBlock, IQ} from './types';

export const CONCEPT_PACKS: InterviewBlock[] = [
  {
    concept: 'Spring AI',
    s30: 'Spring abstraction for models, ChatClient, tools, RAG, memory, MCP with Boot autoconfig.',
    s2m: 'We use ChatClient pipelines with advisors instead of scattered provider SDKs. Domain money stays in Java services exposed as tools.',
    s10m: 'Discuss ChatModel vs ChatClient, advisor chain, version upgrade risks, observability hooks, and why AI Gateway still sits in front.',
    principal: 'Platform choice for governed multi-provider AI inside a Spring estate — not a replacement for domain architecture.',
    followUps: ['Why not call OpenAI from every service?', 'How do you BOM-pin Spring AI?'],
    strong: 'Portability + Spring idioms + centralized safety',
    wrong: 'Spring AI magically makes LLMs correct at finance',
    example: 'Orchestrator module uses ChatClient; portfolio-service remains SoT',
  },
  {
    concept: 'MCP',
    s30: 'Protocol for discovering and invoking AI tools/resources/prompts with schemas.',
    s2m: 'Financial MCP server exposes read tools; client orchestrator discovers them. Authz on every call. Writes are propose-only.',
    s10m: 'Compare MCP vs REST, transports, poisoning, scaling MCP pods, versioned schemas, least privilege scopes.',
    principal: 'Standard capability bus for agents — still needs a security gateway mindset.',
    followUps: ['MCP vs @Tool in-process?', 'How do you rotate tool schemas?'],
    strong: 'Discovery + schema + reusable security boundary',
    wrong: 'MCP replaces all REST APIs',
    example: 'get_portfolio / calculate_pnl tools on financial-mcp-server',
  },
  {
    concept: 'RAG',
    s30: 'Retrieve relevant docs via embeddings, then generate with citations.',
    s2m: 'Ingest policies to vector store; QuestionAnswerAdvisor injects top-K; refuse if below threshold; never RAG live balances.',
    s10m: 'Chunking, hybrid search, rerank, embedding versioning, tenant isolation, eval for retrieval quality.',
    principal: 'Knowledge freshness without fine-tune — retrieval is a production reliability surface.',
    followUps: ['RAG vs fine-tune?', 'How prevent cross-tenant doc bleed?'],
    strong: 'Cited policy answers with fail-closed retrieval',
    wrong: 'Dump whole policy corpus into every prompt',
    example: 'Reversal approval policy POL-ACH-01 chunks',
  },
  {
    concept: 'Embeddings',
    s30: 'Vectors capturing semantic meaning for similarity search.',
    s2m: 'Embed chunks and queries; cosine top-K; "payment failed" near "bank rejected".',
    s10m: 'Dimensions, normalization, model upgrades forcing re-embed, cost at ingest vs query.',
    principal: 'Geometry of meaning — ops problem as much as ML problem.',
    followUps: ['Cosine vs dot product?', 'When hybrid with BM25?'],
    strong: 'Versioned embedding model + metadata filters',
    wrong: 'Embeddings replace transactional queries',
    example: 'In-memory store lab then pgvector',
  },
  {
    concept: 'Tool calling',
    s30: 'Model selects typed tools; Java executes with authz.',
    s2m: '@Tool methods or MCP tools; results feed back; multi-tool loops bounded.',
    s10m: 'Parallel vs sequential tools, failures, timeouts, description poisoning, IDOR via args.',
    principal: 'Tools are privileged RPCs invoked by an untrusted planner (the model).',
    followUps: ['How log tool traces?', 'Read vs write tools?'],
    strong: 'Authz inside tool, not only in prompt text',
    wrong: 'Trust model to only call safe tools',
    example: 'calculatePnL tool wraps PnLCalculator',
  },
  {
    concept: 'Agents',
    s30: 'Bounded planner/executor loop over tools with termination rules.',
    s2m: 'Portfolio agent gathers positions/prices/P&L/risk then stops; expose traces not private CoT.',
    s10m: 'When BPMN beats agents; budgets; runaway loops; human escalation.',
    principal: 'Autonomy is a blast-radius decision in regulated finance.',
    followUps: ['Max iterations default?', 'How test agents?'],
    strong: 'Allowlist + budgets + traces',
    wrong: 'Unbounded ReAct in production payments',
    example: 'P&L down 3% investigation agent',
  },
  {
    concept: 'Human-in-the-loop',
    s30: 'AI proposes sensitive actions; humans approve execution.',
    s2m: 'Reversal flow creates Approval entity; execution service runs only after approve.',
    s10m: 'Maker-checker, SLA, dual control, audit retention, UI for evidence.',
    principal: 'Separates recommendation from authority — non-negotiable for money movement.',
    followUps: ['Auto-approve low risk?', 'How expire stale approvals?'],
    strong: 'Propose/approve/execute state machine',
    wrong: 'LLM calls transfer API directly with user prompt',
    example: '₹20 lakh reversal use case',
  },
  {
    concept: 'Deterministic finance',
    s30: 'Java calculates; AI explains.',
    s2m: 'PnLCalculator output is authoritative; structured response must match snapshot.',
    s10m: 'Reconcile drift, fx rates as-of, corporate actions, audit of calc version.',
    principal: 'Correctness domain stays outside generative models.',
    followUps: ['What if model disagrees with calc?', 'Can LLM estimate fees?'],
    strong: 'Fail if explanation numbers ≠ calculator',
    wrong: 'Ask GPT for portfolio return',
    example: 'ADR-009',
  },
];

function q(id: string, topic: string, question: string, answer: string): IQ {
  return {id, topic, question, answer};
}

export const INTERVIEW_100: IQ[] = [
  q('q1', 'Spring AI', 'Why Spring AI instead of raw OpenAI SDK?', 'Provider abstraction, ChatClient advisors/tools/RAG/MCP integration, Boot config, consistent observability — plus an AI Gateway for governance.'),
  q('q2', 'Spring AI', 'ChatModel vs ChatClient?', 'ChatModel = provider call. ChatClient = fluent app API with advisors, tools, entity mapping, streaming.'),
  q('q3', 'Spring AI', 'What is an Advisor?', 'Intercepts request/response around ChatClient — memory, RAG, security, audit — ordered chain.'),
  q('q4', 'Spring AI', 'Why pass CONVERSATION_ID to memory advisors?', 'Spring AI 1.0+ requires it per call; identifies which history to load; missing → error.'),
  q('q5', 'Spring AI', 'Streaming vs sync?', 'Stream for UX tokens; sync/entity for APIs needing structured JSON.'),
  q('q6', 'Prompts', 'How version prompts?', 'Git-versioned templates, eval suites, canary deploy, rollback like code.'),
  q('q7', 'Prompts', 'Few-shot risk in finance?', 'Models may mimic fake numbers from examples — use format shots carefully.'),
  q('q8', 'Structured', 'How map LLM JSON to records?', 'ChatClient.entity(Class) / converters; then Bean Validation + business reconcile.'),
  q('q9', 'Structured', 'Malformed output handling?', 'Retry with stricter schema; fail closed; never partial-apply money actions.'),
  q('q10', 'Tools', 'How does the model pick a tool?', 'From tool name/description/JSON schema; quality of description is security-sensitive.'),
  q('q11', 'Tools', 'Where enforce authz?', 'Inside tool/service — model args are untrusted input (IDOR risk).'),
  q('q12', 'Tools', 'Parallel tool calls risk?', 'Thundering herd on deps; still per-call authz; timeouts.'),
  q('q13', 'Tools', '@Tool vs MCP tool?', '@Tool in-process; MCP cross-process discoverable reusable façade.'),
  q('q14', 'MCP', 'Why MCP?', 'Standard discovery of tools/resources/prompts for agents across clients.'),
  q('q15', 'MCP', 'MCP vs REST?', 'REST for general APIs; MCP for AI capability sessions/schemas.'),
  q('q16', 'MCP', 'What is tool poisoning?', 'Malicious descriptions that manipulate the model toward unsafe calls.'),
  q('q17', 'MCP', 'How secure MCP?', 'JWT/mTLS, scopes, allowlist, audit, least privilege, no raw money execute.'),
  q('q18', 'MCP', 'MCP resources vs tools?', 'Resources = readable context URIs; tools = actions/computations.'),
  q('q19', 'MCP', 'Scale MCP servers?', 'Stateless pods behind LB; authN; rate limit; independent of orchestrator HPA.'),
  q('q20', 'RAG', 'When RAG vs fine-tune?', 'RAG for changing knowledge; fine-tune for style/stable behavior.'),
  q('q21', 'RAG', 'Chunk size trade-off?', 'Too big → diluted retrieval; too small → broken meaning; tune + overlap.'),
  q('q22', 'RAG', 'Hybrid search?', 'Vector + keyword (BM25) often best for codes/IDs/policy numbers.'),
  q('q23', 'RAG', 'Reduce hallucination?', 'Top-K threshold, citations required, refuse if empty, grounded prompts.'),
  q('q24', 'RAG', 'Cross-tenant leak?', 'Separate indexes or mandatory tenant metadata filters + tests.'),
  q('q25', 'Embed', 'What is an embedding?', 'Dense vector representing semantic content for NN search.'),
  q('q26', 'Embed', 'Cosine similarity?', 'Angle-based similarity; common with normalized vectors.'),
  q('q27', 'Embed', 'Model upgrade impact?', 'Vectors incomparable across models — re-embed corpus; version metadata.'),
  q('q28', 'Vector', 'In-memory store limits?', 'RAM, restart loss, weak multi-pod, poor huge-scale ANN.'),
  q('q29', 'Vector', 'pgvector vs dedicated?', 'pgvector simplicity; dedicated for massive ANN/ops features.'),
  q('q30', 'Vector', 'VectorStore API?', 'add(docs), similaritySearch(request) with topK/filters/threshold.'),
  q('q31', 'Memory', 'Memory explosion?', 'Token growth → summarize/truncate/TTL; privacy retention limits.'),
  q('q32', 'Memory', 'Where store sessions?', 'Redis/DB keyed by tenant+conversation; not only JVM heap.'),
  q('q33', 'Agent', 'When avoid agents?', 'Fixed regulated workflows — use BPMN/deterministic orchestration.'),
  q('q34', 'Agent', 'Stop runaway agents?', 'Max iterations, timeouts, budgets, allowlists, circuit breakers.'),
  q('q35', 'Agent', 'Why traces not CoT?', 'Auditability without leaking private reasoning; compliance friendly.'),
  q('q36', 'Guard', 'Read vs write tools?', 'Read auto; write propose→approve→execute.'),
  q('q37', 'Kafka', 'AI + Kafka pattern?', 'Consume to services/caches; tools read projections; no raw bus in prompt.'),
  q('q38', 'Kafka', 'Replay investigations?', 'Reprocess events idempotently; store investigation execution id.'),
  q('q39', 'Calc', 'Who owns P&L?', 'Java calculator; model explains; validate equality.'),
  q('q40', 'Calc', 'LLM fee estimate OK?', 'No for billing; illustrative only if labeled non-authoritative.'),
  q('q41', 'HITL', 'Why human approval?', 'Authority separation; fraud/compliance; irreversible money risk.'),
  q('q42', 'HITL', 'Approval data model?', 'proposedAction, evidence, risk score, approver, decision, timestamps.'),
  q('q43', 'Inject', 'Indirect injection?', 'Malicious content in retrieved docs influencing tool use.'),
  q('q44', 'Inject', 'Defenses?', 'Allowlists, escaping, redaction, separate untrusted corpora, output filters.'),
  q('q45', 'Sec', 'IDOR via tools?', 'Model passes another user portfolioId — tool must authz.'),
  q('q46', 'Sec', 'PII to provider?', 'Minimize/redact/tokenize; contractual + technical controls.'),
  q('q47', 'Obs', 'Key LLM metrics?', 'Requests, latency, tokens, cost, errors, tool/RAG latency.'),
  q('q48', 'Obs', 'Correlation across MCP?', 'Propagate trace/correlation ids into tool spans + audit rows.'),
  q('q49', 'Resilience', 'LLM outage degrade?', 'FAQ templates, queue to humans, cached prior analyses with staleness.'),
  q('q50', 'Resilience', 'Vector outage?', 'Keyword fallback or refuse RAG questions explicitly.'),
  q('q51', 'Cache', 'Cache market prices?', 'Short TTL + event invalidation; show as-of; never invent.'),
  q('q52', 'Cache', 'Cache LLM answers?', 'Only for immutable FAQs; dangerous for portfolio-specific.'),
  q('q53', 'Cost', 'Cut token cost?', 'Routing, compression, RAG, caching embeddings, smaller models, Java math.'),
  q('q54', 'Route', 'Model router?', 'Classifier → small/medium/large/no-model based on intent.'),
  q('q55', 'Gateway', 'AI Gateway role?', 'Central keys, budgets, routing, safety, templates, metrics.'),
  q('q56', 'Multi', 'Multi-provider?', 'Abstract ChatModel; failover; beware structured-output quirks.'),
  q('q57', 'Data', 'What in Postgres vs vector?', 'Transactions/approvals in PG; chunk embeddings in vector/pgvector.'),
  q('q58', 'API', 'Sync vs 202?', 'Chat sync/stream; long investigations async with execution id.'),
  q('q59', 'Test', 'How test tools?', 'Unit authz+calc; contract tests; mock model selecting tools.'),
  q('q60', 'Test', 'Eval RAG?', 'Golden queries, recall@k, citation accuracy, human ratings.'),
  q('q61', 'Perf', 'p99 dominated by?', 'Usually LLM; then tools; optimize parallel reads + smaller prompts.'),
  q('q62', 'Deploy', 'Canary prompts?', 'Split traffic by tenant%; compare eval metrics; instant rollback.'),
  q('q63', 'Deploy', 'Stateless orchestrator?', 'Yes — externalize memory; scale HPA on RPS/latency.'),
  q('q64', 'Tradeoff', 'Agent vs workflow engine?', 'Agents explore; Camunda enforces regulated paths.'),
  q('q65', 'Tradeoff', 'MCP vs only OpenAPI tools?', 'OpenAPI possible; MCP better discovery/session for agents.'),
  q('q66', 'FinTech', 'What AI must not do?', 'Authoritative money calc, unrestricted transfers, silent compliance bypass.'),
  q('q67', 'FinTech', 'Explain unusual txn?', 'Tools for txn+customer+device; RAG policy; structured suspicion score + human case.'),
  q('q68', 'FinTech', 'Market summary gen?', 'Tools for prices/news metadata; model summarizes with timestamps; no fake quotes.'),
  q('q69', 'Governance', 'Model upgrade process?', 'Shadow eval, canary, embedding reindex plan, prompt regression suite.'),
  q('q70', 'Governance', 'Audit regulators want?', 'Who asked what, tools called, docs cited, approvals, outputs stored.'),
  q('q71', 'Spring', 'BeanOutputConverter role?', 'Helps map model output into typed objects — still validate.'),
  q('q72', 'Spring', 'QuestionAnswerAdvisor?', 'Naive RAG advisor injecting vector hits into prompt context.'),
  q('q73', 'Spring', 'ToolCallingAdvisor?', 'Handles model-requested tool calls in ChatClient chain (1.0+ behavior).'),
  q('q74', 'MCP', 'Capability negotiation?', 'Client/server agree on protocol features/tools available for session.'),
  q('q75', 'MCP', 'Prompts in MCP?', 'Reusable prompt templates hosted by server for clients to fetch.'),
  q('q76', 'RAG', 'Reranking why?', 'Improve precision after cheap top-K recall.'),
  q('q77', 'RAG', 'Context compression?', 'Shrink retrieved text to fit window without losing citations.'),
  q('q78', 'Agent', 'Observation/state?', 'Persist intermediate tool results for resume/debug; bound size.'),
  q('q79', 'Sec', 'ABAC example?', 'Permit read if subject.tenant==resource.tenant && clearance>=doc.level.'),
  q('q80', 'Sec', 'Scope design?', 'Fine-grained mcp.*.read vs rare mcp.transfer.propose.'),
  q('q81', 'Kafka', 'Ordering guarantee?', 'Per partition key (e.g., portfolioId); not global.'),
  q('q82', 'Kafka', 'Exactly-once?', 'Hard end-to-end; prefer idempotent consumers + transactional outbox.'),
  q('q83', 'Obs', 'Track cost?', 'Tokens×price by model/tenant; budget alarms; chargeback.'),
  q('q84', 'Resilience', 'Bulkhead AI?', 'Separate pools/limits for chat vs batch investigations.'),
  q('q85', 'Cache', 'Embedding cache key?', 'modelVersion + hash(text); invalidate on model change.'),
  q('q86', 'Gateway', 'Prevent key sprawl?', 'Only gateway holds provider credentials.'),
  q('q87', 'Multi', 'Structured output differs by provider?', 'Yes — normalize via tests; prefer providers with schema mode.'),
  q('q88', 'Data', 'conversation_messages retention?', 'Policy-driven TTL; encrypt; export/delete support.'),
  q('q89', 'API', 'GET execution/{id}?', 'Fetch tool traces + status for async AI jobs.'),
  q('q90', 'Test', 'Prompt injection CI?', 'Corpus of attacks; assert no forbidden tool; assert refusal.'),
  q('q91', 'Perf', 'Tool latency budget?', 'Parallelize independent tools; cache hot reads; CB slow deps.'),
  q('q92', 'Deploy', 'MCP breaking change?', 'Version tools; dual-run; consumers pin versions.'),
  q('q93', 'Principal', 'Where AI ROI in bank?', 'Ops investigation, policy Q&A, research assist — not core ledger.'),
  q('q94', 'Principal', 'Org operating model?', 'AI platform team owns gateway/eval; domains own tools/calculators.'),
  q('q95', 'Principal', 'Risk of autonomous trading agent?', 'Market abuse, runaway orders — require hard limits + human gates.'),
  q('q96', 'Principal', 'Data residency?', 'Region-pinned providers/vector/DB; block cross-region RAG.'),
  q('q97', 'Principal', 'Evaluate correctness beyond BLEU?', 'Task success, tool accuracy, citation precision, financial reconcile rate.'),
  q('q98', 'Principal', 'Incident: wrong P&L explained?', 'Compare calc snapshot; freeze model; patch validation; customer notify.'),
  q('q99', 'Principal', 'Why not put Kafka consumer in LLM loop?', 'Coupling, latency, prompt bloat — use projections.'),
  q('q100', 'Principal', 'Staff+ signal in design review?', 'Threat model, budgets, failure modes, ownership boundaries, measurable evals.'),
  q('q101', 'Spring AI', 'temperature in FinTech?', 'Keep low for factual tasks; creative marketing separate.'),
  q('q102', 'MCP', 'Local stdio MCP use?', 'Dev/desktop agents; prod prefers remote hardened servers.'),
  q('q103', 'RAG', 'Doc update propagation?', 'Re-ingest pipeline; version metadata; invalidate caches.'),
  q('q104', 'Agent', 'Tool failure mid-loop?', 'Retry idempotent reads; abort writes; return partial with uncertainty.'),
  q('q105', 'Sec', 'Secrets in prompts?', 'Never; use vaulted config; redact logs.'),
];
