import type {TocItem} from './types';

export const SPRING_AI_TOC: TocItem[] = [
  {id: 'runnable-lab', label: '00. Runnable Java lab'},
  {id: 'mission', label: '01. Mission & rules'},
  {id: 'product', label: '02. Product capabilities'},
  {id: 'architecture', label: '03. Reference architecture'},
  {id: 'modules', label: '04. Multi-module structure'},
  {id: 'fundamentals', label: '05. Spring AI fundamentals'},
  {id: 'chatclient', label: '06. ChatClient deep dive'},
  {id: 'prompts', label: '07. Prompt architecture'},
  {id: 'structured', label: '08. Structured output'},
  {id: 'tools', label: '09. Tool calling'},
  {id: 'mcp', label: '10. MCP deep dive'},
  {id: 'mcp-server', label: '11. Financial MCP server'},
  {id: 'mcp-security', label: '12. MCP security'},
  {id: 'rag', label: '13. RAG pipeline'},
  {id: 'embeddings', label: '14. Embeddings internals'},
  {id: 'vector-memory', label: '15. In-memory vector store'},
  {id: 'vectorstore', label: '16. Spring AI VectorStore'},
  {id: 'advisors', label: '17. Advisors'},
  {id: 'memory', label: '18. Conversation memory'},
  {id: 'agents', label: '19. Controlled agents'},
  {id: 'guardrails', label: '20. Agent guardrails'},
  {id: 'kafka', label: '21. Real-time Kafka'},
  {id: 'deterministic', label: '22. Deterministic finance'},
  {id: 'event-ai', label: '23. Event-driven AI'},
  {id: 'hitl', label: '24. Human-in-the-loop'},
  {id: 'injection', label: '25. Prompt injection'},
  {id: 'security', label: '26. Security architecture'},
  {id: 'observability', label: '27. Observability'},
  {id: 'resilience', label: '28. Resilience'},
  {id: 'caching-cost', label: '29. Caching · cost · routing'},
  {id: 'gateway', label: '30. AI Gateway'},
  {id: 'data-api', label: '31. Data model · APIs'},
  {id: 'usecase-pnl', label: '32. E2E: portfolio P&L'},
  {id: 'usecase-payment', label: '33. E2E: payment failure'},
  {id: 'usecase-reversal', label: '34. E2E: reversal + approval'},
  {id: 'testing', label: '35. Testing · performance'},
  {id: 'deploy', label: '36. K8s deployment'},
  {id: 'tradeoffs', label: '37. Architecture trade-offs'},
  {id: 'mistakes', label: '38. Production mistakes'},
  {id: 'adrs', label: '39. ADRs'},
  {id: 'phases', label: '40. Build phases'},
  {id: 'interview-concepts', label: '41. Concept interview packs'},
  {id: 'interview-100', label: '42. 100+ advanced questions'},
  {id: 'checklist', label: '43. Production checklist'},
  {id: 'mock', label: '44. Mock interview'},
];

export const VERSION_NOTE =
  'Spring Boot 3.4 · Spring AI 1.1.x · Ops Assistant: /ai-fintech-demo (ai-fintech-platform/) · Earlier lab: /spring-ai-demo · Sibling: /fintech · /kafka-interview · /spring-security · /resilience4j.';

export const CORE_RULE =
  'AI = orchestration, retrieval, explanation. Java = money math, authorization, audit. Never let the LLM invent P&L or execute unrestricted transfers.';
