import type {InterviewQ} from './types';

export const CORE_QS: InterviewQ[] = [
  {id:'q1',topic:'Fundamentals',question:'Why is cache invalidation hard in distributed systems?',answer30s:'Multiple writers, replicas, L1 copies, and races between DB commit and cache views create coherence windows.',answer2m:'Show multi-pod L1+L2, TX rollback races, and Kafka lag. Prefer invalidate-after-commit and versioned keys.',followUps:['When is put safer than invalidate?'],trick:'Just set a short TTL and forget.'},
  {id:'q2',topic:'Redis',question:'Can Redis be a single point of failure?',answer30s:'A single primary without HA is a SPOF. Cluster/Sentinel reduce but introduce partition behaviors.',answer2m:'Design fail-open for cache; separate durability needs from cache tier.',followUps:['Sentinel vs Cluster tradeoffs?'],trick:'Redis Cluster means zero downtime always.'},
  {id:'q3',topic:'CAP',question:'How do CAP and caching relate?',answer30s:'Caches usually choose AP-ish acceleration with eventual coherence; strong reads go to DB.',answer2m:'During partition, stale hits may continue; document the consistency class per API.',followUps:['RYW designs?'],trick:'Redis is CP for all workloads.'},
  {id:'q4',topic:'Stampede',question:'How do you prevent thundering herd on expiry?',answer30s:'TTL jitter + single-flight lock + refresh-ahead for hot keys.',answer2m:'Show SET NX PX loader election and loser retry.',followUps:['Probabilistic early expiration?'],trick:'Bigger Redis fixes stampedes.'},
  {id:'q5',topic:'Hot key',question:'One key at 500k RPS — what do you do?',answer30s:'L1 per pod, coalesce, replicate keys, read replicas; Cluster alone does not split one key.',answer2m:'Detect hot keys; optional app sharding with fan-out writes.',followUps:['How detect automatically?'],trick:'Add nodes and it shards the key.'},
  {id:'q6',topic:'Spring',question:'Why can @Cacheable silently not run?',answer30s:'Self-invocation bypasses Spring AOP proxy; missing @EnableCaching; wrong CacheManager.',answer2m:'Extract collaborator bean or inject self proxy.',followUps:['AspectJ weaving?'],trick:'Annotations always weave all calls.'},
  {id:'q7',topic:'Consistency',question:'Payment status stale in cache — design fix?',answer30s:'DB SoR; invalidate after commit; CDC/Kafka fan-out; short TTL on status.',answer2m:'Never cache authoritative ledger balances without strict controls.',followUps:['Outbox vs dual write?'],trick:'Write-through always solves money.'},
  {id:'q8',topic:'Lock',question:'JVM lock vs Redis lock?',answer30s:'JVM lock is process-local; Redis lock coordinates pods with NX+TTL+token.',answer2m:'Not a substitute for DB transactions; fencing for writers.',followUps:['Redlock controversy?'],trick:'synchronized across Kubernetes.'},
  {id:'q9',topic:'Multi-region',question:'Design cache for multi-region?',answer30s:'Regional Redis; global invalidation bus; accept RTT; pin sticky reads or version tokens for RYW.',answer2m:'Avoid cross-region synchronous cache dependency on critical path.',followUps:['Active-active conflict?'],trick:'One global Redis always.'},
  {id:'q10',topic:'Security',question:'GDPR / PII in Redis?',answer30s:'Minimize PII; encrypt; TTL; tenant isolation; right-to-erasure = delete keys; no unbounded retention.',answer2m:'Prefer tokens/ids in cache; fetch sensitive fields from secured DB.',followUps:['Cache poisoning defenses?'],trick:'Redis is internal so PII is fine forever.'},
];

function scenarios(): InterviewQ[] {
  const rows: Array<[string, string, string]> = [
    ['Redis unavailable — what happens to API?','Fail-open to DB with timeouts/CB; shed load if DB cannot absorb.','When fail-closed?'],
    ['Hit ratio 95% → 40% overnight','Check deploys, key changes, TTL, evictions, stampede, serialization errors.','Which metrics first?'],
    ['Hot key 500k RPS','L1 + coalesce + replicas; measure node CPU.','App sharding how?'],
    ['All keys same TTL','Jitter + soft load on restart.','Warm strategy?'],
    ['DB overload after Redis restart','Empty cache avalanche; rate-limit loaders; staged warm.','Priority keys?'],
    ['Two services update same customer','Invalidate bus; version field; last-write-wins documented.','CRDT?'],
    ['Stale payment status','afterCommit invalidate; don\'t cache terminal incorrectly.','Who is SoR?'],
    ['Redis latency 2ms → 100ms','Slowlog, big keys, network, CPU, eviction storms; CB.','Thread pool impact?'],
    ['Memory 95%','Eviction policy, TTLs, big JSON, split tiers.','allkeys-lru vs volatile?'],
    ['Cluster node lost','Failover to replica; MOVED handling; client refresh.','Slot migration?'],
    ['Invalidate across 50 services','Kafka/CDC topic; idempotent consumers; monitor lag.','Redis pub/sub limits?'],
    ['Cache 100M customers','Not all in RAM; tier; TTL; probabilistic; store projections.','What subset?'],
    ['Multi-region cache','Regional L2; async invalidate; RYW tokens.','Conflict window?'],
    ['Prevent cache poisoning','Authz on write paths; signed values; no client-set cache.','SSR F caches?'],
    ['Kafka invalidate lag spike','Lag = staleness SLO breach; scale consumers; alert.','Replay strategy?'],
    ['Redis vs Hazelcast','Redis KV/ops simplicity vs IMDG compute.','When grid wins?'],
    ['When NOT to cache','Write-heavy unique keys; strong consistency money; tiny tables.','Index instead?'],
    ['Schema N vs N+1 deploy','Versioned DTO keys; dual-read; ignore unknown fields.','Poison old JSON?'],
    ['TTL too short','DB load ↑; thrash.','How pick TTL?'],
    ['TTL too long','Stale UX / compliance risk.','Invalidate events?'],
    ['Cache vs CQRS','CQRS read models may replace ad-hoc cache.','Materialized view?'],
    ['Saga + cache','Invalidate on each step carefully; avoid caching mid-saga state.','Compensating?'],
    ['Event sourcing + cache','Cache projections; rebuild from stream.','Snapshot?'],
    ['Zero-downtime Redis migration','Dual-write or warm replica; switch DNS; compare.','Slot migrate?'],
    ['Detect hot keys','redis-cli --hotkeys, proxy metrics, app counters.','Auto L1 promote?'],
    ['Null caching attacks','Short __NULL__ TTL + Bloom + rate limit.','False positive?'],
    ['Self-invocation bug','Extract bean; integration test proves HIT.','How test?'],
    ['Cache in @Transactional','afterCommit only.','Dirty read refill?'],
    ['Lettuce vs Jedis','Lettuce netty async default in Boot; pooling.','Blocking risks?'],
    ['Hash tags use','Multi-key ops same slot.','Hot tag risk?'],
  ];
  return rows.map((r, i) => ({
    id: `s${i + 1}`,
    topic: 'Scenario',
    question: r[0],
    answer30s: r[1],
    answer2m: r[1],
    followUps: [r[2]],
  }));
}

function rapid(): InterviewQ[] {
  const qs = [
    'Cache-aside vs read-through?',
    'Write-through vs write-behind risk?',
    'Why hash tags in Cluster?',
    'How many hash slots?',
    'Why avoid JDK serialization?',
    'What is stampede?',
    'What is penetration?',
    'What is avalanche?',
    'L1 vs L2?',
    'Why afterCommit invalidate?',
    'SET NX PX meaning?',
    'Why token on unlock?',
    'Fail-open meaning?',
    'Hit ratio formula?',
    'allkeys-lru vs volatile-lru?',
    'When Caffeine alone?',
    'When Redis alone?',
    'When Hazelcast?',
    'Pub/sub vs Kafka invalidate?',
    'How multi-tenant keys?',
    'Self-invocation problem?',
    'CacheErrorHandler role?',
    'KeyGenerator when?',
    'Null cache marker risk?',
    'Bloom filter role?',
    'Hot key mitigations?',
    'Redis slow → threads?',
    'Circuit breaker placement?',
    'RYW techniques?',
    'Monotonic reads?',
    'Cache poisoning?',
    'PII in cache?',
    'Schema evolution?',
    'Big key problem?',
    'Eviction metrics?',
    'Testcontainers why?',
    'TTL jitter why?',
    'Refresh-ahead when?',
    'Write-around when?',
    'DB index vs cache?',
    'Materialized view vs Redis?',
    'CQRS vs cache?',
    'Saga interaction?',
    'Event sourcing rebuild?',
    'Sentinel vs Cluster?',
    'MOVED redirect?',
    'ASK redirect?',
    'Replica lag stale read?',
    'Connection pool sizing?',
    'Serialization CPU cost?',
    'Micrometer cache meters?',
    'Alert on hit drop?',
    'Cold start warm?',
    'Multi-region invalidate?',
    'Idempotent invalidate?',
    'DLQ for cache events?',
    'Outbox pattern?',
    'CDC invalidate?',
    'Redlock caveat?',
    'ZooKeeper lock when?',
    'DB advisory lock when?',
    'Singleflight in-process?',
    'Coalescing requests?',
    'Soft expiration?',
    'Probabilistic early expire?',
    'Cache stampede lock TTL?',
    'Unlock Lua why?',
    'Cross-slot transaction?',
    'Logical DB isolation weak?',
    'Prefix collision risk?',
    'Service name in key?',
    'Disable null caching when?',
    'Jackson typing risk?',
    'Protobuf vs JSON cache?',
    'Avro evolution?',
    'Kryo Java-only?',
    'Session store vs app cache?',
    'Rate limit in Redis?',
    'Idempotency keys stored where?',
    'Payment status cache TTL?',
    'FX rate hot key?',
    'Catalog L1 TTL?',
    'How debug miss storm?',
    'How prove second hit?',
    'How simulate Redis down in test?',
    'Bulkhead for Redis client?',
    'Timeout 200ms rationale?',
    'What if put fails?',
    'What if evict fails?',
    'Stale while revalidate?',
    'CDN vs Redis app cache?',
    'Near cache meaning?',
    'Replication vs sharding?',
    'Consistent hashing client?',
    'Memcached sharding?',
    'Ehcache disk tier?',
    'Infinispan owners?',
    'Hazelcast MapLoader?',
    'Spring CacheResolver?',
    'Multiple CacheManagers?',
    'Actuator cache endpoint?',
    'When delete cache entirely?',
  ];
  return qs.map((q, i) => ({
    id: `rf${i + 1}`,
    topic: 'Rapid',
    question: q,
    answer30s: 'Mechanism → failure mode → production choice with payment example.',
    answer2m: 'Tie to L1/L2, Redis, Spring AOP, and consistency class.',
    followUps: ['What breaks at 10× traffic?'],
  }));
}

export const SCENARIO_QS = scenarios();
export const RAPID_QS = rapid();
export const ARCHITECT_QS = CORE_QS;
export const ALL_INTERVIEW = [...CORE_QS, ...SCENARIO_QS, ...RAPID_QS];
