import type {TocItem} from './types';

export const CACHE_TOC: TocItem[] = [
  {id: 'overview', label: 'Production Problem'},
  {id: 'taxonomy', label: 'Cache Taxonomy'},
  {id: 'spring-cache', label: 'Spring Cache Abstraction'},
  {id: 'cache-aside', label: 'Cache-Aside'},
  {id: 'read-through', label: 'Read-Through'},
  {id: 'write-through', label: 'Write-Through'},
  {id: 'write-behind', label: 'Write-Behind'},
  {id: 'write-around', label: 'Write-Around'},
  {id: 'refresh-ahead', label: 'Refresh-Ahead'},
  {id: 'redis', label: 'Redis Architecture'},
  {id: 'redis-cluster', label: 'Redis Cluster / Slots'},
  {id: 'l1l2', label: 'Multi-Level L1/L2'},
  {id: 'consistency', label: 'Consistency Models'},
  {id: 'kafka-invalidate', label: 'Kafka Invalidation'},
  {id: 'stampede', label: 'Cache Stampede'},
  {id: 'penetration', label: 'Cache Penetration'},
  {id: 'avalanche', label: 'Cache Avalanche'},
  {id: 'hot-key', label: 'Hot Keys'},
  {id: 'eviction', label: 'Eviction & TTL'},
  {id: 'serialization', label: 'Serialization'},
  {id: 'distributed-lock', label: 'Distributed Locking'},
  {id: 'failures', label: 'Redis Failure Modes'},
  {id: 'config', label: 'Spring Boot Config'},
  {id: 'customization', label: 'Cache Customization'},
  {id: 'multi-tenant', label: 'Multi-Tenant Cache'},
  {id: 'tx-cache', label: 'Transaction + Cache'},
  {id: 'observability', label: 'Observability'},
  {id: 'testing', label: 'Testing'},
  {id: 'matrix', label: 'Technology Matrix'},
  {id: 'decision', label: 'Decision Tree'},
  {id: 'scenarios', label: 'Interview Scenarios'},
  {id: 'architect-qs', label: 'Architect Questions'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'cheat', label: 'Cheat Sheet'},
];
