import type {TocItem} from './types';

/** Producer-only curriculum — maps the master prompt into navigable boards. */
export const KAFKA_PRODUCER_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview & version'},
  {id: 'fundamentals', label: '01. Fundamentals'},
  {id: 'lifecycle', label: '02. send() lifecycle'},
  {id: 'architecture', label: '03. Internals & threads'},
  {id: 'api', label: '04. API & sync/async'},
  {id: 'serialization', label: '05. Serialization'},
  {id: 'partitioning', label: '06. Partitioning & keys'},
  {id: 'ordering', label: '07. Ordering'},
  {id: 'headers-ts', label: '08. Headers & timestamps'},
  {id: 'batching', label: '09. Accumulator · batch · compress'},
  {id: 'memory', label: '10. Memory & backpressure'},
  {id: 'network-meta', label: '11. Network & metadata'},
  {id: 'acks', label: '12. Acks & replication'},
  {id: 'retries', label: '13. Retries & semantics'},
  {id: 'idempotence', label: '14. Idempotence · PID · in-flight'},
  {id: 'transactions', label: '15. Transactions · EOS · outbox'},
  {id: 'config', label: '16. Config & profiles'},
  {id: 'performance', label: '17. Performance & capacity'},
  {id: 'security', label: '18. Security'},
  {id: 'observability', label: '19. Metrics · tracing · logs'},
  {id: 'spring', label: '20. Spring Kafka'},
  {id: 'failures', label: '21. Failure matrix'},
  {id: 'ops', label: '22. Troubleshoot · chaos · DR'},
  {id: 'finance', label: '23. Payments architecture'},
  {id: 'antipatterns', label: '24. Anti-patterns'},
  {id: 'source', label: '25. Source · protocol · quotas'},
  {id: 'interview', label: '26. Interview & cheatsheets'},
];
