server:
  port: 9000

spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:h2:mem:authdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  h2:
    console:
      enabled: true

app:
  issuer: http://localhost:9000
  access-token-ttl: PT10M
  refresh-token-ttl: P1D

logging:
  level:
    org.springframework.security: INFO
