import type {InterviewQ} from './types';

export const SENIOR: InterviewQ[] = [
  {
    id: 's1',
    topic: 'Why',
    question: 'Why override equals and hashCode together for HashMap keys?',
    answer30s: 'hashCode picks the bucket; equals finds the entry. Missing either breaks put/get.',
    answer2m:
      'Without hashCode, equal logical keys land in different buckets so equals never runs. Without equals, same-bucket instances never replace. Keep them consistent with the Object contract.',
    followUps: ['Only equals?', 'Only hashCode?'],
    trick: '“hashCode is optional if equals is correct.”',
  },
  {
    id: 's2',
    topic: 'Contract',
    question: 'If equals is true, must hashCodes match?',
    answer30s: 'Yes — required by the contract.',
    answer2m: 'Hash maps assume this. Violating it causes silent lookup failures.',
    followUps: ['Can unequal objects share a hashCode?'],
  },
  {
    id: 's3',
    topic: 'Collision',
    question: 'Same hashCode — are objects always equal?',
    answer30s: 'No. Collisions are normal; equals decides.',
    answer2m: 'HashMap walks/treeifies the bin and calls equals on candidates.',
    followUps: ['What is treeification?'],
  },
  {
    id: 's4',
    topic: 'CHM',
    question: 'Does ConcurrentHashMap still need equals/hashCode?',
    answer30s: 'Yes — same key equality rules as HashMap.',
    answer2m: 'Concurrency does not replace the contract. Also: no null keys/values; use putIfAbsent/compute carefully.',
    followUps: ['Why no null key?'],
  },
  {
    id: 's5',
    topic: 'LinkedHashMap',
    question: 'Does LinkedHashMap use equals/hashCode?',
    answer30s: 'Yes, identical lookup to HashMap.',
    answer2m: 'Extra linked list gives insertion- or access-order. LRU still needs a correct key contract.',
    followUps: ['accessOrder=true?'],
  },
  {
    id: 's6',
    topic: 'TreeMap',
    question: 'Does TreeMap use hashCode?',
    answer30s: 'Not for placement — Comparable/Comparator.',
    answer2m: 'Sameness is compare==0. Broken equals/hashCode can still “work” if compareTo is by business key — and can silently disagree with HashMap.',
    followUps: ['Not Comparable and no Comparator?'],
    trick: '“TreeMap hashes into a red-black tree.”',
  },
  {
    id: 's7',
    topic: 'compareTo',
    question: 'What happens when compareTo returns zero?',
    answer30s: 'SortedMap treats keys as equal — put replaces.',
    answer2m: 'Even if equals is false. Classic data-loss bug with incomplete Comparators.',
    followUps: ['How to fix dept-only Comparator?'],
  },
  {
    id: 's8',
    topic: 'Mutable',
    question: 'What if a HashMap key is mutated after put?',
    answer30s: 'Entry can become unreachable; get returns null.',
    answer2m: 'hashCode/equals fields changed → wrong bucket. Same class of bug on CHM/LinkedHashMap.',
    followUps: ['TreeMap mutable key?'],
  },
  {
    id: 's9',
    topic: 'TreeMap mutable',
    question: 'What if a TreeMap key is mutated?',
    answer30s: 'Tree structure can break; lookups fail unpredictably.',
    answer2m: 'Node placed by old compare values. Fix: immutable keys or remove+reinsert.',
    followUps: []},
  {
    id: 's10',
    topic: 'Complexity',
    question: 'Why is TreeMap O(log n)?',
    answer30s: 'Balanced tree height is logarithmic.',
    answer2m: 'Each compare descends left/right. HashMap average O(1) with good hashing; worst degraded without treeify.',
    followUps: ['HashMap vs TreeMap when to choose?'],
  },
  {
    id: 's11',
    topic: 'Compare maps',
    question: 'HashMap vs LinkedHashMap vs ConcurrentHashMap?',
    answer30s: 'Same key contract; order vs concurrency differ.',
    answer2m: 'LHM: order/LRU. CHM: concurrent, no nulls. HashMap: general single-thread.',
    followUps: ['Hashtable?'],
  },
  {
    id: 's12',
    topic: 'Comparable vs Comparator',
    question: 'Comparable vs Comparator?',
    answer30s: 'Natural order on the class vs external strategy.',
    answer2m: 'A class can have many Comparators; only one Comparable. Both must stay consistent with equals for SortedMap keys.',
    followUps: ['Multiple sorting strategies?'],
  },
  {
    id: 's13',
    topic: 'Consistency',
    question: 'Comparator inconsistent with equals — what breaks?',
    answer30s: 'TreeMap/SkipList silently collapse distinct keys.',
    answer2m: 'HashMap may keep both while TreeMap keeps one. SortedSet contracts break.',
    followUps: ['Demo with id+tag?'],
  },
  {
    id: 's14',
    topic: 'IdentityHashMap',
    question: 'How is IdentityHashMap different?',
    answer30s: 'Uses == not equals for key identity.',
    answer2m: 'Logically equal instances are different keys. Niche use — not a normal cache.',
    followUps: []},
  {
    id: 's15',
    topic: 'EnumMap',
    question: 'Why prefer EnumMap for enum keys?',
    answer30s: 'Array by ordinal — fast, compact, type-safe.',
    answer2m: 'No hashing of keys; null keys forbidden; single enum type only.',
    followUps: []},
  {
    id: 's16',
    topic: 'Records',
    question: 'Why are records good map keys?',
    answer30s: 'Immutable + generated equals/hashCode.',
    answer2m: 'Still need Comparator for TreeMap unless you implement Comparable.',
    followUps: []},
  {
    id: 's17',
    topic: 'SkipList',
    question: 'ConcurrentSkipListMap key mechanism?',
    answer30s: 'Comparable/Comparator — concurrent sorted map.',
    answer2m: 'Like TreeMap concurrency-wise successor; hashCode unused for order.',
    followUps: []},
  {
    id: 's18',
    topic: 'Hashtable',
    question: 'Why avoid Hashtable in new code?',
    answer30s: 'Coarse synchronization; prefer ConcurrentHashMap.',
    answer2m: 'Still hashCode+equals; no nulls; legacy API.',
    followUps: []},
  {
    id: 's19',
    topic: 'Overflow',
    question: 'Why is id - other.id dangerous in compareTo?',
    answer30s: 'Integer overflow flips sign.',
    answer2m: 'Use Integer.compare or Comparator.comparingInt.',
    followUps: []},
  {
    id: 's20',
    topic: 'Null',
    question: 'Which maps allow a null key?',
    answer30s: 'HashMap/LinkedHashMap: one null key. CHM/Hashtable/TreeMap(natural): no.',
    answer2m: 'TreeMap with nulls-friendly Comparator can allow nulls — usually avoid.',
    followUps: []},
];

export const ARCHITECT: InterviewQ[] = [
  {
    id: 'a1',
    topic: 'Design',
    question: 'Design a production payment cache key for CHM + Redis.',
    answer30s: 'Immutable record (tenantId, paymentId); CHM local; Redis canonical string.',
    answer2m: 'Normalize case; forbid nulls; document encoding; never mutate; do not treat CHM as multi-JVM source of truth.',
    followUps: ['Collision across tenants?'],
  },
  {
    id: 'a2',
    topic: 'LRU',
    question: 'Implement a bounded LRU — trade-offs?',
    answer30s: 'LinkedHashMap accessOrder + removeEldestEntry for single-thread.',
    answer2m: 'For concurrent LRU use Caffeine/Guava or striped designs. Key contract still required.',
    followUps: ['Why not TreeMap for LRU?'],
  },
  {
    id: 'a3',
    topic: 'Sorted concurrent',
    question: 'When ConcurrentSkipListMap over TreeMap?',
    answer30s: 'Need sorted keys under concurrent writers.',
    answer2m: 'O(log n); range views; Comparator consistency critical.',
    followUps: []},
  {
    id: 'a4',
    topic: 'Treeify',
    question: 'How does HashMap treeification change interview answers?',
    answer30s: 'Pathological collisions degrade less than pure linked lists.',
    answer2m: 'Still not an excuse for terrible hashCode (e.g. always 1) — bin pressure and memory hurt.',
    followUps: []},
  {
    id: 'a5',
    topic: 'Identity',
    question: 'When is IdentityHashMap the right tool?',
    answer30s: 'When reference identity is the domain (graphs, serializers).',
    answer2m: 'If you wanted business equality you picked the wrong map.',
    followUps: [],
  },
  {
    id: 'a6',
    topic: 'BigDecimal',
    question: 'Why is BigDecimal a TreeMap interview favorite?',
    answer30s: 'equals cares about scale; compareTo is numerical — HashMap keeps both, TreeMap collapses.',
    answer2m:
      'new BigDecimal("1.0").equals(new BigDecimal("1.00")) is false but compareTo==0. Document stripTrailingZeros or Comparator policy.',
    followUps: ['Would ConcurrentSkipListMap behave like TreeMap?'],
  },
  {
    id: 'a7',
    topic: 'Internals',
    question: 'Why does HashMap XOR hash with hash>>>16?',
    answer30s: 'Spread high bits into the index bits used by power-of-two tables.',
    answer2m:
      'Without spreading, keys differing only in high bits collide. Combined with treeify thresholds, this is the modern collision story.',
    followUps: ['TREEIFY_THRESHOLD?', 'MIN_TREEIFY_CAPACITY?'],
  },
  {
    id: 'a8',
    topic: 'JPA',
    question: 'Why are JPA entities risky as HashMap keys?',
    answer30s: 'Generated ids, proxies, and mutable fields change identity across the lifecycle.',
    answer2m:
      'Prefer Map<UUID, Entity> or an immutable business key assigned at creation. Never hash lazy collections.',
    followUps: ['equals before vs after persist?'],
  },
  {
    id: 'a9',
    topic: 'WeakHashMap',
    question: 'Can WeakHashMap replace a production cache?',
    answer30s: 'No — GC-driven eviction is unpredictable; value→key leaks are common.',
    answer2m: 'Use Caffeine/Guava with size/time eviction. WeakHashMap is for specialized weakly-referenced metadata.',
    followUps: [],
  },
];

export const RAPID: InterviewQ[] = [
  {id: 'r1', topic: 'Rapid', question: 'equals true ⇒ same hashCode?', answer30s: 'Yes.', answer2m: 'Contract.', followUps: []},
  {id: 'r2', topic: 'Rapid', question: 'Same hashCode ⇒ equals?', answer30s: 'No.', answer2m: 'Collisions OK.', followUps: []},
  {id: 'r3', topic: 'Rapid', question: 'TreeMap uses hashCode?', answer30s: 'No for structure.', answer2m: 'compareTo/Comparator.', followUps: []},
  {id: 'r4', topic: 'Rapid', question: 'CHM null key?', answer30s: 'Forbidden.', answer2m: 'NPE.', followUps: []},
  {id: 'r5', topic: 'Rapid', question: 'LinkedHashMap equality?', answer30s: 'Same as HashMap.', answer2m: '+ order.', followUps: []},
  {id: 'r6', topic: 'Rapid', question: 'compareTo==0 means?', answer30s: 'Same SortedMap key.', answer2m: 'Replace on put.', followUps: []},
  {id: 'r7', topic: 'Rapid', question: 'Best key type?', answer30s: 'String/wrapper/record.', answer2m: 'Immutable.', followUps: []},
  {id: 'r8', topic: 'Rapid', question: 'HashMap neither override — size a,b,a?', answer30s: '3', answer2m: 'get null.', followUps: []},
  {id: 'r9', topic: 'Rapid', question: 'Both correct — size?', answer30s: '2', answer2m: 'get works.', followUps: []},
  {id: 'r10', topic: 'Rapid', question: 'IdentityHashMap uses equals?', answer30s: 'No — ==.', answer2m: 'Reference identity.', followUps: []},
  {id: 'r11', topic: 'Rapid', question: 'BigDecimal 1.0 equals 1.00?', answer30s: 'false', answer2m: 'compareTo==0; TreeMap collapses.', followUps: []},
  {id: 'r12', topic: 'Rapid', question: 'TREEIFY_THRESHOLD?', answer30s: '8', answer2m: 'OpenJDK HashMap bin treeify hint.', followUps: []},
  {id: 'r13', topic: 'Rapid', question: '+0.0 equals -0.0 for Double?', answer30s: 'false', answer2m: 'Different hashCodes too.', followUps: []},
  {id: 'r14', topic: 'Rapid', question: 'WeakHashMap keys?', answer30s: 'Weak refs — GC can drop.', answer2m: 'Not a general cache.', followUps: []},
  {id: 'r15', topic: 'Rapid', question: 'get+put vs computeIfAbsent?', answer30s: 'Racy vs atomic.', answer2m: 'Prefer computeIfAbsent.', followUps: []},
];

export const ALL = [...SENIOR, ...ARCHITECT, ...RAPID];
