import type {TocItem} from './types';

export const EQHC_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview'},
  {id: 'core', label: '01. Core concepts'},
  {id: 'contract', label: '02. equals / hashCode contract'},
  {id: 'combos', label: '03. All equals × hashCode combos'},
  {id: 'hashmap', label: '04. HashMap deep dive'},
  {id: 'chm', label: '05. ConcurrentHashMap'},
  {id: 'linked', label: '06. LinkedHashMap + LRU'},
  {id: 'treemap', label: '07. TreeMap'},
  {id: 'skiplist', label: '08. ConcurrentSkipListMap'},
  {id: 'hashtable', label: '09. Hashtable'},
  {id: 'identity', label: '10. IdentityHashMap'},
  {id: 'enummap', label: '11. EnumMap'},
  {id: 'records', label: '12. Records as keys'},
  {id: 'eq-vs-cmp', label: '13. equals vs compareTo'},
  {id: 'comparators', label: '14. Comparator corner cases'},
  {id: 'failures', label: '15. Failure scenarios'},
  {id: 'usecases', label: '16. Real-world choices'},
  {id: 'perf', label: '17. Performance matrix'},
  {id: 'exercises', label: '18. Coding exercises'},
  {id: 'cheatsheet', label: '19. Cheat sheet'},
  {id: 'demo', label: '20. Runnable demo'},
  {id: 'interview', label: '21. Interview bank'},
];
