import type {TocItem} from './types';

export const EQHC_TOC: TocItem[] = [
  {id: 'overview', label: '00. Overview'},
  {id: 'core', label: '01. Core concepts'},
  {id: 'contract', label: '02. equals / hashCode contract'},
  {id: 'internals', label: '03. HashMap internals'},
  {id: 'combos', label: '04. All equals × hashCode combos'},
  {id: 'hashmap', label: '05. HashMap deep dive'},
  {id: 'chm', label: '06. ConcurrentHashMap'},
  {id: 'linked', label: '07. LinkedHashMap + LRU'},
  {id: 'treemap', label: '08. TreeMap + NavigableMap'},
  {id: 'skiplist', label: '09. ConcurrentSkipListMap'},
  {id: 'hashtable', label: '10. Hashtable'},
  {id: 'identity', label: '11. IdentityHashMap'},
  {id: 'weak', label: '12. WeakHashMap'},
  {id: 'enummap', label: '13. EnumMap'},
  {id: 'records', label: '14. Records as keys'},
  {id: 'inheritance', label: '15. Inheritance & canEqual'},
  {id: 'mutable', label: '16. Mutable / nested / arrays'},
  {id: 'floats', label: '17. Floating point & BigDecimal'},
  {id: 'nulls', label: '18. Null key/value matrix'},
  {id: 'eq-vs-cmp', label: '19. equals vs compareTo'},
  {id: 'comparators', label: '20. Comparator corner cases'},
  {id: 'replace', label: '21. Key replacement on put'},
  {id: 'lombok', label: '22. Lombok pitfalls'},
  {id: 'jpa', label: '23. JPA entities as keys'},
  {id: 'cache', label: '24. Caching keys'},
  {id: 'serialize', label: '25. Serialization stability'},
  {id: 'failures', label: '26. Failure scenarios'},
  {id: 'usecases', label: '27. Real-world choices'},
  {id: 'perf', label: '28. Performance matrix'},
  {id: 'exercises', label: '29. Coding exercises'},
  {id: 'cheatsheet', label: '30. Cheat sheet'},
  {id: 'demo', label: '31. Runnable demos'},
  {id: 'interview', label: '32. Interview bank'},
];
