import type {TocItem} from './types';

export const KAFKA_CLUSTER_TOC: TocItem[] = [
  {id: 'overview', label: '00. Cluster overview'},
  {id: 'broker-arch', label: '01. Broker architecture'},
  {id: 'threading', label: '02. Threading model'},
  {id: 'kraft', label: '03. KRaft & Raft'},
  {id: 'controller', label: '04. Controller & registration'},
  {id: 'lifecycle', label: '05. Broker lifecycle'},
  {id: 'config', label: '06. Broker configuration'},
  {id: 'listeners', label: '07. Listeners & networking'},
  {id: 'request-path', label: '08. Request processing'},
  {id: 'protocol', label: '09. Wire protocol (broker)'},
  {id: 'topics-parts', label: '10. Topics & partitions'},
  {id: 'replication', label: '11. Replication · ISR · HW'},
  {id: 'election', label: '12. Leader election · epochs'},
  {id: 'reassign', label: '13. Reassignment & balance'},
  {id: 'storage', label: '14. Storage · segments · indexes'},
  {id: 'pagecache', label: '15. Page cache · zero-copy'},
  {id: 'retention', label: '16. Retention & compaction'},
  {id: 'disk', label: '17. Disk architecture & failure'},
  {id: 'failures', label: '18. Failure matrix'},
  {id: 'az-rack', label: '19. Multi-AZ & rack awareness'},
  {id: 'capacity', label: '20. Capacity & scaling'},
  {id: 'quotas', label: '21. Quotas & control plane'},
  {id: 'security', label: '22. Security'},
  {id: 'monitoring', label: '23. Monitoring & alerts'},
  {id: 'ops', label: '24. Ops · upgrade · k8s'},
  {id: 'source', label: '25. Source-level flows'},
  {id: 'chaos', label: '26. Chaos & war games'},
  {id: 'design', label: '27. Production designs'},
  {id: 'interview', label: '28. Interview & cheatsheets'},
];
