import type {TocItem} from './types';

export const SHARD_TOC: TocItem[] = [
  {id: 'overview', label: '500M Transactions Problem'},
  {id: 'vs', label: 'Partitioning vs Sharding'},
  {id: 'range-part', label: 'Range Partition'},
  {id: 'list-part', label: 'List Partition'},
  {id: 'hash-part', label: 'Hash Partition'},
  {id: 'composite', label: 'Composite + Time'},
  {id: 'pruning', label: 'Partition Pruning'},
  {id: 'mysql', label: 'MySQL Partitioning'},
  {id: 'nosql', label: 'NoSQL Keys'},
  {id: 'range-shard', label: 'Range Sharding'},
  {id: 'hash-shard', label: 'Hash Sharding'},
  {id: 'consistent', label: 'Consistent Hashing'},
  {id: 'directory', label: 'Directory / Tenant'},
  {id: 'spring', label: 'Spring Routing DS'},
  {id: 'cross-shard', label: 'Cross-Shard Query/TX'},
  {id: 'reshard', label: 'Resharding'},
  {id: 'hot', label: 'Hot Shard'},
  {id: 'ids', label: 'Global IDs'},
  {id: 'dr-ha', label: 'HA vs DR · RPO/RTO'},
  {id: 'replication', label: 'Replication Types'},
  {id: 'failover', label: 'Failover · Multi-AZ'},
  {id: 'backup', label: 'Backup · PITR · Clone'},
  {id: 'corruption', label: 'Corruption · DELETE'},
  {id: 'shard-dr', label: 'Shard-Level DR'},
  {id: 'spring-failover', label: 'Spring Failover'},
  {id: 'architecture', label: 'AWS Banking Arch'},
  {id: 'decision', label: 'Decision Tree'},
  {id: 'interview', label: 'Interview Mode'},
  {id: 'lab', label: 'Runnable Lab'},
  {id: 'cheat', label: 'Cheat Sheet'},
];
